### ISSUE TITLE
Custom names when uploading multiple files

### ISSUE THREAD

**Issue by ozantunca** [danialfarid/ng-file-upload#100]
I ran into a situation where I had no control over the API I'm using and I didn't want to send files one by one while I can use FormData to send several of them at once. So I needed to send them with the names that the API forces and not with names "file0", "file1" etc.

It would nice to have this customization.

**Comment by reactiongears** [comment]
Is fileFormDataName a possible fix anymore?
We recently upgraded from version 3 to version 10 (I know...). 

I'm trying to do this
Upload
                .upload({
                    headers: headers,
                    url: url,
                    file: file,
                    fileFormDataName: 'document'
                })

But version 10 doesn't respect fileFormDataName.

Please help!

**Comment by danialfarid** [comment]
Replace with `{url:..., data: {document: file}}`

**Comment by reactiongears** [comment]
Thanks Danial!
That worked!
