### ISSUE TITLE
After select valid and invalid files and delete the invalid files, the model of form is not update properly.

### ISSUE THREAD

**Issue by romelgomez** [danialfarid/ng-file-upload#1000]
I made a jsfiddle and video to describe the issue. Please see the video first.  

Code: https://jsfiddle.net/venezuela/y1ujht5a/
Video: https://youtu.be/Ewkcya5qbfI

After select some valid and invalid files, then deleting the invalid files, the model of the form still kept the error reference of the invalid files.     

Any idea what is happening here?

PD: It is a great directive. Thanks.

**Comment by romelgomez** [comment]
The test files i used are this: 

https://drive.google.com/folderview?id=0B48Iw3KfwRLwa1lLTTYwa1VkdzQ&usp=sharing

**Comment by danialfarid** [comment]
Add 
```
        $scope.model.files = $scope.model.files.slice(0);
```
after line 38 of jsfiddle.
calling splice on the array will not trigger a model change since the model value is still the same array, to force the validation chain you need to change the value of the model object which is in this case could be making a copy of the files array.

**Comment by romelgomez** [comment]
Many Thanks, Danial, that is a great solution.     

After see your idea, i remember that to reset array or object, i need make use of a copy of those, so then, after see this answer in stackoverflow:  http://stackoverflow.com/a/22160628/2513972  , give me other ideas on how tackle this issue:  

    $scope.removeFile = function (fileIndex) {
        $scope.model.files = $filter('filter')($scope.model.files, function(value, index) { return index !== fileIndex;});        
    };
 
I make other jsfiddle with this changes:  https://jsfiddle.net/venezuela/atpaz7w7/  

As we see in the stackoverflow answer, the $filter It can be used in many ways, so i go for this solution.  

Many Thanks.
