### ISSUE TITLE
Cordova , local file blobUrl malformed  ( : as %3A) 

### ISSUE THREAD

**Issue by dansanti** [danialfarid/ng-file-upload#1001]
Hi ! when i try to upload some file from cordova app, (it's  use local url ( file : ///)),  for some reason blobUrl's (:) was parsed as %3A, causing can't load preview and upload file : 
"blobUrl":"blob:file%3A///file_name"

**Comment by danialfarid** [comment]
hmm strange. For the workaround set `ngf-no-object-url="true"` on your ngf-src preview element.

**Comment by dansanti** [comment]
HI! if you see here http://wecare.idodidev.eu/www/#/app/registro_propietario ,  when you select a file,you can get a preview file and when fill the form i can get the img too, but this same code is on a cordova project (using local ), and you don't get a preview file and can't upload..

Then, after ost form i put a log, and noticed that on web (using firefox android) work fine , but on local (using cordova) don't work and blobUrl was  %3A in cordova

i tried with ngf-no-object-url="true" , and get an empty space, and can't upload file.

**Comment by danialfarid** [comment]
Try posting the issue on cordova project then if it is working in one platform but not the other it is probably because of the way cordova compiles the code for tthat platform.

**Comment by dansanti** [comment]
ok, i fix it adding cordova file plugin cordova plugin add cordova-plugin-file
I don't know if because, this plugin add permissions, or complement native file api
