### ISSUE TITLE
Upload files on background

### ISSUE THREAD

**Issue by CrackerakiUA** [danialfarid/ng-file-upload#1002]
I am using nodejs as server. I am using multiple files upload. When they start to upload page don't get other requests from the server. That matter is on nodejs or pluggin option?

**Comment by danialfarid** [comment]
It is probably from nodejs since it is single threaded. This plugin sends files in an asynchronous request so it shouldn't block anything.

**Comment by danialfarid** [comment]
Reopen if you find otherwise.
