### ISSUE TITLE
No success response on IE9

### ISSUE THREAD

**Issue by nettz** [danialfarid/ng-file-upload#1003]
While the Fileupload is successful, i wont get any response back to the js what so ever.
My Server will response with 200 success text/plain (i changed it from 201 created to be sure thats not the problem) and i can see the response of my post in the networking tab of the development tools.
Still i dont get anything further from the upload function. no progress, success, error.

Any ideas?
Cheers

**Comment by danialfarid** [comment]
Hard to say, create a jsfiddle.
Your server needs to have a response body, empty response might cause some issues.

**Comment by nettz** [comment]
My Server got a response body. In fact as i say i can see the Response of the post in the networking tab but i dont get any success, then, finally or what so ever.
I also read an old issue that i should load the shim before angular.js which i do.
Its like the flash dosent call back to the js.

**Comment by danialfarid** [comment]
Are you sure it is sending the file using flash? What networking tab are you using? If it is sending it as XMLHttpRequest then it won't be a flash call.
You can put a breakpoint here and verify that the flash is being called and the response is coming from the flash:
https://github.com/danialfarid/ng-file-upload/blob/master/dist/ng-file-upload-shim.js#L100
https://github.com/danialfarid/ng-file-upload/blob/master/dist/ng-file-upload-shim.js#L189

**Comment by nettz** [comment]
You are right, it really wasnt a flash call.
The reason for it was that my dev webserver dident was set up to server flash(swf) files. doh!

Thanks for your work
