### ISSUE TITLE
File size validation issue

### ISSUE THREAD

**Issue by SteveFidel** [danialfarid/ng-file-upload#1004]
Hi,

I've got a weird bug when using ngf-min-width & ngf-min-height.

I have set the following ngf-min-width="850" ngf-min-height="210" value. When I drag a file (which is 800x533), the file pass the validation and I end up with the following results:

blobUrl: "..."
height: 732
name: "sample.jpg"
size: 94400
type: "image/jpeg"
webkitRelativePath: ""
width: 1099

The files[0] value doesn't return me the correct photo size. Seem to kind of zoom it as it's still the correct file ratio.

Can someone help me on this?

**Comment by danialfarid** [comment]
Can you attach your image here.

**Comment by SteveFidel** [comment]
Yep, here's the file that give me the above result.

Thanks

![sample](https://cloud.githubusercontent.com/assets/7115461/9862450/f54960b8-5b06-11e5-8a5e-a3e02fffba3b.jpg)

**Comment by danialfarid** [comment]
The size of this file is "width":800,"height":533 so if you change the min-width from 850 to 800 it would be uploaded successfully on the demo page.

**Comment by SteveFidel** [comment]
Thanks @danialfarid.

Can you also tell me why in my initial post ng-file-upload was returning me a width of 1099px instead of the real 800px width of the photo?

That was mostly my problem.

**Comment by danialfarid** [comment]
I don't think that would ever happen, if you can reproduce it let me know.

**Comment by SteveFidel** [comment]
Ok thanks alot.
