### ISSUE TITLE
Got error when upload a file with its name containing full width characters

### ISSUE THREAD

**Issue by kevinleeTCA** [danialfarid/ng-file-upload#1006]
When I upload a file, say its name is 'UI。。。.png' containing full width character of '。'
then I got an error:

 Error: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': 'attachment; filename=UI。。。.png' is not a valid HTTP header field value.
    at Error (native)

The version: "ng-file-upload": "~4.2.4",
This error only occurred when I upload a file on chrome. Works all right on Safari.

**Comment by danialfarid** [comment]
Can you post the fill stack trace and attack your file here?

**Comment by kevinleeTCA** [comment]
Thank you very much for your comment.
I solve this problem by encodeURIComponent(fileName), then it works
Since the XMLHttpRequest does not allow unicode character.

The error occurred code segment, 
```javascript
Upload.http({
                url: trunkFile.upload_url,
                headers: {'Content-Type': file.type, 'Content-Disposition': 'attachment; filename=' + encodeURIComponent(file.name)},
                method: 'PUT',
                data: file
            })
```
I just add `encodeURIComponent` (supported by most browsers ) to the code, then all works fine now
