### ISSUE TITLE
Validate only last files when ngf-keep="true

### ISSUE THREAD

**Issue by derwu** [danialfarid/ng-file-upload#1007]
When `ngf-select` `ngf-keep="true"` `ngf-multiple="true"` (and `ngf-max-size="3MB"` with upload on submit) and I add invalid file/files (maxSize exceeded in my case) files model is invalid (correctrly), but if next I add a valid file/files, then files model is valid (incorrectly). This seems to be incorrect, beceause in files model still is invalid file/files waiting to upload.

**Comment by derwu** [comment]
I updated ng-file-upload to recent version the problem seems to be fixed. Issue to close.

**Comment by madurapa** [comment]
This issue is still exist as I'm using 12.0.1

**Comment by danialfarid** [comment]
When you set the ng-model value it will replace everything including the invalid files, so if you want it to persist the invalid files, add them to the ng-model variable before setting it.

**Comment by madurapa** [comment]
I'm sorry but I didn't get you. I added "ngf-keep" to keep the files I have been already chosen but when I add an invalid file it validates as should be but if I added a valid file again it doesn’t validate as it should be.

**Comment by madurapa** [comment]
I guess screenshots might help to understand the issue 

- In here I have selected valid and invalid files together and it validates correctly. ![step-1](https://cloud.githubusercontent.com/assets/4289578/13140672/6d22db14-d659-11e5-9f66-6a2819a8319f.png)

- Then again I have select a valid file and validation has been gone. ![step-2](https://cloud.githubusercontent.com/assets/4289578/13140671/6cdc09a0-d659-11e5-8fb2-6170c929ffe6.png)

**Comment by madurapa** [comment]
Hi @danialfarid 

There are couple of bugs I have found while testing. Will post them soon.

Thanks

**Comment by jar240** [comment]
"Me too". Assume I have:
<button ... ngf-max-files="5" ngf-keep="distinct" (or true) ...>

...if I try to select 6 files, the validation kicks in and works. The issue is, when I click the button again to reselect 5 or less files, the validation hasn't been cleared -- still invalid.

If I set ngf-keep="false", everything works as expected; the problem is, this behaviour is undesirable in my case.

Chris

**Comment by danialfarid** [comment]
@jar240 you need to reset the ng-model to empty if you want to remove those files. Removing them from ngf-invalid-model will not trigger any validation, you need to set the ng-model to empty array or whatever files are left there.

**Comment by jar240** [comment]
@danialfarid an example would be stellar. The timing isn't clear to me... In my mind, this should be taken care of by ng-file-upload when the upload button is clicked a second (third, fourth, etc. time).

Otherwise how would I implement this in a sensible way?

Thanks,
Chris

**Comment by madurapa** [comment]
@danialfarid is it possible to handle all valid and invalid files in a single model with a flag `invalid` then maybe set what is/are the reason(s) for invalid with another or in the same object. Like `invalid extension`, `max file size`, or 'max file count', etc. I think it would be better to attached error with each file object and as a global error array too. Then we can handle everything at one place.

We could also implement remove method inside the directive so then it will be easy to change valid/invalid states in the model.

**Comment by danialfarid** [comment]
@madurapa It is already attached to each file, just set `ng-model-options="{allowInvalid: true}"` to get all files with their error reason etc. '$error` and `$errorParam` it is mentioned in the docs.

**Comment by madurapa** [comment]
I've missed that option, It makes life easier ;)

**Comment by danialfarid** [comment]
fixed at version 12.0.3
