### ISSUE TITLE
Hidden input is being removed when manually compiling the directive inside a modal.

### ISSUE THREAD

**Issue by georgesboris** [danialfarid/ng-file-upload#1008]
Sorry I did not have the time to replicate the issue on a jsfiddle yet.

But what happens is that when I manually $compile the directive inside a modal (like tooltipster) everything is working as expected, except that the hidden input is picked up by the method I will paste below, and so it is removed, preventing the files to be correctly picked up.

When I comment this everything works wonderfully. I did not fully comprehend the intent on this method... Should the directive work normally without it or will it cause a memory leak?

The method is this one:
```
      $timeout(function () {
        for (var i = 0; i < generatedElems.length; i++) {
          var g = generatedElems[i];
          if (!document.body.contains(g.el[0])) {
            generatedElems.splice(i, 1);
            g.ref.remove();
          }
        }
      }); - line 536 as of 7.2.1
```

thank you.

**Comment by danialfarid** [comment]
That is to remove previously detached generated elements. 
Is this happening on Chrome? If you could create a jsfiddle or sample that would be great it might be a bug and would help others too.

Removing that should be fine as long as you don't add too many ngf-select or drop elements. The side effect is not used hidden input files. So it is kind of a memory leak but won't have any issues in most common uses of this plugin.

**Comment by danialfarid** [comment]
Did you figure out why the hidden input is not contained in the document? this check ` if (!document.body.contains(g.el[0])) {` should pass for the element to be removed which is checking if that element is inside the document's body.

**Comment by georgesboris** [comment]
The element was being cloned by the modal that I mentioned (tooltipster) and that was messing with the setup of your directive. I apologise for taking so long to notice that. Fixed the unexpected cloning and now everything is working as expected. Thank you.
