### ISSUE TITLE
ng-file-upload with multer, success not called, and upload called repeatedly

### ISSUE THREAD

**Issue by wisdomry** [danialfarid/ng-file-upload#1012]
I'm using ng-file-upload to upload an image to a node/express server from an  Angular client. 

The image is being loaded, however the 'success' method is not being called and the image upload seems to be called multiple times, causing the image to be repeatedly uploaded to the server.

Here's my HTML form:

    <form accept-charset="UTF-8" ng-submit="uploadPic(picFile)" name="myForm">

                <br>Photo:
                <input type="file" ngf-select ng-model="picFile" ngf-multiple="false" name="file" accept="image/*" ngf-max-size="2MB" required />
                <br>

                <i ng-show="myForm.file.$error.maxSize">File too large {{picFile.size / 1000000|number:1}}MB: max {{picFile.$errorParam}}</i>

                <img ng-show="myForm.file.$valid" ngf-src="!picFile.$error && picFile" class="thumb">
            
                <br>

                <button class="btn btn-info" type="submit">Submit</button>
                <span class="progress" ng-show="picFile.progress >= 0">
                  <div style="width:{{picFile.progress}}%" ng-bind="picFile.progress + '%'" class="ng-binding"></div>
                </span>
                <span ng-show="picFile.result">Upload Successful</span>
            </form>

Here's my JS:

        $scope.uploadPic = function (file) {

            file.upload = Upload.upload({
                url: '/uploads',
                method: 'POST',
                fields: {
                    username: $scope.username
                },
                file: file,
                fileFormDataName: 'photo'
            });

            file.upload.then(function (response) {
                console.log("Postcontroller: upload then ");
                $timeout(function () {
                    file.result = response.data;
                });
            }, function (response) {
                if (response.status > 0)
                    $scope.errorMsg = response.status + ': ' + response.data;
            });

            file.upload.progress(function (evt) {
                // Math.min is to fix IE which reports 200% sometimes
                file.progress = Math.min(100, parseInt(100.0 * evt.loaded / evt.total));
                console.log("PostController: upload progress " + file.progress);
            });

            file.upload.success(function (data, status, headers, config) {
                // file is uploaded successfully
                console.log('file ' + config.file.name + 'is uploaded successfully. Response: ' + data);
            });
        }

Here's my server side code:

    var multer = require('multer');
    var upload = multer({ dest: './public/images'});

    router.post('/uploads', upload.single('file'), function(req,res,next){
      console.log("Server: got file ");
    });

I read somewhere that the shim library must be included first, but I've tried swapping the load order and no joy. Here are my import lines:

     <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
   
    <script src="/lib/ng-file-upload/ng-file-upload-shim.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>
    <script src="/lib/ng-file-upload/ng-file-upload.min.js"></script>
    
    <script src="//cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.2.13/angular-ui-router.js"></script>

Also, looking in the Chrome debug tools - the upload shows a status of 'pending'. The image is definitely on the server and the progress bar (in the html) shows 100%. Yet, a minute or so later, another copy of the image appears in the folder (this behaviour seems to loop) and the ng-file-upload 'success' event is never called.

Grateful for help.

**Comment by wisdomry** [comment]
Sorry, just saw your reply on stackoverlow:

http://stackoverflow.com/questions/32634793/ng-file-upload-with-multer-success-not-called-and-upload-called-repeatedly

Will maintain the thread there.

**Comment by NobodyLR** [comment]
same problem
