### ISSUE TITLE
Overwriting the aHrefSanitizationWhitelist

### ISSUE THREAD

**Issue by liamkeaton** [danialfarid/ng-file-upload#1014]
It seems your overwriting the global aHrefSanitizationWhitelist to be more accepting to files which has meant that other link protocols such as mailto: have been broken.

**ng-file-upload overwrite**
```
/^\s*(https?|ftp|local|file|data|blob):/
```

**angular default**
```
/^\s*(https?|ftp|mailto|tel|file):/
```

A better way to append the new whitelist should be found perhaps just allowing for mailto and tel protocols.

**Suggestion**
```
/^\s*(https?|ftp|mailto|tel|file|data|blob):/
```

**Comment by danialfarid** [comment]
Fixed at version 7.2.2

**Comment by liamkeaton** [comment]
Thank you!

**Comment by koto** [comment]
This was reverted in https://github.com/danialfarid/ng-file-upload/commit/9f5c4697bc5fa6b3f84bcfd3292b00053615e679. ngFileUpload does overwrite the whitelists, which creates an [XSS risk](https://paladion.net/bypass-xss-filters-using-data-uris/) for its users (data: protocol is on the whitelist).

**Comment by koto** [comment]
Hey, any update on this? Why was the change reverted?
