### ISSUE TITLE
Custom key for files

### ISSUE THREAD

**Issue by mrsweaters** [danialfarid/ng-file-upload#1015]
Is there a way to pass a custom key to `addFileToFormData`?
https://github.com/danialfarid/ng-file-upload/blob/master/src/upload.js#L194

I would like to be able to set it based off of the file index like so:
```
addFileToFormData(formData, config.file[i], 'upload[files]['+i+']');
```

**Comment by danialfarid** [comment]
You can have: 
```
Upload.upload({...
  file: {'upload[files][` + i + ']': files[i]},
  ...
}) 
```

**Comment by mrsweaters** [comment]
@danialfarid Thanks!
