### ISSUE TITLE
ngf-pattern not working

### ISSUE THREAD

**Issue by MrOutput** [danialfarid/ng-file-upload#1016]
Hey Danial,

I tried ngf-pattern="'image/*'" and I am able to upload powerpoint files, I also set the accept to the same constraint. But if the user selects all files in the poput, non images are still allowed through, I also set ngf-validate-force=true. Any ideas?

Thank you!

*also your donate link is broken

**Comment by danialfarid** [comment]
Can you create a plunkr or jsfiddle?

**Comment by MrOutput** [comment]
Hey Danial,

I set my $scope.upload() to set $scope.images = $files because ng-model isn't working, I think because I am not using an explicit input field...anyway now my $scope.images[] is resetting to null each time I put images. This happened after upgrading from 7.3.0 to 7.3.2. Before $files would keep all the files, Any ideas?

**Comment by danialfarid** [comment]
The `ngf-pattern` is working on the demo page, you could compare your code with that. 7.3.0 had a bug that would make `ngf-keep` enabled by default. Whenever you click on the input the model values will be reset to empty unless you set `ngf-keep="true"`

**Comment by MrOutput** [comment]
okay, thank you! I will set to ngf-keep="true". I verify and close issue if was my fault. Thanks again!

**Comment by MrOutput** [comment]
for ngf-keep I ran into an issue if it was ngf-keep=true, rather than ngf-keep='true'. Later on, can you please add support for both bool and string. This helps keep things HTML5 compliant. Also, it looks like  ngf-pattern is working because I have $error in the file object. However, shouldn't validate-force="true" disallow them from entering the $files[]?

**Comment by danialfarid** [comment]
ngf-validate-force="boolean" // default false, if true file will be rejected if the dimension or duration
              // values for validations cannot be calculated for example image cannot load or unsupported video by browser

**Comment by MrOutput** [comment]
I read that, but I put it to true, and still files with $error are getting by :(

**Comment by danialfarid** [comment]
oh rejected here means the $error will be set on them I will update the doc

**Comment by MrOutput** [comment]
ah, okay, so I am guessing that I will have to manually filter out file objects from $files[] with $error? My understanding, was that ngf-validate-force="true", should filter this for you. if i made pull request would you merge?

**Comment by MrOutput** [comment]
I would think that forcing validation would just filter objects with $error present in the $files[]

**Comment by MrOutput** [comment]
##### Sample Filter

```javascript
var filter_invalid_files;

$scope.upload = function(files) {
  return $scope.images = filter_invalid_files(files);
};

filter_invalid_files = function(files) {
  var file, i, len, tmp_array;
  tmp_array = [];
  for (i = 0, len = files.length; i < len; i++) {
    file = files[i];
    if (!file.hasOwnProperty('$error')) {
      tmp_array.push(file);
    }
  }
  return tmp_array;
```

**Comment by danialfarid** [comment]
Do you have a usecase scenario that you just want the files without error? Normally you would wanna show the user what error each file has so a list of all files should work.

**Comment by MrOutput** [comment]
I understand what you're saying and the use case of keeping the file and the error. But what I am specifically talking about is that  `ngf-validate-force='true'` should filter invalid files. It just makes sense in my opinion.

**Comment by MrOutput** [comment]
Hey Danial, you can close this issue, also Upload.upload is sending an empty request payload. I am not sure why.

![screenshot from 2015-09-20 17-10-49](https://cloud.githubusercontent.com/assets/8491687/9983210/92a273a6-5fba-11e5-81a2-4d3041d8d1c6.png)

**Comment by danialfarid** [comment]
It is not empty the browser dev tool doesn't show the contents.

**Comment by MrOutput** [comment]
ah okay, thanks! Just that multiparty is not triggering a file event so I am suspecting that no files are getting sent over.

**Comment by danialfarid** [comment]
Added `ngf-valid-only` directive to version 8.0.1 which would assign only the valid files to the model.

**Comment by MrOutput** [comment]
sweet! thank you!
