### ISSUE TITLE
fileFormDataName has no functionality since version 7.2.0

### ISSUE THREAD

**Issue by stelboe** [danialfarid/ng-file-upload#1020]
from version 7.1.0 to 7.2.0 fileFormDataName disappeared and my running application crashed from one day to another 

is there an alternative I missed in the documentation or have you removed this feature?

**Comment by danialfarid** [comment]
See the release notes links at the beginning of the home page.
It is removed and the alternative is to use maps, see the docs.

**Comment by stelboe** [comment]
already found it, I still think adding a functionality is a better way than replacing it
- thank you for the tipp
