### ISSUE TITLE
Use revokeObjectUrl

### ISSUE THREAD

**Issue by bogdanalexe90** [danialfarid/ng-file-upload#1021]
Hi,

I plan to use your component and heavy rely on the objectUrl. I searched in your code but i din't saw memory reclaim for `createObjectUrl`s. Maybe this article can help:

https://developer.mozilla.org/en-US/docs/Web/API/URL/revokeObjectURL

**Comment by danialfarid** [comment]
Any suggestion on when it should be revoked?

**Comment by danialfarid** [comment]
fixed in version 7.3.7

**Comment by bogdanalexe90** [comment]
I was thinking to do some clean up when you change the file since you have access to the prevoius one. But one can reference it from outside and can lose the url.

**Comment by danialfarid** [comment]
In this version all previous files will be revoked upon selecting files or dropping files. I think this should be enough for most cases. Is there a scenario that this could cause problem?
