### ISSUE TITLE
Certain File types do not work with ngf-pattern

### ISSUE THREAD

**Issue by belal-m** [danialfarid/ng-file-upload#1023]
Hi, 

Apologese if this is not a issue and its just me not being able to get this working correctly. But recently looking at the documentation we are able to use the "ngf-drag-over-class" to allow for css changes of the drop box if the file type is not what specified in the ngf-pattern. How ever i have noticed a few issues with this. 

I have specified in ngf-pattern to only allow .png file types, and in the ngf-drag-over-class i have specifed on accept to change the border colour to blue and on reject to apply red. How ever even though i am dragging a .png file into the drop box it changes colour to red. I have managed to get this working by instead of saying ngf-pattern="'.png'" i use ngf-pattern="'image/png'". However the issue with this after testing is that it allows jpeg images to also turn the colour of the drop box to blue when it shouldnt. Can you please advise what is the issue. Below is the code. 

div class="uploadArea" ngf-drop ngf-select ng-model="files" ngf-drag-over-class="{accept: 'dragover', reject: 'dragover-err', delay:1}" ngf-multiple="true" accept=".png" ngf-pattern="'.png'"

**Comment by danialfarid** [comment]
The .jpg image file is probably not a real jpg file it is probably png file with .jpg extension. This is working for me rejecting jpeg files: http://jsfiddle.net/danialfarid/zz52nzqv/
As it is stated in the docs the drag-over-class only works on file mime type for Chrome.

**Comment by danialfarid** [comment]
in version 8.0.1 you can specify the pattern option inside ngf-drag-over-class: `ngf-drag-over-class="{accept: 'dragover', reject: 'dragover-err', pattern:'image/*'}`
