### ISSUE TITLE
fileFormDataName seemingly ignored

### ISSUE THREAD

**Issue by adambuczynski** [danialfarid/ng-file-upload#1024]
On my local machine, when I specify the config option `fileFormDataName` with a value of `logo`, I get the following request sent to the server:

```
------WebKitFormBoundary595YPR0mPFV4GX4r
Content-Disposition: form-data; name="logo"; filename="avatar_2.jpg"
Content-Type: image/jpeg
------WebKitFormBoundary595YPR0mPFV4GX4r--
```

As you can see, the file name is correctly `logo`.

However, after deploying the exact same code in another environment, the config option is suddenly ignored, and it reverts back to `file`:

```
------WebKitFormBoundaryO2geiLg6gk2TFUst
Content-Disposition: form-data; name="file"; filename="avatar_2.jpg"
Content-Type: image/jpeg
------WebKitFormBoundaryO2geiLg6gk2TFUst--
```

Any idea what could be happening here? The only difference is that the code is being minified, but it's still passing the correct config option to the uploader:

```js
o.upload({
  url: l.api.baseUrl + "organisation/logo",
  file: n,
  fileFormDataName: "logo"
  }).then(...)
```

**Comment by danialfarid** [comment]
It's been deprecated since version 7.2.0. read the Migration notes at the beginning of the docs.

**Comment by adambuczynski** [comment]
I find this a really strange update to be honest, having to put both the key and filename in the key of the object. That's a really ugly way of passing configuration parameters. Why didn't you leave the old parameters in for backwards compatibility? Shouldn't breaking changes be reserved for major versions, or aren't you using semantic versioning?

**Comment by danialfarid** [comment]
I agree I should have bumped the major version.
Version 8.0.1 now has those stated in the release notes and with samples 
The reason behind it is to simplifying how you specify the files and keys. It makes it more intuitive to specify them as key value inside data. Also added Upload.rename(file, newName) function to avoid using the key,filename split syntax. Also keeping the old functionality will make the code that deals with adding them to the form data more complicated and migrating to using data should be very easy and make the code simpler/shorter.

**Comment by adambuczynski** [comment]
Alright, thanks for the clarification. I will check out Upload.rename.
