### ISSUE TITLE
extension .tar.gz does not work in mac

### ISSUE THREAD

**Issue by guy-mograbi-at-gigaspaces** [danialfarid/ng-file-upload#1025]
I placed `accept=".tar.gz,.tar,.tgz,.zip"`

and it seems that in mac only, all types are identified properly except for `.tar.gz` 

if I use `.gz` it works - but that's an incorrect solution to the problem.

**Comment by danialfarid** [comment]
Accept is standard html attribute and is browser implementation dependent, there is not much to do about it other than googling it to find a workaround for that specific browser.

**Comment by guy-mograbi-at-gigaspaces** [comment]
thanks, added a question in SO - http://stackoverflow.com/questions/32788178/html-accept-in-mac-ignores-tar-gz-extension
