### ISSUE TITLE
Set form element as $dirty on model change

### ISSUE THREAD

**Issue by bogdanalexe90** [danialfarid/ng-file-upload#1029]
Call `$setDirty()` on each model change (add/change/remove). 

This can be achieved right now by hooking into `ngf-change ` but it will be nice to be supported by default.

**Comment by danialfarid** [comment]
Why is it necessary?

**Comment by bogdanalexe90** [comment]
I have some business logic around formController. 
I mean i want to show the validation only when the user touched the control. It will be logic that the control to become `$dirty` once the user interacted with it.

Have a look here:
https://docs.angularjs.org/api/ng/type/ngModel.NgModelController#$setDirty

**Comment by danialfarid** [comment]
fixed at 8.0.5
