### ISSUE TITLE
Nested data value/object appears as string on server (rails 3.2 backend)

### ISSUE THREAD

**Issue by ryanemmm** [danialfarid/ng-file-upload#103]
Hi I have a question regarding how the data field is encoded when it's sent.

```
$upload.upload(({
    url: myurl,
    method: mymethod,
    data: {myobj: $scope.myobj},
    file: myfile
})
```

When this request fires I expect to see (rails 3.2 backend):

```
params["myobj"] => {"prop1" => "prop1value", "prop2" => "prop2value", ...}
```

But I get:

```
params["myobj"] => "{\"prop1\":\"prop1value\", "\prop2\":\"prop2value\",...}"
```

I'd like to avoid having to JSON.parse params["myobj"] in the rails controller.

Is there a setting I can flip to change the way the data property/object is encoded/stringified?

If I'm doing something incorrectly, let me know ;)

**update**
Looking into this some more, it appears that $upload.upload is sending the request with Content-Type = multipart/form-data; not application/json.

The combination of JSON data + multipart/form-data causes params["myobj"] to be a "flat" string representation of the rest of the data; losing the nesting that I expected.

Would it be possible to change the way data gets encoded in $upload.upload to be compatible with multipart/form-data?

**Comment by pimpin** [comment]
An other solution we used : 

```javascript
    fields: {
          'item[title]': $scope.item.title,
          'item[description]': $scope.item.description,
    },
    file: $scope.files,
    fileFormDataName: ['item[picture_01]', 'item[picture_02]', 'item[picture_03]']
```
