### ISSUE TITLE
ngf-drag-over multi browser

### ISSUE THREAD

**Issue by HoplaGeiss** [danialfarid/ng-file-upload#1031]
Hello, by default when a file / folder is dragged over my window, the class `dragover` is added.

However, when I specify  `ngf-drag-over-class="{accept:'dragoverAccept', delay:100}"`, it doesn't work.

Ok it works well on Chrome, `dragoverAccept` is added.
But other browsers don't support `accept`, which is fine. ( so my class `dragoverAccept` won't appear.)
But in this case even the default class `dragover` doesn't appear.

How can I solve this ?

**Comment by danialfarid** [comment]
Fixed in version 8.0.2
