### ISSUE TITLE
Show error message

### ISSUE THREAD

**Issue by Duovili** [danialfarid/ng-file-upload#1033]
Is there a way to show error messages if the file exceeds the file size? and maybe any other validations that aren't met?

**Comment by danialfarid** [comment]
Yes see the first jsfiddle sample and demo page they both do that.

**Comment by Duovili** [comment]
There are no error messages displaying it just stops the file being uploaded

**Comment by danialfarid** [comment]
http://jsfiddle.net/danialfarid/maqbzv15/14/ select a file larger than 2MB
