### ISSUE TITLE
Upload images to firebase on form submit

### ISSUE THREAD

**Issue by SaidThaher** [danialfarid/ng-file-upload#1034]
I'm building a small web app (blog post alike) using AngularJs and Firebase. i implemented the addPost controller earlier and it worked good. After i wanted to add an input file inside the form which already implemented to upload images to firebase on form submit using ng-file-upload directive . As a new in angular i knew that firebase can save images as base64 but i couldn't figur out how to make it work. Maybe some will say that its repeated question, but believe me i searched allover here i couldent find answer.
Here is my form file :

<div class="container" ng-controller="AddPostCtrl">

        <form class="form-horizontal" ng-submit="AddPost(files)">
            <fieldset>

                
                <legend>Create Post</legend>

                
                <div class="form-group">
                    <label class="col-md-4 control-label" for="txtTitle">Title</label>
                    <div class="col-md-4">
                        <input id="txtTitle" name="txtTitle" ng-model="article.title" type="text" placeholder="placeholder" class="form-control input-md">

                    </div>
                </div>

                
                <div class="form-group">
                    <label class="col-md-4 control-label" for="txtPost">Post</label>
                    <div class="col-md-4">
                        <textarea class="form-control" id="txtPost" ng-model="article.post" name="txtPost"></textarea>
                    </div>
                </div>

                
                <div class="form-group">
                    <label class="col-md-4 control-label" for="pictures">Add Pictures</label>
                    <div class="col-md-4">
                        <input id="pictures" type="file" ngf-select ng-model="files"  name="file"    
                          accept="image/*" ngf-max-size="2MB" ngf-multiple="true" ngf-keep="true" ngf-keep-distinct="true" class="btn btn-primary"/>
                
                        <span ng-repeat="file in files">
                           <img ngf-thumbnail="!file.$error && file" class="thumb"> <button class="btn btn-danger" ng-click="file = null" ng-show="file">Remove</button>
                        </span>
                    </div>
                </div>

                
                <div class="form-group">
                    <label class="col-md-4 control-label" for="singlebutton"></label>
                    <div class="col-md-4">
                        <input id="singlebutton" ng-disabled="!article.title || !article.post" name="singlebutton" class="btn btn-primary" type="submit" value="Publish" />
                    </div>
                </div>

            </fieldset>
        </form>

    </div>

here is my controller :

angular.module('myApp.addPost', ['ngRoute'])

.controller('AddPostCtrl', ['$scope','CommonProp','$firebase','$location','Upload','$timeout', function($scope,CommonProp,$firebase,$location,Upload,$timeout) {
    if(!CommonProp.getUser()){
    $location.path('/main');
    }

    /***** Add data to firebase *****/
    $scope.AddPost = function(files) {
            var fb = new Firebase("https://hotelboard.firebaseio.com/Articles/");

            var title = $scope.article.title;
            var post  = $scope.article.post;
            var user  = CommonProp.getUser();
            var images = $scope.file ;
            fb.push({
                title:     title,
                post:      post,
                emailId:   user,
                images : images,
                '.priority': user

            },function(error) {
                if (error) {
                    console.log("Error:",error);
                } else {
                console.log("Post set successfully!");
                console.log($scope.file);
                $location.path('/home');
                $scope.$apply();

            }

        });

    }

}]);

and here is my GitHub for full project files

https://github.com/SaidThaher/HotelApp

If i get help with this issue , it will be more question regards to the result. PLEASE HELP

**Comment by danialfarid** [comment]
Upgrade to 8.0.6 and move your fb push here:
```
Upload.base64DataUrl(files).then(function(base64Urls) {
  fb.push({...
            images : base64Urls,
        },...
});
```

**Comment by SaidThaher** [comment]
@danialfarid Thank you very much,, worked like charm.

**Comment by SaidThaher** [comment]
Hi again.
I try to implement if statement if the user not choose file it will send null to firebase which mean nothing will pushed for images . the first part where files==undefined worked, but i couldent get the base64Urls from the function and save it to images to push it to firebase: 

'use strict';
 
angular.module('myApp.addPost', ['ngRoute'])
 
.controller('AddPostCtrl', ['$scope','CommonProp','$firebase','$location','Upload','$timeout', function($scope,CommonProp,$firebase,$location,Upload,$timeout) {
	if(!CommonProp.getUser()){
    $location.path('/main');
	}
	/***** Add data to firebase *****/
	$scope.AddPost = function(files) {
			var fb = new Firebase("https://hotelboard.firebaseio.com/Articles/");
			var images ;

			if (files == undefined){
				 images = null;
				 console.log(files);
				console.log(images);
			}else{
				
				images = Upload.base64DataUrl(files).then(function(base64Urls){
					images = base64Urls;
				})

			}
				console.log(files);
				console.log(images);
			
			
			var title = $scope.article.title;
			var post  = $scope.article.post;
			var user  = CommonProp.getUser();
			//var images = Upload.base64DataUrl(files).then(function(base64Urls){
			fb.push({
				title:     title,
				post:      post,
				emailId:   user,
				images : images,
				'.priority': user
				
			},function(error) {
				if (error) {
					console.log("Error:",error);
				} else {
				console.log("Post set successfully!");
				$location.path('/home');
				$scope.$apply();
			
			}
				
		});

	//});
//}
	}
 
}]); 


in the second log after files been selected i got this results and errors:

[File]0: Filelength: 1__proto__: Array[0]
addPost.js:28 Promise {$$state: Object}$$state: Object__proto__: Promise
angular.js:12416 Error: Firebase.push failed: first argument  contains an invalid key ($$state) in property 'Articles.images'.  Keys must be non-empty strings and can't contain ".", "#", "$", "/", "[", or "]"
    at Error (native)
    at http://localhost:8000/app/bower_components/firebase/firebase.js:130:18
    at ib (http://localhost:8000/app/bower_components/firebase/firebase.js:20:569)
    at Wf (http://localhost:8000/app/bower_components/firebase/firebase.js:129:424)
    at http://localhost:8000/app/bower_components/firebase/firebase.js:130:166
    at ib (http://localhost:8000/app/bower_components/firebase/firebase.js:20:569)
    at Wf (http://localhost:8000/app/bower_components/firebase/firebase.js:129:424)
    at Vf (http://localhost:8000/app/bower_components/firebase/firebase.js:128:438)
    at U.push (http://localhost:8000/app/bower_components/firebase/firebase.js:252:102)
    at Scope.$scope.AddPost (http://localhost:8000/app/js/addPost.js:35:7)(anonymous function) @ angular.js:12416ident.$get @ angular.js:9203parent.$get.Scope.$apply @ angular.js:15983(anonymous function) @ angular.js:23376eventHandler @ angular.js:3293

**Comment by kodfocus** [comment]
Hey guys, i have my image in firebase, but how i can decoded to show it in my view, i have this in Firebase:

- myNode
    - -K6Z1dsT7Ha9t-m20NXL
       - images
           - 0: "data:image/jpeg;base64,/9j/4Ru+RXhpZgAATU0AKgAA..."

in my view i have:
<div ng-repeat="p in myNodes">
<img data-ng-src="data:image/jpeg;base64,{{ p.images }}" width="100%" />
</div>

And in response i receive this message:
GET data:image/jpeg;base64,["data:image/jpeg;base64,/9j/4Ru+RXhpZgAATU0AKgAAAAg…U5Psv4fVf8Wv/gZQ/wDPQaf8xkb/AOw/3n/efbXbrPw8R/F8+kTeP9bF/afA3++vVOv/2Q=="] net::ERR_INVALID_URL

**Comment by danialfarid** [comment]
ngf-src or ngf-thumbnail="response[0]"

**Comment by zionnite** [comment]
i keep getting reference error : undefined file

**Comment by zionnite** [comment]
Thank YOu for the great question but @danialfarid  how can i retrieve the value from firebase because if have done that am am receiveing alot bunch of error in my console...
please a clearer code will be more appreciated .

thank you for you time

**Comment by danialfarid** [comment]
post it on SO this is a question not an issue.

**Comment by zionnite** [comment]
please whats the meaning of SO

**Comment by danialfarid** [comment]
www.stackoverflow.com tag your question with ng-file-upload.
