### ISSUE TITLE
CORS issue 

### ISSUE THREAD

**Issue by Bmkaradia** [danialfarid/ng-file-upload#1035]
Hi

can u help me , i have problem related CORS, same funcitonality working on web application.

http://snag.gy/bgdS8.jpg 
http://snag.gy/es8fR.jpg

Thanks
Brijmohan

**Comment by danialfarid** [comment]
The error says your sever doesn't allow cross domain request for that url you are trying to use.

**Comment by Bmkaradia** [comment]
CORS is enabled , i am using other webservices!

it will be glad if you help me!

On 1 October 2015 at 21:23, Danial Farid <notifications@github.com> wrote:

> The error says your sever doesn't allow cross domain request for that url
> you are trying to use.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danialfarid/ng-file-upload/issues/1035#issuecomment-144769861>
> .
>



-- 


*Brijmohan Karadia  *
*+91 9829388872*
*Skype: bmkaradia*bmkaradia@icloud.com
*bmkaradia@g* <bmkaradia@gmail.com>
*mail.com <rubbyraj22@gmail.com>*http://brijmohan-karadia.branded.me

**Comment by danialfarid** [comment]
With this little info you provided it is hard to tell what is going wrong. 
From the logs it's obvious that it is failing due to cors not being allowed by the server.
