### ISSUE TITLE
Is there a reason you avoid using ngModel.$setViewValue()?

### ISSUE THREAD

**Issue by mpolichette** [danialfarid/ng-file-upload#1036]
On line `https://github.com/danialfarid/ng-file-upload/blob/master/src/model.js#L37` you re-parse the ngModel var name off the dom and use `.assign` to update the model value.  

This prevents users from adding their own ng-model validators and using `ng-model-controller` to control how the model is updated. 

It also has the effect of preventing the use of this directive in a component directive which inherits it's ngModel via replacement, if that directive has an isolate scope...

**Comment by mpolichette** [comment]
This has also required you to write your own `ngf-valid-only` instead of using the feature from `ng-model-options`

**Comment by mpolichette** [comment]
You're the man! Thanks for the fast turn around!

**Comment by danialfarid** [comment]
Since version 9.0.3 you can use `ngf-model-options` and by default invalid files are not allowed.
