### ISSUE TITLE
Cannot read property 'flashId' of null

### ISSUE THREAD

**Issue by Darex1991** [danialfarid/ng-file-upload#1038]
Hi,
I tried to upgrade version from 7.3.6 to newest (8.0.6).
In old I had:
```
Upload.upload(
        url: Restangular.all(@componentResource.resourcePath).getRequestedUrl()
        file: @file
        sendFieldsAs: 'form'
        fields:
          detail: @detail.plain()
      )
```
and in new I have:
```
Upload.upload(
        url: Restangular.all(@componentResource.resourcePath).getRequestedUrl()
        data:
          detail: @detail.plain()
          file: @file
      )
```
What is wrong with it?
I have a error at line https://github.com/danialfarid/ng-file-upload/blob/master/demo/src/main/webapp/js/ng-file-upload.js#L194

Also in the newest version it's deprecated 'sendFieldsAs', how I can send this as 'form'?

**Comment by ProfitWarning** [comment]
Can you check the error in Firefox?
If you get:
```javascript
Error: file is null
isFile@https://angular-file-upload.appspot.com/js/ng-file-upload.js:192:7
addFieldToFormData@https://angular-file-upload.appspot.com/js/ng-file-upload.js:223:20
addFieldToFormData@https://angular-file-upload.appspot.com/js/ng-file-upload.js:240:17
addFieldToFormData@https://angular-file-upload.appspot.com/js/ng-file-upload.js:240:17
addFieldToFormData@https://angular-file-upload.appspot.com/js/ng-file-upload.js:240:17
addFieldToFormData@https://angular-file-upload.appspot.com/js/ng-file-upload.js:240:17
addFieldToFormData@https://angular-file-upload.appspot.com/js/ng-file-upload.js:240:17
digestConfig/<@https://angular-file-upload.appspot.com/js/ng-file-upload.js:271:15
```
you probably run into the same "breaking change" as I did upgrading from 7.3.9 to 8.0.*

My issue:
[ Version 8.0.* breakes if array of images is send. #1032 ](https://github.com/danialfarid/ng-file-upload/issues/1032)

**Comment by danialfarid** [comment]
@Darex1991 the default is `form`.
What error do you get? Post more details of the error or better create a jsfiddle.

**Comment by davoam** [comment]
have the same error when trying to upload photo from gallery on android

**Comment by danialfarid** [comment]
You probably set a null object in your file model @davoam

**Comment by danialfarid** [comment]
Or actually this is fixed in latest versions. There is a check for file not being null so if you upgrade to the latest this error should not happen.

**Comment by davoam** [comment]
I fixed it by removing  ngf-pattern="'image/*'" accept="image/*"

**Comment by Darex1991** [comment]
@danialfarid I don't have error when I use
Upload.upload(
        url: Restangular.all(@componentResource.resourcePath).getRequestedUrl()
        data:
          file: @file
          detail: Upload.json(@detail.plain())
      )
but my detail is send as string/object (I don't know)
ie.
"{"modalInstance":{"result":{},"opened":{},"rendered":{}},"images":[],"mainSubject":{"id":1,"name":"Design Thinking""
My server expects form.
Then in last version I was used "sendFieldsAs: 'form'". How I can fix it?

**Comment by danialfarid** [comment]
@Darex1991 
```
data:
file: @file
detail: @detail.plain()
)
```
by default it is `form` now so you don't need to use `Upload.json`

**Comment by Darex1991** [comment]
But then I got error about 'flashId'

**Comment by danialfarid** [comment]
upgrade to the latest version

**Comment by Darex1991** [comment]
@danialfarid I tried it on '9.0.7'. Nothing changed :(

**Comment by danialfarid** [comment]
What is the error that you get?
Could you create a jsfiddle from samples on the readme page?

**Comment by danialfarid** [comment]
flash id is null would never happen in version 9.0.7.
There is a check for null at this line: https://github.com/danialfarid/ng-file-upload/blob/master/dist/ng-file-upload.js#L194

**Comment by srpeterson** [comment]
I have the exact same problem. In Chrome I put a breakpoint in line:

 return file != null && file instanceof Blob || (file.flashId && file.name && file.size);

![image](https://cloud.githubusercontent.com/assets/15022825/10353490/ca32efc2-6d0b-11e5-9d3b-841d88e59c2f.png)

**Comment by danialfarid** [comment]
@srpeterson yes flashId is undefined but that doesn't throw a reference error.

**Comment by IIapad0ks** [comment]
@danialfarid '&&' have higher priority then '||' so
a && b || c work as (a && b) || c

**Comment by danialfarid** [comment]
Right gonna be fixed in the next version.

**Comment by danialfarid** [comment]
Fixed at version 9.0.8. Thanks for the PR and reporting the issue.

**Comment by pedromalta** [comment]
Cool, was having the same issue right now :)

**Comment by srpeterson** [comment]
Thank you, Danial for your quick attention!!

**Comment by Darex1991** [comment]
Tnx for fast fix ;)
