### ISSUE TITLE
Multiple upload with no overriding sample.

### ISSUE THREAD

**Issue by GeorgySerga** [danialfarid/ng-file-upload#1039]
Hi! I have done a little [sample project](https://jsfiddle.net/Georgy/58oL5g4c/1/) with ng-file-upload. The main difference is that it supports selecting additional files during the existing upload process (the provided samples override existing filelist or progress). Also it has little bootstrap polishing :) You can add it to samples paragraph if you like it or just close the issue. The github [repo](https://github.com/GeorgySerga/ng-file-upload-test). Thank you.

**Comment by danialfarid** [comment]
Could you change the upload url too `https://angular-file-upload-cors-srv.appspot.com/upload` and post it here again?

**Comment by danialfarid** [comment]
Also mention your repo url on top of the jsfiddle sample.

**Comment by GeorgySerga** [comment]
Done

**Comment by danialfarid** [comment]
Whats the url?

**Comment by GeorgySerga** [comment]
Oh, sorry, I thought jsfiddle keeps the links after the update. Here it is, added new upload url and comment with repo: https://jsfiddle.net/Georgy/58oL5g4c/3/ .

**Comment by danialfarid** [comment]
You could use `ngf-keep="true"` with `ngf-change="updateFiles($files, $newFiles, $duplicateFiles, $invalidFiles)"` to make it easier to handle those cases.
Also `ngf-keep-distinct` has no effect if `ngf-keep` is not specified.

**Comment by GeorgySerga** [comment]
Remove `ngf-keep-distinct`, remove inline styles. https://jsfiddle.net/Georgy/58oL5g4c/4/

With `ngf-keep` I had some problems, that's why I wrote extra code (If I'm not mistaken, I could upload file 'a.ext' then I had no chance to choose 'a.ext', that's right, but if I picked 'b.ext' I had two files to upload, 'a' and 'b'). May be I did a mistake, but I wasn't able to find it at the moment.

**Comment by danialfarid** [comment]
When ngf-keep is set all files that you choose will be added to the model even if you upload them. So you can easily keep track of which one is uploaded or not by setting a flag on the file like `file.upload` or `file.inProgress`. To know which file is added new to the list you can use $newFiles.
I would rather put an example that uses the plugin features so if there is something that could be done to facilitate your example I would add that feature.

**Comment by GeorgySerga** [comment]
Agree with you, here is the new version without `allFiles` and `progress` arrays : https://jsfiddle.net/Georgy/58oL5g4c/6/ . How do you like it?

**Comment by danialfarid** [comment]
Select file doesn't work, abort just removes the in progress files, abortSingleFile is not used. 
Also why would you want to upload files one by one instead of uploading them together?

**Comment by GeorgySerga** [comment]
> Also why would you want to upload files one by one instead of uploading them together?

I just do have this request. I understand that it would be easier to create such sample without "one by one" uploading process.

> Select file doesn't work, abort just removes the in progress files, abortSingleFile is not used. 

Did you use the link above your comment? I can do selecting (tested in Chrome and Opera Mobile), after clicking on 'Abort'  browser's network tab shows - 200, canceled, and abortForOneFile (yeah, poor naming, I should choose abortSingleFile) is in use here: `<a href='#' ng-click='abortForOneFile($index);' ng-if='f.progress < 100'>X</a>`.

**Comment by danialfarid** [comment]
Alright.
`ngf-keep` is only useful when you have `ng-model`.
I would do your example like this: https://jsfiddle.net/58oL5g4c/10/
