### ISSUE TITLE
The page run out of memory when file is undefined

### ISSUE THREAD

**Issue by roddolf** [danialfarid/ng-file-upload#1040]
I have upgraded from 7.0.17 to 8.0.6 and when I upload my form, which can contain or not a file (undefined), the page crashes because it tries consume all the memory and cpu.

The was no poblem with this in the previous version.

**Comment by roddolf** [comment]
Sorry, I have seen that the error is not by the undefined file.

Looking at the code, it appears that now the extra data is added recursively, and my data had a $promise inside, so it caused an infinite cycle.

**Comment by danialfarid** [comment]
Circular reference detection.

**Comment by danialfarid** [comment]
Since version 9.0.3 you will get an error if you have circular reference in your data.
