### ISSUE TITLE
Refer to the issue #1034 

### ISSUE THREAD

**Issue by SaidThaher** [danialfarid/ng-file-upload#1041]
Hi again.
I try to implement if statement if the user not choose file it will send null to firebase which mean nothing will pushed for images . the first part where files==undefined worked, but i couldent get the base64Urls from the function  Upload.base64DataUrl(files).then(function(base64Urls){
and save it to images to push it to firebase:

'use strict';

angular.module('myApp.addPost', ['ngRoute'])

.controller('AddPostCtrl', ['$scope','CommonProp','$firebase','$location','Upload','$timeout', function($scope,CommonProp,$firebase,$location,Upload,$timeout) {
if(!CommonProp.getUser()){
$location.path('/main');
}
/***** Add data to firebase *****/
$scope.AddPost = function(files) {
var fb = new Firebase("https://hotelboard.firebaseio.com/Articles/");
var images ;

        if (files == undefined){
             images = null;
             console.log(files);
            console.log(images);
        }else{

            images = Upload.base64DataUrl(files).then(function(base64Urls){
                images = base64Urls;
            })

        }
            console.log(files);
            console.log(images);

        var title = $scope.article.title;
        var post  = $scope.article.post;
        var user  = CommonProp.getUser();
        //var images = Upload.base64DataUrl(files).then(function(base64Urls){
        fb.push({
            title:     title,
            post:      post,
            emailId:   user,
            images : images,
            '.priority': user

        },function(error) {
            if (error) {
                console.log("Error:",error);
            } else {
            console.log("Post set successfully!");
            $location.path('/home');
            $scope.$apply();

        }

    });

//});
//}
}

}]);

in the second log after files been selected i got this results and errors:

[File]0: Filelength: 1__proto__: Array[0]

addPost.js:28 Promise {$$state: Object}$$state: Object__proto__: Promise

angular.js:12416 Error: Firebase.push failed: first argument contains an invalid key ($$state) in property 'Articles.images'. Keys must be non-empty strings and can't contain ".", "#", "$", "/", "[", or "]"
at Error (native)
at http://localhost:8000/app/bower_components/firebase/firebase.js:130:18
at ib (http://localhost:8000/app/bower_components/firebase/firebase.js:20:569)
at Wf (http://localhost:8000/app/bower_components/firebase/firebase.js:129:424)
at http://localhost:8000/app/bower_components/firebase/firebase.js:130:166
at ib (http://localhost:8000/app/bower_components/firebase/firebase.js:20:569)
at Wf (http://localhost:8000/app/bower_components/firebase/firebase.js:129:424)
at Vf (http://localhost:8000/app/bower_components/firebase/firebase.js:128:438)
at U.push (http://localhost:8000/app/bower_components/firebase/firebase.js:252:102)
at Scope.$scope.AddPost (http://localhost:8000/app/js/addPost.js:35:7)(anonymous function) @ angular.js:12416ident.$get @ angular.js:9203parent.$get.Scope.$apply @ angular.js:15983(anonymous function) @ angular.js:23376eventHandler @ angular.js:3293

**Comment by danialfarid** [comment]
```
//var images = Upload.base64DataUrl(files).then(function(base64Urls){
    fb.push({
        title:     title,
        post:      post,
        emailId:   user,
        images : base64Urls,
        '.priority': user

    },function(error) {
        if (error) {
     
```

**Comment by SaidThaher** [comment]
i dont get it. you mean i can implement in function(error) to set images to null in unselected files??

**Comment by SaidThaher** [comment]
Hi @danialfarid , Any thing about the solution for this??

**Comment by danialfarid** [comment]
use the latest version

**Comment by SaidThaher** [comment]
I just updated but still not working how i want.
Did you read what i want to do??

**Comment by danialfarid** [comment]
What is not working? What's the error?

**Comment by SaidThaher** [comment]
I try to implement if statement if the user not choose file it will send null to firebase which mean nothing will pushed for images . the first part where files==undefined worked, but i couldent get the base64Urls from the function Upload.base64DataUrl(files).then(function(base64Urls){
and save it to images to push it to firebase:

i get this error : 

Error: Firebase.push failed: first argument contains an invalid key ($$state) in property 'Articles.images'. Keys must be non-empty strings and can't contain ".", "#", "$", "/", "[", or "]"
at Error (native)

**Comment by danialfarid** [comment]
What is the object in article.images? Post you new code.

**Comment by danialfarid** [comment]
What are the base64Urls returned by Upload.base64DataYrk?

**Comment by SaidThaher** [comment]
$scope.AddPost = function(files) {
			var fb = new Firebase("https://hotelboard.firebaseio.com/Articles/");
			var images ;

			if (files == undefined){
				 images = null;
			}else{
				
				images = Upload.base64DataUrl(files).then(function(base64Urls){
					images = base64Urls;
				})

			}
				console.log(files);
				console.log(images);

			var title = $scope.article.title;
			var post  = $scope.article.post;
			var user  = CommonProp.getUser();
			fb.push({
				title:     title,
				post:      post,
				emailId:   user,
				images : images,
				'.priority': user
				
			},function(error) {
				if (error) {
					console.log("Error:",error);
				} else {
				console.log("Post set successfully!");
				$location.path('/home');
				$scope.$apply();
			}		
		});
	}


the object in articles.images is the image selected from the input.
When the user wont select an image i push null in the images variable.

here is the log from console after selecting image

**Comment by danialfarid** [comment]
It is not exactly what I suggested.
You gotta put your code that pushes to the server inside that promise then.
See https://github.com/danialfarid/ng-file-upload/issues/1041#issuecomment-145170843

**Comment by SaidThaher** [comment]
when i did that, i got error : 
ReferenceError: base64Urls is not defined
    at Scope.$scope.AddPost

because its always passes base64Urls .
I dont know

**Comment by SaidThaher** [comment]
Hi, any solution @danialfarid ??

**Comment by danialfarid** [comment]
Either create a jsfiddle so I could debug your code or figure out why it is not defined.

**Comment by SaidThaher** [comment]
i worked it around like that : 

if (files == undefined){

						fb.push({
						title:     title,
						post:      post,
						emailId:   user,
						images : null,
						'.priority': user
						
					},function(error) {
						if (error) {
							console.log("Error:",error);
						} else {
						console.log("Post set successfully!");
						$location.path('/home');
						$scope.$apply();
					
					}
						
				});

			} else {

			Upload.base64DataUrl(files).then(function(base64Urls){

				fb.push({
					title:     title,
					post:      post,
					emailId:   user,
					images : base64Urls,
					'.priority': user
					
				},function(error) {
					if (error) {
						console.log("Error:",error);
					} else {
					console.log("Post set successfully!");
					$location.path('/home');
					$scope.$apply();
				
					}
					
				});

			});
		}


But this case is duplicate code
