### ISSUE TITLE
Unable to set default "ngfResize" with Upload.setDefaults 

### ISSUE THREAD

**Issue by ProfitWarning** [danialfarid/ng-file-upload#1042]
This is how I tried to set the default setting (called first thing in my controller):
```javascript
Upload.setDefaults({
            ngfResize: {width: 20, height: 20}
        })
```
```javascript
if (params) {
          return $parse(this.getAttrWithDefaults(attr, name))(scope, params);
        } else {
          return $parse(this.getAttrWithDefaults(attr, name))(scope);
        }
```
in upload.attrGetter returns  string "[object object]"

ngf-resize is not set as attribute, this triggers 
```javascript
upload.defaults[name].toString()
```
but
```javascript
upload.defaults["ngfResize"]
```
is defined result is the string "[object object]"

side note: if ngf-size is not set on thumbnail it crashes, because
```javascript
canvasElement.toDataURL(type)
```
creates an invalid data url, if with and height of element are 0.
My chrome Version 45.0.2454.85 Ubuntu 14.04 (64-bit)

**Comment by danialfarid** [comment]
Fixed at 9.0.4
