### ISSUE TITLE
Press enter key opens the select file window

### ISSUE THREAD

**Issue by rochadsouza** [danialfarid/ng-file-upload#1045]
If I have a \<button\> inside a \<form\> with the ngf-select tag, as shown in this fiddle: https://jsfiddle.net/rochadsouza/agbbnmp3/1/
Everytime I press the Enter Key in an input (text type) within the form, this action will open the 'select files window'.
You can try this in the fiddle above.

p.s.: My workaround is use a \<a\> tag instead a \<button\> tag.

**Comment by danialfarid** [comment]
This is the default html form behaviour in chrome, when you press enter it would click on the button in the form: https://jsfiddle.net/agbbnmp3/2/

**Comment by ordavidil** [comment]
@rochadsouza 
adding `type="button"` should solve this.

**Comment by nicooga** [comment]
I have a button because It must have markup inside (an icon). Is there other way to work around this?

**Comment by ryangriggs** [comment]
@ordavidil  You, my friend, are a life saver.  Thank you for reminding to add `type="button"` to prevent default form button behavior on Enter keypress!
