### ISSUE TITLE
How to change images ordering on the screen

### ISSUE THREAD

**Issue by talor1981** [danialfarid/ng-file-upload#1046]
There is an option to control on the images order?
For example, If I want to view images in the gallery and give the user the ability to change their order.
Thanks

**Comment by danialfarid** [comment]
The files will be set in the model in the order of selection. You can sort or re-order the files model later on.

**Comment by talor1981** [comment]
Thanks, but i want to give the user the ability to change the order by Drag & Drop in live.

**Comment by danialfarid** [comment]
You can put the files in another model and change their order by dragging.

**Comment by danialfarid** [comment]
You can change the order of the files in the array model if you have ngf-keep set.
