### ISSUE TITLE
Multiple File Upload, no array

### ISSUE THREAD

**Issue by sisu4u** [danialfarid/ng-file-upload#1048]
Hi,

using your multiple file upload example: http://jsfiddle.net/danialfarid/huhjo9jm/5/
The Request Payload looks like this:
```
------WebKitFormBoundary4Lc5A5Z4vExW8bNj
Content-Disposition: form-data; name="files[0]"; filename="1.png"
Content-Type: image/png


------WebKitFormBoundary4Lc5A5Z4vExW8bNj
Content-Disposition: form-data; name="files[1]"; filename="2.png"
Content-Type: image/png



------WebKitFormBoundary4Lc5A5Z4vExW8bNj--
```

Whereas when I use a simple upload form with no JS:
```
<form action="https://angular-file-upload-cors-srv.appspot.com/upload" method="post" enctype="multipart/form-data">
    <input type="file" name="files" multiple="multiple" />
   <input type="submit" />
</form>
```

The payload looks like this:
```
------WebKitFormBoundaryePQRTeioGZmfAN96
Content-Disposition: form-data; name="files"; filename="1.png"
Content-Type: image/png


------WebKitFormBoundaryePQRTeioGZmfAN96
Content-Disposition: form-data; name="files"; filename="2.png"
Content-Type: image/png


------WebKitFormBoundaryePQRTeioGZmfAN96--
```

On the server side I'm using a Spring RESTController endpoint:

```
 @RequestMapping(value="/upload", method=RequestMethod.POST)
    public ResponseEntity<Long> handleFileUpload(
            @RequestParam("files") MultipartFile[] files) {
...
}
```

With the plain HTML upload form this works well. With your upload (files[1], files[2]) the array is always empty. Is there a way to change that? The option arrayKey does not have this specification.

Forked JSFiddle with the normal HTML-form:

https://jsfiddle.net/vxoLLenu/

I'm using chrome.

Thanks for you help!

**Comment by danialfarid** [comment]
Add `arrayKey: ''` option to your config

**Comment by usos0k** [comment]
@danialfarid 
if I want to send files and string array together, is it possible? 
The arrayKey: '' makes to send files O.K but also makes the array of string to change which sent together with the files. so, I want to give arrayKey option to files and array of string separately, but I think there isn't that kind of action. 
is it possible? or should I send files and array of string separately?

**Comment by danialfarid** [comment]
You can use formDataAppender but I would suggest to convert your array to json string and send it as a string and convert it to object on the server from json string.
