### ISSUE TITLE
Popup for choosing upload method doesn't show on iOS

### ISSUE THREAD

**Issue by henev** [danialfarid/ng-file-upload#1049]
Hi,

I am testing my application that uses angular 1.4.4 on iPhone 6 and on iPad 2 with Safari and Chrome as browsers. When I click an upload button nothing happens. I debugged it in Safari console and I got no errors. The demo page works fine but I see there that the angular version is 1.2.24. My ng-file-upload is version 9.0.6. Any ideas?

Thanks :)

**Comment by henev** [comment]
If someone is having this problem - solved it with using `<input type="file">`.

**Comment by danialfarid** [comment]
You can change the version of angular at the top of the demo page and try it out with other version. That might give you a clue if the demo page is working with the version you have.

**Comment by StritziK** [comment]
Same problem for me if I use a div or button instead of <input type="file" .. there is no file selection popup on iPhone 5S

**Comment by danialfarid** [comment]
See if the demo page works

**Comment by StritziK** [comment]
i created a fiddle trying to break my a more complex structure into a simple one, it works with all android devices i tested it but not with iphone.
http://jsfiddle.net/cdtasbc8/

**Comment by maelfrize** [comment]
I'm having the same issue. It works perfectly in all desktop browsers and on android devices. However, many of the upload buttons in my app don't work on iPhone.

**Comment by danialfarid** [comment]
This seems like an issue with ngMaterial, Please open an issue on their github. If you remove ngMaterial from dependencies everything works, probably they have special handling for iphone iOS that make it break the click event on div or button element.
The you see the popup for input type file is because it is its default behaviour but the actual upload may not work even if you have input type file.

Please also link back to this issue if you create an issue over their github.
You can simplify the case by remove dependency to this plugin and just have a button on the page and add 
```
button.on('click', function() { anotherButton.click() });
```
This should click on another button and if you have an event listener on anotherButton it should be triggered. I assume this will not work if you have ngMaterial on iPhone.

**Comment by ereztison** [comment]
Just found a workaround for this issue:

inject $mdGestureProvider to your app, then invoke:
```javascript
$mdGestureProvider.skipClickHijack();
```

The purpose of this function is documented in angular-material source code:
```javascript
     * In some scenarios on Mobile devices (without jQuery), the click events should NOT be hijacked.
     * `$mdGestureProvider` is used to configure the Gesture module to ignore or skip click hijacking on mobile
     * devices.
```

I tested it with iOS 9 and Android 5 and 6 and it seems to work fine so far, though there might be implication on older Android or iOS devices as stated in angular-material source code:
```javascript
       * If hijack clicks is true, we preventDefault any click that wasn't
       * sent by ngMaterial. This is because on older Android & iOS, a false, or 'ghost',
       * click event will be sent ~400ms after a touchend event happens.
       * The only way to know if this click is real is to prevent any normal
       * click events, and add a flag to events sent by material so we know not to prevent those.
```

**Comment by barryvdh** [comment]
Another solution to this is to use a `<label>` with a referencing id, as suggested here: https://github.com/angular/material/issues/3310#issuecomment-189050200

```
<input class="ng-hide" id="input-file-id" multiple type="file" />
<label for="input-file-id" class="md-button md-raised md-primary">Choose Files</label>
```

**Comment by manan-sheth** [comment]
@danialfarid We have implemented code for file upload in backend. It works well with desktop file uploads. 
But we're not able to upload from iOS native app with standard image upload code.
We're not getting any array of files (req.files objects) while sending from iOS - multipart form-data standard method.
Do we require any changes at backend .js files ?

**Comment by danialfarid** [comment]
@manan-sheth which ios native app?

**Comment by manan-sheth** [comment]
@danialfarid We're developing our own application. For backend we've used your npm code for js. 
Now, we're trying to upload from front-end mean application, but we're failed to upload.
Error : Cannot read property 'path' of undefined

**Comment by danialfarid** [comment]
@manan-sheth First of all this is not related to this issue so create a new issue, second you need to post your code or a jsfiddle sample showing how you get that error.

**Comment by dokydok** [comment]
I ran into this issue, and I didn't have ngMaterial in my app.
In my case it was an issue with FastClick, fixed by adding "needsclick" class on my div

**Comment by deifos** [comment]
I had the same issue and thanks to @dokydok is all good now.
