### ISSUE TITLE
Object doesn't support property or method 'xhr'

### ISSUE THREAD

**Issue by alvipeo** [danialfarid/ng-file-upload#1051]
You have on the main page the following:

```
}).xhr(function(xhr){
  //access or attach event listeners to the underlying XMLHttpRequest
  xhr.upload.addEventListener(...)
});
/* return $http promise then,catch or finally.
Note that this promise does NOT have progress, abort or xhr functions */
var promise = upload.then(success, error, progress);
              upload.catch(errorCallback);
              upload.finally(callback, notifyCallback);
```

I try to use .xhr and get error "Object doesn't support property or method 'xhr'". So is there xhr or not? - that is the question!

**Comment by danialfarid** [comment]
This was documentation error. You should call it on the original upload. I have updated the documentation. After you call then() the promise returned is angular promise without any overriden methods (abort/xhr).
