### ISSUE TITLE
Default image and remove image

### ISSUE THREAD

**Issue by Darex1991** [danialfarid/ng-file-upload#1055]
Hi, 
1) On documentation I found solution for default image: 
```img ngf-src="file || 'http://lorempixel.com/400/200/sports/1'"```
but default image are not displayed ;/. 

![screen shot 2015-10-09 at 11 13 07](https://cloud.githubusercontent.com/assets/5881611/10390214/6c98ecd2-6e77-11e5-8860-eb4aa46a3ae7.png)
2) How to declare remove image?
Now I use own function: 
```
@removeFile = (file) =>
      @file = file
      @result = _.findIndex(@resource.files, (file) =>
        file == @file
      )
      @resource.files.splice(@result, 1)

**Comment by LennyLip** [comment]
1) I think you pdf "file" is exist. You must test that file is not image, now you just test that "file" is initialized.
2) I think is ok. And you can send index from angular template like a

    <span ng-repeat="file in files track by $index" >
         <a ng-click="removeFile($index)></a>
    </span>

**Comment by LennyLip** [comment]
@Darex1991  please, close issue, i think it is not "ng-file-upload" issue
