### ISSUE TITLE
Original image got removed as soon as "choose file" is clicked

### ISSUE THREAD

**Issue by tandvu** [danialfarid/ng-file-upload#1056]
So if I have an image.  Then I click on "choose file" to open the file upload.  It would remove the image right away.  So if I decide to cancel the action, I cannot go back to my original image.  How do I solve this problem?

Thank you,

Tan Vu

**Comment by danialfarid** [comment]
You can have `ng-model-options="{updateOn: 'change drop'}"` to disable it.
But remember this is the default behaviour in Chrome so if you click the file select and then cancel the popup the value of the file will be removed that's the plugin removes the file upon clicking.

**Comment by rderharo** [comment]
I had a similar problem. When my upload button was clicked and the form failed validation, if the user tried to select another file, the ngf-change event would be fired and the model file would be cleared by then so the function would fail (as it references the file).

The `ng-model-options` as described above fixed that issue, though I suppose an alternative fix would have been to check for the existence of the file before doing anything with it. For my use case, I preferred to not clear the file unless a new file was actually selected.

**Comment by danialfarid** [comment]
@rderharo condider that clearing the file is default behaviour in Chrome. if you cancel the popup window it will clear the file input. So it is does behave differently cross browser, that's why it is been reset on click to make it behave the same on all browsers.

**Comment by danialfarid** [comment]
@rderharo condider that clearing the file is default behaviour in Chrome. if you cancel the popup window it will clear the file input. So it is does behave differently cross browser, that's why it is been reset on click to make it behave the same on all browsers.
