### ISSUE TITLE
Sending boolean "true" as string true.

### ISSUE THREAD

**Issue by pavankumarkatakam** [danialfarid/ng-file-upload#1057]
When using angular $http, boolean true can be send as boolean true, but when using the Upload service boolean true is sending as string "true".

is the package is writtten like that or any wrong i did.

**Comment by danialfarid** [comment]
Yes it is because upload is sending it as multipart form data request and there is no way to set the content type on each individual form data part unless you convert them to blob or json.
You could use `Upload.json(data)` and then on the backend convert the string of data to the json object.
