### ISSUE TITLE
Rails Paperclip Image Upload 

### ISSUE THREAD

**Issue by nwoow** [danialfarid/ng-file-upload#1058]
Hey I am following the documents and I am trying to upload an image using your plugin here I have come so far here is the code I am using for form :

	  <form ng-submit="addEntry()" name="form">
			    <input type="text" ng-model="name">
			    <input type="text" ng-model="tittle">
			    <input type="text" ng-model="description">
			   <input type="text"  ng-model="user_id">
		<div class="button" ngf-select ng-model="file" name="file" ngf-pattern="'image/*'"
    accept="image/*" ngf-max-size="20MB" ngf-min-height="100" 
    ngf-resize="{width: 100, height: 100}">Select</div>
			    <input type="submit" value="Add">
			  </form>

And in my angular controller I am using this code : 

                    $scope.addEntry = function(){ 
                  
                 $scope.names.push({ 'name':$scope.name,'title':$scope.tittle, 'description': $scope.description, });
           
 
                             // upload on file select or drop
                $scope.upload = function (file) {
                    Upload.upload({
                        url: '/market_places.json',
                        method: 'POST',
                        data: {file: file, 'market_place[user_id]':$scope.user_id,'market_place[image]':$scope.image,'market_place[name]': $scope.name, 'market_place[tittle]': $scope.tittle, 'market_place[description]':$scope.description},
                         headers: {
                            
                            'X-CSRF-Token': $('meta[name=csrf-token]').attr('content')
                        }
                    }).then(function (resp) {
                        console.log('Success ' + resp.config.data.file.name + 'uploaded. Response: ' + resp.data);
                    }, function (resp) {
                        console.log('Error status: ' + resp.status);
                    }, function (evt) {
                        var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
                        console.log('progress: ' + progressPercentage + '% ' + evt.config.data.file.name);
                    });
                };
                
                $scope.upload($scope.file);

Here all the time I am getting this message  in console :  

progress: 100% total-product-marketing.jpg
Success total-product-marketing.jpguploaded. Response: [object Object]

These are the two message I am getting in console . I am using paperclip in paperclip I can upload image easily using front end form . This is a very big issue for me and on net there is hardly any solution .

**Comment by danialfarid** [comment]
Seems like you are getting the success response. So what is the issue?

**Comment by nwoow** [comment]
In general suppose when I am uploading this image using rails form it upload well but when I am using above codes via angular I don't know where this image is saved I am using peperclip gem wondering how can I use angular with paperclip I have searched on net but no solution . Here image is not uploading where I wanted . Hey can you please explain how this attachment travels . This is the actual params which work in general html browser :+1: 
{"utf8"=>"✓", "authenticity_token"=>"0E1vwIaXbsS2Su8D+hZde2e5NQw6KZr51kA1p+d3tWB9z/D/H9gFMht85A0IPvzGo0doLRNhCEKSkS2Gc4+dBg==", "market_place"=>{"name"=>"6666", "tittle"=>"6666", "description"=>"6666", "image"=>#<ActionDispatch::Http::UploadedFile:0xbdc233b0 @tempfile=#<Tempfile:/tmp/RackMultipart20151011-18251-b10bq6.jpg>, @original_filename="total-product-marketing.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"market_place[image]\"; filename=\"total-product-marketing.jpg\"\r\nContent-Type: image/jpeg\r\n">, "user_id"=>"1"}, "commit"=>"Add Product", "id"=>"14"}

Can you tell me how can I send this image When using above params work great .

**Comment by nwoow** [comment]
Hey Can you please tell me how can I change Content-Disposition: form-data; name="file"; filename="download.jpg" in this request name="file" to name="image" this is the issue that is casuing the problem .

**Comment by nwoow** [comment]
I found a solution for this it was a problem with file params . So I made a few change to my rails controller there I changed  the code like this in create action and it was done . code I added if params[:file]
        params[:market_place][:image] = params[:file]
      end

Hey daniel I have a suggestion add something where anyone can change the params[:file ] in angular

**Comment by danialfarid** [comment]
You can do `data: {image: file,...}` instead of `data: {file: file,...}`

**Comment by gerome0123** [comment]
@nwoow hello sir my i see your source i'm doing upload image using angular then save into the paper clip my i request your source code in codepen or jsfiddle to understanmore... if possible?? i need your help <3
