### ISSUE TITLE
ngf-keep="distinct" removes all files from the model before adding new files - is this how it should work?

### ISSUE THREAD

**Issue by progmars** [danialfarid/ng-file-upload#1061]
If I have
```
 <button type="button" ngf-select ng-model="uploadFiles" name="uploadFiles"
                          ngf-multiple="true"
                          ngf-keep="distinct"
                          >Add files</button>
```
my intuitive expectation would be that each time I click the button and select files, the new files should be added to `$scope.uploadFiles` and the old ones should still remain in the model. Only if I select the same file twice, it will be ignored in the model. But currently, each time I click the button my  `$scope.uploadFiles` gets completely cleared out.

If I set `ngf-keep="true"` then  `$scope.uploadFiles` is not cleared out, but then, obviously, duplicate files are not filtered either.

Is there any way to make `distinct` work similar to `true` and ignore only duplicate files without clearing out all the other ones from `$scope.uploadFiles`  ?

**Comment by danialfarid** [comment]
You are probably using an old version of the plugin.

**Comment by progmars** [comment]
Yes, I had 9.0.8 before. Today I updated to 9.0.9. But still the issue is present.

I'm using Chrome.

As it was hard to debug the problem because for unknown reason the file selection dialog does not  appear after breakpoint, I modified the code a bit:

```
  function handleKeep(files, prevFiles, attr, scope) {
    console.log(files, prevFiles);
```

and now I clearly see that when selecting files, `handleKeep` is being called twice - one time before file selection dialog appears, and then later one more time. During the first call `files` is null. But during the second call (right after file selection dialog has been closed), `files` holds the newly selected files, but `prevFiles` is empty array - because it got cleared during the first `handleKeep` call.

I guess, the root cause of the issue is the fact that `handleKeep` is being called twice, and the first call is really unexpected because it happens before selecting any files, thus causing model reset and losing `prevFiles`.

**Comment by sdshankins** [comment]
I am seeing the same issue also on 9.0.9 and I am using IE 11.  I have traced it to the function upload.attrGetter called on line 412 returning <code>undefined</code> rather than <code>'distinct'</code>:

<code>var keep = upload.attrGetter('ngfKeep', attr, scope);</code>

If the value of the variable <code>keep</code> is changed to <code>'distinct'</code> with a debugger after the function returns, the rest of the code runs as expected and the file array maintains its values.

**Comment by danialfarid** [comment]
It should be `ngf-keep="'distinct'"` note the quotation.

**Comment by danialfarid** [comment]
Updated the docs to show the quotations.
