### ISSUE TITLE
Image is "uploaded" before select path on ngf-select

### ISSUE THREAD

**Issue by Emmurillo** [danialfarid/ng-file-upload#1063]
No matter if I use
```javascript
ngf-select="vm.setImage($files, $event)" 
``` 
or 
```javascript
ngf-select ngf-change="vm.setImage($files, $event)" 
``` 
the file is uploaded when the file chooser is triggered.
There's no `on-load-done="{{ expression }}"` tag?

> It works fine with `ngf-drop="vm.setImage($files, $event)"`  because the upload is instantly.

**Comment by danialfarid** [comment]
Add `if ($files && $files.length)` before uploading or if you have ngf-keep check for $newFiles.
That is expected behaviour to be called when you click which will clear out old values of the input.

**Comment by Emmurillo** [comment]
The reason is that I'm using [ngImgCrop](https://github.com/alexk111/ngImgCrop) after upload the file and I need to set the image when the file has been chosen and not before. 
Your suggestion seems to validate if the file is there or not but isn't binding the $newFiles at all.
Check out my code:

 ```javascript
ngf-drop="vm.setImage($files)" ngf-select="vm.setImage($newFiles)" ngf-keep="true"
```
 ```javascript
function setImage(files) {
            if(files && files.length){
                var file = files[0];
                var reader = new FileReader();
                reader.onload = function (evt) {
                    $scope.$apply(function() {
                        vm.image = evt.target.result;
                    });
                };
                reader.readAsDataURL(file);
            }
        }
```

Any suggestion?

**Comment by Emmurillo** [comment]
It seems to be working with ```ngf-select="vm.setImage($files)"``` Thanks @danialfarid !
