### ISSUE TITLE
Action for invalid files

### ISSUE THREAD

**Issue by playUruguay** [danialfarid/ng-file-upload#1064]
When add a  invalid file, this is pushed in ng-model. I need when i select a invalid file, show a error popup and not push the file to the model.

Sorry for my bad English

**Comment by leejaycoke** [comment]
Did you add ngf-model-invalid 
```
ngf-model-invalid="invalidFilesArray" // binds the invalid selected/dropped file...
```

**Comment by danialfarid** [comment]
@playUruguay version 9.x.x by default does that.
