### ISSUE TITLE
Documentation Update: Upload.jsonBlob should contain a json string

### ISSUE THREAD

**Issue by himanshuranavat** [danialfarid/ng-file-upload#1065]
I was doing this:

```javascript
var xInfo = {name: 'foo', id: 'boo'};
Upload.upload({
url: http://someurl,
data: {
  file: file
  otherInfo: Upload.jsonBlob(xInfo)
}
});
```

But, otherInfo was being sent as [object Object] to the server.

I had to use angular.toJson to convert it to a json string to be sent properly to the server:

```javascript
var xInfo = {name: 'foo', id: 'boo'};
Upload.upload({
url: http://someurl,
data: {
  file: file
  otherInfo: Upload.jsonBlob(angular.toJson(xInfo))
}
});
```

Can we make it more explicit that the argument to the jsonBlob method should be a well-formatted JSON string and not a Javascript object as-is

Credit: http://shazwazza.com/post/uploading-files-and-json-data-in-the-same-request-with-angular-js/

**Comment by danialfarid** [comment]
Fixed at version 9.0.10.
Could be an object which will be `JSON.Stringify()`ed before converting to blob.

**Comment by himanshuranavat** [comment]
great thanks.

**Comment by stanleyxu2005** [comment]
@danialfarid If I send json data using `Upload.json(some_obj)`, the raw request body will not carry a `content-type: application/json`. Can you add this to every formdata parts except files?

E.g.
```
------WebKitFormBoundaryK0bcH9TwpNJqYfgR

Content-Disposition: form-data; name="app"
Content-Type: application/json

{"hello":"world"}

------WebKitFormBoundaryK0bcH9TwpNJqYfgR

Content-Disposition: form-data; name="jar"; filename="wordcount-2.11.5-0.6.2-SNAPSHOT-assembly.jar"

Content-Type: application/x-java-archive

```

**Comment by danialfarid** [comment]
You cannot set the content-type for string, only for files and blobs.
