### ISSUE TITLE
How to require use to update exact size

### ISSUE THREAD

**Issue by hughred22** [danialfarid/ng-file-upload#1068]
How I can set the exact size of the image that allow people to upload? 
Also, here is my code, and the min and max is not working. I upload image exact 1400 and 630 and it return error of minWidth. I need to set the min to 1000 then that work. Very strange. Same as height, I can not set min to a set number like 630. I keep trying and only min 400 works. But all the max is not working. so like ngf-validate="{width: {min: 1000, max:2000}, height: {min: 400, max: 900}}", an image large than 2000 (like 3840) will allow upload. 

```
<input id="pictures" label="Upload Images" name="pictures" ngf-select="admin.uploadFiles($files)" ng-model="pictures" accept="image/*" ngf-validate="{width: {min: 1400, max:2000}, height: {min: 630, max: 900}}" ngf-resize="{width: 1600, height: 720, quality: 1}"  ngf-keep="true" multiple>
            <div ng-messages="createActorPageForm.pictures.$error">
                <div ng-message="minWidth">
                    Min Width has to be 1400.
                </div>
                <div ng-message="minHeight">
                    Min height has to be 630.
                </div>
            </div>
```

**Comment by danialfarid** [comment]
It is working just fine for me.
Create a jsfiddle and attach the picture you are trying here.
