### ISSUE TITLE
Documentation error on js single file example

### ISSUE THREAD

**Issue by fabianrios** [danialfarid/ng-file-upload#1069]
I think this is 
   $scope.submit = function() {
      if ($scope.file.$valid && $scope.file && !$scope.file.$error) {
        $scope.upload($scope.file);
      }
    };

and not

   $scope.submit = function() {
      if (form.file.$valid && $scope.file && !$scope.file.$error) {
        $scope.upload($scope.file);
      }
    };

**Comment by danialfarid** [comment]
No it is the form that we are checking the validation.
