### ISSUE TITLE
Using ngf-resize cause ngf-validate to fail. And resize created file name blob without file extension.

### ISSUE THREAD

**Issue by hughred22** [danialfarid/ng-file-upload#1070]
The codepen here demo the issues: http://codepen.io/hughred22/pen/NGaXXg?editors=101

1. upload image file that smaller than 1400 in width will not trigger the error message anymore. Get rid of ngf-resize, everything will work again. 

2. upload image pass the validation, when it hit my server and save. The server file name will be number_blob without file extension like .jpg 
See my codepen how I send the file. The photo property will be:
      photo: "https://actorreels.stamplayapp.com/upload/cobject/pictures/1444892747388_blob"
Get rid of resize, it will be number_filename.jpg. 

I exam the $file object, with resize, it called blob. The proto do not have get name function. Without resize, it called file and the proto has function get name... How can I change the file name into the name with correct extension? 

Test image: 
![nasd_overlay_headerimage4](https://cloud.githubusercontent.com/assets/2126155/10507795/036463e4-72d8-11e5-8c82-8514c406a6a7.jpg)

**Comment by danialfarid** [comment]
1) the picture you attached here has the size within the validation so I am able to select it and it will be set to the model. If I use smaller image it would fail validation and will not be set as model. If you have a file that is smaller and is passing the validation attach it here.

2) Blob has the 'name' property with the correct name of the file so it will be uploaded with the correct file name. For the multipart form-data request blob and file are the same thing.

**Comment by hughred22** [comment]
1) The smaller image does not trigger the validation and show warning message using ngMessages. Check this again: http://codepen.io/hughred22/pen/NGaXXg?editors=101
I made 2 upload inputs now. The first one with resize. When you upload a smaller image, nothing happen and the line still blue and the createActorPageForm.pictures.$error do not trigger... 
The second one without resizing. You see upload a smaller image will trigger the ngMessage - show warning and the line become red. 

test image: 
![md-4](https://cloud.githubusercontent.com/assets/2126155/10520761/d01363d4-7320-11e5-97d7-d4d537d411bb.jpg)

**Comment by hughred22** [comment]
For 2) I am using stamplay as BAAS. They said they will put a timestamp and then the filename as the name. So they read whatever filename is the resize object blob. I can see blob has the name value. But what is the different between file and blob? File has get name in it prototype and blob do not. And Stamplay cannot get the correct filename for blob. Even I use Upload.rename.

**Comment by danialfarid** [comment]
Issues should be fixes in 9.0.11

**Comment by hughred22** [comment]
I just tried 9.0.12. The issue did not get fixed. With my upload directive like this: 
````
<input id="pictures" label="Upload Images" name="pictures" ngf-select="admin.upload($file)" ng-model="pictures" accept="image/*" ngf-max-size="5MB" ngf-validate="{width: {min: 1400, max:2000}, height: {min: 630, max: 900}}" ngf-resize="{width: 1600, height: 720, quality: 1.0}">
````
Now with the new update, validation is totally by passed by ngf-resize. Image with width like the second image I provide got resized and upload as well. Before, it will not get upload - but also will not trigger $error for ng-message. Now, it does not trigger ng-messages $error + it got upload to the server. 

Second, I did not see the blob get name problem solved. Nothing is changed. The filename still did not get read by Stamplay. As you see in the screenshot, it still do not have the get name function in prototype like file: (see Object > data > photo: path -- still end up with _blob with no file extension)
![screen shot 2015-10-15 at 11 08 41 pm](https://cloud.githubusercontent.com/assets/2126155/10534831/bcbc50ea-7391-11e5-8d32-dbfa34515a0b.png)

**Comment by danialfarid** [comment]
Alright there was a bug introduced in 9.0.9 that made the validation pass silently.
Try it with 9.0.13, I also added name to the Blob prototype.

**Comment by r7lemieux** [comment]
We are experiencing the same issue in 12.2.3
File name is blob. no extension.

![image](https://cloud.githubusercontent.com/assets/371129/22847422/56e976e6-efb2-11e6-9309-f25a2e5346fb.png)

**Comment by danialfarid** [comment]
Could you create a jsfiddle @r7lemieux ?
