### ISSUE TITLE
$file argument undefined in ngf-select or ngf-change on ios9 mobile safari

### ISSUE THREAD

**Issue by kylealwyn** [danialfarid/ng-file-upload#1072]
I'm using your awesome lib like so 
````html 
<button ngf-select="vm.timecheck($file)" ng-model="vm.mobilePhoto"></button>
<img class="mobile-photo"
         ngf-src="vm.mobilePhoto"
         ngf-resize="{width: 500, height: 500, quality: 0.9}"
         ngf-no-object-url="true" />
````

and i'm receiving file like so

````javascript
vm.timecheck = function (file) {
  console.log(file); //defined in browser, undefined on mobile
}
````

I need to check the last modified date of the date of the selected photo because we can not allow users to upload photos, only take them.

I receive the file and can successfully check the date on desktop browsers, but the $file argument comes in as `undefined` when debugging on mobile safari. I've also tried $files which sends an empty array.

The last modified date of the ng-model file, or vm.mobilePhoto, has the current date and time regardless of photo age. I'm assuming this is due to you creating these file objects on the fly while attaching the data url.

Any thoughts on this?

**Comment by esetnik** [comment]
i'm having the same issue on mobile safari. For me at least it appears as if ng-file-upload has a defined `$files` array for photos uploaded from "Take photos or video" option whereas `$files` is undefined for "Photo Library" option.

**Comment by esetnik** [comment]
@kylealwyn I figured out the issue I was having. It appears that iOS safari uploads files taken from the photo library with the ".jpeg" extension whereas from the camera they come with the ".jpg" extension. I have no idea why this is but after inspecting the running safari browser I noticed that all uploads from the photo library were failing my pattern validation. Adding `.jpeg` to the pattern causes uploads from mobile safari to work.

@danialfarid you should add a warning to the readme regarding this strange behavior. The fix is `            ngf-pattern="'.png,.jpg,.gif,.jpeg'"`

**Comment by kalwyn** [comment]
@esetnik I will give this a go at work tomorrow and report back. Thanks for the update!

**Comment by kylealwyn** [comment]
@esetnik @danialfarid It looks like this issue was fixed with the update to 9.1 (receiving a file, not undefined). However, the file that is sent via ngf-select has a last modified date of the current moment, regardless of when the picture was taken :(

**Comment by esetnik** [comment]
That's an interesting problem. I would have assumed that the last modified was included in the exif metadata of the image. However it's possible that iOS makes a local copy before upload.

**Comment by kylealwyn** [comment]
As a further update, if you use $files, a blank array is sent whether taking or choosing, but using $file sends a file object with wrong date. I expect your last assumption is the issue @esetnik

**Comment by esetnik** [comment]
@kylealwyn I have it working with `$files` and `ngf-multiple="true`.

**Comment by kylealwyn** [comment]
@esetnik How were you configuring it before to receive a defined array when using "take photo" and undefined when using "choose photo"? That would work for the requirements I have.

**Comment by esetnik** [comment]
Well the issue I described is the opposite of what you want but changing your pattern to `ngf-pattern="'.png,.jpg,.gif,.jpeg'"` causes all uploads to work. By removing the `.jpeg` pattern you will be able to only upload from "take photo". I'd assume, but don't have a chance to test, that removing `.jpg` and keeping `.jpeg` would have the opposite consequences.

**Comment by esetnik** [comment]
This has all kinds of unintended consequences though and probably not something you want to do in production. Keep in mind that this doesn't just affect the behavior of mobile safari but all uploads.

**Comment by kylealwyn** [comment]
I see, thanks. This is just a sloppy workaround for mobile right now. We are using webcam (userMedia) on desktop but since this is not available on mobile, we are using input files and trying to withhold chosen photos. Thanks for the help
