### ISSUE TITLE
Uncaught TypeError when not using ngf-resize

### ISSUE THREAD

**Issue by katemihalikova** [danialfarid/ng-file-upload#1073]
Hi Danial,
Your latest release contains a bug [there](https://github.com/danialfarid/ng-file-upload/commit/109ace98fa94caa44673389efff3a83b1c5fe478#diff-71257b2ea673e6a11bc86329d6034b33R809). If there is no `ngf-resize` attribute, javascript throws a TypeError because `param` is undefined and thus can't access its properties.

**Comment by danialfarid** [comment]
Fixed at 9.0.12

**Comment by rmdrabach** [comment]
Wow, I was having problems with this right now. That was fast...
