### ISSUE TITLE
Making this work with multer

### ISSUE THREAD

**Issue by jagged3dge** [danialfarid/ng-file-upload#1074]
I'm using [Multer](https://github.com/expressjs/multer) on my REST backend to handle the uploads.
I've set it up like the following:
```js
var multer = new Multer({
  multer.diskStorage({
    destination: function (req, file, cb) {
      cb(null, path.join(config.media.mediaFolder, config.media[mediaType].folderName))
    },
    filename: function (req, file, cb) {
      cb(null, uuid.v4() + '-' + fileDate() + path.extname(file.originalname))
    }
  })
})

app.post('/media', multer.array('sharedImg'), function (req, res) {
  console.log(req.files) // This should contain an array of file objects read from the formData keys named 'sharedImg'
})
```

I just upgraded to the latest 9.0.10. I've updated my uploading code like the following:

```js
Upload.upload({
  url: 'http://localhost:3000/media',
  // fileFormDataName: 'sharedImg', // pre-9.0.x
  // file: photos[i] // pre-9.0.x
  data: { sharedImg: photos[i] }
})
```
But it doesn't work. Multer can't find the files. The request payload in Chrome DevTools shows:
```
------WebKitFormBoundaryqXmixQ63rUM57DYa
Content-Disposition: form-data; name="data"

{"file":{"ext":"jpg","dataUrl":"blob:http%3A//localhost%3A5000/20c1ffb8-6454-4fc9-9b01-4cb173615f29"}}
------WebKitFormBoundaryqXmixQ63rUM57DYa--
```
Is it alright for it to show `name="data"`? Shouldn't it be `name="sharedImg"`?

I even tried with `arrayKey: '[sharedImg]'`. Even that didn't work. Can you help me out here?

**Comment by danialfarid** [comment]
This doesn't seem right, that code could not result in that request. Could you create a jsfiddle off the samples on the readme.

**Comment by jagged3dge** [comment]
Hm, it seems to be working over at [jsfiddle](https://jsfiddle.net/fL5r5qyv/). I'm going through my template code now, maybe something I overlooked.

**Comment by jagged3dge** [comment]
False alarm. \**insert foot-in-mouth here*\*
All it took was a restart of the gulp build task and everything's sunny. Thanks for your immediate feedback @danialfarid
