### ISSUE TITLE
error when ngf-keep is used.

### ISSUE THREAD

**Issue by joshikeerti** [danialfarid/ng-file-upload#1078]
I have the latest version of the library and I am trying to use ngf-keep="'distinct'", I am geting an error 
Uncaught TypeError: Cannot read property 'length' of null

I  went into the code and found that the error is in model.js file. It is getting the prevFiles length as null.

function handleKeep(files, prevFiles, attr, scope) {
 var len = prevFiles.length;
}

**Comment by danialfarid** [comment]
Fixed at 9.0.19
