### ISSUE TITLE
Please help me with this issue  TypeError: Cannot read property 'exp' of undefined     

### ISSUE THREAD

**Issue by 1043099804** [danialfarid/ng-file-upload#1080]
I used code of the example but I met this error:
TypeError: Cannot read property 'exp' of undefined
    at watchFnToHumanReadableString (<anonymous>:703:19)
    at l.$delegate.__proto__.$watch (<anonymous>:735:28)

**Comment by danialfarid** [comment]
Are you sure you are posting on the correct github?
Post your code or create a jsfiddle if you can.

**Comment by danialfarid** [comment]
https://github.com/danialfarid/ng-file-upload/issues/982#issuecomment-150061896
