### ISSUE TITLE
Sending json string with files charset problem

### ISSUE THREAD

**Issue by benoit-nadaud** [danialfarid/ng-file-upload#1081]
I'm trying to sends multiple files and a JSON object serialized with Upload.json.
The data received by the Java Spring backend is not considered as UTF-8 encoded so chars with accent are not good.

Could someone help me ?

Part of my code :

Upload.upload({
                url: ENV.restServiceUrl + '/news/',
                data: {file: $scope.files, photo: $scope.photo, "meta-data": Upload.json(dataToSend)},
                arrayKey: '',
                headers: {'Content-Type': undefined }
})

**Comment by benoit-nadaud** [comment]
When i look the request send by the browser in the console everything seems ok but when backend receives my string it's not considered as UTF-8

**Comment by danialfarid** [comment]
It is probably your backend. Search stackoverflow for similar Spring encoding problem. You can try to send a normal request with $http.post and see if that messes up the encoding.
