### ISSUE TITLE
Executable file upload behaves differently on Chrome, Firefox and Safari

### ISSUE THREAD

**Issue by kevinleeTCA** [danialfarid/ng-file-upload#1083]
I just found something interesting to upload a '.app' file on three different browser:
Chrome: Version 46.0.2490.71 (64-bit)
FireFox: 41.0.2
Safari: Version 8.0.5 (10600.5.17)

The properties I used from ng-file-upload is :
```
 <div .... ngf-drop ngf-multiple="true" ngf-allow-dir="false" ngf-change="uploadWithGroupSelection($files)" ng-model="files"> </div>
```
and the file will be uploaded to S3 server.
the normal file works all fine. but the application file will have problem.

The test file is in Application folder of Mac:
![11](https://cloud.githubusercontent.com/assets/6743660/10657832/7d767cda-78dc-11e5-81c0-024f899e9d69.png)
When I drag it to Chrome, it has no responds and show nothing on console. (even can not see the object 'files', did not even execute the program)

When I drag it in Firefox, I got error response while uploading, and the log says: `Cross-Origin Request Blocked`
![22](https://cloud.githubusercontent.com/assets/6743660/10657878/03fb2c4c-78dd-11e5-8ab6-6d1c73acc072.png)

When I drag it in Safari: `it will compress the file to zip and do upload`
![33](https://cloud.githubusercontent.com/assets/6743660/10657919/63a56090-78dd-11e5-90c4-7d328b6a4cf3.png)

This may related to the behaviour of the browser itself while dealing with this executable file format.

We do not wanna this kind of execute file to be uploaded, the file type like: .app, .exe, .job ... etc
My question is how can we detect this kind of format and display a message that "Sorry, this file is not allowed to upload" ? 
I can do file name validation for Firefox and Safari, but can not trace anything on Chrome.

**Comment by danialfarid** [comment]
Use ngf-pattern

**Comment by kevinleeTCA** [comment]
I try to add ngf-pattern="'!.app,!.exe'"
it seems did not work, 
Chrome still got no responses, Firefox still give console log like above, Safari still compress the file and do the upload.

How to correctly using it and handle the related validation error event ?

**Comment by danialfarid** [comment]
It all browser dependent so there is not much to be done in the plugin
