### ISSUE TITLE
"Click" flash button using JavaScript

### ISSUE THREAD

**Issue by danarmstrong** [danialfarid/ng-file-upload#1085]
Since the flash button looks very out of place in our application, we would like to hide it and trigger the click event from javascript. Is this possible? It would be nice if the experience was as consistent as possible between modern and aging browsers since we are still required to support IE9.

**Comment by danialfarid** [comment]
Why is it out of place? You can style the element as you want and the flash would appear on top of that button and no the flash has to be there so you could click on the flash object. For security reasons you cannot click on the flash object programmatically in the browsers.

**Comment by danialfarid** [comment]
If you create a jsfiddle or sample that shows how it is out of place it might be a css problem that could be fixed.

**Comment by danarmstrong** [comment]
I see this when I set html5: false, forceLoad:true on Chrome. If I hide our blue button the Choose files button is off the screen. If I set our button to transparent the same happens. Oddly enough, my coworkers do not experience this in Chrome or IE9 so I'm not sure why I do.

![image](https://cloud.githubusercontent.com/assets/4072243/10699314/0d328580-7973-11e5-9010-167abe57be34.png)

**Comment by danialfarid** [comment]
What do you mean off the screen?
In the picture it looks like it is right on the button. So what the issue is?

**Comment by danarmstrong** [comment]
It would be desirable to not have an ugly grey rectangle button sitting on top of our styled button when flash is in use. We could live with the ugly grey button if we could hide the styled button without the ugly grey button being positioned off screen. And by offscreen I mean the grey button is positioned with negative x and y positions and is not on the screen.

**Comment by danarmstrong** [comment]
I will also note that the grey button is only off screen when we set "display:none" or "color:Transparent, background-color:Transparent;" on our own button.

**Comment by danialfarid** [comment]
The grey button should have opacity zero so unless you have a css rule that overrides it for the file input elements it should stay hidden.
For the positioning it would change it's position when you hover over the actual ngf-select button and position it on top of that button, so yea initially it is off the screen but when your mouse is over that button it would be places on top of that button with zero opacity.

**Comment by danarmstrong** [comment]
That makes sense now. Thank you for clarifying. I will see if I can't figure out where in our vendor's CSS the issue is.
