### ISSUE TITLE
Not support asp.net mvc web api

### ISSUE THREAD

**Issue by sogelivable** [danialfarid/ng-file-upload#1086]

**Comment by sogelivable** [comment]
<button ngf-select="uploadFiles($files)" multiple style="width: 70px"
                                    accept="image/*">
                                {{'SelectImages' | translate}}
                            </button>

**Comment by danialfarid** [comment]
What the issue is?

**Comment by LennyLip** [comment]
@sogelivable I think, "ng-file-upload" is not related for custom server side frameworks. It is works over http protocol and you should report problem related to http protocol. Otherwise, is not issue of  "ng-file-upload"  and must to be closed.
