### ISSUE TITLE
ngf-validate-fn not fired when I manually update ng-model

### ISSUE THREAD

**Issue by brianfeister** [danialfarid/ng-file-upload#1087]
I have an "edit" form which fetches the current values from the server, fetches the file items that would be managed by the form, pushes them to the `ngModel`, and allows the user to update / edit the form.  I was using a material design `md-button` an attaching `ngf-select` to it.  After pushing these previously saved files to the ngModel array, they fail because of `"$error": { "required": true }`. When I add `ngf-validate-fn` with `ng-required="false"` the validation happens as expected. however, when I have `ngf-validate-fn="validate(val)"` (validate(val) is true in this case) + `ng-required="true"` the validation always complains about `$error: { required: true }`... I suspect that this directive is messing with `ngRequired` and setting it based on something like `$touched` which in my case is not valid.  Any ideas for fixing this?

Also, I notice that the `ngf-validate-fn` function is never actually called in the above scenario.

```
  <div layout="row">
    <md-button
      ngf-select
      ng-required="experConfigCtrl.ngRequired"
      ngf-validate-fn="experConfigCtrl.validateFileInput()"
      name="{{ experConfigCtrl.config.name }}"
      ngf-keep="true"
      ngf-multiple="{{ (experConfigCtrl.config.multiItem) ? 'true' : 'false' }}"
      ngf-accept="'{{ experConfigCtrl.config.fileTypes }}'"
      ng-model="experConfigCtrl.ngModel"
      ng-disabled="!experConfigCtrl.multiItem && experConfigCtrl.ngModel.length > 0"
      class="md-primary md-raised"
      aria-label="{{ experConfigCtrl.config.label }}">
      <md-icon size="lg" md-svg-icon="plus" alt="{{ experConfigCtrl.config.label }}"></md-icon>
      {{ experConfigCtrl.config.label }}
    </md-button>
  </div>
```

**Comment by brianfeister** [comment]
So, thinking about this a bit more, my issue is that I start with a value but make an asynchronous call to fetch the existing content items from the server. What I need is a way to call the `ngf-validate-fn` manually the resolution of my Promise call from the server.  Is there a way to call the function on the directive's scope manually?

**Comment by danialfarid** [comment]
Use `ngf-validate-async-fn`.
Also if the validation fails it won't set the model value so the required error will be shown until you choose a valid file.

**Comment by brianfeister** [comment]
Hey, sorry for the delay in following up with this.  The thing is I have a whole complex process that exists outside of what this directive should be responsible for. In my case, I'm setting an array of objects that come back from the REST server's API response.  I use those "file" object (e.g. NOT javascript `File` objects) in many places in my app.  I need a way to load up the form and pre-populate assets in the form as valid, despite them being simply lowercase `file` items rather than javascript `File` items.  I thought the `ngf-validate-fn` or `ngf-validate-async-fn` would allow me to override the validation that the directive does internally since I've decided to manage all of this in my application rather than through the directive. We have validations for types of files like "vector" - SVG, AI, and EPS files, etc. so our needs are more complex and I'm expecting a way to override the directive's default validation. Is it possible?

**Comment by danialfarid** [comment]
It is better to separate the model that is holding file from the model that is holding the url, they are separate object. The plugin is designed to accommodate file types.
But yea you can do any type of validation using those two functions.
