### ISSUE TITLE
Multiple file upload control In single form

### ISSUE THREAD

**Issue by shyamprasathbrigita** [danialfarid/ng-file-upload#1088]
Hi, I have a form with multiple file upload controls in different section. Some sections has file upload  controls which are created dynamically. 
```   
<form>
   <div class="form-group">
    <label for="exampleInputFile">File input</label>
    <input type="file" name="file1" id="exampleInputFile">
  </div>
  
 <div class="form-group">
    <label for="exampleInputFile">File input</label>
    <input type="file" name="file2" id="exampleInputFile">
  </div>
</form>

```
At the back end(laravel - php), I am not able to identify the item by control name(in above example, file1 and file2) as in normal form submit without ajax. But here all files are sending as a single array and only with filename not with the name of the control. Is there any way to get it as individual elements with its own identity (like name in control)?.

**Comment by danialfarid** [comment]
How your js upload code looks like?

**Comment by shyamprasathbrigita** [comment]
Hi danialfarid, thanks for your response.  My JS code
```
    $scope.files = [];
    $scope.onFileSelect = function($files) {
        $scope.files = $files;
    }
    
 $upload.upload({
    url: 'newupload',
    file: $scope.files,
    fields: {'data':$scope.uploadform}
  })
   .success(function(data, status, headers, config) {
   });
```
My HTML code:
```
<form>
   <div class="form-group">
    <label for="exampleInputFile">File input</label>
    <input type="file" ng-file-select="onFileSelect($files)" class="form-control" id="exampleInputFile">
  </div>

 <div class="form-group">
    <label for="exampleInputFile">File input</label>
    <input type="file" ng-file-select="onFileSelect($files)" class="form-control" id="exampleInputFile">
  </div>
</form>
```

**Comment by danialfarid** [comment]
Use the new `data` format file, fields and fileFormDataName are deprecated.
See the readme file and samples.

**Comment by LennyLip** [comment]
@shyamprasathbrigita 

please, close issue if this works.

    Upload.upload({
            url: 'upload/url',
            data: {$scope.question_file_names: $scope.question_files, 'data': $scope.elements})


etc...

**Comment by emjeon93** [comment]
I want using upload as directive.
so I'll get dynamic field's name.
whenever I need other name(not file1, file2), file3, i have to add field's name to data's key?

**Comment by emjeon93** [comment]
Oh, i resolved!

data: {
	[$scope.name]: files
}

it was solution. haha;;
