### ISSUE TITLE
Initial file in create/update Controller

### ISSUE THREAD

**Issue by Novaera** [danialfarid/ng-file-upload#1089]
Hi, I try to make a create/update controller like this:

app.controller('ClientFormCtrl', ['$scope',  '$rootScope', 'API',  '$filter', '$mdDialog', '$http', '$parse',  '$window',  'Upload',  '$cookies', '$routeParams', function ($scope, $rootScope, API, $filter, $mdDialog, $http, $parse, $window, unsavedFormWatcher, Upload, $cookies, $routeParams) {
    
    var urlclientId = '';
    var method = 'POST';
    $scope.title_form = '';
    $scope.submit_form = '';
    $scope.Model = {};
    
    if (isNaN($routeParams.clientId)){
        $scope.title_form = $filter('translate')('NEW_CLIENT');
        $scope.submit_form = $filter('translate')('SAVE');
    }else{
        urlclientId += $routeParams.clientId + '/';
        method = 'PUT';
        $scope.title_form = $filter('translate')('EDIT_CLIENT');
        $scope.submit_form = $filter('translate')('UPDATE');
    
        $http.get(API.url() + '/client/' + urlclientId).success(function (data){            
            $scope.Model = data;
        });
    }

    $scope.submitMethod = function () {
        
        Upload.upload({
            headers: {'Authorization': 'JWT ' + $cookies.get('jwt_token')},
            url: API.url() + '/client/' + urlclientId,
            data: $scope.Model,
            method: method
        }).success(function (data){
            
            $mdDialog.show(
                $mdDialog.alert()
                    .parent(angular.element(document.body))
                    .content($filter('translate')('CREATE_OK'))
                    .ariaLabel($filter('translate')('CREATE_OK'))
                    .clickOutsideToClose(true)
                    .ok($filter('translate')('CLOSE'))
            );

        });
    };

}]);

For create works perfect, but when I retrieve the image and send the updated model after the form manipulation, the fields where are the images, are sending like string "http://domain.com/media/image.png". 

When retrieve the existing model from API server, the images fields are strings: "http://domain.com/media/image.png", because the Django Server (Django REST Framework)  save the image in the disk and save in database field the url location.

How I can initialize the ngf field with only the image source string?

**Comment by danialfarid** [comment]
I don't see any file object in your code? How your html look like? How do you upload the file?
Url is different from file so if you just want to send the url to the server you don't need to use this plugin.

**Comment by Novaera** [comment]
This is the Template (Jade)

div(layout="row", layout-sm="column")
			
				md-input-container.image-upload(flex)
					md-tooltip(class="input") {{ 'CLIENT_LOGO_HELP' | translate }}
					div Logo
					
					md-button.md-raised.md-primary.clean-file(aria-label="{{ 'DELETE' | translate }}" type="button" ng-click="Model.logo = null" ng-show="Model.logo")
						i.icon-trash
						
					div(name="logo" aria-label="Logo" ngf-drop ngf-select ng-model="Model.logo" class="drop-box" ngf-drag-over-class="dragover"
						ngf-max-size="1MB" ngf-max-width="513" ngf-min-width="510" ngf-min-height="100" ngf-pattern="'image/png'" accept="image/png,")
						
						| {{ 'DROPZONE_LABEL_IMG' | translate }}
						
						div.thumbnail
							img(ng-show="ModelForm.logo.$valid" ngf-thumbnail="Model.logo")
						
					div(ng-if="ModelForm.logo.$error.maxSize" class="drop-box-error") {{ 'DROPZONE_IMG_ERROR_SIZE' | translate }}: 1 Megabyte
					div(ng-if="ModelForm.logo.$error.maxWidth || ModelForm.logo.$error.minWidth" class="drop-box-error") {{ 'DROPZONE_IMG_ERROR_DIMENSIONS_EXACT' | translate }}: 512px {{'OF' | translate}} {{'WIDTH' | translate}}
					div(ng-if="ModelForm.logo.$error.maxHeight" class="drop-box-error") {{ 'DROPZONE_IMG_ERROR_DIMENSIONS_MIN' | translate }}: 100px {{'OF' | translate}} {{'HEIGHT' | translate}}
					div(ng-if="ModelForm.logo.$error.pattern" class="drop-box-error") {{ 'DROPZONE_IMG_ERROR_FORMAT' | translate }}: PNG

**Comment by Novaera** [comment]
The file upload work without problem, but in the case when a need edit a Item saved in the database, the retrieve data of the file come in string (http://domain.com/media/image.png), so I need use this url of the image saved previously, for initialize the image field.

**Comment by danialfarid** [comment]
Keep the file and urls in separate models, they are not of the same type.

**Comment by LennyLip** [comment]
Say, I have $scope.files. How to populate this with initial array from server (having only urls to images)?
I need to create array of File objects? how to do it?

**Comment by danialfarid** [comment]
You should keep them seperate so have the files to be the ones user selects in the browser and urls are the one that coming from the server. To show them on the page you can use `ngf-thumbnail="files[i] || urls[i]"` so whichever is available will be shown.

**Comment by Novaera** [comment]
Thanks! ``` ngf-thumbnail="file || url" ``` does the trick!:

Get the model from database (I delete the attributes of images for not raise the error "e.splice" for passing a string to the model $scope.Model['logo'] because only accept files).

My Model and template have other fields (text, json and numbers) but I'll just show file fields.

```
$http.get(API.url() + '/client/' + urlclientId).success(function (response){
            
            $scope.logo = response['logo'];
            delete response['logo'];
            $scope.logo_toolbar = response['logo_toolbar'];
            delete response['logo_toolbar'];
            $scope.favicon = response['favicon'];
            delete response['favicon'];
            $scope.fondo_login = response['fondo_login'];
            delete response['fondo_login'];
            
            $scope.Model = response;
            $scope.Model['theme'] =  angular.fromJson(response['tema_json']);
            
            if(response['servidores_redireccion_json']){
                $scope.Model['servers_redirections'] =  angular.fromJson(response['servidores_redireccion_json']);
            }else{
                $scope.Model['servers_redirections'] = [];
            }
            
        });
```

And the template looks like this:

```
div(layout="row", layout-sm="column")
			
				md-input-container.image-upload(flex)
					md-tooltip(class="input") {{ 'CLIENT_LOGO_HELP' | translate }}
					div Logo
					
					md-button.md-raised.md-primary.clean-file(aria-label="{{ 'DELETE' | translate }}" type="button" ng-click="Model.logo = ''" ng-show="Model.logo")
						i.icon-trash
						
					div(name="logo" aria-label="Logo" ngf-drop ngf-select ng-model="Model.logo" class="drop-box" ngf-drag-over-class="dragover"
						ngf-max-size="1MB" ngf-max-width="513" ngf-min-width="510" ngf-min-height="100" ngf-pattern="'image/png'" accept="image/png,")
						
						| {{ 'DROPZONE_LABEL_IMG' | translate }}
						
						div.thumbnail
							img(ng-show="ModelForm.logo.$valid" ngf-thumbnail="Model.logo || logo")
						
					div(ng-if="ModelForm.logo.$error.maxSize" class="drop-box-error") {{ 'DROPZONE_IMG_ERROR_SIZE' | translate }}: 1 Megabyte
					div(ng-if="ModelForm.logo.$error.maxWidth || ModelForm.logo.$error.minWidth" class="drop-box-error") {{ 'DROPZONE_IMG_ERROR_DIMENSIONS_EXACT' | translate }}: 512px {{'OF' | translate}} {{'WIDTH' | translate}}
					div(ng-if="ModelForm.logo.$error.minHeight" class="drop-box-error") {{ 'DROPZONE_IMG_ERROR_DIMENSIONS_MIN' | translate }}: 100px {{'OF' | translate}} {{'HEIGHT' | translate}}
					div(ng-if="ModelForm.logo.$error.pattern" class="drop-box-error") {{ 'DROPZONE_IMG_ERROR_FORMAT' | translate }}: PNG
			
				md-input-container.image-upload(flex)
					md-tooltip(class="input") {{ 'CLIENT_LOGO_TOOLBAR_HELP' | translate }}
					div {{ 'LOGO_TOOLBAR' | translate }}
					
					md-button.md-raised.md-primary.clean-file(aria-label="{{ 'DELETE' | translate }}" type="button" ng-click="Model.logo_toolbar = ''" ng-show="Model.logo_toolbar")
						i.icon-trash
						
					div(name="logo_toolbar" aria-label="{{ 'LOGO_TOOLBAR' | translate }}" ngf-drop ngf-select ng-model="Model.logo_toolbar" class="drop-box" ngf-drag-over-class="dragover"
						ngf-max-size="100KB" ngf-max-width="216" ngf-pattern="'image/png'" accept="image/png,")
						
						| {{ 'DROPZONE_LABEL_IMG' | translate }}
						
						div.thumbnail
							img(ng-show="ModelForm.logo_toolbar.$valid" ngf-thumbnail="Model.logo_toolbar || logo_toolbar")
						
					div(ng-if="ModelForm.logo_toolbar.$error.maxSize" class="drop-box-error") {{ 'DROPZONE_IMG_ERROR_SIZE' | translate }}: 100 Kilobytes
					div(ng-if="ModelForm.logo_toolbar.$error.maxWidth" class="drop-box-error") {{ 'DROPZONE_IMG_ERROR_DIMENSIONS_MAX' | translate }}: 215px {{'OF' | translate}} {{'WIDTH' | translate}}
					div(ng-if="ModelForm.logo_toolbar.$error.pattern" class="drop-box-error") {{ 'DROPZONE_IMG_ERROR_FORMAT' | translate }}: PNG

			div(layout="row", layout-sm="column")
			
				md-input-container.image-upload(flex)
					md-tooltip(class="input") {{ 'FAVICON_HELP' | translate }}
					div {{ 'FAVICON' | translate }}
					
					md-button.md-raised.md-primary.clean-file(aria-label="{{ 'DELETE' | translate }}" type="button" ng-click="Model.favicon = ''" ng-show="Model.favicon")
						i.icon-trash
						
					div(name="favicon" aria-label="{{ 'FAVICON' | translate }}" ngf-drop ngf-select ng-model="Model.favicon" class="drop-box" ngf-drag-over-class="dragover"
						ngf-max-size="100KB" ngf-min-width="192" ngf-min-height="192" ngf-max-width="193" ngf-max-height="193" ngf-pattern="'image/png'" accept="image/png,")
						
						| {{ 'DROPZONE_LABEL_IMG' | translate }}
						
						div.thumbnail
							img(ng-show="ModelForm.favicon.$valid" ngf-thumbnail="Model.favicon || favicon")
						
					div(ng-if="ModelForm.favicon.$error.maxSize" class="drop-box-error") {{ 'DROPZONE_IMG_ERROR_SIZE' | translate }}: 100 Kilobytes
					div(ng-if="ModelForm.favicon.$error.maxWidth || ModelForm.favicon.$error.minWidth || ModelForm.favicon.$error.maxHeight || ModelForm.favicon.$error.minHeight" class="drop-box-error") {{ 'DROPZONE_IMG_ERROR_DIMENSIONS_EXACT' | translate }}: 192px {{'OF' | translate}} {{'WIDTH' | translate}} {{'BY' | translate}} 192px {{'OF' | translate}} {{'HEIGHT' | translate}}
					div(ng-if="ModelForm.favicon.$error.pattern" class="drop-box-error") {{ 'DROPZONE_IMG_ERROR_FORMAT' | translate }}: PNG
			
				md-input-container.image-upload(flex)
					md-tooltip(class="input") {{ 'CLIENT_BACKGROUND_HELP' | translate }}
					div {{ 'CLIENT_BACKGROUND' | translate }}
					
					md-button.md-raised.md-primary.clean-file(aria-label="{{ 'DELETE' | translate }}" type="button" ng-click="Model.fondo_login = ''" ng-show="Model.fondo_login")
						i.icon-trash
						
					div(name="fondo_login" aria-label="{{ 'FAVICON' | translate }}" ngf-drop ngf-select ng-model="Model.fondo_login" class="drop-box" ngf-drag-over-class="dragover"
						ngf-max-size="2MB" ngf-min-width="1440" ngf-max-width="1920" ngf-min-height="900" ngf-max-height="1080" ngf-pattern="'image/jpeg'" accept="image/jpeg,")
						
						| {{ 'DROPZONE_LABEL_IMG' | translate }}
						
						div.thumbnail(ngf-as-background="true" ngf-thumbnail="Model.fondo_login || fondo_login")
						
					div(ng-if="ModelForm.fondo_login.$error.maxSize" class="drop-box-error") {{ 'DROPZONE_IMG_ERROR_SIZE' | translate }}: 2 Megabyte
					div(ng-if="ModelForm.fondo_login.$error.minWidth" class="drop-box-error") {{ 'DROPZONE_IMG_ERROR_DIMENSIONS_MIN' | translate }}: 1440px {{'OF' | translate}} {{'WIDTH' | translate}}
					div(ng-if="ModelForm.fondo_login.$error.maxWidth" class="drop-box-error") {{ 'DROPZONE_IMG_ERROR_DIMENSIONS_MAX' | translate }}: 1920px {{'OF' | translate}} {{'WIDTH' | translate}}
					div(ng-if="ModelForm.fondo_login.$error.minHeight" class="drop-box-error") {{ 'DROPZONE_IMG_ERROR_DIMENSIONS_MIN' | translate }}: 900px {{'OF' | translate}} {{'HEIGHT' | translate}}
					div(ng-if="ModelForm.fondo_login.$error.maxHeight" class="drop-box-error") {{ 'DROPZONE_IMG_ERROR_DIMENSIONS_MAX' | translate }}: 1080px {{'OF' | translate}} {{'HEIGHT' | translate}}
					div(ng-if="ModelForm.fondo_login.$error.pattern" class="drop-box-error") {{ 'DROPZONE_IMG_ERROR_FORMAT' | translate }}: JPG
```


By the way, great plugin! very useful !
