### ISSUE TITLE
Redundancy in bower installs?

### ISSUE THREAD

**Issue by Tathanen** [danialfarid/ng-file-upload#1090]
Maybe a stupid question, but is there any real difference between `ng-file-upload` and `ng-file-upload-shim` on bower?  As far as I can tell they both contain all of the base and shim files, they just have slightly different readmes.  And I guess the license file isn't in the shim installation.

**Comment by danialfarid** [comment]
the main file in bower.json is different, so if you want to automatically include the js file with command line like yo, you can use that, but otherwise if you add them manually to the html they are the same one of them should be enough.

**Comment by Tathanen** [comment]
Gotcha. :+1:
