### ISSUE TITLE
TypeError: Cannot read property '$ngfDataUrl' of null

### ISSUE THREAD

**Issue by LeleDev** [danialfarid/ng-file-upload#1092]
I'm using the ```Upload.base64DataUrl(file)``` function. If I upload files that don't match the requirements (for example ngf-max-size="'1MB'"), or files that are not images (like .zip archives), i get the following error in the console:
```
TypeError: Cannot read property '$ngfDataUrl' of null
```

To reproduce the error, upload some not-valid images (for example, bigger than 1MB) or file types (.zip archive, pdf, etc.) using this fiddle:
http://jsfiddle.net/3t50b3fw/783/

I think there should be an error management also for Upload.base64DataUrl promises, calling the fail function if something goes wrong and passing to it the error details

Ah, with some images I also get the following error, but don't know if it is releated to the same issue or not:
```
Not a valid marker at offset 623, found: 245
```

**Comment by danialfarid** [comment]
Check if the file is null first: http://jsfiddle.net/3t50b3fw/784/

**Comment by danialfarid** [comment]
For the marker error that should be fine, this is to read exif info of the image and do the possible rotation based on orientation. You can disable this feature by Upload.defaults['ngfFixOrientation']=false; or added `ngf-fix-orientation="false"` to the input file.

**Comment by LennyLip** [comment]
@danialfarid Thanks for ngf-fix-orientation="false" . But how to just disable error log with ngf-fix-orientation="true"?

**Comment by LeleDev** [comment]
Thank you. But what about the error management (pattern, max width, etc.) for base64 images?

**Comment by danialfarid** [comment]
@LeleDev What about them?

**Comment by LeleDev** [comment]
Currently, the ```Upload.base64DataUrl``` promises seems to support only the 'success' function (for resolved promises)... shouldn't be there also an 'error' function (rejected promises) support, in case of some test fail (for example, ngf-max-size)? Just as in the ```Upload.upload function```? 

I'm referring to this one:
```
function (response) {
      if (response.status > 0)
        $scope.errorMsg = response.status + ': ' + response.data;
}
```

**Comment by danialfarid** [comment]
The validations happen before you select the file and are set as directives on html input file. base64DataUrl would call the error function if it cannot convert the file to base64 format.

**Comment by LeleDev** [comment]
Ok I got it (maybe a little note on docs could help also other people), thank you!

**Comment by krisb2007** [comment]
Hi,

Tried getting rid of the Not a valid marker at offset ** issue by setting ngf-fix-orientation="false" but then I lose the image preview. Here's the markup Im using...perhaps there's a better way?
<td ng-repeat="file in files">
          <img class="img-rounded" width="100" height="100" ng-src="{{file.$ngfDataUrl}}">
 </td>

Using file.name doesn't work cause it looks for the file on the server and not the client.

**Comment by danialfarid** [comment]
Use ngf-src or ngf-thumbnail
