### ISSUE TITLE
Could not make ngf-validate-async-fn to work

### ISSUE THREAD

**Issue by allenhwkim** [danialfarid/ng-file-upload#1093]
Thanks for this nice directive. All works fine as expected, but could not make `ngf-validate-async-fn` to work.

http://plnkr.co/edit/P4PxZA?p=preview

As you see in this example. the validateRatio function always fails although it has a valid width and height.

```
    angular.module('testApp').controller('myCtrl', function($scope, $q, Upload){
      $scope.validateRatio = function(image) {
        var defer = $q.defer();
        Upload.imageDimensions(image).then(function(d) {
          console.log('d', d, d.width>d.height,  d.width < d.height*2);
          if (d.width>d.height && d.width < d.height*2) { // 1:1 - 2:1
            defer.resolve()
          } else { // 1:1 - 2:1
            defer.reject();
          }
        }, function(err) {
         defer.reject(err);
        });
        return defer.promise;
      };
    });
```

```
  <div class="simple_drag_drop_zone_div marginBottomQuarter"
      ngf-select ngf-drop
      ng-model="files"
      ngf-model-invalid="invalidFiles"
      ng-model-options="{debounce:100}"
      ngf-multiple="multiple"
      ngf-pattern="'image/jpeg,image/png'"
      accept="'image/*,audio/*,video/*'"
      ngf-capture="'camera'"
      ngf-drag-over-class="dragover"
      ngf-validate="{
        size: {max: '25MB', min: '1KB'},
        height: {max: 5000},
        width: {max: 5000},
        duration: {max: '5m'}
      }"
      ngf-validate-fn="validateRatio($file)"
      ngf-validate-async-fn="validateRatio($file)"
      ngf-keep="'distinct'"
      ngf-drop-available="dropAvailable">
     Drop file here, or click to browse
  </div>
```

**Comment by danialfarid** [comment]
It is because you have `ngf-validate-fn="validateRatio($file)"` which is a sync call and since it returns a value it means that the validation is failed for that reason. If you are returning a promise it should on on async validation only. 

Also why don't you use `ngf-ratio` for the validation of the image ratio?

**Comment by allenhwkim** [comment]
Thanks for the quick reply. However, I still could not make it work without  `ngf-validate-fn="validateRatio($file)"`.  
The following the simplified example only with `ngf-validate-async-fn`.

http://plnkr.co/edit/WV1h9n?p=preview

As you see in the example above, the result of the valid and invalid state is reversed. valid is invalid and invalid is valid.

```
      $scope.validateRatio = function(image) {
        var defer = $q.defer();
        Upload.imageDimensions(image).then(function(d) {
          var ratio = $scope.ratio = (d.width / d.height);
          if (ratio >=1 && ratio <= 2) { // 1:1 - 2:1
            $scope.valid = true;
            defer.resolve(image)
          } else { 
            $scope.valid = false;
            defer.reject('invalid ratio');
          }
        });
        return defer.promise;
      };
```

Also about ratio, I believe that code is only checking the exact ratio, not between min an max ratio.
As you see in this example, 

http://plnkr.co/edit/e0XJJL?p=preview

```
    <div style="border:1px dotted black;height:100px"
      ngf-select ngf-drop
      ng-model="files"
      ngf-model-invalid="invalidFiles"
      ngf-multiple="multiple"
      ngf-pattern="'image/jpeg,image/png'"
      ngf-ratio="1.0,1.1,1.2,1.3,1.4,1.5,1.6,1.7,1.8,1.9,2.0">
```

**Comment by danialfarid** [comment]
Make the promise to resolve to true or false depending on the validation instead of rejecting it for now.
I will make some changes for the next version to simplify that.
The validation assumes that the promise will resolve into true for valid files and false for invalid files. Rejection is for a system error which could be controlled by force validation to assume the file valid or invalid.

**Comment by vishwask007** [comment]
I am also having trouble in validating ngf-ratio, ngf-max-height etc in input file tag like 
<div>
            <input type="file" ngf-select="checkImg($file)" ng-model="myfile" name="file" accept="image/*"  ngf-ratio="1x2" ngf-max-height="100" required />
             {{contentForm.file}}
             <i ng-show="form.file.$error.required">*required</i><br>
             <i ng-show="form.file.$error.maxHeight">File height error</i>
<i ng-show="form.file.$error.ratio">ratio error</i>
          </div>
I am not able to see the error messages once I select an image file.
Can you please help me resolving this? Is the validation only occurs when you upload file?

**Comment by danialfarid** [comment]
@vishwask007 Please open another issue this is not related to ngf-validate-async

**Comment by armangevorgyan** [comment]
Hi @danialfarid  
ngf-ratio="8" not working ?? maybe  because in JS 8000/1000 = 7.994082840236686, 
and how i can us it for 0.3 < width/height < 8 ??
can  i ask why height=1000px width=8000px => console show ngfWidth = 1351, ngfHeight = 169,
Thank you. Sorry for bad English ))
