### ISSUE TITLE
Not a valid marker at offset ***, found: ***

### ISSUE THREAD

**Issue by myrepo1010** [danialfarid/ng-file-upload#1094]
When I try to drag and drop an image sometimes I get:

    Not a valid marker at offset 1009, found: 159 angular.js:12477:18
    consoleLog/<() angular.js:12477
    $ExceptionHandlerProvider/this.$get</<() angular.js:9246
    timeout/timeoutId<() angular.js:17858
    completeOutstandingRequest() angular.js:5507
    Browser/self.defer/timeoutId<()

This is the controller I use:

    app.controller('AvatarCtrl', function ($scope, Upload, $timeout) {
        $scope.file = null

        $scope.$watch('file', function () {
            $scope.upload($scope.file)
        })

        $scope.log = ''

        $scope.upload = function (file) {
        if(!file)
            return
        if (!file.$error) {
            Upload.upload({
                url: '/api/avatar',
                data: {
                    avatarImage: file
                }
            }).progress(function (evt) {
                var progressPercentage = parseInt(100.0 * evt.loaded / evt.total)
                $scope.log = 'progress: ' + progressPercentage + '% ' + evt.config.data.avatarImage.name + '\n' + $scope.log
            }).success(function (data, status, headers, config) {
                $timeout(function() {
                    $scope.log = 'file: ' + config.data.avatarImage.name + ', Response: ' + JSON.stringify(data) + '\n' + $scope.log
                })
            })
          }
        }
      })

while this is the view (I'm using Jade):

    div(ng-controller='AvatarCtrl')
      div(ngf-drop='', ngf-select='', ng-model='file', class='drop-box', ngf-drag-over-class='dragover', ngf-multiple='false', ngf-allow-dir='true',
        accept='image/png,image/jpeg', ngf-pattern="'image/png,image/jpeg'") Drop png or jpg images here or click to upload
      div(ngf-no-file-drop='') File Drag/Drop is not supported for this browser
      pre {{ log }}
The progress seems to stop always at 90% 95%.

**Comment by LennyLip** [comment]
see here 

https://github.com/danialfarid/ng-file-upload/issues/1092

**Comment by fredtma** [comment]
Has this been solved? I am getting the same error

**Comment by myrepo1010** [comment]
Turned out that the blocking error I was receiving was a server one. But still I receive this error when I drag and drop an image. However it seems not affect the correct behavior of the widget.
