### ISSUE TITLE
does not work preview/pattern and etc in Internet Explorer 11

### ISSUE THREAD

**Issue by LennyLip** [danialfarid/ng-file-upload#1095]
In this fiddle
http://jsfiddle.net/danialfarid/maqbzv15/38/

Chrome, FireFox is ok. But in IE11 preview image does not work.  (Windows 8 OS)
It only flashed while form  is in an being  POSTing procces (by clicking "submit").

I think IE create FILE object only after submit or somthing like that, because with
ngf-pattern="'image/*'" i can not to select images (test, that selected FILE is image fails - but it is realy image) also.

How can i fix this? thanks!

**Comment by LennyLip** [comment]
any suggestions?

**Comment by danialfarid** [comment]
Works for me on IE11, Make sure you select a proper image.

**Comment by LennyLip** [comment]
@danialfarid does not work for me. left ie, right chrome. same image.

i think it is also https://github.com/danialfarid/ng-file-upload/issues/1116  related
![preview](https://cloud.githubusercontent.com/assets/955994/11022222/70b2277e-866a-11e5-8650-f25fb3b3909b.png)

**Comment by danialfarid** [comment]
It might be your image, try different image regular jpeg file or post your image here

**Comment by LennyLip** [comment]
i tried to use different images... i think it is no problem with images (i think IE does not create FILE object after select image).

IE 11.0.9600.18053

**i think it is also https://github.com/danialfarid/ng-file-upload/issues/1116  related**

![155988010](https://cloud.githubusercontent.com/assets/955994/11025708/f92c5dbe-86af-11e5-8446-f4acffe3fcb5.jpg)
![shop_items_catalog_image334111](https://cloud.githubusercontent.com/assets/955994/11025871/61df581e-86b2-11e5-9207-e621f6b9893a.jpg)

**Comment by danialfarid** [comment]
I have IE 11.0.18 on Win7 and the images you posted are working fine.
It could be an IE plugin interfering or something. Is there any error in the console? Can you try it on a different machine?

**Comment by LennyLip** [comment]
Hmm, tri same IE 11.0.9600.18053 (also win8) on another notebook machine and It works.
This is strange, i will try to find problem.

1. no errors in console.
2. no plugings at all.

**Comment by LennyLip** [comment]
1. Tried to reset IE settings (+do not use recommended settings). Not helped.
2. Tried to reset IE settings (+use recommended settings). Not helped.
3. https://html5test.com/index.html are the same for ie browsers, except Pointer-events (AFAIK css4).
4. http://jsfiddle.net/maqbzv15/224/ File object is created, but IE, that no works, has empty File type attribute:

[object File]
   {
      [functions]: ,
      __proto__: { },
      constructor: { },
      lastModifiedDate: [date] Wed Apr 17 2013 08:37:06 GMT+0400 (RTZ 2 )),
      name: "1.jpg",
      size: 1362889,
      type: ""
   }

why it can be happened?

**Comment by danialfarid** [comment]
Well, it's IE!
Maybe ask on stackoverflow or file a bug for IE11.
