### ISSUE TITLE
How i abort upload in angular js

### ISSUE THREAD

**Issue by juniorkid** [danialfarid/ng-file-upload#1096]
I want to cancel upload in angular js by use function .  I try to use upload.abort() but it has error .
Can  I use another function to cancel upload ??

thank you

**Comment by LennyLip** [comment]
I think , you should paste error log here

**Comment by juniorkid** [comment]
This is my code in angular js
      $scope.$on('$locationChangeStart', function(event) {
        console.log("IS CLICK : "  + $scope.isClick);

          // check when upload isn't complete
          if ($scope.isClick) {
             var r = confirm("Are you sure to leave this page ?");
             if(r == false) {
               event.preventDefault();
             }
             else {
                // Cancle upload
                upload.abort();
                $http.post('/api/cancelUploadPHR')
             }
          }
      });

and this is error

ReferenceError: upload is not defined
    at script.js:377
    at n.$broadcast (angular.js:16311)
    at angular.js:12292
    at n.$eval (angular.js:15989)
    at n.$digest (angular.js:15800)
    at n.$apply (angular.js:16097)
    at HTMLHtmlElement.<anonymous> (angular.js:12226)
    at HTMLHtmlElement.n.event.dispatch (jquery.js:4435)
    at HTMLHtmlElement.r.handle (jquery.js:4121)

**Comment by LennyLip** [comment]
this is not ng-file-upload issue

you variable upload does not defined:
     ReferenceError: upload is not defined

read docs https://github.com/danialfarid/ng-file-upload#upload-service

**Comment by juniorkid** [comment]
Now I defined it but it has this problem
TypeError: m_upload.abort is not a function
    at script.js:379
    at n.$broadcast (angular.js:16311)
    at angular.js:12292
    at n.$eval (angular.js:15989)
    at n.$digest (angular.js:15800)
    at n.$apply (angular.js:16097)
    at HTMLHtmlElement.<anonymous> (angular.js:12226)
    at HTMLHtmlElement.n.event.dispatch (jquery.js:4435)
    at HTMLHtmlElement.r.handle (jquery.js:4121)

angular js code
var m_upload;

$scope.upload = function (file) {
          m_upload =  Upload.upload({
                url: ...
                data: ...
              }

            }).then(function (resp) {
                ....
            }, function (resp) {
                ....

            }, function (evt) {
                ...
            })
            .finally(function(){
               .....
            });
       
        };

**Comment by juniorkid** [comment]
$scope.$on('$locationChangeStart', function(event) {
        console.log("IS CLICK : "  + $scope.isClick);

          // check when upload isn't complete
          if ($scope.isClick) {
             var r = confirm("Are you sure to leave this page ?");
             if(r == false) {
               event.preventDefault();
             }
             else {
                // Cancle upload
                m_upload.abort();
                $http.post('/api/cancelUploadPHR')
             }
          }
      });

**Comment by LennyLip** [comment]
i think you not call $scope.upload() (bad name BTW!) and m_upload does not initialized.

**Comment by LennyLip** [comment]
please, create fiddle http://jsfiddle.net/

**Comment by juniorkid** [comment]
Ok i will try to create .

**Comment by LennyLip** [comment]
Try 

   // Cancle upload
   console.log(m_upload);
   m_upload.abort();

**Comment by juniorkid** [comment]
I can't create in fiddle because it's large and I'm beginner in angular js .
But I will try follow your suggestion.After i try it , I will tell you

**Comment by juniorkid** [comment]
when i print in console result is
 [object Object]

**Comment by juniorkid** [comment]
when i print key and value result is
KEY : $$state VALUE: [object Object]

**Comment by LennyLip** [comment]
upload object must be like that (try to see it in chrome dev tools)

this is not ng-file-upload issue and must be closed.
![chrome](https://cloud.githubusercontent.com/assets/955994/10715252/90661df0-7b20-11e5-8c84-5962d9bc7b1f.png)

**Comment by juniorkid** [comment]
![image](https://cloud.githubusercontent.com/assets/8817242/10715268/bede18b4-7b42-11e5-9bca-0923f5deb423.png)

**Comment by LennyLip** [comment]
I don't known what is mutler, but  "Multer is a node.js middleware" . I think it server side feature.
You m_upload is not Upload.upload() instance.

**Comment by juniorkid** [comment]
How can i defined m_upload to be a instance of Upload.upload() ?
Don't it can defined by this code?
m_upload = Upload.upload () ??

**Comment by juniorkid** [comment]
I can solve this problem by use http://jsfiddle.net/danialfarid/0mz6ff9o/135/ to be way to define Upload.upload

Thank you for your suggestion.
And sorry in my poor english.

**Comment by LennyLip** [comment]
m_upload = Upload.upload ()

must be 

     m_upload = Upload.upload(...);

please, close issue

**Comment by knifedge** [comment]
I tried searching many forums for aborting file upload, i get following error
 ->  TypeError: Upload.abort is not a function

**Comment by JanuszCh** [comment]
@knifedge 
I had the same issue.
Try this:
```
currentUpload = this.Upload.upload({
// something...
});
currentUpload.then({
// something
});
currentUpload.abort();
```
Just assign to `currentUpload` only `IUploadPromise` from `Upload.upload` without `then`.
