### ISSUE TITLE
[Req] Allow configuring default options for ngfSelect/ngfDrop

### ISSUE THREAD

**Issue by hackel** [danialfarid/ng-file-upload#1097]
It would be useful if I could specify default (or common) options for ngfSelect and ngfDrop so that I'm not  cluttering my template with a bunch of repeated attributes.  Basically, I would like to do this:
```js
myApp.config(ngfDrop => {
  ngfDragOverClass = 'dragover',
});
```
Another viable option would be to add `ngf=options="myCtrl.ngfOptions"` or something so that they could be configured in the controller for multiple fields.  The biggest use-case for this is allowing to drag files *and* have a button to click with the exact same options (without repeating code).  I realise I could probably do this myself by wrapping ngfDrop/Select in another directive and using ng-attr-* to set the values dynamically from a passed-in controller variable, but it seems like something that might be useful enough to add to the directive itself.

**Comment by danialfarid** [comment]
Use 'Upload.defaults={ngfSelect: '....', ...}`

**Comment by hackel** [comment]
Ha, thanks.  I just discovered this myself and came to close this report.  Is this the right way to do it, as opposed to setting the default values using a .config() call?

**Comment by danialfarid** [comment]
move defaults to config

**Comment by danialfarid** [comment]
Or you can do 
```
myApp.config(["Upload", function(Upload) {
  Upload.setDefaults({ngfSelect: '....', ...})
}]);
```
