### ISSUE TITLE
Can't change Content-Disposition name "file"

### ISSUE THREAD

**Issue by gaprl** [danialfarid/ng-file-upload#11]
At the current version, it's not possible to change the **Content-Disposition** property **"name"**. See line [87](http://github.com/danialfarid/angular-file-upload/blob/master/angular-file-upload.js#L87).

Here's an example of the header:

```
Content-Disposition: form-data; name="file"; filename="filename.jpg"
Content-Type: image/jpeg
```

It would be good if we could change it :-)

**Comment by v-andrew** [comment]
Is config param "fileFormDataName" available?

I set
>Upload.setDefaults({ fileFormDataName: "uploadDialog$ctl00$ctl00$fileUpload$ctl00$ctl00$uploadInput" });

and still is sends
>Content-Disposition: form-data; name="file";

I tried to insert it to different places of Upload.upload({..}) and it didn't work.

Please help.

**Comment by danialfarid** [comment]
@v-andrew that option was deprecated and removed while ago, look at the `data` option in the readme file: `data: {newFileKey: myFile}`
