### ISSUE TITLE
mobile device not working

### ISSUE THREAD

**Issue by pouu69** [danialfarid/ng-file-upload#1100]
i'm use ng-select in button tag 

so when click button(upload) my phone (samsung galaxy s5) , not action in my phone.

originally ng-file-upload is restrict  phone device????

**Comment by leibler** [comment]
same problem here :-(
chrome mobile doesn't work on samsung galaxy s3 and asus memo pad

**Comment by danialfarid** [comment]
Can you try the demo page?

**Comment by pouu69** [comment]
im fixed it 
you should change lates version .js

**Comment by leibler** [comment]
Hi, i tried it with latest version and `<button>` method still does not work on android (e.g. Samsung S3).
I created a small app to test it:
http://leo.eibler.at/tests/angularui+material+ngupload/

If you push the button `<button>` nothing happens. if you push the `<input ...>` everything works fine.

regards,
Leo

**Comment by danialfarid** [comment]
@leibler does the demo page work?

**Comment by leibler** [comment]
yes, demo page works, but the demo page also uses `<input type="file" ngf-select ...` and not `<button ...>`

**Comment by danialfarid** [comment]
if you click on the upload area of the demo page it is a div not an input file.

**Comment by ghoullier** [comment]
Hi!

I've got the same problem with ngFileUpload and ngMaterial

```html
<button ngf-select ngf-multiple="false" ngf-capture="'camera'" ngf-accept="'image/*'" ngf-pattern="'image/*'">Select</button>
```

This code works on iOS with the follow module dependencies
```js
angular.module('demo', [
  'ng',
  'ngFileUpload'
])
```

But it doesn't work if I add 'ngMaterial' dependency ...
```js
angular.module('demo', [
  'ng',
  'ngMaterial',
  'ngFileUpload'
])
```

**Comment by macool** [comment]
seems to work on my iPhone 6 but just realised doesn't trigger with a `div` tag on my iPhone 5C - `input type=file` seems to work, but will continue to look at it as our markup currently contains stuff inside the uploader `div`

**Comment by adamelevate** [comment]
+1 

Using Angular Material as well, and nothing but an "input type='file'" will trigger the file upload prompt on iphone 5/6. Tried using a label to style, but the label only triggers sometimes...
