### ISSUE TITLE
Progress bar always show 100 percentage or inconsistent when uploading to localhost

### ISSUE THREAD

**Issue by pramodwerea** [danialfarid/ng-file-upload#1101]
Use case 1: when trying to upload single file (around ~ 4MB and even more) to the localhost server, it shows 100 % progress bar value although file upload is not completed

Use case 2: when I try same code base on the AWS server shows correctly the progress bar

What and where could be the problem?

Thanks!

**Comment by danialfarid** [comment]
Transferring file on local machine network is fast and almost instant, so that's why you see 100 right away. Try a 1 GB file and you will see the progress.
