### ISSUE TITLE
Validation for limiting documents of type .doc, .docx, .pdf etc

### ISSUE THREAD

**Issue by roymj88** [danialfarid/ng-file-upload#1102]
Hi,

Is there a way to allow only certain file extensions to be uploaded?

```
ngf-pattern=" '.pdf, .doc, .docx' " 
accept=" '.pdf, .doc, .docx' "
```

Thanks 
Roy

**Comment by danialfarid** [comment]
Yes what you have here should work. No need for space after comma.
For accept no need for single quote. 
`accept=".pdf,.doc,.docx"`

**Comment by roymj88** [comment]
Okay that is great. Thanks @danialfarid.
