### ISSUE TITLE
Plugin not working in AngularJs Latest version

### ISSUE THREAD

**Issue by ranjithitwizard** [danialfarid/ng-file-upload#1104]
Why this ng-file-upload not working in latest angular versions? I'm using angular 1.4.7 version. It supports upto 1.2.29 only. Can anyone answer for this?
[See here](https://angular-file-upload.appspot.com/#/1.4.7)

**Comment by danialfarid** [comment]
That was an issue with the demo code which is fixed now, the plugin code has not changed.
