### ISSUE TITLE
ngf-drag-over-class bug

### ISSUE THREAD

**Issue by aliksend** [danialfarid/ng-file-upload#1105]
Hello 
I have founded a small bug:
Following documentation this forms and equivalent: 
`ngf-drag-over-class="myDragOverClass"` and
`ngf-drag-over-class="{accept: 'myDragOverClass'}"` 
But first is not working while second is working as expected

**Comment by danialfarid** [comment]
What is not working on the first one?

**Comment by aliksend** [comment]
Open [this example](http://jsfiddle.net/danialfarid/s8kc7wg0/112/) and change value of `ngf-drag-over-class` of dropzone to other (for example to `"myDragOverClass"`) (and also you can change css to match this class instead of `dragover` to see results immediately). 
Press Run and after the page is loaded try to upload file using drag&drop.
Using Chrome Dev Tools I can see that while I moving file over dropzone it obtain new class (as expected), but not my class that I specify into `ngf-drag-over-class` attribute but `"dragover"`. And changed css style is also non-working. 
Second form (`ngf-drag-over-class="{accept: 'myDragOverClass'}"`) is working correct.

**Comment by danialfarid** [comment]
It should be `ngf-drag-over-class="'myDragOverClass'"` fixed the jsfiddle.
