### ISSUE TITLE
Object doesn't support property or method 'upload'

### ISSUE THREAD

**Issue by ment0sman** [danialfarid/ng-file-upload#1106]
I am having an issue in IE11 and Chrome 43.0.2357.81 when I try to call the Upload.upload function using the documentation in the demo page:

file.upload = Upload.upload({
                    url: 'myaddress/file',
                    data: { file: file }
                });

Any idea why it is failing? I have the shim file loading before the main ng-file-upload.js.

Thanks!

**Comment by danialfarid** [comment]
What line is throwing that error?

**Comment by ment0sman** [comment]
Here is the line:

$scope.AddArticle = function (Article, file) {

            if (file && file.size) {
                file.upload = Upload.upload({
                    url: '',
                    data: { file: file }
                });
            } else {

**Comment by cameronjroe** [comment]
Is the file you're passing into $scope.AddArticle an object?

**Comment by ment0sman** [comment]
No that is just a function called on ng click. Let me know I can post more
of the code.

**Comment by danialfarid** [comment]
Post more code or better create a jsfiddle.

**Comment by ment0sman** [comment]
Thanks for the prompt response, there was another module I was using and injecting it after the Upload module resolved the issue... was something weird with dependency injection causing it but it is resolved now with shifting that around.
