### ISSUE TITLE
File not getting sent to s3

### ISSUE THREAD

**Issue by cameronjroe** [danialfarid/ng-file-upload#1107]
I'm trying to upload to an s3 bucket and I've gotten it to work with a demo, however when I try to plug in my own file, it's not attaching the file for upload. The file exists in the function scope, but doesn't show up in the request payload.

#### Upload
```
function uploadFile(options) {
  var file = options.file,
  s3Params = options.data;
    return Upload.upload({
        url: 'https://my-bucket.s3.amazonaws.com/',
        data: {
            'key': 's3UploadExample/'+ Math.round(Math.random()*10000) + '$$' + file.name,
            'AWSAccessKeyId': s3Params.AWSAccessKeyId,
            'acl': 'public-read',
            'Content-Type': file.type,
            'success_action_status': '201',
            'Policy': s3Params.s3Policy,
            'Signature': s3Params.s3Signature,
            file: file
         }
       });
}
```
#### Request Payload
```
{..., "file":{}}
```

**Comment by cameronjroe** [comment]
I should mention it's an audio file.

**Comment by danialfarid** [comment]
it may not show the file content in the console log see the network tab and see if the file is being sent there.

**Comment by cameronjroe** [comment]
That's where I looked. Not getting anything.

**Comment by cameronjroe** [comment]
Upgraded to `9.1.1` fixed it.
