### ISSUE TITLE
File size seems wrong

### ISSUE THREAD

**Issue by thibauds** [danialfarid/ng-file-upload#1110]
Hi,
I try to get the file size but it seems to be wrong for some files (see below):
http://jsfiddle.net/ew4jakn5/175/
For some reason I can't explain the file is converted to a Blob.

Following is converted to Blob (size seems wrong).
![blob](https://cloud.githubusercontent.com/assets/5623472/10868481/efe3a030-808f-11e5-9894-c92178915494.jpg)

Following is not converted to Blob (size is correct).
![file](https://cloud.githubusercontent.com/assets/5623472/10868479/e9a79014-808f-11e5-9bbb-915aba18ed28.jpg)

Tested on FF 41.0.2 and Chrome 46.0.2490.80

**Comment by danialfarid** [comment]
Fixed at version 9.1.2.
The issue was that it tries to fixed the exif orientation even for value 1.

**Comment by thibauds** [comment]
So fast ! Thank you !
