### ISSUE TITLE
Upload multiple and get responses in an array

### ISSUE THREAD

**Issue by manikmi** [danialfarid/ng-file-upload#1114]
Hi,

I am using the ng-file-upload (multiple) with my angular js project with node js on the backend.
I have made an api on node js to upload the files and then return back some data in the json format. For a single I am able to get the data. But if i upload multiple files, I am not getting. Am I doing anything wrong?

HTML:
<div class="button" ng-model="files" ngf-select="uploadFiles($files)" ngf-max-size="10MB"
ngf-multiple="multiple" ngf-keep="keep" multiple="multiple">Upload</div> 

Controller:
$scope.uploadFiles = function (files) {
	var upload = Upload.upload({url: "URL",
		data: {file: files},
		arrayKey: '[i]'});
	upload.then(function(resp) {
		// file is uploaded successfully
		debugger
		//Not Getting Array of resp.data
		//console.log('file ' + resp.data.filename + ' is uploaded successfully. Response: ' + resp.data);
	}, function(resp) {
		// handle error
	}, function(evt) {
		// progress notify
		//console.log('progress: ' + parseInt(100.0 * evt.loaded / evt.total) + '% file :'+ evt.data.filename);
	});
}

**Comment by danialfarid** [comment]
Could be the way you read the file on the server. Btw arrayKey default value is [i] so you can remove it

**Comment by manikmi** [comment]
Thanks Danial, I was making a mistake in the Api. It was returning a single response. Fixed it.
