### ISSUE TITLE
Nuget problem

### ISSUE THREAD

**Issue by raysefo** [danialfarid/ng-file-upload#1115]
Hi,

I am getting error when try to install nuget package.

nstall-Package : An error occurred while retrieving package metadata for 'angular-file-upload' from source 'https://github.com/'.
At line:1 char:1
+ Install-Package angular-file-upload
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by danialfarid** [comment]
Post it on stackoverflow

**Comment by shanezheng** [comment]
@raysefo I think you did NOT specify the correct source. Try make sure you have the correct source configured. "https://www.nuget.org/api/v2/" is the official source for Nuget.
