### ISSUE TITLE
IE 11 input displays the entire file path, not just file name

### ISSUE THREAD

**Issue by dhintze** [danialfarid/ng-file-upload#1116]
In Chrome/FF, the input field displays the filename only.  In IE11, it's displaying the whole path.  I don't want the path to be displayed.  Is there a way to correct this?

![image](https://cloud.githubusercontent.com/assets/5423344/10912096/e40151e0-8215-11e5-8fb0-cfeb7270e301.png)

**Comment by danialfarid** [comment]
Use button and show the file name by {{file.name}}

**Comment by Murali54** [comment]
@dhintze This link might help

http://stackoverflow.com/questions/2200100/input-type-file-for-ie-gives-full-path-need-file-name-only
