### ISSUE TITLE
Is it possible to update  width and height of ngf-resize after file has been selected? 

### ISSUE THREAD

**Issue by vanbergcamp** [danialfarid/ng-file-upload#1117]
I would like to reduce quality of image before image upload. I tried to use 'ngf-resize' with quality set to 0.8. I used Upload.imageDimensions to get width and height of image and use it as  parameter for ngf-resize ( as I don't want to change the dimension) . However, if I update the ngf-resize using this value, it is used only when another file has been selected. It does not work for the current file being selected. Is there a way to update them for the currently selected file?

**Comment by danialfarid** [comment]
Just set the quality on ngf-resize it should use the original size by default so no need for calling imgaeDimentions

**Comment by vanbergcamp** [comment]
When I set quality as ngf-resize="{quality:0.8}" , I got following error. 
"width and height are mandatory for ngf-resize".
I apologize if I am missing simple way to set the value.

**Comment by danialfarid** [comment]
Gonna fix it in the next version. But you probably want to resize the photo as well if you are reducing the quality.
For now use `Upload.resize(file, width, height, quality).then(...)` instead of ngf-resize and pass null for width and height

**Comment by vanbergcamp** [comment]
Thank you danialfarid.

**Comment by MrAtheist** [comment]
@danialfarid, can you provide a more complete example where the image is first resized then being uploaded? I have tried ngf-resize but that's not working for me. Maybe what you're suggesting with ```Upload.resize(file, width, height, quality).then( ...what's passed here for the upload?)``` would do the trick.

**Comment by danialfarid** [comment]
`.then(function(file) {Upload.upload({data: {file: file}})});`

**Comment by danialfarid** [comment]
Fixed at version 10.0.0. You can just specify the quality.
