### ISSUE TITLE
Question: Is it possible to preview .pdf or .docs files?

### ISSUE THREAD

**Issue by F3L1X79** [danialfarid/ng-file-upload#1118]
Hi danialfarid, thanks a lot for this awesome bundle.
I got a simple question:
after reading the doc and playing with the code, I wasn't able to preview a .pdf file (ie: the first page). Do you think it would be possible to do this easily - or does it require another bundle?

**Comment by danialfarid** [comment]
Not yet but I will consider adding the feature to the next version.

**Comment by F3L1X79** [comment]
That would be so nice!
Thank you so much for the fast answer.

**Comment by felixfbecker** [comment]
The file that ng-model is bound to is a File object, which is a subclass of Blob. This means you can construct an URL for it with `URL.createObjectUrl()`. You can then set the src of an iframe to that URL and if the Browser supports PDF previews it will show a preview in that iframe.

**Comment by danialfarid** [comment]
You can use 'Upload.dataUrl(file).then(function(url) {...})` to get the data url of the file.

**Comment by BenMGilman** [comment]
I was able to use ngf-src="uploadFile" in an iframe for a preview with the uploadFile being a .pdf file in scope

**Comment by leongaban** [comment]
Question, It seems that the plugin can't even detect PDF or any non-image file type?

This is the jsfiddle I'm looking at: http://jsfiddle.net/danialfarid/0mz6ff9o/135/

![screen shot 2017-02-03 at 1 59 14 pm](https://cloud.githubusercontent.com/assets/191636/22606301/07383d10-ea19-11e6-9d6d-633ed8669fce.png)

Is there some setting I'm missing?

**Comment by leongaban** [comment]
^ Ah nevermind! Just changed this `accept="images/*"` to `accept="/*"`

**Comment by diasraphael** [comment]
I am unable to load pdf in IE but it works in chrome. <iframe  ngf-src="picFile"></iframe>
@BenMGilman Did it work in IE as well.

**Comment by jakeweb** [comment]
`<iframe ngf-src="uploadFile"></iframe>`
it doesn't work for mobiles. Is it possbile preview pdf files on mobiles?
