### ISSUE TITLE
Selecting the same file for upload again doesn't work 

### ISSUE THREAD

**Issue by rohand89** [danialfarid/ng-file-upload#1119]
I have a scenario in which i have the file upload control in a popup 
If I select a.jpg for one item then when i try to add files for the second item and i select a.jpg again it doesn't upload the file since this file was already posted to the server for the first item, is there any workaround for this if i can reinitialize the control or maybe some other workaround?

**Comment by danialfarid** [comment]
It should resend it by default unless you disable update on click.

**Comment by rohand89** [comment]
Consider if you select a file it gets uploaded to the server and then try reselecting the same file it wont upload since the file has already been uploaded
The same thing happens when I add a product with that i select a image for the product since the page does not get reloaded when i go the add the same image for the second product it doesn't send any request to the server

**Comment by danialfarid** [comment]
Post your code here or create a jsfiddle for faster answer.

**Comment by rohand89** [comment]
http://jsfiddle.net/rohansp/43arsr1h/42/

In fiddle mentioned above when you click on the button you will be given a option to enter a text and select a file. once you select a file the file name and the text entered shows in table but if you select the same file next time  when you try to add another product the popup wont go away since the select file method is not fired

**Comment by rohand89** [comment]
thanks. I got the solution form the work around  mentioned in bug id #141  I just added the onclick="this.value = null" and it worked

**Comment by KD25** [comment]
Hi Danial,

I checked with several post by you to allow same file upload multiple times by adding onclick="this.value =null" but this is not working with Windows safari. 

Please let me know your suggestion on this.

**Comment by danialfarid** [comment]
You are using a very old version of the plugin upgrade to latest and it should work without setting onclick.
