### ISSUE TITLE
.ngf-hide style in javascript results in CSP warning

### ISSUE THREAD

**Issue by timhoekstra** [danialfarid/ng-file-upload#1122]
A Content-Security-Policy header containing ' script-src 'self'; style-src 'self'; ' will result in the following warning:

Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'".

Stacktrace:
(anonymous function) @ ng-file-upload.js:883
(anonymous function) @ ng-file-upload.js:1016

**Comment by danialfarid** [comment]
What browser what version? Does it happen on the demo page as well?

**Comment by timhoekstra** [comment]
Tested in the latest version of chrome. The demo page doesn't give a warning because it hasn't got a content security policy enabled. I have it enabled from my backend to prevent things like XSS attacks.

**Comment by danialfarid** [comment]
Angular adds styles to the head too, do you get the same warning for angular?

**Comment by timhoekstra** [comment]
In angular that part is solved by adding an ngCsp directive. That tells angular to stop injecting css styles. See https://docs.angularjs.org/api/ng/directive/ngCsp

**Comment by danialfarid** [comment]
Fixed at 10.0.0.
