### ISSUE TITLE
width/height auto not supported?

### ISSUE THREAD

**Issue by eduardoinnorway** [danialfarid/ng-file-upload#1124]
Well, I tried this out today and it was really easy to get started. But I can't see how to do width/height:auto, because in almost all cases you never resize an image to fixed sizes on both width and height because then you are probably ending up with a messed up picture, you use one as the reference and the other one is "auto", you never know what ratio the users will have.
This would be very appreciated: 

 ngf-resize="{width: 100, height: 'auto'}" or just  ngf-resize="{width: 100}" and auto as default if  width or height is not given.

**Comment by danialfarid** [comment]
It would always keep the aspect ratio of the image so the image will not be distorted. So you can set the width and height meaning you want that picture to fit in that box by cutting edges.

**Comment by eduardoinnorway** [comment]
I done a ton of picture related projects and they usuallly want a fixed size in the wrapper, so what you do because uploaded images all have different sizes is that you go for widh or height as the determinator and you let the not fitting part, to just be invisible outside that box. So you will need "auto" feature, I usually program this directly before passing down to image-magagic. But I would prefer to start to us ng-file-upload with auto supported.

Don't get me wrong, I am not beeing negative on your project, but width or height auto, is a common wanted feature in what you have.

Why not something like this in the "resize" function:
        if(width === 'auto') {
            width = Math.round((height/imageElement.height) * imageElement.width);
        }
And for height same method with the corresponding right data.

**Comment by danialfarid** [comment]
What you are describing here is doable by setting a large value to either width or height to make them auto.

**Comment by danialfarid** [comment]
Fixed at 10.0.0, you can leave any of the width and height empty for the same effect.
