### ISSUE TITLE
Can't get min-width validation error message to show up

### ISSUE THREAD

**Issue by riyunoa** [danialfarid/ng-file-upload#1129]
Hi, I'm obviously doing something wrong, but I can't get the min-width validation error message to show up. I think validation is working as it doesn't bind to the model if it's too small. Please help! 

I've done this:
```` 
<input type="file" ngf-select ng-model="picFile" name="file" accept="image/*" ngf-min-width="700" required>
<i ng-show="myForm.file.$error.minWidth">Width too small</i>
````

Fiddle here: https://jsfiddle.net/z3s5njgs/2/

**Comment by danialfarid** [comment]
That was a bug. Fixed at version 10.0.1
