### ISSUE TITLE
issues with xdomain.js?

### ISSUE THREAD

**Issue by AdamQuadmon** [danialfarid/ng-file-upload#113]
Hi guys, I'm using [xdomain.js](https://github.com/jpillora/xdomain/) to do cors stuff.

Your script works without xdomain but using also xdomain result in a server error saying the file was not found.
(I tried loading angular-file-upload-shim.js before xdomain and after it, the issue is the same).

Both libraries hacks the XHR object. I think:
- something in xdomain is removing important stuff from the XHR object.
- or your shim is adding something to XHR that xdomain doesn't copy as well

xdomain is using [xhook](https://github.com/jpillora/xhook) and uploads seems to be supported there.

( I tried also to not load the shim but it doesn't work as well)

I need some hint to debug the issue.

Thanks for this module and for you help!

**Comment by priyanganamal** [comment]
Thanks for trying out this issue. As this seems not resolved I had to move on https://github.com/nervgh/angular-file-upload.
It's working like a charm.
