### ISSUE TITLE
Should accept not be ngf-accept

### ISSUE THREAD

**Issue by blowsie** [danialfarid/ng-file-upload#1130]
I was just writing an adapted for ng-file-upload and formly, and noticed one of the attributes `accept` does not follow your prefix convention of using `ngf-` is there a reason for this?
Thanks

**Comment by StefanCodes** [comment]
`accept` is part of the HTML spec for the `<input>` tag when the `type` is file: https://developer.mozilla.org/en/docs/Web/HTML/Element/Input#Attributes

**Comment by danialfarid** [comment]
`ngf-accept` is added since version 10.1.9
