### ISSUE TITLE
Remove console.log() 

### ISSUE THREAD

**Issue by bogdanalexe90** [danialfarid/ng-file-upload#1131]
After updating to `10.0.1` some logs started to appear in console.

<img width="800" alt="screen shot 2015-11-11 at 16 10 19" src="https://cloud.githubusercontent.com/assets/8752468/11092815/c36f46ec-888e-11e5-8669-abd373d03526.png">

Please remove it. Thanks in advanced.

**Comment by danialfarid** [comment]
Fixed at 10.0.2

**Comment by bogdanalexe90** [comment]
cool. Thanks a lot
