### ISSUE TITLE
Expressjs how to save an file.

### ISSUE THREAD

**Issue by Valonix** [danialfarid/ng-file-upload#1132]
Hello, i am new in node.js. i use multer in my app. 

In my route i have this code
var express = require('express');
var router = express.Router();
var multer = require('multer');
var upload = multer({ dest: __dirname + '/public/uploads/' });

router.post('/', upload.single('file'), function(req, res) {
console.log(req.file);
res.status(200).json({ file: req.file});
});
module.exports = router;

But i saving not image. How i can save an image file? I mean some decode function or what?

Thanks.

**Comment by danialfarid** [comment]
Post it on Stackoverflow
