### ISSUE TITLE
How to get text file content

### ISSUE THREAD

**Issue by ramonmulia** [danialfarid/ng-file-upload#1135]
Hi, i have a text file and i need to do some validations before i send. 
I'm using drag and drop example.

I can't get the content of file. How can i do that?

**Comment by danialfarid** [comment]
You can read the content with FileReader:
```
        var input = event.target;

        var reader = new FileReader();
        reader.onload = function(){
          var text = reader.result;
        };
        reader.readAsText(file);
```

**Comment by ramonmulia** [comment]
Thanks man, i spent maybe one day to fix this. i think that i tried to do this but, can you explain why and how the reader.readAsText(file) works with the object model?

anyway thanks!

**Comment by danialfarid** [comment]
```
<button ngf-select ngf-validate-async-fn="validateContent($file)">

$scope.validateContent = function(file) {
   var defer = $q.defer();
   var reader = new FileReader();
   reader.onload = function(){
            var text = reader.result;
           if (validate(text)) {
             defer.resolve(true);
           } else {
             defer.resolve(false);
           }
   };
   reader.readAsText(file);
   return defer.promise;
}
```

**Comment by fisyher** [comment]
sdgs

**Comment by fisyher** [comment]
Hi there, I am new to Angular. This example of a validate-async function with a FileReader has been very useful for my project. I have tried to move the code to a service method and call from the controller but an exception is triggered.

    $scope.validateContent = function(file) {
       return ValidationService.validateFile(file);
    }

	//ValidationService
	this.validateFile = function(file) {
	   var defer = $q.defer();
	   var reader = new FileReader();
	   reader.onload = function(){
				var text = reader.result;
			   if (validate(text)) {
				 defer.resolve(true);
			   } else {
				 defer.resolve(false);
			   }
	   };
	   reader.readAsText(file);//Exception caught in this line
	   return defer.promise;
	}
 
The error shown in console log is "async.then... is not a function" inside ng-file-upload.js. My question is why is the above causing an error?

**Comment by danialfarid** [comment]
There is no ng-file-upload use in your code here.

**Comment by fisyher** [comment]
I forgot to include it in my post but it is inside my html page:
    <input type="file" name="file" ngf-select ngf-validate-async-fn="validateContent($file)">

I will set up a jsfiddle soon and see if I can reproduce the error.

**Comment by danialfarid** [comment]
@fisyher could you open a separate issue, this issue is closed and your issue is with the async validation not text file content.
