### ISSUE TITLE
limit combined max size

### ISSUE THREAD

**Issue by joshikeerti** [danialfarid/ng-file-upload#1136]
Is it possible to check for the total size when multiple select is enabled for files? using ngf-max like below only seems to check it for the individual file, if I want to restrict the combined file size to a size, is there an option?
ngf-max-size="'250MB'"

**Comment by danialfarid** [comment]
' ngf-max-total-size ` see readme.

**Comment by joshikeerti** [comment]
This works, however the behavior is a little weird. When you try to add files after the max total size has exceeded, that file you are trying to add gets added but the first file in the list is deleted.
Once the error is there, I would think any more files added should not get added to the $scope.files.
I looked at the code and seems like the 0th index is always being spliced.
