### ISSUE TITLE
Drag & drop anywhere on the page

### ISSUE THREAD

**Issue by iBasit** [danialfarid/ng-file-upload#1138]
Hi,

I have a long form and I want to let user upload files by drag and drop anywhere on the page (body / window) and files should start appearing in their specified section(s).

I can't manage to find any example or doc for this, other scripts has it, but this one does not, but by the community support, stars and features, I think its best to use this one. So can you tell me how I can accomplish this solution?

**Comment by danialfarid** [comment]
add `ngf-drop` to the body element.
