### ISSUE TITLE
Send not only file

### ISSUE THREAD

**Issue by Valonix** [danialfarid/ng-file-upload#1141]
Hello, can i send to my express js not only file, i want to send file and other data.

            var vm = this;
            vm.newPost = {text: '', picFile: null};

            vm.uploadPic = function(file) {
                file.upload = Upload.upload({
                    url: '/upload/',
                    data: {file: file}
                });

                file.upload.then(function (response) {
                    $timeout(function () {
                        console.log(response.data);
                        file.result = response.data;
                    });
                }, function (response) {
                    if (response.status > 0)
                        vm.errorMsg = response.status + ': ' + response.data;
                }, function (evt) {
                    // Math.min is to fix IE which reports 200% sometimes
                    file.progress = Math.min(100, parseInt(100.0 * evt.loaded / evt.total));
                });
            }

in html i have textarea and text inputs and want to send all data to my route in expressjs, can you explain me how i can do this? thank you

**Comment by danialfarid** [comment]
`data: {file: file, text: $scope.text, ...}`
