### ISSUE TITLE
Using transformResponse/transformRequest: on Upload.upload

### ISSUE THREAD

**Issue by grahamlittle** [danialfarid/ng-file-upload#1142]
Is it possible to use transformResponse or transformRequest on Upload.upload, something like this:

        Upload.upload({
          url: URLS.BASE + URLS.FILE_UPLOAD,
          data: uploadData,
          transformRequest: appendTransform($http.defaults.transformRequest, function(value) {
            return doTransform(value);
          })
        }).then( .....

$http is not available i am wondering if perhaps $upload or something of that nature is.

Many Thanks

**Comment by grahamlittle** [comment]
I now know i can access Upload.http.defaults.transformRequest, but where can i access the data so that i can apply a custom transformation just before Request or Response?

**Comment by danialfarid** [comment]
For the first question just inject $http in your controller.
For the second you can use transformRequest the same way you use for $http. So just have a look at the angular $http samples.

**Comment by grahamlittle** [comment]
@danialfarid thanks, for your comments. I got the transformRequest working:

        Upload.upload({
          url: URLS.BASE + URLS.FILE_UPLOAD,
          data: uploadData,
          transformRequest: function (data) {
                var formData = new FormData();
                $log.debug('formData' + JSON.stringify(data));

                formData.append("model", angular.toJson(data.model));

                return formData;
            }          
        })

I also set up a request interceptor so that i can see the content of the request as its going out:

      .factory('uploadRequestInterceptor', ['$q', '$location','$log',
        function($q, $location, $log) {
            return {
                request: function(config) {
                    $log.debug('Request Interceptor'+JSON.stringify(config));
                    //$log.debug('transformRequest'+config.transformRequest());
                    return config;
                }
            };
        }

The output for both debug logs is as follows:

Request Interceptor = {"method":"POST","transformRequest":[null,null],"transformResponse":[null],"url":"http://testservices.co.uk/v1/customers/signup","data":{"idDocument":{"$ngfDataUrl":"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD//gA7Q1JFQVRPUjogZ2QtanBl…gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg//9k="},"customerInfoPart":{"_ngfBlob":true}},"_isDigested":true,"_chunkSize":null,"headers":{"Accept":"application/json, text/plain, */*","Authorization":"Credentials ce8dcae2-8a1a-4dff-8b88-48aeac544998"},"_deferred":{"promise":{"$$state":{"status":0,"pending":[[{"promise":{"$$state":{"status":0}}},null,null,null]]}}}}

formData = {"idDocument":{"$ngfDataUrl":"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD//gA7Q1JFQVRPUjogZ2QtanBl…gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg//9k="},"customerInfoPart":{"_ngfBlob":true}}


What i want to do is change the Content-Disposition from form-data to attachment. At what point is that being set and how can i change it. I am wondering if perhaps its a promise of some kind and thats why i cant see it even at the interceptor level?

**Comment by danialfarid** [comment]
The content disposition will be form-data since it is a multipart/form-data request.
If you want to send the file binary with file's content-type use `Upload.http()`
