### ISSUE TITLE
How put custom html inside ngf-drop div?

### ISSUE THREAD

**Issue by BaurzhanSakhariev** [danialfarid/ng-file-upload#1145]
I would like to show many spans with loaded filenames in drop area and also let user to load new files via drag and drop. I didn't manage to put something inside ngf-drop div - is there easy way to do it without compiling ng-file-upload with ```transclude=true```?

**Comment by danialfarid** [comment]
Can you create a jsfiddle?

**Comment by BaurzhanSakhariev** [comment]
I updated your fiddle - [drop with watch & ng-model multple files](http://jsfiddle.net/s8kc7wg0/271/)  as [my](http://jsfiddle.net/mmbaLLd1/) almost the same. The only difference in loading dependencies. I have  ```<script src="ext/ng-file-upload-10.0.2/ng-file-upload-all.min.js" charset="utf-8"></script>``` instead of ```ng-file-upload``` & ```ng-file-upload-shim```

**Comment by danialfarid** [comment]
It means that you are doing something differently in your code, using all.js is fine.

**Comment by danialfarid** [comment]
Closing this unless you could provide steps to reproduce.

**Comment by BaurzhanSakhariev** [comment]
I found the reason. I took common css from demo page and modified height. Drop box  padding was larger than height. Thanks!
