### ISSUE TITLE
ngf-resize seems to remove picture properties like GPS position

### ISSUE THREAD

**Issue by dwestphal** [danialfarid/ng-file-upload#1146]
When I don't use ngf-resize, the uploded picture (from a mobile camera) contains properties like GPS position and some others.

When I enable ngf-resize those properties are removed. Is there any way to keep them (or at least the GPS-Position) in the picture?

Thank you very much!

**Comment by danialfarid** [comment]
Will be added to the next release.
For now you could find a workaround here: http://stackoverflow.com/a/18298040/1105011

**Comment by rahulvgmail** [comment]
---NooB alert---
is it possible to call resize from JS code after reading the EXIF information? 
(instead of ngf-resize)

**Comment by danialfarid** [comment]
`Upload.resize(imageFile).then(function(resizedFile) {})`

**Comment by danialfarid** [comment]
Fixed at 11.0.0
