### ISSUE TITLE
Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by diegopolido** [danialfarid/ng-file-upload#1147]
Hey guys, how is it going? I'm trying to use ng-file-upload to handle the uploads and I got everything ok (include the string "success" on the call response and the upload process)

 but this error:

Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
fromJson@https://localhost:9443/pathfinder-web/app/libs/angular.js?v=1447962050409:1075:9
defaultHttpResponseTransform@https://localhost:9443/pathfinder-web/app/libs/angular.js?v=1447962050409:8650:1
transformData/<@https://localhost:9443/pathfinder-web/app/libs/angular.js?v=1447962050409:8735:12
forEach@https://localhost:9443/pathfinder-web/app/libs/angular.js?v=1447962050409:326:11
transformData@https://localhost:9443/pathfinder-web/app/libs/angular.js?v=1447962050409:8734:3
transformResponse@https://localhost:9443/pathfinder-web/app/libs/angular.js?v=1447962050409:9464:23
processQueue@https://localhost:9443/pathfinder-web/app/libs/angular.js?v=1447962050409:13300:27
scheduleProcessQueue/<@https://localhost:9443/pathfinder-web/app/libs/angular.js?v=1447962050409:13316:27
$RootScopeProvider/this.$get</Scope.prototype.$eval@https://localhost:9443/pathfinder-web/app/libs/angular.js?v=1447962050409:14552:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@https://localhost:9443/pathfinder-web/app/libs/angular.js?v=1447962050409:14368:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@https://localhost:9443/pathfinder-web/app/libs/angular.js?v=1447962050409:14657:13
done@https://localhost:9443/pathfinder-web/app/libs/angular.js?v=1447962050409:9734:36
completeRequest@https://localhost:9443/pathfinder-web/app/libs/angular.js?v=1447962050409:9924:7
requestLoaded@https://localhost:9443/pathfinder-web/app/libs/angular.js?v=1447962050409:9865:1

![json-error](https://cloud.githubusercontent.com/assets/140918/11282942/3077de38-8ee9-11e5-899e-5f9fae5234b7.png)
![json-error-response](https://cloud.githubusercontent.com/assets/140918/11282945/33da4462-8ee9-11e5-824f-f2c9da7aa0b7.png)

**Comment by danialfarid** [comment]
The error is not from this plugin, your server probably returns invalid json.

**Comment by diegopolido** [comment]
Yeah.. thanks! It was because my service was returning a string "success" and for some reason I needed to returned with extra double quote like "\"success\"".

Thanks!

**Comment by engrmehdi** [comment]
return string with double slashes like this 
{\"name\":\"john\",\"age\":22,\"class\":\"mca\"}
