### ISSUE TITLE
Automatic cropping

### ISSUE THREAD

**Issue by numasi** [danialfarid/ng-file-upload#1148]
I'm curious whether this functionality implemented already, or it would be useful for more then just myself to implement it.

What I need is something like the nice and built-in resize feature, but for center cropping images while resizing them, instead of keeping their original aspect ratio. I know it's possible via other modules, but most of them I encountered are implementing some fancy cropping boxes, giving the user the freedom to set the cropping area they like. What I want however is to configure this as a constant for all users,  easing the workload on my backend, cropping all images automatically to their desired width and height before uploading them to the server. By automatically I mean to do it without any extra user input, just to crop them behind the scenes.

Have you encountered this scenario before? 
Do you know any solutions ready to use? 
Or do you agree that it worth to implement it for the module? 

I think it can't be to hard to do it, following the path of the already implemented resize directive.

Thank you!

**Comment by danialfarid** [comment]
Added feature to 10.1.0.
Use `ngf-resize="{centerCrop: true, width: x, height: x}"` You can also specify ratio instead of width and height `ngf-resize="{ratio: '1:2'}"`
