### ISSUE TITLE
Is it possible to handle own ng-click() inside ngf-select?

### ISSUE THREAD

**Issue by BaurzhanSakhariev** [danialfarid/ng-file-upload#1151]
I have links inside ngf-drop with ngf-select. I would like to attach some action on that links via ng-click(). I tested it and ng-click() words but ngf-select runs simultaneoulsy. Is there way do not trigger select event when click occurs on my buttons or links? 

My html is the following:

       <div class="row" ngf-drop ngf-select ng-model="files" class="drop-box"  ngf-multiple="true">

            <div  ng-repeat="doc in docsList">
                <div  class="col-xs-3">
                <span class="label label-info" >
                   <a style=" color:white;background-color: none;" download= {{doc.filename}} ng-href="rest/getDoc/{{doc.docId}}"> {{doc.filename}}</a>
                    <span ng-click="load()" style="cursor:pointer;" class="glyphicon glyphicon-remove">
                    </span>
                 </span>&nbsp;&nbsp;&nbsp;&nbsp;
                </div>
            </div>

            </div>

**Comment by bogdanalexe90** [comment]
Just change it to ```ng-click="load(); $event.stopPropagation()"```

**Comment by danialfarid** [comment]
or `ng-model-options="{updateOn: 'change, drop, paste'}`

**Comment by BaurzhanSakhariev** [comment]
ng-model-options="{updateOn: 'change drop paste'} doesn't chnage situation. If I got it properly, such option will cancel ngf-select which is not desired behavior. $event.stopPropagation()" works perfectly on ng-click() but how get it work on download ng-href?

**Comment by GadyTal** [comment]
@danialfarid Also in this area, can I cancel the selection by click? which means it will be possible to upload a file only by dragging?
