### ISSUE TITLE
Validation doesn't work as documented

### ISSUE THREAD

**Issue by piotrd** [danialfarid/ng-file-upload#1152]
Documentation says:

> When any of the validation directives specified the form validation will take place and you can access the value of the validation using `myForm.myFileInputName.$error.<validate error name>` for example `form.file.$error.pattern`.

With the latest version of ng-file-upload (and earlier, too), this doesn't seem to work as described. I have a form (`name="brandForm"`) and a field with the following attributes: `name="logo" required="required"` `ngf-validate='{width: {min: 300}, height: {min: 300}}'`. I also placed `{{brandForm.logo.$error}}` to debug its content. So initially `$error` says `{"required":true}`. Just to note, `ngf-multiple` is not set for the field.

1. When I select an image of width higher than 300px, `$error` is set to `{}` (expected)
2. When I select an image of width smaller than 300px, nothing happens (`$error` still says `{"required":true}`)

So in case 2. I would expect `brandForm.logo.$error` to contain an error related to width being smaller than 300px - is that correct?

What's even more interesting, the docs say further:

> If multiple file selection is allowed you can specify `ngf-model-invalid="invalidFiles"` to assing the invalid files to a model and find the error of each individual file with `file.$error`

I would not expect this to work in my case (as I don't want multiple file selection), but it suprisingly does work. As a test, I explicitly set `ngf-multiple="false"` and `ngf-model-invalid="logoErrors"` to the same field from above and I output `logoErrors` to debug its contents. This is what I got:

1. When I select an image of width higher than 300px, `logoErrors` is empty (expected)
2. When I select an image of width smaller than 300px, `logoErrors` contains:
```json
  {
    "$ngfBlobUrl": "blob:http%3A//localhost...",
    "$ngfWidth": 109,
    "$ngfHeight": 128,
    "$error": "minWidth",
    "$errorParam": 300
  }
```

I would rather use the first method of validation, not the one with `ngf-model-invalid` (due to a way I handle errors in forms). Does anyone else experienced similar issues, or is it only me?

**Comment by danialfarid** [comment]
Make sure to upgrade to the latest version there was a bug with some earlier versions that would not set the form error properly.

**Comment by piotrd** [comment]
You're right, with 10.x it works fine. I had 9.x installed. Thanks!
