### ISSUE TITLE
Resize image to specific height using using aspect ratio

### ISSUE THREAD

**Issue by cameronjroe** [danialfarid/ng-file-upload#1153]
Is there a way to specific a resize without using a specific width? If I specific a `{width:150, height:150}` the images may actually only use 112 in height while the the width is matched to 150. This causes an issue when trying to only meet a 150 required height, yet one cannot simply specify `{height:150}` to scale an image proportionally using it's existing aspect ratio. Any ideas on how to specify the height to a specific value?

**Comment by danialfarid** [comment]
So you want both of them be 150px by adding empty borders on top and bottom of the image?
Can you just center that image wherever you want to use it on the html page?
