### ISSUE TITLE
How do I get this to work with Cognito?

### ISSUE THREAD

**Issue by moneytree-doug** [danialfarid/ng-file-upload#1156]
AWS Cognito grants an authorized session, so I am able to upload to s3 freely without further authentication problems. I still want the progress bars that this library gives, and I am assuming that would require me to use the ``Upload.upload`` method to make use of the notify callback. How can I upload to s3 with the existing authenticated Cognito connection using this library?

For example, it would be nice if I could just supply the existing AWS S3 config, so it would be something like this:

```
s3 = new AWS.S3({
          apiVersion: '2006-03-01'
          params: {
            Bucket: ENV.awsCognito.s3Bucket
            Delimiter: 'thumbnail/' 
            Marker: "#{identityId}/"
            Prefix: "#{identityId}/" 
          }
        });
Upload.upload({
   s3: s3,
   data: {
      file: file, 
      key: keyName
   } 
})
```

**Comment by danialfarid** [comment]
Follow the S3 instructions in the README file.

**Comment by moneytree-doug** [comment]
@danialfarid I appreciate the kind help.

Just wanted to leave a reply for future people that might have trouble with this. You don't actually need to use the Upload service at all provided by this library. You can just use S3's API and you would have everything you need. When you pass back $files ($files is given to you by this library) and loop through it, you can just pass the file into the body. Afterwards, s3 has a uploadProgress event that notifies you the progress loaded. 

Coffee:
```
        deferred = $q.defer()
        s3Bucket.putObject(
          {
            Key: keyName
            Body: file
            ContentType: file.type,
          }
          (err, data) ->
            if err
              return deferred.reject(err)
            else
              return deferred.resolve(data)
            # successful response
            return
        )
        .on('httpUploadProgress', (progress) =>
          deferred.notify(progress)
        )

        return deferred.promise

```
