### ISSUE TITLE
Response always 200

### ISSUE THREAD

**Issue by ssuhat** [danialfarid/ng-file-upload#1158]
Hi

I'm having this issue, that the response always get into the success function instead of error.

I checked my response API , and i can ensure that the response is 400. I've tried 400,422 and 500 but all keep getting into success function.

Here is my upload code:

     Upload.upload({
            url: APIROOT + 'uploads',
            data: data
        }).then(function (resp) {
            console.log(resp);
            console.log('success');
            SweetService(resp);
        }, function (resp) {
            console.log(resp);
            console.log('error');
        });

Here is my response:
  
     Remote Address:192.168.10.10:443
     Request URL:https://api.example.dev/v1/admin/merchants
     Request Method:POST
     Status Code:400 Bad Request

I'm using latest chrome. Sorry can't make js fiddle because the api access need an authorization.

**Comment by danialfarid** [comment]
What version of the api are you using?

**Comment by ssuhat** [comment]
latest api. looks like i mess up with http interceptor. thanks
