### ISSUE TITLE
Progress function not working

### ISSUE THREAD

**Issue by bakgat** [danialfarid/ng-file-upload#1159]
I'll try to reproduce my code in short
I'm using ngFileUpload 10.0.2

I'm loading the script with ng-file-upload-all.min.js

This is in my controller
```javascript
           if (files && files.length) {
                Upload.upload({
                    url: 'api/upload',
                    data: {file: files},
                    headers: {'X-CSRF-TOKEN': common.csrfToken()}
                }).then(function (response) {
                    angular.forEach(response.data, function (asset) {
                        $scope.files.unshift(asset);
                    });
                    console.log('Success ' + response.data[0].name + ' uploaded. Response: ' + response.data);
                }, function (resp) {
                    console.log('Error status: ' + resp.status);
                }, function (evt) {
                    var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
                    $scope.progress = progressPercentage;
                    console.log('progress: ' + progressPercentage + '% ' + evt.config.data.file.name);
                });
```
Progress function is never called. The rest is working fine.

**Comment by piotrd** [comment]
I am using this syntax and progress callback does get called for me:

```javascript
Upload.upload({
  //...
})
.progress(uploadProgress)
.then(function(response) {
  //...
});

**Comment by bakgat** [comment]
Unfortunately, doesn't work

**Comment by piotrd** [comment]
Then please create a JSFiddle with a test case showing the issue.

**Comment by danialfarid** [comment]
It could be your server that doesn't support reporting upload progress.

**Comment by Gompje** [comment]
@danialfarid I'm having the same issue as bakgat; everything works but alas the progress function is never called. I'm using Apache on Debian in a Vagrantbox. I spend the afternoon installing the "mod_status" and "mod_progress" module on Apache following this guide (sortoff) http://webiva.net/doc/user/upload-progress 

Can you point me in a right direction what might be wrong? I'm running the complete site under ssl, with every page requiring authentication. Front: angular; Back: Laravel 5.

Got it "working" now with the famous old "animated gif" trick but it would be nice to get this working properly in the future.

some code:
```
       upload = @Upload.upload(
          disableProgress: false
          url: ...
          data:
            ...
        )

        upload.then ((resp) =>
          # file is uploaded successfully
          console.log 'file is uploaded successfully.'
          return
        ), ((resp) ->
          # handle error
          return
        ), (evt) ->
          # progress notify
          console.log 'progress: ' + parseInt(100.0 * evt.loaded / evt.total) + '%'
          return
```

**Comment by danialfarid** [comment]
@Gompje
You can change the upload url in your code to the demo page upload url: https://angular-file-upload-cors-srv.appspot.com/upload and see if you are capturing the progress correctly on the client side. Then you would be sure the problem is the server side.

**Comment by Gompje** [comment]
@danialfarid Thx! will probably be Saturday or even Sunday or maybe even later when I can toy with this again but I will keep you posted. I do feel kinda like a n00b now for not realising this obvious path sooner :)   This and it also hit me yesterday that, even tough I told Apache to send the progress to the /progress url inside my web app, I didn't change a thing in my Laravel routing so that could be wrong as well.
