### ISSUE TITLE
create $ngfBlobUrl from image url?

### ISSUE THREAD

**Issue by MrAtheist** [danialfarid/ng-file-upload#1161]
I see it has been suggested here in #1089 that to keep ```files``` and ```urls``` as separate scope variables. In my particular case, I've customized the upload form quite a bit in that it would require a lot of extra logic to accommodate both ```files``` and ```urls``` to behave as one seamless scope for my **edit** form (where the ui and the functionality are exactly the same as the upload form).

When I print out ```{{uploadedFiles}}```, I see that theres this $ngfBlobUrl property (i'm assuming that this is also where the preview src comes from). Is there any way for me to create this $ngfBlobUrl based off of an image url?

**Comment by danialfarid** [comment]
The image url is already a url that could be used instead of blob url.
And you want to keep them separate since the model that is assigned to the file input is for containing File or Blob objects. Assigning another type to them doesn't make sense that much and could cause errors in the plugin.
