### ISSUE TITLE
Can't replace "file" with value in [Content-Disposition: form-data; name="file" ...]

### ISSUE THREAD

**Issue by v-andrew** [danialfarid/ng-file-upload#1165]
I have set custom value for name when uploading file, however name is alwais set to "file".

My last effor let me achieve 'Content-Disposition: form-data; name="file[file]"; filename="4pdf.pdf"' with the following code:
        return Upload.upload({
            url: UploadFileURL,
            data: {
                "ContentType": fileItem.ItemType,
                "Culture": "en-CA",
                filename: fileName,
                file: { file: file, name: "uploadDialog$ctl00$ctl00$fileUpload$ctl00$ctl00$uploadInput" }
            }
        });
Please help.

**Comment by v-andrew** [comment]
Apparently it should be 
{
...,
"uploadDialog$ctl00$ctl00$fileUpload$ctl00$ctl00$uploadInput": Upload.rename(file, fileName)
}

**Comment by djindjic** [comment]
I have similar problem, I want to rename default name="file" to name="myName". Don't understand how did you fix it with code above? 

ex.
------WebKitFormBoundarykwEwHrS5loJAAUDX
Content-Disposition: form-data; name="file"; filename="picture.jpg"
Content-Type: image/jpeg


------WebKitFormBoundarykwEwHrS5loJAAUDX--

**Comment by danialfarid** [comment]
Read the docs `data: {myName: file}`

**Comment by djindjic** [comment]
@danialfarid in the mean time I found the solution by trying random combinations
```js
...
data: {
  myname: file
  ...
}
...
```
and now it looks like you are trying to say it in the docs, but it wasn't clear to me on first and second reading. I respect your work and number of stars but I also think that it could be more descriptive.
anyway thanks a lot for this directive!
