### ISSUE TITLE
 file upload problem in ie8 or ie9

### ISSUE THREAD

**Issue by SIDROCK** [danialfarid/ng-file-upload#1166]
i have file upload problem in ie8 or ie9 i m getting this error and here is my code which i write for file ..

        Upload.upload({

            url: $scope.webappUrl + "/transaction-log/" + id + "/document/" + documentType,
            file: uploadFile,
            method: 'POST'

        }).progress(function (evt) {

            var progressPercentage = parseInt(100.00 * evt.loaded / evt.total);
            if (progressPercentage == 100) {
                self.fileUploadedStatus[documentType]= true;
            }
            $log.debug('progress: ' + progressPercentage + '% ' + evt.config.file.name);

        }).success(function (data, status, headers, config) {
            $log.debug('file: ' + config.file.name + ' upload. Response: ');
            // search through the transaction list for the one we just attached an image to.
            ////
            for(var i = 0; i < $scope.transactionList.length; i++) {

                if($scope.transactionList[i].id == data.id) {

                    // replace the current transaction with the updated details
                    //
                    self.regradeTransaction = data;
                    $scope.transactionList[i] = data;

                    break;
                }
            }
            self.fileUploadedStatus[documentType] = true;
        }).error(function (data, status, headers, config) {
            $log.debug('error status: ' + config.file.name + ' upload. Response: ' + data);

        })
    }
here is screen shot for the error which i getting :

![image](https://cloud.githubusercontent.com/assets/16042087/11435171/210179e0-94fd-11e5-8adf-cfb788f4304e.png)

**Comment by danialfarid** [comment]
Does the demo page work?
