### ISSUE TITLE
Add dynamic identifier on input type created by ng-file-upload directive.

### ISSUE THREAD

**Issue by shankar-mits** [danialfarid/ng-file-upload#1167]
i have two separate upload button for angular-file-upload. They both create separate input elements at the bottom of the body. As they look alike ( cannot be distinguished ). I want to differentiate them for testing purpose (e2e test selenium webdriver) by passing optional paramater to the directive, but they are treated as string and not evaluated on the input element. I have used new `doctype`  attribute.
![screenshot from 2015-11-27 12 29 30](https://cloud.githubusercontent.com/assets/12388813/11435427/998832c8-9502-11e5-8b33-086cbddc7b86.png)

**Comment by bikram-mits** [comment]
i am having same issue..we need different identifier so that it will be easier for us to upload the file in end to end  test.

**Comment by danialfarid** [comment]
Feature added at version 10.0.3.
If you specify an id for your element, the input type file will have that id prefixed with `ngf-`.
So 
```
<div id="myid" ngf-select>
```
will create
```
<input type="file"  id="ngf-myid" ...>
```

**Comment by shankar-mits** [comment]
Thanks (y)

**Comment by vilmysj** [comment]
This doesn't work inside `ng-repeat`. For example 
```js
<div ng-repeat="...">
    <div id="myid-{{$index}}" ngf-select></div>
</div>
```
gives
```js
<input type="file"  id="ngf-myid-{{$index}}" ...>
```

is where any other way to set unique identifier?

**Comment by danialfarid** [comment]
@vilmysj  create a separate issue with jsfiddle to show the issue please.

**Comment by coryschires** [comment]
I'm having the same problem as @vilmysj when trying to set the `id` within a directive.

**Comment by vilmysj** [comment]
Here is separate issue #1529
