### ISSUE TITLE
how to remove this one from json $ngfName

### ISSUE THREAD

**Issue by vishnu038** [danialfarid/ng-file-upload#1168]
I am getting a JSON data like this {"Address":{"addressProof":{"$ngfName":"cb_test.jpg"}}.  i have to get JSON like this  {"Address":{"addressProof":"cb_test.jpg"} how do i do this ??

**Comment by danialfarid** [comment]
Post your code here

**Comment by vishnu038** [comment]
in my registercontroller updateCompany function.
  function updateCompany() {
            $scope.dataLoading = true;

            var editCompany = new Object();
            var edCompany= [] ;
            edCompany.push(
                {
                    "compName":$scope.compName,
                    "Address":{
                        "addrStreet1":$scope.addrStreet1,
                        "addrStreet2":$scope.addrStreet2,
                        "city"      :$scope.city,
                        "pinCode":$scope.pinCode,
                        "state":$scope.state,
                        "country":$scope.country,
                       "addressProof":$scope.addressProof

                    }
}
editCompany.edCompany=edCompany;
  console.log(JSON.stringify(edCompany))
            UserService.companyUpdate(edCompany)
                .then(function (response) {
                    if (response.success) {
                        FlashService.Success('Registration successful', true);
                    } else {
                        FlashService.Error(response.message);
                        $scope.dataLoading = false;
                    }
                });
        }

In UserServices companyUpdate finction:
 function companyUpdate(edCompany) {
            return $http.post('/api/edCompany', edCompany).then(handleSuccess, handleError('Error creating user'));
        }

The htmltemplate:
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-50">
            <h2 class="page-header">Registration</h2>
        </div>
        <form name="form"  novalidate ng-submit="updateCompany()" role="form">
            <div class="tab-content">
                <div class="row">
                    <div class="col-sm-3">
 <label>Company  name</label>
                        <div class="form-group" ng-messages="form.Name.$error" style="color:maroon" role="alert">
                            <input type="text" name="Name" placeholder="Name" id="Name" ng-minlength="3" ng-maxlength="30" ng-pattern="/^[a-zA-Z ]*$/"  class="form-control" ng-model="Name"  />
                            <span ng-message="pattern">please enter a valid field</span>
                            <span ng-message="minlength">Your field is too short</span>
                            <span ng-message="maxlength">Your field is too long</span>
</div>
  <label>Address Proof</label>
                        <div class="form-group" ng-class="{ 'has-error': form.addressProof.$dirty && form.addressProof.$error.required }">
                            <div class="button" ngf-select ng-model="addressProof" name="addressProof" ngf-pattern="'image/*'"
                                 accept="image/*" ngf-max-size="20MB" ngf-min-height="100"
                                 ngf-resize="{width: 100, height: 100}">Select</div>


                        </div>


in bower_components included this dependency
"ng-file-upload":"9.0.16"

after filling the form  i am getting JSON data like this :
[{"Address":{"addrStreet1":"add1","addrStreet2":"add2","city":"blr","pinCode":444444,"state":"ka","country":"india","addressProof":{"$ngfName":"cb_test.jpg"}},"PAN":{},"BankAcctInfo":{}}]

so want  the JSON data of image upload like this "addressProof":{"cb_test:jpg"}...
why that $ngfName is coming i am not getting that.


I am new to Angular, please help me on this.

**Comment by vishnu038** [comment]
the HTML template
<form name="form"  novalidate ng-submit="updateCompany()" role="form">
 <label>Company  name</label>
 <input type="text" name="compName" placeholder="compName" id="compName" ng-minlength="3" ng-maxlength="30" ng-pattern="/^[a-zA-Z ]*$/"  class="form-control" ng-model="compName"  />
</div>
 <label>Address Proof</label>
 <div class="button" ngf-select ng-model="addressProof" name="addressProof" ngf-pattern="'image/*'"
                                 accept="image/*" ngf-max-size="20MB" ngf-min-height="100"
                                 ngf-resize="{width: 100, height: 100}">Select</div>

**Comment by vishnu038** [comment]
<label>Address Proof</label>
  <div class="button" ngf-select ng-model="addressProof" name="addressProof" ngf-pattern="'image/*'"
                                 accept="image/*" ngf-max-size="20MB" ngf-min-height="100"
                                 ngf-resize="{width: 100, height: 100}">Select</div>
the HTML template

**Comment by vishnu038** [comment]
Hi Daniel,
Here i am sending my Complete Code
in github i am unable send certain html templates thats  why i am mailling
you.

In my registercontroller updateCompany function.
  function updateCompany() {
            $scope.dataLoading = true;

            var editCompany = new Object();
            var edCompany= [] ;
            edCompany.push(
                {
                    "compName":$scope.compName,
                    "Address":{
                        "addrStreet1":$scope.addrStreet1,
                        "addrStreet2":$scope.addrStreet2,
                        "city"      :$scope.city,
                        "pinCode":$scope.pinCode,
                        "state":$scope.state,
                        "country":$scope.country,
                       "addressProof":$scope.addressProof

                    }
}
editCompany.edCompany=edCompany;
  console.log(JSON.stringify(edCompany))
            UserService.companyUpdate(edCompany)
                .then(function (response) {
                    if (response.success) {
                        FlashService.Success('Registration successful',
true);
                    } else {
                        FlashService.Error(response.message);
                        $scope.dataLoading = false;
                    }
                });
        }

In UserServices companyUpdate finction:
 function companyUpdate(edCompany) {
            return $http.post('/api/edCompany',
edCompany).then(handleSuccess, handleError('Error creating user'));
        }

 <form name="form"  novalidate ng-submit="updateCompany()" role="form">
           <label>Address Proof</label>
                        <div class="form-group" ng-class="{ 'has-error':
form.addressProof.$dirty && form.addressProof.$error.required }">
                            <div class="button" ngf-select
ng-model="addressProof" name="addressProof" ngf-pattern="'image/*'"
                                 accept="image/*" ngf-max-size="20MB"
ngf-min-height="100"
                                 ngf-resize="{width: 100, height:
100}">Select</div>


                        </div>


in bower_components included this dependency
"ng-file-upload":"9.0.16"

after filling the form  i am getting JSON data like this :
[{"Address":{"addrStreet1":"add1","addrStreet2":"add2","city":"blr","pinCode":444444,"state":"ka","country":"india","addressProof":{"$ngfName":"cb_test.jpg"}},"PAN":{},"BankAcctInfo":{}}]

so want  the JSON data of image upload like this
"addressProof":{"cb_test:jpg"}...
why that $ngfName is coming i am not getting that.


I am new to Angular, please help me on this.

**Comment by danialfarid** [comment]
Just post the part the you are calling `Upload.upload()` specially the `data` option.

**Comment by vishnu038** [comment]
function uploadPic(file) {
    console.log("IN");

    Upload.upload({
        url: 'https://angular-file-upload-cors-srv.appspot.com/upload',
        file:file
    }).progress(function (evt) {
        console.log("Progress");
        var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
        console.log('progress: ' + progressPercentage + '% ' +
evt.config.file.name);
    }).success(function (data, status, headers, config) {
        console.log("Progress1");
        console.log('file ' + config.file.name + 'uploaded. Response: ' + data);
    }).error(function (data, status, headers, config) {
        console.log("Progress2");
        console.log('error status: ' + status);
    })
}

**Comment by danialfarid** [comment]
I don't see any address in the Upload.upload(). How come you get address in your json server side?

**Comment by vishnu038** [comment]
<div class="button" ngf-select ng-model="addressProof"
name="addressProof" ngf-pattern="'image/*'"
     accept="image/*" ngf-max-size="20MB" ngf-min-height="100"
     ngf-resize="{width: 100, height: 100}">Select</div>

i used above code ngf-select ng-model="addressProof"

in controller

  var editCompany = new Object();
            var edCompany= [] ;
            edCompany.push(
                {
                    "compName":$scope.compName,
                    "Address":{
                        "addrStreet1":$scope.addrStreet1,
                        "addrStreet2":$scope.addrStreet2,
                        "city"      :$scope.city,
                        "pinCode":$scope.pinCode,
                        "state":$scope.state,
                        "country":$scope.country,
                       "addressProof":$scope.addressProof

                    }

console.log(JSON.stringify(edCompany))

after doing this i am getting a JSON in a  console likes this

[{"compName":"alok","Address":{"addrStreet1":"add1","addrStreet2":"add2","city":"blr","pinCode":555555,"state":"ka","country":"india","addressProof":{"$ngfName":"Koala.jpg"}},"PAN":{},"BankAcctInfo":{}}


in that json why that $ngfName is coming ??


i want the JSON like this

"addressProof":"Koala.jpg"}

how do i do this??

**Comment by danialfarid** [comment]
That's a file object and it will print all the property of that object. $ngfName is a property of that file object and probably console.log won't show the native properties of the file object.
File object cannot be converted to json since it has binary data so if you want your json to just have the file name then make your object to have `"addressProof":$scope.addressProof.name`

**Comment by vishnu038** [comment]
thanku so much Danial Farid its working.
