### ISSUE TITLE
Azure blob container - cross doamin issues

### ISSUE THREAD

**Issue by nasir-mps** [danialfarid/ng-file-upload#1173]
I am trying to upload an image to blob container, and getting some cross doamin errors.

Code to upload image:-

 file.upload = Upload.upload({
                        url: 'https://example.blob.core.windows.net/conatiner/FileName.jpg?sv=2014&sr=c&si=00&sig=125',
                        data: {file: file},
                        method: "PUT",
                        headers : { 'Authorization': 'Bearer ',  'x-ms-blob-type': 'BlockBlob'}
                    });

                    file.upload.then(function (response) {
                        if (response.status > 0)
                            console.log( response.status + ': ' + response.data );
                    });

It fails at preflight request, and throw the following errors

Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 403.

OPTIONS request header:-
Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en,sv;q=0.8
Access-Control-Request-Headers:accept, authorization, content-type, x-ms-blob-type
Access-Control-Request-Method:PUT
Connection:keep-alive
Host:kumo2stage.blob.core.windows.net
Origin:http://localhost
Referer:http://localhost
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36

Response header:-
Content-Length:316
Content-Type:application/xml
Date:Tue, 01 Dec 2015 16:12:44 GMT
Server:Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id:
x-ms-version:2014

The azure storage account is already CORS enabled, as follows
Allowed Origins:  *,
Allowed Methods:  Put
Allowed Headers:  content-type, accept, x-ms-*,
Max Age (Seconds): 86400
Exposed Headers:  x-ms-*,

**Comment by danialfarid** [comment]
Your server response to OPTIONS request doesn't have any headers to allow CORS.
So you could try adding OPTIONS method to the CORS config. Also you probably want to add 'Authorization` to the allowed headers.

**Comment by danialfarid** [comment]
Closing this since it is a server side issue. You can post it on SO

**Comment by prashanthmadi** [comment]
Use below python script to set CORS in azure blob service
- use below pip command to install azure python sdk

> pip install azure

```
from azure.storage.blob import BlockBlobService
from azure.storage.models import CorsRule
import json

block_blob_service = BlockBlobService(account_name='xxxxx', account_key='xxxx')

url = ["abc.com","abc.azure.com"]
method =["GET","POST"]

corslist = [];
for count in range(len(url)):
   corslist.append(CorsRule(url[count],method,50))

block_blob_service.set_blob_service_properties(None,None,None,corslist,"2015-02-21",None)
```
