### ISSUE TITLE
Progress bar event is not working

### ISSUE THREAD

**Issue by karenhovhannisian** [danialfarid/ng-file-upload#1174]
Hello,

I have a problem with progress bar, when I am trying same code in angularjs without nodejs it works fine, but with nodejs it's not showing. Can you help me to figure out the issue? My code looks like the following:

Upload
       .upload({
		 url: {url},
		 data: {data},
		 file: payload_file                               
       })
       .then(function (clResponse) { 
		//successfull response
        }, function (err) {
               //error response
         }, function (evt) { 
		//progress bar
         });

**Comment by danialfarid** [comment]
Create a jsfiddle and post it on stackoverflow since it is a question.

**Comment by karenhovhannisian** [comment]
I found the problem. For some reason (xhr instanceof XMLHttpRequest) returns false, but xhr is XMLHttpRequest instance. https://bugs.webkit.org/show_bug.cgi?id=25205

**Comment by danialfarid** [comment]
How is it related to progress event?
That bug seems very old and fixed already.
