### ISSUE TITLE
Not sending any body?

### ISSUE THREAD

**Issue by 9mm** [danialfarid/ng-file-upload#1177]
Sorry... I have been trying to get this to work for ages and I cant figure it out.

For whatever reason, when I upload an MP3, the body isnt getting sent. Only the filename.

I've checked the examples like 100 times and I can't see what I have wrong here:

```
    Upload.upload({
      url: '/api/upload/tracks',
      data: { file: file }
    }).then(function(resp) {
      // do success stuff
    }, function() {
      // do error stuff
    }, function(e) {
      // do progress stuff
    });
```

And this is the request:

```
------WebKitFormBoundarylbYSwHYH95kxUtvq
Content-Disposition: form-data; name="file"; filename="test.mp3"
Content-Type: audio/mp3
```

Any ideas?

**Comment by stanleyxu2005** [comment]
Do you have any solution? I was able to upload files. But I tried to wrap ng-upload in a directive, uploading will fail. The file object looks exactly the same as previous. It seems the body is not sent. WIred issue.
