### ISSUE TITLE
ngf-allow-dir on firefox tries to upload

### ISSUE THREAD

**Issue by yeou** [danialfarid/ng-file-upload#1179]
When I drag a folder on the dropzone it tries to upload a file with the foldername.
The library shouldn't send a request in this case.
It doesn't matter if ngf-allow-dir is true or false. Firefox is always sending a request.

You can reproduce this on this link: https://angular-file-upload.appspot.com/ with firefox

Is there some option where I can disable this (folder behaviour) correctly?

**Comment by danialfarid** [comment]
Fixed at 10.1.8

**Comment by yeou** [comment]
Thank you for your quick reply.

But there is still a small bug on Chrome. 
My workaround was like this:

     //Chrome sets the type to 'directory' and We don't need to upload this.
     if (file.type === 'directory' || (file.size === 0 && file.type === '') ) {
                 return true;
             }

Your code:

    var file = fileList.item(j);
            if (file.type || file.size > 0) {
              files.push(file);
            }
    // doesn't take into account the 'directory' type and thus still tries to upload the folder

Could you update this ?

**Comment by danialfarid** [comment]
It doesn't get to that code for Chrome. The demo page seems to work fine.

**Comment by yeou** [comment]
Just tested this on Chrome  (OSX and ubuntu) with the demo page.
This is the output:

<img width="440" alt="screen shot 2015-12-04 at 19 18 52" src="https://cloud.githubusercontent.com/assets/14311618/11597440/01ed875a-9abc-11e5-8f1f-49b84f0e8994.png">
The structure of the directory is: 
 -logs
     - .DS_Store
     - .gitkeep
     - dev.log
     - prod.log

As you can see the logs folder is also send to the server.
And also there seems to be a bug, the size is never set in chrome so it throws an error:
<img width="588" alt="screen shot 2015-12-04 at 19 22 04" src="https://cloud.githubusercontent.com/assets/14311618/11597500/76975fa4-9abc-11e5-93fe-6e72a4ddf21a.png">

Maybe your check is running earlier in the app and so the directory type is not yet set? It is probably coming from the webkitGetAsEntry?

**Comment by danialfarid** [comment]
That error could be fixed in the demo code by not sending the directories.
The idea is that when you are dropping the directory you might wanna know the directory name or send it to the server so you could create the same directory structure. So if the allowDir is true then the directories will be included in the files.

**Comment by yeou** [comment]
Wouldn't it be better if this behaviour was configurable? Some APIs might not want to recreate the folder, but just upload the contents of them.
At least that's the case for me.

If not I could catch this case in the controller.

**Comment by danialfarid** [comment]
I think would be easier to just add `if (file.size)` if your controller rather than adding another configuration option. Also if you have a validation on the file size like ngf-min-size="1" that should get rid of folders.

**Comment by danialfarid** [comment]
Fixed at 11.2.0.
By default it would not include directories, you can change that by `ngf-include-dir="true"`
