### ISSUE TITLE
ie 8 can't open explorer window

### ISSUE THREAD

**Issue by Dragna** [danialfarid/ng-file-upload#118]
Hello,

I have the exact same issue as this one : 
Issue #91 

But i'm following what you said here is my code :

```
<span  class="btn btn-success fileinput-button">
    <i class="icon-plus icon-white"></i>
    <span>Change icon</span>
    <input id="iconeUpload" type="file" ng-file-select="onFileSelect($files)" />
</span>
```

The script are loaded :

```
<script>
    //optional need to be loaded before angular-file-upload-shim(.min).js
    FileAPI = {
        jsPath: 'vendor/angular-file-upload/FileAPI.min.js',
        staticPath: 'vendor/angular-file-upload/FileAPI.flash.swf'
    }
</script>
<script src="vendor/angular-file-upload/angular-file-upload-shim.min.js"></script>

<script src="vendor/angular/angular.min.js"></script>
<script src="vendor/angular/angular-route.min.js"></script>
<script src="vendor/angular-file-upload/angular-file-upload.min.js"></script>
```

But on ie8 the explorer window doesn't open. And I don't know what i'm doing wrong.
Could you help me please ?

**Comment by v29neil** [comment]
I am having the same issue.
html:
<button ng-file-select ng-file-change="upload($files)">Upload</button>
Getting the error :
Error: Out of memory<button style="POSITION: relative; OVERFLOW: hidden" class="btn btn-default ng-isolate-scope" type=submit ng-file-change="upload($files)" ng-file-select ng-1421214453147="8">
Adding 
.js-fileapi-wrapper {
position:static !important;
}  doesnt solve the problem either.  
I am not attaching the css to button still it is giving error.
This code is working fine in IE9,chrome,firefox. Giving error in IE8.

**Comment by v29neil** [comment]
//Error: Out of memory<button style="POSITION: relative; OVERFLOW: hidden" class="btn btn-default ng-isolate-scope" type=submit ng-file-change="upload($files)" ng-file-select ng-1421214453147="8">

**Comment by danialfarid** [comment]
@v29neil Does it work if you change the elemtn from button to div?

**Comment by v29neil** [comment]
I tried this also. Copied the css of demo.
<div ng-controller="FileUploadController">
<div class="up-buttons">                                    
                <button  ng-file-select  ng-file-change="upload($files)" resetOnClick="true">Attach Any File</button>
            </div>
</div>
Just like in demo page.  Still giving error. I also tried adding style="position: static/absolute/relative". Nothing seems to work. To give little idea about my implementation, Here are the codes-
 i am opening the modal dialog 
in FileUploadController:

 $scope.upload = function($files) {
            //console.log($scope.modeltest);
            $modal.open({
                templateUrl: 'views/fupload.html',
                controller: 'ModalInstanceCtrl',
                resolve: {
                    file: function () {
                        return $files;
                    }
                }
            });
In ModalInstanceCtrl:
$scope.file = $upload.upload({
                url: 'URL',
                method: 'POST',
                file: file
            })
                .progress(function(evt) {
                    console.log('percent: ' + parseInt(100.0 * evt.loaded / evt.total));
                    if (evt.lengthComputable) {
                        $scope.progress = Math.round(evt.loaded * 100 / evt.total)
                    } else {
                        $scope.progress = 'unable to compute'
                    }

                })
                .success(function(data, status, headers, config) {
                    console.log(data);
                    $scope.complete=true;
                    $scope.close=false;
                })
                .error(function (err) {
                    $scope.failed=true;
                    $scope.fail='Upload failed';
                });
                             $scope.abort = function() {
                                 $scope.file.abort();
                                 $modalInstance.dismiss('cancel');
                             };


        $scope.cancel = function () {
            $modalInstance.dismiss('cancel');
        };

Hope i am doing correct. 
Note: i am testing code in ie8 without compatibility view.

**Comment by v29neil** [comment]
Same error by chaging button to div. 
Demo seems to be working. Not able to figure out why.
