### ISSUE TITLE
Not automatic multiple upload

### ISSUE THREAD

**Issue by GiacomoK** [danialfarid/ng-file-upload#1180]
Hi,
Is it possible to do a not automatic multiple upload? I mean, select files one by one and upload all files clicking on 1 button?

I read the docs but I didnt get if it its possible?

Thanks.

**Comment by danialfarid** [comment]
Yes, uploading and selecting files are totally separate.

**Comment by GiacomoK** [comment]
Thanks for the answer, where can I find out an example? I didnt find it.

**Comment by danialfarid** [comment]
Add `ngf-keep="true"` to the input. Ask on stackoverflow if you are looking for examples.
