### ISSUE TITLE
Any plan to implement this in Angular2?

### ISSUE THREAD

**Issue by shanezheng** [danialfarid/ng-file-upload#1186]

**Comment by danialfarid** [comment]
Once there is a more stable version of it.

**Comment by shanezheng** [comment]
Nice. Looking forward to that.

**Comment by TroyCoombs** [comment]
Now that Angular2 is in RC do you have a timeline for implementing this in Angular2?

**Comment by danialfarid** [comment]
working on it, I would sat couple weeks.

**Comment by TroyCoombs** [comment]
Awesome, thanks!

**Comment by jalchr** [comment]
Hi,
Any planned releases for Angular2?

**Comment by danialfarid** [comment]
Yes I have been working on it, hopefully in 1-2 weeks.
It is almost half way done and it needs a restructuring of the code and port it to TypeScript. If you are willing to contribute I could create a branch that you could work on but since it is 3/4th done it might be just easier to wait.

**Comment by aitboudad** [comment]
@danialfarid did you make any progress on this?

**Comment by danialfarid** [comment]
Yea it's mostly done, you can checkout the code in branch ng2. Expected time would be in December.

**Comment by aitboudad** [comment]
awesome!

**Comment by helzgate** [comment]
Done yet?  KIDDING!!!!

**Comment by ravishan110** [comment]
Hey, First of all, thanks a lot for this awesome library in AngularJs. Loved it! But can you tell me whats the status on releasing it for Angular 2 (or 4) ? Would really love it in angular 2. I am sure many others are waiting for it. :)
