### ISSUE TITLE
Problems sending extra fields and renaming file.

### ISSUE THREAD

**Issue by DrankoLQ** [danialfarid/ng-file-upload#1187]
Hello!

I'm trying to upload a file but I need two extra things: I want to send an extra field and rename the file.
I've been reading your examples but it doesn't work as expected:

```javascript
Upload.upload({
                url: '/postnuevadieta',
                data: {file: Upload.rename($scope.fichero, 'dieta.pdf'), 'email': mail}
```
When I try to get the "email" field in Node.js (req.email) it's undefined, and the rename function doesn't rename the file. Could yo help me?

And by the way, thanks for your work :)

**Comment by danialfarid** [comment]
See the network tab request being sent. If those values are there then the problem is server side.

**Comment by DrankoLQ** [comment]
Yay! AngularJS was sending data correctly, but I was trying to get email using "req.email" instead of "req.body.email".

About the Upload.rename function, any idea why is it not working?

**Comment by DrankoLQ** [comment]
Nervermind, the rename function is working, it's (again) the server side who is not working (I'm using multer lib)

Thanks for your help!
