### ISSUE TITLE
data issue when uploading multiple files plus data for each file wrapped in a promise 

### ISSUE THREAD

**Issue by BonnieBonfire** [danialfarid/ng-file-upload#1194]
I am uploading a set of files each of which have associated data in a loop. However the the request payload shows the data associated with the final file is being sent for each file. Can you help? Thank you.
```
var deferred = $q.defer();
if ($scope.fileData.data.length) {
  for (var i = 0; i < $scope.fileData.data.length; i++) {
    var file = $scope.fileData.data[i].file;
    if (!file.$error) {
      $scope.documentDTO.description = $scope.fileData.data[i].description;
      Upload.upload({
        url: '../document',
        data: $scope.documentDTO,
        file: file
        }).then(function (resp) { ...});
    }
  }
}
deferred.resolve();
return deferred.promise;
```

**Comment by danialfarid** [comment]
Why do you resolve your promise outside `Upload.upload().then()` it would never be resolved.
The demo page and jsfiddle sample use the same looping, you probably have the same data in the array.

**Comment by danialfarid** [comment]
Also since this is a questions post it on SO if you still have issue or create a jsfiddle.
