### ISSUE TITLE
Validations aren't updated in case of drag'n'drop

### ISSUE THREAD

**Issue by hellfrom** [danialfarid/ng-file-upload#1195]
Hi, I have validation problems using drag'n'drop with 10.1.9 version.

http://jsfiddle.net/maqbzv15/404/

Look at 

      <div ngf-drop
          ng-model="picFile">
     
       <input type="file" 
		      ngf-select 
		      ng-model="picFile" 
		      name="file"    
	          required>
          
        <div>{{myForm.file.$error|json}}</div>
     </div>

When I select file using input field `$error` object is empty.
However when I use drag-n-drop - `$error` object still contains 
`{required: true}`. 
What is the right way to validate file using both methods - `input type = 'file'` and drop mode
How to update form validation in case I use drag-n-drop. 

Thanks in advance

**Comment by hellfrom** [comment]
I've found temporary solution in form of additional directive. However I'm not sure that it will be appropriate solution for all other validation strategies such as max-size etc.

````
function link(scope,elem,attrs,ngModelCtrl){
	scope.$watch(()=>ngModelCtrl.$modelValue,newVal=>{
		let type;

		if(!newVal){
			return;
		}

		type = Object.prototype.toString.call(newVal).slice(8,-1).toLowerCase();

		if(type !== 'file'){
			return;
		}

		ngModelCtrl.$setValidity('required',true);
	});
}
```

It seems to be weird to perform this additional operation. 
Maybe there is a better way?

**Comment by danialfarid** [comment]
required is for a single form element and since you have it on the input type file it would be required for that element only.
If you want to make sure the file exists remove the required directive and just check `picFile != null` and show the required error with that check.
