### ISSUE TITLE
globStringToRegex issues...

### ISSUE THREAD

**Issue by neoamuro** [danialfarid/ng-file-upload#1196]
First of all, thanks for a given make a wonderful library.

I had set as follows:
$scope.pattern = '.pdf,.jpg,video/*,!.jog';
but... can't validated...
cause: !.jog

I have found the cause by analyzing the source.

in ng-file-upload.js:
function globStringToRegex(str) 
...
...
...
    if (i < split.length - 1) {
        regexp += '|'; <--------------------------------  This is the cause.
    }
...
...
...
if inserted " ! " in pattern, In regexp it is excluded .
so... In regexp's last character "|" is added.

Finally... 
because "|" of last, regexp.test(file.type)) of validatePattern() function is passed.

Please fix it .
(Im korean, I'm sorry not write English well.)

**Comment by danialfarid** [comment]
This works fine on the demo page.
Please create a jsfiddle showing the error. Attach the problematic files too.

**Comment by neoamuro** [comment]
Ok~! I created the jsfiddle.
This is  reappearance of bug.
link: http://jsfiddle.net/soonwook/4mzmtt41/1/embedded/result/

**Comment by danialfarid** [comment]
What are the steps to reproduce?

**Comment by neoamuro** [comment]
Please select any file except to jpg file.
If it is right work then, will display invalid pattern.
but currently no.
