### ISSUE TITLE
Need update on the typescript definition file

### ISSUE THREAD

**Issue by stunaz** [danialfarid/ng-file-upload#1197]
Hello,
With release frequency on this repo, would be great if someone update the tds file located here https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/ng-file-upload/ng-file-upload.d.ts , this would allow us to quickly check the if the current code is broken with a library update.

**Comment by danialfarid** [comment]
Post it on their github.
If there is a script I could run to update that I could do that but that is a separate repo and need to know the process for updating that file.

**Comment by stunaz** [comment]
As far as I know there is no special process, only need to submit a PR with updated definition file and test. I will post an issue in their github too, I just though it will be easier to find help here (as I saw many time that they just suggest to post a PR).

**Comment by stunaz** [comment]
ref https://github.com/DefinitelyTyped/DefinitelyTyped/issues/7278

**Comment by nkovacic** [comment]
Already updated.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/7640

**Comment by stunaz** [comment]
Thank you  @nkovacic , that is a big step.
But I couldn't find the definition type for the `file` object itself, and more importantly for the `errors` object.
Thank you again

**Comment by nkovacic** [comment]
The File object is already included in TypeScript core lib.d interfaces. Could you provide a link to the errors object, because I cant find it in the source.

**Comment by stunaz** [comment]
Hi @nkovacic  check this plunker from @danialfarid  http://jsfiddle.net/danialfarid/0mz6ff9o/135/
Look at the `$invalidFiles` on the html file and `errFiles` on the js file.
At the same time, there si the `evt` type missing, which have the properties `loaded` and `total`
Thanks.

**Comment by Miced** [comment]
Definitions seem to be up to 11.1.1 version.
