### ISSUE TITLE
Sample usage error in IE9

### ISSUE THREAD

**Issue by momyyao** [danialfarid/ng-file-upload#1199]
I'm trying this sample usage in IE9: http://jsfiddle.net/danialfarid/s8kc7wg0/219/
And I'm getting this error:
ngFileUpload: Circular reference in config.data. Make sure specified data for Upload.upload() has no circular reference: file[blob][files][0]

I have to set file.blob.files = [] for it to work.  But still, the file size will be 0 so the progress bar won't work correctly.

**Comment by mechevarria** [comment]
I am running into the same issue when trying to upload a file in IE9.  I am not bothering with progress but it still doesn't work.  Is there a workaround?

**Comment by danialfarid** [comment]
That was a bug introduced recently for fixing accessibility warning. Fixed at version 10.1.14.

**Comment by IsraelSouza** [comment]
I have the same issue, now on version 11.0.0.

**Comment by danialfarid** [comment]
@IsraelSouza Have you tried with the latest version? Post your code here. Does the demo page work?

**Comment by IsraelSouza** [comment]
Hi!! I have tried with the version 11.0.0, downloaded by bower.. As i have to solve this with certainly urgency, i opted to use angular-file-upload, thanks a lot for fast response, and sorry by poor english.

**Comment by jducrot** [comment]
I am getting this issue on and off (which is really weird) on IE9 with 11.1.1

**Comment by thilakWD** [comment]
I have the same issue in 11.0.0

**Comment by danialfarid** [comment]
@thilakWD What issue do you have and is the demo page and the jsfiddle mentioned above working?

**Comment by thilakWD** [comment]
I am getting this error in ie9 `ngFileUpload: Circular reference in config.data. Make sure specified data for Upload.upload() has no circular reference: file[blob][files][0]` . it is working in ie10 and above. but it is not working in ie9. i have used 11.0.0 version

**Comment by danialfarid** [comment]
and the jsfiddle mentioned above working?

**Comment by thilakWD** [comment]
In ie10 and above, that above jsfiddle as well as my project is working. but in ie9 the js fiddle shows this error in console `SCRIPT5007: Unable to get property 'id' of undefined or null reference` .
 and in my project it shows `ngFileUpload: Circular reference in config.data. Make sure specified data for Upload.upload() has no circular reference: file[blob][files][0]` as i have used file api and flash  which was in your post.

**Comment by thilakWD** [comment]
If you could help, can you please tell me how to write, if it is ie9--> it should take normal upload, other wise it should take ng-file-upload. Please

**Comment by thilakWD** [comment]
This will be the problem when i use this code for preview on my page. '<img ng-show="myForm.file.$valid" ngf-thumbnail="picFile" class="thumb">` if i comment or remove this line ,i can upload but not able to preview it. is there any fix for it.

**Comment by thilakWD** [comment]
I have included html5shiv script. it solves me the problem. thank you

**Comment by StephanieOSZ** [comment]
Hello, I'm having the same problem on IE9 with 11.1.1.
When I use Chrome or Firefox everything works fine, but using IE 9 appears the message : 

ngFileUpload: Circular reference in config.data. Make sure specified data for Upload.upload() has no circular reference: file[blob][files][0] 

I'm calling on page
<script>
       window.FileAPI = {
            jsPath: 'js/FileAPI.min.js',        
            staticPath: 'js/FileAPI.flash.swf'        
        };
</script>
<script type="text/javascript" src="js/FileAPI.min.js"></script>
<script type="text/javascript" src="js/ng-file-upload-shim.min.js"></script>
<script type="text/javascript" src="js/ng-file-upload.js"></script>

//MODAL TO INPUT THE FILE
<div id="addAtach" class="modal fade" role="dialog">
                <div class="modal-dialog">
                    
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" ng-click="closeAction()" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title text-light-blue">A3 Attachments</h4>
                        </div>
                        <div class="modal-body">
                            <div>
                                <input type="file" name="file" ngf-select="onFileSelect($file)" ng-model="file">
                                <span style="color:#FF0000;font-style:italic;font-size:10px;margin-top:10px;">*File size cannot exceed 15 MB</span>
                                <span style="color:#FF0000;font-style:italic;font-size:16px;">{{message}}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

//THIS IS MY ANGULAR FUNCTION
$scope.onFileSelect = function(file) {
            $scope.upload = Upload.upload({
            url: './model/uploadA3.php',
            method: 'POST',
            data: {file: file, id_plan: $scope.plan.cod}
        }).success(function(data, status, headers, config) {
			if(data == '1'){
				$scope.message = "Error to send file, verify the type or size!";
			}else if(data == '2'){
				$scope.message = "Please don't use on the file name characters like % or #";
			}else{
				$http.get('./model/atachA3/'+$scope.cod)
					.success(function(data) {
					$scope.atachInfo = data;
					$(data).each(function( i ) {
						$scope.attachCount = i+1;
					  });
				});
				$('#addAtach').modal('hide');
				$scope.message = "";
				$scope.file='';
			}		
        });  
	};

Thank you in advanced!!!

**Comment by danialfarid** [comment]
@StephanieOSZ What version of the plugin? Can you create a reproducible jsfiddle?

**Comment by Juggernaughtt** [comment]
getting the same error using version 12.0.3

**Comment by bartonsprings** [comment]
I am having exact same issue. I am using version 12.2.5. Only happens in IE9

**Comment by danialfarid** [comment]
make sure you include the shim file

**Comment by bartonsprings** [comment]
This is what I have. Is there any other Shim I need to include? 

<script src="https://cdnjs.cloudflare.com/ajax/libs/danialfarid-angular-file-upload/12.2.5/ng-file-upload.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/danialfarid-angular-file-upload/12.2.5/ng-file-upload-shim.min.js"></script>

**Comment by danialfarid** [comment]
make sure 'FileAPI.*' files are loaded. They should be placed at the same server location. Checkout the section for Old Browsers in the docs.

**Comment by bartonsprings** [comment]
Thanks. I will check and make sure it is getting loaded.
-------- Original message --------From: Danial Farid <notifications@github.com> Date: 9/6/16  2:38 AM  (GMT-06:00) To: danialfarid/ng-file-upload <ng-file-upload@noreply.github.com> Cc: bartonsprings <bartonsprings2@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [danialfarid/ng-file-upload] Sample usage error in IE9 (#1199) 
make sure 'FileAPI.*' files are loaded. They should be placed at the same server location. Checkout the section for Old Browsers in the docs.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/danialfarid/ng-file-upload","title":"danialfarid/ng-file-upload","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/danialfarid/ng-file-upload"}},"updates":{"snippets":[{"icon":"PERSON","message":"@danialfarid in #1199: make sure 'FileAPI.*' files are loaded. They should be placed at the same server location. Checkout the section for Old Browsers in the docs."}],"action":{"name":"View Issue","url":"https://github.com/danialfarid/ng-file-upload/issues/1199#issuecomment-244872911"}}}

**Comment by bartonsprings** [comment]
Ok. I added the FileAPI.* shims also in my paths (I thought earlier that they will be downloaded on demand) but I included them in my index.html. But same errors. Here is the image of IE9 network loads:

![image](https://cloud.githubusercontent.com/assets/9456041/18297977/9bcc36da-747a-11e6-972e-0f0ca9fbea84.png)

Also, here are the error messages I am getting:

```
ngFileUpload: Circular reference in config.data. Make sure specified data for Upload.upload() has no circular reference: file[blob][files][0] 
TypeError: Unable to get value of the property 'ignoreAuthModule': object is null or undefined 
```

**Comment by danialfarid** [comment]
You can check if you are loading it properly by right clicking on the button and it should show the flash context menu.

**Comment by bartonsprings** [comment]
It does not show the Flash context menu so something is wrong on my side. I am using a virtualbox VM (Win7/IE9). Don't know if that could be creating an issue. But I checked that Flash is loaded on my system.

**Comment by danialfarid** [comment]
Use the demo page as the guide, copy the code to your page and try from a simple example. Also the order of loading the scripts are important.

**Comment by catzaizai** [comment]
I know how it happened
When the content is too long to appear scroll bar
If the upload button is outside the screen
The flash control does not cover the button correctly

**Comment by Benjanver** [comment]
Same happening here. I am using version 12.2.12. Only happens in IE9
