### ISSUE TITLE
Problems with PUT method

### ISSUE THREAD

**Issue by csilvav** [danialfarid/ng-file-upload#1200]
This library is awesome, however when I tried to send data (with file of course) via PUT, in the server side I was many problems with all data, I could not retrieve the data sent thru HTTP PUT method, I saw the all content and was so strange, it seemed corrupted.

Sending data thru POST was not a problem. Meanwhile as workaround I created a new route with POST method too, sending the identifier on url.

**Comment by danialfarid** [comment]
Should be server side problem. There is no special handling of PUT method in this plugin.

**Comment by csilvav** [comment]
Hi @danialfarid, I don't think so, why? because the back-end is on PHP and Laravel framework, and I have other routes and controllers for other processes where I send data through POST and PUT methods and I never got a problem, the data always was receive successfully in the server-side.

So I tested sending data thru PUT with other data and everything was Ok., but then using Upload.upload  service-function, setting "method" to "PUT" I got problems with the all data.

regards....

**Comment by danialfarid** [comment]
Probably server handles PUT multipart/form-data requests differently. If you see the request being sent on the network tab of your browser you would see that it looks exactly like POST request.

**Comment by csilvav** [comment]
@danialfarid thanks for your time, maybe you're right because the data is been sending to the server but with a strange format, I think that is a different behavior using multipart requests using PUT.

**Comment by arseneoaa** [comment]
Hi,

I also had the same issue using Laravel, also changed to POST.

**Comment by danialfarid** [comment]
Make sure you don't set the `content-type` when you are using `Upload.upload()` that could be the problem.

**Comment by jacksbox** [comment]
Hi, I just had the same problem with Laravel 5. I found an easy workaround - send the request via POST but attach ?_method=PUT to the url, so Laravel will use your PUT function.

And after 15min of searching the web, I just discovered taht this is probably the only way to do this:
https://laravel.com/docs/5.2/routing#form-method-spoofing

**Comment by rafwell** [comment]
I've faced the same issue. If you send an item _method on your post request, it will work.
Soo,

```
$scope.data['_method'] = $scope.isUpdateForm() ? 'PATCH' : 'POST';

Upload.upload({
            method: 'POST', //dont change this
            url: 'admin/your-url',
            data: $scope.data
        }).then(function(response){

        }).catch(function(response){

        });
```
