### ISSUE TITLE
Binding to pattern and accept values

### ISSUE THREAD

**Issue by DaAwesomeP** [danialfarid/ng-file-upload#1201]
I have a checkbox that I want to control whether the uploader only allows certain file types or everything. However, I cannot get the pattern and accept values to to change when I change that scope variable:
```html
<div ngf-select ngf-drop
     ng-model="main.file.upload.data"
     ngf-model-invalid="main.file.upload.invalid"
     ngf-invalid-class="bg-danger"
     ngf-multiple="false"
     ngf-pattern="main.file.upload.pattern"
     accept="{{main.file.upload.accept}}"
     ngf-accept="main.file.upload.accept"
     ng-disabled="main.file.loading"
     ngf-drag-over-class="{accept:'bg-info', reject:'bg-danger', delay:100}" 
     ngf-valid-only="true"
     ngf-keep="false"
     ngf-allow-dir="false"
     ngf-drop-available="main.file.upload.dropAvailable">
  <button class="btn btn-xs btn-primary">Select File</button>
  <span ng-show="main.file.upload.dropAvailable">or Drag/Drop File Here</span>
</div>
```
When I change `vm.file.upload.pattern` and `vm.file.upload.accept` to `null` from my controller, there is no affect on the uploader.

**Comment by danialfarid** [comment]
The demo page does that, you can set those model values to empty and it would work. That could give you a clue where in your code things go wrong.
If you can reproduce it in a jsfiddle post it here and I will have a look.

**Comment by DaAwesomeP** [comment]
http://plnkr.co/edit/XCLYjn?p=preview

When you check the checkbox, it change the value of the accept and pattern, but this has no affect. If the red alert appears, then the `invalid` variable has a pattern error.

**Comment by danialfarid** [comment]
When i check the checkbox `main.file.upload.pattern` still has the same value.

**Comment by DaAwesomeP** [comment]
My bad. I should have debugged it a little more. The if statement wasn't updating automatically. I added a function to the checkbox with `ng-click` now that will update it.

Thanks for your quick reply.
