### ISSUE TITLE
abort function for Upload.http?

### ISSUE THREAD

**Issue by hellohereiam** [danialfarid/ng-file-upload#1202]
Hi, I am using Upload.http and not Upload.upload to upload via pre signed upload URI to gcs (Google Cloud Storage). For longer upload I wanted to add a cancel button to cancel the upload, but as it turns out Upload.http does not return the abort / pause function that is provided by Upload.upload. Is this correct, or am I missing something?

Thans and all best,
Tobias

**Comment by danialfarid** [comment]
It does.

**Comment by hellohereiam** [comment]
Thanks, I realized that this does not work:
```
file.upload = Upload.http({
    url: uploadurl.url,
    method: 'PUT',
    filename: file.name,
    headers: {
        "Content-Type": file.type !== '' ? file.type : 'application/octet-stream'
    },
    data: file
}).then(function (resp) {
    //success
}, function (resp) {
    //log upload error
}, function (evt) {
    //progress
});

file.upload.abort();
```
because abort(); (and all the other methods) is not existent in file.upload.
Whereas this does work indeed:
```
file.upload = Upload.http({
    url: uploadurl.url,
    method: 'PUT',
    filename: file.name,
    headers: {
        "Content-Type": file.type !== '' ? file.type : 'application/octet-stream'
    },
    data: file
});

file.upload.then(function (resp) {
    //success
}, function (resp) {
    //log upload error
}, function (evt) {
    //progress
});

file.upload.abort();
```

**Comment by mcka-dev** [comment]
Thanks @hellohereiam. It works now

**Comment by amar3128** [comment]
Thanks tobiasvielmetter, that is working fine to cancel a single file upload. My requirement is i will upload multiple files, and need to cancel the upload after couple of files are uploaded. fighting from past two days, it could be great if some helps

**Comment by tobiasvielmetter** [comment]
@amar3128 not sure your issue is relevant to this. are you uploading the different element after each other or in parallel? if in parallel make sure you have the reference to the correct file. i would probably recommend to upload serially though first, once you have mastered that you can still try and see how to upload in parallel, if you feel it better fits your use case.
