### ISSUE TITLE
How to get contents of file in JavaScript?

### ISSUE THREAD

**Issue by DaAwesomeP** [danialfarid/ng-file-upload#1205]
I've tried both `ng-model` and the output of the function tied to `ngf-drop`, but all I get is an object with metadata about the file, which is useful, but is not the actual file's data. How can I get the binary or textual contents of the file without sending it to a server?

**Comment by danialfarid** [comment]
Ask it on Stackoverflow please since it is a question.
You can read the file content with FileReader api.
