### ISSUE TITLE
Setting Content-Type of individual parts inside multipart request

### ISSUE THREAD

**Issue by uyilmaz** [danialfarid/ng-file-upload#1207]
When submitting a multipart form with a bunch of fields together as json plus a file, is there a way to set json part as Content-Type: application/json? Because Spring cannot pick up the parts without Content-Type set.

Upload.upload({
	url : 'myUrl',
	data: {file: myFile, request: angular.toJson(myFormData)}
})

This posts a 2 part multipart, file part has the correct Content-Type, but json part doesn't have that header.

**Comment by danialfarid** [comment]
You can use `Upload.jsonBlob(myFormData)` this will send the data as a blob (byte array) but with application/json content type.
Otherwise you cannot set the content type of a string form-data. XMLHttpRequest limitation.
