### ISSUE TITLE
File unique identifier

### ISSUE THREAD

**Issue by shanezheng** [danialfarid/ng-file-upload#1209]
It would be good to post _fileIdentifier (a random GUID??) for chunking, so the uploaded file can be uniquely identified.

The scenario is that I may have multiple web api server that can accept file POST request, the chunks are NOT guaranteed to hit the same server, such that I need a unique way to identify them.

**Comment by danialfarid** [comment]
You can use the file name or if that is not unique enough for you, you can use `Upload.rename()` to give the file a unique name.

**Comment by shanezheng** [comment]
@danialfarid Sure. Thanks a lot for your help. This file upload directive is awesome. Love it.
