### ISSUE TITLE
Accept request header always set to 'text/*' when reverting to FileApi

### ISSUE THREAD

**Issue by mbyrne00** [danialfarid/ng-file-upload#121]
When using the plugin with a HTML5 compatible browser it produces a request with the Accept request header as 'application/json', however the FileApi (flash) code always produces an Accept header of 'text/*'.

I can't find a way to override this and this causes issues with Java server-side code.

Any workarounds in the mean time would be greatly appreciated.

The following have been tried and have no effect:
1) Setting headers in $upload:
     $upload.upload({headers: {accept:'application/json',....}})

2) Editing angular-file-upload-shim.js and forcing header config
      // Hack to try to force headers to be passed to FileAPI
      config.headers = {'Accept': 'application/json'};
      // Existing line below
      xhr.__fileApiXHR = FileAPI.upload(config);

After making each of the above changes and sniffing the traffic, the Accept header was still 'text/*'

**Comment by danialfarid** [comment]
No easy solution or alternative for this and there are server workarounds for this issue.
