### ISSUE TITLE
Can't abort an upload?

### ISSUE THREAD

**Issue by KannarFr** [danialfarid/ng-file-upload#1210]
Hi,

I've read on your README these lines:

<code>var upload = Upload.upload({...});</code>

and

<code>upload.abort();</code>

But it seems that abort() isn't existing for upload var??

Where am i wrong? :)

**Comment by danialfarid** [comment]
Post your code

**Comment by KannarFr** [comment]
<code>


        service.removeFromQueue = function(obj) {
            console.log('Removing ' + obj.file.name + ' from queue...');
            if (obj.uploadRequest) {
                console.log('Currently in upload, stopping it...');
                console.log(obj.uploadRequest);
                obj.uploadRequest.abort();
                console.log('Stopped');
            }
            service.objects.splice(service.findIndexFromObject(obj), 1);
            console.log('Removed');
        };

        service.nextToUpload = function() {
            console.log('Looking for next to upload...');
            service.upload(service.objects[++service.currentUploadingID]);
        };

        service.upload = function (obj) {
            if (obj !== undefined) {
                console.log('Starting upload of : ' + obj.file.name + '...');
                obj.isUploading = true;
                obj.isUploadFailed = false;
                obj.uploadRequest = Upload.upload({
                    url: 'https://angular-file-upload-cors-srv.appspot.com/upload',
                    data: { file: obj.file, 'username': 'kannar' }
                }).then(function (resp) {
                    console.log('Success ' + resp.config.data.file.name + 'uploaded. Response: ' + resp.data);
                    obj.isUploading = false;
                    obj.isUploaded = true;
                    service.removeFromQueue(obj);
                    service.nextToUpload();
                }, function (resp) {
                    console.log('Error status: ' + resp.status);
                    obj.isUploadFailed = true;
                }, function (evt) {
                    obj.progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
                    console.log(obj.progressPercentage + '% ' + evt.config.data.file.name);
                });
                console.log(obj.uploadRequest);
            } else {
                console.log('Object to upload is UNDEFINED');
            }
        };

</code>

**Comment by KannarFr** [comment]
obj.uploadRequest.abort();

obj.uploadRequest = Upload.upload({
                url: 'https://angular-file-upload-cors-srv.appspot.com/upload',
                data: { file: obj.file, 'username': 'kannar' }
            }).then(function (resp) {

**Comment by danialfarid** [comment]
```
 obj.uploadRequest = Upload.upload({
                url: 'https://angular-file-upload-cors-srv.appspot.com/upload',
                data: { file: obj.file, 'username': 'kannar' }
            });
 obj.uploadRequest.then(....
```
would have it

**Comment by KannarFr** [comment]
Thank you!
