### ISSUE TITLE
File type is blank in Windows 7 and Windows 10

### ISSUE THREAD

**Issue by hsujeremyc** [danialfarid/ng-file-upload#1211]
Using 
```
<input type="file" ngf-select ng-model="uploadSelections.csvFile" />
```
whenever I look at `$scope.uploadSelections.csvFile.type` in Mac OS, it returns `text/csv` as expected.

However, in Windows (7 and 10 tested), running Chrome and IE11, `$scope.uploadSelections.csvFile.type` returns an empty string `''`. The file object looks like this
```
File {}
  lastModified: 1450235407000
  lastModifiedDate: Tue Dec 15 2015 19:10:07 GMT-0800 (Pacific Standard Time)
  name: "filename.csv"
  size: 20524
  type: ""
  webkitRelativePath: ""
  __proto__: File
```

Any help would be appreciated.

**Comment by danialfarid** [comment]
There is not much to do since it is browser specific. You can add a function to guess the file type from the extension for the files that don't have the type reported as a workaround.

**Comment by hsujeremyc** [comment]
@danialfarid, this actually is not browser specific. It seems like it is more OS specific. This issue happens in both Chrome and IE in Windows 7 and 10, but works fine in Chrome in OSX.

**Comment by danialfarid** [comment]
File type property cannot be set programmatically so the best way is to have the check for file extension in the pattern.

**Comment by juliusbz** [comment]
I am having this issue as well. .csv type is empty on file upload

**Comment by kadir-calvid** [comment]
@danialfarid  I am also facing the same issue file type empty on windows but working fine with ubuntu.
also tried ngf-pattern="*" but no success.
any solution for the same?

**Comment by DrummerHead** [comment]
Hello! I come from the future to tell you not to rely on `filetype` mime type when using `FileList` since on Windows this is blank.

Just had this exact same problem, commenting here since this is the only reference to this problem I've found online.

```TypeScript
-                if (fileList[0].type === 'text/csv') {
+                if (/\.csv$/i.test(fileList[0].name)) {
```

Cheers!
