### ISSUE TITLE
Upload to owncloud through webdav

### ISSUE THREAD

**Issue by trinhvanhuy** [danialfarid/ng-file-upload#1213]
Hello, 
I'm using ng-file-upload to owncloud, the upload is successful for other files type except image
All images .png, .jpg are boken when i'm uploading ( for example, i uploaded images 900KB, but the image on server is just 800KB, thats why it's broken.  ) 
here is my code 
$scope.uploadFiles = function (files) {
        $location.hash('bottom');
        $anchorScroll();
        $scope.uploadingFile = files[0];
        $scope.uploadingFile.mtime = new Date();
        $scope.uploadingFile.percent = 0;
        angular.forEach(files, function (file) {
            //blockUI.start();
            Upload.upload({
                url:  $window.serverPath + 'owncloud/remote.php/webdav/' + $rootScope.currentDir.path + '/' + file.name,
                file: file,
                method: 'PUT'
            }).then(function (resp) {
                $scope.uploadingFile = null;
            }, function (resp) {
                console.log('Error status: ' + resp);
                $scope.uploadingFile = null;
            }, function (evt) {
                var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
                $scope.uploadingFile.percent = progressPercentage;
                console.log('progress: ' + progressPercentage + '% ');
            });
        });
    };

**Comment by danialfarid** [comment]
Ask it on SO please since it is a question. There is no spacial handling of images unless you have image related directives on your element.
