### ISSUE TITLE
Setting filename for an non-file object

### ISSUE THREAD

**Issue by cobaltroad** [danialfarid/ng-file-upload#1214]
I'm using a third party app that returns a data url, thus it doesn't respond to `Upload.rename(myData, 'foo.jpg')` since my object is just a string.  Currently I'm doing this:

    Upload.upload({
      url: 'https://myserver.com/myresource/upload',
      headers: myHeaders,
      data: {
        file: myData
      }
    });

which creates a request payload that looks like this:

    ------WebKitFormBoundary4xzOsgH7wzc7giFo
    Content-Disposition: form-data; name="file"
    
    /9j/4AAQS[...snip...]
    ------WebKitFormBoundary4xzOsgH7wzc7giFo--

How do I add `filename='foo.jpg'` to the Content-Disposition line?

Thanks for your time.

**Comment by danialfarid** [comment]
Use `upload.dataUrltoBlob(dataurl, name);` to convert the dataUrl to Blob and then send it in place of the file.
