### ISSUE TITLE
not getting the link of the uploaded object in amazon S3 bucket.

### ISSUE THREAD

**Issue by NavneetKaur9** [danialfarid/ng-file-upload#1220]
When an object gets uploaded to my s3 bucket, following properties gets generated in the bucket(when i see the property of an object in s3 bucket):
Bucket: 	loudshout-videos
Folder: 	s3UploadExample
Name: 	6805$ryan_gosling_hey_girl_meme_5_1agc9n9-1agc9o4.jpg
Link: 	
[This is a public link] https://s3-ap-southeast-1.amazonaws.com/loudshout-videos/s3UploadExample/6805%24ryan_gosling_hey_girl_meme_5_1agc9n9-1agc9o4.jpg
Size: 	37623
Last Modified: 	Mon Dec 21 18:28:34 GMT+530 2015
Owner: 	amit.vaish
ETag: 	744ad6adbc24fce70cd53484fd56cc0d
Expiry Date: 	None
Expiration Rule: 	N/A

I want the "Link:https://s3-ap-southeast-1.amazonaws.com/loudshout-videos/s3UploadExample/6805%24ryan_gosling_hey_girl_meme_5_1agc9n9-1agc9o4.jpg" to be returned back as a response ,once the file gets uploaded.

Please suggest how am gonna do that?
 Cheers,

**Comment by danialfarid** [comment]
Ask on Stackoverflow not related to the client side js.

**Comment by NavneetKaur9** [comment]
i didn't get you..client side js means what?

**Comment by danialfarid** [comment]
Your question is related to amazon S3 and how to return a url in the response not specific to this library ask it on stackoverflow.

**Comment by NavneetKaur9** [comment]
Thank you so much
