### ISSUE TITLE
Memory leaks when using ngf-select on element other than file input

### ISSUE THREAD

**Issue by dani3l** [danialfarid/ng-file-upload#1222]
Hi dude! Thanks for your package - it's a really great one.
I've noticed that ngf-select leaking when it's being used on any element other than file input.

I guess it's because the directive creates the file input and something just doesn't clear right.

**Comment by danialfarid** [comment]
How do you know it is leaking? What version are you using?

**Comment by dani3l** [comment]
version 10.1.11

I noticed in chrome profiler that some of my services wasn't cleared, and I had to dig in and check why. 
When I removed the ngf-select attribute it cleared alright as well as when I used ngf-select inside a file input.

**Comment by danialfarid** [comment]
It should clear them, it would create an input type file to do the actual browser select for div or button but only one extra element should be present at all times and would be cleared on scope destroy or recompiling. 
If you could dig further or create a jsfiddle to narrow down when it keeps the reference would help to find the issue.

**Comment by dani3l** [comment]
I wish I had the time :(
For now I'm using it within a file input and when user clicks on a button it simulates a click (which is what you did in clickHandler).

Maybe it's becuase the file input is created outside of the scope?

And again - thank you for the awesome package!
