### ISSUE TITLE
Data sent as Query String after upgrading

### ISSUE THREAD

**Issue by slimovic** [danialfarid/ng-file-upload#1223]
Hello there,

 By upgrading the ng-file-upload from version **6** to the version **10.1.11**, I got a problem in the server side:

Let's say I want to send this data with the file:

test = {A: "X", B: "Y", C: "Z"}

In the frontend I send it like this using the old version:

Upload.upload({
        url: '/api/upload/',
        file: file,
       data: test,
});

In the server side I receive this string: 
{data=%7b%22A%22%3a%22X%22%2c%22B%22%3a%22Y%22%2c%22C%22%3a%22Z%22%7d}
And this is good

By upgrading I got a query string like this: {A=X&B=Y&C=Z}
Like Im using the **GET** method, even I force it to use **POST** and change to the new format(with the version **8**)
 
$upload.upload({
        url: '/api/upload/',
        method: 'POST',
       data: {test, file: file}
});

And still getting the same result.

**Comment by danialfarid** [comment]
Read the docs about chunk upload and see the demo page code.
The get request is to know how much of the file is already uploaded.
Also `data: {test, file: file}` is a wrong json format.

**Comment by slimovic** [comment]
I deleted the second point about chunks.
Could you explain more? What should I do (without changing the backend) with the new version to send my data(test) like the old version?

**Comment by danialfarid** [comment]
If you want to send the file in chunks you need to change the server code. It needs to be able to receive chunks and assemble them on the server side.

**Comment by slimovic** [comment]
I meant after upgrading to the last version from the version 5, Im receiving a different type of data as "Query String" (something like that: {A: "X", B: "Y", C: "Z"}) and this brake my code in the server side.
what should I change in the client side?

**Comment by danialfarid** [comment]
post your code

**Comment by slimovic** [comment]
In the old version(I used the version 5), I send the data and file as fallows:
```javascript
Upload.upload({
    url: '/api/upload/',
    file: file,
    data: test
});
```

in the new one, with your upgrade Im sending the data + file as fallows: 

```javascript
Upload.upload({
    url: '/api/upload/',
    data: {test: test, file: file}
});
```

**Comment by danialfarid** [comment]
try 
```
test.file = file;
Upload.upload({
    url: '/api/upload/',
    data: test
});
```
```

**Comment by slimovic** [comment]
Same problem

**Comment by danialfarid** [comment]
Create a jsfiddle showing steps to reproduce.

**Comment by slimovic** [comment]
I dont have a problem in my client side, I'm sending my data this way:

```javascript
Upload.upload({
    url: '/api/upload/',
    file: file,
    data: test
});
```
As I told you the data that I'm sending(the extra data or the arguments, in this case **test**) from the js client received in the server(C# with web API ) as different format not like before(with the version 5).

**Comment by danialfarid** [comment]
so is the data being sent the same way as version 5? You can compare them in he browser's network tab.
If they are the same then the problem is server side which is not an issue with this plugin, you can ask it on SO.

**Comment by slimovic** [comment]
I have some news:
The data are not sent the same way, I checked the the network tab, under the Headers.
Let's say I want to send this object: 
test = {A: "foo", B: 0, C: null"} and the file is: **text.txt**

The **request Payload**  contain in the version **5.0.9**:

------WebKitFormBoundaryxNFyB3Vv5Cw2FJNm
Content-Disposition: form-data; name="data"

{"A":"foo","B":0,"C":null}
------WebKitFormBoundaryxNFyB3Vv5Cw2FJNm
Content-Disposition: form-data; name="file"; filename="text.txt"
Content-Type: application/octet-stream

The **request Payload**  contain in the version **11.2.2**:

------WebKitFormBoundary7dfVMOOigis96tQA
Content-Disposition: form-data; name="A"

"foo"
------WebKitFormBoundary7dfVMOOigis96tQA
Content-Disposition: form-data; name="B"

0
------WebKitFormBoundary7dfVMOOigis96tQA
Content-Disposition: form-data; name="C"

null
------WebKitFormBoundary7dfVMOOigis96tQA
Content-Disposition: form-data; name="file"; filename="text.txt"
Content-Type: application/octet-stream

So what I can conclude that the arguments are sent separately in your latest versions.

I will try to make a **jsfiddle** for each one.

**Comment by slimovic** [comment]
Here you go:

[Plunker with Angular file upload 5.0.9](http://plnkr.co/edit/pghp1SqrxyjWIPLwa2oV?p=preview)
[Plunker with Angular file upload 11.2.3]( http://plnkr.co/edit/cCVcZX0bpk9DKbfRpbkF?p=preview)

**Comment by danialfarid** [comment]
Use `Upload.json()` to convert your data to json before sending if you want to send them in one form data element.

**Comment by slimovic** [comment]
Interesting..
That fix the problem, I added a [plunker ](http://plnkr.co/edit/OiiiPk3aoew5roW0CaeO?p=preview) with the fix.
Thank you.
