### ISSUE TITLE
Override display:none for file preview tag

### ISSUE THREAD

**Issue by gjdownes** [danialfarid/ng-file-upload#1224]
I have the following markup to display a selected image:

<div class="cover-image-preview"
                         ngf-select ngf-accept="'.jpg,.jpeg'"
                         ngf-thumbnail="vm.coverImageUpload"
                         ngf-as-background="true">
                    </div>

I want this to act as the placeholder for select and drop functions as well, but the library seems to add display:none automatically if the thumbnail is unavailable. 

Is there anyway to override this behavior? I've been forced to create a container element which duplicates some of the select/drop logic.

**Comment by danialfarid** [comment]
You can have `ngf-thumbnail="file || 'placeholder'"` or you can overwrite css class `ngf-hide`.
