### ISSUE TITLE
No 'Access-Control-Allow-Origin' header when uploading to Azure Blob Storage

### ISSUE THREAD

**Issue by dotnetjunkie1** [danialfarid/ng-file-upload#1225]
I am receiving the following error when I call the Upload.upload angularjs call: Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:10000/devstoreaccount1/file.mp4?sv=version&sr=c&sig=signature&sp=w. (Reason: CORS header 'Access-Control-Allow-Origin' missing).  I am trying to upload a file to azure blob storage emulator to test the functionality before adding the code to the cloud instance.  What do I need to set on the storage emulator to properly test this functionality under azure?

**Comment by danialfarid** [comment]
You should ask this on Azure Blob Storage forum or StackOverflow.
