### ISSUE TITLE
Fixing orientation changes a file size

### ISSUE THREAD

**Issue by jarszkutn** [danialfarid/ng-file-upload#1227]
Hi,
There is a problem when I setup ngf-fix-orientation="true". My file is 2MB big and I setup max file size to 3MB.
When image is loaded then orientation is fixed and file size increases 3 times ! to 6MB and validation does not take it into consideration.
I believe that fixing file orienetation shouldn't cause image size increase.

**Comment by danialfarid** [comment]
Fixed at version 11.0.0
