### ISSUE TITLE
Weird behaviour during uploading a single file on chrome & safari

### ISSUE THREAD

**Issue by mrded** [danialfarid/ng-file-upload#1228]
Hello, just quick test on your example [Upload single file on file select](http://jsfiddle.net/danialfarid/0mz6ff9o/135/embedded/result/)

I'm trying to upload the same file on chrome (47.0.2526.106) and safari (9.0.2)

And for some reasons safari doesn't want to upload my file. Take a look screenshots:
![screen shot 2015-12-23 at 17 17 42](https://cloud.githubusercontent.com/assets/347098/11981323/9d1bafae-a999-11e5-9b14-2709c0d7f0a0.png)

![screen shot 2015-12-23 at 17 14 36](https://cloud.githubusercontent.com/assets/347098/11981330/a3654000-a999-11e5-909f-c588484d2764.png)

---

Moreover, I made a really basic form which uploads a file to our PHP backend and from chrome backend gets always empty `$_FILES`. Safari submits it correct.

Any thoughts?

**Comment by danialfarid** [comment]
Maybe your file is too large? Is it just the progress that is not updating or is it the POST request that is getting timed out or stays pending?

**Comment by mrded** [comment]
No, the file is small 29 KB. it passes validation.

**Comment by mrded** [comment]
I've changed backend's url on your example to my one, and chrome submits empty $_FILES.
It works completely fine on safari. I haven't tried other browsers yet.

**Comment by mrded** [comment]
I found the problem. It was my backend related. 

`Upload.upload()` sends two requests, `OPTIONS` and `POST`. I was checking $_FILES inside `OPTIONS` request. My bad.
