### ISSUE TITLE
is it support image width or height must be at least some pixes

### ISSUE THREAD

**Issue by zuohd** [danialfarid/ng-file-upload#1229]
currently if I write as the follow ,that is limt the image both width and height are great than 600:
` <input type="file" ngf-select ng-model="logotypefiles" name="file" accept="image/*" ngf-min-height="600" ngf-min-width="600" />`,
any suggestions?

**Comment by acobster** [comment]
You want `ngf-validate`. Using the [demo](https://angular-file-upload.appspot.com/) I was able to get the desired error message using `ngf-validate="{height: {min: 600}, width: {min: 600}}`.

**Comment by danialfarid** [comment]
Fixed at 11.0.0
Added `ngf-dimensions` to customize the validation `ngf-dimensions="$width < 1000 || $height < 1000"`

**Comment by acobster** [comment]
Did I misunderstand what OP was asking or is `ngf-dimensions` do the same thing?

**Comment by danialfarid** [comment]
He wanted an "or" condition for with OR height to be limited. With ngf-validate you can just "and" the conditions.

**Comment by zuohd** [comment]
Great work.
