### ISSUE TITLE
$file or $files null after first use and upload method called multiple times

### ISSUE THREAD

**Issue by johnwpowell** [danialfarid/ng-file-upload#1232]
I am having an issue where I can always successfully upload one or multiple the first time.

The next time I try, it calls the upload method 2 times.  One time the file is null and the second time results is no files being sent to the server.  If I keep trying, it will call the upload method 1 time for each upload attempt.

Is it keeping a reference somewhere?

Here's my code:
```
<a class="btn btn-primary pull-right" id="docAdd" ng-if="vm.canEdit" title="Add Document(s)" ngf-select="vm.uploadDocument($file)"><i class="fa fa-upload"></i>Add Document(s)</a>

uploadDocument(file): void {
                this.uploadService.upload({
                    url: "[my api url]",
                    data: { file: file }
                })
                    .then((response) => {
                        this.documents.splice(0, 0, <Models.Document>{ id: <number>response.data, name: file.name }));
        }

```

I have no problems with drag and drop and I can also use a file input with a separate upload button.  If I try to use the ngf-select on the input file to immediately upload, it also has the same issue.

**Comment by danialfarid** [comment]
Check for null. When you click on the select it will empty previous files so that's why you see null value for the model, so if you cancel the popup the value would stay null.

**Comment by johnwpowell** [comment]
The problem was happening after successfully uploading file(s), not when canceling the dialog.  I was able to work around the behavior by having an ng-if on the button element that does not show the button when uploading.  Then when the upload is finished, the button is displayed.

I think there is a scope/reference problem because my workaround is essentially removing the button after each uploading and replacing it with a new one.  It is worth noting that the app has many ng-includes and is using controller as.  If time permits, I will put together a jsfiddle to repro.

**Comment by danialfarid** [comment]
So what the problem is? Can you describe the steps to reproduce?

**Comment by m2omou** [comment]
I am facing the same issue. 

1- I upload multiple pictures.
2- retry, then I see my upload methods is called 2 times this time. One with null and the other one with my pictures.

So two uploads, my methods is called 3 times.

**Comment by danialfarid** [comment]
@m2omou read https://github.com/danialfarid/ng-file-upload/issues/1232#issuecomment-167440159

**Comment by m2omou** [comment]
@danialfarid Yes this is what I am doing currently to avoid that :)

**Comment by darkmavis1980** [comment]
I'm seeing the same issue, but only on firefox, on Chrome it works fine.
Essentially you select a file, and I can see the file is loaded as I used the ngf-thumbnail, but then if I click on the button to select another file, this time the file model will be null.

**Comment by danialfarid** [comment]
@darkmavis1980 that's expected when you click old file will be cleared so the model will be set to null.

**Comment by darkmavis1980** [comment]
Yes, but when you select a new file, it should populate the  model with the new data no?

**Comment by danialfarid** [comment]
yes it would.

**Comment by darkmavis1980** [comment]
Unfortunately it's happening but only on Chrome, on Firefox it stays null.
I'm using the latest version of the library 11.2.3, I tried to go back to 10.1.x to see if it was making any different, but nothing, it just doesn't work on Firefox (I'm using version 46.0a2, but it's the same with previous versions like 44)

**Comment by danialfarid** [comment]
Create a jsfiddle with steps to reproduce.

**Comment by slfan2013** [comment]
@danialfarid 
Please see this one,
http://jsfiddle.net/n1ux6opb/. Thank you.
