### ISSUE TITLE
accept="application/x-rar-compressed" does not work

### ISSUE THREAD

**Issue by Clan-Utility** [danialfarid/ng-file-upload#1233]
On Mac, in neither chrome (v46) nor safari (v8.0.7), adding accept="application/x-rar-compressed"  does not allow .rar files be selectable. What is the suitable mime type for .rar files (or all compressed files)?

**Comment by Clan-Utility** [comment]
accept=".rar" works in chrome, but not in safari

**Comment by danialfarid** [comment]
That is browser specific. Same as setting it for a regular input type file. You can ask it on stackoverflow or Safari forum. It could be a safari security thing that does not allow seleting .rar files.

**Comment by Clan-Utility** [comment]
OK. Thanks for replying
