### ISSUE TITLE
Being able to limit number of files selected/uploaded with "multiple"

### ISSUE THREAD

**Issue by AdeelMufti** [danialfarid/ng-file-upload#1236]
Hello,

There isn't a way to limit the number of files a user can select when multiple file uploads are enabled. Or, there isn't an easy way, at least. I was doing a custom solution by adding and subtracting from an internal counter (through ngf-validate-fn, which is called for every file selected so a good place to count) but that seems to be difficult to manage and messy especially when there are other validation errors for a file defined through ngf-validate (in which case ngf-validate-fn isn't always called first, and there isn't a way to subtract from the internal number of files counter on ngf-validate errors, since there is no error callback).

Does anyone have a good solution for this?

Thanks!

**Comment by graundas** [comment]
Hi. I have got the same problem recently, so I will try to find a solution. I think that **ngf-max-files** validation constraint would be useful.

**Comment by graundas** [comment]
Currently I do not have much time for this enhancement. Maybe someone will get interested in this.

**Comment by AdeelMufti** [comment]
It would be great if this feature can be implemented. For now I'm not too worried because I'm preventing it on the server side anyway. 

Just FYI the solution below works nicely if an image is selected one by one and added to the array, instead of all at once:

HTML:
            <div id="newImages" class="btn btn-default btn-file"
                 ngf-select
                 ngf-multiple="true"
                 ng-model="images"
                 ngf-validate-fn="validateImage($file)"
                 ...

Angular:
    $scope.validateImage = function(image)
    {
      if($scope.images.length>=10)
        return "TOO_MANY_IMAGES";
      return true;
    }

**Comment by danialfarid** [comment]
Fixed at 11.1.0 'ngf-max-files`
