### ISSUE TITLE
ngFileUpload: Circular reference in config.data.

### ISSUE THREAD

**Issue by diegofc00** [danialfarid/ng-file-upload#1238]
I'm using your lib, and I have a problem...

ngFileUpload: Circular reference in config.data. Make sure specified data for Upload.upload() has no circular reference: file[$parentForm][$success][date][0][$parentForm](anonymous function) @ angular.min.js:107$get @ angular.min.js:80(anonymous function) @ angular.min.js:119$get.n.$eval @ angular.min.js:133$get.n.$digest @ angular.min.js:130$get.n.$apply @ angular.min.js:133(anonymous function) @ angular.min.js:254n.event.dispatch @ jquery.min.js:3n.event.add.r.handle @ jquery.min.js:3
angular.min.js:107 

TypeError: n.headers is not a function
    at responseError (angular-oauth2.min.js:1)
    at angular.min.js:119
    at n.$get.n.$eval (angular.min.js:133)
    at n.$get.n.$digest (angular.min.js:130)
    at n.$get.n.$apply (angular.min.js:133)
    at HTMLFormElement.<anonymous> (angular.min.js:254)
    at HTMLFormElement.n.event.dispatch (jquery.min.js:3)
    at HTMLFormElement.n.event.add.r.handle (jquery.min.js:3)

implementation

			Upload.upload({
				url: url,
				method: 'POST',
				data: {file: $scope.form.file}
			}).then(function (resp) {
				//console.log('Success ' + resp.config.data.file.name + 'uploaded. Response: ' + resp.data);
				$location.path('/people');
			}, function (resp) {
				console.log('Error status: ' + resp.status);
			}, function (evt) {
				var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
				console.log('progress: ' + progressPercentage + '% ' + evt.config.data.file.name);
			});

I'm sorry for boring you, but I don't know what I do.
I made this in a form submit...

**Comment by danialfarid** [comment]
`$scope.form.file` doesn't seem to be a file object. Make sure it is a file create a jsfiddle or post more of you code here.

**Comment by diegofc00** [comment]
<form class="form-horizontal" name="form" role="form" method="POST" ng-submit="save()">
<div class="form-group">
                            <label for="photo" class="col-md-4 control-label">Foto:</label>

                            <div class="col-md-6">
                                <div class="btn btn-info button" name="file"
                                    ngf-select 
                                    ng-model="file"
                                    ngf-pattern="'image/*'"
                                    accept="image/*"
                                    ngf-max-size="20MB"
                                    ngf-min-height="100"
                                    ngf-resize="{width: 100, height: 100}"
                                    >
                                    Selecione
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">Gravar</button>
                            </div>
                        </div>
                    </form>

**Comment by diegofc00** [comment]
<div class="btn btn-info button" name="file"
                                    ngf-select 
                                    ng-model="file"
                                    ngf-pattern="'image/*'"
                                    accept="image/*"
                                    ngf-max-size="20MB"
                                    ngf-min-height="100"
                                    ngf-resize="{width: 100, height: 100}"
                                    >
                                    Selecione
                                </div>

**Comment by danialfarid** [comment]
Your file model is called file so it is `$scope.file` not ` $scope.form.file`

**Comment by diegofc00** [comment]
I'm sorry, inside <form class="form-horizontal" name="form" role="form" method="POST" ng-submit="save()">

**Comment by danialfarid** [comment]
still the same your file model is $scope.file

**Comment by diegofc00** [comment]
I'm sorry to bother you with this. It's work!

Hug bro.

**Comment by kimbumbia** [comment]
Hello Danialfarid:
Hello :
I'm using your library to add data. When I create the data and add a file it works perfectly (by POST). But when updating an object (by PUT), it does not work. This is the problem: "Circular reference in config.data. Make sure specified data for Upload.upload () has no circular reference: $ promise [$ state] [value] [$ promise]". This is the code:

```
 <form enctype="multipart/form-data" name="userform">
 	<input name="user" ng-model="entity.login" required>
 	<div class="button" ngf-select="upload($file)" ng-model="file" 
 	name="file" ngf-pattern="'image/*'" ngf-accept="'image/*'" 
 	ngf-max-size="20MB" ngf-min-height="100" 
 	ngf-resize="{width: 100, height: 100}">
 	</div>
 	<button ng-click="updateUser()" type="submit">Save</button>
 </form>
```

```
$scope.entity = {
	login: null,
	icon: null
};

$scope.upload = function(file) {
	if(file){
		$scope.file = file
        $scope.entity.icono = file
    }
};

$scope.updateUser= function()
{
	Upload.upload({
		url: App.apiBaseUrl + 'usuarios/' + $scope.entity.id + '/',
		data: $scope.entity ,
		method : 'PUT',
	}).then(function (resp) {
		console.log('OK')
	}, function (resp) {

	}, function (evt) { });	
};
```

**Comment by kimbumbia** [comment]
Problem resolved : 
By PUT method Replace $scope.entity by object directly defined on data propierty
Example

```
Upload.upload({
		url: App.apiBaseUrl + 'usuarios/' + $scope.entity.id + '/',
		**data: {
login: $scope.entity.login,
icon:  $scope.entity.icono
},**
		method : 'PUT',
	}).then(function (resp) {
		console.log('OK')
	}, function (resp) {

	}, function (evt) { });	
```
