### ISSUE TITLE
File doesn't save image with the format

### ISSUE THREAD

**Issue by SarasArya** [danialfarid/ng-file-upload#1239]
When I use ng-file-upload, it save it in the web-server at the moment it hits the `connect-multiparty` object at the specified `upload Directory` . The issue it it just save the file with the a hashed name, but without specifying the format. For example like this `nlzt9LJWRrAZEO3ZteZUOgGc` instead of `nlzt9LJWRrAZEO3ZteZUOgGc.png` Now when I try to serve the file in the front end It downloads the file. Instead of displaying it in the browser.  

I believe either there is something wrong with the module or I am doing something incorrect. I feel the latter is of more possibility. In any case and would some one like to showcase some best practice while displaying the image in the frontend.

**Comment by danialfarid** [comment]
Should be backend issue. You can use `Upload.rename` if you wish to rename the file on the front end. You could try to ask it on SO.
