### ISSUE TITLE
ng-file-upload modifies the object name

### ISSUE THREAD

**Issue by deltreey** [danialfarid/ng-file-upload#1240]
using multer on the backend, I checked the wierdness going on and found that the actual file was renamed to `file[0]`.

I don't know if I'm doing something wonky, but I'm not trying to be fancy.

```javascript
Upload.upload({
        url: '/upload',
        data: { file: file }
});
```

I then actually dropped some debug lines in multer's code to see that the `file` object they receive in:

```javascript
function wrappedFileFilter (req, file, cb) {
  if ((filesLeft[file.fieldname] || 0) <= 0) {
    return cb(makeError('LIMIT_UNEXPECTED_FILE', file.fieldname))
  }
  filesLeft[file.fieldname] -= 1
  fileFilter(req, file, cb)
}
```

is named `file[0]` instead of `file`.

**Note: It's not an array.  The string of the name has brackets in it.**

**Comment by danialfarid** [comment]
file name is different from fieldname.

**Comment by danialfarid** [comment]
Your `file` object is probably an array of files not a single file. If you have ngf-multiple your model will be an array and it would be sent as `file[i]` as the fieldname.

**Comment by deltreey** [comment]
you are correct.  I meant fieldname.  I did not use ngf-multiple.  Here is the html (not ccce yet)

```html
<div ngf-drop="upload($files)" ngf-select="upload($files)" ng-model="files" class="drop-box" accept=".xlsx" ngf-drag-over-class="'dragover'" ngf-pattern="'*'">Drop an excel document here or click to upload</div>
```

**Comment by danialfarid** [comment]
So what do you see in the console if you have `console.log(file)` before uploading the `file`?

**Comment by deltreey** [comment]
`[{}]` as you can see here: http://jsfiddle.net/ubbf71zn/1/

**Comment by danialfarid** [comment]
So yea as I said it is an array. Use `ngf-select="upload($file)"` if you want a single file.

**Comment by deltreey** [comment]
is that documented somewhere?  Because I had no idea that there was a `$file` variable

**Comment by danialfarid** [comment]
Yes read the readme.
