### ISSUE TITLE
Abort not working using Upload.http method

### ISSUE THREAD

**Issue by vtkumaresan** [danialfarid/ng-file-upload#1244]
var upload = Upload.http(config).then(function (resp) {
...

}
$scope.cancel = function(){
upload.abort();
};

Can you pls give the solution?

**Comment by vtkumaresan** [comment]
Edit:
Tested in Mac Chrome Browser

**Comment by danialfarid** [comment]
Since Upload.http()  sends all the content inside the request body abort may not work.

**Comment by danialfarid** [comment]
You can try `Upload.upload(...).xhr(function(xhr) {xhr})

**Comment by vtkumaresan** [comment]
version: 10.1.14
Upload.upload(...).xhr(function(xhr) {
$scope.xhr = xhr; // this line was not triggered
});

**Comment by vtkumaresan** [comment]
we are uploading file as binary. can you provide an abort solution for Upload.http?

**Comment by danialfarid** [comment]
Actually abort is working on the demo page for http. Follow the demo page code, calling abort should abort the request.

**Comment by danialfarid** [comment]
If you still have problem create a jsfiddle with steps to reproduce.
