### ISSUE TITLE
ngf-src not working properly

### ISSUE THREAD

**Issue by mickeychu** [danialfarid/ng-file-upload#1245]
I want to display the image preview or the user's avatar but the ngf-src is not working as I expected:

<**img id="avatar" class="ui centered image" ngf-src="avatar || 'http://localhost:8000/img/user_avatar/{{vm.detail.id}}.jpg'"**>

somehow I can not get the picture from the server.
It showed on the HTML like this:

<**img src="http://localhost:8000/img/user_avatar/.jpg" id="avatar" class="ui centered image" ngf-src="avatar || 'http://localhost:8000/img/user_avatar/5.jpg'"**>

Could anyone help pleaseeee!

**Comment by danialfarid** [comment]
`{{vm.detail.id}}` is null.

**Comment by mickeychu** [comment]
No, I don't think {{vm.detail.id}} is null cause when I tested it with **ng-src**  it still display the picture normally and you can see on the html that: <img src="http://localhost:8000/img/user_avatar/.jpg" id="avatar" class="ui centered image" ngf-src="avatar || '**http://localhost:8000/img/user_avatar/5.jpg**'">

**Comment by danialfarid** [comment]
add a scope variable for the url instead of double curly bracket syntax. `ngf-src="avatar || avatarUr"`

**Comment by mickeychu** [comment]
Thank you, it worked!!!!
