### ISSUE TITLE
Problem with the way that object data is sent in new version (11.0.1)

### ISSUE THREAD

**Issue by Blarm1959** [danialfarid/ng-file-upload#1248]
Hi Danial,

Thanks for providing this fantastic library.

The way that object form-data is being sent has changed when I upgraded from version 6.0.4 to 11.01.
How can I continue to send in the format required by the API I am using.

Here is some example code and also the Network Request Payload from Chrome Dev Tools:
var data = {
    Document: {
        DocumentObject: 'Document',
        DocumentObjectID: 1278,
        DocumentType: 'SA'
    }
};

var uploadConfig = {
    file: file,
    url: url,
    fields: data
}

return Upload.upload(uploadConfig)
    .progress(progress)
    .then(success, fail);

In Version 6.0.4 the Document object was sent as an object in the correct format  as JSON.stringify was used:

------WebKitFormBoundary4Uy4unOEb7mqk3kd
Content-Disposition: form-data; name="Document"

**{"DocumentObject":"Document","DocumentObjectID":1278,"DocumentType":"SA"}**
------WebKitFormBoundary4Uy4unOEb7mqk3kd

However in Version 11.0.1 the Document object fields had been split out into 3 separate form-data pieces which is not valid for the API: 

------WebKitFormBoundaryRj1JxPgkLmw1AMAl
Content-Disposition: form-data; name="Document[DocumentObject]"

Document
------WebKitFormBoundaryRj1JxPgkLmw1AMAl
Content-Disposition: form-data; name="Document[DocumentObjectID]"

1278
------WebKitFormBoundaryRj1JxPgkLmw1AMAl
Content-Disposition: form-data; name="Document[DocumentType]"

SA
------WebKitFormBoundaryRj1JxPgkLmw1AMAl

I have also tried using this method (as per the read.me) bu the results are still incorrect.
var uploadConfig = {
    url: url,
    data: { file: file, Document: data.Document }
}

------WebKitFormBoundaryLVfA4D9pHzy6ccHQ
Content-Disposition: form-data; name="Document[DocumentObject]"

Document
------WebKitFormBoundaryLVfA4D9pHzy6ccHQ
Content-Disposition: form-data; name="Document[DocumentObjectID]"

1278
------WebKitFormBoundaryLVfA4D9pHzy6ccHQ
Content-Disposition: form-data; name="Document[DocumentType]"

SA
------WebKitFormBoundaryLVfA4D9pHzy6ccHQ--

Can you please advise how I can send the data in the correct format (JSON.stringify) which has previously worked.

Thanks,

Bill

**Comment by danialfarid** [comment]
Read the release notes at the top of readme file.
