### ISSUE TITLE
Hidden input element is not being disabled

### ISSUE THREAD

**Issue by smilasek** [danialfarid/ng-file-upload#1249]
When using `ng-disabled` and `ngf-select-disabled`, the `disabled` attribute is not being added to the hidden `input` element, so malicious users could still access and use the element.

**Comment by hellfrom** [comment]
I'd like to add to add few words to strange behaviour of disabling.
If I have `ng-disabled = "false"` or `ngf-select-disabled = "false"` or `ngf-drop-disabled = "false"`
at first. Then when I change this condition to true element doesn't work at all. Both select and drop mode. But if it was enabled during initialization everything works as expected. The same situation if directive was hidden with ng-hide during initialization

**Comment by danialfarid** [comment]
Can you create a jsfiddle? The demo page has ng-disabled and it is working properly by the checkbox.

**Comment by smilasek** [comment]
Here is jsfiddle: http://jsfiddle.net/uekxfs3r/. 
Button is disabled, but underneath input element is still being generated.
![screen](https://cloud.githubusercontent.com/assets/743696/12215583/77acb678-b6c3-11e5-9481-ac33ada762e6.PNG)

Is it intended action?

**Comment by danialfarid** [comment]
Yea that's an invisible element so it doesn't matter.

**Comment by danialfarid** [comment]
Malicious user can remove the disabled attribute of any element or add any element and use it.
