### ISSUE TITLE
Image Width and Height Validation Error

### ISSUE THREAD

**Issue by vikashkrjha** [danialfarid/ng-file-upload#1250]
When I select the Correct image still getting the Error Message on chrome. Same code is working fine on Firefox on the same system.

Works fine on other Windows on both chrome and firefox.

Following are the details : 
Os - Windows 7
Chrome Version - 47.0.2526.106 m (Not Working)
Firefox Version - 40.0.3 (Working)
<code>
Input Field -
input type="file" class="upload" name="appIconInput" accept="image/*"
                               ngf-select="uploadAssetImg(appIcon, 'IOS', 'app_icon_url')" ng-model="appIcon"
                               ngf-max-size="2MB" ngf-min-width="1024" ngf-max-width="1024" ngf-min-height="1024" ngf-max-height="1024">

Error Msg - 
i class="size_error" ng-show="AppVersion.appIconInput.$error.minWidth || AppVersion.appIconInput.$error.maxWidth  || AppVersion.appIconInput.$error.minHeight  || AppVersion.appIconInput.$error.maxHeight">
                              Image Resolution Must Be : 1024 W * 1024 H.
                           </i>
</code>

![capture](https://cloud.githubusercontent.com/assets/2944846/12201889/a708307c-b64c-11e5-86f0-c0e40bd2a6c1.PNG)

![1024 1](https://cloud.githubusercontent.com/assets/2944846/12201757/1ae5fe30-b64c-11e5-9247-add9286cdcd4.png)

Any help will be appreciated.
Thanks,

**Comment by danialfarid** [comment]
Could be a float comparison issue. Make the max-width height 1025 insteaed of 1024 and see if it fixes it.
