### ISSUE TITLE
Click on <a> tag doesn't work.

### ISSUE THREAD

**Issue by vilmysj** [danialfarid/ng-file-upload#1253]
I am using Angular 1.4.8 with full jQuery 1.11.3 so `.bind` method differs from default Angular jqLite.

In jQuery: [source](http://api.jquery.com/bind/)
> Returning false from a handler is equivalent to calling both .preventDefault() and .stopPropagation() on the event object.  

I have `ng-file-upload` directive which wrapping some content where are few links and if I add `ngf-select` and `ngf-select-disabled` click on these link doesn't work.

[jsfiddle with jQuery + Angular](https://jsfiddle.net/zxdec3np/) click on `link` doesn't work
[jsfiddle with Angular](https://jsfiddle.net/abk7zdar/) click on `link` works

**Comment by danialfarid** [comment]
Fixed at 11.1.0
