### ISSUE TITLE
How to mock upload callback.

### ISSUE THREAD

**Issue by nileshpore** [danialfarid/ng-file-upload#1256]
I am trying to write Jasmine Unit Test for upload file function.
I am getting following error while mocking upload call. I am using version @version 5.0.9.
_this.$upload.upload(...).success is not a function.

Any Idea how to deal with this? If yes please provide example.

**Comment by danialfarid** [comment]
It is called Upload not $upload.

**Comment by nileshpore** [comment]
Yes, that's right. I am injecting "Upload"  and using it in variable "$upload". I want to write Jasmine test to cover code inside success method. Please see below example.

export class TestCtrl{
 public static $inject = ["Upload"]

 constructor(public $upload: any){
 }

 this.$upload.upload({
                url: url,
                method: "POST",
                file: fileArray,
                fileName: fileNames,
                data: JSON.stringify(me.sectionListToUpdate)
            }).success(function (data, status, headers, config) {   

	//I want to test code in success method.
	})
}

**Comment by danialfarid** [comment]
Ask on SO since this is just a question.
