### ISSUE TITLE
What happened to "fileFormDataName"?

### ISSUE THREAD

**Issue by Vortilion** [danialfarid/ng-file-upload#1257]
Hi,

in a previous version i could change the post name of the file field, but now it always sets the post name to "file". I noticed that you changed it with version 7.2.0, but I don't understand how exactly I have to use this key-Map now to change "file" to "photo" for example.

Also I used ng-file-changed before to upload a file directly after selection. With the new parameter name "ngf-change" this doesn't work anymore, the function is not being called anymore.

And last but not least: How can I get the dimensions of an uploaded image with my version of your plugin (< 7.2.0)?

**Comment by danialfarid** [comment]
Upgrade to latest version and read the docs. Specially for `data`
'data: {photo: file}`
'ngf-change' will still work when you select the file.

**Comment by Vortilion** [comment]
I did migrate to the latest version, but it didn't work.... And I don't understand how to reference the file if I bind it to a scope model (via ng-model="messageHistory.commentPhoto"). Do I have to pass it to a scope function like

ngf-change="uploadPhoto($file)"

or rather

ngf-change="uploadPhoto(messageHistory.commentPhoto)"

?

Both didn't call the function uploadPhoto() at all. Don't know why.

**Comment by danialfarid** [comment]
First one is correct If you have multiple files you should have $files.
Create a jsfiddle. There are jsfiddle sample on the readme page you can follow those.
