### ISSUE TITLE
creating custom controls with components

### ISSUE THREAD

**Issue by mmasoud2010** [danialfarid/ng-file-upload#1258]
hi 
does any one has an idea about creating a component and using it like an input?
lets say i have this component:
import { Input, Component, View} from 'angular2/core';

@Component({
    selector: 'text-input',
    template:
    `
        <label>{{label}}</label>
        <input name="value" type="text" [(ngModel)]="value"/>
    `,
  
    inputs: ['label', 'value']
})

export class TextInputComponent {
    public label: string;
    public value: string;
}

and then i want to use this component in another component as a text input control like this

@Component({
    selector: 'my-app',
    template:
    `
        <text-input [label]="myLabel" [(value)]="myValue"/>
    `,
   
})

export class MyAppComponent
{
...... etc
}

now should the two way binding work on myValue property from the text-input component,
because it doesn't for me,

is there a proper way to do this

Please Help

Thanks

**Comment by danialfarid** [comment]
This is not related to file upload.
