### ISSUE TITLE
the scope value is not getting cleared

### ISSUE THREAD

**Issue by snehaRCanvera** [danialfarid/ng-file-upload#1260]
Hi I have an issue where $scope.picFile = ' ' is a ng-model object. In my html I have 

![fileupload](https://cloud.githubusercontent.com/assets/15225103/12263331/2fa018d2-b954-11e5-83ad-a69e3635a96a.PNG)

Here the scope variable $scope.picFile returns an array if ngf-keep is set to true.  I have a scenario where I am supposed to upload images one at a time to the server and hence I am using the above approach.

The problem I seem to face is I am not able to clear the $scope.picFile in reset. It still shows the array. I am using version 11.0.0. Could you please tell me what I am doing wrong?

**Comment by danialfarid** [comment]
How do you clear it? Create a jsfiddle from the samples on the readme page.

**Comment by snehaRCanvera** [comment]
http://jsfiddle.net/maqbzv15/654/ Please use this as the reference.

**Comment by danialfarid** [comment]
So what the issue is in that jsfiddle? steps to reproduce?

**Comment by snehaRCanvera** [comment]
I am surprised that its working in that fiddle. The problem I was facing was I have a ng-model say $scope.picFile = ''. I set the value of ngf-keep = true. Loop over the picFile to see the thumbNails of different images. While resetting the ng-model to null seemed to do nothing in my case.

**Comment by danialfarid** [comment]
Modify jsfiddle to reproduce your case.
