### ISSUE TITLE
Unable to click Upload when using a touchscreen hybrid device

### ISSUE THREAD

**Issue by mbrewerton** [danialfarid/ng-file-upload#1262]
This issue was supposed to have been addressed in a previous build, but we're still having problems with every version.

When using a laptop/device with a touchscreen, clicking on the Upload button just does nothing in Chrome, but works fine in IE. If I use the touchscreen in Chrome the button works fine. This isn't really fit for purpose but at the same time seems to be the only library for Angular upload that anyone seems to use. An update on this issue or some guidance would be greatly appreciated!

Thanks in advance.

**Comment by danialfarid** [comment]
What issue are you referring to?
And what the issue is? Is it working in Chrome or not?

**Comment by mbrewerton** [comment]
Hi,

I realise that I was a little bit vague on some of the details.

When using Chrome:
- Touchscreen works fine

**Comment by danialfarid** [comment]
What device? os version? chrome version?

**Comment by mbrewerton** [comment]
The issue happens on any device with a touchscreen as well as mouse capability, eg: HP Envy JS151SA laptop, and any other laptop we've tested. Both running Windows 8.1, latest Chrome version 47

**Comment by danialfarid** [comment]
First could you make sure it is broken for both `<input type="file"  ngf-select...>` and `<div ngf-select...>`?

Then can you put a breakpoint here: https://github.com/danialfarid/ng-file-upload/blob/master/dist/ng-file-upload.js#L702 and see if it would be hit when you clicking on it and how far the execution will go in that function?

**Comment by mbrewerton** [comment]
Hi, sorry for the late reply, I'll try that and then let you know how it works.

**Comment by mbrewerton** [comment]
Upgrading again seemed to work wonders! The issue has been resolved, thank you.
