### ISSUE TITLE
popup opens twice in version 10.1.8

### ISSUE THREAD

**Issue by steve-mcqs** [danialfarid/ng-file-upload#1265]
Popup opens twice but image is uploaded after first popup closes.

html:

    <img ng-src="{{profileImage}}" class="profile-photo hand-mouseover"  style="margin: 10px"
                         ngf-select="vm.upload($file)"
                         accept="image/*" ng-multiple="false"
                         tooltips tooltip-title="Upload Profile Picture" tooltip-try="false" tooltip-side="right" tooltip-delay="1000" tooltip-lazy="false">

JS:

      function upload(file) {
            console.log("file to be uploaded ===== " + file)
            Upload.upload({
                url: '/api/profile/profile',
                data: {file: file}
            }).then(function (resp) {
                //console.log('Success ' + resp.config.data.file.name + 'uploaded. Response: ' + JSON.stringify(resp.data));
                //debugger;
            }, function (resp) {
                //console.log('Error status: ' + resp.status);
                //debugger;
            }, function (evt) {
                var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
                console.log('progress: ' + progressPercentage + '% ' + evt.config.data.file.name);
            });
        }

**Comment by steve-mcqs** [comment]
It seems to be 
 
    ng-src={{profileImage}}

That is causing the issue. Could the change of "profileImage" trigger another upload?

**Comment by danialfarid** [comment]
Could you create a jsfiddle? That's unlikely to cause this issue.
