### ISSUE TITLE
option for confirm about onunload

### ISSUE THREAD

**Issue by Hirbod** [danialfarid/ng-file-upload#1266]
Hi there,

could you please provide an optional method for setting an confirm message when user tries to leave the page while the upload is still in progress?

I would like to have something like ngf-confirm-on-leave="bool" (default false) and ngf-confirm-text="My Text/{{'STRING' | translate}}"

Would something like this be possible? I dont want to register a confirm on every upload by myself (my app has more then 20 different upload scenarios, doing this for every single one is really painful)

Thanks!

**Comment by danialfarid** [comment]
Since 11.1.0 you can use `Upload.isUploadInProgress()` to see if there is an active upload in progress and prompt user before closing.

**Comment by Hirbod** [comment]
Thanks. Isn't it possible to provide a UploadProvider (for .run() or a global .config() variable to enable this app wide? It's a real pain to implement the check for 20 different scenarios

**Comment by danialfarid** [comment]
By calling isUploadInProgress() you can have a generic message if the upload is in progress. You won't need 20 different scenarios.
Generally the upload could be called from any js code and may not be related to any element or directive, for example you can add all files from all inputs to one array and upload that one.

**Comment by Hirbod** [comment]
Ok, so I could register a window.onunload and check if isUploadInProgress and prompt a confirm. That's good, thought that it is necessary to pass Upload as directive to use it (but I could swear I could access it without passing to the controller). Will try that later...
