### ISSUE TITLE
Change file key value?

### ISSUE THREAD

**Issue by deep-c** [danialfarid/ng-file-upload#1267]
Hi,

Im having a little trouble getting the following data to have the correct key structure that im looking for.

This is what my Upload call looks like.

            Upload.upload(
                url: "#{@API_URL}"
                method: 'POST'
                data: { file: files, data: Upload.json(data) }
            )

data looks like this:

    {
    field4171: "dsgsdgds"
    field5837: "rgba(204,57,57,1)"
    field6970: Object
    field8919: "asfas@sadfg.com"
    field9611: Array[0]
    field9613: Array[0]
    form: 1
    }

and the files object i am passing in is this:

    {
    field9611: Array[3]
    0: File
    1: File
    2: File
    field9613: Array[2]
    0: File
    1: File
    }

This is what my request.POST looks like:

     <QueryDict: {u'data': [u'{"form":1,"data":{"field6970":{"1":true,"2":true},"field4171":"asddsgs","field8919":"asdg@sdgj.com","field9611":[],"field9613":[],"field5837":"rgba(166,60,60,1)"}}']}>

The issue is im getting the following files structure serverside.

    <MultiValueDict: {u'file[field9611][1]': [<TemporaryUploadedFile: arnold-schwarzenegger-the-    terminator-150x150 copy 4.jpg (image/jpeg)>], u'file[field9613][1]': [<TemporaryUploadedFile: ff_x10_001 copy 4.JPG (image/jpeg)>], u'file[field9611][0]': [<TemporaryUploadedFile: arnold-schwarzenegger-the-terminator-150x150 copy 3.jpg (image/jpeg)>], u'file[field9613][0]': [<TemporaryUploadedFile: ff_x10_001 copy 2.JPG (image/jpeg)>]}>

Instead I need a structure where the i can grab files based on a field -> i.e field9611. So i need files to have the same key when uploaded i.e 'field9611' : file1, 'field9611' : file2, 'field9611' : file3, 'field9613': file1. I was using version 1.x which provided this structure however i needed to update to this latest version for other reasons and need to attempt to get the same result as i dont think django understands these nested keys and i need to know which file corresponds to which field in data. 

Any help would be appreciated. Thanks

**Comment by danialfarid** [comment]
`data: {'field9611' : file1, 'field9611' : file2, 'field9611' : file3, 'field9613': file1}`
