### ISSUE TITLE
Update/fix the doc

### ISSUE THREAD

**Issue by MathieuAA** [danialfarid/ng-file-upload#1268]
Hi. According to what the readme says, and the various available samples, what's the correct way to upload a file alongside some data?

I see two different versions, the first (from the readme): 

    data: {key: file, otherInfo: uploadInfo}

with `uploadInfo` being an object, and (from the Spring sample):

    fields: {'username': 'zouroto'}, // additional data to send
    file: file

Thanks.

**Comment by MathieuAA** [comment]
Update: got it working with:

    file: $scope....
    date: { some keys/values }

Might be a good idea to update that doc =)

**Comment by danialfarid** [comment]
You better use 
`data: {file: $scope...., some keys/values}`
`file` option might become deprecated at some point and is there just for the backward compatibility.

**Comment by MathieuAA** [comment]
Ok! thanks.
