### ISSUE TITLE
ngf-invalid-pattern and ngf-invalid-maxsize

### ISSUE THREAD

**Issue by bhuranideepak82** [danialfarid/ng-file-upload#1269]
Hi,

We need to show invalid files based on invalid pattern and invalid maxsize.

ng-file-upload adds ng-invalid-pattern and ng-invalid-maxsize on form to make form and button invalid (which is correct)

How do i remove ng-invalid-pattern and ng-invalid-maxsize from button and form to make form pristine as we are not posting those invalid files to server.

**Comment by danialfarid** [comment]
Set the model value to the correct files.
