### ISSUE TITLE
Failed to validate minWidth if .png

### ISSUE THREAD

**Issue by ssuhat** [danialfarid/ng-file-upload#1270]
Hi, Love this package. I just found an issue (I think but maybe i'm wrong), I've put validation min-width and min-height like this:

````
<input type="file" ngf-select name="cover" id="cover" required accept="image/*" ng-model="upload.coverSource" ngf-validate="{size: {max: '512KB'}, width: {min: 800}, height: {min: 450}, pattern: '.jpg, .png'}">
````

It's working perfectly if I select my image .jpg, but if I select .png file it cannot validate the pattern and the minimum width and height.

I've tried show the error like this:

````
<div class="alert alert-danger alert-dismissable"  ng-show="form.cover.$error.maxSize || form.cover.$error.minWidth || form.cover.$error.minHeight || form.cover.$error.pattern">
                    <ul>
                        <li ng-show="form.cover.$error.maxSize">File too large, maximum file can be upload is 512KB</li>
                        <li ng-show="form.cover.$error.minWidth || form.cover.$error.minHeight">
                            File minimum width is 800px and minimum height is 450px.
                        </li>
                        <li ng-show="form.cover.$error.pattern">
                            File unsupported. Supported file is .jpg
                        </li>
                    </ul>
                </div>
````

Am i making mistake?

THanks!

**Comment by danialfarid** [comment]
So what happens when you select the png file? Could you create a jsfiddle?

**Comment by ssuhat** [comment]
My submit button is still invalid (looks like validation is working), but it not showing any error to my <div>

**Comment by ssuhat** [comment]
Okay, i found the error is at pattern,  pattern: '.jpg' I add .png but using space. I delete the space and it working perfectly.
