### ISSUE TITLE
Using abort

### ISSUE THREAD

**Issue by prashanthsun9** [danialfarid/ng-file-upload#1271]
first of all thank you for creating this project, it is awesome, I have used it in my project, and it works flawlessly. Now I am trying to integrate aborting a list of files that are getting uploaded, I am really not sure how to do that, do you have any sample projects where you only do a multiple file upload and abort all the file upload at once? if you have can you give me the link to it so I can implement in my project.

Or if you can let me know how can I abort the upload by viewing the my source code, please do let me know? below is the code.

 $scope.uploadFiles = function(files) {

        if(files != undefined){
            $scope.currentFileUploadList = files;
            $scope.$apply();
        }
        angular.forEach(files, function(file, key) {
            if(isSpecialChar(file.name)){
                //$scope.currentFileUploadList[key].status = false;
                //$scope.$apply();
                file.upload = Upload.upload({
                    url: $scope.BASE_FOLDER+'/sync/file/upload',
                    fields: {csrf_token: $('.csrf_token').html(), path: 'ParaBlu'},
                    file: file
                });

                file.upload.then(function (response) {
                    $timeout(function () {
                        file.result = response.data;
                        if(response.data.result == 'success'){
                            $('.status').hide();
                            toastr.success(response.data.file.fileName+' has been uploaded successfully', 'Successfully!!!', {allowHtml: true});
                            $scope.currentFileUploadList.forEach(function(value, key){
                                if(value.name.toString() == response.data.file.fileName.toString()){
                                    $scope.currentFileUploadList.splice(key, 1);
                                }
                            });
                            if((files.length) == key){
                                $('#uploadFiles').modal('hide');
                            }
                        }else{
                            toastr.error(file.name, response.data.msg, 'Fail!!!', {allowHtml: true});
                        }
                    });
                }, function (response) {
                    if (response.status > 0)
                        $scope.errorMsg = response.status + ': ' + response.data;
                });

                file.upload.progress(function (evt) {
                    file.progress = Math.min(100, parseInt(100.0 *
                        evt.loaded / evt.total));
                });
            }else{
                $scope.currentFileUploadList.forEach(function(value, key){
                    if(value.name.toString() == file.name.toString()){
                        $scope.currentFileUploadList.splice(key, 1);
                    }
                });
                toastr.error('Special characters like ( * \ | : " < > ? / ) are not allowed, in a file name.', 'Fail!!!', {allowHtml: true});
            }
        });
    };

**Comment by danialfarid** [comment]
Call `file.upload.abort()` on every file inside `$scope.currentFileUploadList` array if you want to cancel them all.

**Comment by prashanthsun9** [comment]
I did not understand, I have a cancel button, and onClick of that button I need to call a function which cancels everything, another thing is, I have removed file.upload.then() and file.upload.progress() both functions and I was calling only file.upload.abort(), still files are getting uploaded, not sure why?

**Comment by danialfarid** [comment]
Create a jsfiddle or post on Stackoverflow

**Comment by prashanthsun9** [comment]
My Code does not work in jsfiddle, I have a bit of a logic in php where I wont move the uploaded file, I will read it and stream to an api through curl, so is there any jsfiddle that you have where you have an upload button and a cancel button, upload btn, uploads all files and cancel btn, cancels all the current uploading files.

Here is the StackOverFlow issue link : http://stackoverflow.com/questions/34918943/cancel-angular-file-upload?noredirect=1#comment57571986_34918943
