### ISSUE TITLE
size validation fails even after resize

### ISSUE THREAD

**Issue by dk8996** [danialfarid/ng-file-upload#1274]
It looks like file size validation is done before resizing but it seems like it should be done after.

**Comment by danialfarid** [comment]
When you resize the image you kind of have an idea what size it would be but when the user selects it, it could be of any size so it make sense to validate it before the resize.

**Comment by dk8996** [comment]
Expect in the case when the user tries to upload a video file that isn't resized.  Moreover, I just think its strange that if you have resize and size validation then the validation will always fail even if the resulting resize file is smaller.

**Comment by danialfarid** [comment]
Resize is only for photos.
I might add an option to the next version to validate after resize.

**Comment by danialfarid** [comment]
Fixed at 11.2.0, added option `ngf-validate-after-resize="boolean"`
