### ISSUE TITLE
`TypeError: Illegal invocation` problem

### ISSUE THREAD

**Issue by melon** [danialfarid/ng-file-upload#1275]
Version: 11.1.1
Browser: Chrome/47.0.2526.106

If I write code like this, browser would throw an error `TypeError: Illegal invocation`
```
Upload.upload({
    url: 'xxx',
    data: {
      file: $scope.file  
    },
})
```
but when do this in another way
```
Upload.upload({
    url: 'xxx',
    data: {
        
    },
    file: $scope.file
})
```
the problem solved
I guess there should be something wrong with processing File object

**Comment by danialfarid** [comment]
What version?

**Comment by targetoyes** [comment]
I have the same problem in chrome：49.0.2623.87,but in /*! 12.0.4 */.
The function module is ok,but in console always get this error message:
`TypeError: Illegal invocation`
Is that cause by angularjs file（mine is  v1.2.7）?if So, which version of the angularjs do you use?
