### ISSUE TITLE
ngf-keep = true | 'distinct' upload all files again!

### ISSUE THREAD

**Issue by unrelaxby** [danialfarid/ng-file-upload#1276]
ngf-keep = true | 'distinct' upload all files again! Google Chrome 47

**Comment by danialfarid** [comment]
That's the expected behaviour it keeps all the files.

**Comment by dbelieves** [comment]
is there any workaround to upload only files that are new and prevent previously uploaded files from being uploaded

**Comment by danialfarid** [comment]
Just keep a flag in the file to know which ones are being uploaded so you don't re-upload them. There is a feature for it in version 2 which will be released later for angular2 and might be ported to angular1 too.
