### ISSUE TITLE
When image is rotated, exif orientation is not updated.

### ISSUE THREAD

**Issue by jeremyk** [danialfarid/ng-file-upload#1277]
Currently I do rotation on the server. I also manually generate and rotate a thumbnail as a preview. I am looking into doing the rotation in javascript but when I turn it on, the server double rotates it and I presume that is because the orientation in the exif hasn't bee reset to 1 after the image is rotated. I could fix it by just not having the server rotate the image but I don't like the idea of having a mismatched exif-orientation/image-orientation as the file will be displayed incorrectly on other devices. Let me know if I am just misunderstanding something. Thanks!

**Comment by CasherWest** [comment]
You could turn off server side rotation if a specific parmater is send. Something like image_rotation=false. It is a fast solution for the problem.

**Comment by danialfarid** [comment]
I am working on a fix. Should be released soon in couple days.

**Comment by danialfarid** [comment]
Fixed at 11.2.0

**Comment by ruslan5t** [comment]
This fix does not work for drug and drop.

**Comment by danialfarid** [comment]
It should work for everything. Create a separate issue with jsfiddle and steps to reproduce if that's the case.
