### ISSUE TITLE
Failed to load resource: the server responded with a status of 415

### ISSUE THREAD

**Issue by raysefo** [danialfarid/ng-file-upload#1278]
I am trying to send an image with the code below but getting this error. How can I fix this?

`$scope.upload = function (dataUrl) {

        Upload.upload({
           
            url: 'http://192.168.1.20/wcf/OCRService.svc',
            data: {
                file: Upload.dataUrltoBlob(dataUrl)

            },
        }).then(function (response) {
            $timeout(function () {
                $scope.result = response.data;
                console.log(response.data);
                alert(response.data);
            });
        }, function (response) {
            if (response.status > 0) $scope.errorMsg = response.status
				+ ': ' + response.data;
            alert(response.status);
        });

    }` 
Failed to load resource: the server responded with a status of 415 (Cannot process the message because the content type 'multipart/form-data; boundary=----WebKitFormBoundaryPUTlLsy2dLriRyDm' was not the expected type 'multipart/related; type="application/xop+xml"'.)
OCRService.svc (0,0)

Best Regards.

**Comment by danialfarid** [comment]
Seems like your server does not accept multipart/form-data requests.
Post it on SO.
