### ISSUE TITLE
Is it possible to upload to parse.com?

### ISSUE THREAD

**Issue by bagusflyer** [danialfarid/ng-file-upload#1279]
Does anybody know parse.com? Is it possible to use ng-file-upload to upload image file to parse.com? Thanks

**Comment by danialfarid** [comment]
Yea you should be able to upload using `Upload.http()` see the sample on the doc.
You need to set these headers:
```
  -H "X-Parse-Application-Id: ${APPLICATION_ID}" 
  -H "X-Parse-REST-API-Key: ${REST_API_KEY}"     
  -H "Content-Type: text/plain" 
```

**Comment by bagusflyer** [comment]
OK, I'll have a try, thanks.
