### ISSUE TITLE
$ngfDataUrl missing 

### ISSUE THREAD

**Issue by Sellitecture** [danialfarid/ng-file-upload#1281]
What am I doing wrong here?   The binary is not in the file object

view:

                            <div id="oyeChooseButton" class="btn btn-primary" ngf-select="reg.OyeAddSubmission()" ng-model="reg.file" ng-disabled="!reg.oyeFirstName || !reg.oyeState" name="reg.file" ngf-pattern="'image/*'"
                                ngf-accept="'image/*'"
                                ngf-keep="distinct"
                                ngf-fix-orientation="true"
                                ngf-resize="{width:1000, height:1000, quality:1,centerCrop: true}"
                                ngf-resize-if="$width<>1000 || $height<>1000"
                                ngf-validate="{size: {min: 10, max: '1MB'}, width: {min: 500, max:2800}, height: {min: 500, max: 2800} }">
                                Choose<i class="fa fa-camera"></i>
                            </div>

controller

    vm.OyeAddSubmission = function () {
        vm.oyeObject = {
            blob: {},
            firstName: null,
            state:null
        }
        var currentOyeSubmission = angular.copy(vm.oyeObject);
            currentOyeSubmission.firstName = vm.oyeFirstName;
            currentOyeSubmission.state = vm.oyeState;
            currentOyeSubmission.blob = vm.file;

        $rootScope.registration.oyeSubmissions.push(currentOyeSubmission);
        updateTotals();
        vm.registration.oyeSubmissions = $rootScope.registration.oyeSubmissions;
        vm.oyeFirstName = null;
        vm.oyeState = null;
    };

when i select the image the file  object looks like this:

{"$ngfName":"bill.jpg"}

Any idea where the $ngDataUrl is?

**Comment by danialfarid** [comment]
Why do you need `$ngDataUrl`? Those are reserved for internal use and could be removed later.

**Comment by Sellitecture** [comment]
There is no binary in the file object which is going to be uploaded plus  I
can preview the image with ngfDataUrl

**Comment by danialfarid** [comment]
The binary is just not shown in the console.log but it is there. You can use `ngf-src` to preview the image.

**Comment by Sellitecture** [comment]
Can I do a delayed upload.  For example have them choose the files but not
upload until after payment processing.  How would I do that

**Comment by danialfarid** [comment]
See the first jsfiddle sample
