### ISSUE TITLE
invalid ngf-pattern silently fails with angular 1.4.8

### ISSUE THREAD

**Issue by redwyre** [danialfarid/ng-file-upload#1282]
I'm guessing some parsing has been made to be a bit more strict because I had an error in my ngf-pattern

> ngf-pattern="'image/*"

Note the missing quote. This worked fine previously but now silently fails, it seems angular is throwing an exception but it is getting ignored.

**Comment by danialfarid** [comment]
It would actually use the "image/*" string as pattern if you don't put quotes.

**Comment by redwyre** [comment]
It doesn't work without them: "[$parse:syntax] http://errors.angularjs.org/1.4.8/$parse/syntax?p0=*&p1=not%20a%20primary%20expression&p2=7&p3=image%2F*&p4=*"

Also, ngf-max-size="1MB" needs to be quoted as well
https://docs.angularjs.org/error/$parse/syntax?p0=MB&p1=is%20an%20unexpected%20token&p2=2&p3=1MB&p4=MB

Can you re-throw these expections?

**Comment by danialfarid** [comment]
It does work, try it on the jsfiddle samples. The catch is there to handle those cases.
