### ISSUE TITLE
not supporting korean language in case of using ng-file-upload service

### ISSUE THREAD

**Issue by raghala** [danialfarid/ng-file-upload#1285]
Hi Danial,

I am using your service to upload a image, while sending data i am giving a Username in korean language like (안녕), but it is converting into some double byte characters.

here is the link to test http://embed.plnkr.co/mTyI676rSKh8WnjJoDQ0/ 

In the place of username give 안녕. 

Please help me!!!!!!!!!!!

**Comment by danialfarid** [comment]
@raghala  That's just the server response. if you see the network tab you will see that the data is being sent correctly
