### ISSUE TITLE
IE10,11,Edge won't pass the formdata besides "file"

### ISSUE THREAD

**Issue by codingfishman** [danialfarid/ng-file-upload#1286]
Maybe this is the only case for me, but I haven't find any related issues referring to this.

I want to pass some authentication data together with `file` in the `data` block, as this:
```
file.upload = Upload.upload({
          url: '/api/file',
          data: {
            'file': file,
            'token': 'thetoken'
          }
        })

```
This works fine in Chrome and Safari, but in IE the `token` will not be passed in the request. I checked the request body, only `file` is there, the `token` is dropped.

I did some debugging with the `upload` function, and saw the parameter `token` was added to the formdata by `formdata.append()`, but in the final request it was lost. This happens in IE10, IE11 and Edge.

**Comment by danialfarid** [comment]
How do you know it is lost in the final request?
Add some screenshots or create a jsfiddle.

**Comment by codingfishman** [comment]
Sorry @danialfarid , my mistake.  I checked the `body` panel in IE developer tool, and there was only "form-data:file", no `token` and the API returned error code so I thought this is the root cause.

But when I was about to try a new way I realized the URL of the API was wrong. So I changed it to the correct one and the error gone.

Thanks for your help!
