### ISSUE TITLE
Removing files with ngf-keep and ngf-mutliple

### ISSUE THREAD

**Issue by lpoulter** [danialfarid/ng-file-upload#1287]
I remove files from util.files by setting to null. However they all return with the new file added when I select a new file.

             <button type="file"
                        ngf-select
                        ng-model="util.files"
                        name="file"
                        ngf-multiple="true"
                        ngf-keep="true"
                        >CHOOSE FILE
                </button>

**Comment by lpoulter** [comment]
<button type="file" ng-click='util.files = null'
ng-show="util.files">
REMOVE ALL
</button>

**Comment by danialfarid** [comment]
Set it to an empty array if you want to remove previous files.
