### ISSUE TITLE
Aborting an upload error

### ISSUE THREAD

**Issue by bgold0** [danialfarid/ng-file-upload#1288]
When I try to abort the upload, the abort works, but I keep getting the following error when I try both of the following:

    for (var i = 0; i < $scope.files.length; i++) $scope.uploadArray[i].abort();
    for (var i = 0; i < $scope.uploadArray.length; i++) $scope.uploadArray[i].abort();

> Error: undefined is not an object (evaluating '$scope.statusLog[evt.config.data.index].percentage = progressPercentage')

This is what it is referring to in the `$scope.uploadArray[i] = Upload.upload()`

    .progress(function (evt) {
        var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
        $scope.statusLog[evt.config.data.index].percentage = progressPercentage;
     })

Do you know why this could be happening? Is there a better way to abort the upload?

**Comment by danialfarid** [comment]
Check if evt and evt.config.data are defined.

**Comment by bgold0** [comment]
I'm using your exact sample scripts. The percentages always show correctly of course they are defined. Why close this so fast?

**Comment by danialfarid** [comment]
This is a javascript question ask it on stackoverflow. This is not an issue with the plugin itself.
You can ignore that abort error or as I mentioned check that those variables are not empty since when you are aborting those values could be emptied before the last progress event.

**Comment by bgold0** [comment]
Don't gotta be a dick about it. That's fine, I'll dig around more and make a more comprehensive question on stack. I'm fairly certain it's an issue with the plugin's abort feature tho.. The last progress event is no where near complete and there is absolutely no reason why it wouldn't be found.

**Comment by danialfarid** [comment]
Sorry, that's the only way to be able to keep up with all the new issues that are being opened and avoiding a pile of issues with the limited time I have to work on this project. So unless steps to reproduce are provided clearly and it is certainly an issue with the plugin it would most probably be an angular or javascript question or not configuring the plugin correctly so those are better to be asked on SO.

In this case the error is clear that one of those values are undefined so you can figure out which one it is and have a null check for that.
