### ISSUE TITLE
Security error 2049

### ISSUE THREAD

**Issue by dmarlow** [danialfarid/ng-file-upload#1289]
I'm using IE9 and am seeing an error. Here's my setup: trying to postback to server that's hosting the upload control, so CORS shouldn't be an issue (though I've enabled CORS and have a crossdomain.xml in the root of my server), using HTTPS. Chrome works fine.
The error which provides little help to fixing it. I'm hoping someone else has seen it and can point me in the right direction. I've tried all sorts of internet explorer options (trusted sites, lowering security, etc.)

`"SecurityError [SecurityErrorEvent type="securityError" bubbles=false cancelable=false eventPhase=2 text="Error #: [SecurityErrorEvent type="securityError" bubbles=false cancelable=false eventPhase=2 text="Error #2049" {
	contains : function(){return-1!==String.prototype.indexOf.apply(this,arguments)}
}`

**Comment by danialfarid** [comment]
Possibly your crossdomain.xml is missing some permissions.

**Comment by dmarlow** [comment]
If there's an option to give it more permissions, I'm open to suggestions.
Here's my current one:
```xml
<cross-domain-policy>
  <site-control permitted-cross-domain-policies="all"/>
  <allow-access-from domain="*redacted*>"/>
  <allow-http-request-headers-from domain="*" headers="*" secure="false"/>
</cross-domain-policy>```

**Comment by danialfarid** [comment]
try 

```
<?xml version="1.0" ?>
<cross-domain-policy>
	<site-control permitted-cross-domain-policies="all" />
	<allow-access-from domain="*" secure="false" />
	<allow-access-from domain="sub.domain.com" />
	<allow-http-request-headers-from domain="*" headers="*" secure="false" />
</cross-domain-policy>
```

replace the url with the exact client url and also have *. If that works then you can try to narrow it down.

**Comment by dmarlow** [comment]
Thanks for the suggestion. I'll try it out.

**Comment by dmarlow** [comment]
That looks like it worked. Thanks again. Now I need to figure out why what I had didn't work...
