### ISSUE TITLE
Setting custom headers for $upload.upload() or sending file with $upload.http() in IE8-9

### ISSUE THREAD

**Issue by benbracha** [danialfarid/ng-file-upload#129]
I wanted to send file's content to the server, and it expects a 
'Content-Type': 'application/octet-stream'
But even when setting it in the $upload.upload() (setting the 'headers'), it gets overridden.

Daniel answer for this:
$upload.upload() need to have the content type formdata-multipart for the server to be able to decode the content of the request so you cannot change that.

For that purpose, we should use the $upload.http() call, as here:
See this: https://github.com/danialfarid/angular-file-upload/issues/88#issuecomment-31366487

**Comment by danialfarid** [comment]
@benbracha 
FileReader readAsDataURL polyfill has been added since version 4.2.0
