### ISSUE TITLE
Firefox and Safari encoding issue

### ISSUE THREAD

**Issue by oozywaters** [danialfarid/ng-file-upload#1291]
Hi,
I' m trying to send multiple files and JSON data with cyrillic symbols. After making a request, cyrillic characters shown in console's Request Payload section (and received by server) are not displayed correctly (something like ÐÐ°Ðº Ð¶Ð¸ÑÑ ÑÐ).
This behaviour can be seen in Firefox and Safari browsers.
Chrome seems to be OK.
Any thoughts?

EDIT: Problem magically solves if I don't attach files to my request.

**Comment by danialfarid** [comment]
Create a jsfiddle with steps to reproduce.
