### ISSUE TITLE
Able to upload any file

### ISSUE THREAD

**Issue by skbelalmd** [danialfarid/ng-file-upload#1292]
If I want to upload only images, the accept attribute has property image/* .
But it can upload files with any extension.

**Comment by danialfarid** [comment]
What do you mean? provide steps to reproduce and see the jsfiddle sample for uploading images.

**Comment by skbelalmd** [comment]
While uploading images, if you select a text file, (or even any file in formats other than images), are uploaded.

is there any method to ensure that only image file can be uploaded

**Comment by danialfarid** [comment]
use `ngf-pattern`
