### ISSUE TITLE
Chunk upload with Laravel 5

### ISSUE THREAD

**Issue by lakhwinder-logiciel** [danialfarid/ng-file-upload#1293]
Hi, 
I'm stuck in chunk upload of file. If I'm using this with core php then it will send total chunks and current chunk. But not getting these parameters in laravel controller using Request class. Can you please tell me that, is there any issue in my code or any other issue. Please help me.

## here is the angular code.
```
if (files && files.length) {
    for (var i = 0; i < files.length; i++) {
    	Upload.upload({
            url: RouteUrlsConstant.UploadMultipleDocument,
            data: {file: files[i]},
            resumeChunkSize: '10KB'
        }).then(function (resp) {
            console.log('Success ' + resp.config.data.file.name + 'uploaded. Response: ' + resp.data);
        }, function (resp) {
            console.log('Error status: ' + resp.status);
        }, function (evt) {
            var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
            console.log('progress: ' + progressPercentage + '% ' + evt.config.data.file.name);
            $scope.progress = 
                Math.min(100, parseInt(100.0 * evt.loaded / evt.total));
        });
    }
}
```

## and here is the laravel code 
```
public function upload(Request $request) {
   dd($request->all());
}
```
## output code
```
array:1 [
  "file" => UploadedFile {#30
    -test: false
    -originalName: "MARBLES.gif"
    -mimeType: "image/gif"
    -size: 770388
    -error: 0
  }
]
```

**Comment by danialfarid** [comment]
You need to provide `resumeSizeUrl` or `resumeSize`. Read the Resumable Uploads section.

**Comment by dustin-miller** [comment]
I am also noticing some oddities with the _chunkSize and _currentChunkSize values. I have resumeChunkSize and resumeSizeUrl specified, but on one of our environments the _currentChunkSize property is not showing up, and the _chunkSize property seems to be behaving like the _currentChunkSize typically would.

**Comment by danialfarid** [comment]
you probably have different versions of the plugin. _currentChunkSize was introduced recently. @dustin-miller

**Comment by dustin-miller** [comment]
@danialfarid Upon closer inspection, the environment did turn out to be stuck on an older version. I updated it to the latest and the problem is now resolved. Thanks!
