### ISSUE TITLE
Preview only and an upload button to upload

### ISSUE THREAD

**Issue by jeanrl** [danialfarid/ng-file-upload#1295]
Hello everyone!

Sorry for the dumb question, but how can just only show the image and have a upload button to upload the picture?
I only saw examples bearing the image and already do the upload.

I use angularjs.

Thanks,

**Comment by danialfarid** [comment]
see jsfiddle samples on the docs

**Comment by jeanrl** [comment]
@danialfarid 

I'm sorry the insistence and lack of experience, but
I looked at all the examples and they do direct uploading. I need a first preview and a button to upload.

Thank you so much.

**Comment by danialfarid** [comment]
first jsfiddle example uploads on submit not direct.

**Comment by jeanrl** [comment]
Ok, thanks.
