### ISSUE TITLE
Incompatibiliy with page.js - progress callback not called - progress notify not called

### ISSUE THREAD

**Issue by nyl-auster** [danialfarid/ng-file-upload#1297]
I spent 3 days on it so i must post this somewhere , i did not find the previous issue about it : https://github.com/danialfarid/ng-file-upload/issues/561

The notify callback or progress callback was never called on my project. That was because "pace" was included in the page too and that was fucking hard to understand as they were so many javascripts included in my page... Hope that it will save someone else !

**Comment by danialfarid** [comment]
There is already an issue opened for this and is fixed at 11.2.0.
#1123
