### ISSUE TITLE
405 on upload

### ISSUE THREAD

**Issue by Sellitecture** [danialfarid/ng-file-upload#1298]
my shared hosting provider (hostek) is blocking file uploads through angular evidently which is totally lame.  I need to figure out how to get to the actual binary string so i can save it out to an object and send it up with my json object so i can process on the server side and convert it back to an image.

How do i either get around the 405 issue or how can I get to the binary string?  I'm under the gun so any help is greatly appreciated.

**Comment by danialfarid** [comment]
Use `Upload.dataUrl(file).then(...)` to convert the file to dataurl then send the data url to the server and convert it to file on the server side.

**Comment by Sellitecture** [comment]
here is the code once i select the picture off the computer.  I selected a
900x900 pixel image so the binary should be pretty long.


    vm.uploadOyeItem = function (file) {
        console.log(file);
        var binary = Upload.dataUrl(file);

        console.log (binary);

[snip]



[image: Inline image 1]
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by danialfarid** [comment]
it returns a promise

**Comment by danialfarid** [comment]
read the docs
