### ISSUE TITLE
Error: a is null : Error on clicking remove button

### ISSUE THREAD

**Issue by rroxysam** [danialfarid/ng-file-upload#1299]
Hello Danial,

I have faced one error when click on the remove button after image preview.  Here is the link of fiddle, i am using for upload :  http://jsfiddle.net/danialfarid/maqbzv15/544/. No doubt, that file is uploading successfully.  I have tried many changes, but still it appears.

Below is the error, i got

Error: a is null
h/<@http://localhost:3000/scripts/webjs_angular/angular-ng-file-upload.min.js:2:19441
n@http://localhost:3000/scripts/webjs_angular/angular.min.js:7:331
h@http://localhost:3000/scripts/webjs_angular/angular-ng-file-upload.min.js:2:19370
f.validate@http://localhost:3000/scripts/webjs_angular/angular-ng-file-upload.min.js:2:20801
f.registerModelChangeValidator/<@http://localhost:3000/scripts/webjs_angular/angular-ng-file-upload.min.js:2:18370
yg</<@http://localhost:3000/scripts/webjs_angular/angular.min.js:266:23
lf/this.$get</r.prototype.$digest@http://localhost:3000/scripts/webjs_angular/angular.min.js:131:12
lf/this.$get</r.prototype.$apply@http://localhost:3000/scripts/webjs_angular/angular.min.js:134:76
Ic[b]</<.compile/</<@http://localhost:3000/scripts/webjs_angular/angular.min.js:254:124
n.event.dispatch@http://localhost:3000/scripts/webjs/jquery-2.1.3.min.js:3:6392
n.event.add/r.handle@http://localhost:3000/scripts/webjs/jquery-2.1.3.min.js:3:3202

http://localhost:3000/scripts/webjs_angular/angular.min.js
Line 107

**Comment by danialfarid** [comment]
Fixed at 11.2.3
