### ISSUE TITLE
ngf-pattern base64 ng-invalid 

### ISSUE THREAD

**Issue by tiberiuzuld** [danialfarid/ng-file-upload#1301]
Hello,

Related to #1294 , now after converting to base64 and setting the model to that, I get ng-invalid for pattern.

I updated [plunker](https://plnkr.co/edit/OE97515YOJtvSl7sMNFp?p=preview)

**Comment by danialfarid** [comment]
base64 data url is a string not a file, you shouldn't set it as file model.
