### ISSUE TITLE
Question: Drag and Drop on anywhere on page

### ISSUE THREAD

**Issue by irshadmalek11** [danialfarid/ng-file-upload#1303]
Is it possible to process file if user drag and drop on the page anywhere other than drag and drop "div" ?
I added "ngf-drop" on form but it doesn't do anything, just shows some blue box when I try to drag but after drop doesn't happen anything

**Comment by danialfarid** [comment]
You should be able to add it to any element that supports drop event.
Post your code or create a jsfiddle it is probably error in your directives setup or js code
