### ISSUE TITLE
Can't upload some images when ngf-fix-orientation="true"

### ISSUE THREAD

**Issue by miguelcaires** [danialfarid/ng-file-upload#1306]
When forcing the ngf-fix-orientation attribute to be true, as it isn't triggering the necessary transforms otherwise, I keep getting the a 400 - Bad Request error, when not uploading an image that has been taken with an iOS device.
This is the plugin's response:
"Upload a valid image. The file you uploaded was either not an image or a corrupted image."

Any ideas on what might be causing this?

Thanks a lot! :+1: 

Relates to #927 - "iOS - Taking a picture to upload is always coming out landscape"

**Comment by danialfarid** [comment]
@miguelcaires What is the technology on your server that returns this error?

**Comment by miguelcaires** [comment]
@danialfarid It's running a Django backend.

**Comment by danialfarid** [comment]
Would it work if you just have `ngf-resize="{width:100, height:100}"` without `ngf-fix-orientation`?

**Comment by danialfarid** [comment]
Could it be this? http://stackoverflow.com/questions/7606614/django-imagefield-upload-a-valid-image-the-file-you-uploaded-was-either-not-an

**Comment by miguelcaires** [comment]
Hi @danialfarid.

Sorry for the delay. 
This issue was addressed in the backend. 

Thanks for getting back, and congrats once again on an amazing plugin! :+1:
