### ISSUE TITLE
How check upload status?

### ISSUE THREAD

**Issue by masoud919** [danialfarid/ng-file-upload#1308]
I'm building a web page where you can upload multiple files.                
```HTML
<button type="button" class="btn btn-default"
        ngf-select="model.uploadSelectedFiles($files, $invalidFiles)" ngf-multiple="true"
        ngf-accept="'.bmp, .gif, .png, .jpeg, .jpg, .jpe, .jfif, .pdf'"
        ngf-max-size="2MB" ngf-keep="true"
        ng-model="model.files" ngf-model-invalid="model.invalidFiles">
    Select receipt files
</button>                
```
When files are selected, they are listed by `<div  ng-repeat="f in model.files">` and there are 3 buttons for every file: Upload, Cancel, Remove.
When the Upload is clicked, how would you check the upload status, see if it is being uploaded, already successfully uploaded, was failed or was aborted?

Cheers

**Comment by danialfarid** [comment]
That's an SO question.
You can set the status on each individual file based on progress success and error promise returned by Upload.upload().then().
See the demo page code for hints.
