### ISSUE TITLE
ie8 nothing happens by upload

### ISSUE THREAD

**Issue by zsolti** [danialfarid/ng-file-upload#1310]
Hello Danial,
My problem is that when I overwrite my controllers body with the upload.js body from the latest demo, and put exactly the same html elements what i find in index.html on my page nothing happens. 
I have tried the demo page though, and there everything functioned, I could upload a small csv file. 
That would be my target: To upload a small csv file (<1MB), always one file, and POST it to the server side, but I couldn't manage to do that so far. I use IE8 (not compatibility mode, but really ie8) Win7 x64.
Angular 1.2.28 (as far as i know the best version which still supports ie8) and jQuery v1.11.3.

The symptom is: the Flash is there (right click, and than comes this Adobe Flash player...sg.) The filepicker works, but when I close it, on the demo page I can see some progress down there, almost immediatelly 100% en writes some details about my file... I think that should happen in my html too, but after picking the file, the picker disappears. Thats all.
These are my scripts in index.html:
<script>
document.createElement('paginator');
document.createElement('paginatorGrey');
document.createElement('preventDefault');
document.createElement('header'); 
document.createElement('footer'); 
document.createElement('section'); 
document.createElement('article'); 
document.createElement('aside'); 
document.createElement('nav');
document.createElement('predefhtml');
document.createElement('fileModel');
</script>
<script type="text/javascript">
    FileAPI = {
      jsPath: '/VV3rng-rs/app/js/',
      staticPath: '/VV3rng-rs/app/js/'
    };
</script>
<script src="js/angular.js"></script>
<script src="js/angular-route.js"></script>
<script src="js/angular-resource.js"></script>
<script src="js/angular-animate.js"></script>
<script src="js/angular-sanitize.js"></script>
<script src="js/angular-locale_de-de.js"></script>
<script src="js/ui-bootstrap-tpls.js"></script>
<script src="js/angular-fancy-modal.js"></script>
<script src="js/respond.js"></script>
<script src="js/html5shiv-printshiv.js"></script>
<script src="js/html5.js"></script>
<script src="js/json3.js"></script>
<script src="js/jquery.js"></script>
<script src="js/bootstrap.js"></script>
<script src="js/angular-strap.js"></script>
<script src="js/angular-strap.tpl.js"></script>
<script src="js/bootstrap-datepicker.js"></script>
<script src="js/bootstrap-datepicker.de.min.js"></script>
<script src="js/moment.js"></script>
<script src="js/lodash.js"></script>
<script src="js/restangular.js"></script>

<script src="js/ng-file-upload-shim.js"></script>
<script src="js/ng-file-upload.js"></script>
<script src="js/upload.js"></script>
 
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/4.8.0/codemirror.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/4.8.0/codemirror.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/4.8.0/mode/htmlmixed/htmlmixed.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/4.8.0/mode/htmlembedded/htmlembedded.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/4.8.0/mode/xml/xml.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/4.8.0/mode/javascript/javascript.min.js"></script>
<script src="js/vv3.js"></script>
<script src="js/vv3-controllers.js"></script>
<script src="js/vv3-services.js"></script>
<script src="js/vv3-directives.js"></script>
<script src="js/vv3-filters.js"></script>

Thank you for help!

**Comment by zsolti** [comment]
so my scripts from index.html (somehow it was cut out for the first time):

FileAPI = {
	      jsPath: '/VV3rng-rs/app/js/',
	      staticPath: '/VV3rng-rs/app/js/'
 };
js/angular.js"></script>
js/angular-route.js"></script>
js/angular-resource.js"></script>
js/angular-animate.js"></script>
js/angular-sanitize.js"></script>
js/angular-locale_de-de.js"></script>
js/ui-bootstrap-tpls.js"></script>
js/angular-fancy-modal.js"></script>
js/respond.js"></script>
js/html5shiv-printshiv.js"></script>
js/html5.js"></script>
js/json3.js"></script>
js/jquery.js"></script>
js/bootstrap.js"></script>
js/angular-strap.js"></script>
js/angular-strap.tpl.js"></script>
js/bootstrap-datepicker.js"></script>
js/bootstrap-datepicker.de.min.js"></script>
js/moment.js"></script>
js/lodash.js"></script>
js/restangular.js"></script>
	
js/ng-file-upload-shim.js"></script>
js/ng-file-upload.js"></script>
js/upload.js"></script>
 
//cdnjs.cloudflare.com/ajax/libs/codemirror/4.8.0/codemirror.min.css
//cdnjs.cloudflare.com/ajax/libs/codemirror/4.8.0/codemirror.min.js
//cdnjs.cloudflare.com/ajax/libs/codemirror/4.8.0/mode/htmlmixed/htmlmixed.min.js
//cdnjs.cloudflare.com/ajax/libs/codemirror/4.8.0/mode/htmlembedded/htmlembedded.min.js
//cdnjs.cloudflare.com/ajax/libs/codemirror/4.8.0/mode/xml/xml.min.js
//cdnjs.cloudflare.com/ajax/libs/codemirror/4.8.0/mode/javascript/javascript.min.js
js/vv3.js
js/vv3-controllers.js
js/vv3-services.js
js/vv3-directives.js
js/vv3-filters.js

**Comment by zsolti** [comment]
I also enabled debug on flash fileAPI, and made several breakpoints, and it doesnt stop after I picked the file, but the $watch uses the exact same name of the model. 

![debug001](https://cloud.githubusercontent.com/assets/6108483/12659392/d3626e54-c60e-11e5-840b-a2520c80f85b.png)

**Comment by danialfarid** [comment]
If you could create a jsfiddle that would help narrow down the problem.
You could use `ngf-select="selectFile($file)"`  and define `$scope.selectFile` function in your js code to make sure the select works.

**Comment by zsolti** [comment]
As I was trying out your suggestion something happened in the background (or at least it was not triggered by user input):
![debug002](https://cloud.githubusercontent.com/assets/6108483/12661092/e7b42e2a-c617-11e5-8769-c7454a3eb846.png)
and at the same time i have made this into my controller:
$scope.selectFile = function($file) {
   $scope.selectedFileToUpload = $file;
 }
And made a breakpoint there, but it didn't stop.
It doesn't stop either in the latest chrome.
I work on the jsfiddle. Hopefully it will work on ie8.

**Comment by danialfarid** [comment]
Reopen if the issue still exists and you could reproduce in a fiddle.
