### ISSUE TITLE
Validate JSON file content before uploading to server

### ISSUE THREAD

**Issue by jitendersandhu** [danialfarid/ng-file-upload#1311]
Hi Danial (@danialfarid),

I am using `ng-file-upload` to upload `JSON file` to server. Everything is working fine except, not able to read file content and validate for valid `JSON` file on client side before uploading to server. something like this:

> function isValidJson ($scope.file) {
>                     try {
>                         JSON.parse(str);
>                     } catch (e) {
>                         return false;
>                     }
>                     return true;
>                 }

Is there an option available to do this or to validate json file by some other means. Any help is much appreciated. Thanks!

**Comment by danialfarid** [comment]
You can have `ngf-validate-async-fn="validateJson($file)"` and use FileReader readAsText: https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsText to ready the text content of the file and validate it.

**Comment by jitendersandhu** [comment]
@danialfarid 
Thanks for the quick reply. I will try this solution.

**Comment by jitendersandhu** [comment]
@danialfarid 
Thanks Danial, it works now..hence closing this one.
