### ISSUE TITLE
One By One File upload is not working

### ISSUE THREAD

**Issue by prashanthsun9** [danialfarid/ng-file-upload#1312]
Below is my code, I am trying to send files one by one which is not working I am not sure why?

Whenever I upload multiple files, the entire files(all) is getting sent together and the file content is getting misplaced, not sure why? please help

    $scope.uploadFiles = function(files) {
        blockUI.stop();
        if(files != undefined) {

            for (var i = 0; i < files.length; i++) {

                if (files[i] && !files[i].$error) {

                    if (isSpecialChar(files[i].name)) {

                        var headers = {
                            'token': $('.uploadToken').html(),
                            'userName': $('.uploadUserName').html(),
                            'Content-disposition': 'inline;filename=' + files[i].name,
                            'is-exists': 'false',
                            'file-path': $scope.crumbString.slice(0, -1),
                            'file-name': files[i].name,
                            'file-size': files[i].size,
                            'is-folder': 'false',
                            'is-base-folder': 'false',
                            'fileMD5': md5.createHash('fileName'),
                            'modified': files[i].lastModified
                        };

                        Upload.upload({
                            url: url,
                            headers: headers,
                            method: 'POST',
                            file: files[i]
                        });
                    }
                }
            }
        }

**Comment by danialfarid** [comment]
Create a jsfiddle with steps to reproduce. This is probably an error in your js code.
