### ISSUE TITLE
File type filter not working in Safari

### ISSUE THREAD

**Issue by Tedko** [danialfarid/ng-file-upload#1313]
Environment: OS X 10.11 Safari 9.0.2

I add a filter ```.txt``` and it works well in Chrome (but this filter also accept files like .py, .sh)
![2016-01-29 6 37 41](https://cloud.githubusercontent.com/assets/6687437/12693174/0d514636-c6b8-11e5-86a7-7bb501626272.png)

However, it's not working on Safari.

![2016-01-29 6 37 31](https://cloud.githubusercontent.com/assets/6687437/12693176/1b73dee0-c6b8-11e5-88d7-86e98e8965d1.png)

This can be reproduced by the demo.
![2016-01-29 6 40 22](https://cloud.githubusercontent.com/assets/6687437/12693181/38c95830-c6b8-11e5-8da8-d3864595b4b6.png)

**Comment by danialfarid** [comment]
Post your code

**Comment by Tedko** [comment]
You can reproduce it in the official demo. Change the filter from `"images/*" `to ` "'.txt'"`

**Comment by danialfarid** [comment]
which filter

**Comment by Tedko** [comment]
ngf-accept = "'.txt'"

**Comment by Tedko** [comment]
```html
              Profile Picture: <input type="file" ngf-select="" ng-model="picFile" name="file" ngf-accept="'.txt'" required="">

```

I changed this line in the demo

**Comment by Tedko** [comment]
Here is how I reproduce it on Safari.

![mediummaze](https://cloud.githubusercontent.com/assets/6687437/12694138/aa539a50-c6d7-11e5-91af-47951c493499.gif)

**Comment by danialfarid** [comment]
The popup file select is browser specific implementation, use `ngf-pattern` to validate the file type.
You can play around with different accept values by a regular `<input type="file" accept=".txt">` to see if you can get it to filter what you want but it depends on how browsers are implementing it.

**Comment by Tedko** [comment]
I had tried this 
```html
                    <input type="file" ngf-select
                           ng-model="File"
                           name="file"
                           input type="file"
                           accept=".txt"
                           ngf-accept="'.txt, .json'"
                           ngf-max-size="10MB" required
                           ngf-model-invalid="errorFiles">
```

it's not working on safari. Seems like all filters are not working properly on Safari.

**Comment by danialfarid** [comment]
As i said it's browser dependent so yep ask it on safari forum or support.

**Comment by keithics** [comment]
+1 same problem.. osx 10.10.5 safari.

**Comment by Tedko** [comment]
Seems Safari all have this problem

**Comment by jitendersandhu** [comment]
+1
@danialfarid 
I am also facing the same issue in safari. `accept=".json"` is not working in safari for me. Any workaround you suggest. Thanks!

**Comment by ltkhuong7** [comment]
You guys should use MIME type instead of file extension name.
example: accept: 'image/*,audio/*,video/*,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/msword,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,text/csv,application/vnd.ms-powerpoint,application/vnd.openxmlformats-officedocument.presentationml.presentation,application/x-zip-compressed,.7z,application/octet-stream,application/pdf,text/rtf,text/plain,.gpd,.pro', //,.gpd,.pro sterio records

**Comment by wenjiezhang2013** [comment]
even the MIME type won't work for all the types. See https://caniuse.com/#feat=input-file-accept, 

Safari has an issue on implementing this for all the standard versions, I have verified some of the types that do not work in standard version of safari, but work fine in Safari Tech review version.

**Comment by Xample** [comment]
MIME looks to work fine on Sarafi, for instance I replaced accept=".png" with
```html
<input accept="image/png,image/x-png">
```
