### ISSUE TITLE
When using drag and drop $watch only work with $scope and no vm

### ISSUE THREAD

**Issue by faidoc** [danialfarid/ng-file-upload#1314]
Hi

I am using ControllerAs and making my functions with 'vm = this'.

When I write the $watch code to make the drag and drop work, I first put my model with 'uploader.Files' and create the function as follows:

```
 $scope.$watch('vm.Files', function () {
      vm.uploadFiles(vm.Files);
 });
```

But never worked. Then I tried using scope setting my model to 'Files' and the $watch function as follows:

```
 $scope.$watch('Files', function () {
      vm.uploadFiles($scope.Files);
 });
```

And I got it working. Why can't I put it with the vm approach?

Thanks

**Comment by danialfarid** [comment]
Ask on SO and create a jsfiddle sample or post your full html js code

**Comment by slimovic** [comment]
@faidoc  I assume in your html you set your ng-model like this

```javascript
ng-model="vm.Files"
```
