### ISSUE TITLE
upload not working

### ISSUE THREAD

**Issue by aspcsharp** [danialfarid/ng-file-upload#1315]
What is the problem, when change your url to my url upload not working!

          //url: 'https://angular-file-upload-cors-srv.appspot.com/upload',
	  url: 'http//mysite.com/img',

**Comment by slimovic** [comment]
You miss a colon:

** url: 'http://mysite.com/img', **

**Comment by aspcsharp** [comment]
Again not working, please try http://infoprijedor.info/indexUpload.html

**Comment by danialfarid** [comment]
That's a server issue nor related to this plugin, try posting it on stackoverflow
