### ISSUE TITLE
ngf-max-size and custom directive

### ISSUE THREAD

**Issue by CicciMTS** [danialfarid/ng-file-upload#1318]
Hello, i have a custom directive that is delegate to upload a file, everything is ok, but when i set ngf-max-size with a scope obj, i have this error: 
<pre>Syntax Error: Token '{' invalid key at column 2 of the expression [{{field.maxLen}}] starting at [{field.maxLen}}].</pre>

This is the HTML:
```<custom-field-file ng-model="field.value" name-field="{{field.name}}" ngf-max-size="{{field.maxLen}}" ng-required="field.isRequired === 'true'"></custom-field-file>```

And this is the directive:
```
appDirectives.directive('customFieldFile', ['Upload' ,function( Upload ){
    return{
        restrict: 'E',
        scope: {
            isRequired: "@ngRequired",
            ngModel: "=",
            nameField: "@",
            ngfMaxSize: "=",
            ngfSelect: "="
        },
        template: '<input type="file" name="{{nameField}}" ngf-select ngf-max-size >'
        replace: true
    }
}]);
```

How can i figure out? Thanks

**Comment by danialfarid** [comment]
remove the curly brackets.

**Comment by CicciMTS** [comment]
Ok, the errror is solved, but doen't works... the validation of the size is ever valid.

**Comment by danialfarid** [comment]
Post your code or create a jsfiddle. It works on the demo page.
