### ISSUE TITLE
ngf-background should add option to disable toggling ng-hide

### ISSUE THREAD

**Issue by epelc** [danialfarid/ng-file-upload#1320]
I was using an older version(5.x) and I had a custom thumbnail/preview generator similar to the new `ngf-background`. I just upgraded to the latest version so I figured I'd see if I could switch to using `ngf-background` as it's already included now. However I ran into an issue. It automatically toggles the `.ng-hide` class. This is a problem if your preview/background area is the same as your drag n drop area.

With my custom generator I could let users drop different files on the drop area to change the current selected/previewed file. With the `ngf-background` I can't do this anymore so I can't switch to using it.

Example of where `.ng-hide` is toggled. Note there are a few other spots in this file. Perhaps adding an option to disable this behavior would work? Or maybe even remove it and make people manage `ng-hide` themselves.
https://github.com/danialfarid/ng-file-upload/blob/master/src/data-url.js#L111-L115

**Comment by danialfarid** [comment]
For a workaround you can have `ngf-background="file || ' '"`

**Comment by epelc** [comment]
@danialfarid Thanks that works perfect.

**Comment by danialfarid** [comment]
I think this workaround is good/simple enough that doesn't need to add another directive for this.
