### ISSUE TITLE
Error callback returns status 0

### ISSUE THREAD

**Issue by random-one** [danialfarid/ng-file-upload#1322]
Hello, I am using `ng-file-upload` for a single file to put it on a django server. I am using Django Rest Framework and what I am trying to achieve it to block all other server uploads if one upload is already started.
Django has a middleware mechanism that allows me to attach on each request and do some checks and decide if the request(in my case file upload) can be passed to the view or rejected.
This middleware returns `None` if the request should be further processed or an `HttpResponse` with a particular content and status code. In my case I want to return `400` and receive this status code in the error callback. What happens is that no matter what response my middleware returns in the `.error(response)` function all I get is `status=0`, `data=null` and no headers.

Can you give me a hint how to fix this?

**Comment by danialfarid** [comment]
If you see the response in the network tab with empty data and status then it is a server side issue, you can post it on SO with Django tag.

**Comment by jitendersandhu** [comment]
@danialfarid 
[QUESTION] Should the File Upload API always return a response object, even in case there is an error?
For example - `403 Forbidden`, APIs in our project just return `403` status code in case of `Authorization Token` missing. Wondering if there is an option for `ng-file-upload error handler` to handle API errors without any response object? Thanks!

**Comment by danialfarid** [comment]
No there is no need for response, unless you are supported IE8-9 which would need the response due to Flash bug (read the old browsers known issues section).

**Comment by jitendersandhu** [comment]
@danialfarid In my project, API is returning `Status Code:200 OK` on successful upload, still file upload is failing with following error in developer tool console log - 
`net::ERR_CONTENT_LENGTH_MISMATCH`
But when API returns response object `{"fileName":config.json}`, it works fine. Not sure whether it's issue with plugin or my JS code.

Here is my code for upload -

> var importURL = urlConfigService.getURL('importConfig'),
>   dataObject = {
>     'config': $scope.file
>   };
> 
> uploadPromise.upload = Upload.upload({
>   url: importURL,
>   data: dataObject
> });
> 
> uploadPromise.upload.then(function() {
>   $log.debug('upload success');
>   // stop spinner and success notification code here
> }, function() {
>   $log.debug('upload failure');
> }, function(evt) {
>   $log.debug('upload progress');
>   $scope.progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
> }).finally(function() {
>   // stop spinner code here
> });

Thanks!

**Comment by danialfarid** [comment]
Well the error say content-length doesn't match in your response header. Make sure your server returns correct response header for content-length.

**Comment by jitendersandhu** [comment]
@danialfarid 

Thanks for your response..It's a great plugin to implement file upload feature. it's working fine for me. Thanks for closing this. sorry for late reply but it's resolved now. Thanks once again!
