### ISSUE TITLE
iOS 9 and ngf-keep distinct gives problems

### ISSUE THREAD

**Issue by JaZo** [danialfarid/ng-file-upload#1323]
When I set ngf-keep to distinct, I can't upload more than one photo. This is because on iOS 9 the filename of every file is 'image.jpeg' and the distinct check is based on the filename.

**Comment by danialfarid** [comment]
Will be fixed in the next release.

**Comment by JaZo** [comment]
Ok, thanks for the quick response!

**Comment by danialfarid** [comment]
Fixed at 12.0.1
