### ISSUE TITLE
fileUpload doesn't work properly after build with Grunt and Bower

### ISSUE THREAD

**Issue by SpadesTheOriginal** [danialfarid/ng-file-upload#1324]
I installed ng-file-upload with bower. and I use it to create a drop zone.
It's working perfectly (though it crashes when  I drop a huge folder, but I digress...)

But once I build the project, when I drop files, whatever the number, I don't get an array but a single file.
EDIT: I checked, and both in the devel and the build version "multiple" is set.

For the build, since it's a bower_component, it's concatenated like every other components, with which I don't have any issue.

**Comment by danialfarid** [comment]
Post your code.
Also for folder drop you can set `ngf-max-files="100"` or something similar to avoid crash.

**Comment by SpadesTheOriginal** [comment]
I have a pretty basic form, with a bit of css tweaking.

	
	<div class="dropzone" ngf-select ngf-drop ng-model="files" multiple="true" ngf-min-size="132">
		<h2><i class="fa fa-upload"></i> Drop Images Here !</h2>
		<div>Or just click to select files.</div>
	</div>

And my files are retreived the way your tuto explained.

	// In my controller I have this watcher.
	$scope.$watch('files', function(newValue, oldValue) {
		if (newValue && newValue !== oldValue) {
			$rootScope.uploadProcess = true;
			processFiles(newValue);
		}
	});

As I was writing more about my problem, I tried to replace multiple="true" **by ngf-multiple="true" and it works**.
I don't know if it will help identify the why but I have these add-ons:

    "angular": "^1.4.0",
    "bootstrap": "^3.2.0",
    "angular-animate": "^1.4.0",
    "angular-resource": "^1.4.0",
    "angular-route": "^1.4.0",
    "angular-sanitize": "^1.4.0",
    "angular-touch": "^1.4.0",
    "angular-bootstrap": "^1.1.1",
    "ng-file-upload": "^11.2.3",
    "angular-ui-notification": "^0.1.0",
    "components-font-awesome": "^4.5.0",
    "dicomParser": "^1.2.0",
    "jszip": "Stuk/jszip#^2.5.0",
    "file-saver.js": "^1.20150507.2"

These are concatenated and uglified in a vendor.token.js via grunt build.

**Comment by danialfarid** [comment]
multiple="true" works on the demo page. Create a jsfiddle if you can reproduce it.
