### ISSUE TITLE
Dragging and dropping pictures does not work in last version of plugin.

### ISSUE THREAD

**Issue by ruslan5t** [danialfarid/ng-file-upload#1325]
Hello.

Dragging and dropping pictures does not work for me in chrome with last version of plugin.

**Important:** It is not usual dragging and dropping, it does not work only when you tries to move picture from one tab to another - you select picture, move to tab with input-uploader and drop picture on input - result - you get this error message:
TypeError: Cannot read property 'type' of undefined
    at ng-file-upload.js:1321
    at Object.forEach (angular.js:325)
    at validateAsync (ng-file-upload.js:1318)
    at upload.validate (ng-file-upload.js:1355)
    at upload.updateModel (ng-file-upload.js:593)
    at updateModel (ng-file-upload.js:1840)
    at ng-file-upload.js:1797
    at wrappedCallback (angular.js:11572)
    at angular.js:11658
    at Scope.$eval (angular.js:12701)

It works correct with version 10.0.0.

If you need an example, you can use your own - https://angular-file-upload.appspot.com/. And video for you - http://screencast.com/t/nodjQsLg

**Comment by danialfarid** [comment]
I believe this bug has been introduced recently, you can try to use older versions until it is fixed in the next version.

**Comment by ruslan5t** [comment]
Thanks!
When do you think next release will be available?

**Comment by danialfarid** [comment]
ETA Less than a week

**Comment by danialfarid** [comment]
Fixed at 12.0.1

**Comment by ruslan5t** [comment]
Thanks!

**Comment by OverZealous** [comment]
@ruslan5t Did this fix work for you? I'm seeing the same error with 12.0.1 when I drag an image from one tab to another.

**Comment by ruslan5t** [comment]
@OverZealous You are right, I was too naive.
@danialfarid Can you please check your fix?
