### ISSUE TITLE
angular throws 'Illegal Invocation' when watching $files 

### ISSUE THREAD

**Issue by guy-mograbi-at-gigaspaces** [danialfarid/ng-file-upload#1327]
I have code that does the following 

     $scope.onFileSelected = function( $files ){ //  ==> callback to ngf-select
          $scope.item.file = $files[0];
     }  

     $scope.$watch('item', function(){ ... }, true); // watch changes on item

Once I select a file, angular throws `Illegal Invocation' when `$watch` is invoked

Not watching it, or not placing the file on the object, solves the problem.

**Comment by danialfarid** [comment]
that is not related to the plugin code, post it on StackOverflow or create a jsfiddle.
