### ISSUE TITLE
[Question] Big files uploading in 2 seconds?

### ISSUE THREAD

**Issue by Tomino2112** [danialfarid/ng-file-upload#1328]
Hi, this is just something that I would like to understand to. 

I just spent quite a long time making pretty progress bar for the upload only to find out that it swooshes through in about 2 seconds. 

I am uploading 25MB PDF on quite slow network, yet in network console I see POST request size of 800kb thats done in 2s. 

This would seem impossible, only the file really is on the server in its all 25mb glory... 

How is this done? Is the file somehow pre-uploading? But its the same even when I press upload right after I select it. Seems like magic to me haha

**Comment by danialfarid** [comment]
You are probably using the wrong options, post your code.

**Comment by Tomino2112** [comment]
@danialfarid I dont understand? Everything works fine, I just dont get how 25mb file is uploaded in 2s

Code that I am using:

```
$scope.upload = function (file) {
                var q = $q.defer();

                Upload.upload({
                    url: config.urls.endpoint+'/import/upload',
                    method: 'POST',
                    sendFieldsAs: 'form',
                    file: file,
                    withCredentials: true,
                    data: {
                        folderId: $scope.folderId,
                        pageId: $scope.pageId
                    }
                }).then(function (resp) {
                    $scope.uploadProgress = {loaded:0,total:0};

                    servAlert.success('File Upload', 'Document successfully uploaded');

                    q.resolve(resp.data);
                }, function (resp) {
                    $scope.uploadProgress = {loaded:0,total:0};
                    q.reject(resp.data);

                    servAlert.danger('Upload','Error uploading file');

                    console.log('Error status: ' + resp.status);
                }, function (evt) {
                    $scope.uploadProgress = evt;
                });

                return q.promise;
            };
```

**Comment by danialfarid** [comment]
What version of the plugin are you using?
`sendFieldsAs` is deprecated and you should put the file inside data.

**Comment by danialfarid** [comment]
If you don't see the file in the network tab request as part of form data then you are not adding the file object to the data and options properly.

**Comment by Tomino2112** [comment]
I am using 11.2.3

**Comment by danialfarid** [comment]
it should be 
```
 url: config.urls.endpoint+'/import/upload',
                    method: 'POST',
                    withCredentials: true,
                    data: {
                        folderId: $scope.folderId,
                        pageId: $scope.pageId,
                        file: file
                    }
```
and make sure the file object is the actual file not array or other objects.

**Comment by Tomino2112** [comment]
Same thing, 50mb file uploaded in 3s ... And there is no problem, I can see it full on the server

**Comment by Tomino2112** [comment]
The way I have it setup is that your script sends the file to my PHP script that uploads it to S3

**Comment by Tomino2112** [comment]
Only thing I can think of is that my php is streaming data from the client and passing it to s3. So I get response only about stream being established. Problem with that is, if I go to s3 in 2 seconds after hitting upload, the whole 50mb file is already there, I can open it and see it whole. 

Magic?

**Comment by danialfarid** [comment]
Well if it uploads properly then there is no issue, your network is probably faster than you think specially if you are running things locally, then it would be just one trip to amazon s3 servers which should be fast.

**Comment by Tomino2112** [comment]
yes there is no issue, I just dont understand how it can work like this. My network is definitely not fast enough to upload 50mb in 2s. And when I look at the network tab, the request doesnt have 50mb but ~800kb. I think it has something to do with streaming. I had a dig around the libraries and it streams the file from client and also streams it to s3. Thats only reasoning I can think of. I will probably ask on SO as well. Thanks
