### ISSUE TITLE
trigger file selected event 

### ISSUE THREAD

**Issue by Leo-G** [danialfarid/ng-file-upload#1329]
I have a crud app which works fine, except for the update part.

     <div>
       <input type = "file" ngf-select  ng-model="image.data.attributes.path" name="path" ngf-pattern="'image/*'"
             ngf-accept="'image/*'" ngf-max-size="20MB" required>
      <img ngf-thumbnail="image.data.attributes.path" width="101" height="62">
      <a ng-click="image.data.attributes.path = null" ng-show="image.data.attributes.path">Remove</a>
    
     </div>

The problem  is that  thumbnail works but the input displays no file chosen. I need it to display the currently uploaded file, How can I do this?

**Comment by danialfarid** [comment]
Show the current file using `image.data.attributes.path.name` and hide the input or parts of it that shows no file chosen or use a div instead of input.
