### ISSUE TITLE
When I'm using this with image crop it says this error Unknown provider: ngfDataUrlFilterProvider <- ngfDataUrlFilter

### ISSUE THREAD

**Issue by alexliubj** [danialfarid/ng-file-upload#1330]
Error: [$injector:unpr] Unknown provider: ngfDataUrlFilterProvider <- ngfDataUrlFilter
http://errors.angularjs.org/1.4.7/$injector/unpr?p0=ngfDataUrlFilterProvider%20%3C-%20ngfDataUrlFilter
    at angular.js:68
    at angular.js:4289
    at Object.getService [as get] (angular.js:4437)
    at angular.js:4294
    at Object.getService [as get] (angular.js:4437)
    at angular.js:18229
    at isStateless (angular.js:13130)
    at findConstantAndWatchExpressions (angular.js:13187)
    at angular.js:13141
    at forEach (angular.js:336)(anonymous function) @ angular.js:12477

**Comment by danialfarid** [comment]
Post your code and steps to reproduce. That's probably dependency injection error.

**Comment by alexliubj** [comment]
Copy and past the same code from this demo?
http://jsfiddle.net/xxo3sk41/1/

but i'm not using the latest version. Is that the problem?

**Comment by danialfarid** [comment]
Yes it could be.
