### ISSUE TITLE
Uploading to S3 having issues on some buckets

### ISSUE THREAD

**Issue by m0ngr31** [danialfarid/ng-file-upload#1331]
Having an issue uploading to S3 and can't figure out the issue. It's been working fine until recently.

I started looking for the issue and realized we were running v2.0.5(!!) so I updated and still running into the same issue.

Here's my function:
```
.factory('S3FileUploader', function($log, $q, Upload, FileUploader, Notifier) {
    var S3FileUploader = FileUploader.extend({
      uploadExternal: function(ecUploadResult) {
        return Upload.http({
          url: ecUploadResult.source_url,
          method: 'PUT',
          headers: {'Content-Type': this.file.type},
          data: this.fileContent
        }).progress(function(evt) { 
          this.notifyProgress(this.externalUploadQuotient * (evt.loaded / evt.total)); 
        }.bind(this)).then(function(response) {
          if(response.statusText === 'OK') {
            return ecUploadResult;
          } else {
            Notifier.error("There was an error uploading the file. Please try again.");
            $log.error('There was a problem uploading to s3:', response);
            return $q.reject(response);
          }
        }, function(err) {
          Notifier.error("There was an error uploading the file. Please try again");
          $log.error('There was a problem uploading to s3:', err);
          return $q.reject(err);
        });
      }
    });
    return S3FileUploader;
  })
```

I think the only thing I changed here is `Upload` from `$upload`. We have 2 different buckets, one of them works fine. But one of our buckets will not work at all: `SignatureDoesNotMatch`, `The request signature we calculated does not match the signature you provided. Check your key and signing method.`

The crazy thing is that this still works fine on our 1 bucket on our live server, just not our dev server, even with the old version of the directive. Is there something that I can check that it doesn't like?

I setup a codepen and just wrote a quick test outside of Angular to test and I was able to upload to that bucket with no issues, so it's something in our app.

**Comment by danialfarid** [comment]
If you are signing the url it is probably not signed properly from the error I would say.
Anyway if you are able to upload it to a different bucket then there is no issue with the plugin, and you can try asking it on SO.
