### ISSUE TITLE
ngf-file attribute fails when is called in a modal

### ISSUE THREAD

**Issue by coicoronado** [danialfarid/ng-file-upload#1332]
Hi
i was triying to make the implementation of the ngf-file in my current project, but came across a bug that involves angular-bootstrap ($modal) and of course this repo

I'm calling the select of the file inside a modal
At the first time is called everythig works great but since the modal is closed and try to re-open it the modal makes a compile call wich it will never display again the modal page since the compiler caught as an error the declaration of the attributes ngf-file

i did the test to call the modal several times without that attribute and works as expected but i cant use the plugin as it is in the demo

Additional data:
the template that is loaded in the modal is an outside file

**Comment by danialfarid** [comment]
I don't see how this issue is related to this plugin, provide steps to reproduce.
