### ISSUE TITLE
ngf-resize doesn't seem to do anything

### ISSUE THREAD

**Issue by danielbonnell** [danialfarid/ng-file-upload#1333]
I'm not sure if this is a bug or a problem with my code. I tried to follow the readme example as closely as possible. When I select image(s), they're uploaded successfully, however they're not being resized prior to upload as I would expect. Here is the code for my select button:

    <div class="btn btn-primary" ngf-select="submit($files, $event);" ngf-multiple="true" ngf-max-size="10MB" ngf-resize="{width: 1280, height: 1280}" ng-model="editPhotos.files" name="files" ngf-pattern="image/*" accept="image/*" required>Upload Images</div>

I'm not getting any errors or anything, but the images are clearly not resized when they hit S3.

**Comment by danialfarid** [comment]
Can you create a jsfiddle? what size are they on S3?

**Comment by danielbonnell** [comment]
I solved it. Pretty sure it was because I was running an older version (7.014) of this. Redownloaded the source and it's working great now. Thanks!

**Comment by kavishmehta** [comment]
@danialfarid 

I am trying to resize image by decreasing it quality (like quality: 0.8) but its not working for me like its not compressing image

`<div ngf-drop="" ngf-select="" ng-model="albumFiles" ng-model-rejected="rejFiles" ngf-drag-over-class="{accept:'dragover', reject:'dragover-err', delay:100}" class="drop-box ng-pristine ng-valid" ngf-multiple="true" ngf-allow-dir="true" ngf-accept="'image/*'"  ngf-pattern="'.jpg,.png,.jpeg,.bmp'" ngf-drop-available="dropAvailable" ngf-keep="true" ngf-validate="{pattern: '.jpg,.png,.jpeg,.bmp'}" ngf-ignore-invalid="'pattern'"  ngf-resize="{quality: .6}">`

This is my code but its not working file size remain same as uploaded.

Can you help me here where I am making mistake
