### ISSUE TITLE
ngf-select detect when user selects files and run function before processing files

### ISSUE THREAD

**Issue by danielbonnell** [danialfarid/ng-file-upload#1334]
Hello,

I'm wondering if it's possible to detect when a user selects a batch of files and call a function *before* the files are preprocessed. For example, I'd like to call a function to display a progress bar when a user selects a batch of files. In my controller I currently have the following function that is called in my `ngf-select`.

    $scope.submit = function(files) {
        $scope.failedUploads = [];
        photoUploadBtn.addClass('disabled');

        if (files) {
            for (var i = 0; i < files.length; i++) {
                var file = files[i];

                if(file.$error !== undefined){
                    $scope.failedUploads.push(file.name);
                    files.splice(i,1);
                }
            };

            if($scope.failedUploads.length > 0) $scope.validationError = true;
            $scope.uploading = true;
            $timeout(function(){
                upload(files);
            },100);
        };
    };

The `upload` function is the function that uploads the files to the server. As you can see, I'm trying to delay the the upload process momentarily so that I can first display a progress bar (`$scope.uploading = true`) to alert the user that their upload has started. Unfortunately this doesn't seem to work. My `submit` function isn't called until after the files have been preprocessed (e.g. resized using `ngf-resize`), which for a large batch, could be 30 seconds or longer - enough time for a user to think the app had frozen and navigate away from the page.

**Comment by danialfarid** [comment]
Use ngf-before-model-change="beforeChange($files, ...)"
