### ISSUE TITLE
An ‘invalid’ file selected makes the form state invalid (even when not required)

### ISSUE THREAD

**Issue by PsyStorm25** [danialfarid/ng-file-upload#1337]
Hello,

I have a problem with form validation and ng-file-upload.
When an ‘invalid’ image is selected/dropped the form becomes invalid whereas selecting a file is not mandatory.

Here is a jsfiddle to illustrate that:
http://jsfiddle.net/hbvsLstm/10/

Let’s suppose we have a form with a text field required and an optional image to attach.
I put a validation rule for the file size: <= 500KB.
The submit button is greyed out while the form state is invalid.

If you type something in the text field, the submit button is no longer disabled.

But if after, you select an image greater than 500KB, an error message is displayed and the submit button is back to its disabled state, preventing the user to submit the form (for example if the user changes his mind and no longer want to upload an image).
So you have to refresh the page and restart from the beginning

Is it a feature? 

I would say that as long as attaching a file is no required, any validation rule on a selected file should not change the form state.

Do you know any workaround?

Thanks

**Comment by danialfarid** [comment]
You can have a remove button to remove the invalid file. If there is a validation on the file and a file is selected the form should be invalid unless the file is removed.

**Comment by PsyStorm25** [comment]
Thank you for your reply.

I tried the following to remove the invalid files but with no success (the submit button remains disabled):
`    $scope.removeInvalidFile = function(file){`
`      var index = $scope.$invalidFiles.indexOf(file);`
`      if (index >= 0)`
`        $scope.$invalidFiles.splice(index, 1);    `
`    }`

Here is the jsfiddle updated: [http://jsfiddle.net/hbvsLstm/11/](http://jsfiddle.net/hbvsLstm/11/)

Would you have any suggestion?

**Comment by danialfarid** [comment]
You can use this: http://jsfiddle.net/hbvsLstm/12/ until I fix it.
There are errors in your code for uploading and showing progress on index but after you fix those the validation and removing files should work.
Basically you use `ng-model-options="{allowInvalid: true}" and manipulate the $scope.files array instead of invalidFiles.

**Comment by PsyStorm25** [comment]
Thank you for your suggestions, they were useful.

**Comment by danialfarid** [comment]
I am not gonna implement the ability to remove invalidModel because of complication and easy workaround. If you want to be able to remove files individually you need to have allowInvalid set and remove the files from the ng-model which would trigger the re-validations.
