### ISSUE TITLE
Drag and Drop background error

### ISSUE THREAD

**Issue by Luntegg** [danialfarid/ng-file-upload#1338]
I have ngf-drop element and inside this element directive https://github.com/fraywing/textAngular I can drop images in this textarea, it's work - files don't append to ngf and append to textarea. But ngf-drag-over-class stays on block forever. How I can fix this problem? Apparently drop event get textangular and ngf is always waiting.

**Comment by danialfarid** [comment]
Create a jsfiddle.

**Comment by Luntegg** [comment]
JSFiddle - https://jsfiddle.net/wf7zzzpa/12/
You should add a picture to textarea. Image will be appended to textarea and background will remain in place.

**Comment by danialfarid** [comment]
It doesn't seem to work, when i drop a jpg image nothing happens and the green border will be cleared after drop. How to reproduce it?

**Comment by Luntegg** [comment]
First step - https://yadi.sk/i/-s8nFl8vodN7p
We have empty textarea. After this I drop image to textarea (which is also drag-and-drop), not to drag-and-drop div.
And in the end we have - https://yadi.sk/i/dUeqZWwoodNSq
I can write everything in textarea - https://yadi.sk/i/YKJdfyLTodNed
And background stays in place.

**Comment by danialfarid** [comment]
Put the text area outside the ngf-drop div if you don't want it to be handled by ngf-drop.

**Comment by Luntegg** [comment]
But I need the textarea was inside the ngf.. Is there any chance to check for target?

**Comment by danialfarid** [comment]
Why would you need it inside ngf?

**Comment by Luntegg** [comment]
I have a message box where I can specify the recipients, the textarea with the message  and input file for files. I also wanted to attach files to the message, simply by dragging them to block, at any place. Everything works except the background. Files attached to the form, if I drag them to the block. Inserted in the textarea if I drag them there. But the background remains.

**Comment by danialfarid** [comment]
It doesn't fire the ngf-drop if you drop it in the textarea, seems like textAngular is eating the drop event.
