### ISSUE TITLE
ngf-max-files not working when ngf-multiple="true" and  ngf-keep="true"

### ISSUE THREAD

**Issue by lvendramini** [danialfarid/ng-file-upload#1342]
The ngf-max-files does not seem to work when the user can upload multiple files and when new files are appended to the existing list.    

For example
- ngf-max-files="10"
- ngf-keep="true"
- upload 8 images (works)
- upload 3 images (allows all 3 to be uploaded but should not)

**Comment by danialfarid** [comment]
Fixed at 12.0.1
