### ISSUE TITLE
$watch inside ui bootstrap tabs not working

### ISSUE THREAD

**Issue by comapedrosa** [danialfarid/ng-file-upload#1343]
Hi all!

I am having an issue with the _Drop and upload with $watch_ example http://jsfiddle.net/danialfarid/s8kc7wg0/400/ everything works fine if I use it in the normal way but when I put it inside ui boostrap tabs https://angular-ui.github.io/bootstrap/#/tabs the upload function is not triggering, as if the $watch wasn't actualy watching the files.

Here is the code which is working in the normal way but not inside ui boostrap tabs...!

```
  $scope.$watch('files', function () {
      $scope.upload($scope.files);
  });
  $scope.upload = function (files) {
    console.log("trigger")
  };
```

Hope you can help me!

Thx for this awesome project!

**Comment by danialfarid** [comment]
You can use a controller scope function for `ngf-change="filesSelected($files)` as an alternative.

**Comment by comapedrosa** [comment]
Thank you very much @danialfarid works like a charm! 
I used `ngf-change="upload($files)"` and is triggering when it has to!
Congratulations for the awesome work you are doing! Keep it up! :+1:
