### ISSUE TITLE
File size limit is not inclusive

### ISSUE THREAD

**Issue by shanezheng** [danialfarid/ng-file-upload#1344]
When I set the file upload size, I set to 200MB (which is in theory 209715200B), but we notice that if I upload a file with 199MB size (209715100B), it fails.

I think there are two problems:
1. The size calculation is not using 1024, but 1000. Not very accurate.
2: The size limit should be inclusive, i.e. if I set 200MB, I should be able to load 200MB file, but not 201MB (which is 1024*1024*210 = 210763776B).

**Comment by danialfarid** [comment]
Fixed at 12.0.1
