### ISSUE TITLE
Dynamic ngf-resize

### ISSUE THREAD

**Issue by rkusuma** [danialfarid/ng-file-upload#1345]
Hi @danialfarid ,

Can i construct ngf-resize object dynamically? For example:
if the original image width greater than 1000px i want to use `{width: 1000, quality: .8, restoreExif: false}`
else `{quality: .8, restoreExif: false}`

Thank You

**Comment by danialfarid** [comment]
No, Use `Upload.resize(file).then()` instead before uploading.

**Comment by danialfarid** [comment]
Feature added to 12.0.3. `ngf-resize` can return a promise that resolves to the resize options.

**Comment by chanusukarno** [comment]
Can please provide an example of usage?
