### ISSUE TITLE
Hello IE9 issue 

### ISSUE THREAD

**Issue by perentti** [danialfarid/ng-file-upload#1346]
Hello danial,
I hope your fine, i use  your module ng file upload and i find some little issue:
When the documend is load the flash element is activated on the file form but we make the scroll the element flash is desappear on the file form.
After checking i see that the flash element is fix when we scroll
Could please help me on this issue
Thank you, sorry for my bad english
Best regards

**Comment by danialfarid** [comment]
What the issue is?
