### ISSUE TITLE
Retrieve local full path

### ISSUE THREAD

**Issue by frlinw** [danialfarid/ng-file-upload#1348]
Hello,

I'm building an offline mode for my app and I need to store images.

BUT !

I'm working in localStorage and there is a lil quota... I can't add all stringified files into it

SO !

Is it possible to retreive (and store in localStorage) fullpath of the selected file instead of retrieve the file itself ?

When the connection is back, my SYNC function will be able to upload all files with their path, everything will be fine and the localStorage will love me.

Thanks!

**Comment by danialfarid** [comment]
You cannot access the selected file programmatically later and the browser does not provide the full path because of the security concerns.

**Comment by frlinw** [comment]
Thanks for your answer, is there a way to store a "shortcut" of the file during offline time and proceed to a real upload when the connection is back ?

**Comment by danialfarid** [comment]
You can use html5 FileSystem to store the file locally for browser: http://stackoverflow.com/questions/4940586/can-you-use-html5-local-storage-to-store-a-file-if-not-how
but otherwise you need to store the whole file's content in localStorage.
