### ISSUE TITLE
ngf-drop and ngf-accept issue

### ISSUE THREAD

**Issue by m2omou** [danialfarid/ng-file-upload#1350]
It looks like that the `ngf-accept` doesn't work with `ngf-drop` ?  For example, when I drop a pdf file, it still accept it. I only want to be able to drop images. Any ideas ?

ps: `ngf-accept` is working fine with `ngf-select`

```html
<div ngf-accept="'image/*'" ngf-drop="upload_files($files, $invalidFiles)" ngf-multiple="true">
</div>
```

**Comment by danialfarid** [comment]
ngf-accept is only for ngf-select.

**Comment by m2omou** [comment]
@danialfarid Oh I see, is there any way to tell drop to only accept images ? thanks

**Comment by danialfarid** [comment]
ngf-pattern
