### ISSUE TITLE
Field order when doing multipart upload

### ISSUE THREAD

**Issue by tayste5000** [danialfarid/ng-file-upload#1353]
So I have noticed that, when uploading text and a file together, the ordering in the multipart request body is based off of the ordering in the JS object, so if I have '{foo: bar, file: somefile}' and '{file: somefile, foo: bar}' I will have two different requests with opposite ordering. I feel like this is a bit of an issue for two reasons:

-javascript doesn't guarantee preservation of object order, so if you're doing some manipulation of the data object before sending the request you may not get the ordering you expected

-some body parsers will ignore any text fields if they are below a file in a multipart request

Maybe this doesn't warrant any updates but I feel like it should at least be mentioned in the docs...

**Comment by danialfarid** [comment]
That sounds like a bug in those body parsers. The order of the multipart form data should not matter.
