### ISSUE TITLE
disable dragging image from browser

### ISSUE THREAD

**Issue by m2omou** [danialfarid/ng-file-upload#1354]
When I try to drag an image from my website to the drop zone it will trigger `ngf-drag`.

Is it possible to `ngf-drag` only detect the files coming from the desktop and not the images from the browser ? Thanks

**Comment by danialfarid** [comment]
`ngf-model-option="{updateOn: 'select drop'}"` if you don't add dropUrl it won't update on image drop from browser.

**Comment by m2omou** [comment]
Hi @danialfarid,

This is what I have so far, and `ngf-drag` is still called when dragging an image from the browser. 

Am I doing something wrong ? here is the html

```html
        <div ngf-model-option="{updateOn: 'select drop'}" ngf-drop="upload_files($files, $invalidFiles)" ngf-drag="drag_upload($isDragging, $class, $event)"  ngf-multiple="true"></div>
```

thanks

**Comment by m2omou** [comment]
By the way I am using chrome.

**Comment by danialfarid** [comment]
it is `ng-model-options`

**Comment by m2omou** [comment]
@danialfarid I also tried `ng-model-options` and still able to drag images from the browser. What is strange is that I copied the exact code from that fiddle `http://jsfiddle.net/danialfarid/s8kc7wg0/400/` and still having the same problem, but in the fiddle it works fine... any idea ?

**Comment by danialfarid** [comment]
Create a jsfiddle! you probably have a typo
