### ISSUE TITLE
ngf-thumbnail Hyperlink

### ISSUE THREAD

**Issue by zaryk** [danialfarid/ng-file-upload#1355]
would ya'll add something for hyperlink so that it populates "href" with the thumbnail link.  I am previewing the uploaded files, but also want to include lightbox, which seems to require a link.   Pretty much all I did for now is check if the element is a hyperlink, and set the href.  There is probably a better solution, but it is late.  Then I can use ngf-thumbnail on the hyperlink.

> function linkFileDirective(Upload, $timeout, scope, elem, attr, directiveName, resizeParams, isBackground) {
>     function constructDataUrl(file) {
>       var disallowObjectUrl = Upload.attrGetter('ngfNoObjectUrl', attr, scope);
>       Upload.dataUrl(file, disallowObjectUrl)['finally'](function () {
>         $timeout(function () {
>           var src = (disallowObjectUrl ? file.$ngfDataUrl : file.$ngfBlobUrl) || file.$ngfDataUrl;
>           if (isBackground) {
>             elem.css('background-image', 'url(\'' + (src || '') + '\')');
>           } else {
>               if (elem.is("a")) {
>                   elem.attr('href', src)
>               }
>               else {
>                   elem.attr('src', src);
>               }
>             elem.attr('src', src);
>           }
>           if (src) {
>             elem.removeClass('ng-hide');
>           } else {
>             elem.addClass('ng-hide');
>           }
>         });
>       });
>     }

**Comment by danialfarid** [comment]
You can use `Upload.dataUrl(file).then()` for now to get the url of the file and set it to a model for href.

**Comment by zaryk** [comment]
I suppose that would work, but what I failed to mention is that I am updating all the files at once on submit button, so the success event won't be fired until after it has returned from that call, but by then I will have moved to another page.  The preview and lightbox is for reviewing the images before they have been submitted.  I also looked at the progress event, but the dataurl looks to be the base64 representation.

**Comment by danialfarid** [comment]
You can use Upload.dataUrl before uploading the file, right after file selection or on model change.

**Comment by zaryk** [comment]
Thanks!  I used ng-href and grabbed the ngfDataUrl.  I was also mistaken that the lightbox didn't do base64 rep., but I guess that was my fault and bad copy/paste when testing it.  Thanks for the help and advice.

**Comment by danialfarid** [comment]
`$ngfDataUrl` is just for internal use and might be removed in later versions.

**Comment by danialfarid** [comment]
You can use ngfDataUrl filter though.

**Comment by danialfarid** [comment]
The way to go about this is to use the filter  `<a href="files | ngfDataUrl">...`
