### ISSUE TITLE
File upload not functioning in Firefox on Mac

### ISSUE THREAD

**Issue by jester12345** [danialfarid/ng-file-upload#1356]
I've been trying to solve a bug in our code base, and noticed that your demos all have the same problem - Firefox on the Mac simply doesn't work. Click and nothing happens. I have Firefox 44.0.2, but was also testing with 43.something with the same issue. Firefox on Windows works fine, this is just a Mac issue.

If there is anything I can do to assist with solving this, I'm happy to help. Best I can tell, the click event is getting eaten.

**Comment by danialfarid** [comment]
It could be a plugin on your firefox that causes this, disable plugins, etc.

**Comment by jester12345** [comment]
Argh! You are absolutely right! I had installed a pop-up blocker plug-in to see what happens on our site when pop-ups don't work. It was apparently blocking file fields as well. I'm so sorry for the false report. Thanks for your insightful reply!
