### ISSUE TITLE
how i do for avoid the reload of the image?

### ISSUE THREAD

**Issue by Yording** [danialfarid/ng-file-upload#1357]
hi, 
I'm trying to avoid the image disappears 
Pressing again on the input file,please
¿any idea how to do?

```
form name="myForm">
    <fieldset>
      <legend>Upload on form submit</legend>
      Username:
      <input type="text" name="userName" ng-model="username" size="31" required>
      <i ng-show="myForm.userName.$error.required">*required</i>
      <br>Photo:
      <input type="file" ngf-select ng-model="picFile" name="file"    
             accept="image/*" ngf-max-size="2MB" required
             ngf-model-invalid="errorFiles">
      <i ng-show="myForm.file.$error.required">*required</i><br>
      <i ng-show="myForm.file.$error.maxSize">File too large 
          {{errorFiles[0].size / 1000000|number:1}}MB: max 2M</i>
      <img ng-show="myForm.file.$valid" ngf-thumbnail="picFile" class="thumb"> <button ng-click="picFile = null" ng-show="picFile">Remove</button>
```

**Comment by danialfarid** [comment]
Why do you want that?
You can have ng-model-options="{updateOn: 'select'}" but that will not behave the same cross browser. Chrome by default empties the file input when you click and cancel.

**Comment by Yording** [comment]
hi, thanks for response.
I do it to give a better presentation to the end user,
because I 'm making an example of user settings and in this update the profile picture.
if the user does not select any image after pressing the input file,the picture disappears.This ruins the performance for the User.

I will try your solution.

**Comment by Yording** [comment]
thanks for you help, 
I solved in the following manner. 
I create another tag <img> 
with a condition, if the image is null shows the default image.
```
<div class="form-group text-center">
          <img  class="img-thumbnail user-profile-picture" ngf-thumbnail="imageFile">
          <img ng-if="!imageFile" class="img-thumbnail user-profile-picture" ngf-thumbnail="imageFile=user().profileImageURL">
        </div>

```

**Comment by danialfarid** [comment]
You can just have
` <img  class="img-thumbnail user-profile-picture" ngf-thumbnail="imageFile || user().profileImageURL">`

**Comment by Yording** [comment]
thanks for correction
