### ISSUE TITLE
Add To Documentation/Readme About The Hidden Input And How To Get It

### ISSUE THREAD

**Issue by opticyclic** [danialfarid/ng-file-upload#1358]
Since the hidden input element gets added to the end of the page I didn't realise it even existed at first.

After finding out about it I spent quite some time trying to access it until I found issue [1167](https://github.com/danialfarid/ng-file-upload/issues/1167)

Can you add these (quite important) nuggets to the Readme please.

**Comment by danialfarid** [comment]
Why do you care about the hidden inputs?

**Comment by opticyclic** [comment]
It seems to be the only way to automate the file uploads when testing with Selenium and PhantomJS.
