### ISSUE TITLE
An error occured when using resize and applyExifRotation function if the image uploaded is too large

### ISSUE THREAD

**Issue by zuolei828** [danialfarid/ng-file-upload#1360]
Thanks for your work and share! 

I used the Upload.resize and Upload.applyExifRotation function for my mobile app, and I found that when the image uploaded is too large, the HTML5 canvas drawImage function will not work right. Then the canvas toDataUrl will return only a 'data,;' string, so the upload.dataUrltoBlob function will throw an error.

It seems to be a memory problem, but I think you should catch the error and reject the promise. Here is your code:

    var deferred = $q.defer();
    upload.dataUrl(file, true).then(function (url) {
      resize(url, width, height, quality, type || file.type, ratio, centerCrop, resizeIf)
        .then(function (dataUrl) {
          if (file.type === 'image/jpeg' && restoreExif) {
            try {
              dataUrl = upload.restoreExif(url, dataUrl);
            } catch (e) {
              setTimeout(function () {throw e;}, 1);
            }    
          }    
          deferred.resolve(upload.dataUrltoBlob(dataUrl, file.name, file.size));
        }, function (r) {
          if (r === 'resizeIf') {
            deferred.resolve(file);
          }    
          deferred.reject();
        });  
    }, function () { 
      deferred.reject();
    });  
    return deferred.promise;

And I think it is better to change to the blow code:

         try {
              var blob = upload.dataUrltoBlob(dataUrl, file.name, file.size);
          } catch (e) {
              deferred.reject();
          }
          deferred.resolve(blob);

**Comment by danialfarid** [comment]
Fixed at 12.0.3
