### ISSUE TITLE
is there any method in ng-file-upload.js that make the attachment must filled?

### ISSUE THREAD

**Issue by FadliKun** [danialfarid/ng-file-upload#1362]
excusme mr farid, sorry for disturbing you may i ask some question about ng-file-upload,
i have a form for submit the data of "payment", there is a field for attachment the receipt_img, which is used for optional upload..

is there any method in ng-file-upload.js that make the attachment proccess not work  if the attachment is null?,

i'm using rails in backend(use paperclip for attachment file), i've used any of paperclip ways to make it not required, but it's doesn't work..

oh ya, i'm using angular in frontend, so i use this plugin as a bridge between angular, rails and s3 amazon..

best regards, Auliya

**Comment by danialfarid** [comment]
You can use form validation and add ng-required to the input file.

**Comment by FadliKun** [comment]
i've set ng-required="false"  in my input file, but it's still doesn't work..

the error shown "unprocessable entity"..

it's my stackoverflow sir, 

http://stackoverflow.com/questions/35447648/how-to-make-an-optional-attachment-in-rails-using-paperclip-angular-js-ng-file

sorry for redirect this to stackoverflow...

**Comment by FadliKun** [comment]
oh Alhamdulillah god, it's solved by myself after headche for a day..

after tried many ways of references, but no one worked at all, i'm solved it by creating a condition in my service (payment.coffee), so the service look like this :

```
Sprangular.service "Payment", ($http, $q, _, Env, Account, Cart, Flash, Upload) ->

  service =

confirmPaymentBankTransfer: (order, payment, bankTransfer) ->
  if bankTransfer.receipt_img is null
    params =
      payment:
        bank_name: bankTransfer.bank_name
        deposited_on: bankTransfer.deposited_on
        account_name: bankTransfer.account_name
        account_no: bankTransfer.account_no
        transaction_reference_no: bankTransfer.transaction_reference_no

    config =
      ignoreLoadingIndicator: true
      headers:
        'X-Spree-Order-Token': order.token

    url = Spree.mountedAt() + "/api/orders/#{order.number}/payments/#{payment.id}"

    $http.put(url, $.param(params), config)
      .success (response) ->
        Flash.success 'app.account_updated'
      .error (response) ->
        Flash.error 'app.account_update_failed'

  else
    url = Spree.mountedAt() + "/api/orders/#{order.number}/payments/#{payment.id}"

    bankTransfer.receipt_img.upload = Upload.upload
      url: url
      method: 'PUT'
      headers:
        'X-Spree-Order-Token': order.token
      data:
        payment:
          receipt_img: bankTransfer.receipt_img
          bank_name: bankTransfer.bank_name
          deposited_on: bankTransfer.deposited_on
          account_name: bankTransfer.account_name
          account_no: bankTransfer.account_no
          transaction_reference_no: bankTransfer.transaction_reference_no
          our_bank_name: bankTransfer.our_bank_name  

    # $http.put(url, $.param(params), config)
    #   .success (response) ->
    #     Flash.success 'app.account_updated'
    #   .error (response) ->
    #     Flash.error 'app.account_update_failed'

  service
```

so i put the if else condition on the function,. it's look a little dirty, but it's work fine for me..

thx for help..

thanks you very much for the awesome plugin mr farid...
