### ISSUE TITLE
Validate only last files when ngf-keep set to true

### ISSUE THREAD

**Issue by madurapa** [danialfarid/ng-file-upload#1364]
HI @danialfarid 

#1007 the same issue is still there, I'm using 12.0.1 Please check.

Here is the code:

`<div class="btn vd_btn vd_bg-grey" ngf-pattern="'.pdf,.doc,.docx,.xls,.xlsx,.txt,.rtf,.jpg,.jpeg,.png,.gif'" ngf-accept="'.pdf,.doc,.docx,.xls,.xlsx,.txt,.rtf,.jpg,.jpeg,.png,.gif'" name="files" ngf-model-invalid="invalidFiles" ngf-select ng-model="files" ngf-multiple="true" ngf-keep="'distinct'" ngf-max-size="2MB">
            <i class="fa fa-files-o"></i> &nbsp; Attach Files
        </div>`

Thanks

**Comment by danialfarid** [comment]
Comment on the original issue.

**Comment by madurapa** [comment]
Sorry Danial, my mistake.
