### ISSUE TITLE
When I cancel to select a file to upload, some questions!

### ISSUE THREAD

**Issue by Zhang-Yida** [danialfarid/ng-file-upload#1373]
Now I click select button, but I do not want to select a file and click cancel button, the original file has been deleted, how can I keep original file when I cancel to select a file?

**Comment by YuvPrime** [comment]
+ 1

**Comment by danialfarid** [comment]
You can have `ng-model-options="{updateOn:'select drop dropUrl'}" this will exclude click from resetting the model.

**Comment by Zhang-Yida** [comment]
@YuvPrime 
<button class="btn btn-primary" ngf-accept="'image/*'" ngf-select ng-model="file" ngf-keep="distinct">
select</button>

it does not solve my issue...

**Comment by Hirbod** [comment]
put distinct inside of ''

```
ngf-keep="'distinct'" 
```

or it will be considered as an boolean
