### ISSUE TITLE
Upload progress is always returning 100% even before upload is finish

### ISSUE THREAD

**Issue by pgamilde** [danialfarid/ng-file-upload#1374]
Hi,

My progress event handler is always giving me a 100% even if the request is not yet finish.

Here is my sample code:

    Upload.upload({
        url: 'upload_url',
        data: {file: file},
        method: 'POST'
    }).then(function (resp) {
        // success 
    }, function (error) {
        // error
    }, function(e){
       var progress = Math.min(100, parseInt(100.0 * e.loaded / e.total)); // this always give me 100
    });

**Comment by danialfarid** [comment]
Can you create steps to reproduce with a jsfiddle?
