### ISSUE TITLE
Add response Interceptor to ng-file-upload

### ISSUE THREAD

**Issue by slimovic** [danialfarid/ng-file-upload#1376]
Hello there,

Is there a way to add a response interceptor like **[restangular](https://github.com/mgonto/restangular#addresponseinterceptor)**?

The main purpose is to use tokens, and this way I can get i from the server and apply it in the default headers in your Directive, like this:

```javascript
Upload.upload({
	url: url,
	file: file,
	data: data,
	headers: {
		Token: interceptedToken
	}
})
```

**Comment by danialfarid** [comment]
Use angular transformResponse function.

**Comment by slimovic** [comment]
The problem I want to get the token from the server and apply it in the headers, the equivalent in  Restangular, something like that:

```javascript
RestangularProvider.setFullResponse(true); // to have a full reponse
Restangular.setResponseInterceptor(function (data, operation, what, url, response) {
  //restangularize data, operation, what, url, response
  var token = response.headers('Token-From-Server');
  RestangularProvider.setDefaultHeaders({ MyToken: token });
  return restangularizedResponse
});
```

**Comment by danialfarid** [comment]
You can use any library or just angular $http to get the header token, and then set it for `Upload.upload()` calls.
