### ISSUE TITLE
IE9 Upload

### ISSUE THREAD

**Issue by AlexandreKilian** [danialfarid/ng-file-upload#1378]
Hi,
I came across this issue and I can't explain it: in IE9 (with FileAPI active and all), the Upload doesn't send the correct body. Instead of a normal body, I get 

> -----------------------------7e030a112015a--

FileAPI is working, when I log the $file before Upload.upload($file), i get all the information I'd expect like filename, filesize, flashid. But when I try to execute "Upload", the file istn't being sent to the server.

Any idea what this could be? Getting pretty desperate

**Comment by danialfarid** [comment]
The file is being sent using flash so you won't be seeing the request in the browser's network tab. You can monitor your local network and find the request.

**Comment by AlexandreKilian** [comment]
how/where is the file being sent? in my backend, the request is empty when I do
`Upload.upload({
            url: '/upload',
            method: 'POST',
            data:{file:$file},
            sendFieldsAs: 'form',
            objectKey: 'file'`

and the same as #1380 when I do
`  Upload.upload({
            url: '/upload',
            method: 'POST',
            data:$file,`

**Comment by danialfarid** [comment]
That is probably your backend code that you are not retrieving the file properly.
Create a jsfiddle if you want me to investigate further and also remove the sendFieldAs and objectKey options, they are not necessary.
The second line is wrong , data should be an object containing the file not the file itself.
