### ISSUE TITLE
IE9 Upload and FileAPI

### ISSUE THREAD

**Issue by CamilleTh** [danialfarid/ng-file-upload#1380]
Hi Everyone, 

I have an issue on the upload feature on ie9

The context : 
Front  : Angular js 
Back :  JAVA EE

The front side send the file with a REST post service, everything it's ok on IE 10, chrome, etc
I have added the FileAPI files (js + flash) to allow ie9 to manage file thanks to flash
The problem is when i try to get the inputstream on java side 

There is the code : 

`

	@POST
	@Path("/add/crs/{IdSuivi}")
	@Consumes(MediaType.MULTIPART_FORM_DATA)
	@Produces(MediaType.APPLICATION_JSON + ";charset=utf-8")
	public Response addDocument(InputStream uploadedInputStream, @PathParam("IdSuivi") int IdSuivi,  @QueryParam("filename") String filename){
		Gson gson = new Gson();
		JsonParser parser = new JsonParser();
		try{
			byte[] bytes = IOUtils.toByteArray(uploadedInputStream);
                        ...
		} catch (IOException tfe) {
                       ...
		}
`

**My problem is that on IE9, the inputstream contains the object flash file : 
{flashId: "fileapi14563029716892", id: "1456303002854801", name: "test.txt", size: 31, type: "text/plain"}
instead of the file content**

Angular js code :

"file" represent the Object send by the ng-file-upload library
```
this.upload = function (file) {

	uploadDoc(file, file.name, self.trackingFile.idTracking )
	.success(function(res){
           ....
	})
	.error(function(error, status){
          .....
	});
}
	
this.uploadDoc = function uploadDoc(file,filename,idSuivi) {

var url = baseUrl + urls.addDoc + "/" + idSuivi;
  var req = {
	method: 'POST',
	url: url,
	headers: {
		'Content-Type': 'multipart/form-data'
	},
	params: {'filename': filename},
	data : file	
  }	 

   return $http(req);	
}
```

**Comment by danialfarid** [comment]
Can you create a jsfiddle for your js code part

**Comment by danialfarid** [comment]
Change it to `{..., data: {file: file}}` it should be an object containing the file not the file itself. Also remove the content-type header.
Follow the jsfiddle or demo code.
