### ISSUE TITLE
Cannot override the file input names used in the http request

### ISSUE THREAD

**Issue by hammady** [danialfarid/ng-file-upload#1381]
Whatever I do to the <input> field the form names sent are files[0], files[1], ...
This complicates the backend. I want to override this name to be simply: myfiles, myfiles, ... (same).
Tried setting name="myfiles" but with no luck.

**Comment by danialfarid** [comment]
`arrayKey: ''` read the docs

**Comment by hammady** [comment]
@danialfarid thank you for your quick reply. That fixed my problem :)
btw the documentation needs more effort to make it easier to reach the information without having to read it in full.
