### ISSUE TITLE
Callback called twice after upload + click on upload again before selecting file

### ISSUE THREAD

**Issue by dlarr** [danialfarid/ng-file-upload#1383]
Hello, 

I am using this library for upload file use case. By the way thank you so much : very nice job.

Concerning the topic : When I upload one or several files to server everything is fine, but when I try to send another file, as soon as I clicked on the select file button(before I select other files), the .then() callback function is called again.

Here is my HTML :
```html
    <button class="btn btn-primary btn-icon waves-effect waves-circle" 
        ngf-select="uploadFiles($files, $invalidFiles)" 
        multiple 
        ngf-max-height="1000" 
        ngf-max-size="1MB">
    </button>
```

And now the controller.js part
(be aware I keep separated Database file management, so fichiersJointsUploadTab is meant for DTO object tracking)

```javascript
    $scope.uploadFiles = function(files, errFiles) {
      $scope.files = files;
      $scope.errFiles = errFiles;
      var fichiersJointsUpload = [];
	
        angular.forEach(files, function(file) {
            var fichierJoint={
                dossier: $scope.dossier,
                url: file.name
            }
            fichiersJointsUpload.push(fichierJoint);
        });
	
        var formData=new FormData();
        formData.append('fichiersJoints', angular.toJson(fichiersJointsUpload,true));
        formData.append('files', files);
	
        Upload.upload({
            url: serverUploadUrl,
            data: {
                 fichiersJoints : angular.toJson(fichiersJointsUpload,true),
                 files: files
            }
        }).then(function (resp) {
                //Alert window
                growlService.growl("Le fichier a été rajouté au dossier" , 'success');
		
                // Update available file list
                Restangular.all(URL).getList().then(function(data) {
                        if (data!=null){
                              $scope.fichiersJoints = data;
                        }
                });
        }, function (resp) {
                growlService.growl("Un problème a eu lieu pendant l'ajout du fichier : "+ resp.status , 'error');
        });
    }
```

Thank you for any answer you come with.

Best regards,
Deunz.

**Comment by danialfarid** [comment]
That's expected behaviour there are lots of other similar issues and notes in the docs about it.

**Comment by danialfarid** [comment]
Check for file is null before upload

**Comment by dlarr** [comment]
Ok sorry about it ! And thank you so much for answering.

Best regards,
Deunz

**Comment by dlarr** [comment]
Following your advice and I got rid of my unwanted behaviour:

    if(files!=null && files.length>0){
        Upload.upload({
             url: serverUploadUrl,
             data: {
                    fichiersJoints : angular.toJson(fichiersJointsUpload,true),
                    files: files
             }
	}).then(function (resp) {
                // Do success callback actions

        }, function (resp) {
                // Do error callback actions
	        });
    }

Thank you very much.

**Comment by feimosi** [comment]
@danialfarid what's the exact reason for keeping this behaviour, if I may ask? Wouldn't it be easier to add an additional method like `ngf-clear` ? I find it, in most use cases people need only a selected file, currently it's misleading.

**Comment by danialfarid** [comment]
@feimosi https://github.com/danialfarid/ng-file-upload/issues/558#issuecomment-73891405 and more explanations in older issues just search for expected behaviour in the issues.
