### ISSUE TITLE
ngf-select button function triggering when it shouldn't

### ISSUE THREAD

**Issue by kas84** [danialfarid/ng-file-upload#1385]
When using ngf-select to upload a file right after it's selected the function it's been called too many times, even when initializing the component.

I noticed on load it's been called 3 times on angular 1.2.x and 5 times on angular.1.5.x.

```<div class="btn btn-default" ngf-select="uploadPicture() " ngf-max-files="1" ngf-pattern="'.jpg'">Upload on file select</div>```

And the function:

```  var i=0;
    $scope.uploadPicture=function(file,level){
        console.log("going to upload file",++i);
    };```

**Comment by danialfarid** [comment]
It will be called each time it is compiled to set the value to null..
Also latest version should have less calls maybe you are using an older version.
You need to check for null before uploading as you see in the examples.
