### ISSUE TITLE
file: Upload.dataUrltoBlob(dataUrl, picFile.name) -- file size does not get smaller.

### ISSUE THREAD

**Issue by philipfwilson** [danialfarid/ng-file-upload#1390]
Hi,

Thanks for your hard work. I have a question on a issue I have been working on for days. 

http://stackoverflow.com/questions/35679570/nodejs-write-simple-image-blob-upload-dataurltoblob

I posted my answer here but it is not really working. 

1. I noticed that the file is zooming in on what is selected with 
data: {
  file: Upload.dataUrltoBlob(dataUrl, picFile.name)
},

but the file size does not go down from the original size. 

2. After I write the file out with the following it works in chrome but I can't open the file in gimp. Gimp gives me an error.

router.post('/user/uploads', function (req, res){
    var form = new formidable.IncomingForm();
    form.parse(req, function(err, fields, files) {
        res.writeHead(200, {'content-type': 'text/plain'});
        res.write('received upload:\n\n');
        res.end(util.inspect({fields: fields, files: files}));
    });

    form.on('end', function(fields, files) {
        /* Temporary location of our uploaded file */
        var temp_path = this.openedFiles[0].path;
        /* The file name of the uploaded file */
        var file_name = this.openedFiles[0].name;
        /* Location where we want to copy the uploaded file */
        var new_location = "/Users/philipwilson/test_hold_files/";

        fs_extra.copy(temp_path, new_location + file_name, function(err) {
            if (err) {
                console.error(err);
            } else {
                console.log("success!")
            }
        });
    });
});

Any help is great. 

Thanks

**Comment by danialfarid** [comment]
Create a jsfiddle so i can verify the front-end code and why it is not resized.
