### ISSUE TITLE
chunked upload if using resumeSize instead of resumeSizeUrl

### ISSUE THREAD

**Issue by dethegeek** [danialfarid/ng-file-upload#1392]
Hi

I'm trying to make chunked uploads work with a php backend. If I use ```resumeSize``` I encountereed an issue and I think is related to ```config._end``` being not set. 

If I understand correctly, resumeSize shoud return a promise. This promise resolves to any custom way to tell  the uploaded file size to the module.

At time of writing this, the issue I encountereed seems to be linked below :

https://github.com/danialfarid/ng-file-upload/blob/master/src/upload.js#L135

Note : I workarounded by using ```resumeSizeUrl``` instead.

**Comment by danialfarid** [comment]
So what the issue is when you use resumeSize?

**Comment by btry** [comment]
Hi

The file is uploaded in a single chunk, and tu uploader sends it again and again in an endless loop.

I also noticed one of the passed values contains NaN instead of a number.

**Comment by danialfarid** [comment]
It could be that your resumeSize doesn't resolve to the correct value for the remaining of the file. For example if it resolves to 0 all the time it would start from position 0 over and over.

**Comment by danialfarid** [comment]
If you could create a jsfiddle would be easier to figure it out.

**Comment by kostko** [comment]
I can confirm this issue. The problem is that if `config.resumeSize` is used together with a chunked upload, then `config._end` is not set at all:

```javascript
 } else if (config.resumeSize) {
      config.resumeSize().then(function (size) {
        config._start = size;
        uploadWithAngular();
      }, function (e) {
        throw e;
      });
    }
```

As you see, `config._start` is set, but `config._end` is not. The above code should be modified to also do something like the following:
```javascript
if (config._chunkSize) {
  config._end = config._start + config._chunkSize;
}
```
