### ISSUE TITLE
Question-Multiupload Mobile: Can I access the whole Upload-Process by giving a Filelist

### ISSUE THREAD

**Issue by ElaHo** [danialfarid/ng-file-upload#1395]
Multiple-Upload does not work on mobile (old) Android, so I'm trying to pass Filelist from Cordova Imagepicker.

Is there any chance to do so? Where can i hook into ng-file-upload. Would be happy for advice, cause the plugin works really really great, i love it.

The Imagepicker gives an Array of Files like
"file:///sdcard/....jpg", 
"file:///sdcard/....jpg", etc.

Probably I have to add missed data to the array of files by myself (like size etc.), but where to attach?

**Comment by danialfarid** [comment]
If that is just a list of strings it should not work, you need the actual javascript File object to have the blob data attached to it.
