### ISSUE TITLE
Problem on IE9 with 11.1.1.

### ISSUE THREAD

**Issue by StephanieOSZ** [danialfarid/ng-file-upload#1396]
Hello, I'm having the same problem on IE9 with 11.1.1.
When I use Chrome or Firefox everything works fine, but using IE 9 appears the message :

ngFileUpload: Circular reference in config.data. Make sure specified data for Upload.upload() has no circular reference: file[blob][files][0]

I'm calling on page

//MODAL TO INPUT THE FILE

×
A3 Attachments

                    <div class="modal-body">
                        <div>
                            <input type="file" name="file" ngf-select="onFileSelect($file)" ng-model="file">
                            <span style="color:#FF0000;font-style:italic;font-size:10px;margin-top:10px;">*File size cannot exceed 15 MB</span>
                            <span style="color:#FF0000;font-style:italic;font-size:16px;">{{message}}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
//THIS IS MY ANGULAR FUNCTION
$scope.onFileSelect = function(file) {
$scope.upload = Upload.upload({
url: './model/uploadA3.php',
method: 'POST',
data: {file: file, id_plan: $scope.plan.cod}
}).success(function(data, status, headers, config) {
if(data == '1'){
$scope.message = "Error to send file, verify the type or size!";
}else if(data == '2'){
$scope.message = "Please don't use on the file name characters like % or #";
}else{
$http.get('./model/atachA3/'+$scope.cod)
.success(function(data) {
$scope.atachInfo = data;
$(data).each(function( i ) {
$scope.attachCount = i+1;
});
});
$('#addAtach').modal('hide');
$scope.message = "";
$scope.file='';
}

});

};

Thank you in advanced!!!

**Comment by danialfarid** [comment]
Upgrade to the latest version
