### ISSUE TITLE
$viewValue not set after the model is changed from outside

### ISSUE THREAD

**Issue by margru** [danialfarid/ng-file-upload#1397]
I have just upgraded from 6.2 to 12.0.1 and I noticed that when the ng-model value is updated from outside (e.g. a file is assigned to it by another function) or from the drag&drop area, the $viewValue is not updated or even reset (however, it worked fine in 6.2). Anyway, I am not sure if this is the reason for the following: 

If there is e.g. an angular "required" form field validation, it always fails even though the model indeed contains a file. The file has to be selected again using the `ngf-select` directive to update the $viewValue correctly.

For example, I have both `ngf-select` and `ngf-drop` directives, both pointing to the same ng-model, both required, both with the same validation object, both with the same "name" attribute so that the formName.fieldName can be used for managing errors via formName.fieldName.$error. But this is not working. I also tried to have the "name" attribute only in one of the directives but with the same result.

Am I missing something, is it a feature or is it a bug?

I created a jsfiddle where this is demonstrated (but the behavior is a little bit different). 
http://jsfiddle.net/mjLvp31m/2/
If you select a file via Select file button, you will get VALID indicator (if the file is not too big) but the "\*file required" indicator is still on. If you drop the file into the drag&drop area, you will get VALID indicator and the "\*file required" indicator will disappear.
If you select a file bigger than 2MB via the Select file button, you will not get the message "File too large" but if you do the same via the drop area, you will get that message.

How to make sure that these 2 directives work together?

Thanks.

**Comment by danialfarid** [comment]
You have two inputs in the form with the same "name" attribute which is why it acts not as expected. Add a different name for the div and check that both errors exists for showing required.
