### ISSUE TITLE
clarification on use of ngf data url

### ISSUE THREAD

**Issue by deckikwok** [danialfarid/ng-file-upload#1398]
read that $ngfDataUrl is just for internal use

in the fiddle for ng-img-crop: http://jsfiddle.net/xxo3sk41/1/
an ngDataUrl filter was used. Are they the same thing? is this allowed?

Instead of using that service, is it all right to use base64DataUrl of Upload service instead?
I got the 'solution' from here:
http://stackoverflow.com/questions/35185600/having-problems-with-ngfdataurl-with-angular-ng-file-upload#

thanks

**Comment by danialfarid** [comment]
Those are different and ngfDataUrl should be removed from the jsfiddle.

**Comment by realappie** [comment]
@danialfarid Is there any substitute for it ? The image crop example [here](http://jsfiddle.net/danialfarid/xxo3sk41/590/) makes use of it.

**Comment by danialfarid** [comment]
@realappie Why would you need a substitute? You can use `base64DataUrl` in Upload service in your js.
