### ISSUE TITLE
ngf-min-width not working on mobile devices.

### ISSUE THREAD

**Issue by sameer1750** [danialfarid/ng-file-upload#1400]
Hello,
I am using validation ngf-min-width and ngf-min-height.
But the image is taking the width of the mobile instead of its original width and height.
is this a bug ?

**Comment by danialfarid** [comment]
I think there is a similar issue open

**Comment by danialfarid** [comment]
Could you try again with version 12.0.3. It could be fixed.

**Comment by Yrvaan** [comment]
Hi, I've tried with version 12.0.4 and this issue seems to be still there.
