### ISSUE TITLE
ng-file-upload gives error message twice

### ISSUE THREAD

**Issue by Sampath-Lokuge** [danialfarid/ng-file-upload#1401]
Hi,

**Html**

    <button ngf-select="vm.addPictures($files)" ngf-multiple="true" ngf-pattern="'.jpg,.png,.jpeg,.bmp'"
                            accept="image/*">
                        Select Files
                    </button>

**JS**

     //to add Pictures
       vm.addPictures = function ($files) {
              vm.upload = [];
              if ($files && $files.length) {
              //$files: an array of files selected, each file has name, size, and type
                  for (var i = 0; i < $files.length; i++) {
                          var $file = $files[i];
                            (function (index) {
                              vm.upload[index] = upload.upload({
                                 url: "/api/Picture/AddPictures",
                                 method: "POST",
                                 data: {},
                                        file: $file
                                    }).progress(function () {
                                    }).success(function (data) {
                                        vm.pictureList.push({
                                            id: vm.pictureList.length + 1,
                                            url: '/common/pictures/' + data.newImageName,
                                            note: '',
                                            isSelected: true,
                                        });

                                    }).error(function () {
                                    });
                                })(i);
                            }
                 } else {
      abp.message.error('Invalid file format', 'Error');//this is the error msg which it fires twice.
                 }
              };

**Question :** When user selects the wrong format it gives the error message as expected.But after that when user tries to select the image again by just pressing the "Select" button,It shows the same error message again even without selecting the image.Could you tell me how to fix this ? Thanks.

When I select a wrong file type,it looks like this...

**[Debug mode](http://i.imgur.com/RRB9shP.png)**

**Comment by danialfarid** [comment]
follow stackoverflow.

**Comment by Sampath-Lokuge** [comment]
@danialfarid Can you give me an example of how to handle `ngf-model-invalid` with the multiple File select ? I cannot use Angular form with the submit button.Thanks.

Please update the below mentioned fiddle and let me know the new url.

**[Fiddle](http://jsfiddle.net/sampath_lokuge/2vq88rfs/472/)**

**Comment by danialfarid** [comment]
The first fiddle and demo page are using ngf-model-invalid

**Comment by Sampath-Lokuge** [comment]
@danialfarid Yes,But it is with the form no ? I need to do it without the submit button.So how can I do that ? Thanks.

     <i ng-show="myForm.file.$error.required">*required</i><br>

**Comment by danialfarid** [comment]
replace it with `file.$error.required`

**Comment by Sampath-Lokuge** [comment]
@danialfarid Yes,We can use in-line messages as you mentioned above.But unfortunately we cannot use `Sweetalert` kind of popup messages with this api. I think it's a BUG on this api.I have created a Fiddle by using Doc's 2 fiddle.Please see the issue.Thanks. 

**Test case 1 :** Select the non `jpg` file from the popup.Then it will show the `Invalid File` alert box.That is fine.

**Test case 2 :** After that close the alert and try to open a file select box by using `Select File` button.Then simultaneously it will open an Alert box and the Image box.That is the BUG here.

Here is the Fiddle : **[Alert Bug On This Api](http://jsfiddle.net/sampath_lokuge/2vq88rfs/475/)**

**Comment by danialfarid** [comment]
@Sampath-Lokuge That's expected behaviour previous files will be reset and set to null upon clicking on the button. There are other issues and mentions in the docs about this.

**Comment by DmitryGonchar** [comment]
@danialfarid Where is this note in the docs (did not find it), and how to prevent this need of double clicking ?

**Comment by Sampath-Lokuge** [comment]
@DmitryGonchar https://github.com/danialfarid/ng-file-upload#file-select-and-drop and see the **validation** section.
