### ISSUE TITLE
Uploading in nodejs need to re arrange

### ISSUE THREAD

**Issue by modernduck** [danialfarid/ng-file-upload#1403]
Hi there from the example

 Upload.upload({
            url: 'upload/url',
            data: {file: file, 'username': $scope.username}
        })

This might not be a problem if you use it with other backend but with nodejs with multer this code won't work and you won't find any username in the req.body

So to fix this you need to change to

 Upload.upload({
            url: 'upload/url',
            data: {'username': $scope.username, file: file,}
        })

**Comment by danialfarid** [comment]
fixed
