### ISSUE TITLE
Multiple resize for each upload

### ISSUE THREAD

**Issue by damianobarbati** [danialfarid/ng-file-upload#1404]
Is there a way to resize the image to different sizes and then handle the upload of each?
It would be a great combo to allow the use of picturefill then.

**Comment by danialfarid** [comment]
Use `Upload.resize()` service.

**Comment by damianobarbati** [comment]
You mean the resize method on the Upload service right?
`Upload.resize(file, width, height, quality, type, ratio, centerCrop, resizeIf).then(function(resizedFile){...});`
Just found, I really thank you: great job.

**Comment by danialfarid** [comment]
yep
