### ISSUE TITLE
Image crop and upload example is broken

### ISSUE THREAD

**Issue by isupersid** [danialfarid/ng-file-upload#1406]
Hi,

The image crop and upload example at url: http://jsfiddle.net/xxo3sk41/580/
is broken. Can we please have a working example?

Thanks!

**Comment by danialfarid** [comment]
this is the correct link http://jsfiddle.net/xxo3sk41/1/

**Comment by danialfarid** [comment]
Fixed at 12.0.3

**Comment by vionemc** [comment]
It's broken again.
