### ISSUE TITLE
problem with xdomain

### ISSUE THREAD

**Issue by longdo0111** [danialfarid/ng-file-upload#1407]
Hi there, first thanks for your module upload-file.
I must to use xdomain.js for other operation, but when click "upload" button the error had shown: 
angular.js:11655 Error: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': 'function (xhr) {
          if (!xhr) return;
          config.__XHR = xhr;
          if (config.xhrFn) config.xhrFn(xhr);
          xhr.upload.addEventListener('progress', function (e) {
            e.config = config;
            notifyProgress(getNotifyEvent(e));
          }, false);
          //fix for firefox not firing upload progress end, also IE8-9
          xhr.upload.addEventListener('load', function (e) {
            if (e.lengthComputable) {
              e.config = config;
              notifyProgress(getNotifyEvent(e));
            }
          }, false);
        }' is not a valid HTTP header field value.
    at Error (native)
    at send (http://localhost:8282/xdomain.js:375:13)
    at process (http://localhost:8282/xdomain.js:386:16)

I see it conflict with xdomain and I cannot resolve it. Please help
This is jsfiddle : [link](https://jsfiddle.net/qL4L49q1/4/)
On jsfiddle, the error is different a little bit :

 angular.js:11655 SyntaxError: Unexpected token p
    at Object.parse (native)
    at fromJson (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.js:1072:14)
    at defaultHttpResponseTransform (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.js:8618:16)
    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.js:8703:12

**Comment by danialfarid** [comment]
There are similar issues with xdomain and workarounds available. Search for xdomain in the issues.
