### ISSUE TITLE
drag & drop problem for .doc files on chrome + windows

### ISSUE THREAD

**Issue by signalkuppe** [danialfarid/ng-file-upload#1408]
I can't drop .doc files only on chrome for windows
I'm using ngf-pattern to whitelist some mimetypes

`ngf-pattern="image/*,application/pdf,application/msword,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"`

I can drop a .doc file on every browser/OS (firefox for windows for example works fine, and also chrome on mac) but I cannot drop the same file on windows(7/10) + chrome (latest version)
I disabled all the chrome plugins, but same result.

**Comment by danialfarid** [comment]
If the browser doesn't report the file's mime-type you are out of luck. You could add filter for `.doc,.docx` etc to filter by file's extension.
