### ISSUE TITLE
Shimed Blob possible bug

### ISSUE THREAD

**Issue by iseeyou911** [danialfarid/ng-file-upload#1409]
Hello

>ng-file-upload-shim

`window.Blob = Blob = function (b) {
      return {
        data: b,
        __isFileAPIBlobShim: true
      };
    };`

The constructor will return instance of Object and not of Blob, even with new keyword. So the data props, created with Upload.jsonBlob, will always transorm with **addFieldToFormData** to 3 data fields: propName._ngfBlob, propName.data[0], propName.__isFileAPIBlobShim, and all the fields will send to server in multipart data.

It's looks like a bug because you have shimed **FormData.append** where you extract _data[0]_ from Blob in case if __isFileAPIBlobShim is true.

Another huge problem with flash-uploader, related to Blobs, is that props created with **jsonBlob**, isn't sent to server with right content-type (application/json) as mentioned in docs. And because of this server's marshallers can't parse the props automaticaly.

**Comment by danialfarid** [comment]
I don't think there is a way to convert json to blob in the old browsers and send it as a File with flash. So that feature would be for html5 only.

**Comment by iseeyou911** [comment]
You may send blob to flash and then manualy build multipart/form-data and set custom Content-Type to parts where it needed.

Shimed Blob constructor may looks like:

```
function Blob (data, options) {
   options = options || {};

   this.data = data;
   this.__isFileAPIBlobShim = true;
   this.type = options.type;
   this.size = options.size;
}
```

So when you call new Blob(...) it will be instanceOf Blob. 
So, then you may check in Flash app if param is Blob, and set content-type to related part of multipart request.

Example of building custom multipart/form-data with as3.
https://github.com/jonasmonnier/Multipart.as/blob/master/src/com/jonas/net/Multipart.as

**Comment by danialfarid** [comment]
This would require changing FileAPI shim or additional library for doing that just to support older browsers, there are higher priority issues, so it might take a while unless you are willing to contribute or provide a flash js and swf file that is able to do this or integrate it within [FileAPI](https://github.com/mailru/FileAPI)
