### ISSUE TITLE
meteor add danialfarid:ng-file-upload gives me Version 5.0.9

### ISSUE THREAD

**Issue by austin4perezident** [danialfarid/ng-file-upload#1410]
I removed the package and add the package again specifying version 12 for ng-file-upload but it gives me an error saying there is no such version. How can I get the latest package for ng-file-upload?

I have tried meteor add danialfarid:ng-file-upload@=12.0.0 but it says that no such version exists.

**Comment by danialfarid** [comment]
Use danialf:ng-file-upload. The other one is an obsolete package by unaccessible owner.
https://github.com/danialfarid/ng-file-upload/issues/880
