### ISSUE TITLE
angular file upload as ng-include in another module

### ISSUE THREAD

**Issue by ihamouda** [danialfarid/ng-file-upload#1412]
HI
I have angular-file-upload in a module by itself
then I include it in other modules using ng-include like this
```
<div class="row">
        <div ng-include="'app/uploadModule/views/upload.html'" ng-controller="UploadController"></div>
    </div>
```
my upload.hrml looks like this
```
<div>
    <div class="up-buttons" ng-show="upload">
        <div class="drop-box"
             ngf-drop
             ngf-select
             ng-model="files" 
             ngf-multiple="multiple"
             ngf-pattern="acceptedFiles"
             ngf-accept="acceptedMimes"
             ngf-drop-available="true"
             ngf-allow-dir="false"
             ngf-drag-over-class="dragover"
             ngf-model-invalid="invlideFiles(s)"
             ngf-max-files="20"
             ngf-max-size="15MB">
            <span ng-show="true">{{uploadMessage}}</span>
        </div>
        <div ngf-no-file-drop>File Drag/Drop is not supported for this browser</div>
    </div>
</div>
```
when I drop any files nothing gets dropped, and invalidFiles gives me
TypeError: $parse(...).assign is not a function

Any suggestions?

**Comment by danialfarid** [comment]
create a jsfiddle

**Comment by ihamouda** [comment]
https://plnkr.co/edit/W9Mct0dYulmI1FlXKfIu

**Comment by danialfarid** [comment]
That's a $scope.$watch() issue. If you add double curly bracket in your html for files and invalidFiles you will see that they have the expected values.
You can post it on SO for help since it is a general angular scope question.

**Comment by ihamouda** [comment]
these are models
I don't think I should add double curly for them
Thanks anyway

**Comment by danialfarid** [comment]
This is what i meant: https://plnkr.co/edit/lMlcn8soJ4n6YoOGnFDs?p=preview

**Comment by ihamouda** [comment]
Got you
now if you try to drop a JPG file, it shows the files empty array and the invalidFiles empty also.
so why do you think it is not picking it up?

Thanks for your help

**Comment by danialfarid** [comment]
files isn't empty. it is an object it just doesn't print it's properties, try files[0].name
