### ISSUE TITLE
Images gets corrupted if an array of image is uploaded to the server

### ISSUE THREAD

**Issue by khaled4vokalz** [danialfarid/ng-file-upload#1414]
@danial I am facing some problems while uploading an array of images to the server. As the upload procedure is async all my files becomes  corrupted as angular is sending one after another image to Web API before the first one's upload is completed... But when i upload only one image it works fine. do you have any suggestions?

**Comment by danial** [comment]
@khaled4vokalz I believe you meant to tag @danialfarid

**Comment by danialfarid** [comment]
Fix your server code or upload the next file inside the success function of the previous file.
something like
```
function uploadFile(i) {
Upload.upload(...).then(function() {uploadFile(i + 1);});
}
uploadFile(0);
```
