### ISSUE TITLE
Drag and drop file is not working

### ISSUE THREAD

**Issue by bnussey** [danialfarid/ng-file-upload#1418]
I'm trying to get drag and drop working for ng-file-upload and its not working whatsoever. Whenever I try and drag and drop an image on it, it registers as an active state, but it does not upload. Uploading works absolutely fine when selecting the file manually. I've updated to the latest version.

Here is the code:

```
     <div class="avatar-upload bg-cover" ngf-drop ngf-multiple="false" ng-disabled="avatar.isUploading" ngf-drag-over-class="'avatar-upload--drag-over'" ngf-select="avatar.uploadAvatar($file)" title="Upload picture" ngf-pattern="'image/*'"
        ngf-accept="'image/*'" resetOnClick="true" ngf-max-size="'5MB'" ngf-capture="'camera'" ng-style="avatar.isUploaded && {'background-image': 'url(' + avatar.avatarUrl + ')'}">
        </div>
```

Thanks!

**Comment by danialfarid** [comment]
add `ngf-drop`

**Comment by bnussey** [comment]
Hey @danialfarid thanks for getting back to me.. Appreciate the support and ng-file-upload. I do have ngf-drop in there and its still not working. Any ideas?

**Comment by ali-bugdayci** [comment]
You can check your fiddle. It is not working on the latest version of google chrome:  Google Chrome Version 49.0.2623.87 (64-bit)

http://jsfiddle.net/danialfarid/s8kc7wg0/400/

**Comment by danialfarid** [comment]
What is not working?
