### ISSUE TITLE
Trigger an alert message when ngf-pattern or ngf-keep error occurs?

### ISSUE THREAD

**Issue by TommiZZ** [danialfarid/ng-file-upload#1419]
Hi there,
Is it possible to trigger an alert message when ngf-pattern=".png" or ngf-keep="distinct" error occurs? 
Everything works perfectly, but right now the user can't tell why nothing happens when he tries to browse an image that doesn't meet the requirements above-mentioned.
Thank you!

**Comment by danialfarid** [comment]
use `ngf-change="duplicateFiles($duplicateFiles)"`

**Comment by TommiZZ** [comment]
Ok, thank you! 
What about ngf-pattern=".png"?

**Comment by danialfarid** [comment]
'ngf-change="selectedFiles($duplicateFiles, $invalidFiles)"
