### ISSUE TITLE
node.js questions

### ISSUE THREAD

**Issue by AmirGilboa** [danialfarid/ng-file-upload#1422]
sorry for the noob question, i am noob at node.js.
i see the node.js example, but i'm not sure what to do with that.
the express middleware: what to do with that? is that a file? where to put it?

and the 'Route handler/controller', where should i put it?
any example would be great. 
thanks!

**Comment by danialfarid** [comment]
ask it on node.js github, this is a client side library. There is a wiki and notes for nodejs in the readme.
