### ISSUE TITLE
Resume a file upload API method?

### ISSUE THREAD

**Issue by alexstanbury** [danialfarid/ng-file-upload#1425]
Firstly, thanks for a great library!

I have file pause and resume from position working well when I reselect the file manually. 

If I am maintaining a queue of uploads which I then pause all by calling abort on each one, is there a way of resuming each upload without having to clear my queue and rebuilding it using new Upload.upload() calls on the files from the initially passed $files array?

Something like upload.resume() or similar. I can't find any API to do what I need but rebuilding seems like a long way round of doing it.

Thanks

**Comment by danialfarid** [comment]
`Upload.upload()` would be the same as `resume` meaning that if the file is partially uploaded already then it would resume the upload.

**Comment by alexstanbury** [comment]
I did it the long way round using Upload.upload() and passing in all the same config options as suggested, it still seems like there should be some kind of resume method meaning I wouldn't have to pass in the config again.
