### ISSUE TITLE
init validation

### ISSUE THREAD

**Issue by lkdnvc** [danialfarid/ng-file-upload#1429]
Hello! I initialize the loader ng-model with a starting value, but it does not pass validation. Please tell me what to do? example ng-model value : `[
  {
    "id": "123",
    "thumbnailUrl": "http://loremflickr.com/320/240",
    "rotateDegree": 0,
    "isDefault": false,
    "tmpId": "3z9o9mv7fj1us4te29"
  },
  {
    "id": "123",
    "thumbnailUrl": "http://loremflickr.com/320/240",
    "rotateDegree": 90,
    "isDefault": true,
    "tmpId": "757llumgsx7okk9sh5mi"
  },
  {
    "id": "123",
    "thumbnailUrl": "http://loremflickr.com/320/240",
    "rotateDegree": 0,
    "isDefault": false,
    "tmpId": "eayk5magjswwhilik9"
  }
]`
If i run force validation in ngModel.$render -> ngModel.$validate(); remove all items in ng-model

**Comment by danialfarid** [comment]
ng-model shoulld be a list of files those are not File objects.
