### ISSUE TITLE
I can't detect when a minHeight/minWidth error occurs

### ISSUE THREAD

**Issue by rzylber** [danialfarid/ng-file-upload#1430]
Hello, can I detect when a minHeight/minWidth error occurs and send a notification to the user?
Thank you

**Comment by danialfarid** [comment]
use `ngf-min-height` validation read the docs and samples.

**Comment by danialfarid** [comment]
use `ngf-min-height` validation read the docs and samples.

**Comment by matheusdavidson** [comment]
Hi, i had the same problem, solved by printing `form.file.$error`, then i saw the validation property `minHeight` which is not on the docs. The docs shows only: `maxHeight` and `maxWidth`, would be good to have these on the docs as well.

This is whats in the docs:
`ngf-min-height, ngf-max-height, ngf-min-width, ngf-max-width="1000" in pixels only images
              // validate error name: maxHeight
`
