### ISSUE TITLE
How to disable "All Files" choice while choosing file

### ISSUE THREAD

**Issue by kemalmuderrisoglu** [danialfarid/ng-file-upload#1433]
Hi,

I want to upload only excel files to my website. For this I added the code below 
(ngf-accept="'.xls'", ngf-pattern="'.xls'" ) 

When I click the button and the file choosing page comes, it is showing Excel files and All Files on the file formats.
Is there any way to disable All Files selection? So that users can only upload excel files.

Thanks.

**Comment by breaddevil** [comment]
I had that problem with accept/ngf-accept but it appeared only with chrome so I concluded it was a chrome bug.

The ngf-pattern works fine but you have to make the checks mentioned in the readme.

**Comment by danialfarid** [comment]
Use accept instead of ngf-accept

**Comment by danialfarid** [comment]
If that doesn't work then it is browser dependent and could be a browser bug you can try specifying the file mime type instead of extension

**Comment by vadq91** [comment]
Hi

I worked with: ngf-accept="'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'"
