### ISSUE TITLE
Testing with protractor when ngf-select is not input

### ISSUE THREAD

**Issue by pbouda** [danialfarid/ng-file-upload#1435]
I currently try to implement a protractor test the ng-file-upload functionality. It works fine as long as I use the `ngf-select` on an `<input>` element (I jsut send `sendKeys` to the element), but if I use `<span>` or `<div>` with `ngf-select` it does not work. Protractor tells me that it cannot focus on the element:

> Failed: unknown error: cannot focus element

Do you know if and how it is possible to test with non-input elements?

**Comment by pbouda** [comment]
I finally found it, after checking the code of the plugin. I was not aware that ng-file-uploads adds an input element somewhere in the DOM (not in the original `<form>`), so now I can such search for it like this:

> element( by.css( 'input[type=file][ng-model=modelImageName]' ) ).sendKeys( absolutePath );

Nice!

**Comment by mrtobo** [comment]
Wow, so glad I found this. Thanks!

**Comment by JulianPorras8** [comment]
You saved my life! Thanks a lot.

**Comment by PerwiPerwi** [comment]
Unfortunately, when I try to use this solution, I receive the error : "Element is no currently visible and so may not be interacted with". Any other ideas?

**Comment by bersling** [comment]
@PerwiPerwi It's because the <label> surrounding the input is hidden and this causes a problem in some browsers. Here's a solution how to make it visible:

```
  it('should upload a file', function() {

    var callback = function () {

      var fileToUpload = './upload-test.js',
          absolutePath = path.resolve(__dirname, fileToUpload);

      element(by.css('input[type=file]')).sendKeys(absolutePath); //assuming you only have 1 input

    };

    //firefox fix
    browser.executeAsyncScript(function(callback) {

      //make ngfSelectLabel visible
      
      //ngf is usually the last label on the page
      var ngfSelectLabel = document.querySelectorAll('label')[document.querySelectorAll('label').length - 1];
      
      ngfSelectLabel.style.visibility = 'visible';
      ngfSelectLabel.style.position = 'absolute';
      ngfSelectLabel.style.top = '0'; //maybe needs adjustment, depending on where on the page you are
      ngfSelectLabel.style.width = '100px';
      ngfSelectLabel.style.height = '100px';
      ngfSelectLabel.style.background = 'white';
      ngfSelectLabel.style.zIndex = '10000'; //to account for any blocking modal / popup screens

      callback();

    }).then(function() {
      callback();
    });


  });
```

**Comment by Bryan-Lavallee** [comment]
Thank you so much!

**Comment by tiffanytomol** [comment]
Hi, what if there's really no Input element? Does anybody know to do the test? Appreciate any help as I'm really stuck on this. Thank you.

**Comment by sarla2010** [comment]
It works like charm! Thanks.
