### ISSUE TITLE
[q/fr] support of request params

### ISSUE THREAD

**Issue by ZuBB** [danialfarid/ng-file-upload#1436]
Hi there!

thanks a lot for a so great lib!

Angular's http service allows to specify [request params](https://docs.angularjs.org/api/ng/service/$http#usage) in very nice (automatic) way. is it possible to pass a hash with params to `Upload.upload()` call somehow and get them appended to url automatically?

For now I am doing this, but it looks a bit ugly

```
...
      var uploadServiceOptions = {
        file: file,
        fileFormDataName: 'file',
        url: this.URL_PATHES.baseplan + '?ignoreWarnings=' + force.toString()
      };

      _.extend(uploadServiceOptions, this.reqConfig);

      return this.Upload.upload(uploadServiceOptions)
...
```

**Comment by danialfarid** [comment]
You should be able to use params

**Comment by ZuBB** [comment]
Hi @danialfarid!

Thanks for reply! Could you please write really quick example how to do that. Also please specify from which version it is supported (we are currently use 5.2.0)

**Comment by danialfarid** [comment]
It uses angular's $http underneath so all the $http options are available for Upload.upload. Since early versions.

**Comment by ZuBB** [comment]
ok, will try one more time

Thanks

**Comment by ZuBB** [comment]
yea, everything works. sorry for a false alarm

:bow:
