### ISSUE TITLE
ngf-resize not working on dynamic ngf-src

### ISSUE THREAD

**Issue by chanusukarno** [danialfarid/ng-file-upload#1440]
I have scenario where i have to generate thumbnail version of main images am using one `ngf-resize` on the `ngf-select` and it works fine i get the main resized image but when i take a copy of the same resized file into `ngf-src` of my thumbnail tag and set `ngf-resize` it has no effect.

here is the code snippet:
```
<div class="upload-select"
        ngf-select="onSelectFiles(galleryFiles, 'gallery')"
        ng-model="galleryFiles"
        ngf-multiple="true"
        ngf-resize="{width: 800, height: 600}">+ Select images
</div>
```
```
<div class="preview"
        ngf-src="image.temp_thumb.file"
        ngf-resize="{width: 200, height: 200}"
        ngf-background="image.temp_thumb.file">
</div>
```

`onSelectFiles` am just copying the file object into temp_thumb

**Comment by kavishmehta** [comment]
@chanusukarno will ngf-resize work without ngf-select as I want to compress image and then send to server
