### ISSUE TITLE
Drop does not work on the latest version of chrome

### ISSUE THREAD

**Issue by ali-bugdayci** [danialfarid/ng-file-upload#1444]
Checked your fiddle too: 

http://jsfiddle.net/danialfarid/s8kc7wg0/400/

Dragging an image does not change the model on the latest version of google chrome: Google Chrome Version 49.0.2623.87 (64-bit)

Works on Firefox  version 45.0

I am on a linux machine(it might not be important). Will be testing on other browsers tomorrow and let you know.

Thanks in advance

**Comment by danialfarid** [comment]
What is not working? Steps to reproduce

**Comment by ali-bugdayci** [comment]
Drag and drop an image does not work. It might be a browser thing though, hence its not easy to test for you.

I checked that filedrop.js console logs and seems like it is getting the image.

http://filedropjs.org/demo/basic.html

**Comment by danialfarid** [comment]
The fiddle is working for me on Chrome so unless you provide exact steps to reproduce this is not reproducible .
