### ISSUE TITLE
Upload.resize breaks animated gifs

### ISSUE THREAD

**Issue by danielbonnell** [danialfarid/ng-file-upload#1445]
Hello,

I've recently encountered an issue where client-side resizing of photos using `Upload.resize` causes animated gifs to break. I saw a work around for this issue that involves using the `ngf-resize-if` directive, however I've been struggling to get around this issue using the `Upload.resize` function within my app. 

A cursory look at the source reveals that `resize` takes 9 arguments, the 8th of which is `resizeIf`, which seems to be expecting a string object. What I'd like to know is if it's possible to pass in a regex that picks up only `jpg/jpeg/png` files (`/(image\/.*(jpeg|jpg|png))/`) instead, and how I could do that. Also, is it possible to pass in `resizeIf` without passing in other arguments? 

For example, I want to pass in only the `file`, `width`, and `resizeIf` arguments. I've tried passing in just those arguments, as well as passing `undefined` for the other arguments that I'm not interested in specifying, but I can't get it to work.

**Comment by danialfarid** [comment]
This is the syntax of resizeIf function `resizeIf(width, height) returns boolean`.
Updated readme file and gonna add enhancement to the next version to accept an options object rather than arguments. For now you need to pass all the arguments before resizeIf.

**Comment by danialfarid** [comment]
Fixed at 12.2.0. `Upload.resize(file, options)`
