### ISSUE TITLE
Is it possible to specify a response type if expecting a response from the upload method

### ISSUE THREAD

**Issue by admsugar** [danialfarid/ng-file-upload#1448]
Looking at a answer here which would allow to download a BLOB of a file and display it in browser: 
http://stackoverflow.com/questions/21628378/angularjs-display-blob-pdf-in-an-angular-app

It specifies that we would have to specifically declare the responseType (in my case an 'arraybuffer').

Is it possible to do something like:

    ```
    $scope.upload = Upload.upload({
            url: "../api/Upload", // webapi url
            method: "POST",
            file: controllerFile,
            responseType: 'arraybuffer'
        }).progress(function (evt) {
            // get upload percentage
            console.log('percent: ' + parseInt(100.0 * evt.loaded / evt.total));
        }).success(function (data, status, headers, config) {
            // file is uploaded successfully
            console.log(data);

            var fileBack = new Blob([(data)], { type: 'application/pdf' });
            var fileURL = URL.createObjectURL(fileBack);
            $scope.content = $sce.trustAsResourceUrl(fileURL);

        }).error(function (data, status, headers, config) {
            // file failed to upload
            console.log(data);
        });



Without the line: 'responseType:'arraybuffer' nothing throws any warnings or anything but with that line upon reaching this controller in the console I see:  

> GET http://localhost:54170/Client/%7B%7Bcontent%7D%7D 404 (Not Found)

**Comment by danialfarid** [comment]
Add it to the headers.

**Comment by JasonTheProgrammer** [comment]
@danialfarid, @admsugar  The `responseType` property on the Angular `$http` service options object doesn't set HTTP headers, it sets the underlying property on the `XMLHttpRequest`. [This property](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseType), as detailed further [here](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Sending_and_Receiving_Binary_Data).

Setting that property doesn't result in any change to the HTTP headers in the request, but changes how the response is processed. In the case of 'arraybuffer', that means the response object will be of type [ArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer).

With the `Upload.upload` function, the `data` property on the response object appears to always be formatted as a string. But if the response from the server was binary, that effectively destroys the data.

**Comment by HarishVerma-UI** [comment]
Hi Just replace `responseType: 'arraybuffer' `with `options:{responseType: 'arraybuffer'} `.
