### ISSUE TITLE
Trouble getting multipart/form-data POST payload to S3

### ISSUE THREAD

**Issue by notbrain** [danialfarid/ng-file-upload#1451]
Issue in SO: http://stackoverflow.com/questions/36295065/ng-file-upload-to-s3-with-v4-auth-file-data-missing

The crux of it is the Request is being sent as an object (or so it appears) instead of multipart/form-data, it's just form-data. What am I missing that would send this as multipart?

![image](https://cloud.githubusercontent.com/assets/67282/14152395/f58e2b10-f667-11e5-9467-8c0b9318fbc8.png)

**Comment by danialfarid** [comment]
follow on SO
