### ISSUE TITLE
Upload and crop inside $uibModal

### ISSUE THREAD

**Issue by biblicalph** [danialfarid/ng-file-upload#1452]
I followed the http://jsfiddle.net/danialfarid/xxo3sk41/590/ example on how to implement upload and crop. 

I implemented a similar case with a modal and works fine outside of my application. Adding the same snippet of code to my application always returns the file object to crop with the property **_$ngfDataUrlFilterInProgress: true_** defined on it. The image to crop therefore does not display.

Under what circumstances does this occur? What does it mean when it does occur?

Any assistance would be greatly appreciated.

**Comment by danialfarid** [comment]
Create a jsfiddle or copy your code.
