### ISSUE TITLE
upload with backend laravel

### ISSUE THREAD

**Issue by syehbiherbian** [danialfarid/ng-file-upload#1453]
i want to upload photo with angular and backend laravel, but the photos I uploaded does not enter into the upload folder laravel

why? angular js http://pastebin.com/TsCf9ud6 Controller Upload http://pastebin.com/3wKifyJy

What Should I Do? Thank You

**Comment by danialfarid** [comment]
Post it on SO. This is a server side issue.

**Comment by syehbiherbian** [comment]
okay, i'm sorry bro
