### ISSUE TITLE
Resize image with aspect ratio 

### ISSUE THREAD

**Issue by shubhamvermadaffodil** [danialfarid/ng-file-upload#1454]
I need to resize the image with keep maintain aspect ratio of image.

To calculate the height and width after file selected, we required the height and width of image selected in resizeOptions function.But I did't get image height and width in same function.

Please suggest how to resize image with maintain aspect ratio.

**Comment by danialfarid** [comment]
resize would always keep the aspect ratio

**Comment by shubhamvermadaffodil** [comment]
Thanks
