### ISSUE TITLE
For the method    Upload.urlToBlob(url).    I can't pass  the base64 url generate by  Upload.base64DataUrl

### ISSUE THREAD

**Issue by liu-kanghui** [danialfarid/ng-file-upload#1461]
I want to save the file object in localstorage,  but I don't know how to store a FILE type object.  so i try to convert the FILE image  to base64 url and store it into localstorage,  and then retrive the localstrage base64 url back to blob object  so I can upload the FILE type.

I can't get this to work.
Any help would appreciate. :)

**Comment by danialfarid** [comment]
It is not a good idea since the localstorage has limited space. What is not working? create a jsfiddle.
