### ISSUE TITLE
How to set Image into the ng-model and get it as a file.

### ISSUE THREAD

**Issue by galibimtiaz** [danialfarid/ng-file-upload#1465]
Hello , i am trying to make an edit UI , I am putting my image url in ng-modal and its showing the preview but when I am trying to get the file from the ng-modal its just giving me the url back not as a file. But I want it as a file so that I can post the request to upload the file. Right now my server-side laravel is showing error - Call to a member function getClientOriginalName() on null .

If I intentionally choose the file it works just fine.

**Comment by danialfarid** [comment]
post your code

**Comment by galibimtiaz** [comment]
<div class="form-group ">
                            <div class="col-sm-offset-2 col-sm-10 ">
                                <div class="content-box-header">
                                    <div class="panel-title">Service Icon</div>

                                    <div class="panel-options">
                                        <a href="javascript:void(0)" data-rel="collapse" ng-click="picFile = null"
                                           ng-show="picFile"><i class="glyphicon glyphicon-remove"></i></a>
                                        <a href="javascript:void(0)" data-rel="reload" type="file" ngf-select
                                           ng-model="picFile" name="file" accept="image/*" ngf-max-size="2MB" required
                                           ngf-model-invalid="errorFile"><i class="glyphicon glyphicon-plus"></i></a>
                                    </div>
                                </div>
                                <div class="content-box-large box-with-header center-cropped ">

                                    <img ngf-thumbnail="picFile" class="thumb">

                                </div>
                             </div>
                        </div>





This is my form , I am using it for editing infos.

Here is my functions from my controller -

```
 $scope.showModal = function (index) {


            $('#myModal').modal('show');
            var service = $scope.services[index];
            $scope.title = service.title;
            $scope.content = service.content;
            $scope.picFile = service.image;
            $scope.id = index;
 };

 $scope.updateService = function (index) {

            $scope.loading = true;
            var service = $scope.services[index];
            console.log($scope.picFile);

            $scope.upload($scope.picFile).then(function (url) {

                $http.put('http://localhost/twiined/public/service/' + service.id, {
                    title: $scope.title,
                    content: $scope.content,
                    image: url
                }).success(function (data, status, headers, config) {

                    $scope.loading = false;
                    $timeout(function () {
                        //$scope.services.splice(id, 1,data);
                        $scope.services[index] = data;
                        $scope.$apply();
                        console.log(data);
                    }, 100);

                });


            })
        };



 $scope.upload = function (file) {

            var q = $q.defer();
            Upload.upload({
                url: 'api/upload',
                data: {file: file}
            }).then(function (resp) {
                console.log('Success ' + resp.config.data.file.name + ' uploaded. Response: ' + resp.data);
                if (resp.data.url) {

                    q.resolve(resp.data.url);

                } else {
                    q.reject();
                }
            }, function (resp) {
                console.log('Error status: ' + resp.status);
                q.reject();
            }, function (evt) {
                var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
                console.log('progress: ' + progressPercentage + '% ' + evt.config.data.file.name);

            });

            return q.promise;
        };


And this is from Laravel-



 public function store(Request $request)
    {
        $image =$request->file('file');
        $fileName =$image->getClientOriginalName();
        $destinationPath = base_path().'/public/img/uploads/';

        if (file_exists($destinationPath.$fileName)){

            return response()->json(['success' => true,'url'=>url('/img/uploads').'/'.$fileName,'new'=>false], 200);

        }

        if(!$image->move($destinationPath,$fileName)) {
            return $this->errors(['message' => 'Error saving the file.', 'code' => 400]);
        }
        return response()->json(['success' => true,'url'=>url('/img/uploads').'/'.$fileName,'new'=>true], 200);
    }
```

**Comment by danialfarid** [comment]
You can only set a file as ng-model, url is just a string.
You can convert it to a file using `Upload.urlToBlob()` but I would recommend to keep the url and files in separate models.
