### ISSUE TITLE
Image retieve  not displaying 

### ISSUE THREAD

**Issue by zionnite** [danialfarid/ng-file-upload#1466]
i succeded uploading an image to firebase database but when i tend to retrieve my image but its not displaying...

i would have paste mt code but my laptop battery is dead and am only typing from my phone.

thanks anyone...

**Comment by calbear47** [comment]
Are you storing just the file name of the image on Firebase, or are you trying to store the whole image on Firebase? Unless you are hosting your app on Firebase as well, the image file shouldn't be "uploaded" to Firebase, but rather uploaded to your host server. 

Irregardless of where you upload the image, I would suggest thinking about retrieving not an image, but a string of image file you are referencing. You can retieve data from Firebase like this: 

`//setup instance of Firebase Service 
var ref = new Firebase(FIREBASE_URI+'web/data/images') 

//$loaded returns a promise. Load all the images into an array. 
//$firebaseArray is a service from the AngularFire libarary...will need to go read the docs on this. 
$firebaseArray(limitImages).$loaded().then(function(data){
	vm.images = data;
}); . `

But this is pretty off topic here you need to go explore Stackoverflow for more details on Firebase or visit their docs. 

Good luck

**Comment by zionnite** [comment]
sir, i thank ibfor ir time.
but the issues is that the image is not showing like kind of broken images .

**Comment by danialfarid** [comment]
Post it on SO since this is a question
