### ISSUE TITLE
ngf-thumbnail crashing IE11

### ISSUE THREAD

**Issue by general-adhoc** [danialfarid/ng-file-upload#1467]
When using ngf-thumbnail in IE11 once you try to upload around 100 MB of images the operation fails with a "Not enough storage is available to complete this operation".  (You may need to do one upload of images & reload the page and try again).

See fiddle: http://jsfiddle.net/nwy08oak/32/

I was attempting to get an example danialfarid posted in a separate issue (https://github.com/danialfarid/ng-file-upload/issues/1307) working with thumbnails & resize, but as you can see in the fiddle the upload chunk resizing code is being commented out.  

I'm running on a machine with 32 GB Ram & quad core i7 as well.  I notice chrome seems to have no issue, but IE11 (and likely other versions) can't handle it.

It appears changing `Upload.defaults.blobUrlsMaxMemory` by an order of magnitude in either direction has no impact.

Any suggestions (I know, other than not to use IE)?

**Comment by danialfarid** [comment]
Use 'ngf-src' instead.

**Comment by general-adhoc** [comment]
Thanks for the suggestion.  It works with ngf-src, but with no resizing after.  It crashes when you enable the compression piece (in IE11)

http://jsfiddle.net/nwy08oak/35/

Any ideas on how to solve?

**Comment by general-adhoc** [comment]
It appears I wasn't setting the `Upload.defaults.blobUrlsMaxMemory` low enough.  The default is `268435456` and decreasing it by two orders of magnitude `2684354` appears to work (at least with ~ 100 MB of files)

That seems really low -- 2.6 MB?  Could you elaborate a little more on what that variable is actually setting?  Is it the total size of all blobs or just the data urls related to the blobs?

Thanks for all of your work on this library.

**Comment by danialfarid** [comment]
Dataurls are cached for faster access and avoiding recalculation for different validation sand resizing. That variable sets the maximum cumulative size of data urls that should be cashed. If you set it very low or set the number of dataurls to be cached to zero it will not cache any dataurls allowing more available memory for js engine.
