### ISSUE TITLE
[Issue] Files selection dialog does not show on Ionic mobile app for iOS

### ISSUE THREAD

**Issue by saintc0d3r** [danialfarid/ng-file-upload#1468]
Synopsis:
-------------

I work on hybrid Web SPA , iOS & Android mobile app using Ionic & Angular Material frameworks. On one of the app's view, I put ng-file-upload for picking an image file and display it on the view, when the ng-file-upload's button is clicked/touched. Here is the code:

![image](https://cloud.githubusercontent.com/assets/1336147/14413459/463ce670-ffad-11e5-8b98-73ad12f6d3be.png)

Ng-file-upload works fine on major desktop browsers ( chrome, firefox, safari) & on Ionic Cordova app runs on Android platform. However, when I build the app as an Ionic Cordova for iOS app, runs the app on my iPhone 6 which runs iOS version 9.3.1, the file selection dialog does not show when I touch the ng-file-upload's button.  

Replication Steps:
-------------------------

1. Setup Ionic framework on your development environment (http://ionicframework.com/getting-started/) 
2. Create a new Ionic app with a simple view. 
3. Add ng-file-upload button on the view which takes image file.
4. Run the app as a web application & click the ng-file-upload button. Confirm that pick file dialog is shown.
5. Attach your android phone to your machine with USB debugging mode is turned on. Ensure that the phone is detected by your machine ( run `adb devices` command).
6. Build the app as an android app ( run `ionic run android`). Confirm that the app is build as an android app & running on your attached android phone.
7. On the android app version, touch the ng-file-upload button. Confirm the pick file dialog is shown.
8. Attach your iPhone which runs iOS 9.3.1 to your machine.
9. Build the ionic app for IOS platform (run `ionic build ios`).
10. Open the created iOS project from the prior build process on your XCode 7.3
11. Build & run the project on your iphone.
12. On the iOS app version, touch the ng-file-upload button. Confirm that the pick file dialog does not show. If we debug it using safari browser's developer tool and touch the ng-file-upload button, no error appear on the developer tool's console log window.

System Environment:
----------------------------
![image](https://cloud.githubusercontent.com/assets/1336147/14413530/899d30d0-ffaf-11e5-9270-5529852f4549.png)

**Comment by danialfarid** [comment]
https://github.com/danialfarid/ng-file-upload/issues/1049
