### ISSUE TITLE
Support for interceptors

### ISSUE THREAD

**Issue by nicolae-olariu** [danialfarid/ng-file-upload#1471]
Hi,

What do I need to modify in the source code to add support for something like this:

    Upload.upload({
            url: my_url_here,
            data: {
              file: file_here
            },
            headers: {
             // add headers here
            },
            interceptor: MY_INTERCEPTOR_HERE
          })
          .then(success, error, percentageStep);

where MY_INTERCEPTOR_HERE should look like this:

    (function() {
      'use strict';

      angular
        .module('app', [])
        .factory('MY_INTERCEPTOR_HERE', MY_INTERCEPTOR_HERE);

      /** @ngInject */

      function MY_INTERCEPTOR_HERE() {
          return {
          response: function(response) {
            // modify response here

            return response;
          }
        };
      }
    })();

Thanks in advance!

**Comment by nicolae-olariu** [comment]
One way would be to globally add the desired interceptor inside the config step:

    $httpProvider.interceptors.push('RestServiceInterceptor');

but I'm curious if we could decorate the Upload service to add support for this functionality. Thx!

**Comment by danialfarid** [comment]
Use regular $http() syntax:
```
Upload.upload{..., transformResponse: function() {....}}
```
