### ISSUE TITLE
Phonegap support.

### ISSUE THREAD

**Issue by CrackerakiUA** [danialfarid/ng-file-upload#1472]
When i am opening phonegap project inside web browser, everything work correct but when i open it on mobile, no file is send and no data at all. req.body is empty object and req.file is undefined.
I am working under windows server and android phone.

**Comment by dannysoer** [comment]
Are you using cordova camera to take Photos? I have the same problem, I don't know what exactly send, FILE_URI (Path) or imageData ("data:image/jpeg;base64,"+imageData)

**Comment by CrackerakiUA** [comment]
I have solved it, file which we are getting on mobile it's not same with file we are getting in browser, you just have to modify a bit how you will read it.

**Comment by erperejildo** [comment]
Hi @CrackerakiUA could you share with us that modification you did?

**Comment by CrackerakiUA** [comment]
I don't remeber where exactly that is, but it was easy, use console.log to check what are mobile giving you when you pick file and act proper.
