### ISSUE TITLE
Multiple drop areas

### ISSUE THREAD

**Issue by fbarnard** [danialfarid/ng-file-upload#1474]
Hi

We have a page that user can upload images into different "buckets" so we have about 30 buckets on the page . If i look at the source there is allot of <label><input> elements i assume one for each drop area.

Is there a way to consolidate this in some way.

![image](https://cloud.githubusercontent.com/assets/2089396/14530473/760c425c-0259-11e6-835d-497bcaab28c7.png)

thanks

**Comment by danialfarid** [comment]
30 elements is not a lot, should be fine. You can have one big drop element and base on the location of the mouse figure out the bucket if you have to have only one element.
Ask the question on SO, since it is not an issue
