### ISSUE TITLE
NodeJS, multiple files upload

### ISSUE THREAD

**Issue by mmumshad** [danialfarid/ng-file-upload#1475]
I am trying to upload multiple files in Angular, backend NodeJS

```
Upload.upload({
			url: '/api/updateReport',
			fields: metadata,
			file: [imageFile, reportFile, additionalFile]
		})
```

On the server end, I try to get them like this:

```
var file = req.files.file;
imageFile = file[0]
reportFile= file[1]
additionalFile= file[2]
```

The problem is it is not always in the same order. Sometimes they mix up. ie imageFile is not the First file.

How do I get around this?

I tried to send data like below. But I can't seem to read the data on the server end. I am  using 'connect-multiparty' middleware.
```
Upload.upload({
			url: '/api/updateReport',
			fields: metadata,
            data: {imageFile: imageFile, reportFile: reportFile, additionalFile: additionalFile}
		})
```

**Comment by danialfarid** [comment]
You can send the files one by one as a workaround. This is a node.js and connect-mutiparty so post it on SO.
