### ISSUE TITLE
progress issue

### ISSUE THREAD

**Issue by jammy525** [danialfarid/ng-file-upload#1478]
If I use ngf-resize directive progress is not working properly (it says 100% suddenly after uploading and at controller upload method is not fired at once while selecting file) following is my code. if removed ngf-resize directive working fine

`<span class="area-file ion-ios-camera camera-icon">
<input type="file" ngf-select="vm.uploadImageFile(imageFile)" ng-model="imageFile" name="file" ngf-pattern="'image/*'" accept="'image/*'"  ngf-accept="'image/*'" ngf-resize="{width: 320, height: 177, centerCrop: true}" ngf-min-height="177" ngf-max-size="20MB"></span>
    </div>
      <div class="progress" ng-if="vm.progress >= 0 && vm.progress < 100">
        <div class="progress-bar" style="width: {{vm.progress}}% !important;"></div>
      </div>`

**Comment by danialfarid** [comment]
How do you set vm.progress?

**Comment by jammy525** [comment]
at app.js:
controllerAs: vm

at controller : 
`var vm = this;`

**Comment by jammy525** [comment]
Please notice my issue. It seems that ngf-resize() directive process resizing and uploading then called my `vm.uploadImageFil()` method.

**Comment by danialfarid** [comment]
Create a jsfiddle sample, with your js code.

**Comment by jammy525** [comment]
http://jsfiddle.net/0mz6ff9o/861/

I have updated your own  jsfiddle link Please test it by removing `ngf-resize()` directive and by adding..
also please test when I used `ngf-fix-orientation="true"` its ngf-resize directive stop working

**Comment by danialfarid** [comment]
It is because the resized image is very small and will be uploaded immediately. If you make the values for ngf-resize bigger you would see the progress.

**Comment by jammy525** [comment]
Please check about `ngf-fix-orientation="true"` directive. when i am using this directive with ngf-resize. ngf-resize stop resizing.
