### ISSUE TITLE
Handle progress events using AngularJS (1.5.4+)

### ISSUE THREAD

**Issue by Frank3K** [danialfarid/ng-file-upload#1479]
AngularJS 1.5.4 provides to support handle additional $http events. See [the changelog](https://github.com/angular/angular.js/blob/master/CHANGELOG.md):

- **$http:**
  - support handling additional XHR events
  ([01b18450](https://github.com/angular/angular.js/commit/01b18450882da9bb9c903d43c0daddbc03c2c35d) and
  [56c861c9](https://github.com/angular/angular.js/commit/56c861c9e114c45790865e5635eaae8d32eb649a),
   [#14367](https://github.com/angular/angular.js/issues/14367), [#11547](https://github.com/angular/angular.js/issues/11547), [#1934](https://github.com/angular/angular.js/issues/1934))

This way, less functionality needs to be shimmed.

References #51, #267, #847.

**Comment by danialfarid** [comment]
I think it's kind of too late for now, the shimmed code is working and with angular 2 released the focus will be on that so doesn't worth implementing it just for angular 1.5 above. If you are willing to contribute it would be great.
