### ISSUE TITLE
Directory name is appended twice

### ISSUE THREAD

**Issue by dduft** [danialfarid/ng-file-upload#1480]
Hi,
i recognized the issue in title.
For version 12.0.4 in line number 1980, there should be the typo:
`file.name = file.path = (path || '') + entry.name + entry.name;`

Thank you for your great job!

**Comment by danialfarid** [comment]
Already fixed https://github.com/danialfarid/ng-file-upload/pull/1424 will be release in the next version.

**Comment by dduft** [comment]
Any news on this?

**Comment by danialfarid** [comment]
Fixed at 12.1.0
