### ISSUE TITLE
Module injector error

### ISSUE THREAD

**Issue by Noob7** [danialfarid/ng-file-upload#1481]
When trying to inject the 'ngFileUpload' in my module I was getting an injector error. However it worked with 'angularFileUpload'. Just wanted to give a heads up to anyone else stuck with the same issue so they do not end up wasting hours

**Comment by danialfarid** [comment]
You are on a wrong github or installed another plugin, You should use `ngFileUpload`, follow the instruction in the docs.

**Comment by Noob7** [comment]
Hey,

I figured it out. Actually the cdn links i was getting from google were
outdated ones. Installed from bower link and it started working

Regards
Qaim
