### ISSUE TITLE
Drag and Drop not working on Firefox 45.0.2

### ISSUE THREAD

**Issue by vileppanen** [danialfarid/ng-file-upload#1482]
It seems that drag and drop feature does not work in Firefox 45.0.2 (this security update was patched for me somewhere around 12.4.2016).

When you try to drag a file in to the drop zone, the cursor state remains as rejecting the operation.

Referring to this example:
http://jsfiddle.net/danialfarid/s8kc7wg0/400/

Works correctly in chrome, but not with the most recent version of Firefox.

**Comment by Frank3K** [comment]
Related: #1470.

**Comment by danialfarid** [comment]
Demo is working for me on mac firefox 45.0.2.

**Comment by danialfarid** [comment]
Could be a temporary browser bug.
