### ISSUE TITLE
Have problem when upload bmp files

### ISSUE THREAD

**Issue by x69chen** [danialfarid/ng-file-upload#1484]
Hi I have tested with bmp, jpg, gif, and png files, all other three looks fine, but I only get errors when I upload bmp files.
My html code:

`			<div ngf-drop ngf-select ng-model="file" class="drop_box" ngf-drag-over-class="'dragover'" ngf-multiple="false" ngf-allow-dir="true" accept="image/*,application/pdf" ngf-pattern="'image/*,application/pdf'" ngf-capture="'camera'"></div>
`
and then php code:

```
	$cid =  $_POST['cid'];
	$filename =  $_FILES['file']['name'];
	$destination = '../img/' . $cid . '/';
	if(!is_dir($destination))
		mkdir($destination);
	$filetmpname = $_FILES['file']['tmp_name'];
	move_uploaded_file($filetmpname, $destination . $filename);
```
The error appears when I define $cid (or $filename if I put it at the first),
the error message is "Type: ErrorException; Code: 8; Message: Undefined index: cid".

Any ideas why this happens? Thank you.

**Comment by danialfarid** [comment]
This is a server php error so post it on SO, this plugin is client side javascript.
