### ISSUE TITLE
Convert url to blob guidance

### ISSUE THREAD

**Issue by TamHi** [danialfarid/ng-file-upload#1485]
Hi, I'm trying to convert url to blob to use it in the ng-model.
This is what I've tried:
- Get the string url from the server (eg: '/assets/uploads/Gx8nedbb_DAhOxfzA_SnRBQx.jpg').
- Convert it to blob `Upload.urlToBlob(url).then(function(blob) { // Assign blob to model used with ng-model })`
- I log the blob out and get the following `Blob {size: 214565, type: "image/jpeg", name: undefined}`
Can you show me the way to do it? Thanks in advance, really enjoy your directive.

**Comment by danialfarid** [comment]
So what your question is?

**Comment by TamHi** [comment]
I figured out what my problem is, and it's not related to ng-file-upload, thank you for your time.
