### ISSUE TITLE
Getting different css

### ISSUE THREAD

**Issue by AtulaGuleria** [danialfarid/ng-file-upload#1486]
Hello Danialfarid !
I have made a fiddle which is a copy paste of [your](http://jsfiddle.net/danialfarid/maqbzv15/1118/) code but I am getting result shown in the Image below. 
<a href="https://www.dropbox.com/s/zhvfoy9ted3urd9/error.png?dl=0">link</a>

Please Guide. 
Regards.

**Comment by danialfarid** [comment]
submit your jsfiddle.

**Comment by AtulaGuleria** [comment]
<a src="https://jsfiddle.net/Atula/n99d9tyk/">fiddle</a>

**Comment by AtulaGuleria** [comment]
ok this error is only showing in the fiddle. css fine on my app.
But can you tell why I am getting error when I am selecting image.
"ERROR :TypeError: Illegal constructor.
              at c.dataUrltoBlob (file:///android_asset/www/lib/ng-file-upload/ng-file-upload.min.js:2:26316)"

**Comment by danialfarid** [comment]
your fiddle is not working you should include angular.

**Comment by danialfarid** [comment]
your fiddle is not working you should include angular.
