### ISSUE TITLE
$ngfDuration reports wrong duration.

### ISSUE THREAD

**Issue by swayamnag** [danialfarid/ng-file-upload#1488]
Hello
I have noticed from some video files the duration value returned by $ngfDuration was wrong. I have verified the video file that was used had a duration(by playing the video file)  which was different from what was reported by $ngfDuration. Anyone noticed or experienced this issue ?
I noticed this on .mpg type file.

**Comment by danialfarid** [comment]
Can you post the file that is reporting wrong duration? Also $ngfDuration is for internal use and should not be used in your app.

**Comment by swayamnag** [comment]
Hi Danial, now i understand this is for internal use. What is the other way to access the duration of the video media file ? The files i have attached(two .mpg file in .zip file) do not seem to report the duration at all. I just noticed the same issue with .flv file no duration reported. Is it likely because $ngfDuration should not be used. 
I appreciate the good work you have done with ng-file-upload 


[Creative Sample File.zip](https://github.com/danialfarid/ng-file-upload/files/233614/Creative.Sample.File.zip)



[Creative Sample File.zip](https://github.com/danialfarid/ng-file-upload/files/233613/Creative.Sample.File.zip)

**Comment by danialfarid** [comment]
Use `Upload.mediaDuration()` read the docs there is a list of all services provided.
