### ISSUE TITLE
imageDimensions(file) and $ngfWidth/$ngfHeight have wrong values

### ISSUE THREAD

**Issue by thegitfather** [danialfarid/ng-file-upload#1490]
The values vary depending on the actual browser window size. E.g. when I add an image with an actual width of 2000px and my Browser window is 1280px then the width value will show something like <1280px.

**Comment by danialfarid** [comment]
What device and browser?

**Comment by thegitfather** [comment]
Happens in Chrome stable and Firefox. But I see the Demo is working (sorry - didn't think about checking it there first). Guess my problem is somewhere here

```js
$scope.$watchCollection('vm.files', function(newVal, oldVal) {
      // console.log("newVal:", newVal);
      vm.busy = true;
      var fileErrors = 0;
      for (var i = 0; i < newVal.length; i++) {
        if (newVal[i].dimensions === undefined) {
          // TODO: https://github.com/danialfarid/ng-file-upload/issues/1490
          appendDimensions(newVal[i]);
        }
        if (newVal[i].$error !== undefined) {
          fileErrors += 1;
        }
      }
      $scope.queueInvalidLength = fileErrors;
      ...
```
I read something about adding `ngf-min-width="0"` so the dimensions get appended automatically. But I remember that I had the same problem then.. Not quite sure whats wrong but I will have a look into that later (but any hints are welcome of course :) )

**Comment by thegitfather** [comment]
Just created a new pull request (#1506). Should be safe to merge this I think.

**Comment by thegitfather** [comment]
If somebody runs into this issue, simple fix would be:
```css
body > img {
  max-width: none !important;
}
```
