### ISSUE TITLE
Problem for upload files between 500MB to 2GB.

### ISSUE THREAD

**Issue by harmeetsingh0013** [danialfarid/ng-file-upload#1492]
Hi Danial,

I have an issue when using your libraries for uploading large size of videos. I need to upload videos on AmazonS3. Less then 500mb videos uploaded successfully, but when we trying upload videos above 500mb up-to 2gb, we are facing CROSS origin error. Pleas find attached screenshot of error.
![crosserror](https://cloud.githubusercontent.com/assets/5654656/14710966/22e5af90-07f5-11e6-9ed0-7d388c633b8e.png)

**Comment by danialfarid** [comment]
It is probably server error and is probably server limitation on the size of upload.

**Comment by harmeetsingh0013** [comment]
Hi Danial,

The files are uploaded directly from angular to s3, there is no involvement of server here. You see the request url is directly for amazon bucket. I am sure, this is not server error.

**Comment by danialfarid** [comment]
S3 is your server. Post it on stackoverflow since it is a S3 server 400 error. You can probably change the S3 settings to accept larger files or it might be a hard limit.
