### ISSUE TITLE
Add a connection timeout 

### ISSUE THREAD

**Issue by j-w-miller** [danialfarid/ng-file-upload#1493]
When running on a desktop, a file is uploaded, and then the connection is lost midstream, I get an ERR_CONNECTION_RESET within 1 minute.  However, when I'm running on a mobile and the connection is lost, I receive a ERR_ADDRESS_UNREACHABLE that takes 15 minutes. It would be beneficial to be able specify a timeout so that the application would react the same regardless of the platform.   This occurs on Google Chrome but see something similar on Firefox.

**Comment by danialfarid** [comment]
Set `Upload.upload({..., timeout: xxx})`

**Comment by j-w-miller** [comment]
Thank you Danial, worked perfectly

**Comment by danielcmm** [comment]
Hi, in which version was this included? The timeout is in seconds? Thanks

**Comment by danialfarid** [comment]
All versions

**Comment by Diliptopdox** [comment]
I am using Upload.http() method to upload files. How can we specify request tiimeout there in Upload.http method ?
