### ISSUE TITLE
Chunk files for upload on windows azure

### ISSUE THREAD

**Issue by jefersonmanjos** [danialfarid/ng-file-upload#1494]
I'm trying to send large files to the azure windows, but did not see possibilities to enable chunk. Always get error 413.

Some way to do this?

Thanks

**Comment by danialfarid** [comment]
Unless the server has special support for this it is not possible.

**Comment by razblack** [comment]
in MVC, you would need to support partial digests of the stream somehow.. there's examples using flow, and here are a couple spots that might get you started.

http://studentguru.gr/b/eloy/archive/2015/07/13/video-streaming-for-mobile-clients-via-asp-net-web-api-2-tutorial

http://senvichet.com/blog/iformfile-how-to-upload-asp-net-core-mvc-6/

I have to admit, with asp.net core mvc 6, I was having a really hard time getting any of it to work....
