### ISSUE TITLE
Remove the files I have attached but have not submitted yet

### ISSUE THREAD

**Issue by x69chen** [danialfarid/ng-file-upload#1495]
I am using drag and drop box to attached images, thumbnails to show preview, and then submit button to upload the images.

Here is my HTML code:
```
			<div class="image_thumbnails">
				<div class="image_thumbnail" ng-repeat="image in file.images">
					<img ngf-thumbnail="image" width="200" height="200">
					<a ng-click="deleteFile($index)"><i class="fa fa-times fa-5x" aria-hidden="true"></i></a>
				</div>
			</div>
			<div ngf-drop ngf-select ng-model="file.images" name="images" class="drop_files" ngf-drag-over-class="'dragover'" ngf-multiple="true" ngf-allow-dir="true" accept="image/*" ngf-pattern="'image/*'" ngf-capture="'camera'" ngf-keep="'distinct'">
				<figure><i class="fa fa-file-image-o fa-3x" aria-hidden="true"></i></figure>
				<span>{{ changeUText(file.images) }}</span>
			</div>
```

I am using  ngf-keep="'distinct'" so I suppose to remove the files before submit is possible, however I don't know where the system stores them, I checked web storage, local storage, and cookies but did not find any fields should contain the temporary files.

Could anyone helps me how to remove those temporary files before submit? Thanks

**Comment by x69chen** [comment]
Ok I have found the solution by using "files.splice(idx, 1)" to remove the items in the array.

**Comment by Frank3K** [comment]
@x69chen: Good. Could you close the issue since you have found the solution?
