### ISSUE TITLE
It should be possible to disable ngf-drop

### ISSUE THREAD

**Issue by teterovic** [danialfarid/ng-file-upload#1498]
it should be possible to disable ngf-drop based on a variable value for example:
`<div ngf-drop="false">`

```
ngFileUpload.directive('ngfDrop', [
....
link: function (scope, elem, attr, ngModel) {
          if (attr.ngfDrop != "false")
            linkDrop(scope, ....);
        }
```

**Comment by danialfarid** [comment]
Use   ngf-drop-disabled="boolean" // default false, disables file drop on this element
read the docs!
