### ISSUE TITLE
nice to have model reference supported along with ng-model

### ISSUE THREAD

**Issue by razblack** [danialfarid/ng-file-upload#1499]
I have a use case where adding and removing multiple files from my view-model requires some additional meta data to accompany the file.  It would be great, if we could have an additional tag (or directive added) to support a reference model that would include the file object along with any meta data that needs to accompany that particular file that is added (besides it's name, creation date, et al)

What I was thinking is that we can use ng-model to specify the 'array' to be used and a ngf-model-reference to build that array and add extra meta data with it, say:

```
function fileMeta(file, uid, timestamp, originationUri){
  this.file = file,  //the actual FileAPI file
  this.uid = uid,  //extra meta
  this.timestamp = timestamp,  //extra meta
  this.originationUri  //extra meta
}
```

in the routine you have to apply the file into the ng-model array.. have it first make an angular.copy(new fileMeta(null,null,null,null)), and ingest the file to fileMeta.file ?

**Comment by danialfarid** [comment]
Why don't you just keep a scope variable for that. I don't see the need for a directive.

**Comment by razblack** [comment]
agreed...  i ended up creating a viewmodel service to handle all the schema and it is working nicely.

thanks for considering.
