### ISSUE TITLE
Can't find my uploaded image in s3 after successful upload with ng-file

### ISSUE THREAD

**Issue by nuruddeensalihu** [danialfarid/ng-file-upload#1500]
Please i don't seem to find my image in my s3 bucket despite receiving positive response from my ng-upload. I opened a question at SO [Here](http://stackoverflow.com/questions/36549765/cant-find-my-uploaded-file-in-my-s3-bucket) yet no one seem to know what the problem is . I would really appreciate it if some one can help me. I based my code on the tutorial here https://github.com/danialfarid/ng-file-upload/wiki/Direct-S3-upload-and-Node-signing-example

**Comment by danialfarid** [comment]
Po
