### ISSUE TITLE
How to use s3 put paramter using file upload

### ISSUE THREAD

**Issue by harmeetsingh0013** [danialfarid/ng-file-upload#1501]
Hi Danial,

As we discuss the issue for uploading file with server error. For handling this server error, we need to pass put parameters with upload request. These parameters are mention [in this link](http://www.s3express.com/help/help.html?vv_put.html). How we can use `-p`, `-mul` etc parameters using your library. 
I am using following code for upload files: 
`
AWS.config.region = $scope.properties.region;
var bucket = new AWS.S3({
params: {
	Bucket: $scope.properties.bucket
}
});
var params = {
	Key: filekey,
	ContentType: file.type,
	Body: file
};
$scope.uploadProcess= bucket.putObject(params, function(err, data) {}
`

**Comment by danialfarid** [comment]
Post on stackoverflow
