### ISSUE TITLE
ngf-hide-on-drop-not-available is missing

### ISSUE THREAD

**Issue by DanieleTorino** [danialfarid/ng-file-upload#1503]
The `ngf-hide-on-drop-not-available` feature seems to be completely missing.

Also, a symmetric version `ngf-show-on-drop-available` would be a nice addition.

**Comment by danialfarid** [comment]
ngf-hide-on-drop-not-available should be working. create a jsfiddle to show the issue.
What would be the usecase of show-on-drop-available?

**Comment by DanieleTorino** [comment]
Nevermind. I could achieve the same thing using `ngf-drop-available` together with `ng-show` and `ng-hide`.
