### ISSUE TITLE
send the file binary to GCS failed, succeed with new XMLHttpRequest

### ISSUE THREAD

**Issue by Pleasurazy** [danialfarid/ng-file-upload#1504]
Hi, how are you?

I am trying to upload file binary to GCS (Google cloud storage) by Signed URLs

I following that docs says:
```
    Upload.http({
      method: 'PUT',
      url: signedUrl,
      headers: {
        'Content-Type': file.type // image/png
      },
      data: file,
    })
```

![image](https://cloud.githubusercontent.com/assets/1500206/14876718/bdc36d96-0d49-11e6-90aa-a5cd74a517b5.png)

Although 200 ok, but the file got broken.

---

and I am succeed with pure js
```
    const xhr = new XMLHttpRequest()
    xhr.addEventListener('readystatechange', function () {
      if (this.readyState === 4) {
        console.log(this.responseText)
      }
    })
    xhr.open('PUT', signedUrl)
    xhr.setRequestHeader('content-type', file.type)
    xhr.send(file)
```

![image](https://cloud.githubusercontent.com/assets/1500206/14876720/c4ca83b8-0d49-11e6-9963-e49951ce7e21.png)

Can you help me?

![default](https://cloud.githubusercontent.com/assets/1500206/14876711/a7c62952-0d49-11e6-9092-6b4509b33ba7.gif)

**Comment by danialfarid** [comment]
What are the differences between two requests? In header or file content being sent? Maybe a header is missing or is extra.
