### ISSUE TITLE
ngf-keep true/distinct will cause problems when removing image

### ISSUE THREAD

**Issue by Hirbod** [danialfarid/ng-file-upload#1507]
Hi,

I'm building an upload list. The upload will start after the user have clicked "start". The list is editable. When deleting a file from queue

```
    $scope.files.splice(index, 1);
```

it will be deleted from my list, but as soon as I add another file to that model, the deleted one appears again. I tried to use a debounce but that didn't work out. Any solution how I can make sure, that a spliced file won't appear again?

**Comment by Hirbod** [comment]
Just updated to 12.0.4 - looks like this problem has been fixed.

**Comment by Hirbod** [comment]
But there is another problem: once a file was added and deleted, it can't be readded, as distinct "thinks", that the file is still present. Any fix or workaround for that?

**Comment by bruceCzK** [comment]
+1, same problem.

**Comment by bruceCzK** [comment]
Oh, I think I just use it wrong. I wrote like this before
```
<div ngf-upload="vm.upload($files)" ngf-keep="'distinct'" ngf-multiple="true"></div>
```

```
vm.upload = function(files) {
  vm.files = files;
  ...
}

vm.removeFile = function(index) {
  vm.files.splice(index,1);
}
```

and when I add file again, the old ones was added again.

It turns out that I forgot to set `ng-model`, like this
```
<div ngf-upload="vm.upload(vm.files)" ng-model="vm.files" ngf-keep="'distinct'" ngf-multiple="true"></div>
```
Then it works perfect. Hope to be helpful.

**Comment by Hirbod** [comment]
I already got the model there correctly. I also thought they it was fixed, but now, it also happens, that all the files, which were deleted before, will be back again, as soon as I add another file

**Comment by danialfarid** [comment]
Create a jsfiddle with steps to reproduce.

**Comment by zoltan-boros** [comment]
Hi, I face the same issue.
Here you can find a JSFiddle to reproduce it: https://jsfiddle.net/zoltan_boros/s847ahk9/1/

**Comment by danialfarid** [comment]
This will fix it: https://jsfiddle.net/ufhb5yt5/

**Comment by Hirbod** [comment]
I can't see what you've done? Did you change something in your directive or only inside of the fiddle? As I am still having the same issue

**Comment by zoltan-boros** [comment]
Danial made a change within the `reset` function in JSFiddle:
Bad:
`$scope.files = undefined;`
Fixed:
`$scope.files = [];`

In my case this solved the issue.
Thank you Danial!

**Comment by Hirbod** [comment]
Thanks for that. It worked for me also! (i made $scoe.files = '')
