### ISSUE TITLE
ng-material md-button compatibility

### ISSUE THREAD

**Issue by pavelety** [danialfarid/ng-file-upload#1514]
The code I would like to use, but it doesn't work for now:
`<md-button flex class="md-raised md-primary" ngf-select="uploadPictures($files)" multiple accept="image/*">Select Files</md-button>`
And workaround solution I have to use:
`<md-button flex class="md-raised md-primary"><span ngf-select="uploadPictures($files)" multiple accept="image/*">Select Files</span></md-button>`

**Comment by danialfarid** [comment]
What the issue is? Create a jsfiddle.

**Comment by gliss** [comment]
Works for me when I use `<md-button class="md-btn md-raised m-b btn-fw md-primary" ng-model="_categoryCtrl.files"  ngf-pattern="{{_categoryCtrl.allowPatterns}}" ngf-multiple="true" ngf-max-size="10MB">Select Files</md-button>`
