### ISSUE TITLE
not working with angular material.

### ISSUE THREAD

**Issue by andreipot** [danialfarid/ng-file-upload#1518]
@danialfarid is this working with angular 1.5.5? I'm using ng-file-upload v12.0.4 but when i select files, files are not bound to ng-model.  And I'm using angular material 1.0.8

**Comment by danialfarid** [comment]
Create a jsfiddle. The demo page works with 1.5.5.

**Comment by andreipot** [comment]
@danialfarid  when i click button, it doesn't show up file select dialog. do you know why?

**Comment by andreipot** [comment]
@danialfarid  how can I implement file upload with progress displayed?

**Comment by danialfarid** [comment]
See the docs, and jsfiddle sample. Create a jsfiddle with steps to reproduce if you have issue.
