### ISSUE TITLE
ngf-hide is being added to <img> tags while uploading sub sequent images

### ISSUE THREAD

**Issue by jsrikrishna** [danialfarid/ng-file-upload#1519]
Can be reproduces like this
1) Upload an image using ngf-select=upload(file)
2) Render the preview using `<img ngf-src="file">`
3) Try to upload an image now, ngf-hide class is being added to the `<img>`

**Comment by danialfarid** [comment]
Can you create a jsfiddle?

**Comment by jsrikrishna** [comment]
In the existing demo here: https://angular-file-upload.appspot.com/, i uploaded a single image by selecting the file. Then the images is displayed like this: 
![screen shot 2016-05-09 at 17 20 58](https://cloud.githubusercontent.com/assets/8509959/15112436/d816b69c-160b-11e6-8964-fe3f7161792b.png)

Now, tried to upload one more image by selecting the file and the previous image is not being displayed;
![screen shot 2016-05-09 at 17 30 18](https://cloud.githubusercontent.com/assets/8509959/15112463/0546fe6a-160c-11e6-81f7-7e11aac7c960.png)

So the selected `img` tag is having a style of `ngf-hide`

**Comment by danialfarid** [comment]
So what the issue is? If the model is empty the ngf-hide will be added.

**Comment by jsrikrishna** [comment]
I am not able to understand who is setting the model to empty (null).

**Comment by danialfarid** [comment]
When you click on the button the previous file will be cleared.

**Comment by jsrikrishna** [comment]
Okay got it, Wondering if is there anyway to empty the model only after successfully selecting another image rather than emptying model on click of button

**Comment by danialfarid** [comment]
there is no cross browser way to do this that's the reason why by default it will clear it.
You can use ng-model-options to disable clearing on click but it could behave differently on browsers and won't fire change if you select the same file again.

**Comment by jsrikrishna** [comment]
got it and closing this.
