### ISSUE TITLE
How to handle the resizing event when  i select a large image(more than 10m)?

### ISSUE THREAD

**Issue by vincent-lee90** [danialfarid/ng-file-upload#1525]
How to handle the resizing event when i upload a large image which is more than 10m ?
I hope that there are  resizing started event and resizing  finished started.
can you give me some suggestions?

**Comment by danialfarid** [comment]
There is a before change directive that you can detect the file selection before resizing starts and when the model is set or ngf-change is called the resizing is finished. See the docs.

**Comment by vincent-lee90** [comment]
thanks very much,i have solved it by the directive of 'ngf-before-model-change'!
