### ISSUE TITLE
Why goes my progress bar to 100% before Upload finished?

### ISSUE THREAD

**Issue by mitomm** [danialfarid/ng-file-upload#1527]
Hi there,

thanks for the great plugin.

However, somehow I cannot get the progress bar to work properly. Whatever I upload and unrelated to how long the upload really takes, the progress bar very quickly jumps to 100%.

My basic code looks as follows:

```
 settingsApp.controller('imageUploadController', function($scope, Upload, $uibModalInstance, $timeout, backendUploadPath, cropShape, cropRatio, imageWidth){

	var upload;
		
	$scope.genericUpload = function (croppedDataUrl, imageName) {
		this.upload = Upload.upload({
		    url: backendUploadPath,
		    data: {
		        file: Upload.dataUrltoBlob(croppedDataUrl),
				name: imageName //only used to get ending of filename (.jpeg, etc...)
		    },
		}).then(function (response) {
			// file is uploaded successfully
		    $timeout(function () {
		        $scope.result = response.data;  
		        $uibModalInstance.close({"tempImgData":croppedDataUrl,"insertID":response.data.insertID});	        
		    });
		}, function (response) {
			// handle error
			if (response.status > 0) {
				$scope.errorMsg = response.status + ': ' + response.data;
			}
		}, function (evt) {
  			// progress notify
  			if ($scope.errorMsg) {
  				return
  			}
		    $scope.progress = parseInt(100.0 * evt.loaded / evt.total);    
		});
	}
     .....
}
```

Logging $scope.progress prints numbers from 0 up to 100 in steps of 9 (e.g. 8, 17, 26, 35,..) and reaches 100 long before upload is finished?

Any idea on what I'm doing wrong?

Any help is greatly appreciated.

**Comment by danialfarid** [comment]
How do you know it finishes before upload?

**Comment by mitomm** [comment]
I assume it based on multiple reasons:
1. the success callback
```
.then(function (response) {
            // file is uploaded successfully
            $timeout(function () {
                $scope.result = response.data;  
                $uibModalInstance.close({"tempImgData":croppedDataUrl,"insertID":response.data.insertID});          
            });
        }, ....
```
is getting called about a second later than `$scope.progress` reaches 100
2. I intentionally tried it with a very slow internet connection, but still, the progress reaches 100 in a couple ms which regarding the slow connection cannot be possible.

Do I have to handle the progress in the backend (with Node) somehow?

**Comment by danialfarid** [comment]
Well if you get the progress event and you see numbers are increasing then that's the information your server is sending. So it could be that it is sent on the network but it is not processed by the server yet.

**Comment by mitomm** [comment]
Hmmm, I'm not sure if the issue is really relate to server processing  since I get an immediate success response when I try it on localhost (thus it doesn't seem to me that my server code is doing something too slow). It really seems that I'm doing something wrong with the progress bar because even if I "simulate" a really slow Edge connection, the progress bar jumps 100 in a matter of ms and the actually image upload cannot have happend that fast. Actually, no matter what connection I have the progress jumps to 100% in a couple of ms.

**Comment by danialfarid** [comment]
Point your code to the demo page server url to make sure it is your server.

**Comment by mitomm** [comment]
So I just pointed my code to "http://angular-file-upload-cors-srv.appspot.com" and limited my internet speed to Edge and the progress bar has been working perfectly fine (i.e. not jumping to 100% in a couple ms).

As you said, the issue seems to be related to the server then. However it doesn't seem that the server processes the image to long but rather that the upload progress information gets messed up by the server. I have no idea why. Maybe you have a suggestion? 

But since a server problem is not an issue of your library, thanks anyway for your help.

**Comment by danialfarid** [comment]
Try posting it on StackOverflow. Some node experts might know about it.

**Comment by WuglyakBolgoink** [comment]
@mitomm are you found a fix for this problem? I have the same problem with progressbar...

**Comment by maddenf** [comment]
I'm also having the same issue.
