### ISSUE TITLE
Simultaneously uploading individual files duplicates single image.

### ISSUE THREAD

**Issue by NoelBaron** [danialfarid/ng-file-upload#1530]
Odd issue: 
1. Select 4 files.
2. Iterate 4 files and upload individually, all at once. (4 simultaneous Upload.upload() commands).
3. Chrome picks the last file and uploads it 4 times.

To get around the issue, I had to queue the files in a batch. In batched mode, the next file was not started until previous was complete, and the issue was resolved.

Any idea why simultaneous .upload() calls bugged out?

**Comment by danialfarid** [comment]
It is an error in your code, you are probably using a global index for pointing to file in the array. Try using the code in the jsfiddles or demo page. If you didn't figure out create a jsfiddle with steps to reproduce.

**Comment by NoelBaron** [comment]
Two functions... spot anything obvious? I'll port this over to a jsFiddle later this morning.
```
// Scope handler
$scope.uploads = []; 
$scope.uploadFiles = function(files) {
  if (!Array.isArray(files)) { files = [ files ]; }
  for (var i = 0; i < files.length; i++) {
    var file = files[i];
    $scope.uploads.push(file); // displays progress
    UploadService.uploadFile({file:file});
  }
}

// Uploader Service
self.uploadFile = function(data) {
  Upload.upload({
      url: '/api/assets',
      data:data,
      headers:{'Authorization':"Bearer "+user.cookies.get("access_token")},
  })
  .then(function(resp) {
   // success stuff
 }
  ,function (resp) {
  // error stuff
  }
  ,function (resp) {
    // progress stuff
  });
}

```

**Comment by danialfarid** [comment]
Do a console.log of the file before it is being called in Upload.upload() to figure it out.
