### ISSUE TITLE
File uploads to S3 successfully but permission and Content-Type null

### ISSUE THREAD

**Issue by 10printhello** [danialfarid/ng-file-upload#1531]
I have used the following method to try to post (and put) files in my S3 bucket. They are successfully uploaded and appear in the bucket but they neither have the Content-Type or Permissions set. I've also tried using http.post also but the same issue. I think it may have to do with skipAuthorisation? 

I can upload successfully from the DEMO and the permissions and content-type are correctly added.

Any ideas?

Upload.upload({
                  url: myUrl,
                  method: 'PUT',
                  skipAuthorization: true,
                  data: {
                      'key' : myKey,
                      'acl' : 'public-read',
                      'Content-Type' : file.type,
                      'AWSAccessKeyId': 'XXXXXXXsssXXXXsxXX',
                      'success_action_status' : '201',
                      'Policy' : myPolicy,
                      'Signature' : mySignature
                  },
                  file: file,
                })

**Comment by 10printhello** [comment]
SOLVED :

**Comment by mcintyre321** [comment]
Hi @10printhello any chance you could email me on my github userid at gmail.com. Thanks!
