### ISSUE TITLE
Chrome display window after a long time on Windows

### ISSUE THREAD

**Issue by cmillauriaux** [danialfarid/ng-file-upload#1532]
Hi !

I'm using ng-file-upload for many months and i'm very happy to this projet ! But, since I updated Chrome in Windows (v50.0.2661.102), the browser display the file selection window 10-20 seconds after I clicked on the button. In Firefox or Edge, everything works fine. I have a virtual machine on Ubuntu and Chrome v50.0 and everything works fine too.

Thanks in advance

**Comment by danialfarid** [comment]
Disable plugins in Chrome or use incognito mode see if the issue exists. Also you can try creating a new profile in chrome.

**Comment by cmillauriaux** [comment]
After disable plugins, it works fine !

Thanks you
