### ISSUE TITLE
Center Crop Thumbnail

### ISSUE THREAD

**Issue by joelcdoyle** [danialfarid/ng-file-upload#1538]
`centerCrop` doesn't seem to work for `ngf-thumbnail`. I'd like to use the thumbnail as a preview so the user can see exactly how their avatar will look cropped.

```js
<div class="btn btn-default"
 ngf-select ng-model="avatarFile" name="avatarFile" ngf-pattern="'image/*'"
 ngf-accept="'image/*'" ngf-max-size="2MB" ngf-max-height="1000" ngf-max-width="1000"
 ngf-resize="{width: 200, height: 200, centerCrop: true}">
  Select
</div>

<img class="avatar-preview" ngf-thumbnail="avatarFile" ngf-size="{width:200, height:200, centerCrop: true}"/>
```

If I upload an image that is larger that 200x200 (say 214x317) the image is resized, the aspect ratio is maintained (very nice!), but the image is not center cropped. Instead, it's largest dimension is reset to 200.

**Comment by aronduby** [comment]
Was bummed to see this not supported. However it was pretty easy to fake using `ngf-background` instead of thumbnail and setting the element's `background-size: cover` and `background-position: 50%`

**Comment by danialfarid** [comment]
You can use `Upload.resize()` to create a resized center cropped image to display with ngf-src as thumbnail for now.
