### ISSUE TITLE
avoid resizing if destination mimetype is image/svg+xml (throws in firefox)

### ISSUE THREAD

**Issue by maninga** [danialfarid/ng-file-upload#1540]
Danial,

as discussed in #1509 an error is thrown on firefox with current resizing implementation when input file is in svg format `file.type !== 'image/svg+xml'` (it also happens when you use the `ngf-thumbnail` directive still on firefox)

a solution could be to avoid resizing as I propose in the pull request, but this is not complete as the thumbnail will not be resized (maybe the thumbnail should be in resized to png in this case as it is only for previewing purpose)

on other major browsers (safari, chrome), the `ngf-thumbnail` directive is working as expected, and the upload works (but you get the same image as the original, which is not a problem for the svg format)

**Comment by danialfarid** [comment]
Fixed at 12.2.0
