### ISSUE TITLE
IE8 callback unknow error

### ISSUE THREAD

**Issue by nancyway** [danialfarid/ng-file-upload#1541]
Hi,I got an error in ie8,my enviroment below:
xp system
browser:ie8
angularJS 1.2.29
ng-file-upload 12.0.1
I can get flash Id and file size,file name when I add jquery1.8.3.min.js(if i won't add jquery, I cannot get file size and flash id),I flowing the steps about old browers usage,I add shim.js and crossdomain.xml 
but when I upload file,I got unknow error in error callback function,never got success callback,could you reply me and give me some advice?

**Comment by danialfarid** [comment]
Can you log the error you get on the server side and see what data is received on the server? That might give you a clue. You can also monitor the network on that machine and see what is being sent to the server. Is the same code works on other browsers?
