### ISSUE TITLE
ngf-ratio 16:9 doesn't work, fires back validation error.

### ISSUE THREAD

**Issue by altinselimi** [danialfarid/ng-file-upload#1542]
Setting the ngf-ratio upon calling the directive to 16:9 fires a "ratio" error when validating.

**Comment by danialfarid** [comment]
Your file is probably not of that ratio.

**Comment by altinselimi** [comment]
I investigated this a bit further and it fires this error when (width property of image / 16) does not give back a natural number. I tested this with 2 files, both cropped with Photoshop to 16:9 aspect ratio. Their dimensions are as following:
#1 image: 1000x563
#2 image: 715x402

And then I tested another one with dimensions : 1280x720 and it did upload successfully without any validation error.

**Comment by danialfarid** [comment]
Use min-ratio max-ratio

**Comment by danialfarid** [comment]
Fixed at 12.2.0
