### ISSUE TITLE
ngf-blob url getting saved to mongoose apart from amazon s3 url

### ISSUE THREAD

**Issue by venkatesh39** [danialfarid/ng-file-upload#1545]
I have started learning Angular Js and using  ngFileUpload for file uploads. Thanks a lot for a great module. I have an issue. When i try to upload multiple images to amazon s3 and save s3 url to mongoose database , ngf blob url is also getting saved . Is there any solution to save only s3 url in database.

The following is the blob url :
"{\"$ngfBlobUrl\":\"blob:http%3A//localhost%3A3000/282754b4-14dd-4ed2-9795-15bc125f7576\"}"

**Comment by danialfarid** [comment]
post your code

**Comment by venkatesh39** [comment]
Sorry Danial.I made a mistake in database storing. It is working now. Thanks for your help and continue doing great work
