### ISSUE TITLE
ngf-accept is case sensitive but it shouldn't

### ISSUE THREAD

**Issue by cipianpascu** [danialfarid/ng-file-upload#1546]
When I use ngf-pattern="'image/*'" and ngf-accept="'image/*'", files with upper case extensions are ignored. I noticed this on Ubuntu OS.

**Comment by gitnik** [comment]
This is still an issue. Any update?

**Comment by danialfarid** [comment]
`ngf-accept` will just map to the normal html file input `accept` attribute so it is browser specific implementation. `ngf-pattern` is case insensitive.
