### ISSUE TITLE
A very simple (and must be stupid) issue, i cannot load the ng-file-upload succefully...

### ISSUE THREAD

**Issue by dotlog** [danialfarid/ng-file-upload#1547]
I am writing something based  on the example (single-file-upload-button):
       http://jsfiddle.net/danialfarid/0mz6ff9o/135/

However, the same code can work correctly if I paste it directly to replace the original example, but failed, if I created a new one myself:
       https://jsfiddle.net/2r7qypsL/1/

FireFox debugger indicates that there is an error:
        Failed to instantiate module TimelineData due to:
[$injector:nomod] Module 'TimelineData' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument

BTW, in my own webpage, there is no such issue reported..

There must be something missing here, stupid and I am a fresh to the web coding...

Sorry for bring this up if it takes your time...

Thanks:)

**Comment by vibesharing** [comment]
Hi, I'm getting the same error, 
did you solve it and if yes can you tell me how ?

cheers

**Comment by dotlog** [comment]
Hi Hadrien,

I solved it by finding I used two different ng-app names in different HTML
elements. It is stupid... I hope it can help..

2016-05-28 18:35 GMT+08:00 Hadrien Buret <notifications@github.com>:
