### ISSUE TITLE
call ngfSelect event when click upload button after uploaded one file

### ISSUE THREAD

**Issue by why520crazy** [danialfarid/ng-file-upload#1550]
it can't call ngfSelect event when click upload button first, i select one file and click select, it call ngfSelect even, but i click upload button second and have not chosen file,  it call ngfSelect event，files it empty，it call ngfChange event is triggered by resetModel function.

I think it should not trigger ngfSelect when second click upload button, because I did not select file.

**Comment by why520crazy** [comment]
I'm not good at English, the description may not be very clear.

**Comment by danialfarid** [comment]
That's expected behaviour. There are plenty of issues and discussions related to this.
