### ISSUE TITLE
Upload progress in Safari is not working

### ISSUE THREAD

**Issue by rabid-on** [danialfarid/ng-file-upload#1551]
Hi everyone !

During the upload I prompt a message to the user for letting him know that his file is uploading, and I remove it when the progress is ended (see below : evt.loaded == evt.total).
However in Safari, the file is uploaded successfully but the prompted message never go.

```javascript
Upload.upload({
   url: "/url/of/api",
   data: {file: file, 'name': name}
}).then(function (resp) {
   // nothing
}, function (resp) {
   // error message
}, function (evt) {
   if (evt.loaded == evt.total) {
       // remove prompted message
   }
});
```

I don't use the first response function (success response) because it happen as soon as the server is hit by the request and not at the end of the upload.

Have you any idea of how I can find a way to resolve this issue ?

Thanks :)

**Comment by danialfarid** [comment]
Could be safari bug.

**Comment by rabid-on** [comment]
Thanks for your answer !

As I said, success part was called sometimes too early (before the upload end) but I will try again this way, maybe I did something wrong last time :)
