### ISSUE TITLE
Issue with ngf-accept, ngf-pattern and accept params while using the plugin

### ISSUE THREAD

**Issue by mukulgupta2507** [danialfarid/ng-file-upload#1552]
I'm trying to use this plugin to upload pdf,ppt,doc and images in my application. I tried using ngf-accept, ngf-pattern and accept attributes but it's not working for me. While opening the selection window, I can see all the types of files which I have permiited in my accept param but when I try to select any of them, it's not working.

ng-hide="uploadedFiles.length != 0" ngf-select="" ngf-drop="" ngf-change="upload($files)" ng-model="$parent.files" ngf-multiple="true" ngf-max-size="1MB" ngf-keep-distinct="true" ngf-drop-available="true" accept=".doc, .docx, .xls, .ppt, .pps, .pptx, .txt, .pdf, image/*" ngf-accept=".doc, .docx, .xls, .ppt, .pps, .pptx, .txt, .pdf, image/*" ngf-pattern=".doc, .docx, .xls, .ppt, .pps, .pptx, .txt, .pdf, image/*"

I tried giving MIME types also in pace of actual extension but even then it's not working:

application/msword, application/vnd.ms-excel, application/vnd.ms-powerpoint, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/vnd.openxmlformats-officedocument.presentationml.presentation, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, text/plain, application/pdf,

This issue is happening only with files other than images. If I use only "image/*" for accept, ngf-accept and ngf-pattern, then it works fine.

Can anyone please help me out in this ?

**Comment by danialfarid** [comment]
accept is standard html attribute and you cannot mix extension with mime types. Remove image/ at the end. Read the standard html input file accept docs for details.

**Comment by mukulgupta2507** [comment]
I tried with mime types as well but even then it wasn't working.

**Comment by danialfarid** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input
