### ISSUE TITLE
Id's for ng-file-upload

### ISSUE THREAD

**Issue by balajicbabu** [danialfarid/ng-file-upload#1555]
Not sure whether it's possible to add id's to the each file upload button because at the moment i'm working on UI automation using protractor where accessing each of the ng-file-upload widget is quite difficult. There are 100's of file input's and there is not unique to click each one of them.

**Comment by danialfarid** [comment]
why don't you set the id?

**Comment by balajicbabu** [comment]
The problem here is that we can set the id if it's a static file upload but if the file upload button's generated dynamically then it's hard to add id's to them. For instance: in the ng-repeat, if we want to use index in the id, all of the file upload input elements will all come out as "element-id-{{index}}". So we can't distinguish them.

**Comment by balajicbabu** [comment]
try running this: 
https://jsfiddle.net/uc3mzLe0/1/
Once you get the output, click on getInputElements, you will know what i'm trying explain.

**Comment by danialfarid** [comment]
Duplicate https://github.com/danialfarid/ng-file-upload/issues/1529
