### ISSUE TITLE
Upload file zip

### ISSUE THREAD

**Issue by Florentin62** [danialfarid/ng-file-upload#1557]
Hello, I have a little problem, I can upload a zip file but how I can to unzip this file please ? A function with ng file upload ?

` apps.route('/api/image')
            .post(function (req, res) {

                var form = new formidable.IncomingForm();
                form.parse(req, function (err, fields, files) {
                        res.writeHead(200, {
                        'content-type': 'text/plain'
                    });
                    res.write('fichier recu:\n\n');
                    var chemin = files.file.path;
                    return chemin;
                    res.end({files.file.path}));

                });

                form.on('fileBegin', function (name, file) {
                    file.path =  path.join('./tmp/') + file.name;

                
                });
            console.log(chemin);
            });`

thank you

**Comment by danialfarid** [comment]
You should better do it on the server side
