### ISSUE TITLE
Drag of .docx do not apply accept class

### ISSUE THREAD

**Issue by joaocmfcm** [danialfarid/ng-file-upload#1559]
Hello, I'm having this strange issue: I can add the type of files that I want to the list of files without problem. But when it comes to drag them, the .docx files apply the reject class but are added to the list.

`<div name="files" ngf-drop ngf-select ng-model="files" class="drop-box" 
			ngf-drag-over-class="{accept:'dragover', reject: 'reject-dragover'}" ngf-multiple="true" ngf-allow-dir="true"
			accept="image/*,application/pdf,.docx" ngf-keep="true" ngf-change="filesChanged()"
			ngf-pattern="'image/*,application/pdf,.docx'" required>
				<strong>{{ 'SEND.ATTACHMENTS_PLACEHOLDER' | translate }}</strong> <br> <small>{{ 'SEND.ATTACHMENTS_PLACEHOLDER_INFO' | translate }}</small>
		</div>`

Is that a bug or am I doing something wrong?
Thanks

EDIT: 
http://i.imgur.com/OGsAIb3.gifv
As you can see I drag a .docx, an image an then a .txt. All are added or not added properly. Although the class on .docx drag is wrong.

**Comment by danialfarid** [comment]
Drag over class only works with file's mime type since it is the only thing that is reported by browser during drag. It is mentioned in the docs.
