### ISSUE TITLE
How to preview a image which size is bigger than 20000 in IE8 

### ISSUE THREAD

**Issue by andyhuang15** [danialfarid/ng-file-upload#1564]
Hello
 i have a problem which is that i can't preview the local image in IE8 when i use ng-src directive , and this image's size is larger than 20000B, and i debugger ng-file-upload-all.js file,and i find the image size has been limited in IE8. So do u have some good ways to solve this problem.
By the way ,i find this variable window.URL or window.webkitURL  is undefined in IE8.
thanks for your any help.

**Comment by danialfarid** [comment]
Yea if the size is bigger than that the browser is going to crash.
I don't know of any workarounds at the moment I suspect that it might be internal limit of IE8 on the size of image src that can be hold.

**Comment by andyhuang15** [comment]
okay, thanks for your reply. Maybe i need to find other way to solve this problem
