### ISSUE TITLE
503 Over Quota Issue

### ISSUE THREAD

**Issue by sultanrbt** [danialfarid/ng-file-upload#1566]
I am using ng-file-upload in my application like
<script src="https://angular-file-upload.appspot.com/js/ng-file-upload-shim.js"></script>
<script src="https://angular-file-upload.appspot.com/js/ng-file-upload.js"></script>

Some times I am getting issue like 503 Over Quota Issue, This application is temporarily over its serving quota. Please try again later.
attaching screen shot
Can any one please tell me whats the issue
![503](https://cloud.githubusercontent.com/assets/17764295/15885670/4fa79952-2d76-11e6-9af2-757419cd0311.png)

**Comment by dzek69** [comment]
this is server-side issue, not related to this plugin. contact your server provider, but generally this means your server hourly (or daily or something) data transfer limit.

**Comment by sultanrbt** [comment]
@dzek69 Thanks for the reply I'll check it and update. Thanks again

**Comment by danialfarid** [comment]
It means the demo server is over quota temporarily.
