### ISSUE TITLE
ng-file-upload property and method document

### ISSUE THREAD

**Issue by samtran123** [danialfarid/ng-file-upload#1567]
Hi all, first of all, I want to point out,

"ng-file-upload" (https://github.com/nervgh/angular-file-upload) is **NOT** "angular-file-upload" (https://github.com/nervgh/angular-file-upload). If anyone is confused with this as I am.

I searched for "ng-file-upload" document and Google leads to "angular-file-upload" (a lot), which makes more confusion.

Anyway, it's clear to me that the "ng-file-upload" and "angular-file-upload" are totally two DIFFERENT modules.

My question is, can anyone point me a full document of "ng-file-upload" property and method?

Thanks in advance.

**Comment by gbittmann** [comment]
You are already in the right place if you posted this comment.

The readme has lots of info [https://github.com/danialfarid/ng-file-upload](https://github.com/danialfarid/ng-file-upload)

Also the wiki [https://github.com/danialfarid/ng-file-upload/wiki](https://github.com/danialfarid/ng-file-upload/wiki)
