### ISSUE TITLE
How we can incorporate skip crop functionality? I want to save the actual image on skip crop option @danialfarid can you lease suggest how to achieve this.

### ISSUE THREAD

**Issue by hbbkatiyar** [danialfarid/ng-file-upload#1568]

**Comment by danialfarid** [comment]
What is skip crop? Explain more in the body of your message not the title.

**Comment by jeevasusej** [comment]
If u want to crop, you need extra code to do that crop.
If you don't do, then crop functionality won't be available.

Actually you have to skip to do extra code.

**Comment by danialfarid** [comment]
I still don't understand what you means. Provide some code samples.
