### ISSUE TITLE
Suggestion: Add project to jsdelivr

### ISSUE THREAD

**Issue by gbittmann** [danialfarid/ng-file-upload#1570]
Here is a link to the website if you're not familiar with it. Great project by the way.

[https://www.jsdelivr.com/](https://www.jsdelivr.com/)

**Comment by danialfarid** [comment]
It is already added https://www.jsdelivr.com/projects/angular.file-upload

**Comment by gbittmann** [comment]
Great thank you! 

I only searched by ng-file-upload, I'm new to jsDelivr so didn't realize it might have a different name.

**Comment by gRoussac** [comment]
Hi

[This package](https://www.jsdelivr.com/package/npm/ng-file-upload) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

Thanks
