### ISSUE TITLE
Working with Cordova

### ISSUE THREAD

**Issue by erperejildo** [danialfarid/ng-file-upload#1571]
Hi, first of all thanks for your plugin, it's really helpful.

I'm working in a app with Cordova which can select images from your gallery or take them from camera.
Before upload them, the user can change filters and size (canvas), but at the end of the process (when I need upload the image) I've got only an url, with the final image.

How can use this url the upload the image with no input at all?

I've seen ngf-capture="'camera'" property but as I said the user has to edit before the image.

**Comment by danialfarid** [comment]
Post on SO

**Comment by gkimpson** [comment]
@erperejildo did you do anything special to get this to work within a Cordova application - I am unable to get the camera to work using the ngf-capture="'camera'" (it just opens the photo gallery)

**Comment by erperejildo** [comment]
In my case I had to change from Cordova plugin to Meteor plugin but if you are using Cordova be aware that you follow the instructions: https://github.com/apache/cordova-plugin-camera
I also had to use a CDN like cloudinary to upload the image
