### ISSUE TITLE
File content-type excel not installed

### ISSUE THREAD

**Issue by Jensiator** [danialfarid/ng-file-upload#1572]
Hi thanks for a great directive! I just noticed that file.type is empty when you try to upload an excel file. It only happens when you don't have excel installed. Should not the file.type be 'application/octet-stream' at these situations? I tried to set the file.type myself but got: 'setting a property that has only a getter'
Jens Alenius

**Comment by danialfarid** [comment]
You can try `new File(["This is my blob content"], filename, {type : "text/plain"})` to create a new file with the correct type. You need to read the file into byte array first with FileReader api.
Or you can set the file type on the server side.

**Comment by Jensiator** [comment]
Ok thanks

**Comment by Jensiator** [comment]
That wont do if the files get big. It would mean that the data will be temp cached in the browser wont it?

**Comment by danialfarid** [comment]
Correct. But again this is browser dependent and you can open a bug for the browser that is not reporting the file type.
