### ISSUE TITLE
console error "Not a valid marker at offset 623, found: 247" when upload jpg image

### ISSUE THREAD

**Issue by andyhuang15** [danialfarid/ng-file-upload#1574]
Hi 
  i find there is some console error log which is " Not a valid marker at offset 623" when i upload some jpg image. i have debugged ng-file-upload.js file, and this error is happen in this function findEXIFinJPEG, but i don't know what's this error meaning? Could u give me some help information to solve this problem. Thanks very much.

**Comment by andyhuang15** [comment]
who know this issue ,and could give me help?

**Comment by danialfarid** [comment]
Could be an error in the jpeg file. You can disable ngf-fix-orientation or restorExif in resize.
