### ISSUE TITLE
ngf-resize cropping image on IE11

### ISSUE THREAD

**Issue by sarahduve** [danialfarid/ng-file-upload#1576]
I'm using `ngf-resize` in combination with `ngf-resize-if`:

```
 ngf-resize="{quality: .5}"
 ngf-resize-if="$width > 1000 || $height > 1000"
```

This is working fine on Chrome, Safari, and Firefox, but for some reason on IE it is square cropping the image.

Original: https://styleitpretty.files.wordpress.com/2013/09/blog3.jpg
Resized on IE11: https://s3.amazonaws.com/crowdtap-assets/action/media_attachments/images/575ed9ff1e1b9f122c000270/original.jpg?1465833981

Any ideas? The shim is already included in the Gulpfile.

**Comment by danialfarid** [comment]
Can you create a jsfiddle with steps to reproduce.
