### ISSUE TITLE
Certain CSS properties causes image to get smaller is causing image to collapse to tiny sizes.

### ISSUE THREAD

**Issue by jaesung2061** [danialfarid/ng-file-upload#1579]
If I add any kind of property like `padding` or `border`, it'll cause images to collapse to the smallest size until its only the border or padding.

Adding Bootstrap `img-thumbnail` class will cause image to collapse all the way. I've pinned it down to `padding` and `border` (either or). Right clicking and opening the image in a new window also shows the same shrunken image.

**Comment by danialfarid** [comment]
Set the width and height on the img element

**Comment by jaesung2061** [comment]
What about for images that vary in resolution?

**Comment by danialfarid** [comment]
well you need to fit it in a box, so you can use centerCrop option to customize how it is fit.

**Comment by peteringram0** [comment]
Im also seeing this issue. The centerCrop work around does not seem to work.

**Comment by danialfarid** [comment]
Create a jsfiddle with steps to reproduce if you still have this issue.
