### ISSUE TITLE
Tiff Thumbnail Issue

### ISSUE THREAD

**Issue by infrarosso78** [danialfarid/ng-file-upload#1583]
I am trying to show a thumb preview of the images user will upload but of course I've problem with tiff files. Is there anyway to do it? or eventually to show a default picture in case the user is trying to upload a tiff?

**Comment by danialfarid** [comment]
Does `ngf-thumbnail="file || defaultImageUrl"` works to show default image?

**Comment by infrarosso78** [comment]
(First of all thanks for the fast reply) It dosen't work. I guess because file is indeed defined

**Comment by danialfarid** [comment]
`"(file && file.type != 'image/tiff') || defaultImageUrl"`

**Comment by infrarosso78** [comment]
Thanks a lot. It worked partially. It's good to show another picture in case of tiff but doesn't show any jpg, gif, png, etc images. I fixed like this (hope it can be helpful to someone else):
`img.upload-thumb(
            ng-if="file.type != 'image/tiff'"
            ng-show='uploadForm.file.$valid'
            ngf-thumbnail="file"
            ngf-size="{width: 120, height: 140, quality: 0.9}")
 img.upload-thumb(
            ng-if="file.type == 'image/tiff'"
            ng-show='uploadForm.file.$valid'
            ngf-thumbnail="(file && file.type != 'image/tiff') || 'defaultImageUrl'"
            ngf-size="{width: 120, height: 140, quality: 0.9}")`
