### ISSUE TITLE
Trouble with overwriting the aHrefSanitizationWhitelist 

### ISSUE THREAD

**Issue by danxshap** [danialfarid/ng-file-upload#1584]
There was a previous issue about this at https://github.com/danialfarid/ng-file-upload/issues/1014 which was "fixed", seemingly by having the relevant lines commented out in https://github.com/danialfarid/ng-file-upload/commit/df94b03681fcce413d67fd5439ff045dbba9650d, but then they were un-commented in https://github.com/danialfarid/ng-file-upload/commit/9f5c4697bc5fa6b3f84bcfd3292b00053615e679 and now the same issue remains.

In our case, we use `webcal://` links in the same app as `ngFileUpload`, so our own config to add "webcal" to the whitelist was being overriden by ngFileUpload's, which was being run afterward because it comes later in the dependency list.

Our current solution to this, which is not pretty, is the following module:

```
// ng-file-upload overrides this and does not include "webcal", so to get our webcal links to work on pages
// that use ng-file-upload, we need to use their pattern (https://github.com/danialfarid/ng-file-upload/blob/master/src/data-url.js)
// and add "webcal" to it. Furthermore, this module must be included in the dependency list AFTER the last module
// that depends on ngFileUpload so that this config function runs last.
angular.module('urlSanitizationOverride', []).config(['$compileProvider', function($compileProvider){
    $compileProvider.aHrefSanitizationWhitelist(/^\s*(https?|ftp|mailto|tel|local|file|data|blob|webcal):/);
}]);
```

Is there a better solution here? Perhaps some user-facing ngFileUpload config/setting that takes extra URL prefixes and adds them to the whitelist for you?

**Comment by danialfarid** [comment]
Should be fixed at 12.1.0
