### ISSUE TITLE
ngf-pattern="'application/pdf'" not working on IE 11

### ISSUE THREAD

**Issue by gauravermax** [danialfarid/ng-file-upload#1585]
Hi 
Requirement to stop any files other than PDF. The code works fine in chrome but i get pattern error in IE11 (edge mode). 

I am stuck and everything works if i remove the ngf-pattern from html view. Can anyone advise if i need to so something special for IE 11 ?

**Comment by danialfarid** [comment]
What's the mime type of the file in IE11?

**Comment by gauravermax** [comment]
Hi Danial

Can you please advise how to fine the mime type. i havnt changed any thing so it must be default.

**Comment by gauravermax** [comment]
Hello 
The same works after i change the ngf-pattern to ngf-pattern="'.pdf'"

**Comment by danialfarid** [comment]
You can print `file.type` to see its type. Probably IE11 does not have a type for pdf files so ".pdf" seems like a good workaround.
