### ISSUE TITLE
ngf-max-files not working when value is set to method in scope

### ISSUE THREAD

**Issue by dackmin** [danialfarid/ng-file-upload#1586]
Hi !

I came across this fluffy one this morning : When I set ngf-max-files to watch for a method into my scope, it only keeps the first returned value.

Assuming we have `ngf-max-files="get_rooms_count()"` and that `get_rooms_count()` returns 0 at first digest, if I update some models and `get_rooms_count()` now returns 10, `ngf-drop` still doesn't accept more than 0 files (which is... kind of blocking haha). Btw, `ngf-select` works great, even if `get_rooms_count()` value changes.

I'll try to do a plunkr if you need it.

Cheers,
Ugo

**Comment by danialfarid** [comment]
jsfiddle would help

**Comment by dackmin** [comment]
Here you goooo : http://jsfiddle.net/a0tjc12f/

Steps to reproduce :
- Try to drop an image in the box when count is on zero : no image is added.
- Increment count with "Test" button
- Then retry to drop images : no image is added either

FYI, when I increment count before trying to drop a first image, it works fine.

**Comment by dackmin** [comment]
Any news about this ? :)

**Comment by dackmin** [comment]
Great news haha thx

**Comment by danialfarid** [comment]
Fixed at 12.2.0
