### ISSUE TITLE
Runtime exception in IE 9 - File upload ( working in chrome,ie10-11)

### ISSUE THREAD

**Issue by gauravermax** [danialfarid/ng-file-upload#1587]
Hi
I am working on IE 11 and everything works fine. When i changed the document mode to IE9 and try to upload the file i get a runtime error. i.e.

Unhandled exception at line 85801. This is refering the js file.

The fileList value is coming as undefined. Please advise. (code attched below)

    function changeFn(evt) {
      if (upload.shouldUpdateOn('change', attr, scope)) {
        var fileList = evt.__files_ || (evt.target && evt.target.files), files = [];
        for (var i = 0; i < fileList.length; i++) {
          files.push(fileList[i]);
        }
        upload.updateModel(ngModel, attr, scope, fileChangeAttr(),
          files.length ? files : null, evt);
      }
    }

**Comment by danialfarid** [comment]
Document mode IE9 is not supported.

**Comment by gauravermax** [comment]
Thanks Danial
Please confirm if the same would work on IE9 browser. I was just trying to imitate the behavior of IE on my dev machine. 

Also i see the flash file and  js but dont understand if i need to do anything special to make it work on oold browsers ?

**Comment by gauravermax** [comment]
Most of the blogs says flash player would be used for making it work on IE9. As per the description i have checked and confirm that there are  FileAPI.min.js ,  FileAPI.flash.swf  at the same path as  angular-file-upload-shim(.min).js ..

Now what should i do to force IE9 demand Flash player and use FileAPI calls. any sample example would be appreciated.

**Comment by danialfarid** [comment]
It would only work on real IE9. Running on the compatibility mode may not work as expected. The demo page works in IE9. You can use that as reference. Read the part about Old Browsers in the docs. The shim file will be automatically loaded if XMLHttpRequest is not available.

**Comment by gauravermax** [comment]
Hi Danial,

I just noticed something. If i open your sample demo on IE 11 ( ie 9 compatability mode) it works and it calls the Flash API. Which means for some reason my code is not behaving the same. I read the Old browser section but i am struggling to understand the settings. 

The article says there need to be two more files  FileAPI.min.js ,  FileAPI.flash.swf   at the same location as angular-file-upload-shim(.min).js . I have checked and its there. They are all under bower_components\ng-file-upload path. We are using Bower to handle the scripts.

Do we need to refer these files and add them in gulp.config ??

**Comment by gauravermax** [comment]
okey somehow i manage to add the files and flash api call is happening for ie9 compatible mode. Now i get a new error on the same : 
ngFileUpload: Circular reference in config.data. Make sure specified data for Upload.upload() has no circular reference: file[blob][jQuery223030319713400116162][$ngModelController][$viewValue] undefined

please advise. i am using the latest version

**Comment by danialfarid** [comment]
test with real IE9

**Comment by gauravermax** [comment]
Hi Damial,

I have got real IE9 and my componet is still giving me the error above. I belive this may be caused due to Flash component not getting loaded. 

I have made sure that we have FileAPI.min.js , FileAPI.flash.swf at the same location as angular-file-upload-shim(.min).js. I have added FileApi.js and shim.js in the bower config to include the same in .js.

To Confirm the following two steps are needed for the fileupload to work on ie9 and load flash: 
1. We just need to make sure we have the above mention 2 files at the same location as shim.js
2. shim.js and fileapi.js file need to be available at page. 

I think i am missing some piece of puzzle which i couldnt figure out. Please advise ?

**Comment by gauravermax** [comment]
Another lead 
I used the force flash on chrome and ie. Thedemo applicaiton has the folllowing logs 
LOG: FlashAPI.state: awaiting 
LOG: (flash -> js).log: storeKey=5090616450220507274040_2.0.7 
LOG: (flash -> js).log: timeout=0 
LOG: FlashAPI.state: ready 

Where as my application ONLY says Awaiting. I am trying to debug the same but struggling to fgure out why its not running.

**Comment by gauravermax** [comment]
The fix for above issue was the code was trying to find the flash file at a incorrect place. I fix the path and the flash started to work :)

Now stuck  in upload issues . Getting the following log : 

LOG: (flash -> js).log: fileReference.upload onError: [IOErrorEvent type="ioError" bubbles=false cancelable=false eventPhase=2 text="Error #2038"] 
LOG: FlashAPI.upload.error 
LOG: xhr.end: 0 IOError [IOErrorEvent type="ioError" bubbles=false cancelable=false eventPhase=2 text="Error #: [IOErrorEvent type="ioError" bubbles=false cancelable=false eventPhase=2 text="Error #2038 


This looks like some adobe thing. Any idea ??

**Comment by zd5043039119** [comment]
i use real ie 9(version:9.0.8112.16421),but occur the same problem, evt.target.files is undefined,because in ie 9,the attr "files" is not supported

**Comment by danialfarid** [comment]
@zd5043039119 make sure you follow the steps for older browsers and have the shim files included and FileAPI files in the correct path. Read the docs seems like you are not including the shim properly.

**Comment by danialfarid** [comment]
Not much time to investigate this. If you find any new clues reopen this.
