### ISSUE TITLE
How do I access an error if I use ngf-select with only single file support and the element not on a form? 

### ISSUE THREAD

**Issue by Kabangi** [danialfarid/ng-file-upload#1589]
`<div class="button" ngf-select="upload($file)" ng-model="file" name="file" ngf-pattern="'image/*'"
    ngf-accept="'image/*'" ngf-max-size="20MB" ngf-min-height="100" 
    ngf-resize="{width: 100, height: 100}">Select</div>`

**Comment by danialfarid** [comment]
`file.$error`
