### ISSUE TITLE
Upload direct from outlook

### ISSUE THREAD

**Issue by johntom** [danialfarid/ng-file-upload#159]
Hi,
First, thanks for the wonderful directive as I make use of it in my production code. I'd like to know if it's possible to drag an email directly from outlook for the upload. Currently, the  upload requires that I make an initial drop to desktop, wondering if possible to get the stream data.
TIA
John

**Comment by ptitdje45** [comment]
Did this has been solved ?

**Comment by ramarathna** [comment]
Hi ,

I have a similar requirement where I would have to drag the email from outlook and drop it on the browser directly rather than saving it on desktop.Is this possible in some way?

Thanks & Regards
Ramarathna B C
