### ISSUE TITLE
not uploading file in safari

### ISSUE THREAD

**Issue by VikramSisodiya** [danialfarid/ng-file-upload#1592]
I am using your FileAPI with below FileAPI js but in safari page cant upload any image and load it and no error comes in console.

version 1.2.8 AngularJS file upload shim
FileAPI : https://cdnjs.cloudflare.com/ajax/libs/danialfarid-angular-file-upload/1.4.0/FileAPI.min.js
Can you guide me through this problem?

**Comment by danialfarid** [comment]
post your code here
