### ISSUE TITLE
Image on ngf-resize does delete the exif information

### ISSUE THREAD

**Issue by kriebb** [danialfarid/ng-file-upload#1594]
I fixed this in my local version. We use the version  with bower:

> "ng-file-upload": "12.0.4",

The following code should be applied:
```

if (file && file.type && file.type.search(getTagType(elem[0])) === 0 &&
          (!isBackground || file.type.indexOf('image') === 0)) {
          if (size && Upload.isResizeSupported()) {
            Upload.resize(file, size.width, size.height, size.quality,undefined,undefined,undefined,undefined,size.restoreExif).then(
              function (f) {
                  constructDataUrl(f);
                  
              }, function (e) {
                throw e;
              }
            );
```

In the above copy,

Original code is the following

>       Upload.resize(file, size.width, size.height, size.quality)

and this is the line of code to replace it with
>       Upload.resize(file, size.width, size.height, size.quality,undefined,undefined,undefined,undefined,size.restoreExif)

And then you will not lose the exif information if you use this as followed:

```
  <img ngf-src="picture"
                                                     ngf-no-object-url="false"
                                                     ngf-resize="{width: 640, height: 480, centerCrop:false, restoreExif:true}"
                                                     alt="Reszing...." />

```

Happy coding. So I don't only supply the problem. Also the solution :)
If this is not the way, I'm looking forward to your comments.

**Comment by danialfarid** [comment]
Fixed at 12.2.0
