### ISSUE TITLE
Image resize occurring before upload

### ISSUE THREAD

**Issue by JamesTPF** [danialfarid/ng-file-upload#1596]
Hi,
We are using ng-file-upload to do client side image resize and exif rotation.
We have a spinner that is tied into active http requests.

This means that when our users select several large images to upload, then there is a long delay between them selecting upload and the spinner appearing.

Is there a way to receive an event from ng-file-upload for when the user has clicked upload?
Otherwise, would it be better to do resize and file upload together to avoid the large delay before uploading?

Has anyone else found ways around this issue?
Thanks.

**Comment by danialfarid** [comment]
Use ngf-before-model-change read the docs and there are already similar issues with answers
