### ISSUE TITLE
errorFiles considering invalid files as valid

### ISSUE THREAD

**Issue by snehaRCanvera** [danialfarid/ng-file-upload#1598]
Hi,

http://jsfiddle.net/czc6oays/

Please refer to the above fiddle. The error here is i have a ngf-max-size option given and nfg-max-files. The errorFiles model is considering even the invalid files as valid. One way to reproduce this is 
1. In your images folder, the first 2 images are of size greater than 12MB.
2. Next, suppose the ngf-max-files is set to 6 and the subsequent images are valid images only 4 images get added in the model. The errorFiles here counts 6(2 invalid + 4 valid) images which has reached the ngf-max-files which is 6. 

It should be ideally functioning as upload all valid images and not count the previous invalidFiles. Please look into this and let me know if you need more clarity on this.

**Comment by danialfarid** [comment]
known issue will be fixed soon: https://github.com/danialfarid/ng-file-upload/issues/1521
