### ISSUE TITLE
"Stupid" users can crash Chrome when uploading

### ISSUE THREAD

**Issue by proreact-mj** [danialfarid/ng-file-upload#1600]
Hi. 

Looking at the official example: http://jsfiddle.net/danialfarid/s8kc7wg0/400/ (Drop and upload with $watch). (verified in Chorme across several machines and Windows versions, not reproducible in Edge) 

If you press the dropfile area, to open the "open" dialog, then proceed to _drag_ images over in the dropfile area and _while they are processing_, close the dialog _with the "open" button_, then the page crashes the browser. 

I know that this is ultimately caused by stupid users, but it is pretty annoying anyway and I'm getting quite some support headaches explaining why they should not do it like that, cause i have to agree, that it is convenient to open the explorer view and then dragging files over. 

Any suggestions on how to work around?

**Comment by katemihalikova** [comment]
Works fine on my box (Win10, Chrome51) - the file is processed twice, but no crash happens.

**Comment by proreact-mj** [comment]
Just checked again. Problem still there Win10 / Chrome52.

Not that is does not crash pr say, the browser **hangs** (like stuck in a loop)

Reproduction:
Press the drop area to open the dialog
Select multiple files (images?) from the "open" dialog and drag them over to the drop area. 
While the dragged files are processing immediately hit "open"-button in the "open"-dialog
Browser hangs immediately after this

**Comment by katemihalikova** [comment]
OK I can confirm it hangs the browser when using the latest reproduction steps (Win10, Chrome52).

**Comment by danialfarid** [comment]
Not much to be done on the module level. It is more like a browser bug.
