### ISSUE TITLE
How to upload image to a web service on a server?

### ISSUE THREAD

**Issue by raysefo** [danialfarid/ng-file-upload#1601]
Hello,

On my IOS mobile application I am taking picture and then select a picture from gallery. After selecting this picture I am using ng-img-crop.js to crop this image and without saving this cropped image, trying to upload it to a server via web service (wcf). (In this particular example I am trying to upload local IIS) But I am getting this error:

ERROR: {"code":1,"source":"data:image/png;base64,iVBORw0KGgoAAAANSUhE...","target":"http://11.111.11.111/wcf/OCRService.svc/upload","http_status":null,"body":null,"exception":null}
app.js (76,24)

Is there a way to do this?

Best Regards.

**Comment by danialfarid** [comment]
Post on SO.
