### ISSUE TITLE
Question: Can i stringify file object?

### ISSUE THREAD

**Issue by hotrush** [danialfarid/ng-file-upload#1605]
I am trying to serialize File object with JSON.stringify, but losing lot of data. Maybe some magic needed when parsing this json?
```
console.log(file);
console.log(JSON.stringify(file));
console.log(JSON.parse(JSON.stringify(file)));
```
![1467737094016](https://cloud.githubusercontent.com/assets/1247004/16592360/fa0dd4f6-42e8-11e6-9063-742129d219be.jpg)

**Comment by hotrush** [comment]
that is not possible

**Comment by warodri** [comment]
You have options...

function stringifyFileObject(arrWithFiles = []) {
  const arrData = [];
   for (let i=0; i < arrWithFiles.length; i++) {
    const file = arrWithFiles[i];
    const obj = {
        lastModified: file.lastModified,
        name: file.name,
        size: file.size,
        type: file.type,
        webkitRelativePath: file.webkitRelativePath,
    }
    arrData.push( obj );
  }
}
