### ISSUE TITLE
Send original imagen and crop at the same time

### ISSUE THREAD

**Issue by gomezv9** [danialfarid/ng-file-upload#1606]
Hi

In this example : [http://jsfiddle.net/danialfarid/xxo3sk41/590/], I'm trying to figure out, how could I send the original image and the crop image to the server at the same time ?

Any help ..

Thanks

**Comment by danialfarid** [comment]
```
data: {
                file: Upload.dataUrltoBlob(dataUrl, name),
                origFile: $scope.picFile
            },
```
