### ISSUE TITLE
How to use this Plugin

### ISSUE THREAD

**Issue by anshul-budhiraja** [danialfarid/ng-file-upload#1609]
Hi @danialfarid ,

I am bit confused in how to use this package. I am trying to test a simple file upload. My app is on meteor-angular and deployed on an amazon machine. I am using package https://atmospherejs.com/danialf/ng-file-upload.

I've few questions:
1. Do I need to do any server side code or just adding this package and updating view and controller will work.
2. What is Upload URL. I believe its the path where I want to put my uploaded files. Input for this in controller will be  "http://myserver/folderloc" or its "folderloc/upload". I tried both. http thows error. and another one giving Success message but no file on the location.
3. As I said my app is in meteor-angular so port 80 is busy on server in serving my app. I looked into http://jsfiddle.net/danialfarid/maqbzv15/1118/. Give path to my server with port 81 but no success because other ports are block.

**Comment by gbittmann** [comment]
1. You need server side code to accept the file.

2. The Upload URL is the endpoint used to handle the file upload.

3. He has examples for a few languages, not meteor but maybe one of those will help you get an idea of what is needed. 

[https://github.com/danialfarid/ng-file-upload/wiki](https://github.com/danialfarid/ng-file-upload/wiki)
