### ISSUE TITLE
no $ngfBlobUrl when used with ngf-resize

### ISSUE THREAD

**Issue by dtiwan** [danialfarid/ng-file-upload#1613]
I am using version 12.0.4 and with html code
`<button type="file" ngf-select="uploadFiles($file, $invalidFiles)" accept="image/*" ngf-max-height="1000" ngf-max-size="1MB" ngf-resize="{height: 480, centerCrop: true}">Select Files</button>`

I do not get $ngfBlobUrl in my file object. Rather the file object looks like
`{"$ngfName":"Chrysanthemum.jpg","$ngfOrigSize":879394}`

But when I do n use the ngf-resize option, I get the $ngfBlobUrl.

Any help will be highly appreciated.

Thanks,

**Comment by danialfarid** [comment]
Does fields are for internal use only and could change at any time. Use the api and services provided in the docs. You can use `Upload.dataUrl(file)` or similar services mentioned in the docs.

**Comment by nguyenmanhtuan93** [comment]
I want to take the value of $ngfBlobUrl
Like:
```
File {
   $$hashKey:"object:23"
   $ngfBlobUrl:"blob:http://localhost:54138/6f115952-6481-42ab-823d-f0a54c413dbc"
   lastModified:1492927243028
   lastModifiedDate:Sun Apr 23 2017 13:00:43 GMT+0700 (SE Asia Standard Time)
   name:"abc.avi"
   size:0
   type:"video/avi"
   webkitRelativePath:""
   __proto__:File
```
and $ngfBlobUrl = "blob:http://localhost:54138/6f115952-6481-42ab-823d-f0a54c413dbc"
Please, help me!!!
