### ISSUE TITLE
Cannot Upload STL Files

### ISSUE THREAD

**Issue by efifogel** [danialfarid/ng-file-upload#1614]
Hi, 

I have a problem uploading files in the STL format. A file in this format contains a description of a 3D model. It is used for 3D printing.
I'm using ng-file-upload version 12.0.4.
The mime types are specified as follows:

           ngf-pattern="'application/vnd.ms-pki.stl,application/sla,model/vrml'"
           accept="application/vnd.ms-pki.stl,application/sla,model/vrml"

Apparently, uploading STL files works fine on Ubuntu running Firefox and also running Chrome Version 51.0.2704.106 (64-bit). 
It fails on Windows running Edge (IE) and Chrome same version as above. The failure occurs immediately upon selection. Notice that the specification of mime types above include VRML file. Everything works fine when I upload VRML files both on Ubuntu and on Windows with all common browsers.
(The 'accept' attribute above does not make a difference. That is, the problem persists even when the accept attribute is omitted.)

I don't know whether the problem is related to ng-file-upload. Even if not, perhaps someone can share some information on how to fix this problem.

Thanks in advance,
Efi

**Comment by danialfarid** [comment]
What is the failure? The browser probably does not recognize that type of file. You can try filtering it by extention "`'.stl'"

**Comment by efifogel** [comment]
Hi Danial,

The file selection fails. See the entire div element below.
When I add "`'.stl'" it works.
I wonder what part of the system is responsible for not recognizing the
mime type of stl files.
Note that I run the same version of chrome on Ubuntu and on Windows (8.1).
It works on the former, but fails on the latter.

Thanks a lot for responding and for the entire component,
Efi

<div class="drop-box upload-drop-box" ngf-drop ngf-select ng-model="files"
           ngf-drag-over-class="dragover" ngf-multiple="true"
           ngf-keep="true" ngf-keep-distinct="false"
           ngf-allow-dir="true" type="file" ngf-max-size="16MB"

ngf-pattern="'.stl,application/vnd.ms-pki.stl,application/sla,application/netfabb,model/vrml'"

accept=".stl,application/vnd.ms-pki.stl,application/sla,application/netfabb,model/vrml"
       ngf-model-invalid="errorFiles">



   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/
