### ISSUE TITLE
Click not triggering on iOS

### ISSUE THREAD

**Issue by Jrubensson** [danialfarid/ng-file-upload#1615]
Trying to use this plugin with AngularJS 1.5.7, using the latest version of ng-file-upload. I am not able to click and choose a file on iOS 9, using an iPhone 6 (only version I've tried so far). All works fine in every browser I've tried, and on Android running Chrome. 

The code I am using is this:  

`<div ngf-change="vm.checkFileSize();" style="z-index: 999999;"
			ngf-drop ngf-select accept="video/*" ngf-keep="false" ng-model="vm.video.file"
			ngf-drag-over-class="dragover" ngf-multiple="false" ngf-allowed-dir="false" 
			ngf-accept="'video/*, video/mp4, video/x-m4v'"
			class="txt-center pointer">
	CLICK HERE TO UPLOAD
</div>`

**Comment by amritk** [comment]
I am experiencing this bug as well. I found that it works with input but not with button or anything else.
works:
`<input type="file" ngf-select="vm.uploadFile($file)" accept="image/*">`

doesn't work:
`<button type="file" ngf-select="vm.uploadFile($file)" accept="image/*">click me</button>`

My  "fix" was to just position absolute an invisible input on top of the button for iOS

**Comment by amritk** [comment]
Check out this issue: https://github.com/danialfarid/ng-file-upload/issues/1049
