### ISSUE TITLE
How to upload file to localhost 

### ISSUE THREAD

**Issue by oro77** [danialfarid/ng-file-upload#1617]
I am using an Apache server and I would like to upload a file which is in my local drive.
Here is the code I am using : http://jsfiddle.net/danialfarid/0mz6ff9o/135/
For the upload location folder, I changed the "file.upload = Upload.upload url" to http://localhost:80/ngfile/upload, I am not sure if it is right but I guess it is the upload location.

When I select my file, the filename displays and the progress bar goes to 100%. I have checked my browser console and there is no error but my ngfile/upload folder remains empty.

I think I did not get some fundamentals about ng-file, I would be glad. if someone could enlighten me

**Comment by ja-cardoso** [comment]
You need server-side code to handle the file:
e.g with node: https://github.com/danialfarid/ng-file-upload/wiki/node.js-example

**Comment by ghost** [comment]
i have got html and css files can i uplaod it to local host
