### ISSUE TITLE
Unable to correctly upload to ownCloud

### ISSUE THREAD

**Issue by uname8** [danialfarid/ng-file-upload#1618]
Hi,

I am facing issues while trying to upload files (text, images, documents etc.) to ownCloud server.

For a file with name **t1.txt** with contents **a text file** it is showing up

------WebKitFormBoundaryXTNL8QBW5Zb1YM75
Content-Disposition: form-data; name="file"; filename="t1.txt"
Content-Type: text/plain

a text file
------WebKitFormBoundaryXTNL8QBW5Zb1YM75--

in the uploaded file.

Same goes for images and documents.

Below is my html code.

```
<div class="container" ng-controller="upload">
<form name="form">
  Single Image with validations
  <input class="button" ngf-select="upload($file)" ng-model="picFile" name="file" ngf-accept="'*'" required="" type="file">
              <i ng-show="myForm.file.$error.required">*required</i>
  <div class="" style="border:2px solid green; width:400px; height:200px;" ngf-drop="uploadFiles($files)" ngf-drag-over-class="'dragover'" ngf-multiple="false">
</form>
</div>

```

and the js code
```

angular.module('ocWebApp').controller('upload', ['$scope', 'Upload', '$http', '$q', function ($scope, Upload, $http, $q) {
//  angular.module('ocWebApp').controller('upload', ['$scope', 'Upload', '$timeout', '$http', function ($scope, Upload, $timeout, $http) {
    // upload later on form submit or something similar
    $scope.serverRoot = '../../owncloud/';
    $http.defaults.withCredentials = true;
    $scope.submit = function() {
      if ($scope.form.file.$valid && $scope.file) {
        $scope.upload($scope.file);
      }
    };

    $scope.upload = function (file) {
          Upload.upload({
              url: $scope.serverRoot + 'remote.php/webdav/' + file.name,
              data:{file:file},
              method: 'PUT'
          }).then(function (resp) {
            console.log(resp);
              console.log('Success ' + resp.config.data.name );
          }, function (resp) {
              console.log('Error status: ' + resp.statusText);
          }, function (evt) {
            console.log(evt);
              var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
              console.log('progress: ' + progressPercentage + '% ' );
          });
    };
}]);
```

Please note, since ownCloud uses Basic Authentication, i have added  `$http.defaults.withCredentials = true;` as well

I have tried replacing and trying various combinations of `data:{file:file},` and `data:file,` but no help.

ownCloud version: 9.0
ng upload: latest from master

**Comment by danialfarid** [comment]
What the issue is?

**Comment by uname8** [comment]
When uploading a file **t1.txt** that has the text contents **a text file** from local machine,
it is showing up on remote as **t1.txt** with the below contents

------WebKitFormBoundaryXTNL8QBW5Zb1YM75
Content-Disposition: form-data; name="file"; filename="t1.txt"
Content-Type: text/plain

a text file
------WebKitFormBoundaryXTNL8QBW5Zb1YM75--


I dont want the WebKitFormBoundary information, I just want the text contents.

Same goes for any other files like, image or document.
file data gets appended with WebKitFormBoundary information on the ownCloud server.

Since local and remote files are not same as WebKitFormBoundary information is appended, how to deal with this.

**Comment by pjmeadmtu** [comment]
This is not an issue with the ng-file-upload directive.  This is an issue with the way your server is handling the request.
