### ISSUE TITLE
Accepting a content type of 'audio/mp4' allows video content as well.

### ISSUE THREAD

**Issue by parkej60** [danialfarid/ng-file-upload#1619]
When I set ngf-accept to allow 'audio/mp4' it also allows video content to be selected to be updated. According to http://www.rfc-editor.org/rfc/rfc4337.txt this is a correct designation. Is this something that can be added?

**Comment by danialfarid** [comment]
`accept` is browser dependent implementation and we don't have control over how the popup browser works in different browsers.
