### ISSUE TITLE
ios mutliple file upload can not delete or add additional photos

### ISSUE THREAD

**Issue by richardsamuellopez** [danialfarid/ng-file-upload#1623]
On ios any picture is added as image.jpeg. If you add multiple files and click on one to delete it all the pictures are deleted, because they are named image.jpeg. 
Also after adding multiple files if you click to choose more the newly selected files are in place of the previous files.

**Comment by danialfarid** [comment]
That's the logic of your deletion. You can add unique id or check the file reference or index instead of the name. For the second you can use ngf-keep.
