### ISSUE TITLE
Where to add error situation handling code?

### ISSUE THREAD

**Issue by shurui91** [danialfarid/ng-file-upload#1625]
I wonder where and what should I add in order to do error handling like network disconnected? Maybe setup a timeout function. My workstation's network situation is not that good. Thanks!

**Comment by shurui91** [comment]
I saw a $timeout variable in the controller part, I wonder what its output gonna be and how would I be able to modify the output if $timeout is active?

**Comment by danialfarid** [comment]
once the request times out you will get an error in your promise chain.

**Comment by shurui91** [comment]
I wonder if I can customized the error message.

**Comment by danialfarid** [comment]
You can detect the status code of the error or error message and if it is timeout you can set a scope variable to show the specific error.
