### ISSUE TITLE
Is there  way to change the style of the "Choose file" button?

### ISSUE THREAD

**Issue by cmacdonnacha** [danialfarid/ng-file-upload#1626]
Just wondering if there's a way to change the default style of the "Choose file" button?

![image](https://cloud.githubusercontent.com/assets/9777763/16998223/6127ea82-4eb0-11e6-9559-2a68bd5fd7fb.png)

**Comment by shurui91** [comment]
I think this has nothing to do with this Angular directive. This is pure CSS stuff.
