### ISSUE TITLE
prevent fileChange if file is null

### ISSUE THREAD

**Issue by krusk8** [danialfarid/ng-file-upload#1629]
ng-file-upload/src/model.js
in row 140, you must chek if file is null to prevent update callback.

 if (fileChange) {

must be : 

if (file && fileChange) {

**Comment by danialfarid** [comment]
What issue does it resolve? Can you create a jsfiddle or steps to reproduce?

**Comment by krusk8** [comment]
Hi Danialfarid, thank you for reply, and thank you for the plugin.

You can use : Upload single file on file select: http://jsfiddle.net/danialfarid/0mz6ff9o/135/

place a brackpoint in file top/result/fiddle.jshell.net/danialfarid/0mz6ff9o/135/show/index
row 84         $scope.f = file;

1)First time you click on "Select FIle" button the modal will open, you'll choose the file, and then click on "Open" button. Now the function "$scope.uploadFiles = function(file, errFiles)" will called and you have in param "file" the file selected. Everything is OK

2)If you click for the second time on "Select File" button the modal will open, and the function  "$scope.uploadFiles = function(file, errFiles)" will called, but in param "file" you have Null, because you have not chose it yet. When you chose the file and click on "Open" the function "$scope.uploadFiles" will called another time with the right param file. So you have to prevent to fire the callback if the file is null. I don't have tested the multifile upload, but only the single file, maybe my solution fit ok only for it.

Have a nice day. and sorry for my little English

Mirko

**Comment by danialfarid** [comment]
It is expected behaviour. When you click on the button it will empty the previous files so that's why you get a null file change. To prevent this you can use `ngModelOptions="{updateOn: 'select drop'}"` (not including click) there are plenty if similar threads and mentions in the docs.
