### ISSUE TITLE
Select existing video is empty in iOS devices

### ISSUE THREAD

**Issue by cavarzan** [danialfarid/ng-file-upload#1630]
Hi!

When I select a video (.mp4) from an iOS device, the file comes empty. 

Images and etc are working normally (including take video/photo from camera). Just for existing videos files, the content is empty.

In this case I can't show a preview / upload the media.

Does anyone got the same behavior?

![image](https://cloud.githubusercontent.com/assets/3915288/17146335/6e6bb826-5334-11e6-9e64-577de967507c.png)

![image](https://cloud.githubusercontent.com/assets/3915288/17146375/9a1de57a-5334-11e6-827b-8ea5bd08b8cf.png)

```
               <button
                        ngf-select
                        ngf-fix-orientation="true"
                        ngf-change="enqueueFiles($files)"
                        ngf-multiple="true"
                        ngf-accept="'*'"
                        class="button button-small button-icon" >
                        <i class="icon ion-image positive icon-share-options" ></i>

                    </button>

```

**Comment by cavarzan** [comment]
OK, notice that works if I remove `ngf-multiple="true"`... is any option for use multiple with videos?

**Comment by danialfarid** [comment]
you probably not showing the preview correctly in case of multiple files. post your code.

**Comment by cavarzan** [comment]
@danialfarid OK! 

It works for images and camera. Only videos came as a 0 size file object.

```
<button
   ngf-select
   ngf-fix-orientation="true"
   ngf-change="enqueueFiles($files)"
   ngf-accept="accept"
   ngf-pattern="pattern"
   class="button button-small button-icon" >
   <i class="icon ion-image positive icon-share-options" ></i>

</button>
<video controls ngf-src="file" ></video>


$scope.enqueueFiles = function (files) {

    $scope.file = files[0]; 
    // this $scope.file has a file size of 0

 };

```

**Comment by danialfarid** [comment]
Upload another video that is not zero size.

**Comment by cavarzan** [comment]
But the videos are not 0 size at the gallery, it's a normal video with ~4MB. Same video in chrome / android works well.

**Comment by danialfarid** [comment]
Could be iOS browser bug. Search for similar bugs in the browser you are using on iOS.

**Comment by ycgmarket** [comment]
i found the same issue since version 12.2.5

**Comment by darxmac** [comment]
I've been having strange issues with videos uploaded from iOS/ Safari as well, and here is what i found out:

If the user is using iCloud Photo Library and the video file had been purged, and the user then tries to upload it, fails when `multiple="multiple"` is set. When not set to multiple files, it works.

It's probably a strange browser/iCloud Photo Library bug

**Comment by lawik** [comment]
@cavarzan You are completely correct, this is not your code. There has been a fairly lond-standing Safari bug and a so far unfixed UIWebView bug that means if multiple upload is active video files will be uploaded with zero filesize, completely unusable file objects as far as I know.

This has been solved in Safari. It was not solved in UIWebView. Just recently the UIWebView changed behavior. It is now multiple by default and I cannot disable it. Expect more people to have issues with this on iOS, primarily with web/hybrid apps.

**Comment by pinchnzoom** [comment]
I have the same issue as @lawik. It looks to have changed in iOS 10.3.x. I submitted a bug to Apple in May, and haven't seen a response yet. There was an existing multi-select bug, but now with it auto selected, and no way to disable it, uploading videos from existing camera roll on UIWebView is broken. Works fine in Safari. Anyone have any workarounds?

**Comment by lawik** [comment]
I won't be a big help sadly. We ended up fixing it by building a file upload feature in native Swift and hooking that into the web code with JS. Thankfully that was quite simple in our app. This is, in the end, not really an ng-file-upload issue unless the project feels like fixing it by making a general-purpose file upload hook for iOS. But it breaks the whole thing as it is :/
