### ISSUE TITLE
ngfBlobUrl to upload file

### ISSUE THREAD

**Issue by amitgaur208** [danialfarid/ng-file-upload#1632]
I have an step form with ng-file upload in the middle of steps. So i don't want to upload file on the same step on which i'm selecting but i want to upload the image after two more step. I have shared the scope of file object and it save like nfBlobURL, $ngfHeight, $ngfWidth. But its not enough to upload file in later step.

I really want to know how can i create a file object using BlobUrl to upload in later steps.

Thnaks in Advance

**Comment by amitgaur208** [comment]
@danialfarid I am waiting for the response.

**Comment by amitgaur208** [comment]
Someone please help me!!!

**Comment by danialfarid** [comment]
The file object reference is enough to upload later. The first jsfiddle example uploads on form submit at later time.

**Comment by amitgaur208** [comment]
No,

I have tried to add file object into another scope variable like in $rootScope and tried to save using $rooScope its not working like below:
upload Pic function called on select image but i am not uploading at the same time and same controller.
 $scope.uploadPic = function (file) {
                $rootScope..main_photo = file;
)
And now i a want to upload that file using rootScope after changing controller
Upload.upload({
                        url: site_config.apiUrl + '/upload_main_photo',
                        data: {file: $rootScope.main_photo, 'property_id': '49'}, 
                        //headers: {'Content-Type': 'multipart/form-data'},
                    }).then(function (resp) {
                        $scope.formData.main_image = resp.data.main_image;
                        $scope.formData.main_image_id = resp.data.main_image_id;
                        console.log('uploaded. Response: ' + resp.data);
                    }, function (resp) {
                        console.log('Error status: ' + resp.status);
                    }, function (evt) {
                        var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
                        //console.log('progress: ' + progressPercentage + '% ' + evt.config.data.file.name);
                    });

**Comment by danialfarid** [comment]
If you have the correct file object reference it should upload the file. It is more like angular question. Create a jsfiddle.
