### ISSUE TITLE
How to upload a file with cookies attached in request?

### ISSUE THREAD

**Issue by yyli12** [danialfarid/ng-file-upload#1638]

**Comment by pjmeadmtu** [comment]
Unless this request is cross domain, cookies should be sent along with request.  What's the root of your problem?  What information do you ultimately need server side from the request?

**Comment by kc1116** [comment]
I am also trying to make a cors request , how would I set {withCredentials: true} when making a file upload?

**Comment by pjmeadmtu** [comment]
Set up an $http interceptor to set the withCredentials property.

**Comment by danialfarid** [comment]
@kc1116 `Upload,upload({..., withCredentials: true})`

**Comment by HelloAmy** [comment]
Is that use?
