### ISSUE TITLE
Upload.urlToBlob(url) converts to webp

### ISSUE THREAD

**Issue by luco** [danialfarid/ng-file-upload#1639]
Has anyone seen this? I save a temporary file in Android, with cordova-file-plugin and I keep the path. When I try to convert to blob, it converts to webp instead of jpg:

![captura de tela 2016-08-05 as 4 55 21 pm](https://cloud.githubusercontent.com/assets/246373/17448938/70de9564-5b2d-11e6-87d2-c377eeadee6d.png)

**Comment by danialfarid** [comment]
How do you convert it?

**Comment by luco** [comment]
@danialfarid 
```
Upload.urlToBlob(value.temp_file).then(function(blob) {
});
```

Where `value.temp_file` is something like `file:///...`
