### ISSUE TITLE
Limit the number of concurrent uploads

### ISSUE THREAD

**Issue by whitews** [danialfarid/ng-file-upload#164]
Hi,

First, thanks for sharing this extremely useful code. Kudos!

This isn't a bug or really even an enhancement request, but more of a curiosity. I've been experimenting with angular-file-upload and noticed Chrome seems to allow 6 concurrent uploads. Since you have likely used this with many browsers and platforms, could your provide information about the concurrency of the different browsers and whether it is possible to control this capability?

The reason I ask is that I am using this for file sizes in the 20-50 MB range and it would be useful to limit the number of concurrent uploads to 2 or 3 to allow some uploads to finish faster, to avoid re-uploading if some connectivity problem occurs.

Thanks again,
Scott

**Comment by darrudi** [comment]
+1

**Comment by griffinkelly** [comment]
@danialfarid How would one go about doing this?

**Comment by danialfarid** [comment]
The feature will be available in angular 2 version and might be ported to angular 1 too once it is released.
For now just implement it manually something like this:
https://github.com/danialfarid/ng-file-upload/issues/1307#issuecomment-176359201
