### ISSUE TITLE
Automation script for uploading file works fine with chrome but not with firefox browser

### ISSUE THREAD

**Issue by vsathyak** [danialfarid/ng-file-upload#1642]
Hi @danialfarid,

I am working on test automation of an angular app using protractor+jasmine, and we used ng-file uploader for upload files in our app. The automation script successfully uploads file in Chrome browser but not working in firefox browser and I am getting the following error :

Message: Failed: Element is not currently visible and so may not be interacted with Stack: ElementNotVisibleError: Element is not currently visible and so may not be interacted with

Code snippet for file upload

this.uploadFile = function (uploadFile) {
    var fileToUpload = uploadFile;
    var absolutePath = path.resolve(__dirname, fileToUpload);
    $('input[type="file"]').sendKeys(absolutePath);
    element(submitBtn).click();
};

    <label style="visibility: hidden; position: absolute; overflow: hidden; width: 0px; height: 0px; border: medium none; margin: 0px; padding: 0px;" tabindex="-1">
    upload
    <input id="ngf-{{ id }}" type="file" ngf-change="onChange($file)" ngf-keep="{{ keep }}" required="required" ngf-validate="{{ validate }}" ngf-pattern="{{ pattern }}" ngf-accept="{{ allowedMime }}" ngf-multiple="{{ multipleAllowed }}" ngf-model-invalid="invalid" ng-model-options="{ allowInvalid: multipleAllowed }" ng-model="files" ngf-select="" ngf-drop="" name="{{ name }}" accept=".csv,text/plain,application/vnd.ms-excel"/>

Any help would be greatly appreciated!!

**Comment by vsathyak** [comment]
Not an issue

**Comment by Nighthawk14** [comment]
@vsathyak Hey how did you fix your issue?

**Comment by vsathyak** [comment]
@Nighthawk14 : I also did the same thing.

    http://stackoverflow.com/questions/38835106/unable-to-upload-fileng-file-upload-in-firefox-browser-with-protractor/38837289#38837289
