### ISSUE TITLE
when multiple upload is true ngf-resize is only resizing my first image and subsequent images are reduced unequally 

### ISSUE THREAD

**Issue by appplumbr** [danialfarid/ng-file-upload#1644]
**Development Environment**
Device : Desktop/Mobile Web
Angular Core : 1.5.5
ng-file-upload : 12.0.4

```
accept="image/*"
ngf-capture="camera"
ngf-select required ngf-multiple="true" 
ngf-max-files="10"
ngf-min-width="500"
ngf-max-total-size="10MB" 
ngf-resize="{width: 1024, height: auto, quality: .9}" 
```

**Issue**  
The first image file [in multiple selected files] is resized as expected and rest are resized with some different dimensions [not sure where these are coming from and 50% less compared to first image resized dimensions ]

Does ngf-resize applies to multiple files? It works like a charm for single selected file.

**Comment by danialfarid** [comment]
Yes it works with multiple files too but there is no option for `height: auto`. You need to specify the height. Refer to the docs.
