### ISSUE TITLE
imageDimensions function not return real size of image

### ISSUE THREAD

**Issue by maxinminax** [danialfarid/ng-file-upload#1646]
As the title, imageDimensions function not return real size of image, I think should replace clientWidth and clientHeight with naturalWidth and naturalHeight

**Comment by danialfarid** [comment]
Can you provide a sample image or steps to reproduce in a jsfiddle?

**Comment by dustinsgoodman** [comment]
@danialfarid This one is weird and it's hyper-specific to a computer's hardware/software so it's not reproducible consistently. Basically, in certain cases, the `clientWidth` or `clientHeight` properties of the image [here](https://github.com/danialfarid/ng-file-upload/blob/master/dist/ng-file-upload.js#L1572) are getting an extra pixel. If you see the screenshot below, you can see that the `naturalWidth` and `naturalHeight` will return the correct values but the client values are incorrect. We had 2/9 computers in my office experience this bug. Tracked it down to Chrome but couldn't determine what was adding the pixel.

![screen shot 2016-09-07 at 10 54 54 am](https://cloud.githubusercontent.com/assets/1815379/18317521/74744286-74ec-11e6-9a60-a0f3053f67f1.png)

**Comment by ndavis** [comment]
Watching

**Comment by danialfarid** [comment]
Fixed at 12.2.8

**Comment by dustinsgoodman** [comment]
Thank you for the quick fix/response! Wanted to get you a PR but hands are tied.
