### ISSUE TITLE
Image is not uploading when image object sent via $http.put method

### ISSUE THREAD

**Issue by amitgaur208** [danialfarid/ng-file-upload#1648]
Hi @danialfarid 

I want to upload file using put method with other data but when i tried to assign $scope.file object into data object it turns object like;
Object { $ngfBlobUrl="blob:http://www.optamark...-4d9c-8c8c-3d42491c1c5a",  $ngfWidth=525,  $ngfHeight=324}

And its not sufficient to upload image.

**Comment by danialfarid** [comment]
console.log doesn't show the binary of the file but it is there.
