### ISSUE TITLE
Encoding issue on form fields with multipart

### ISSUE THREAD

**Issue by damrem** [danialfarid/ng-file-upload#1652]
On the first form on the demo page, accentuated characters in the Username field are garbled in the `POST` request body. I'm using Firefox. Chrome won't show the issue so obviously because I suspect it decodes thoses chars in the network panel though they're garbled on the serverside.

**Comment by damrem** [comment]
After investigation, the issue seems to occur whenever posting a `multipart/form-data` request with a file combined with some fields: in this case, accentuated characters in fields will break. 

In multipart specs (http://www.ietf.org/rfc/rfc2388.txt), it seems possible to format the request like this:
```
--AaB03x
content-disposition: form-data; name="field1"
content-type: text/plain;charset=windows-1250
content-transfer-encoding: quoted-printable
```
By default, `ng-file-upload` only set `content-disposition` and the `name`. Is there already a hook to add the others?

**Comment by damrem** [comment]
Garbling occurs only when the file is not in `UTF-8`, so it's definitely not a `ng-file-upload` issue. Closing.

**Comment by sbaechler** [comment]
This is actually still an issue if the server expects a different encoding. 

Currently Upload sets this content-type header, overriding the one in the config object:

`Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryYL3o8C0TATe628Ux`

**Comment by danialfarid** [comment]
That has to be the content-type when you use Upload.upload() since it is being sent as multipart form-data. You can use Upload.http() to set custom content-type @sbaechler
