### ISSUE TITLE
ng-file-upload not working with webpack?

### ISSUE THREAD

**Issue by brianpchsu** [danialfarid/ng-file-upload#1655]
Hi, I've been trying to use ng-file-upload with webpack. However, I keep seeing the error that the app failed to instantiate module ng-file-upload. I imported the ng-file-upload module and verified that it's in the vendor.js and vendor.bundle.js. Does ng-file-upload support to be used with webpack? Is there anything I need to do to use it? Thanks.

**Comment by theatrain** [comment]
I am using ngFileUpload with webpack successfully so the issue is likely to be with your code.

**Comment by mhd999** [comment]
Using it also with webpack and still working. you maybe want to provide more code details

**Comment by Zajkox** [comment]
Had the same issue. The problem was I was trying to require via full path to file.

This worked for me:
var ngFileUpload = require('ng-file-upload');
module.exports = angular .module('app', [ngFileUpload]);

**Comment by saeidalidadi** [comment]
I have the same issue.

I am using 
`webpack 2.2.1`
`angularjs 1.6.3`
`node 6.9`
`ng-file-upload 12.2.13`

Error when bundling with webpack 
```log
ERROR in ./~/ng-file-upload/dist/ng-file-upload-all.js
Module not found: Error: Can't resolve 'jQuery' in '/home/saeid/Projects/arp-apn/client/node_modules/ng-file-upload/dist'
 @ ./~/ng-file-upload/dist/ng-file-upload-all.js 1:0-17
 @ ./~/ng-file-upload/index.js
```
