### ISSUE TITLE
Set $error and $errorMessages when upload failed

### ISSUE THREAD

**Issue by pfeigl** [danialfarid/ng-file-upload#1657]
I would be nice, if internally the $error and $errorMessages properties of the models / files would be set automatically, if the upload fails (xhr goes into error handler).

This would allow very easy coupling of ng-messages with failed uploads.

**Comment by danialfarid** [comment]
the $error and $errorMessages are there for form validation. Submitting the files to the server could happen in a whole different scope and different time or another page so it should be handled when the call to the server is placed.
