### ISSUE TITLE
ngf-select and ng-click Don't work together on iphone

### ISSUE THREAD

**Issue by case12** [danialfarid/ng-file-upload#1659]
On iphone when I tap the element that contains the ng-file-upload directive, I get the system dialog to either take a picture or choose from library, but ng-click never gets processed.

On mac when I click the element, I get the system dialog to choose a picture, and ng-click does get processed.  

```
  button.upload(
      accept="image/*"  
      ng-if="uploadImages.enabled"
      ng-click="onUploadClick()"
      ng-class="{'post-picture-button': postPicture.show}"
      ng-model="uploadOverlay.file"
      ngf-pattern="image/*"
      ngf-select="uploadFile($file)"
      ngf-resize="getUploadResizeOptions()"
    )
```

Any alternatives I can use? Known issue?

**Comment by danialfarid** [comment]
Why do you need ng-click on the upload button?

**Comment by case12** [comment]
Using analytics to know when the user pressed that button.

**Comment by danialfarid** [comment]
You can use `ngf-change` or `ngf-before-model-change` to handle that case.

**Comment by case12** [comment]
That works if they change the model. Not if they cancel.

**Comment by danialfarid** [comment]
Would it make a difference if you use input type file?

**Comment by case12** [comment]
Doesn't make a difference. I guess this is hapepning because when ios brings up it's system menu it pauses the javascript events in my website?

**Comment by danialfarid** [comment]
Fixed at 12.2.5

**Comment by case12** [comment]
Thanks!

**Comment by shanthakumarf22** [comment]
@danialfarid : still have same issue. 12.2.5/12. any idea?

**Comment by pns2050** [comment]
Had the same issue on Microsoft Edge

Used this dirty trick to make it work

`onclick=angular.element(document.getElementById('YourElementId')).scope().myfunction();`
