### ISSUE TITLE
What is the ng-model's value format?

### ISSUE THREAD

**Issue by slavafomin** [danialfarid/ng-file-upload#1662]
Hello!

Thank you for this great library!

However, I couldn't find a documentation for ngModel's value format.

If I use:

```html
<button
    type="button"
    ngf-select
    ng-model="vm.uploadFile"
>Select</button>
```

What is the format of `vm.uploadFile` value? When I try to output it, I'm getting empty object, i.e.: `{}`.

How do I get the name of the uploading file (before it's actually uploaded)?

Thanks!

**Comment by danialfarid** [comment]
It might be just console.log that is not showing the properties of the file. Your code seems to be fine.

**Comment by slavafomin** [comment]
I'm sorry, but you've still not answered my question and the issue is not resolved — there is no description for `file` format in documentation.

**Comment by danialfarid** [comment]
It is the regular `ng-model` you can use on any element in angualr. The bound object is either one single file or an array of files. It is mentioned in the docs and there are couple of samples there. If you have an issue create a jsfiddle with steps to reproduce otherwise post your questions on StackOverflow.

**Comment by slavafomin** [comment]
The question is: **what is the structure of this "file" value?** I can't find it in the docs, could you please point me in the right direction?

For example:

> How do I get the name of the uploading file (before it's actually uploaded)?

**Comment by danialfarid** [comment]
`file.name` https://developer.mozilla.org/en/docs/Web/API/File

**Comment by slavafomin** [comment]
Now, I see. Thanks!

I think you should provide a link to the File API from documentation as it's not clear what format the `file` is in.
