### ISSUE TITLE
Get the original picture on client side

### ISSUE THREAD

**Issue by florentplomb** [danialfarid/ng-file-upload#1664]
Hey, 

I have got a question concerning the client side. Once the user selected the picture to upload , I would like display the original picture instead the thumbnail like you did in your exemple here (http://jsfiddle.net/danialfarid/maqbzv15/1118/) :

`<img ng-show="myForm.file.$valid"  class="thumb" ngf-thumbnail="picFile"> `

Is there a simple way to display the orignal picutre instead the thumbnail?

**Comment by danialfarid** [comment]
`ngf-src` instead of `ngf-thumbnail`
