### ISSUE TITLE
ngf-drop not working

### ISSUE THREAD

**Issue by myjoytou** [danialfarid/ng-file-upload#1666]
Browser: Chrome Version 52.0.2743.82 (64-bit)

included_files: 

    <script src="plugins/file-upload/ng-file-upload-shim.min.js"></script>
    <script src="plugins/file-upload/ng-file-upload.min.js"></script>
    <script src="plugins/file-upload/ng-file-upload-all.min.js"></script>

code:

     <div ngf-drop ng-model="files">Drop</div>

**Comment by danialfarid** [comment]
You don't need to include `all.min.js` 
Create a jsfiddle. The demo and samples are working.`
