### ISSUE TITLE
Odd Behaviour with Large Files

### ISSUE THREAD

**Issue by robpolak** [danialfarid/ng-file-upload#1667]
I am seeing an issue with uploading files where the file size is over ~>40mb.  

The file starts uploading and then seems to fail around ~60% and then the file upload will restarts.  After a period of time the upload will just error out with status = 0 and no real error information.

I was curious if you have seen this type of behaviour before.  I am utilizing connect-busboy to handle the requests.  I am then streaming them live to AWS S3.

Here is the relevant code:

```javascript
function $__uploadToAWSS3() {
            var file = $scope.file;
            Upload.upload({
              url: '/api/file/upload/s3/',
              data: {file_data: JSON.stringify($scope.file)},
              file: file,
            }).progress(function (evt) {
              file.progress = parseInt(100.0 * evt.loaded / evt.total);
            }).success(function (data, status, headers, config) {
              $scope.loading.uploading = false;
              $scope.$__executeOnUploadComplete();
              $scope.$__initFields();
            }).error(function (reply, status, headers) {
              $scope.loading.uploading = false;
              util.setValidationError($scope, 'Error Uploading!');
            });
          }
        }
        
```

**Comment by danialfarid** [comment]
It must be a server issue. Post it on SO doesn't seem to have anything with plugin.
You can try to increase the connection timeout.
