### ISSUE TITLE
ng-file-upload not working with localstorage

### ISSUE THREAD

**Issue by netwrkx** [danialfarid/ng-file-upload#1668]
i'm using ng-file-upload for uploading image in my project but whenever i implement localStorage using AuthFactory.setToken({token: "secret_token", expires: 'time'}); ng-file-upload fails to send image

http://stackoverflow.com/questions/39129308/ng-file-upload-not-working-with-localstorage

**Comment by danialfarid** [comment]
create a jsfiddle with steps to reproduce and follow it on stackoverflow.
