### ISSUE TITLE
ng-file-upload wont upload with header

### ISSUE THREAD

**Issue by netwrkx** [danialfarid/ng-file-upload#1669]
everytime I add header to ng-file-upload, image upload 100% but wont upload to server

```
file.upload = Upload.upload({
	url: 'http://localhost/server/upload.php',
        headers: {
			   'Accept':  "*/*",
	                   'Content-Type': '*/*',
		           'X-Access-Token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9._B_0ymCSWvdY',
			   'X-Key': 'sam@samq.com',
						
		     },
	data: {username: $scope.username, file: file},
					  
});
```

![xaccess](https://cloud.githubusercontent.com/assets/5035044/17946845/ea586582-6a41-11e6-9c2d-e835bb4baaae.PNG)

**Comment by danialfarid** [comment]
You should not set the content-type it must stay multipart/form-data. Remove that line.
