### ISSUE TITLE
http interceptor ng-file-upload

### ISSUE THREAD

**Issue by netwrkx** [danialfarid/ng-file-upload#1670]
hello guys, file wont upload when I use http interceptor with ng-file-upload [http://jsfiddle.net/](http://jsfiddle.net/netwrkx/1z1vhzd8/2/)

here is my php code
```
<?php

header('Access-Control-Allow-Origin: *');

	
if ( !empty( $_FILES ) ) {
    $tempPath = $_FILES[ 'file' ][ 'tmp_name' ];
    $uploadPath = dirname( __FILE__ ) . DIRECTORY_SEPARATOR . 'upload' . DIRECTORY_SEPARATOR . $_FILES[ 'file' ][ 'name' ];
    move_uploaded_file( $tempPath, $uploadPath );
    $answer = array( 'answer' => 'File transfer completed' );
    $json = json_encode( $answer );
    echo $json;
} else {
    echo 'No files';
}

?>

```

![capture](https://cloud.githubusercontent.com/assets/5035044/17949654/58dd8a4e-6a4e-11e6-9d92-6d7bc18a404b.PNG)

**Comment by danialfarid** [comment]
You should not set the content-type on `Upload.upload()` call. The content-type has to stay default multipart/form-data.

**Comment by netwrkx** [comment]
thanks, it worked!!
