### ISSUE TITLE
ngf-max-size validation issue.

### ISSUE THREAD

**Issue by AndrewCeM** [danialfarid/ng-file-upload#1671]
Release 12.0.4 doesn't have such issue.
If I upload file with size greater than is described in `ngf-max-size`, then `undefined` is passed, not the proper File object. And the error occurs (`TypeError: Cannot read property 'length' of undefined` - taken from your demo), which makes impossible to use the `ng-file-upload` without reloading the page. 

Tested on Chrome, Firefox.

Update.
Seems, that this issues is connected with whole validation, no only the `ngf-max-size`.

**Comment by danialfarid** [comment]
Fixed at 12.2.4

**Comment by AndrewCeM** [comment]
Thanks for quick response.
