### ISSUE TITLE
Object returned with Upload.upload does not have abort method with it.

### ISSUE THREAD

**Issue by saharcasm** [danialfarid/ng-file-upload#1674]
I have an upload factory that has the following methods, but the object returned with Upload.upload does not have an abort method with it.

var uploadObject;

function uploadFile(){
uploadObject=Upload.upload({
          method: 'POST',
          url: url,
          data: {
            files: [file]
          },
          timeout: canceler[index].promise,
          headers: {
            'Content-Type': 'application/json',
            'token': 'Bearer {' + $localStorage.token + '}'
          }
        }).then(success, error, progress);
}

function abortUploading(){
      uploadObject.abort();  //throws an error uploadObject.abort is not a function
    }

**Comment by danialfarid** [comment]
Follow the sample don't call then() on it which will return a promise that don't have abort.
