### ISSUE TITLE
IOS - file always null

### ISSUE THREAD

**Issue by jksa** [danialfarid/ng-file-upload#1675]
Hi,
I'm having issue with ios devices. 
Here is jsfiddle to demonstrate issue: https://jsfiddle.net/jsa/537yg6dt/

With IOS device, if you select file and press Check File button, IOS device always returns "File is not set" alert. 

Any ideas whats wrong?

**Comment by danialfarid** [comment]
You are probably selecting a file that fails the validations. Remove the validations and try again.
