### ISSUE TITLE
ngf-select not detecting horizontal swipe, causing opening window to select image in mobile devices

### ISSUE THREAD

**Issue by abgupta9** [danialfarid/ng-file-upload#1676]
Hi I am seeing an issue with swipe - 
if we have list of placeholders to select images, which has ngf-select to select image. then I am not able to swipe through the list. as it is causing opening a window while swiping. I looked at the code in select.js and saw it has the code to detect and handle vertical swipe but horizontal swipe is not handled. 

Please have a look. 
ref - http://stackoverflow.com/questions/38920489/ngf-select-causing-opening-window-while-swiping-on-phone?noredirect=1#comment65596330_38920489

**Comment by danialfarid** [comment]
Fixed at 12.2.5
