### ISSUE TITLE
Unable to change min/max width/height dimensions validation

### ISSUE THREAD

**Issue by mindscratch** [danialfarid/ng-file-upload#1678]
I'm using `Upload` via JavaScript. The default max height and width for an image is 1000, but I'd like to remove the validation altogether. If that's not possible I'd like to increase the max height and width.

I've been trying: 

```
Upload.setDefaults({
        ngfDimensions: "$width > 2000 || $height > 2000"
      });
```

Using the debugger, if I upload an image whose height is 1194, the `$scope.errFile.$error` is equal to `dimensions`.  The `$scope.errFile.$errorMessages` is equal to `{dimensions: true, maxHeight: true}`.

I'm having a hard time understanding how to change this validation from the documentation, any help would be appreciated.

**Comment by danialfarid** [comment]
Remove the validations directives from your element. Create a jsfiddle with steps.

**Comment by mindscratch** [comment]
Thanks, I completely forgot to look at the HTML template that set the `ngf-max-height`, thanks.
