### ISSUE TITLE
ngf-change isn't called in IE 11 with compability mode set to IE 10 if user aborts

### ISSUE THREAD

**Issue by SlippySken** [danialfarid/ng-file-upload#1679]
Hello there,

I have the following code:
`<input type="file"
                       ngf-select
                       ngf-change="changeFile($file)" />`
`$scope.changeFile = function ($file) {
            console.log("$file");
            console.log($file);}`
When I select a file in FF or Chrome and click on open, the function in ngf-change is called with the file as parameter. Now I open the file dialog another time (with the file selected) and click on cancel. Now no file is selected and ngf-change was called as soon as I open the file dialog. So far so good :)

Doing the same in IE 11 with IE 10 compability mode, ngf-change isn't called by opening the file dialog the second time. Pressing cancel erases the input field (it looks like no file is selected), but the file before is still selected.

**Comment by SlippySken** [comment]
Some new news? :)

**Comment by danialfarid** [comment]
Well it is supported in the actual IE10 browser but I am not sure what happens in compatibility mode and it may not be supported in compatibility mode.
