### ISSUE TITLE
Validation not working as expected

### ISSUE THREAD

**Issue by beeches** [danialfarid/ng-file-upload#1680]
Hi,

I am using version 12.2.5 with the following validations:
`ngf-validate="{"size":{"max":"2MB"},"width":{"min":100},"pattern":".jpg,.gif,.png"}"`

When uploading a 10x10px .gif following $ngfValidations are returned, showing a valid minWidth:

`"$ngfValidations":[{"name":"maxHeight","valid":true},{"name":"minHeight","valid":true},{"name":"maxWidth","valid":true},{"name":"dimensions","valid":true},{"name":"ratio","valid":true},{"name":"maxRatio","valid":true},{"name":"minRatio","valid":true},{"name":"maxDuration","valid":true},{"name":"minDuration","valid":true},{"name":"duration","valid":true},{"name":"validateAsyncFn","valid":true},{"name":"minWidth","valid":true}]`

All other validations seem to be working fine. (The minWith was validated some versions ago).

Any idea what could be done about this?

Thanks!

**Comment by danialfarid** [comment]
Could you attack your file here? You can verify it on the demo page.

**Comment by beeches** [comment]
Hi, I am using the attached 10x10px gif that passes the validation posted in my initial message.

The demo page is validating the image correctly.

![10x10](https://cloud.githubusercontent.com/assets/2827090/18193349/f0b005ec-70dc-11e6-8701-6cd19f346f2b.gif)

**Comment by danialfarid** [comment]
So if the demo page works then create a jsfiddle to figure out what you are doing differently.
