### ISSUE TITLE
Can not preview all images while using multiple

### ISSUE THREAD

**Issue by jiten1990** [danialfarid/ng-file-upload#1681]
Hi,

How can i preview all images while using multiple

**Comment by danialfarid** [comment]
<img ng-repeat"f in files" ngf-thumbnail="f"> demo has it already

**Comment by amdcaruso** [comment]
Oh dear finally, I have been struggling with this for a while now. However this does not give you a tiny thumbnail for a pdf/app file showing its icon does it?
