### ISSUE TITLE
Files are corrupted when upload image files and .xlsx files

### ISSUE THREAD

**Issue by gihanmaduranga** [danialfarid/ng-file-upload#1683]
My files are  corrupted  when upload **.xlsx** and **image(.jpeg,.png)** files into the server.Other file format work perfectly.(.xml,.csv,.txt) I am not sure if i set the pattern correctly.

`accept="text/csv/xlsx/xls/image" ngf-pattern=".txt,.xml,.xls,.csv,.xlsx,.png,.jpeg"`

I am not clear ngf-pattern directive so what it does exactly?

Note: i sent those files along with the other form data using form multi part.So can i convert only files data into **Base64** format when sending http request to the server.

Please find following [link](http://stackoverflow.com/questions/39284412/files-are-corrupted-when-upload-image-files-and-xlsx-in-ng-file-upload-in-angul)to more details about the problem.

please let me know how to solve this.

Thanks.

**Comment by danialfarid** [comment]
follow on SO since it is rather a question.
