### ISSUE TITLE
different response in firefox and chorome

### ISSUE THREAD

**Issue by dammad2299** [danialfarid/ng-file-upload#1687]
for firefox 44.0.2 even when disabling folder upload ngf-allow-dir="false" 
it shows some object with no type 
this issue was seen even when enabling folder for this version of firefox but worked fine with chrome.
also the object for uploading file with no extensions is type="".

**Comment by oboshto** [comment]
```
if (!files.length) {
    console.warn('Error! Invalid object'); // for example
    return;
}
```
