### ISSUE TITLE
MaxWidth/MaxHeight validations not working

### ISSUE THREAD

**Issue by rosalindwills** [danialfarid/ng-file-upload#1689]
http://jsfiddle.net/rosalindwills/uxue77qh/2/ Demo Fiddle

Note that selecting an image larger than 500x500 does not trigger the validation to appear. This appears to have been introduced in the last few versions, as when I revert to v12.1.0 (http://jsfiddle.net/rosalindwills/uxue77qh/3/) the validation appears correctly.

LMK if I can provide any further information of use. Thanks!

**Comment by danialfarid** [comment]
Fixed at 12.2.7
