### ISSUE TITLE
Using `ngf-resize=someFunction` fails with `TypeError: Cannot read property 'then' of undefined`

### ISSUE THREAD

**Issue by sdeprez** [danialfarid/ng-file-upload#1691]
For instance: `ngf-resize=resizeOptions` with
```
function resizeOptions () {
  var defer = $q.defer();
  defer.resolve({width: 100, height: 100, quality: .8});
  return defer.promise;
}
```

The culprit is [this line](https://github.com/danialfarid/ng-file-upload/blob/master/src/model.js#L213) which chain a `then` on the result of `resize` but you can see [here](https://github.com/danialfarid/ng-file-upload/blob/master/src/model.js#L85) that this function does not return nothing when `ngfResize` is a `Function`. Adding a simple return on [this line](https://github.com/danialfarid/ng-file-upload/blob/master/src/model.js#L87) seems to fix the problem.

Anyway thanks for your work, very useful library!

**Comment by danialfarid** [comment]
Fixed at 12.2.7
