### ISSUE TITLE
ng-file-upload issue

### ISSUE THREAD

**Issue by ITDante93** [danialfarid/ng-file-upload#1693]
Dear Developer,
Hope this find you well,

I am making a website using AngularJS and I am trying to upload using your module:
http://ngmodules.org/modules/ng-file-upload

However I keep getting this error and I have searched the web for similar problems but I didn't get a solution, I really hope you could help...
I am using Visual Studio 2015 latest update...
Thank you very much,
Highly appreciated and looking forword to hear from you soon,
Sincerly yours,
Dante

I am new to github, I'll do my best to describe the problem...
Below is the code:
the typescript:
/// <reference path="../../../typings/tsd.d.ts" />
module app.views {
    export class tests {
        public static $inject = ['Upload'];
        public file: any;
        public upload: (file) => void;
        constructor(private Upload: any) {
            var self = this;
            // upload on file select or drop
            self.upload = (file) => {
                Upload.upload({
                    url: '/images/',     //It should look for this folder and put the file in it,
                    data: { file: file }
                }).then(function (resp) {
                    console.log('Success ' + resp.config.data.file.name + 'uploaded. Response: ' + resp.data);
                    }, function (resp) {
                    console.log('Error status: ' + resp.status);
                }, function (evt) {
                    var progressPercentage = parseInt(100.0 \* evt.loaded / evt.total);
                    console.log('progress: ' + progressPercentage + '% ' + evt.config.data.file.name);
                });
            };
        }
    }
}
var myapp = angular.module('myApp');
myapp.controller('app.views.tests', app.views.tests);

the html:
<md-content flex ng-cloak ng-controller="app.views.tests as vm">
    <form name="form">
        Single Image with validations
        <button class="button" ngf-select ng-model="vm.file" name="file" ngf-pattern="'image/*'"
             ngf-accept="'image/*'" ngf-max-size="20MB" ngf-min-height="100"
             ngf-resize="{width: 425, height: 230}">Select</button><br />Preview:
        <img ngf-src="vm.file" ngf-resize="{width: 256, height: 256, quality: 0.9}"/><br />
        <button type="submit" ng-click="vm.upload(vm.file)">submit</button>
    </form>
</md-content>

the calling sequence:
            vendors: {
                src: [
                   "bower_components/angular/angular.js",
                   "bower_components/ng-file-upload/ng-file-upload-all.js",
                   "bower_components/angular-animate/angular-animate.js",
                   "bower_components/angular-aria/angular-aria.min.js",
                   "bower_components/angular-ui-router/release/angular-ui-router.min.js",
                   "bower_components/angular-material/angular-material.min.js",
                   "bower_components/angular-messages/angular-messages.min.js",
                   "bower_components/firebase/firebase.js",
                   "bower_components/angularfire/dist/angularfire.js"
                ],
                dest: 'www/scripts/vendors.min.js'
            }

the error:
Error: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': 'function (xhr) {
          if (!xhr || !xhr.upload || !xhr.upload.addEventListener) return;
          config.__XHR = xhr;
          if (config.xhrFn) config.xhrFn(xhr);
          xhr.upload.addEventListener('progress', function (e) {
            e.config = config;
            notifyProgress(getNotifyEvent(e));
          }, false);
          //fix for firefox not firing upload progress end, also IE8-9
          xhr.upload.addEventListener('load', function (e) {
            if (e.lengthComputable) {
              e.config = config;
              notifyProgress(getNotifyEvent(e));
            }
          }, false);
        }' is not a valid HTTP header field value.
    at Error (native)
    at Object.<anonymous> (http://localhost:4400/ripple/assets/ripple.js:51:4377)
    at Object.xhr.setRequestHeader (http://localhost:4400/ripple/assets/ripple.js:51:5324)
    at http://localhost:4400/scripts/vendors.min.js:11945:17
    at forEach (http://localhost:4400/scripts/vendors.min.js:335:20)
    at http://localhost:4400/scripts/vendors.min.js:11943:7
    at sendReq (http://localhost:4400/scripts/vendors.min.js:11776:9)
    at serverRequest (http://localhost:4400/scripts/vendors.min.js:11571:16)
    at processQueue (http://localhost:4400/scripts/vendors.min.js:16383:28)
    at http://localhost:4400/scripts/vendors.min.js:16399:27
vendors.min.js (13920,24)

the console.log:
Error status: undefined
code.min.js (1,12324)

**Comment by danialfarid** [comment]
These are similar issue might give you an idea: https://github.com/danialfarid/ng-file-upload/search?q=Failed+to+execute+%27setRequestHeader%27+on+%27XMLHttpRequest%27&type=Issues&utf8=%E2%9C%93

**Comment by ITDante93** [comment]
I have seen most of these issues with no clue of what to be done in my situation...

**Comment by danialfarid** [comment]
try to remove some of the dependencies it might be a conflict with other modules like pace.

**Comment by ITDante93** [comment]
I believe that I do not have pace.js...

**Comment by ITDante93** [comment]
This useless -_-
I am wasting my time if I can't figure out where my problem is...

**Comment by ITDante93** [comment]
don't expect from the developer to help, if you ever face an issue don't bother contacting, try to solve it or look for another solution, good day to everyone....
I hope no one gets what I got...
