### ISSUE TITLE
Chrome becomes active window after drag and drop

### ISSUE THREAD

**Issue by gary-gnu** [danialfarid/ng-file-upload#1695]
This is currently reproducible on the demo page: https://angular-file-upload.appspot.com/.
OS: Windows 7
Browser Versions: Chrome 53 & 52, Firefox 48, IE11

1. Position a Windows Explorer window on top of a Chrome window.
2. Drag and drop a file from Windows Explorer to the demo page draggable area in Chrome
3. Chrome becomes the active window

Follow the steps above again using Firefox and IE and note that Windows Explorer remains the active window after dragging and dropping the file.

Can you prevent Chrome from stealing focus from Windows Explorer?

**Comment by danialfarid** [comment]
Submit the bug on google Chrome. I am not sure which behaviour would be better. Having the browser to gain focus makes sense to me. Anyway it is very browser implementation dependent I don't think it should be hacked to accommodate for inside this plugin. You might be able to achieve something for chrome by listening to the drop event and stopping propagation something similar.
