### ISSUE TITLE
Uploading Multiple File Types

### ISSUE THREAD

**Issue by Dylan1116** [danialfarid/ng-file-upload#1697]
How can I filter the files to view in the directory by more than one type?
I am looking to get CSV and XML
<button class="md-trigger btn btn-primary" ngf-select="vm.upload($files)" accept=".csv" ngf-allow-dir="false" ngf-multiple="false"><i class="fa fa-cloud-upload" aria-hidden="true"></i> {{ "LBL_DATAIMPORT_IMPORTFILE" |  translate }}
    </button>

**Comment by danialfarid** [comment]
`.cvs,.xml`

**Comment by Dylan1116** [comment]
Thanks @danialfarid 
I can see this and have this working no problems.  Except when I see it in the file dialog I see it as a custom link.  It doesn't separate it out by line, i.e. All Files (first line), CSV (second), XML (third) etc.  

What I see is All Files (first line) Custom Files (second line).

I am looking for something like the actual file dialog shows in the file explorer.   Like so:
dialog.Filter = "JPEG Files (*.jpeg)|*.jpeg|PNG Files (*.png)|*.png|JPG Files (*.jpg)|*.jpg|GIF Files (*.gif)|*.gif"

**Comment by Dylan1116** [comment]
Thanks for the quick response to @danialfarid

**Comment by danialfarid** [comment]
`accept=".cvs,.xml"`
