### ISSUE TITLE
How to know if multiple file are all uploaded to the server?

### ISSUE THREAD

**Issue by regmish** [danialfarid/ng-file-upload#1698]
Is there any way to be notified if multiple files selected are all uploaded to the server ?

When i console on `.success(data)` data is printed twice and `.progress(e)` runs 4 times

**Comment by danialfarid** [comment]
follow the jsfiddle sample for multiple file upload.

**Comment by dylanspurgin** [comment]
Is this the fiddle you are referring to: http://jsfiddle.net/danialfarid/huhjo9jm/5/ ?

Is it possible to get progress on each file individually when uploading multiple files at once in this way?

**Comment by danialfarid** [comment]
Yes that's the fiddle.
No if it is one request for all you will have one progress for the request.
