### ISSUE TITLE
Having trouble with complex use case

### ISSUE THREAD

**Issue by merzikain** [danialfarid/ng-file-upload#1703]
I've been working on a reporting system web app to replace an obsolete system on our intranet. My first version had a custom file upload directive but has some limitations that aren't worth troubleshooting so I decided to use ng-file-upload instead.

Along with files I have to collect a lot of information to store in the database for the report. The problem I'm running into is that I can't seem to figure out how to:
A.) get the file queue to send along with my other data to the mediator that's doing the storing of files and db data.
OR
B.) send the rest of the form data along with the file uploads.

Part of the file upload process is to create a folder using the auditor's user id and then place the files in a folder with the name of the timestamp for the form submission.

I'm assuming I should be able to do this with this module but I can't figure out how. I'm not seeing anything in the documentation about getting file data to send with another method or sending other form data along with the file uploads.

**Comment by danialfarid** [comment]
Post it on SO since it is a question. The example with form sends data along with file
