### ISSUE TITLE
Abort file upload inside a Directive

### ISSUE THREAD

**Issue by bgadiel** [danialfarid/ng-file-upload#1705]
Hi,
Not sure if its a bug or not - 
I have a directive which I use in a wizard for uploading files with the following code:

```
var upload = Upload.upload({
                url: fileObj.aws_url,
                data: fileData,
                method: 'POST'
            });

            upload.then(function (resp) {  // success
                   fileObj.upload_time = new Date();
                    initFileObj('success');

            }, function (resp) { // error
                initFileObj('init');
                alertsModalService.error(resp.status);
                logger.error('Error status: ' + resp.status + ' ' + resp.data);
            }, function (evt) { // uploading....
                   progressbar.value = parseInt(100.0 * evt.loaded / evt.total);
            });
```

everything works ok, but if I leave the page and go back, the directive is initiated  and I am not able to cancel the upload process in case it was already started. 
I tried passing the upload variable to the parent controller using 2-way binding. although I get the full object inside the initiated directive properly, using abort() throws me to the error response from the promise.

Thanks.

**Comment by danialfarid** [comment]
Could you create a jsfiddle?

**Comment by bgadiel** [comment]
http://jsfiddle.net/s8kc7wg0/909/

**Comment by danialfarid** [comment]
There is no call to the abort in this example. How do you call abort?

**Comment by bgadiel** [comment]
sorry, wrong plnkr.
http://jsfiddle.net/s8kc7wg0/910/

**Comment by danialfarid** [comment]
it does cancel the upload.

**Comment by bgadiel** [comment]
but returns error.
which I use to catch real netwotk / upload errors.
I there a way to distinguish?

בתאריך 15 בספט׳ 2016 3:00 אחה״צ,‏ "Danial Farid" <notifications@github.com>
כתב:

**Comment by danialfarid** [comment]
You can check for the status code or set a flag before you call abort to know that the error is from abort.
