### ISSUE TITLE
Starting at 12.2.5, the button to pick files becomes unresponsive on iOS

### ISSUE THREAD

**Issue by jeremyk** [danialfarid/ng-file-upload#1706]
On iOS (version 10.10 on iphone for sure)

If I hold it down it eventually works but a quick tap does nothing. 100% reproducible switching back and forth between 12.2.4 and 12.2.5.

This is how I am using it:

`button ng-if="!showAddPhotoTip" ngf-select="" ngf-drop="" ngf-change="uploadFiles($files, collection)" multiple="multiple" accept="image/*" ADD PHOTOS`

**Comment by danialfarid** [comment]
Can you create a jsfiddle? Does it happen on the demo page?

**Comment by jeremyk** [comment]
It works fine on the demo page and also with a minimal fiddle. I will work on figuring out exactly what is going on.

**Comment by rgins16** [comment]
I am experiencing the EXACT same issue. I did not even know it would work if I held down the button until I read this post.

**Comment by jeremyk** [comment]
I am pretty sure this is due to fastclick: http://fiddle.jshell.net/9bLocL2y/6/

**Comment by danialfarid** [comment]
Try this fix: https://github.com/danialfarid/ng-file-upload/issues/1700#issuecomment-246347440
