### ISSUE TITLE
Working JsFiddle Drag and Drop Example for IE 11

### ISSUE THREAD

**Issue by squadwuschel** [danialfarid/ng-file-upload#1708]
Hi, great directive!

It works fine so far in Chrome and FireFox. But when I try 

http://jsfiddle.net/danialfarid/s8kc7wg0/400/

in IE 11 the Drag And Drop is not working, but on the Demo Page 

https://angular-file-upload.appspot.com/

it is working, but I can't find the differences between the two pages, perhaps you could provide a JsFiddle with IE 11 Drag and Drop working.

**Comment by danialfarid** [comment]
It is working fine for me. Maybe you are running in compatibility mode or something.

**Comment by squadwuschel** [comment]
both demos are working for you? Because its strange that the one works and the other not in the same IE. I will make a screenshot and share my  IE settings.

**Comment by danialfarid** [comment]
Yes both works.

**Comment by squadwuschel** [comment]
Hi,

so I've tried it again and its not working in my IE. 
![ieversion](https://cloud.githubusercontent.com/assets/1572878/18738213/e7150984-8099-11e6-9502-9f117bdece52.png)
![emulation](https://cloud.githubusercontent.com/assets/1572878/18738199/c82da2e2-8099-11e6-938c-8420cba3d2b8.png)

I am including the following files in my BundleConfig

      bundles.Add(new ScriptBundle("~/bundles/js").Include(
                   "~/Scripts/jquery-{version}.js",
                   "~/Scripts/angular.js",
                   "~/Scripts/angular-sanitize.js",
                   "~/Scripts/i18n/angular-locale_de-de.js",
                   "~/Scripts/angular-ui-router.js",
                   "~/Scripts/ng-file-upload-shim.js",
                   "~/Scripts/ng-file-upload.js",
                  "~/Scripts/AngularJsSxp/Addons/ui-bootstrap-tpls.js")

and i am just using your directive no backend code

      <div ngf-drop 
              ngf-select ngf-multiple="true"
              ngf-max-size="200MB" 
              ngf-allow-dir="true" 
              ng-model="ctrl.Locals.filesData" 
              name="upFiles" class="drop-box link-cursor">
                      <strong>drop files here</strong>
       </div>

Strange is, that at the moment my IE is not working on your Demopage and JsFiddle as well and I am shure it was working on the Demo Page last week. I've looked also into the console and there are no errors.

**Comment by danialfarid** [comment]
Can you send the screenshot for the demo page with the files that are loaded and console logs.

**Comment by danialfarid** [comment]
There should be logs from FileAPI if it is loaded properly.

**Comment by danialfarid** [comment]
Can you send the screenshots of the demo page with the loaded files and console logs?

**Comment by danialfarid** [comment]
Also make sure it is not in compatibility mode

**Comment by squadwuschel** [comment]
Damn that seems to be the solution, I thought I had deaktivated compatibility mode but it was not. I've deaktived it and now it works in IE too.

**Comment by gayaprabhu** [comment]
Hi ,
I have deactivated the compatibility mode in IE11, even though the drag and drop feature is not working in demo page as well as on my page. I've looked into the console also and there are no errors. Any idea?
