### ISSUE TITLE
iPhone/Safari: Images captured by camera do not show up in the image crop

### ISSUE THREAD

**Issue by rgins16** [danialfarid/ng-file-upload#1709]
I am using my iPhone 5C (all the latest updates).

I am able to successfully crop and upload an image with screenshots or downloaded images.

However, when the image I choose was a picture taken by my phone's camera, the image does not show up in the image crop, and therefore can not be uploaded. 

Is this a bug?

**Comment by danialfarid** [comment]
Create a jsfiddle with steps to reproduce

**Comment by rgins16** [comment]
I have the same issue when I use your jsfiddle on my phone. 

http://jsfiddle.net/danialfarid/xxo3sk41/590/

**Comment by rgins16** [comment]
@danialfarid Have you been able to reproduce this?

**Comment by danialfarid** [comment]
It is related to this issue probably: https://github.com/alexk111/ngImgCrop/issues/40 and is for ngImgCrop so follow it up there.
