### ISSUE TITLE
File uploads broken since 1.2.10

### ISSUE THREAD

**Issue by sorccu** [danialfarid/ng-file-upload#171]
It seems that [this change](https://github.com/danialfarid/angular-file-upload/commit/5a32e271e27354c07ade1ee5518947bf5ca7680e#diff-51a6a7154f0adadb9cbba9bebfd4d68fL95) has broken file uploads in 1.2.10. `$http.defaults.transformRequest` (the effective `config.transformRequest` in 1.2.10) is not suitable for file uploads, whereas `angular.identity` (the effective  `config.transformRequest` in 1.2.9) works. No files get sent and the `Content-Type` reverts to `text/plain;charset=UTF-8`. Was the line perhaps accidentally removed during refactoring?

**Comment by ErBahuguna** [comment]
I am getting the following issue while selecting the files.

![image](https://cloud.githubusercontent.com/assets/9461432/8175348/ee2c13d0-1406-11e5-8372-30ef175d9c44.png)

**Comment by danialfarid** [comment]
Can you create a jsfiddle? Is the demo page working?

**Comment by danialfarid** [comment]
@ErBahuguna  Create a new issue with more details this is an old closed issue

**Comment by ErBahuguna** [comment]
okay i will create the js fiddle or plunk today.

Thanks

On Tue, Jun 16, 2015 at 10:00 AM, Danial Farid <notifications@github.com>
wrote:

> @ErBahuguna <https://github.com/ErBahuguna> Create a new issue with more
> details this is an old closed issue
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danialfarid/ng-file-upload/issues/171#issuecomment-112284183>
> .
>



-- 
@Bahuguna Goyal
