### ISSUE TITLE
Upload with flash

### ISSUE THREAD

**Issue by pascalcarmoni** [danialfarid/ng-file-upload#1710]
ng-file-upload-all.min.js:2

Uncaught TypeError: Failed to set the 'files' property on 'HTMLInputElement': The provided value is not of type 'FileList'.

**Comment by danialfarid** [comment]
Put more details steps to reproduce a jsfiddle or your code

**Comment by pascalcarmoni** [comment]
<input type="file" name="driver_criminalFile" ng-model="vm.driver.criminalFile" class="btn btn-info" style="display: inline-block" ngf-select ngf-change="vmStep.upload($files)" ngf-multiple="false" ng-required="vm.driver.hasCriminalRecord && vm.driver.criminalRecord == undefined" >
                        
Controller

            var file = files[0];
            vm.fileInfoProgress = "";
            vm.fileInfo = "";
            vm.fileInfoError = "";

            Upload.upload({
                url: "api/uploadDocument/",  
                data: { file: file }
            })

**Comment by pascalcarmoni** [comment]
When i Force load FileAPI I got the error Uncaught TypeError: Failed to set the 'files' property on 'HTMLInputElement': The provided value is not of type 'FileList'.


works with html5 supported

**Comment by danialfarid** [comment]
why do you force load FileAPI? That is just for testing and may not work in html5 browsers.

**Comment by pascalcarmoni** [comment]
I what to test Flash upload if it works on IE 9 with FLASH.

**Comment by danialfarid** [comment]
test it on a real IE9
