### ISSUE TITLE
Sending array in data

### ISSUE THREAD

**Issue by thierryskoda** [danialfarid/ng-file-upload#1711]
Hi,

Anyone ever had this problem? 

I'm trying to send an array in the data parameters like this : 

````
data: {
   info: {[
      field1: 'test'
   ]}
}
````

And my backend is receiving it like this : 
````
{ info[0][field1] : 'test' }
`````

But I would like to receive it like this : 
````
{ info[{field1 : 'test'}] }
`````

Can I only resolve this with my backend code or is there an option that I can use frontend?

Thank you everyone!

**Comment by atais** [comment]
+1

**Comment by danialfarid** [comment]
Data will be send in form-data format which means a set of key/values(string). If you want to send a json object you can convert the json to string `JSON.stringify()` on the client side and then on the server convert the string to json.
