### ISSUE TITLE
Display a confirmation box before file select

### ISSUE THREAD

**Issue by sqzbx** [danialfarid/ng-file-upload#1713]
Is it possible to display first a confirmation box before the selecting of file window appears?
I can display a confirmation box after I select a file using `ngf-select` or `ngf-change` but I would like to have the confirmation box before file select but I'm not sure how to do it.

Anyone's help will be greatly appreciated...

Thanks

**Comment by danialfarid** [comment]
Add a ng-click to the button and call stopPropagation and preventDefault on the event if it is not confirmed.

**Comment by sqzbx** [comment]
Thanks for the fast reply... :)

Tried it... But still not working for me...

```
<a class="button button-calm icons" ng-click="clickEvent($event)" ngf-change="selectImage()" ng-model="file" name="file" ngf-pattern="'image/*'" ngf-accept="'image/*'" ngf-max-size="20MB"></a>
```
Is this right? I added the `ng-click` for `stopPropagation` and `preventDefault`... What I wanted is upon clicking that button i will show an ionicPopup first to the user then upon confirmation open the file select window... Currently what happens is both ionicpopup and file select window opens at the same time...

**Comment by danialfarid** [comment]
How about having two separate buttons the file button invisible and when you click on the confirmation then do `fileButton.click()`

**Comment by sqzbx** [comment]
I guess I just have to do it that way... :)

Thanks...
