### ISSUE TITLE
Is it possible to have spinner while waiting file loading preview?

### ISSUE THREAD

**Issue by macsermkiat** [danialfarid/ng-file-upload#1716]
While waiting for a file preview to show up, sometimes it took a long time especially a large file.
I'm thinking that it would be a better for UX if having this feature.

**Comment by danialfarid** [comment]
You can use `ngf-before-model-change="beforeChange($files, ...)"` to mark the beginning of file selection before validation/resizing happens and show the spinner until the file model is available.
