### ISSUE TITLE
Multiple image validation with height.min and width.min is broken

### ISSUE THREAD

**Issue by timomitt2610** [danialfarid/ng-file-upload#1717]
I used your [demo site](https://angular-file-upload.appspot.com/)

I changed the ngf-validate field to the following: {size: { max: '50MB' }, height: { min: 768 }, width: { min: 1500} } and set ngf-multiple to true.

1. If I chose all the correct pictures (that pass the validation), then everything worked fine
2. If I chose 2 correct pictures and 1 incorrect, then it only uploaded 1 correct picture and showed 1 picture with error, but 1 picture got lost in the process (not in $files or $invalidFiles). It should upload 2 correct pictures and show 1 with errors.
3. If I chose 2 correct pictures and 2 incorrect, then it did not upload any of the pictures and showed 2 pictrues with errors, meaning that 2 pictures got lost in the process (not in $files or $invalidFiles). It should upload 2 correct pictures and show 2 with errors.

To conclude, it uploads only n images that pass the validation, where n = validated images length - invalidated images length. But this kind of behaviour exists only if I use width and height rules together in ngf-validate and it disappears when I remove width or height rules from ngf-validate.

**edit:** there seems to be no issue, when using height.max and width.max together

**Comment by danialfarid** [comment]
Fixed at 12.2.10

**Comment by timomitt2610** [comment]
Thanks!
