### ISSUE TITLE
Upload doesn't work on Safari. Options request 403 Forbidden.

### ISSUE THREAD

**Issue by andreabtr95** [danialfarid/ng-file-upload#1718]
Hi guys i would fix a problem that i found with ng-file-upload. I did this inside my web app to upload a file using a presigned url.
```
var formData = new FormData();
        formData.append("file", file);

        var config = {
            url: preSignedUrl,
            headers: {
                "Content-Type": 'multipart/form-data'
            },
            method: 'PUT',
            data: formData
        };

        return Upload.http(config);
```

Content-Type is setted on web-app and back-end (when make presigned-url).
Chrome, Mozilla works fine, but when i try to upload a file with safari i receive a 403 Forbidden on Options request. Exactly this error:
Failed to load resource: the server responded with a status of 403 (Forbidden)
Failed to load resource: Origin is not allowed by Access-Control-Allow-Origin.
XMLHttpRequest cannot load. Origin is not allowed by Access-Control-Allow-Origin.

And the response of S3 is that:
The request signature we calculated does not match the signature you provided. Check your key and signing method.

In the request of Chrome and Mozilla, the request Options and Put works, in Safari no. Another strange thing is inside the signed string of S3. On Chrome and Mozilla i find:
GET multipart/form-data timestamp filename
On Safari:
GET timestamp filename

**Comment by danialfarid** [comment]
`Upload.http()` is not supposed to be used for multipart/form-data content-type. Instead use `Upload.upload()`
