### ISSUE TITLE
ngf-select superslow on Chrome

### ISSUE THREAD

**Issue by beyondsanity** [danialfarid/ng-file-upload#1724]
After pressing a ngf-select element i'm experiencing up to 10 seconds delay before the file browser comes up.
No errors in console, other browsers work fine. 
I'm on MacOSX Chrome 53.0.2785.116.

The demo seems affected too
https://angular-file-upload.appspot.com/

**Comment by brainsqueezer** [comment]
Same here

**Comment by agyrafa** [comment]
same here

**Comment by rocketlobster** [comment]
same here

**Comment by kelsmj** [comment]
We are seeing this as well...happens on Chrome > 52.  Chrome 51.0.2704 seems fine.

**Comment by stephenlorenz** [comment]
We are seeing this, as well, on both Mac and Windows versions of Chrome. It seems to get worse the more images you upload (as if it's a memory leak):

Windows 7, Chrome Version 53.0.2785.116 m
OSX 10.105, Chrome Version 53.0.2785.116 m

**Comment by gbittmann** [comment]
Not seeing the problem with:

Windows 10, Version 53.0.2785.116 m
ng-file-upload @ 12.2.11

Is everyone seeing this problem at 12.2.12?

**Comment by JohnsonBM** [comment]
I am seeing this too but it seems to be a much worse delay when using the ngf-pattern attribute.

Without whitelisting files to upload it is fairly fast and not much of a delay but when I started using the file types supported by my server the delay is close to 10 seconds:

```ngf-pattern= ".jpg,.xlsx,.xlt,.bmp,.svg,.csv,.png,.xsd,.docx,.pptx,.txt,.pdf,.ico,.ppt,.uml,.xml,.jpeg,.doc,.json,.yml,.xls"```

**Comment by danialfarid** [comment]
This happened for me for a minute on the demo page but while I was trying to debug it, it just went away and never happened again. Could it be that it might happen if you have the developer console on? Can you guys constantly reproduce it

**Comment by danialfarid** [comment]
@JohnsonBM the issue is about the delay between when you click and popup window shows up. The `ngf-pattern` is for after the file selection so that is not related to this issue.

**Comment by JohnsonBM** [comment]
I see the popup shows "All Files" when no pattern is set and "Custom Files" when some pattern is set but I am not able to constantly reproduce this anymore.

My Chrome just updated to Version 53.0.2785.143 m so who knows but I haven't reproduced since that update

**Comment by mattblang** [comment]
This is so strange. I was definitely seeing this issue earlier (which had led me to this ticket), but now I can't reproduce it. I tried with the developer console both open and closed.

OSX 10.11.6 (15G1004)
Chrome 53.0.2785.116

**Comment by stephenlorenz** [comment]
It is intermittent for us, as well, and doesn't ever seem to happen on my more powerful developer machine; only on standard user workstations. I think I can say with confidence that these users do not have the developer console open; though, ironically, I probably nearly always have it open and it doesn't seem to affect me.

**Comment by SunyLiu** [comment]
I have the issue here too after upgraded the chrome( 53.0.2785.116 m). 

I notice that it works well if I remove the ngf-accept attribute and the speed is very slow if the ngf-accept attribute has value  (e.g. ngf-accept="'image/*'"). 

Hope that it is helpful to reproduce issue.

**Comment by a455bcd9** [comment]
Same here + variation of the issue:
- infinite-scroll is super slow on Chrome Version 53.0.2785.116 (64-bit) (Ubuntu 14.0 and Mac OSX) is there is ngf-select on the same page (even if not pressed).

**Comment by danialfarid** [comment]
@a455bcd9 Could you create a reproducible jsfiddle?

**Comment by beyondsanity** [comment]
The problem is solved for me, i guess it was caused by Chrome version.
Yesterday i was experiencing the bug with both developer console closed and open. Before opening the bug i tried other file browsers on the web and they were all working fine.

**Comment by danialfarid** [comment]
Since this is only happening in Chrome this is most probably the browser's issues. Since I cannot reproduce it, I won't be able to investigate. If you guys can reproduce it, while it is waiting for the popup to show up click on the pause button the the dev console and see if it stops anywhere in the ng-file-upload code or something like that which could give us a clue. 
Also if you are able to reproduce try it in incognito tab to make sure it is not a Chrome plugin causing it.

**Comment by brainsqueezer** [comment]
May be useful to check Chromium bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=638874

**Comment by stephenlorenz** [comment]
@brainsqueezer Thanks! That Chromium bug work-around (https://bugs.chromium.org/p/chromium/issues/detail?id=638874#c13) fixed our problem.  Essentially, we changed this:

    <input type="file" .... accept="image/*">

to this:

    <input type="file" .... accept="image/gif, image/png, image/jpeg">

and the problem went away.

**Comment by cdll** [comment]
same here~trying above~
