### ISSUE TITLE
Question: Is there an Event When the User Cancels The Fileupload

### ISSUE THREAD

**Issue by 360disrupt** [danialfarid/ng-file-upload#1725]
I block the button as soon as the user clicks the button, to prevent multiple clicks on the button. I tried  to unblock the button in`ngf-select` so far, but this works only if there is a change. E.g. 
no file -> file. It does not work when no file is selected and the user cancels the upload.

```
<button class="btn select-file-button" ng-model="file" ngf-multiple="false" name="file" ngf-pattern="battleTatamiController.allowedMime" ngf-accept="battleTatamiController.allowedMime" ngf-max-size="4MB" ngf-change="fileChanged()" ng-click="battleTatamiController.buttonFileDisabled = true" ngf-select="battleTatamiController.selectedFile()" ng-disabled="battleTatamiController.buttonFileDisabled">Or Click Here</button>
```

```
    $scope.selectedFile = ()->
      console.info "I'm not called"
```

**Comment by danialfarid** [comment]
When the user cancels the popup window there is no event triggered from the browser so there is no easy cross-browser way to detect cancellation of popup.
