### ISSUE TITLE
File upload function calls multiple times.

### ISSUE THREAD

**Issue by bkhushang** [danialfarid/ng-file-upload#1731]
I have used uibModal for load bootstrap modal and inside that I have created file upload form and that form doesn't contains any submit button. I have submit the form on files select/drag. But the problem is that upload function in angular controller calls multiple times and even I couldn't enter anything inside that form's input tag.

Please suggest me the solution. 

Thanks.

**Comment by danialfarid** [comment]
Create a jsfiddle or plnkr. What do you mean you cannot enter anything?

**Comment by WuglyakBolgoink** [comment]
@bkhushang any updates?
