### ISSUE TITLE
Slowly turn on browse image

### ISSUE THREAD

**Issue by CuongPham459** [danialfarid/ng-file-upload#1732]
Hi Danialfarid and everyone,
Thank you so much for your control (Mr. Danialfarid).
I have a problem which relate with the performance of upload control. When I click on upload control, I must wait more than 10 seconds to display pop-up browse.
I didn't know why it slowly loaded.
Any suggests, I looking forward to hearing from you.
Many thanks.

**Comment by px751** [comment]
Same problem here, did you manage to fix you issue? and how especially ;)
