### ISSUE TITLE
xlsx, docx formats are not supported

### ISSUE THREAD

**Issue by ishanrustagi** [danialfarid/ng-file-upload#1739]
I am trying to upload xls, xlsx, doc, docx files, but unable to set the required validations for these.
Moreover, xlsx and docx mime-types are not even generating the blob for processing.

**Comment by danialfarid** [comment]
Create a jsfiddle or copy your code

**Comment by ishanrustagi** [comment]
`<input type="file" class="input-file" ng-model="creditFile" name="creditFile"
                                   ngf-select="uploadFile(creditFile)" ngf-pattern="'.xls,.xsls,.doc,.docx'" ngf-accept="'.xls,.xls,.doc,.docxx'"
                                    />`

**Comment by danialfarid** [comment]
I don't see any `required` in this code.

**Comment by ishanrustagi** [comment]
`<input type="file" class="input-file" ng-model="creditFile" name="creditFile"
                                   ngf-select="uploadFile(creditFile)" ngf-pattern="'.xls,.xsls,.doc,.docx'" ngf-accept="'.xls,.xls,.doc,.docxx'"
                                    />`

**Comment by ishanrustagi** [comment]
Sorry, required word wasn't used for `required` validation. I was talking about the blob processing for xlsx and docx. When uploading any document with these mime-type, I am not getting anything in `creditFile` whereas this function is working fine for xls and doc

**Comment by danialfarid** [comment]
You have a typo `.xsls`. It probably fails the pattern matching and is part of `ngf-model-invalid` create a jsfiddle to further investigate.
