### ISSUE TITLE
Problems with csv files

### ISSUE THREAD

**Issue by faridhajnal** [danialfarid/ng-file-upload#1742]
Hello and thanks for the awesome module!

For some reason, I cannot specifi csv as part of the **ngf-pattern** attribute.

I've tried using '.csv' and 'text/csv'. 
xls formats work with no problem.

Any ideas?

Thanks a lot

**Comment by danialfarid** [comment]
`try ngf-pattern="'.csv'"` if that is not working the file you are selecting does not end with .csv.
