### ISSUE TITLE
Can not change the oder of pace.js ; any other alternative?

### ISSUE THREAD

**Issue by zymr-keshav** [danialfarid/ng-file-upload#1744]
I am using gulp and one of it's task load all JS files took from from bowe.json and it load _pace.js_ before _ng-upload.js_

I can not change the orderof js as suggested in the same issue. is there any other solution?  so that 

**Failed to execute 'setRequestHeader' on 'XMLHttpRequest':**  sort out

**Comment by Dufgui** [comment]
i have the same problem and my dep are injected via gulp so...i create a small patch as describe in #579

Bower : pace-ng-file-upload-inlinepatch 0.0.6
https://github.com/Dufgui/pace-ng-file-upload-patch

**Comment by Dufgui** [comment]
i have the same problem and my dep are injected via gulp so...i create a small patch as describe in #832

Bower : pace-ng-file-upload-inlinepatch 0.0.6
https://github.com/Dufgui/pace-ng-file-upload-patch

**Comment by zymr-keshav** [comment]
and how to use this patch? where to write/install/add this one.

**Comment by Dufgui** [comment]
In my bower.json. I add :
"pace-ng-file-upload-inlinepatch":"0.0.6";",

And then I launch:
Bower install

And then My gulp task:
Gulp inject: vendor 

I use jhipster so you can test the gulp task in it.

**Comment by zymr-keshav** [comment]
I have applied quick fix as
change the order on included bower packaged order in `bower.json` dependencies section as below

```
  "ng-file-upload": "^12.2.12",
   "pace": "~1.0.2",
```

This will automatically add `pace.js` below to `ng-upload`

**Comment by Dufgui** [comment]
not for me sorry ;o), that's why i create this patch
