### ISSUE TITLE
Is it possible to preload images from remote URL?

### ISSUE THREAD

**Issue by tekfunk** [danialfarid/ng-file-upload#1746]
I am using ng-file-upload to allow users to add up to 8 images to their post and have got that part working.  The problem is I need to allow them to also come back and edit these images as in delete some, add new ones, etc.  I was wondering if there is an easy way to preload my form with images that they have already uploaded to the server with an AJAX request.

**Comment by tekfunk** [comment]
Doah, just found urlToBlob()

**Comment by danialfarid** [comment]
ng-model="file"
var blob = Upload.urlToBlob(URL);
$scope.file = blob;

if you don't have multiple

**Comment by abumere** [comment]
@danialfarid using that method posted would you be able to say: 

1. upload and image (image a) 
2. get the image blog, given the url and urlToBlob, 
3. change/overwrite the image to something else? 

Im am currently trying to do just that. Allow a user to upload an image but later come back and upload another image over it. (delete and upload something different)

**Comment by danialfarid** [comment]
Once you upload to S3 you get a unique url for the file. So when the user select another image to replace that url you can upload the new image on the same url on S3.
