### ISSUE TITLE
Upload multifile error (over 12 files)

### ISSUE THREAD

**Issue by CuongPham459** [danialfarid/ng-file-upload#1758]
Hi everyone,
Thanks @Danialfarid so much for your control.
I have a problem with ng-file-upload which i used to upload multifile images. I only uploaded 12 files, if i made 13 or more, the control would not receive that files. 
I configured that i accepted ngf-multiple='true' and i did not use limit size.
How can i do? Any suggests
Many thanks

**Comment by danialfarid** [comment]
Post your code or create a jsfiddle.

**Comment by CuongPham459** [comment]
Opps. Sorry @danialfarid  I reviewed again and I saw that api which limited size upload file.
**And ng-file-upload is okay.**
I'm sorry about this mistake.

Thank you very much @danialfarid .
Enjoy your day as well Sir :)
