### ISSUE TITLE
When using ngf-select on Google Chrome, it will take 10 seconds to open the file

### ISSUE THREAD

**Issue by smart-dream** [danialfarid/ng-file-upload#1760]
Last month, accidentally rose to the latest version of GoogleChrome(Current version 53.0.2785.143 m), and the results using ngf-select, it will delay 10 seconds to open the file, but no problem with other browsers.
Click https://angular-file-upload.appspot.com/ click on the file will be delayed for 10 seconds to open the file, ask for help to see, thank you

**Comment by danialfarid** [comment]
See this: https://github.com/danialfarid/ng-file-upload/issues/1724

**Comment by smart-dream** [comment]
That Chromium bug work-around (https://bugs.chromium.org/p/chromium/issues/detail?id=638874#c13) fixed our problem. Essentially, I changed this:
`<div  ngf-select .... accept="image/*"></div>`
to this:
`<div  ngf-select .... accept="image/gif, image/png, image/jpeg"></div>`
and the problem went away.

**Comment by smart-dream** [comment]
@danialfarid thanks very much ! It really helped me solve the problem！
