### ISSUE TITLE
Abort does not work

### ISSUE THREAD

**Issue by rakib-jahan** [danialfarid/ng-file-upload#1763]
When abort calls then in client side it works but still it goes to server side and uploaded to s3 , i want that when abort calls it should not go to server.

Here is the abort call from html where there is a repeater  :

<div class="uploadDetailDiv" ng-repeat="f in files">
      <span data-ng-if="f.progress == 100 && f.errorMsg.length == 0" style="color:      #5cb85c;">Completed</span>
      <i ng-click="f.upload.abort();f.upload.aborted=true" data-ng-if="f.progress < 100" style="padding-right: 15px;float: right;cursor:pointer;color:#990000" class="fa fa-times-circle-o fa-2x" aria-hidden="true"></i>
</div>

Here is the angular controller function code : 
$scope.uploadFiles = function (files, errFiles) {
            var m_upload;

```
        $scope.files = files;
        $scope.errFiles = errFiles;

        angular.forEach(files, function (file) {

            file.errorMsg = '';

            file.upload = Upload.upload({
                url: '/Global/EmailAutomation/Controllers/PictureBankImages',
                file: file,
                data: {

                }
            });

            file.upload.then(function (response) {

                $timeout(function () {

                    file.progress = 100;
                    file.errorMsg = '';

                });
            }, function (response) {

                if (response.status == 300) {
                    file.errorMsg = response.data.returnData;
                    file.RenameTxt = file.name;
                    file.DuplicateName = true;
                }
                if (response.status == -1) {
                    file.errorMsg = 'Aborted ...';
                }

            }, function (evt) {
                $timeout(function () {
                    file.progress = parseInt(evt.loaded / evt.total * 95, 10);
                }, 500);
            });

            file.upload.xhr(function (xhr) {
                xhr.upload.addEventListener('abort', function () {

                    file.progress = 100;
                    console.log('abort complete');

                }, false);
            });

        });
    }
```

**Comment by danialfarid** [comment]
What the issue is?

**Comment by rakib-jahan** [comment]
I just implemented abort function, in client side it cancel but the multipart file upload async request goes to server and my s3 upload function executes, I need to abort in server side too.

file.upload.xhr(function (xhr) {
                    xhr.upload.addEventListener('abort', function () {

                        file.progress = 100;
                        console.log('abort complete');

                    }, false);
                });

How can I cancel while uploading file in server side, is that when I know its aborted then again I send a request to server to delete this file from s3, is that standard process?

**Comment by danialfarid** [comment]
Well if calling abort on the xhr doesn't work and you get the abort complete message but still the file is being uploaded then it means the server doesn't support it, so yes you can send another request to delete it from s3. There is not much to be done on the client side other than aborting the connection.

**Comment by Plonq** [comment]
For those banging their head against the wall and end up here like me - if you're testing locally, the upload is probably instant, and therefore not cancellable. It should work as expected if you enable network throttling in the browser.
