### ISSUE TITLE
ngf-select stopped working after upgrade to iOS10 (iphone 5 and 5c)

### ISSUE THREAD

**Issue by pimrie** [danialfarid/ng-file-upload#1775]
Hi there,

We have an app that uses the ngf-select directive to upload an image file.
We have noticed that this has stopped working on a couple of iOS 10 devices (iphone 5 and 5c) after upgrade from iOS 9 to 10. We have an iPhone 6 that works correctly after an upgrade.

Cordova 6.3.1
Ionic 2.0.0

IPA built using ionic cloud.

Thanks

Peter

**Comment by coopers98** [comment]
Seconding

**Comment by thanuzz** [comment]
Same issue here, also doesn't work withing Chrome browser on IPhone

**Comment by itibet** [comment]
+1

**Comment by jj-julia** [comment]
+1

**Comment by danialfarid** [comment]
Can you provide your code? Does it work if you use `<input type="file"...>`. What exactly not working?

**Comment by pimrie** [comment]
Hi Daniel,

I have the following code: `<div class="avatar-label-link" ng-model="file" name="file" type="file" ngf-pattern="'image/*'" ngf-accept="'image/*'" ngf-max-size="20MB" ngf-min-height="100" ngf-select="upload($file)" style="color:white;"><span>Change profile image <i class="material-icons avatar-label-icon">photo_camera</i></span></div>`

This works fine across most browsers and devices. It was working fine on my iPhone 5 and iPhone 5C devices running iOS 9. After upgrading to iOS 10 when you tap on the 'Change Profile Image' link then nothing happens. Strangely enough works on iPhone 6 running iOS10.

Thanks

Peter

**Comment by jj-julia** [comment]
Hi Peter. Did you ever solve this or find out why it is happening? I am still struggling to figure out why its not working on those particular devices for me too.

**Comment by dondoco7** [comment]
+1

**Comment by pimrie** [comment]
Hi jj-julia, there is the workaround to use the <input> tag but I haven't been able to devote much time to looking into this as a possible fix. Depending on your use it may need some additional styling if it does work.

**Comment by maniolek** [comment]
Hi jj-julia, I'm having the same problem on ios 10 with iphone 7. Have you managed to solve this issue?

**Comment by 5hanth** [comment]
+1

**Comment by jpduckwo** [comment]
+1

**Comment by gbelmm** [comment]
+1

**Comment by danialfarid** [comment]
Follow it here: https://github.com/danialfarid/ng-file-upload/issues/1728#issuecomment-285666176
