### ISSUE TITLE
ngf-select doesnt work on all browsers

### ISSUE THREAD

**Issue by pavlokitdev** [danialfarid/ng-file-upload#1776]
Hello!

Case with 'ng-file-upload' and 'ng-img-crop'.
'ngf-select' directive opens file browser but after selecting image - does nothing. No errors in console.

I'm using 'ngf-select' with callback, so for example: 
ngf-select="cropImage($file)" - cropImage will not be fired.
(cropImage function should open modal with ng-img-crop functionality)

Only after second attempt attaching file I have some response:
http://take.ms/1Ol68 unfortunately - this object don't works for 'ng-img-crop' (just blank canvas appears), I think that's because of '$ngfDataUrlFilterInProgress: true'

Same behavior on FF/Safari, FF (Windows7)

UPD: When use 'ngf-drop' file will be opened for cropping

**Comment by danialfarid** [comment]
Create a jsfiddle, steps to reproduce.
