### ISSUE TITLE
Image is larger after resize

### ISSUE THREAD

**Issue by ericfrancis** [danialfarid/ng-file-upload#1778]
Have this function

```
function resizeFile(file) {

          // if file is not too large, resolve
          var tooLarge = isTooLarge(file);
          if (!tooLarge) {
            return $q.resolve(file);
          }

          return Upload.imageDimensions(file).then(function(imageDimensions) {
            // get dimensions from file
            resizeOptions.width = Math.round(imageDimensions.width * .8);
            resizeOptions.height = Math.round(imageDimensions.height * .8);
            resizeOptions.quality = Math.round(resizeOptions.quality * 100 - 5) / 100;
            return Upload.resize(file, resizeOptions);
          }).then(resizeFile);
        }
```

After the first resize, the file's total size gets larger. 

This only happens for this image:

![planet_4 3mb](https://cloud.githubusercontent.com/assets/1517115/20313639/26ae7f28-ab1d-11e6-897e-5a6f5c51d7b5.jpg)

**Comment by danialfarid** [comment]
reduce the quality of the image.

**Comment by ericfrancis** [comment]
@danialfarid I am reducing the quality:  `resizeOptions.quality = Math.round(resizeOptions.quality * 100 - 5) / 100;`; Or do you mean reduce the quality of the image before using this library?

**Comment by danialfarid** [comment]
Quality is a between zero and 1.

**Comment by ericfrancis** [comment]
I'm setting quality to .95

**Comment by danialfarid** [comment]
There is not much guarantee on the size of the image that will be created after resize, you can try to lower the quality to get a smaller image if it is too big using `Upload.resize()`.

**Comment by ericfrancis** [comment]
@danialfarid Gotcha. The image gets smaller after the first call to `Upload.resize()`. It's odd, but I wanted to make sure that this was known.
