### ISSUE TITLE
req.file undefined

### ISSUE THREAD

**Issue by pazalvin** [danialfarid/ng-file-upload#1779]
![image](https://cloud.githubusercontent.com/assets/2208580/20380037/7f81b7fa-acda-11e6-87d6-7c1c7a843566.png)

my scenario:
at first it's works but when i try to upload again it return like that.

here is the file that i'm using
[test.xlsx](https://github.com/danialfarid/ng-file-upload/files/596764/import-design-FabricFM944-1.xlsx)

**Comment by danialfarid** [comment]
Check for null before uploading the file in your js. See the sample codes.
