### ISSUE TITLE
Adding new parameters in upload method

### ISSUE THREAD

**Issue by amiteswar** [danialfarid/ng-file-upload#178]
Hi,

I am having a $upload.upload method like below,

$scope.upload = $upload.upload({
        url: 'UploadTest/upload',  
        method: 'POST',
        data: {myObj: $scope.myModelObj},
        file: file
      }).progress(function(evt) {
        alert("upload is in progress");
        console.log('percent: ' + parseInt(100.0 \* evt.loaded / evt.total));
      }).success(function(data, status, headers, config) {
        alert("file is uploaded successfully");
        // file is uploaded successfully
        console.log(data);
      });

the url above is calling a grails plugin which expects some more parameters. Now how do I send those new parameters into this method.

If I just add the parameters it is not being posted.

New Parameters are below,
        title: 'filename',
        contextJSON: {"lazyInitialize":true,"referenceType":"Account","referenceId":1000}

**Comment by hellonishu** [comment]
Please How to get <code>data</code> in php?

**Comment by danialfarid** [comment]
@hellonishu follow the wiki page: https://github.com/danialfarid/ng-file-upload/wiki/PHP-Example
