### ISSUE TITLE
Validations Not working.

### ISSUE THREAD

**Issue by PradeepSmg** [danialfarid/ng-file-upload#1781]
Hi,,

I am using ngf-select in my mobile app to select a single image from gallery to upload it to remote server .
It is working fine for all types images,  but i wanted to show an error message when user selects file other than Image file.

Here is my code:
<div class="button button-stable button-block" ngf-select ng-model="file" name="selctedFile" ngf-pattern=" 'image/*'" ngf-accept = " 'image/*'" >
<span ng-show = "!file[0].name">Select image file</span>
<span ng-show = "file[0].name">{{file[0].name}}</span>
</div>
<span style = "color:red" ng-show="attachmentForm.selctedFile.$error == 'pattern'">File type of {{file[0].name}} not supported.</span>

It does not show error message when user selects file other than image.

**Comment by danialfarid** [comment]
You should set `ngf-model-invalid` or set `allowInvalid` in the `ng-model-options`.
