### ISSUE TITLE
ngf-validate-after-resize="true" don't work

### ISSUE THREAD

**Issue by Aluman** [danialfarid/ng-file-upload#1786]
If I change 
              valids = validationResult.validsFiles;
to 
              valids = validationResult.validFiles;
it works fine.
https://github.com/danialfarid/ng-file-upload/blob/master/dist/ng-file-upload.js#L622

**Comment by chanchilun** [comment]
has been fixed already?

**Comment by danialfarid** [comment]
Not yet. You can submit a pull request.

**Comment by soniram** [comment]
Could you please fix this issue ?
It seems that line 623 needs correction also. My knowledge is limited to submit a pull request and help :-)

**Comment by LoneRifle** [comment]
This has not been released. Would you be kind enough cut a new one to npm and bower please?
