### ISSUE TITLE
please help me 

### ISSUE THREAD

**Issue by Jame0527** [danialfarid/ng-file-upload#1788]
I don't know why this
 error angular.js:13920 Error: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': '测试内容k6xj' is not a valid HTTP header field value.
    at XMLHttpRequest.eval [as setRequestHeader] (ng-file-upload-all.js:440)

**Comment by danialfarid** [comment]
Create jsfiddle or post your code. There are other similar issues on the github, search through the issues.
