### ISSUE TITLE
nested array multiple files

### ISSUE THREAD

**Issue by daewongz** [danialfarid/ng-file-upload#1789]
i always encountered error status 500 when try to upload files

this is my client side:

            Upload.upload({
              url : 'c1210Register.do',
              method: 'POST',
               data : { c1210ListBean : {attachment:$scope.file,fileNo:1}},
               objectKey: '.k'
            });

and this is my controller on server side.

  @RequestMapping(value = "c1210Register.do", method = RequestMethod.POST)
  @ResponseBody
  public ResponseEntity<Object> register(@RequestParam(value = "c1210ListBean") final C1210AttachmentBean pC1210ListBean) {
    ResponseEntity<Object> response = new ResponseEntity<Object>(HttpStatus.OK);

    return response;
  }

and for the bean

public class C1210AttachmentBean {

  /** Attachment. */
  private Object attachment;

  /** File no */
  private int fileNo;

  public Object getAttachment() {
    return this.attachment;
  }

  public void setAttachment(final Object pAttachment) {
    this.attachment = pAttachment;
  }

  public int getFileNo() {
    return this.fileNo;
  }

  public void setFileNo(final int pFileNo) {
    this.fileNo = pFileNo;
  }

}

Please help me thanks,

**Comment by danialfarid** [comment]
That's a server issue. See the java example and wiki page for java or find Spring tutorials for file upload to fix the backend code. There are also other similar issues if you search here.
