### ISSUE TITLE
Drop image from different browser tab (w/o hitting CORS errors)

### ISSUE THREAD

**Issue by knigal** [danialfarid/ng-file-upload#1790]
Hi
I'm trying to figure out how to drop an image from a different browser tab without hitting CORS.
Reproduction using a j[s fiddle from the README](http://jsfiddle.net/danialfarid/s8kc7wg0/400/)

Open a new browser tab with an online image such as [this random cat picture](https://s-media-cache-ak0.pinimg.com/736x/dc/6e/49/dc6e49d1c6fdc548282792aa5aab4891.jpg)

Grab the cat picture and drop it in the fiddle, on the `Drop pdfs or images here or click to upload` area. Then the devtools console shows:
```
XMLHttpRequest cannot load https://s-media-cache-ak0.pinimg.com/736x/dc/6e/49/dc6e49d1c6fdc548282792aa5aab4891.jpg. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://fiddle.jshell.net' is therefore not allowed access.
```
Is it possible at all to use the `ng-file-upload` module to grab images from other browser tabs? 
If not - what would be your advice/ideas to achieve that?

**Comment by danialfarid** [comment]
There might be some hacks by creating the image with the url inside a canvas and then convert that to image but I think browsers won't allow that anymore, so there is no simple solution since the cross browser access policy is for this reason to allow or not allow this kind of access.
