### ISSUE TITLE
Upload several files at once not working

### ISSUE THREAD

**Issue by brunneus** [danialfarid/ng-file-upload#1796]
Hello, I'm trying to upload several times at once but my API is recieving null, I've tried with only one file and works fine, there's some other configuration that  I have to do in order to send multiple files?

Here's my upload code:

        this.Upload.upload({
            url: apiUrl,
            method: 'POST',
            data: { file: myFiles }
        }).then((response: any) => {
            deferred.resolve(response);
        }, (error: Error) => {
            deferred.reject('Error'));
            console.log(error);
        });

        return deferred.promise;`

**Comment by Bleil** [comment]
+1

**Comment by danialfarid** [comment]
No special config needed. You need to fix your backend to be able to receive the files. If you look at the network tab of your browser you would see that the files are being sent in the xhr request.
