### ISSUE TITLE
Capture camera not working on Android (Ionic)

### ISSUE THREAD

**Issue by Amar444** [danialfarid/ng-file-upload#1797]
Hi guys. I have seen multiple (open and closed) issues about this on here, but none of them solved the problem for me...

Edit: I'm making an app in Ionic. 
When using ngf-select with `ngf-capture="camera"`, it doesn't show the camera option on Android. IOS works fine though..
I have tried it without the tags (still works on IOS..). with the tag `ngf-capture="camera"` and also `capture="camera"`. 

I have also tried using a `<button>` and `<input type="file"...>`, which also don't work..

I am using the following code:
`<div class="thumbnail_box col col-25" ngf-select="addImage(picFile)" ngf-fix-orientation="true" ngf-capture="camera" ng-model="picFile"  accept="image/*">`

None of them work.. I have also tried it with, and without the Crosswalker-project. Doesn't seem to make any difference.. Has anyone found a solution or workaround for this?

Any help appreciated!

**Comment by danialfarid** [comment]
If `<input type="file" capture="camera">` doesn't bring up the option then it is browser's bug. You can look into bugs of the specific browser that you are using.

**Comment by Amar444** [comment]
Found the problem. Seems I had to add:
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`
to the AndroidManifest xml file

**Comment by sbhandary** [comment]
I am still having the issue even after I added this to the AndroidManifest xml file <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />.

**Comment by gkimpson** [comment]
I am having the same issue however with Cordova, I have checked the AndroidManifest.xml file and have 
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />the permission added but still get this issue, any ideas?
