### ISSUE TITLE
APK upload failure?!

### ISSUE THREAD

**Issue by amhajavi** [danialfarid/ng-file-upload#1802]
As I try to upload an "apk" file before it even complete the service call the file field gets flushed out and remains empty during the service call. Is there any thing preventing an apk file to be uploaded?! Other files such as images and etc. get uploaded perfectly! 

ps. I'm trying your examples in usage section adding apk content type to ngf-accept and ngf-pattern directives.

**Comment by danialfarid** [comment]
Could be a browser or server restriction. There is no filter for the file type in the plugin.

**Comment by amhajavi** [comment]
@danialfarid  Could there be any processing involved making the file mandatory to be an image? there are no restrictions neither on server nor the browser. We tested it over various platforms and ended up with the same result.

**Comment by danialfarid** [comment]
Create a jsfiddle. You can also try your file on the demo page to make sure it is being uploaded if it uploads on the demo page then it is your server issue.
