### ISSUE TITLE
Some clear up for documentation

### ISSUE THREAD

**Issue by 1001v** [danialfarid/ng-file-upload#1803]
Hello. I think the existence of such parameters as $ngfHeight and $nghWidth in file object should be mentioned in documentation, as well as fact that their calculation performs asynchronously after $ngfDimensionPromise resolves. This information would be very helpful for people who'd like to create custom validate function.

**Comment by danialfarid** [comment]
You can use `Upload.imageDimensions()` to get those values and those variables are only for internal use and might be removed in the future so should not be used in prod only for debug purposes.
