### ISSUE TITLE
When I select button using ngf-select, ng-model is changed to null.

### ISSUE THREAD

**Issue by minyoungk** [danialfarid/ng-file-upload#1804]
I have this source.
```
<div class="row">
                    <ptgui-imagebox name="file1" class="col-md-3" style="width: 100px;height: 100px;" ng-model="product.image" ngf-max-size="1MB"; ngf-select></ptgui-imagebox>

                    <div class="col-md-4 hidden-sm hidden-xs">
                      <div class="file-drop-zone" ngf-select ngf-drop ng-model="product.image" ngf-drag-over-class="'file-drop-zone-over'" ngf-accept="'image/*'" ngf-pattern="'*.jpg,*.jpeg,*.gif,*.png'" ngf-max-size="1MB" name="file2">
                        <span class="help-block"><i class="fa fa-file-picture-o"> Drag and Drop</i></span>
                      </div>
                    </div>
                  </div>
```

when i click ptgui-imagebox showing image, ng-model is changed. 
but I want to maintain image before I select new image. 

How can I do?

**Comment by danialfarid** [comment]
You can use `ng-model-options="{updateOn: 'select drop'}"` but it will not allow you to select the same file again and if the user cancels the popup in Chrome the value will become null. That feature is there to have the same behaviour cross browser. So when the user opens the dialog it means that they want to select another file and if they cancel the old file is removed.
