### ISSUE TITLE
Detect when ngf-thumbnail is ready

### ISSUE THREAD

**Issue by danielbonnell** [danialfarid/ng-file-upload#1807]
I have a question (could be an issue request also) about whether it is possible to programmatically detect when `ngf-thumbnail` is ready to view. More specifically, I'm building an interface that will allow a user to select multiple photos, tag them, and then upload them. The problem I'm running into is that `ngf-thumbnail` seems to take several seconds before the thumbnail is displayed on the screen. Multiplied across multiple instances, it makes using it for this project untenable. 

Is there some way to detect when the thumbnail is ready to display? Or alternatively, some faster way to display thumbnails to the user. I'm working with photos shot on an iPhone and my interface needs to be mobile friendly and fast. It might almost be faster to just upload the files first, however i prefer to avoid that if possible.

Thanks!

**Comment by danialfarid** [comment]
Use `ngf-src`. Thumbnail will resize the images first and that could be slow.

**Comment by danielbonnell** [comment]
Much faster indeed. Thanks! 👍
