### ISSUE TITLE
None of the demo links are working.

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [danialfarid/ng-file-upload#1808]
None of the demo links are working.

![screen shot 2016-12-22 at 11 16 33 am](https://cloud.githubusercontent.com/assets/9896335/21416345/21f22b00-c838-11e6-9fdd-3ba1c562cb8c.png)

![screen shot 2016-12-22 at 11 16 06 am](https://cloud.githubusercontent.com/assets/9896335/21416346/2244e8c2-c838-11e6-96d0-affbce58bb0b.png)

**Comment by danialfarid** [comment]
Try again tomorrow or use the jsfiddle samples.

**Comment by jeevasusej** [comment]
[https://angular-file-upload.appspot.com/](https://angular-file-upload.appspot.com/)
Try the above demo.

**Comment by rajeshwarpatlolla** [comment]
Thanks, i can see that the demo links are working fine now.
