### ISSUE TITLE
I cannot see other type of video when file select

### ISSUE THREAD

**Issue by jeevasusej** [danialfarid/ng-file-upload#1813]
In chrome, I can see the mp4 file format. I can not view the flv file format.

In firefox, i am able to see mp4, flv and mkv.

[https://angular-file-upload.appspot.com/](https://angular-file-upload.appspot.com/)

**Comment by danialfarid** [comment]
It depends on the `accept` value if by "see" you mean they are not showing in the browsers popup for file selection.
