### ISSUE TITLE
ngf-select doesn't work on Android 6 with default browser

### ISSUE THREAD

**Issue by apinz1** [danialfarid/ng-file-upload#1817]
Hi all,
I'm trying the demo page (https://angular-file-upload.appspot.com/) on Android 6.0.1 default browser (Internet 5.0.20-45) but "Upload on form submit" doesn't upload the file. It works on the same device with other browser (like Chrome).

Same behaviour in my app. 

When I try to upload file with with this button inside a form:

`<button type="file" name="file" class="btn btn-sm btn-info" ngf-select="vm.uploadFile($file)" accept="image/*" ng-disabled="$invalidFiles" ngf-max-size="1MB" ngf-model-invalid="vm.errorFile" ng-model="vm.rightFile"> UPLOAD </button>`

and print the model var {{vm.rightFile}} it works fine from browser but in the above configuration the var value is {"$ngfDataUrl":""}.

Thanks a lot,
AP

**Comment by danialfarid** [comment]
Could be the browser's bug.
