### ISSUE TITLE
The directive doesn't interpolate in ng-transclude

### ISSUE THREAD

**Issue by ostaplisovyj** [danialfarid/ng-file-upload#1819]
In case I'd like to attach an id to the input filed using string interpolation, the directive stops responding, see the example below:

```
<input type="file"
               class="form-control" id="bg_image_{{btnCtrl.index}}"
               ngf-select="btnCtrl.uploadFiles($file, $invalidFiles)"
               accept="image/*" ngf-max-height="1000" ngf-max-size="1MB">
```

I assume that the digest cycle is not called at some point (as an example see [this topic](http://stackoverflow.com/questions/30360605/transclude-does-not-interpolate)

**Comment by Mangor** [comment]
@ostaplisovyj, try to use 
`ng-attr-id="bg_image_{{btnCtrl.index}}"`

**Comment by ostaplisovyj** [comment]
`ng-attr-id`doesn't appear to be working, the 'Upload' button doesn't open the modal window

**Comment by Mangor** [comment]
@ostaplisovyj can you create some example on jsfiddle or jsbin?

**Comment by ostaplisovyj** [comment]
closing due to issue being no more valid
