### ISSUE TITLE
IE9 error response undefined

### ISSUE THREAD

**Issue by albitxu** [danialfarid/ng-file-upload#182]
When uploading a file using IE9 the response received in the error event is always undefined. I can't get the error message received from the server. 

```
$scope.uploadTemplate = function() {
                $upload.upload({
                    url: '/data/kpi/upload?session_id=' + $scope.getSessionID(),
                    file: $scope.files[0],
                    paramName: 'file'
                }).success(function(response) {

                    }
                }).error(function(response, status) {
                    console.log('response=' + response);
                   //This is always undefined
                });
            };
```

In other browser it works perfectly. When the upload is successful everything goes fine. FileAPI is loading fine and also shim js. Why is the response always undefined? Am I doing something wrong? 

Can you help, please?

**Comment by shiva2035** [comment]
Hi, I am using the below code for uploading. It's working fine in IE 10,11,Edge, Firefox, Chrome. But in IE9 it's showing response 'undefined'.

Upload.upload({
        url: '/por/api/attachment',
        file: file
 }).progress(function (evt) {
        var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
        file.uploadPct = progressPercentage;
        console.log('In Progress');
  }).success(function (data, status, headers, config) {
        file.uploadPct = 100;
        file.attachmentData = data.response;
        console.log('In Success');
  }).error(function(response, status) {
        console.log('In Error');
        console.log('response=' + response);
});
});

Can you help, please?

**Comment by danialfarid** [comment]
So success is called with undefined response? What does your server sends back?

**Comment by shiva2035** [comment]
Yes, success is called with Undefined response.
My server sends back with empty data. In other browsers it sends the data.





Thanks & Regards,
*Shiva Kumar. K*
*+91 - 9963808956*
<http://in.linkedin.com/in/shiva2035>
<https://sites.google.com/site/shivab082035>

**Comment by danialfarid** [comment]
well if your server response is empty then you would expect empty data on the client too.

**Comment by shiva2035** [comment]
Did it work for anyone on IE9? I don't think it's problem with my back-end
code, because I checked for the response in back-end code with the help of
breakpoints the server is having some response.




Thanks & Regards,
*Shiva Kumar. K*
*+91 - 9963808956*
<http://in.linkedin.com/in/shiva2035>
<https://sites.google.com/site/shivab082035>
