### ISSUE TITLE
Invalid required state

### ISSUE THREAD

**Issue by norkunas** [danialfarid/ng-file-upload#1821]
When using required validation on model it should be false even if the selected file is invalid otherwise i can't use `<ng-messages>` directive because it always selects the `required` validation message.

**Comment by danialfarid** [comment]
Could you create a jsfiddle to explain what you mean.

**Comment by tsm91** [comment]
@danialfarid it simply doesnt work

```html
<input class="form-control form-control-solid"
                     name="avatar"
                     type="file"
                     accept="image/*"
                     ng-model="avatar"
                     ngf-select
                     ngf-model-invalid="errorFile"
                     ngf-max-size="2MB"
                     ngf-min-height="250"
                     required />

<span ng-show="avatarForm.$submitted && avatarForm.avatar.$error.required" class="help-block">{{ 'FORM.REQUIRED' | translate }}</span>
```


angular ver: 1.6.3
file-upload ver: 12.2.13

**Comment by ryan0122** [comment]
Doesn't work for me either! I want to disable the submit button until a file has been uploaded. 

This was working in Angular 1.4 but DOES NOT work in Angular 1.6.3
