### ISSUE TITLE
How to change the ngf-drop div  background color when drag over and the color change back after drop?

### ISSUE THREAD

**Issue by LUJULIANG2016** [danialfarid/ng-file-upload#1822]
How to change the ngf-drop div  background color when drag over and the color change back after drop?

**Comment by Mangor** [comment]
@LUJULIANG2016, use ngf-drag-over-class="'dragover'" and css something like that:
```
.dragover {
  background-color: red;
}
```

**Comment by LUJULIANG2016** [comment]
Thanks a lot
