### ISSUE TITLE
Is it possible to show progress bar while image previewing only

### ISSUE THREAD

**Issue by goutham-M** [danialfarid/ng-file-upload#1823]
because delay is there while image previewing, when image size is 3mb and I am resizing ngf-resize="{width: 500, height: 800}", ngf-fix-orientation= true .

**Comment by danialfarid** [comment]
You can use `ngf-before-model-change` to know when the resize is starting and once the model is set or callbacks are called the resize is finished, but there is no progress status you just know the beginning and the ending.
