### ISSUE TITLE
How to browse photo gallery from mobile browser as Facebook (image)

### ISSUE THREAD

**Issue by chhumsina** [danialfarid/ng-file-upload#1828]
Dear all,
I would like to ask about browsing photo gallery from mobile browser.
If there is directive about this help to share.
![15967776_1410151259009518_939875253_o](https://cloud.githubusercontent.com/assets/3894767/21812051/4cbf7bca-d784-11e6-89d6-fb0a4b984747.png)

Thank you,
CHHUM Sina

**Comment by danialfarid** [comment]
This plugin focuses on uploading photos. Displaying images in a grid would be another library.
