### ISSUE TITLE
Progress without chunk

### ISSUE THREAD

**Issue by rafwell** [danialfarid/ng-file-upload#1834]
Hi, the progress without chunk feature not work? I'm trying in last version of Chrome execute this code:

```javascript
Upload.upload({
            url: "admin/arquivos",
            data: $scope.arquivo
        }).then(function(response){
            console.log(response);
        }, 
        function(err){
         console.log(err);
       }, 
        function(evt){
            console.log('evt', evt);
        })
```

If i include the chunk config the progress work fine, but i no need chunk because the files are small.

**Comment by danialfarid** [comment]
Create a jsfiddle so I can verify. If the file is very small and is uploaded fast enough your progress might go directly to 100%. Also it could be your server config that doesn't support progress, you can try to change the upload url to the url in the demo page to verify it.
