### ISSUE TITLE
Should register with ngModel $validators in link function

### ISSUE THREAD

**Issue by fimius23** [danialfarid/ng-file-upload#1835]
Currently, the validators are basically lazy loaded the first time they are run. It would be better if, in the link function, they were registered in the ngModel's $validator pipeline. This would insure that only the validators that were needed were run, and is more consistent with angular standards. Might be nice if you could also namespace the validator name so that if, for example, one were to use ngPattern somewhere else in the application, the error message wouldn't be overwritten.

**Comment by danialfarid** [comment]
All the validations have "ngf-" namespace.
I had tried that approach first but gave up. Adding to validator pipeline would not work as smoothly first it won't work for versions prior to 1.3 so I would need to double the code to handle specific versions and second the validators are designed for single value input element and don't work well with the file input which can have an array of files and validations has to run on individual and/or all of the files (for example ngf-max-files). Also I believe it had issues with setting the files manually into the model.

Anyway contributions and submitting a PR would be appreciated If you could makes it work with validators and support for older versions.
