### ISSUE TITLE
Send string data along with file upload

### ISSUE THREAD

**Issue by Opariti** [danialfarid/ng-file-upload#1839]
Hi,
I want to send some string data in a POST using Upload, but I've found only as example the file upload parameter on client side, as here:

`Upload.upload({
                            url: 'api/upload_route',   
                            data: { file: vm.file}        
                        }).then(function (resp) { 
                       // ...............................
                       }` 
First, how can I add in the above code an object like 
`{"one": "first string", "two": "second string"} `<br>
to capture it in the server node js controller?
I have tried this
`data: { file: vm.file, "one": "first string", "two": "second string"}`<br>
but didn't work.
Second, how can I capture this object on the server side with something like
`req.body.data.one` for example.
Thanks

**Comment by danialfarid** [comment]
The way you are sending it seems fine. That's node.js question. You can verify how the request is being sent from the browser in the network tab of the browser and ask the question on node.js forum or stackoverflow.
