### ISSUE TITLE
How to Upload Multiple file

### ISSUE THREAD

**Issue by phannack** [danialfarid/ng-file-upload#1843]
I want to upload and Image File and PDF File. How to upload multi file?
Help me please.

`
  <form name="myForm">
    <fieldset>
      <legend>Upload on form submit</legend>
      Username: <input type="text" name="userName" ng-model="username" size="39">

      Profile Picture: <input type="file" ngf-select="" ng-model="picFile" name="file" ngf-accept="'image/*'">
 
      Resume(.pdf): <input type="file" ngf-select="" ng-model="resumeFile" name="fileResume">
 
      <button ng-disabled="!myForm.$valid" ng-click="uploadPic(picFile)">Submit</button>

  </form>

        $scope.uploadPic = function (file) {
            file.upload = Upload.upload({
                url: 'save_form.php',
                data: {
                    file: file,
                    username: $scope.username
                },
            });

            file.upload.then(function (response) {
                $timeout(function () {
                    file.result = response.data;
                });
            }, function (response) {
                if (response.status > 0) $scope.errorMsg = response.status + ': ' + response.data;
            }, function (evt) {
                // Math.min is to fix IE which reports 200% sometimes
                file.progress = Math.min(100, parseInt(100.0 * evt.loaded / evt.total));
            });
        };
`

**Comment by danialfarid** [comment]
```
Upload.upload({
            url: 'save_form.php',
            data: {
                file1: imageFile,
                file2: pdfFile, 
                username: $scope.username
            },
        });
```

**Comment by phannack** [comment]
Thank you.
It's work.
