### ISSUE TITLE
Getting public url after uploading to aws s3

### ISSUE THREAD

**Issue by abumere** [danialfarid/ng-file-upload#1847]
Is there currently a way to get the public url of an image after uploading it to aws s3? 

I would have expected the public url to be embedded somewhere in the returned value (after a successful upload) but I can't seem to find anything

**Comment by rahatarmanahmed** [comment]
The response you get after uploading to S3 has a `Location` header that contains the url of the thing you just uploaded. You can use that, or also just build the url yourself since you know what bucket and key you uploaded with.
