### ISSUE TITLE
CSV file type not recognized on windows environment causing valid files to be set to invalid ones

### ISSUE THREAD

**Issue by wjakobsmeier** [danialfarid/ng-file-upload#1849]
In windows environment using Chrome browser:
1. https://angular-file-upload.appspot.com/

2. replace accept, ngf-pattern, ngf-drag-over-class with "text/csv"

3. drag and drop .csv file 

Directive will not be able to retrieve the type of the file, it will be empty which results in the directive thinking the file is invalid/causes error:
"Invalid File: {"pattern": true} text/csv, name-of-file.csv - size: 1929B - type: 

screenshot:
http://oi68.tinypic.com/bg45s9.jpg

**Comment by danialfarid** [comment]
That is browser specific. If the browser does not report the mime-type of the file correctly there is not much to do. You can have a custom validator that validates the cvs file type or user `.cvs` for pattern instead of mime-type.
