### ISSUE TITLE
TypeError: Cannot read property 'file' of undefined (Solved)

### ISSUE THREAD

**Issue by noducks** [danialfarid/ng-file-upload#185]
On the off chance that anyone comes across this error while using node and express. This was the solution for me.

Since `express.bodyParser()` was getting deprecated. I had replaced it with:

```
app.use(express.urlencoded());
app.use(express.json());
```

But then started getting the `Cannot read property 'file' of undefined` error. Finally resolved it, by also adding. 

```
app.use(express.methodOverride());
app.use(express.multipart());
```

**Comment by ronakjain90** [comment]
If you are using Latest version of Express, you'd notice that 

```app.use(express.multipart()); ``` is no longer bundled with express.

So do the following configuration changes.

```multer  = require('multer'),
app.use(multer({ dest: './uploads/'}));```

You'd find that after doing this you would find the data and file , in req.body req.file respectively.

Hope it helps
