### ISSUE TITLE
Multipart headers not aligned

### ISSUE THREAD

**Issue by RogierKonings** [danialfarid/ng-file-upload#1851]
Dear,

`data: {
                    document: file,
                    documentItem: {
                        itemName: self.documentItem.itemName,
                        documentType: self.documentItem.documentType
                    }`

When i send the following file, combined with data that each will be send as multipart. Now when i check my browser for the request payload, I see the following:

------WebKitFormBoundarysAuPR3hHZVrqLD8D
Content-Disposition: form-data; name="document"; filename="Desert.jpg"
Content-Type: image/jpeg

------WebKitFormBoundarysAuPR3hHZVrqLD8D
Content-Disposition: form-data; name="documentItem[itemName]"

proofOfIdentityClient
------WebKitFormBoundarysAuPR3hHZVrqLD8D
Content-Disposition: form-data; name="documentItem[documentType]"

Government registration document
------WebKitFormBoundarysAuPR3hHZVrqLD8D--

Somehow it has misaligned the headers of each multipart, how is this possible??? I expect my that the data object that I pass should have it's key and value pairs in order.

**Comment by RogierKonings** [comment]
Clarification: 

itemName: proofOfIdentityClient,
documentType: Government registration document

**Comment by danialfarid** [comment]
That seems right. The content comes after the content-disposition.
