### ISSUE TITLE
The file above, 15 MB isn't (or gets partially) uploaded.

### ISSUE THREAD

**Issue by khatekar** [danialfarid/ng-file-upload#1852]
Hello,
I am using "ng-file-upload":  "11.0.0", "angular": "1.4.7", "node": "6.9.0" and "npm": "3.10.8".

I imported a file of size > 20 MB and it did not show up. Then I tried 12 MB and it showed up. All files less than 12MB are uploaded correctly. All the file-import POST requests get a 200 response. But the location where the file saved shows no or partially uploaded files. 
No issue with the nginx max file size upload, it has already increased (~15MB). Not sure what was the issue there were no logs in console or in the server.

One possibility in my setup could be, our production has 4 portal instances that are round-robbined. So, one instance might gets the data and writes and then another instance gets the data and messes up. But not sure how to debug it. Could the ng-file-upload has a way to persist with single instance every time it sends the data? How it handle or send data to multiple portal instances.?

Thank you.

**Comment by lbellows** [comment]
Its probably a server issue.  You should try a $http POST with a large file to make sure.

Troubleshooting:
You can try increasing timeouts on the server.
Try accessing servers directly via IP or modified hosts file so you know which one you're hitting.

**Comment by khatekar** [comment]
Thank @lbellows,

I got the issue and have found the workaround. The issue was with multiple instances, I mentioned above. 
The changes I made was with the nginx load balancing. I have disabled the load balancing for the '/file-upload' API. I have added a "location" in the nginx config for my API. Now it always uses a single assigned instance for the file upload API.
