### ISSUE TITLE
file uploading

### ISSUE THREAD

**Issue by thapaprince** [danialfarid/ng-file-upload#1854]
<form enctype='multipart/form-data' method="POST">
                                    <input type="file" file-model="customer.file">
                                     <button type="submit" ng-click="submit()">submit</button>
                                </form>

my cntroller->-------------
    
$scope.customer={};
        $scope.submit=function(){
            console.log($scope.customer);
          wsService.upload(
           $scope.customer
            );
my service----------------

var upload = function (file) {
            var defer = $q.defer();

            console.log(file);
 var fileFormData = new FormData();
            for(var key in file)
            fileFormData.append(key, file[key]);
            console.log(fileFormData);
 return defer.promise;
        };

my issu is fileFormData is showing empty{ }

**Comment by danialfarid** [comment]
console.log may not print the content of fileFormData
