### ISSUE TITLE
Selecting .app file causes browser to hang

### ISSUE THREAD

**Issue by alexeveritt** [danialfarid/ng-file-upload#1864]
This is a bit of a weird edge case. I clicked on an app file (on mac) just randomly and noticed that it takes ages to respond. Even though the file is not part of the selection pattern it seems like it's being processed locally - possibly for thumbnail.
Other file types like dmg/zip etc. are handled quickly and correctly.
It's not my intention to upload .app files however thought i'd mention it as it locks up the browser without any kind of notification. Eventually the browser comes back with invalid file.

![image](https://cloud.githubusercontent.com/assets/6032222/23024163/c65cfa8c-f450-11e6-83b8-cf2a7c3fd82d.png)

**Comment by danialfarid** [comment]
There is no special processing for .app inside the plugin. It is the browser that does some checking I believe so the work around would be to filter those files out in using `accept` or `ngf-accept`.
