### ISSUE TITLE
ngf-resize-if $file arg is always the last file when uploading multiple

### ISSUE THREAD

**Issue by digitalgears** [danialfarid/ng-file-upload#1867]
I set ngf-resize-if="resizeCondition($file, $width, $height)" as per the docs, but when uploading multiple files the $file arg is always set to the last file I am trying to upload.

I think the issue is with the handleFile method (ln 508)
``` javascript
params.resizeIf = function (width, height) {
    return upload.attrGetter('ngfResizeIf', attr, scope, {$width: width, $height: height, $file: f});
};
```
params.resizeIf seems to get overridden with each iteration.

**Comment by danialfarid** [comment]
`ngf-resize-if="resizeCondition($width, $height)"` this is the syntax in the docs.

**Comment by osro** [comment]
> `ngf-resize-if="resizeCondition($width, $height)"` this is the syntax in the docs.

That is definitely not the syntax in the docs! 

This is what GitHub page says like @digitalgears already wrote.
`resizeCondition($file, $width, $height)`
