### ISSUE TITLE
upload() requires 'file' property, not 'data'

### ISSUE THREAD

**Issue by rocifier** [danialfarid/ng-file-upload#1874]
We could only get our code working using the following inside umbraco's backshop which seems to use version 9.3 of ng-file-upload:

    Upload.upload({
            url: 'upload/url',
            file: file
    })

not the following as documented:

    Upload.upload({
            url: 'upload/url',
            data: {file: file, 'username': $scope.username}
    })

we were unable to find the file property documented anywhere and this took a considerable amount of time to debug.

**Comment by danialfarid** [comment]
It is there for the backward compatibility. The library might be using and older version of ng-file-upload.

**Comment by jasonwr** [comment]
The 'file' parameter works for me to and I'm using the latest. Not sure why 'data' is included.

**Comment by jasonwr** [comment]
Also why is $ngfBlobUrl posting an image to a random file under tmp? I'm seeing newly uploaded files such as this:

/tmp/A-GDOzM9x4l-ynUl83a_nsb-.JPG

I set the path and everything. Seems like the upload function is doing some magic here that isn't well documented.
