### ISSUE TITLE
Uploading base64 example

### ISSUE THREAD

**Issue by rvmladenov** [danialfarid/ng-file-upload#1875]
Hi, there ... I am having troubles making an example of uploading base64 to a server. I have a base64 so I do not need to convert it but I can not figure out how to do the rest. Can anyone help me with this ?

**Comment by danialfarid** [comment]
Just send a `$post` with the base64 string in the body if you want base64 on the backend. Otherwise convert it to file using `Upload.urlToBlob(url).then(function(blob) {...});` and upload it.
