### ISSUE TITLE
No 'Access-Control-Allow-Origin' header....

### ISSUE THREAD

**Issue by jeffthompson1971** [danialfarid/ng-file-upload#188]
"XMLHttpRequest cannot load http://localhost:8080/service. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access. "

Seems with angular I can never get my requests to NOT do pre-flight.   I'm seeing an 

So I would expect if this is using built-in angular that the OPTIONS request is sent first.  And indeed it is, but nothing happens after that other than I get this error.  Seems my response headers allow most things.   What else needs to happen?   

I would use a fiddle, but I quite literally have your code in both your GAE server example and your view and controller files exactly like you have in your repo.   I did try to play with request headers but no help....

This is my trace of the initial OPTIONS request and response that LOOKS good.   I have no idea how that response is coming with all those options set.. is it getting that from my apache config or something?    Anything jumping out here?

Remote Address:127.0.0.1:8080
Request URL:http://127.0.0.1:8080/service
Request Method:OPTIONS
Status Code:200 OK
Request Headers-view source
Accept:_/_
Accept-Encoding:gzip,deflate,sdch
Accept-Language:en-US,en;q=0.8,tr;q=0.6
Access-Control-Request-Headers:accept, method, content-type
Access-Control-Request-Method:POST
Cache-Control:no-cache
Connection:keep-alive
Host:127.0.0.1:8080
Origin:http://localhost
Pragma:no-cache
Referer:http://localhost/okrp/app/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.116 Safari/537.36 FirePHP/4Chrome
X-FirePHP-Version:0.0.6
X-Wf-Max-Combined-Size:262144

Response Headers-view source
Allow:GET, HEAD, POST, TRACE, OPTIONS
Cache-Control:no-cache
Content-Length:0
Date:Sat, 12 Apr 2014 00:05:14 GMT
Expires:Fri, 01 Jan 1990 00:00:00 GMT
Server:Development/1.0

**********************\* MY (YOUR) CONTROLLER ******************

assetsApp.controller('reportCtrl', [ '$scope', '$upload', function($scope, $upload) {
  $scope.onFileSelect = function($files) {
    //$files: an array of files selected, each file has name, size, and type.
    for (var i = 0; i < $files.length; i++) {
      var file = $files[i];
      $scope.upload = $upload.upload({
        url: 'http://localhost:8080/service',//upload.php script, node.js route, or servlet url
        // method: POST or PUT,
        // headers: {'header-key': 'header-value'},
        // withCredentials: true,

```
    //headers: {'method':'POST', 'Content-Type': undefined},
    data: {myObj: $scope.myModelObj},
    file: file, // or list of files: $files for html5 only
    /* set the file formData name ('Content-Desposition'). Default is 'file' */
    //fileFormDataName: myFile, //or a list of names for multiple files (html5).
    /* customize how data is added to formData. See #40#issuecomment-28612000 for sample code */
    //formDataAppender: function(formData, key, val){}
  }).progress(function(evt) {
    console.log('percent: ' + parseInt(100.0 * evt.loaded / evt.total));
  }).success(function(data, status, headers, config) {
    // file is uploaded successfully
    console.log(data);
  });
  //.error(...)
  //.then(success, error, progress); 
  //.xhr(function(xhr){xhr.upload.addEventListener(...)})// access and attach any event listener to XMLHttpRequest.
}
/* alternative way of uploading, send the file binary with the file's content-type.
   Could be used to upload files to CouchDB, imgur, etc... html5 FileReader is needed. 
   It could also be used to monitor the progress of a normal http post/put request with large data*/
// $scope.upload = $upload.http({...})  see 88#issuecomment-31366487 for sample code.
```

  };
}]);

**Comment by viconn** [comment]
XMLHttpRequest cannot load http://192.168.1.17:8080/uploadTest.do. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

**Comment by danialfarid** [comment]
@viconn you need to enable CORS on your server.

**Comment by viconn** [comment]
server Use CORS ~

**Comment by viconn** [comment]
HTML CODE
 <form name="myForm">
        <fieldset>
            <legend>Upload on form submit</legend>
            Username:
            <input type="text" name="userName" ng-model="username" size="31" required>
            <i ng-show="myForm.userName.$error.required">*required</i>
            <br>Photo:
            <input type="file" ngf-select ng-model="picFile" name="file" accept="image/*" ngf-max-size="2MB" required>
            <i ng-show="myForm.file.$error.required">*required</i>
            <br>
            <i ng-show="myForm.file.$error.maxSize">File too large 
          {{picFile.size / 1000000|number:1}}MB: max 2M</i>
            <img ng-show="myForm.file.$valid" ngf-thumbnail="picFile" class="thumb">
            <button ng-click="picFile = null" ng-show="picFile">Remove</button>
            <br>
            <button ng-disabled="!myForm.$valid" ng-click="uploadPic(picFile)">Submit</button>
            <span class="progress" ng-show="picFile.progress >= 0">
        <div style="width:{{picFile.progress}}%" 
            ng-bind="picFile.progress + '%'"></div>
      </span>
            <span ng-show="picFile.result">Upload Successful</span>
            <span class="err" ng-show="errorMsg">{{errorMsg}}</span>
        </fieldset>
        <br>
        
    </form>

javascript CODE 
___________________________
var app = angular.module('fileUpload', ['ngFileUpload']);


app.controller('MyCtrl', ['$scope', 'Upload', '$timeout', function($scope, Upload, $timeout) {
    $scope.uploadPic = function(file) {
        file.upload = Upload.upload({
            url: 'http://192.168.1.7:8080/uploadTest.do',
            data: {
                file: file,
                username: $scope.username
            },
            method:'JSONP',
            headers: {
              /*  'enctype': 'multipart/form-data',*/
               /* 'Content-Type': undefined,*/
                /*'Access-Control-Allow-Origin': '*'*/

            } 
        });

        file.upload.then(function(response) {
            $timeout(function() {
                file.result = response.data;
            });
        }, function(response) {
            if (response.status > 0)
                $scope.errorMsg = response.status + ': ' + response.data;
        }, function(evt) {
            // Math.min is to fix IE which reports 200% sometimes
            file.progress = Math.min(100, parseInt(100.0 * evt.loaded / evt.total));
        });
    }
}]);

ERROR INFO
_____________
the request doesn't contain a multipart/form-data or multipart/mixed stream, content type header is null
