### ISSUE TITLE
ngf-select can't select PDF files from Google Drive on iOS

### ISSUE THREAD

**Issue by WuglyakBolgoink** [danialfarid/ng-file-upload#1880]
Hi, I can't select `PDF` files from `Google Drive` on `iOS v10.0.2(14A456)` (https://github.com/danialfarid/ng-file-upload/issues/1624)

- angular: 1.5.8
- ng-file-upload: 12.2.13
- cordova: 6.5.0

```html
<button
                type="button"
                data-ngf-select="vm.uploadFiles($files, $invalidFiles)"
                ngf-multiple="false"
                data-ng-model="vm.file"
                data-ngf-capture="'other'"
                data-ngf-pattern="'image/jpg,image/png,image/jpeg,application/pdf'"
                data-ngf-accept="'image/jpg,image/png,image/jpeg,application/pdf'"
                data-ngf-max-size="50MB">
                Select File
</button>
```

![img_0004](https://cloud.githubusercontent.com/assets/2271337/24003400/a6148f8c-0a63-11e7-823e-b9d85760c227.JPG)

**Comment by WuglyakBolgoink** [comment]
If I remove 
```html
data-ngf-accept="'image/jpg,image/png,image/jpeg,application/pdf'"
```

it work fine, but can select not allowed file types...

**Comment by danialfarid** [comment]
`accept` is browser specific implementation so there's not much can be done on the plugin level.
