### ISSUE TITLE
Cordova iOS - iCloud not found

### ISSUE THREAD

**Issue by WuglyakBolgoink** [danialfarid/ng-file-upload#1886]
Hallo,

In iPad v10.0.x -> Safari -> if I click on button -> `OK` -> iCloud exist in choosing-Dialog
in Cordova+WkWebKit -> if I click on button -> `BAD` -> iCloud not exist in choosing-Dialog

---

- Browser
![image](https://cloud.githubusercontent.com/assets/2271337/24293647/17fbb37a-1093-11e7-8d7b-d8122eab64e6.png)
- Cordova App
![image](https://cloud.githubusercontent.com/assets/2271337/24293674/37bb423e-1093-11e7-9cb7-462c069db931.png)

---

Can't understand why it doesn't work...

**PS**: Im Provision Profile iCloud is disabled (But this is neccessary only if we will save files in Cloud, in my case I must only read file and upload it)
![image](https://cloud.githubusercontent.com/assets/2271337/24293725/83b49e24-1093-11e7-86a9-96af0ecca6c0.png)

**Comment by WuglyakBolgoink** [comment]
@danialfarid any idea to fix this?

**Comment by WuglyakBolgoink** [comment]
1. For using **iCloud** you should activate it in "**Capabilities**" Tab in **xCode**
2. We have now Problemn with latest iOS version. if I click on button, I can do only Photos. No popup dialog...

**Comment by Arxi** [comment]
Were you able to solve the second issue (seeing only Photos)?

**Comment by WuglyakBolgoink** [comment]
this ticket can be closed.

Solution: Change settings in xCode

**Comment by WuglyakBolgoink** [comment]
@Arxi 
https://github.com/danialfarid/ng-file-upload/issues/2004
