### ISSUE TITLE
multiple not working with ngf-drop

### ISSUE THREAD

**Issue by PPVphilosopher** [danialfarid/ng-file-upload#1900]
Hi Danial
I cannot upload multiple files using ngf-drop (see sample code here -> http://jsfiddle.net/huhjo9jm/705/ )
How I can do this?
Thanks in advance.

**Comment by dieontime** [comment]
ngf-multiple="true" made it work!

**Comment by PPVphilosopher** [comment]
@dieontime ok, it work! thanks a lot
