### ISSUE TITLE
Is support in Angular 2?

### ISSUE THREAD

**Issue by binal24** [danialfarid/ng-file-upload#1994]
Can this directive is support in angular 2/angualr 4?
**I need file upload directive which send data in chunks.**

**Comment by Assdi** [comment]
I want to use it in angular 4 . pleas help with docs @binal24

**Comment by Assdi** [comment]
I want to use it with angular 4 , any docs ? @binal24

**Comment by srinig29** [comment]
Can i use this for Angular 5?
