### ISSUE TITLE
ngf-change not working in windows

### ISSUE THREAD

**Issue by dream-play** [danialfarid/ng-file-upload#2030]
`<div ngf-select ngf-drop ng-model="ctrl.vm.file" name="upload-csv-form-element"
                                 ngf-pattern="'*/*'"
                                 ngf-accept="'*/*'"
                                 ngf-change="ctrl.vm.fileSelected($files, $file, $newFiles, $duplicateFiles, $invalidFiles, $event)"
                                 ng-disabled="ctrl.vm.isUploading"
                                 class="form-control file-upload">Select File
                            </div>`

I am trying to upload a "tab separated file", when I browse to the file I want to select from my WINDOWS 7/10 system, and double click it, the **fileSelected** function doesn't get any parameter values set. They are null/empty. Everything works just fine in Mac / Linux system.

I tried in incognito mode, in both chrome and firefox.

**Comment by dsmithco** [comment]
I am having this issue too. Any solution?

**Comment by vijikraj** [comment]
I face this issue too.File Selected value is null.

**Comment by dream-play** [comment]
I was able to solve it by getting rid of most of the unnecessary ngf-S
