### ISSUE TITLE
Maximum File Size limited to 1mb

### ISSUE THREAD

**Issue by vcoderyt** [danialfarid/ng-file-upload#2055]
When a file of size more than 1mb is tried to upload it fails with a 413 (Request entity too large) error. Tried ngf-maxsize and some other things. Is there any config parameter to be set to solve this?

**Comment by shane9** [comment]
Looks like a server-side error. You'll need to modify your server or web application configuration to accept larger files

**Comment by vcoderyt** [comment]
Got it.. It was my nginx issue. Had to add in nginx.conf "client_max_body_size 100M;".
Thanks..
