### ISSUE TITLE
Chrome crashing when uploading large files

### ISSUE THREAD

**Issue by LukeKittridgeProteo** [danialfarid/ng-file-upload#206]
Hi,

I've found an issue when trying to upload large files using google chrome on windows (though this issue sometimes occurs in firefox). It can be replicated on the demo site http://angular-file-upload.appspot.com/ by selecting "File binary content with the file type as Content-Type header using $upload.http() service" and then selecting a large file, the one I've tested with is 138MB

In the task manager if you look at the memory usage for chrome it will shoot up until chrome force closes the the tab.

I don't know if this is an issue with the file uploader or an underlying issue with angular or the browser itself.

Thanks.

**Comment by caneraydinbey** [comment]
Any improvement?
