### ISSUE TITLE
Cannot seem to post multiple files to action expecting List<HttpPostedFileBase>

### ISSUE THREAD

**Issue by nmartin867** [danialfarid/ng-file-upload#212]
I've read the section concerning uploading multiple files in your README. I am trying to post multiple files to an ASP MVC action. The action signature looks like this:

<pre><code> public JsonResult AddPictures(List &lt;HttpPostedFileBase&gt; albumPictures, long albumId)</code></pre>

I am assigning 'fileFormDataName' to an array of file names. However 'albumPictures' is always null when the data arrives at the server. I must be missing something. Can you offer any advice?

<pre><code>
function uploadRapidPhotos(photos, rapidAlbumId) {
        var deferred = $q.defer();
        var fileNames = [];
        angular.forEach(photos, function(value) {
            this.push(value.name);
        }, fileNames);
        $upload.upload({
            url: configuration.host() + '/Photo/AddPictures',
            method: 'POST',
            fileFormDataName: fileNames, //array of filenames
            data: { albumId: rapidAlbumId }, //second parameter. This works fine
            file: photos //array of files ($files)
        }).success(function() {
            deferred.resolve();
        });
        return deferred.promise;
    }
</code></pre>

**Comment by kbsaravana** [comment]
Hi Martin, Im also facing issues with uploading multiple files, this is really helpful please tell more about object photos. 
is it a array of formdata objs of files?
 plse help me to process from <input type "file" object like filecntrl.files[0]
