### ISSUE TITLE
File upload demo does not work under IE 10

### ISSUE THREAD

**Issue by roypeled** [danialfarid/ng-file-upload#22]
I tried this demo: http://angular-file-upload.appspot.com/
In IE 10 I can only select a file and then nothing happens, no upload.

I have flash installed, but the browse buttons are not flash movies.

**Comment by jvaleroso** [comment]
I faced exactly the same issue. I was able to upload two files at first and then a waited for 3 to 5 mins and click the upload button again, after that the request is pending forever... It doesn't throw any error and it doesn't even reach the web api controller.
