### ISSUE TITLE
Identify file uploaded (multiple files) to sum all files progressBar

### ISSUE THREAD

**Issue by rainmakertwo** [danialfarid/ng-file-upload#231]
How can make a sum of all my files being loaded simultaneously for a progressBar.

I edited a little the angular-file-upload example so all the files (4) are submitted when I click a SEND button.

for example: 
  file 1: 20%
  file 2: 13%
  file 3: 80%
  file 4: 50%

progress = file1+file2+file3+file4 / 4;

the problem is that the "evt" does not identify files.

var files = $files;
for (var i = 0; i < files.length; i++) {
    if(files[i]){
                 dressesServ.uploadPhotos(files[i], $stateParams.dressId, $scope.myModelObj)  
                    .progress(function(evt){
                        console.log(evt);  
                        $scope.uploadProgress = ?;
                    })
                   .success(function(data, status, headers, config){
                       console.log('file uploaded');
                    }); 
       }
}

If someone have some ideas.I will aprecciate it so much if you share.

**Comment by tahirdemirtas** [comment]
How did you solve this?
