### ISSUE TITLE
ngFileSelect: re-selecting same file

### ISSUE THREAD

**Issue by natwallbank** [danialfarid/ng-file-upload#235]
Hi,

I've just migrated some custom in-house code to use angular-file-upload (good job, btw!) and am just hitting one problem.

We use ngFileSelect to add files to a queue, so users can either select or drag files into a queue and they can remove items from that queue before hitting an 'Upload' button.

If a user removes a file from the queue (just an array on my directive scope) but then decides they made a mistake and re-adds the file, it doesn't work, presumably because the file input is holding some state.

I remember we encountered this problem with our own custom directive that did a similar job, and the way we resolved it was by doing the following at the end of the 'change' event handler:

``` JavaScript
elem.replaceWith(elem.clone(true));
```

I'm just wondering whether this is a known issue and if you have any kind of workaround for it?

Thanks in advance.

Nat

**Comment by akshay-bbytes** [comment]
`onclick="this.value=null"` worked fine for me, thanks :)

**Comment by rajguru827** [comment]
it's not working in windows safari.

**Comment by JDVS20** [comment]
I resolved this issue using this,

onChange(event:any):void{
event.srcElement.value = "";
}
