### ISSUE TITLE
Directory Structure Upload

### ISSUE THREAD

**Issue by webdevjg** [danialfarid/ng-file-upload#238]
Is there a way to upload both the files and directory structure?
Currently it appears the demo just uploads the files and not folder structure?

Ex.
Folder A
| -Folder B
  ---File in folder B
  ---File in folder B

Browser - Chrome.
Angular file - version 1.40
Angular version - 1.2.14

**Comment by danialfarid** [comment]
Option `ngf-include-dir` is added since 11.2.x to include the directories in the dropped files output.
You can detect it by `type == 'directory'`. The name of the files/directories when this option is set will be the relative path of the file/directory.
