### ISSUE TITLE
Trigger file upload selection from script on page?

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [danialfarid/ng-file-upload#274]
Hello, I have a scenario where I do not want the upload component to be visual on the page but instead triggered by a menu option via javascript.

The user would still select the file, (I'm not trying to do a stealth upload) but they would not click on anything in the page itself to do it but rather via a command on a menu (in another controller entirely), not from a component visually on the page that they click on.

So I guess what would have to happen is the component would need to be hidden on the page but triggered via javascript in the controller if possible.

Is this possible and if so any suggestions appreciated.

**Comment by amritk** [comment]
I can't get it to open at all. My filesList exists so its doing something, but I don't get the dialog asking which file to upload. I know some things are different now, can anyone get this to open programatically?

```
angular.element(document.getElementById('postform_status_photo')).triggerHandler('click')
```
```
		<md-button id="postform_status_photo" class="button-icon-right large-icon" flex ngf-select ng-model="postformStatus.files" ngf-accept="'image/*'" ng-if="postformStatus.submit">
		  	<md-icon md-font-icon="icon-camera"></md-icon>
		  	Add Photo
		</md-button>
```

**Comment by p-mcgowan** [comment]
+1 having the same problem as @amritk

**Comment by pankajdaffodil** [comment]
Thanks, I have resolved my problem without wasting of time.:)

**Comment by geethaar09** [comment]
@amritk - I have the same problem, I can't get the attachment dialog to open. Did you get this resolved?

angular.element('#uploadAttachment').triggerHandler('click'); --> this does not seem to work for me

**Comment by amritk** [comment]
@geethaar09 I haven't got it working yet either

**Comment by danialfarid** [comment]
I believe if you are using angular material it prevents programmatic clicks.

**Comment by p-mcgowan** [comment]
With angular v1.5.0-rc.0, this seems to have been fixed - this now works:
```this.$timeout(function () {document.getElementById('upload').click()});```

**Comment by amritk** [comment]
@geethaar09 I can confirm this works, good job @p-mcgowan

**Comment by VivienZo** [comment]
Thanks @p-mcgowan

**Comment by damianobarbati** [comment]
I can't have this working (angular@1.5.7 + ng-file-upload@12.0.4).
I have a form with a container component with generic button "upload", and then I have an "uploader" component with the real upload button and the gallery of uploads (they're in totally separate divs).

How can I trigger the button inside <upload></uploader> from the other generic button? Element in forwardClick is found and defined but the .click() method on it doesn't trigger the file window.

Excerpts:
```
//uploader.html in upload component
<button ngf-change="$ctrl....."....></button>

//view.html in container component
    <div>
        <div class="action-buttons">
            <button type="button" class="button-default" ng-click="$ctrl.forwardClick('[ngf-change]')"><span>Upload</span></button>
			<button type="button" class="button-primary" ng-click="$ctrl.data.content.length > 4 && $ctrl.call($ctrl.add)"><span>Post</span></button>
        </div>
    </div>
	<uploader></uploader>

//forwardClick method in container component controller
	forwardClick(selector) {
		this.services.$timeout(() => {
			let element = document.querySelector(selector).click();
		});
	}

```

**Comment by duartealexf** [comment]
Thank you @p-mcgowan. As for @geethaar09, @amritk, from what I tested and saw in http://api.jquery.com/triggerHandler/ , triggering the handler won't work because it only does what it states: triggers the handlers. So any functions listening on the element's click would run as if it was clicked, but the DOM event 'click' itself does not bubble up to the window, so the browser doesn't know the element was clicked, therefore not showing the dialog. p-mcgowan's solution relies on raw javascript click() method so it works. But it also seems to be risky as it is non-standard. It seems to be the only solution so that is what I'm going for.

**Comment by TD-Stanley** [comment]
I'm still having issues with this: 

`              <input id="upload" type="file" class="hide" ngf-drop="droppedFile()" required ng-model="post.picturePreCrop" ngf-pattern="image/*" ngf-select="droppedFile()" accept="image/*" ngf-accept="'image/*'" ngf-pattern="'.jpeg,.jpg,.png,.gif,.bmp'" ngf-max-size="5MB" ngf-max-files="1" ngf-fix-orientation="false">`

I'm attempting to call it automatically when the view loads: 

```
    $timeout(function () {
      console.log('timeout')
      document.getElementById('upload').click();
    }, 100);
```

**Comment by andersborum** [comment]
@TD-Stanley any progress or solution to this issue? I'm facing the same issue from the same setup and it works if the click is invoked from the console or upon opening the modal two or more times; but the first time it fails (or doesn't respond to the click event).

I'm thinking it's some kind of timing issue related to the angular digest cycle or something in the DOM that isn't fully initialized from the upload directive. Very strange.
