### ISSUE TITLE
File type reports an empty file type for OpenXML MS Office documents

### ISSUE THREAD

**Issue by auchenberg** [danialfarid/ng-file-upload#291]
Caused by this issue in Chrome, https://code.google.com/p/chromium/issues/detail?id=155455

The workaround is to disable the directory support, which is using the flawed webkit prefixed API. 
I created a fork with the change, as this was a blocker in our product (PPTX files wouldn't upload)

See https://github.com/auchenberg/angular-file-upload/commit/5d61b45d72b6ea5f01a10b36c15b8cdb10a40eac

**Comment by lbellows** [comment]
I am still getting this in 12.2.13
