### ISSUE TITLE
Resize the image during upload

### ISSUE THREAD

**Issue by surampark** [danialfarid/ng-file-upload#295]
Can I resize the image during upload?

**Comment by danialfarid** [comment]
Feature added in version 7.2.1.

**Comment by piotrd** [comment]
@danialfarid was cropping really added? I can see the release note saying `Added image resize feature #996, #295` , but there seems to be no mention of cropping.

**Comment by danialfarid** [comment]
@piotrd no it is not added

**Comment by danialfarid** [comment]
Add image cropping.

**Comment by danialfarid** [comment]
Integration with ngImgCrop is the way to go. Find the sample jsfiddle in readme on how to use these two plugins together:
http://jsfiddle.net/xxo3sk41/1/
