### ISSUE TITLE
Callback not triggered: IE9

### ISSUE THREAD

**Issue by ghost** [danialfarid/ng-file-upload#304]
Hi!

I have issues with the directive, when Internet Explorer 9 is used.
The File gets uploaded correctly, but none of the callbacks gets triggered.

The following exception gets throwed, when the uploading starts or ends, i can't tell (debug enabled):
[transport.onload] SyntaxError: Invalid Syntax

These js-files are included and the swf-file successfully gets loaded:

```
<script type="text/javascript" src="/js/upload/FileAPI.min.js"></script>
<script type="text/javascript" src="/js/upload/angular-file-upload-shim.min.js"></script>
<script type="text/javascript" src="/js/upload/angular-file-upload-html5-shim.min.js"><script>
<script type="text/javascript" src="/js/angular.js"></script>
<script type="text/javascript" src="/js/upload/angular-file-upload.js"></script>
```

The code:

```
$scope.upload = $upload.upload({
    url: url + _uuid,
    method: 'POST',
    file: file
});

$scope.upload.progress( function (event, zus) {
    _file.progress = parseInt(100.0 * event.loaded / event.total);
}).success( function (data, status) {
    _file.nfileid   = data.nfileid;
    _file.hash      = data.hash;
    _file.progress  = null;
    callback(_file);
}).error( function (data, status) {
    Messenger.push({title: 'Error', type: 'error', text: data.text});
});
```

The response from the server is as following:

```
{"nfileid":361,"cfilename":"Lorem Ispum.pdf","hash":"33dbc9b29358aefba0b31bdd7ab3290f","hashKey":"304f1cbb-5fb5-6baa-840d-d8efbe9ca6c2"}
```

**Comment by asso1985** [comment]
I'm having the same problem

**Comment by tawani** [comment]
I am having this same issue with IE9 and still can't figure out how you resolved it

**Comment by fdidron** [comment]
I'm also getting the issue 'c00c023e' using the current demo site on IE9 / Japanese Env
@dongdingdong How did you fix that issue ?

**Comment by danialfarid** [comment]
Any stacktrace from FileAPI? Can you put some breakpoints in the shim file and see how far it is being executed,

**Comment by danialfarid** [comment]
or you could post here the console log when it happens.

**Comment by fdidron** [comment]
Sure, should I open a new issue ?

**Comment by danialfarid** [comment]
If it is the same issue reopen this otherwise yes
