### ISSUE TITLE
ng-file-select inside ng-repeat behaves... strangely...

### ISSUE THREAD

**Issue by cribbsjy** [danialfarid/ng-file-upload#330]
I am trying to create an upload icon for each object in my ng-repeat (ng-repeat="object in objects").  I have created a service for the onFileSelect function, which is called in my controller.  To determine where to assign the uploaded file, I am trying to pass the object's ID (ng-file-select="controller.onFileSelect($files, object.id).  However, no matter what I do, object.id = 0.  In fact, object always equals the first object returned in objects.

If I create another button that does an ng-click instead of ng-file-select, the correct object.id is passed to the controller.  Do you know why this could be happening?

Full disclosure -- I am fairly new to AngularJS, so I could be missing something simple.  If that is the case, I apologize for bothering anybody with this.

**Comment by burzum** [comment]
@danialfarid I have a similar problem, it's not working for me inside a ng-repeat. The `files` always stay empty. See http://stackoverflow.com/questions/31313845/angularjs-ng-file-upload-not-working-inside-ng-repeat or go directly to the plunk http://plnkr.co/edit/QRWBmmSDEjgRH2N0OBEF

**Comment by edencorbin** [comment]
I only get one input in chromium from this fiddle, looking to see if I can use this library in an ng-repeat or not.
