### ISSUE TITLE
Multiple progressbar

### ISSUE THREAD

**Issue by sansantosh** [danialfarid/ng-file-upload#348]
I am uploading one file at a time. I want to show individual progress bar for each file i am uploading.  When uploading second file, progress bar for first uploading will stop moving. 

Here is my code:

$scope.upload[idx].progress( function(evt) {
       $scope.progressBars[idx].width = Math.min(100, parseInt(100.0 \* evt.loaded / evt.total);
}

**Comment by rohanbhangui** [comment]
@sansantosh how did you solve it exactly? im having the same issue

**Comment by rohanbhangui** [comment]
okay so for people who come here for future reference: you have to follow the demo to the T. you can skip the if statements for different methods of upload if you like. But yes you need to follow it to the letter.

**Comment by sansantosh** [comment]
Cool. Glad you figure it out.
