### ISSUE TITLE
ng-file-drop-available doesn't seem to work.

### ISSUE THREAD

**Issue by nknj** [danialfarid/ng-file-upload#351]
The [DEMO](https://angular-file-upload.appspot.com) page on my iOS 8 Safari Browser and Android 4.3 Stock Browser both show the file drop div.

[Can I use](http://caniuse.com/#feat=dragndrop) shows that Drag and Drop should not work on these browsers.

**Comment by ravishivt** [comment]
+1, this is still a problem with the latest 3.2.4 release.

**Comment by danialfarid** [comment]
Fixed in version 4.0.0
