### ISSUE TITLE
404 response with CORS

### ISSUE THREAD

**Issue by navotera** [danialfarid/ng-file-upload#353]
im using firefox 32. i use your plugin in my ionic app, my server is PHP and it just  print log to show the response. But on the process the uploading request is return 404 response ... 

here is the log in the firebug : 
Request Header : 
Accept  text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
Accept-Encoding gzip, deflate
Accept-Language en-us,id;q=0.7,en;q=0.3
Access-Control-Request-Me...    POST
Cache-Control   no-cache
Connection  keep-alive
DNT 1
Host    localhost
Origin  http://localhost:8100
Pragma  no-cache
User-Agent  Mozilla/5.0 (Windows NT 6.1; WOW64; rv:32.0) Gecko/20100101 Firefox/32.0

and the Response header : 
Connection  Keep-Alive
Content-Length  99
Content-Type    application/xml; charset=utf-8
Date    Sun, 12 Oct 2014 09:21:39 GMT
Keep-Alive  timeout=5, max=100
Server  Apache/2.4.9 (Win64) PHP/5.5.12
Set-Cookie  ci_session=a%3A5%3A%7Bs%3A10%3A%22session_id%22%3Bs%3A32%3A%229da86f73b3c1dbcd3cbe799a8b95cdfc%22%3Bs%3A10%3A%22ip_address%22%3Bs%3A9%3A%22127.0.0.1%22%3Bs%3A10%3A%22user_agent%22%3Bs%3A72%3A%22Mozilla%2F5.0+%28Windows+NT+6.1%3B+WOW64%3B+rv%3A32.0%29+Gecko%2F20100101+Firefox%2F32.0%22%3Bs%3A13%3A%22last_activity%22%3Bi%3A1413105699%3Bs%3A9%3A%22user_data%22%3Bs%3A0%3A%22%22%3B%7Ddd721798f7e15d36c1b3ad2c05bcf03b; path=/
X-Powered-By    PHP/5.5.12
access-control-allow-orig...    *

any setting did i miss ? 
thanks for any suggestion

**Comment by infacq** [comment]
Do you have solution for not having `OPTIONS` ?
