### ISSUE TITLE
Change OPTIONS method to POST

### ISSUE THREAD

**Issue by navotera** [danialfarid/ng-file-upload#354]
Im already change the method in the properties with this code : 

<code>
$scope.upload = $upload.upload({
        method: 'POST'
   });
</code>

but the request still OPTIONS ? although in the Request Headers is showed

<code> Access-Control-Request-Method is POST </code>

**Comment by infacq** [comment]
how do we avoid this preflight

**Comment by danialfarid** [comment]
@infacq  that is being sent by the browsers and is needed to know if cors is allowed or not:
https://en.wikipedia.org/wiki/Cross-origin_resource_sharing#Preflight_example
