### ISSUE TITLE
Cancel upload while uploading

### ISSUE THREAD

**Issue by foyzulkarim** [danialfarid/ng-file-upload#36]
Is there any event or function by which I can cancel uploading at the time of upload?
I got 'process' function, but how can I stop the upload?

**Comment by redders6600** [comment]
Is this still a feature? I see a reference to it in the readme, but can't see how to actually cancel it!

**Comment by danialfarid** [comment]
@redders6600  I added it to the reference section of the readme.

**Comment by redders6600** [comment]
Perfect, thanks - pretty obvious actually. :)
