### ISSUE TITLE
Uploading a large file using $upload.upload is returning 413

### ISSUE THREAD

**Issue by amith-cv** [danialfarid/ng-file-upload#366]
Hi Danial,
Our team has a requirement to upload files from the UI and send it to the back end java webservice (in spring) which will eventually store the file as CLOB in oracle database.
We have written the UI in Angular (of course thanks to angular-file-upload code) and we are successfully able to upload a file and things look good end to end.

However when we test with a very large file (per say > 1gig), we are seeing failures and we see error HTTP Error 413 Request entity too large.
Below is the code snippet.
We are under the impression that $upload.upload will slice the files and send it as multi-part. But it looks like the entire file is being sent in one request and hence the Error 413.
For obvious reasons, we can not expect the server to have configurations changed to expect a very big request data. 
Given this scenario, what would be the right approach to successfully upload a large file?

----Code Snippet---
$upload.upload({
                    url: '../../ws/Report/uploadfile,
                    file: $file, //file that has to be uploaded
                    data: modelData,
                    progress: function (e) {
                  console.log("In Progress");
                 }
                }).success(function (data, status, headers, config) {
               console.log("Success");
                }).
                error(function (data, status, headers, config) {
                   console.log("Failure");
                });

**Comment by AnthumChris** [comment]
This issue still exists, and files continue to upload on `413` errors.

`$upload.upload().error()` is not called until the upload completes.  This is problematic if the server returns error `413` for a file that is too large for the server's setting. For example, if the default NGINX file upload size is 1MB and a user tries to upload a 15MB file, the user won't see the error and the file upload completes.

My solution was to add an event handler to intercept the server's any non-200 server responses and abort the upload.

```
var abortedXhr = null;
$upload.upload({
	url: '/api/upload/',
	'file': file
}).xhr(function(xhr){
	xhr.addEventListener("abort", function() {
		console.log('Main XHR request aborted.');
	});

	// xhr.upload.addEventListener("error", function() {});
	// xhr.upload.addEventListener("load", function() {});
	// xhr.upload.addEventListener("loadend", function() {});
	// xhr.upload.addEventListener("loadstart", function() {});
	// xhr.upload.addEventListener("timeout", function() {});
	xhr.upload.addEventListener("abort", function() {
		console.log('Upload XHR request aborted.');
	});
	xhr.upload.addEventListener("progress", function(progressEvent) {
		console.log('upload progress: '+parseInt(100.0 * progressEvent.loaded / progressEvent.total)+'%');
		if (xhr.readyState > 2 && xhr.status !== 0 && xhr.status !== 200) {
			// save the state of the faild request.  (i.e. 413 error codes and server error messages)
			abortedXhr = JSON.parse(JSON.stringify(xhr)); 

			xhr.abort();
		}
	})
}).error(function(e) {
	if(abortedXhr) {
		console.error('An error occurred during upload that prompted an abort');
		console.dir(abortedXhr);
	} else {
		console.error('An Error occurred during upload', e);
	}
}).success(function(e) {
	console.log('Upload successful.')
})
```

**Comment by schmkr** [comment]
I've been having issues with a 413 response as well. Turned out that because I was uploading to another domain and nginx fails fast, the appropriate CORS-headers were not in the response, so the browser could not read the response status code.
Adding the [HttpHeadersMoreModule](http://wiki.nginx.org/HttpHeadersMoreModule) to nginx and then configuring the API to add CORS headers even in case of a 413 resolved the issue and allowed the client to read the failed response properly.

**Comment by danialfarid** [comment]
Cool!
