### ISSUE TITLE
Issues with uploading the same file(s) multiple times

### ISSUE THREAD

**Issue by geoffreak** [danialfarid/ng-file-upload#372]
This is a great plugin and everything is working flawlessly for me except one major pain point. It seems that if the files that get selected match that of the last selection, the callback will not get fired. This is happening in every browser I tested in (all versions of IE from 8-11, latest Chrome, latest Firefox, latest Safari)

Steps to replicate:
1. Add to HTML: (enabling multiple selection will make no difference)
   
   ```
   ng-file-select="upload($files)"
   ```
2. Add to controller:
   
   ```
   $scope.upload = function($files) {
    console.log('upload!');
   }
   ```
3. Select any file(s) via uploader
4. See `upload!` in console
5. Select exact same file(s) via uploader
6. Nothing happens

As long as the selection isn't identical to that of the previous selection, the callback will get fired, but if it matches exactly it will silently fail with no possible way of catching.

Has anyone else run into the same issue? The only workaround I've found other than reloading the page is to re-render the HTML.

**Comment by KD25** [comment]
Hi danialfarid

onclick="this.value=null" is not working with safari. Please let me know your suggestion on this.

Thanks.

**Comment by danialfarid** [comment]
You won't need this anymore. Does the demo page work?

**Comment by rajguru827** [comment]
In windows safari it not working
