### ISSUE TITLE
angular file upload submitting file plus other data model with restangular

### ISSUE THREAD

**Issue by ovione** [danialfarid/ng-file-upload#376]
I would like to use angular-file-upload with Restangular
I have a form with user info and a file upload
I need to post with Restangular the model + the file that I choose to upload.
This should be done with Restangular in one call.
If you shed some light that would be very useful
thanks
Ovidio

**Comment by sagar-ranglani** [comment]
What would be an elegant solution to this one? I am also struggling with the same.

**Comment by danialfarid** [comment]
Ask on Stackoverflow since it is not an issue with this plugin. @sagar-ranglani
