### ISSUE TITLE
Trying to integrate this with my meanjs app

### ISSUE THREAD

**Issue by jfoscue** [danialfarid/ng-file-upload#381]
I'm new to the meanjs stack and was trying to get angular-file-upload integrated but am having problems.  I keep getting "Unknown provider: $uploadProvider <- $upload" when I load the page.  Can you give me any advice or examples of using this with the meanjs stack?

**Comment by hudakdidit** [comment]
Hi, I'm having a very similar issue when integrating into a mean.js app. 

Here the steps I followed to include:

- I've installed via bower: "ng-file-upload": "~2.1.1"
- included 'angular-file-upload-shim.js', and 'angular-file-upload.js' into my html layout.
- Added 'angularFileUpload' as a module dependency
-  `angular.module('articles').controller('ArticlesController', ['$scope', '$upload',
	function($scope, $upload) { ... }]);

There error I receive is: "[$injector:unpr] Unknown provider: falseFilterProvider <- falseFilter".

Did I miss a step, or could there be some conflict in the mean.js module structure?

Thanks for any help!

**Comment by JonathanZWhite** [comment]
This doesn't seem like an issue that you're experiencing due to angular-file-upload. You might want to poke around and see if you have a dependency falseFilter that isn't being injected properly.

**Comment by ChrisMaher** [comment]
Did you get this problem sorted? I have exactly the same issue.

**Comment by georgeportillo** [comment]
Same issue here

**Comment by kurienzach** [comment]
I had the same issue `"[$injector:unpr] Unknown provider: falseFilterProvider <- falseFilter"`. The problem was that I used some snippets in Sublime Text which produced code like this 
```
<div ng-disabled="true|false">
```
Angular is searching for a filter called false which obviously doesn't exist.
