### ISSUE TITLE
image preview in ie9

### ISSUE THREAD

**Issue by devilcoke** [danialfarid/ng-file-upload#384]
Hello,

I've posted this issue at FileAPI issue section but didn't get any luck and thought if you have any idea what's going on with my code.

with ie9, uploading file works just fine, however, I can't get image preview before uploading it.

Any idea or debugging point would be appreciated.  

Thanks!

**Comment by danialfarid** [comment]
Image preview has been added to version 4.2.0.
There is a limit on the file size though, 4M for IE9 and 20K for IE8.
