### ISSUE TITLE
Upload does not work with Android default browser/UC Browser

### ISSUE THREAD

**Issue by Jempan** [danialfarid/ng-file-upload#388]
Thanks for an awesome script, very useful! It´s works flawlessly in Chrome for Android and in Safari on iOS, but in the native Android browser and UC Browser the files have a content-length of 0 when they reach the server :( I have also tried to use the $upload.http and send the file as an ArrayBuffer with no luck. Unfortunately kind of stuck and out of ideas now and any help or guidance would be very appreciated :)

**Comment by carlhopf** [comment]
I was using version 1.6.12 before, and it worked fine with about every android device version 4 and higher. Just upgraded to 3.2.25 and the file upload dialog will no longer open on the same test devices.

If i add ng-capture="'foo'|'bar'" it will throw an exception (cause 'bar' is not a valid angular filter) but atleast show the file selection dialog. So my guess is, that ng-file-select internals for opening the upload dialog do not work some older webkit versions.

I'll dig into the source if i find the time.

Cheers
