### ISSUE TITLE
Two different file upload on the same controller

### ISSUE THREAD

**Issue by JeffGreat** [danialfarid/ng-file-upload#389]
When using the directive twice on a page with two different upload method it doesn't work. for instance the first directive calls uploadPicture($files) and the second one uploadDocument($files).
Actually angular-file-upload only consider the second method for both directive element. This is due to directive scope which is global. 
To avoid this behaviour directive must have the "scope : true" parameter. I'll post a pull request.

**Comment by danialfarid** [comment]
Actually going through the old version prior to 2.x. this behaviour doesn't happen and I can have two different methods for ng-file-select for two elements in the same controller and they call the correct method.
Could you create a jsfiddle with version 1.x to show what you were referring to here.
It seems unnecessary to have an isolated scope for this directive.

**Comment by JeffGreat** [comment]
Ok, i'll try to check that asap
