### ISSUE TITLE
support Required attribute?

### ISSUE THREAD

**Issue by devmark** [danialfarid/ng-file-upload#422]
this package support Required attribute?

http://stackoverflow.com/questions/16207202/required-attribute-not-working-with-file-input-in-angular-js

**Comment by piotrkulpinski** [comment]
Could you tell me how to pass the required attribute to generated file input when you're using it on "div" element like that:
```html
<div ng-file-select ng-model="myFiles" required>(...)</div>
```
It looks like the required attr is not passed to generated input.

**Comment by danialfarid** [comment]
`ng-required` read the docs.

**Comment by piotrkulpinski** [comment]
I did and didn't saw anything helpful. Do you have any example of using that with div ng-file-input?

**Comment by danialfarid** [comment]
Demo page has the example.

**Comment by antonioreyna** [comment]
I? cant find the example either

**Comment by danialfarid** [comment]
The first form in the demo page has required. https://angular-file-upload.appspot.com/

**Comment by antonioreyna** [comment]
and could it have that same required attribute in the drop zone?

**Comment by danialfarid** [comment]
yes

**Comment by antonioreyna** [comment]
I tried and it is not working <div ng-file-drop ng-file-select ng-model="image" class="drop-box" drag-over-class="{accept:'dragover', reject:'dragover-error', delay:100}" ng-multiple="false" allow-dir="false" ng-accept="'image/*'" ng-file-change="fileDropped($files, $event, $rejectedFiles)" required>Drop your image</div>

**Comment by danialfarid** [comment]
```
       	<div required="" name="drop" ngf-drop="" ngf-select="" ng-model="files">
            Drop files	
         </div>
	<i ng-show="myForm.drop.$error.required">*required</i>
```

if you still cannot figure it out create a jsfiddle.

**Comment by bmsdave** [comment]
@danialfarid, Hi!

wath this example http://jsfiddle.net/bmsdave/3v8e4h7u/2/ 

if I select some files, and clear all -> picFile = [] , and require dont work.

sorry, for my english =\

**Comment by bmsdave** [comment]
@danialfarid, 

this error exist if set: multiple="true" of ngf-multiple="true"

**Comment by danialfarid** [comment]
set picFile = null

**Comment by bmsdave** [comment]
@danialfarid, where I must set picFile = null?
If i set in controller MyCtrl ( see example in jsfiddle ), picFile rewrite on [] again if i dont choised any files.

**Comment by danialfarid** [comment]
If you set `picFile = null` it would clear the errors.

**Comment by bmsdave** [comment]
@danialfarid, i set `$scope.picFile = null ` in controller.
It is dont work: http://jsfiddle.net/3v8e4h7u/3/
<img width="312" alt="err" src="https://cloud.githubusercontent.com/assets/3020607/22102565/eeb8af76-de48-11e6-921a-0cab134004f5.png">

**Comment by danialfarid** [comment]
What doesn't work? Provide steps to reproduce and expected/actual result.

**Comment by bmsdave** [comment]
@danialfarid, http://jsfiddle.net/3v8e4h7u/3/
steps:
1. choise some files
2. clear input (click on input and click cancel button)
3. see the screenshot in comment on 19 Jan. picFile will be equal array, and require won't work.

pull request #1833 fix it
