### ISSUE TITLE
Corrupt files when using direct upload to amazon s3?

### ISSUE THREAD

**Issue by ghost** [danialfarid/ng-file-upload#428]
I can't get amazon s3 upload to work correctly with html5 file uploads. Every file get corrupted with WebKitFormBoundary file header info. When I try and upload a simple txt-file:

```
simple file upload test
```

The file content on s3 is changed to this:

```
------WebKitFormBoundaryodjYRgYPytUgeq1Z
Content-Disposition: form-data; name="file"; filename="test.txt"
Content-Type: text/plain

simple file upload test
------WebKitFormBoundaryodjYRgYPytUgeq1Z--
```

I'm using the example from the readme but I get the url params/data from my backend:

``` javascript
$upload.upload({
    url: signedData.signedRequest,
    method: 'PUT',
    file: file
})
```

In the backend I'm using aws-sdk to generate a signedRequest 

``` javascript
var signedData = {
    Bucket: s3Bucket,
    Key: req.body.fileName,
    ContentType = req.body.contentType,
    Expires: 60,
    ACL: 'private'
};
var s3 = new aws.S3();
s3.getSignedUrl('putObject', signedData, function(error, data) {
    res.send({ signedRequest: data });
});
```

I have tried using $upload.http with the FileReader api as well but without success, how do I upload files correctly directly to amazon s3?

**Comment by billyshena** [comment]
I have the exact same issue. When I upload any file directly from client (html5/js) to Amazon S3, the file is corrupted and when I open it (for example a .jpg), I can see that 'Content-Type' and 'Content-Disposition' plain text inside the file data.

I've checked the request on the DEMO and the one I'm doing and cannot see anything different.
Could you please detail how did you solve this issue?

Best,

**Comment by wiggin** [comment]
For me I changed from using a signed url (like in my first example) to structure the request like the demo fixed the problem. Here is what I'm currently using (signedData is coming from my server request to give me all proper endpoints and the signature).

```
$upload.upload({
	url: signedData.url,
	data: {
		key: projectFolder +'/'+ file.name,
		acl: signedData.acl,
		'Content-Type': file.type || 'application/octet-stream',
		'success_action_status': 201,
		AWSAccessKeyId: signedData.AWSAccessKeyId,
		Policy: signedData.s3Policy,
		Signature: signedData.s3Signature
	},
	skipAuthorization: true,
	method: 'POST',
	file: file
}
```

**Comment by billyshena** [comment]
Well I am using the AWS V4 signature (my bucket is located in Frankfurt).
Are you sure u have to use method: 'POST' ? Because I'm using PUT instead, don't know if it can cause the issue.

**Comment by davehigginson** [comment]
Also having the same issue.

I think that a) pre-signed URLs do not support the 'POST' method and b) the 'PUT' method at S3's end doesn't understand multipart/form-data. If these statements are both true then doesn't seem possible to upload from a form to S3 using pre-signed URLs, which seems both inconvenient and odd.

I'm going to try the alternative method described here: https://aws.amazon.com/articles/1434

I'm using DropzoneJS which allows you to add hidden inputs to your form, so my plan is to add the fields as described in that blog article and follow the rest of the instructions about generating and signing a policy. All of this will be implemented on the server side, of course. I'm using Rails so the Ruby examples in the blog should come in useful.

**Comment by billyshena** [comment]
Did you manage to do the upload? Btw, are you also using AWS V4 signature?

**Comment by davehigginson** [comment]
Just started coding it! Gimme 15 minutes or so.

**Comment by davehigginson** [comment]
Ok, I got it working, finally.

My Rails model code looks like this:

    def post_url
      S3.bucket( "MY_BUCKET_NAME" ).url
    end
    
    def policy
      policy = {
        "expiration": ( DateTime.now + 7.days ).to_time.utc.iso8601,
        "conditions": [ 
          {"bucket": "MY_BUCKET_NAME"}, 
          ["starts-with", "$key", "uploads/"],
          {"acl": "private"},
          ["content-length-range", 0, 1048576],
        ]
      }
    
      Base64.encode64(policy.to_json).gsub("\n","")
    end
  
    def signature
      Base64.encode64( OpenSSL::HMAC.digest( OpenSSL::Digest.new('sha1'), Rails.application.secrets.aws_secret_access_key, policy ) ).gsub("\n","")
    end

and my view looks like this:

	<form action="<%= @image.post_url %>" class="dropzone" id="my-image-dropzone" enctype="multipart/form-data">
		<input type="hidden" name="key" value="<%= @image.filename %>">
		<input type="hidden" name="AWSAccessKeyId" value="<%= Rails.application.secrets.aws_access_key %>"> 
		<input type="hidden" name="acl" value="private"> 
		<input type="hidden" name="policy" value="<%= @image.policy %>">
		<input type="hidden" name="signature" value="<%= @image.signature %>">
		<i class="fa fa-user"></i>
	</form>

You may not be using Rails but hopefully there's enough information here for you to figure out how to do it.

**Comment by billyshena** [comment]
Are you using the AWS V4 signature or another version?

**Comment by davehigginson** [comment]
No, I don't think so. I remember seeing that Frankfurt only supports V4. My bucket is in Ireland. It doesn't look too difficult to achieve, though. I'll see whether I can change my code to V4 style.

**Comment by billyshena** [comment]
I'm going to try to use Dropzone + V4 style, I'll upload some code also if it works...
Thanks for your support dave !

**Comment by davehigginson** [comment]
No problem. I'd be much further behind if I hadn't found the clues in this thread. :-)

Here's the same code for V4. I got it working by following this example:

http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-post-example.html

which seems mostly correct except that the signature field is called "Signature", not "X-Amz-Signature".

	<% today = DateTime.now %>
	<form action="<%= @image.post_url %>" class="dropzone" id="profile-pic-dropzone" enctype="multipart/form-data">
		<input type="hidden" name="key" value="<%= @image.filename %>">
		<input type="hidden" name="AWSAccessKeyId" value="<%= Rails.application.secrets.aws_access_key %>">
		<input type="hidden" name="acl" value="private">
		<input type="hidden" name="policy" value="<%= policy = @image.policy( today ) %>">
		<input type="hidden" name="X-Amz-Algorithm" value="<%= @image.amz_algorithm %>">
		<input type="hidden" name="X-Amz-Credential" value="<%= @image.amz_credential( today ) %>">
		<input type="hidden" name="X-Amz-Date" value="<%= @image.amz_date( today ) %>">
		<input type="hidden" name="Signature" value="<%= @image.amz_signature( policy ) %>">
	</form>

Model code:

    def post_url
      S3.bucket("MY_BUCKET_NAME").url
    end
    
    def policy(today)
      policy = {
        "expiration": ( today + 7.days ).to_time.utc.iso8601,
        "conditions": [ 
          { "bucket": "MY_BUCKET_NAME" },
          [ "starts-with", "$key", "uploads/" ],
          { "acl": "private" },
          [ "content-length-range", 0, 1048576 ],
          { "x-amz-credential": amz_credential(today) },
          { "x-amz-algorithm": amz_algorithm },
          { "x-amz-date": amz_date(today) },
        ],
      }
    
      Base64.encode64(policy.to_json).gsub("\n","")
    end
    
    def amz_algorithm
      "AWS4-HMAX-SHA256"
    end
    
    def amz_credential(today)
      parts =[ 
        Rails.application.secrets.aws_access_key, 
        today.strftime("%Y%m%d"),
        Rails.application.secrets.aws_region,
        "s3",
        "aws4_request",
      ]
      
      parts.join( "/" )
    end
    
    def amz_date(today)
      today.to_time.utc.iso8601
    end
    
    def amz_signature(the_policy)
      Base64.encode64( OpenSSL::HMAC.digest( OpenSSL::Digest.new('sha1'), Rails.application.secrets.aws_secret_access_key, the_policy ) ).gsub("\n","")
    end

**Comment by billyshena** [comment]
I see that your form is generate dynamically through your Rails app. However, my structure has an Angular JS app (client) and a Node.js server (to send back the pre-signedUrl before the upload to S3 from my Angular app).

I don't know how exactly you can do that "manually" with dropzone, to set the different parameters needed (signature,policy,etc.)

**Comment by davehigginson** [comment]
What is generating your form HTML? The code has to go in there. If that's being done on the client side, then you'll need to transmit all the fields to the client somehow so that it can construct the form. The signature method needs your secret key, so it has to happen on the server.
