### ISSUE TITLE
file upload in IE8 and IE9 with angular-flie-upload using triger 

### ISSUE THREAD

**Issue by msnpr567** [danialfarid/ng-file-upload#439]
I got successfull file upload in IE8 and IE9 with angular-flie-upload. but iam using triger to click on browse input with the help of anchor tag. At that time im getting "Access denied " error in console. Im searching for solution through a day but i didnt get. can u help me once.

**Comment by SIDROCK** [comment]
i have file upload problem in ie8 or ie9 i m getting this error and here is my code which i write for file ..


            Upload.upload({


                url: $scope.webappUrl + "/transaction-log/" + id + "/document/" + documentType,
                file: uploadFile,
                method: 'POST'

            }).progress(function (evt) {

                var progressPercentage = parseInt(100.00 * evt.loaded / evt.total);
                if (progressPercentage == 100) {
                    self.fileUploadedStatus[documentType]= true;
                }
                $log.debug('progress: ' + progressPercentage + '% ' + evt.config.file.name);

            }).success(function (data, status, headers, config) {
                $log.debug('file: ' + config.file.name + ' upload. Response: ');
                // search through the transaction list for the one we just attached an image to.
                ////
                for(var i = 0; i < $scope.transactionList.length; i++) {

                    if($scope.transactionList[i].id == data.id) {

                        // replace the current transaction with the updated details
                        //
                        self.regradeTransaction = data;
                        $scope.transactionList[i] = data;

                        break;
                    }
                }
                self.fileUploadedStatus[documentType] = true;
            }).error(function (data, status, headers, config) {
                $log.debug('error status: ' + config.file.name + ' upload. Response: ' + data);

            })
        }


here is screen shot for the error which i getting : 

![image](https://cloud.githubusercontent.com/assets/16042087/11435114/8017f07c-94fc-11e5-8516-2db7fff3d788.png)
