### ISSUE TITLE
Error: Unknown provider: $uploadProvider <- $upload     at Error (<anonymous>)

### ISSUE THREAD

**Issue by theninthnode** [danialfarid/ng-file-upload#45]
I'm trying to inject this module into a controller but when the controller is initialised I get the following error:

```
Error: Unknown provider: $uploadProvider <- $upload at Error (<anonymous>)
```

I've included the module (after angular.js).

```
<script src="/app/components/angularjs-file-upload/angular-file-upload.js"></script>
```

And injected it into my app:

```
angular.module('App',  ['ngResource', 'ngSanitize', 'ui.state', 'ui.compat', 'ngCookies', 'ui.bootstrap', 'angularFileUpload'])
```

And then in my controller:

```
angular.module('App').controller('FeaturedImageCtrl', ['$scope', '$rootScope', '$state', '$stateParams', 'dialog', '$upload', 'img_src', 'entity_id', 'entity', 'media', function ($scope, $rootScope, $state, $stateParams, dialog, $upload, img_src, entity_id, entity, media) {
```

However it seems to be the controller which throws the error.

Have I forgotten to do something?

**Comment by azue** [comment]
I had the same problem after upgrading to version 4.x , caused by the different name of the service 'Upload' (prev. named $upload) 
https://github.com/danialfarid/ng-file-upload/releases/tag/4.0.0

**Comment by mattharrison** [comment]
I had the same problem. Was calling:
 
    MyCtrl.$inject = ['ngFileUpload'];

Needed to call

    MyCtrl.$inject = ['Upload'];

**Comment by oliveheide** [comment]
I'm going through the same problem. I'm using Typescript + Angular.

Error: [$injector:unpr] Unknown provider: $uploadProvider <- $upload <- RemessaBancariaCtrl
http://errors.angularjs.org/1.4.7/$injector/unpr?p0=%24uploadProvider%20%3C-%20%24upload%20%3C-%20RemessaBancariaCtrl

<script src="/.build/vendors/jquery.js"></script>
    <script src="/.build/vendors/angular.js"></script>
    <script src="/.build/vendors/angular-route.js"></script>
    <script src="/.build/vendors/ng-file-upload-shim.js"></script>
    <script src="/.build/vendors/ng-file-upload.js"></script>
    <script src="/.build/vendors/bootstrap.js"></script>
    <script src="/.build/vendors/angular-animate.js"></script>
    <script src="/.build/vendors/loading-bar.js"></script>

app.ts: 
var mainApp = angular.module('arrecadacaoWebApp', ['ngFileUpload', 'ngRoute', 'angular-loading-bar', 'ngAnimate'])

My Controller:
     
        static $inject = ['$http', '$location', '$scope', '$upload', '$timeout'];

        constructor(private $http: ng.IHttpService,
                    private $location: ng.ILocationService,
                    private $scope: ng.IScope,
                    private $upload: ng.angularFileUpload.IUploadService,
                    private $timeout: ng.ITimeoutService
        )
        {
            /*.......*/
        }
        
AngularJS v1.4.7
ng-file-upload @version 9.1.1

Help me please, do two days I'm with this problem without soluçõa. I thank you.

**Comment by danialfarid** [comment]
@oliveheide it is `Upload' not '$upload'.

**Comment by oliveheide** [comment]
Thanks ... It worked... I'm from Brazil, it is difficult to write post in English... But I think now it will... Thanks @danialfarid

**Comment by gowthamrodda** [comment]
Thanks a lot, this saved my time.
