### ISSUE TITLE
node.js working example

### ISSUE THREAD

**Issue by bhanu2507** [danialfarid/ng-file-upload#478]
Hi,

Whatever I do, I can't get this work on mean.io stack. Node.js example doesn't give a lot of information. I am new to MEAN. Can you give me a working code for Node.js, preferable on MEAN stack?

Thanks

**Comment by JonathanZWhite** [comment]
I'm using Node as a BE as well. I'll add my code when I get it working.

**Comment by JonathanZWhite** [comment]
Okay I have a working example. I used the form parsing middleware [node-multiparty](https://github.com/andrewrk/node-multiparty). This enables you to access and interpret `req.files` (same one used in the documentation). 

app.js
```
// Requires multiparty 
multiparty = require('connect-multiparty'),
multipartyMiddleware = multiparty(),

// Example endpoint 
router.post('/api/user/image', multipartyMiddleware, UserController.uploadCoverImage);
```

UserController.js
```
UserController = function() {};

UserController.prototype.uploadCoverImage = function(req, res) {
    var file = req.files.file;
    console.log(file.name);
    console.log(file.type);
}
```

**Comment by danialfarid** [comment]
@JonathanZWhite Feel free to create another [wiki](https://github.com/danialfarid/angular-file-upload/wiki) page and I will link it to the readme file.

**Comment by JonathanZWhite** [comment]
@danialfarid I added another [wiki](https://github.com/danialfarid/angular-file-upload/wiki/Node-example) page. Cheers

**Comment by woniesong92** [comment]
@danialfarid Would you be interested in a wiki page about uploading a file with NodeJS + Angular to S3?

**Comment by danialfarid** [comment]
@woniesong92 sure
