### ISSUE TITLE
ionic working example

### ISSUE THREAD

**Issue by pcocko** [danialfarid/ng-file-upload#480]
I would like to have an example running angular-file-upload with an ionic app.

At the moment i can't upload files in my nodeJs backend. I'm receiving the body JSON data:

body: 
   { dir: '/img/',
     file: 'file:///storage/sdcard0/DCIM/Camera/IMG_20141226_122050.jpg' }

But, files are totally empty:

 files: {}

I could add my angular code for more information.

Thanks

**Comment by danialfarid** [comment]
Add your html and js code.

**Comment by danialfarid** [comment]
or better create a jsfiddle

**Comment by JonathanZWhite** [comment]
Are you using the correct middleware? I encountered the same issue until I used the [connect-multiparty] (https://github.com/andrewrk/node-multiparty) middleware. I detailed my solution in issue #478.

**Comment by pcocko** [comment]
Jonathan, I'm using same middleware. I think the problem is in client-side.

Now, I got this working using cordova file-transfer but i would like to replicate this issue in plunker/jsfiddle to figure out why is not working. I'll try to create a plunker asap.

I have other projects running with angular-file-upload but no ionic apps.

Thanks!

**Comment by sergiomilici** [comment]
Hi, i have a similar problem. Using this module on the web works fine. Now, i add the ionic library and it stops working also on the web. Just nothing happens.

Any idea?

**Comment by sandeepkacha** [comment]
Hi, i also have similar problem working on ionic app. I am trying to upload an array of images along with formData from phone memory (file url locations) instead of having a form upload button. Is there anyway i can do that using angular-file-upload? 

Thanks!

**Comment by etopian** [comment]
This module will not work with Cordova. You must use: https://github.com/apache/cordova-plugin-file-transfer

**Comment by sandeepkacha** [comment]
yea, i figured it out , anyhow thanks for reply.

**Comment by anaganisk** [comment]
@sandeepkacha posting the solution would help other with the same problem, since you say you figured it out.

**Comment by fendorio** [comment]
Strange... I use ng-file-upload for both video and image uploads to a nodejs backend on a cordova app i've made. Check out 'memorybubbles' on the app store. All file uploading is done via ng-file-upload. 

What brought me here is that it seems to fail for the Android version of the App i'm making.

**Comment by fendorio** [comment]
Just to follow up on my comment from yesterday - using crosswalk solved this issue for me.

**Comment by siddmegadeth** [comment]
cordova filetranafwr is no lonfer supported with 9.xx .
Its means we canot use cordova file-transfer.
any help would be appreciated here

**Comment by mateusleon** [comment]
It's no longer supported because of XHR2. Checkout this blog entry from 2017:

https://cordova.apache.org/blog/2017/10/18/from-filetransfer-to-xhr2.html
