### ISSUE TITLE
I want to upload files upto 1 GB but it crashes. I am able to upload file upto 10 MB. 

### ISSUE THREAD

**Issue by ankurshah32** [danialfarid/ng-file-upload#489]
I want to upload files upto 1 GB but it crashes. I am able to upload file upto 10 MB. 
Can you please let me know how can i increase uploading file size?

**Comment by raffsangiani** [comment]
I believe the issue is your webserver. Check configuration. If you are using nginx look for client_max_body_size in nginx.conf.

**Comment by ankurshah32** [comment]
i am using node JS 

Node JS Server Side Code to uplaod file on Azure blob.
var multiparty = require('multiparty');
var blobService = client.blobService();
var form = new multiparty.Form();
      form.on('field', function(name, value){
      });
      form.on('part', function(part) {

        if (!part.filename) {callback(null, "Not a valid file.");}
        var size = part.byteCount - part.byteOffset;
        var name = part.filename;
        var container = 'name of container ';
        blobService.createBlockBlobFromStream(container, rowKey, part, size, function(error) {
          if (error) {
            console.log('Not able to upload file.');
            callback(null, "error in uploading.");
          }
        });
 form.parse(req);

Client Side Code :+1: 

<div ng-controller="UploadCtrl">
          <button input type="file"
              ng-file-select ng-model="myFiles" 
              ng-file-change="fileSelected($files, $event)" 
              ng-multiple="true" 
              ng-capture="'camera'"
              accept=" " 
              resetOnClick="true" >Upload</button>
</div>
Controller Class
app.controller('UploadCtrl', [ '$scope', '$upload', 'gmTexts', function($scope, $upload) {
  $scope.$watch('myFiles', function() {
    $scope.uploadedPercent = [];
    for (var i = 0; i < $scope.myFiles.length; i++) {
      var file = $scope.myFiles[i];
      $scope.upload = $upload.upload({
        url: '/uploadstream',
        method: 'POST',
        contentType: 'application/octet-stream',
        data: {myObj: $scope.myModelObj},
        file: file,
        formDataAppender: function(formData, key, val){
        } 
     });
      $scope.upload.progress(function(evt) {
        console.log('progress: '+parseInt(100.0 * evt.loaded / evt.total) + '%');
      });
      $scope.upload.success(function(data, status, headers, config) {
        console.log('file ' + config.file.name + 'is uploaded successfully. Response: ' + data);
      });
      $scope.upload.error(function (err) {
        alert('Error occured during upload');
      })
   }
  });
}]);

**Comment by ankurshah32** [comment]
Node JS Server Side Code to uplaod file on Azure blob.
   var multiparty = require('multiparty');
   var blobService = client.blobService();
   var form = new multiparty.Form();
     form.on('field', function(name, value){
     });
     form.on('part', function(part) {
       if (!part.filename) {alert("Not a valid file.");}
       var size = part.byteCount - part.byteOffset;
       var name = part.filename;
       var container = 'name of container ';
       blobService.createBlockBlobFromStream(container, rowKey, part, size, function(error) {
         if (error) {
           console.log('Not able to upload file.');
         }
     });
    form.parse(req);

Client Side Code 

<div ng-controller="UploadCtrl">
          <button input type="file"
              ng-file-select ng-model="myFiles" 
              ng-file-change="fileSelected($files, $event)" 
              ng-multiple="true" 
              ng-capture="'camera'"
              accept=" " 
              resetOnClick="true" >Upload</button>
</div>

Controller Class
app.controller('UploadCtrl', [ '$scope', '$upload', 'gmTexts', function($scope, $upload) {
  $scope.$watch('myFiles', function() {
    $scope.uploadedPercent = [];
    for (var i = 0; i < $scope.myFiles.length; i++) {
      var file = $scope.myFiles[i];
      $scope.upload = $upload.upload({
        url: '/uploadstream',
        method: 'POST',
        contentType: 'application/octet-stream',
        data: {myObj: $scope.myModelObj},
        file: file,
        formDataAppender: function(formData, key, val){
        } 
     });
      $scope.upload.progress(function(evt) {
        console.log('progress: '+parseInt(100.0 * evt.loaded / evt.total) + '%');
      });
      $scope.upload.success(function(data, status, headers, config) {
        console.log('file ' + config.file.name + 'is uploaded successfully. Response: ' + data);
      });
      $scope.upload.error(function (err) {
        alert('Error occured during upload');
      })
   }
  });
}]);
