### ISSUE TITLE
Do you support Blob responses?

### ISSUE THREAD

**Issue by paulcwarren** [danialfarid/ng-file-upload#497]
Is it possible to handle binary responses?  I have code like this:-

```
	var fileReader = new FileReader();
	fileReader.onload = function(e) {
	    $timeout(function() {
		file.upload = $upload.http({
			url: '/image-flip',
			method: 'POST',
			headers : {
		                'Accept': 'image/jpeg',
				'Content-Type': file.type
			},
			data: e.target.result
		});
		
		file.upload.then(function(response) {
			file.result = response.data;
						
			var responseReader = new FileReader();
 		        responseReader.onload = function(evt) {
			    	  var dataURL = responseReader.result;
			          var output = document.getElementById('result');
			          output.src = dataURL;  
			};
			responseReader.readAsDataURL(file.result);
		}, function(response) {
		        if (response.status > 0)
				$scope.errorMsg = response.status + ': ' + response.data;
			});
						
	        file.upload.progress(function(evt) {
			file.progress = Math.min(100, parseInt(100.0 * evt.loaded / evt.total));
		});
	    }, 5000);
        }
        fileReader.readAsArrayBuffer(file);
```
but it fails with the following exception:-

TypeError: Failed to execute 'readAsDataURL' on 'FileReader': parameter 1 is not of type 'Blob'.
    at TypeError (native)
    at $scope.flip.fileReader.onload.file.upload.then.$scope.errorMsg (http://localhost:8080/index.html:119:29)
    at processQueue (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:13137:27)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:13153:27
    at Scope.$get.Scope.$eval (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:14353:28)
    at Scope.$get.Scope.$digest (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:14169:31)
    at Scope.$get.Scope.$apply (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:14457:24)
    at done (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:9614:47)
    at completeRequest (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:9804:7)
    at XMLHttpRequest.requestLoaded (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:9745:9)

Is there a way to do this as-is?  Or is this a feature request?

Many thanks
_Paul

**Comment by danialfarid** [comment]
readAsDataURL needs a js Blob object, what you are returning from the server is not a js Blob.
If you wanna get the dataUrl of the file you gotta pass in the `file` object from the client side to it not the server response. What are you trying to achieve here?

**Comment by paulcwarren** [comment]
My server accepts a binary image/jpeg and responds with a transformed binary image/jpeg.

If I use the following XMLHttpRequest-based code:-

```
	var file = $scope.file;
	var fileReader = new FileReader();
	fileReader.onload = function(e) {
		var data = e.target.result;
		var ajax = new XMLHttpRequest();
		ajax.open("POST", "/transformations/image-flip", true);
		ajax.setRequestHeader('Accept', 'image/jpeg');
		ajax.setRequestHeader('Content-Type', $scope.file.type);
		ajax.responseType = "blob";
		ajax.onload = function (e) {
			  if (ajax.readyState === 4) {
			    if (ajax.status === 201) {
			      var blob = ajax.response;
			      var responseReader = new FileReader();
			      responseReader.onload = function(evt) {
			    	  var dataURL = responseReader.result;
			          var output = document.getElementById('result');
			          output.src = dataURL;  
			      };
			      responseReader.readAsDataURL(blob);
			    } else {
			      console.error(ajax.statusText);
			    }
			  }
			};
			ajax.onerror = function (e) {
			  console.error(ajax.statusText);
			};
			ajax.send(data);
		}
```
i.e. I tell the ajax request to handle the response as a Blob which then allows me to hand it straight to a FileReader and get a data URL that I can set on a img.src attribute.

I can use this code but I would like to stick with angular-file-upload.

**Comment by danialfarid** [comment]
Why don't you send back the dataUrl string from your server back? Or better send the url to the uploaded image. I don't think your code would work, in order to create a blob object on the client side you should have new Blob() in your code.

If you just wanna show a preview of the image being uploaded you can follow the demo code and you don't need to create it from the server response.
