### ISSUE TITLE
Not working in bootstrap modal!

### ISSUE THREAD

**Issue by shreejibawa** [danialfarid/ng-file-upload#511]
It doesn't work in ui.bootstrap modal. Can you please tell me what am I doing wrong? 

Here is code :

In directive 

     <input type="file" class="form-control" ng-file-select ng-multiple="true" ng-file-change="upload($files, $event)">

In JavaScript

    $scope.upload = function (files,event) {
			clog(files.length);
		};

**Comment by danialfarid** [comment]
Can you create a jsfiddle?

**Comment by fdelbos** [comment]
I have the same issue, put your upload in a directive and it should work

**Comment by danialfarid** [comment]
I would reopen if you could create a jsfiddle showing the error.

**Comment by Oceanswave** [comment]
Having this same issue. When the directive is within a modal or within a loaded template, things go south.

**Comment by Oceanswave** [comment]
https://jsfiddle.net/nmdcwf3w/506/

**Comment by danialfarid** [comment]
@Oceanswave see https://github.com/danialfarid/ng-file-upload/issues/552

**Comment by Oceanswave** [comment]
Awesome, thanks

**Comment by pptp** [comment]
@shreejibawa just wrap the variable file in object
`<input type="file" class="form-control" ng-file-select ng-multiple="true" ng-file-change="upload($files, $event)">`
to
`<input type="model.file" class="form-control" ng-file-select ng-multiple="true" ng-file-change="upload($files, $event)">`
it helps me

**Comment by shreejibawa** [comment]
thank you.

**Comment by dileepbalineni** [comment]
** Issue:** while uploading the image defaultly loading img tag
and where ever we are trying to upload multiple times  image not clearing
step1 : 
![image](https://user-images.githubusercontent.com/22293644/56279775-60ab4780-6126-11e9-9cf6-12f965172727.png)
Step 2 : 
![image](https://user-images.githubusercontent.com/22293644/56279970-d7484500-6126-11e9-9ad4-4b8a5a61af13.png)
 step3 : 
![image](https://user-images.githubusercontent.com/22293644/56280051-0959a700-6127-11e9-9c25-e2e727589552.png)

Here I am sharing the My code
**Html Code:**

<div class="col-sm-3">
    <input type="file"  ng-click="clear()" 
      onchange="angular.element(this).scope().upload(event)" accept="image/png, image/jpeg,image/jpg" style="display: block;"  />
  </div>
  <div class="col-sm-3">
    <button class="btn btn-primary btn-md" ng-click="click()">Upload</button>
  </div>
**javaScript code:**

$scope.setImage = function (ix) {
        $scope.display = $scope.images[ix];
    }
    $scope.clearAll = function () {
        $scope.display = '';
        $scope.images = [];
    }
     $scope.afterClick = false;
        $scope.loadingImages = false;
    $scope.upload = function (obj) {
       $scope.afterClick = false;
          $scope.loadingImages = false;
        var elem = obj.target || obj.srcElement;
            $scope.file = elem.files[0];
            var reader = new FileReader();

            $scope.fileName =   $scope.file.name;           
           
            reader.readAsDataURL( $scope.file);
           } 
                  $scope.afterClick = false;
                  $scope.loadingImages = false;
               $scope.errors = true;
                                
                  $scope.click = function() {
                $scope.loadingImages = false;
                Upload.upload(
                        {
                          method : 'POST',
                          url : 'http://localhost:8080/image/getDeepLearningPredections',
                          file : $scope.file,
                          data : {
                            fileName : $scope.fileName,
                          }
                        })
                    .then(
                        function(response) {
                          try {
                            if (response.data["Status"] != "Ok") {
                              $scope.errors = false;
                              $scope.errorMessasge = response.data["Status"];
                              Notification
                                  .error(response.data["Status"]);
                              $scope.loadingImages = true;
                            } else {
                              $scope.loadingImages = true;
                              var outputData = JSON
                                  .stringify(response.data);
                              $scope.attributes = JSON
                                  .parse(outputData).Attributes;
                             
                         
                               
                                $scope.loadingImages = true;
// }

                            }

                          } catch (e) {
                            console.log(e);// you
                          }

                        })
