### ISSUE TITLE
multipart/mixed

### ISSUE THREAD

**Issue by jmacpomment** [danialfarid/ng-file-upload#517]
I am working on a project where I have to upload a small bit of JSON with a file, working in AngularJS.

I've written code using angular-file-upload, and it is working, except, it always sends "multipart/form-data, boundary=&lt;whatever&gt;"

However, I MUST use multipart/mixed.  This is a requirement for the backend service I am calling.

This is my call:

    $scope.upload = $upload.upload({
      url: <my url>,
      method: 'POST',
      data: $scope.data,
      file: file,
    }).progress(function(evt) {
      console.log('percent: ' + parseInt(100.0 * evt.loaded / evt.total));
    }).success(function(data, status, headers, config) {
      // file is uploaded successfully
      console.log(data);
    });

Is there a way to modify the headers just before it gets sent?

Of course, I can add

    headers: {'Content-Type': 'multipart/mixed'}

but then the boundary is unavailable.  Is there a way to pull the boundary out and have it appear where it should in the Content-Type?

**Comment by danialfarid** [comment]
The boundary is calculated by the browser. You can try to add a transformRequest and see if the headerGetter will have the boundary value for content-type and use that to reconstruct the header.
