### ISSUE TITLE
Would it make sense for angular-file-upload to compute and include the Content-Range header?

### ISSUE THREAD

**Issue by erichiggins** [danialfarid/ng-file-upload#522]
I've been using angular-file-upload to allow users to upload files directly to Google Cloud Storage using [Resumable Uploads](https://cloud.google.com/storage/docs/concepts-techniques#resumable). The process looks something like this:

1. User drops a file into UI.
2. JS sends the file metadata is sent to server, which initiates a resumable upload to GCS.
3. GCS returns a tokenized URL for resuming the upload.
4. The server sends the tokenized URL back to JS.
5. angular-file-upload is configured to use the tokenized URL to upload the file contents to GCS.

To make this process work correctly, the `Content-Range` header is expected in the request headers when resuming the upload. This can be particularly tricky to calculate, since it also includes the length of the query parameters.

Since angular-file-upload already calculates `Content-Length` (and prevents developers from defining it), would it make sense for `Content-Range` to be calculated as well? Perhaps optionally?

**Comment by danialfarid** [comment]
Content-Length is calculated by the browser. there is a feature request to support resumable upload and uploading in chunks but it would take a while to implement. If you are willing to contribute to implement this let me know.

**Comment by do-n-khanh** [comment]
@erichiggins  I am very interested in how to use angular-file-upload to allow users to upload files directly to Google Cloud Storage. Do user need to user google account to login in beofre uploading file?

**Comment by erichiggins** [comment]
@do-n-khanh You can utilize [Signed URLs](https://cloud.google.com/storage/docs/access-control#Signed-URLs) to allow users without Google accounts to upload into a GCS bucket.

**Comment by do-n-khanh** [comment]
@erichiggins Thanks. I tried it but I could not get the final results.

I followed your link and get the signed url as below

C:\khanh>gsutil signurl -m PUT -d 1000d -c image/* grapshipper.p12 gs://passportphoto/
Keystore password:
URL     HTTP Method     Expiration      Signed URL
gs://passportphoto/     PUT     2018-06-11 16:50:30     https://storage.googleapis.com/passportphoto?GoogleAccessId=284514258194-85voonrjcuf7adofg70lqfnf6ee2f5fm@de........His49%2F0kQkdHF7DWLQ%3D%3D

Then I put the signed url into the js file as below:

$scope.uploadFiles = function(file) {
      $scope.f = file;
      if (file && !file.$error) {
        file.upload = Upload.upload({
          url: ' https://storage.googleapis.com/passportphoto?GoogleAccessId=284514258194-85voonrjcuf7adofg70lqfnf6ee2f5fm@de........His49%2F0kQkdHF7DWLQ%3D%3D',
          file: file,
          method: 'PUT'
        });

I tested, I did not get any error in chrome console. But I did see any files in the bucket. 
Do I miss something here?

**Comment by erichiggins** [comment]
@do-n-khanh This isn't something I can help you with and it's off-topic for the `ng-file-upload` project. You might try asking your question over on one of [the various community support channels](https://cloud.google.com/support/#community) that Google has set up.
