### ISSUE TITLE
Sample code not getting progress / Using Controller As

### ISSUE THREAD

**Issue by clabough** [danialfarid/ng-file-upload#526]
I'm using 2.2.2 with AngularJS 1.3.11 and the latest Chrome, I noticed that the file objects are not getting a .progress or .upload property.

To display the progress, I'm having to do this:

		$scope.$watch('files', function () {
			if ($scope.files == null) return;
			$scope.upload = $upload.upload({
				url: 'api/upload',
				data: { ID: 1 },
				file: $scope.files
			}).progress(function (evt) {
				var currentFile = evt.config.file[0];
				currentFile.progress = parseInt(100.0 * evt.loaded / evt.total);
			}).success(function (data, status, headers, config) {
				console.log('file ' + config.file[0].name + ' is uploaded successfully. Response: ' + data);
			});
		});

**Comment by clabough** [comment]
OK, I figured out that the sample on the main page doesn't support progress and aborting.  I changed the code to this.

		$scope.$watch('files', function (files) {
			if (files != null) {
				for (var i = 0; i < files.length; i++) {
					$scope.errorMsg = null;
					(function (file) {

						file.upload = $upload.upload({
							url: '/api/erexattachment',
							method: 'POST',
							data: { ID: 1 },
							file: file
						});

						file.upload.then(function (response) {
							$timeout(function () {
								file.result = response.data;
							});
						}, function (response) {
							if (response.status > 0)
								$scope.errorMsg = response.status + ': ' + response.data;
						});

						file.upload.progress(function (evt) {
							// Math.min is to fix IE which reports 200% sometimes
							file.progress = Math.min(100, parseInt(100.0 * evt.loaded / evt.total));
						});
					})(files[i]);
				}
			}
		});

Note: This also shows people where the 'file' object comes from that's missing in the demo page documentation.

**Comment by clabough** [comment]
In case someone is using Controller As style or would prefer not to use $watch, I'm now using this.

ng-controller="formController as frm"

  <button ng-file-select data-ng-model="frm.Attachments" data-ng-change="frm.uploadFile(frm.Attachments)">Attach File</button>

[Controller function]

                vm = this;
		vm.uploadFile = function(files) {
			if (files != null) {
				for (var i = 0; i < files.length; i++) {
					vm.errorMsg = null;
					(function(file) {

						file.upload = $upload.upload({
							url: '/api/upload',
							method: 'POST',
							file: file
						});

						file.upload.then(function(response) {
							$timeout(function() {
								file.result = response.data;
							});
						}, function(response) {
							if (response.status > 0)
								vm.errorMsg = response.status + ': ' + response.data;
						});

						file.upload.progress(function(evt) {
							// Math.min is to fix IE which reports 200% sometimes
							file.progress = Math.min(100, parseInt(100.0 * evt.loaded / evt.total));
						});
					})(files[i]);
				}
			}
		};

**Comment by KoalaOnAStick** [comment]
@clabough Hey Clabough, thanks for your code: helped along a lot while implementing it for myself.

@danialfarid Perhaps it would be good to try to improve the docs to include these kinds of examples?

**Comment by KoalaOnAStick** [comment]
Also, @clabough , did you manage to make the image preview working using a Controller As style? If you did, I would really be interested in seeing some sample code...

**Comment by danialfarid** [comment]
Version 3.0.0 has fixed the sample code and there is a jsfiddle link that you can see and play with to figure out these samples.

**Comment by mikeandersun** [comment]
Version 3.0.0  isn't on NuGet!

**Comment by danialfarid** [comment]
I'm pushing it right now
