### ISSUE TITLE
multipart form data getting duplicated when request deferred

### ISSUE THREAD

**Issue by andrasg** [danialfarid/ng-file-upload#529]
I am using an interceptor to catch 401 responses and request new accesstokens. If the token operation succeeds I am retrying the request:

Catching and queueing the request:
 ```javascript
deferred = $q.defer();
httpBufferService.append(response.config, deferred);
$rootScope.$broadcast('event:auth-loginRequired', response);
```

Retrying:
```javascript
        function retryHttpRequest(config, deferred) {
            function successCallback(response) {
                deferred.resolve(response);
            }
            function errorCallback(response) {
                deferred.reject(response);
            }
            $http = $http || $injector.get('$http');
            $http(config).then(successCallback, errorCallback);
        }
```
[retry logic source](http://jeremymarc.github.io/2014/08/14/oauth2-with-angular-the-right-way/)

I have noticed that upon retry all form data in my multipart form gets doubled. Seems to me that the requesttransformer runs again and adds all headers again?
How can I make sure my retried requests aren't transformed again?

**Comment by lmolnargh** [comment]
Try override the transformRequest (in the retryHttpRequest function), if the formData was already appended. Sg like this:
$http = $http || $injector.get('$http');
if (angular.isDefined(config.file)) {
  config.transformRequest = function (formData, headerGetter) { return formData; };
}
$http(config).then(successCallback, errorCallback);
