### ISSUE TITLE
File upload not working with file select

### ISSUE THREAD

**Issue by mdesanti** [danialfarid/ng-file-upload#533]
I can't get the file upload to work when using `ng-file-select`. It's like the file is never added to the associated model. What's strange is that `ng-file-drop` is working without any issues.

Just for context, I am developing a node-webkit app with angularjs. I am using coffeescript and building the app with grunt.

My html looks like this:

```
<form id="new-project-form" name="form" ng-submit="create(project)" novalidate="novalidate" class="form-horizontal">
  <div ng-file-drop="ng-file-drop" ng-model="files" drag-over-class="dragover" class="drop-box">
    <fieldset>
      <legend translate="subproject.new"></legend>
      <div class="form-group">
        <label for="inputFile" translate="subproject.file" class="col-xs-2 control-label"></label>
        <div class="col-xs-10">
          <input type="file" ng-file-select="" ng-model="files" translate="subproject.form.select_file"/>
          <div class="progress progress-striped active">
            <div ng-style="progress" class="progress-bar"></div>
          </div>
          <div ng-repeat="file in uploadedFiles">
            <div class="row">
              <div ng-click="deleteFile(file)" class="col-xs-1"><img src="delete.png" class="delete"/></div>
              <div class="col-xs-11"><span>{{file.name}}</span></div>
            </div>
          </div>
        </div>
      </div>
    </fieldset>
  </div>
</form>
```

And this is the part of my controller that handles the file upload:

```
$scope.progress = {
    'width': '0%'
};
$scope.uploadedFiles = [];
$scope.project = {
    'file-ids': [],
    email: authenticationService.loggedInUser()
};
$scope.$watch('files', function(newValue, oldValue) {
      if (newValue === void 0) {
        return;
      }
      $scope.upload = $upload.upload({
        url: "some-upload-url",
        file: $scope.files
      }).progress(function(evt) {
         $scope.progress = {
           'width': parseInt(100.0 * evt.loaded / evt.total) + '%'
         };
      }).success(function(data, status, headers, config) {
          $scope.project['file-ids'].push(data.files[0].id);
          $scope.uploadedFiles.push(data.files[0]);
          $scope.progress = {
              'width': '0%'
          };
      });
});
```

Just in case it is useful, these are the declared dependencies in bower.json:
```
"dependencies": {
    "console-polyfill": "0.1.2",
    "jquery": "~2.0.3",
    "bootstrap-less": "~3.1.1",
    "angular-bootstrap": "~0.5.0",
    "angular": "1.3.10",
    "angular-truncate": "*",
    "angular-sanitize": "1.3.10",
    "angular-resource": "1.3.10",
    "angular-route": "1.3.10",
    "angular-cookies": "1.2.5",
    "angular-mocks": "1.2.5",
    "components-underscore": "~1.5.2",
    "ngstorage": "0.3.0",
    "bootstrap-material-design": "0.2.1",
    "ng-file-upload": "~2.2.2",
    "ng-file-upload-shim": "~2.2.2",
    "ngQuickDate": "~1.3.3",
    "spin.js": "~2.0.2",
    "angular-spinner": "~0.6.1",
    "angular-translate": "~2.5.2"
 }
```

**Comment by ryanki1** [comment]
The demo for IE9 doesn't appear to work either - just run https://angular-file-upload.appspot.com/ in IE9 and try and upload - you can select a file, but after that tumbleweed :-(

**Comment by ryanki1** [comment]
Also line 346 in angular-file-upload-shim needs to be changed from:
_this.onloadstart && this.onloadstart(constructEvent('loadstart', evt));
to (see char 22):
_this.onloadstart && _this.onloadstart(constructEvent('loadstart', evt));

**Comment by danialfarid** [comment]
@ryanki1 the demo should work in IE9. Are you sure it is not compatibility mode? What error message do you get in the console?

**Comment by danialfarid** [comment]
@ryanki1 thanks for pointing out the error in the shim file.

**Comment by ryanki1** [comment]
Hi Daniel 
Tried also in 64-bit IE8 on a non-work / my own home (windows) pc - can browse to file but then no feedback on page that file uploaded :-(
Attached the feedback from the console :-)

Best regards,
Kieran





Date: Tue, 3 Feb 2015 10:53:34 -0800

**Comment by danialfarid** [comment]
There's no attachment here

**Comment by olegskl** [comment]
I confirm that the demo doesn't work in IE9. Here's the log:
 
> Journal : FileAPI: 2.0.7
Journal : protocol: https:
Journal : doctype: [html] null null
Journal : FlashAPI.state: awaiting
Journal : (flash -> js).log: storeKey=509061645022050727353072930307296024040_2.0.7
Journal : (flash -> js).log: timeout=0
Journal : FlashAPI.state: ready
Journal : FlashAPI.event.mouseenter: [object Object]
Journal : (js -> flash).multiple: true
Journal : (flash -> js).log: parseCmd, command: multiple
Journal : (js -> flash).accept: *
Journal : (flash -> js).log: parseCmd, command: accept
Journal : FlashAPI.event.select: [object Object]
Error: Impossible d'effectuer l'opération à cause de l'erreur suivante c00c023e.

Rough translation: "Error: Impossible to perform an action because of error c00c023e"

The Flash version is 16.0.0.305

**Comment by danialfarid** [comment]
What OS do you have?
Is this link working?
http://2-2-1.angular-file-upload.appspot.com/
How about this:
http://3-0-0.angular-file-upload.appspot.com/

**Comment by olegskl** [comment]
We're using Windows 7 Professional Service Pack 1.
IE 9.0.8112.16421

### http://2-2-1.angular-file-upload.appspot.com/
> Journal : FileAPI: 2.0.7
Journal : protocol: http:
Journal : doctype: [html] null null
Journal : FlashAPI.state: awaiting
Journal : (flash -> js).log: storeKey=509061645022050727353072930307296024040_2.0.7
Journal : (flash -> js).log: timeout=0
Journal : FlashAPI.state: ready
Journal : FlashAPI.event.mouseenter: [object Object]
Journal : (js -> flash).multiple: false
Journal : (flash -> js).log: parseCmd, command: multiple
Journal : (js -> flash).accept: art,bm,bmp,dwg,dxf,cbr,cbz,fif,fpx,gif,ico,iefs,jfif,jpe,jpeg,jpg,jps,jut,mcf,nap,nif,pbm,pcx,pgm,pict,pm,png,pnm,qif,qtif,ras,rast,rf,rp,svf,tga,tif,tiff,xbm,xpm,xwd,ART,BM,BMP,DWG,DXF,CBR,CBZ,FIF,FPX,GIF,ICO,IEFS,JFIF,JPE,JPEG,JPG,JPS,JUT,MCF,NAP,NIF,PBM,PCX,PGM,PICT,PM,PNG,PNM,QIF,QTIF,RAS,RAST,RF,RP,SVF,TGA,TIF,TIFF,XBM,XPM,XWD
Journal : (flash -> js).log: parseCmd, command: accept
Journal : FlashAPI.event.mouseenter: [object Object]
Journal : (js -> flash).multiple: true
Journal : (flash -> js).log: parseCmd, command: multiple
Journal : (js -> flash).accept: *
Journal : (flash -> js).log: parseCmd, command: accept
Journal : FlashAPI.event.select: [object Object]
**Error: Erreur non spécifiée.**

(Non-specified error)

### http://3-0-0.angular-file-upload.appspot.com/
> Journal : FileAPI: 2.0.7
Journal : protocol: http:
Journal : doctype: [html] null null
Journal : FlashAPI.state: awaiting
Journal : (flash -> js).log: storeKey=509061645022050727353072930307296024040_2.0.7
Journal : (flash -> js).log: timeout=0
Journal : FlashAPI.state: ready
Journal : FlashAPI.event.mouseenter: [object Object]
Journal : (js -> flash).multiple: true
Journal : (flash -> js).log: parseCmd, command: multiple
Journal : (js -> flash).accept: *
Journal : (flash -> js).log: parseCmd, command: accept
Journal : FlashAPI.event.mouseenter: [object Object]
Journal : (js -> flash).multiple: false
Journal : (flash -> js).log: parseCmd, command: multiple
Journal : (js -> flash).accept: *
Journal : (flash -> js).log: parseCmd, command: accept
Journal : FlashAPI.event.mouseenter: [object Object]
Journal : (js -> flash).multiple: false
Journal : (flash -> js).log: parseCmd, command: multiple
Journal : (js -> flash).accept: *
Journal : (flash -> js).log: parseCmd, command: accept
Journal : FlashAPI.event.select: [object Object]
**Error: Erreur non spécifiée.**

(Non-specified error)

**Comment by danialfarid** [comment]
Well it works fine on the VM's that I have.
Can you try it on another machine? It could be a flash or network problem on that machine.

**Comment by danialfarid** [comment]
Any of these works?

http://1-6-0.angular-file-upload.appspot.com/
http://1-5-0.angular-file-upload.appspot.com/
http://2-0-0.angular-file-upload.appspot.com/
http://1.angular-file-upload.appspot.com/

**Comment by ryanki1** [comment]
Hi Daniel
thanks for the reply :-)
Apart from the "Upload on form submit" example (http://2-0-0.angular-file-upload.appspot.com/) ..
success :-) All the other links work with IE8 64-bit
Is it possible from the input[type="file"] files property to get at the binary/base64 data on the client side or is this information only available as a stream to the server?

Best regards,
Kieran





Date: Fri, 6 Feb 2015 08:35:17 -0800

**Comment by danialfarid** [comment]
I have fixed an issue with the demo page in version 3.0.2. Could you try again the main demo page and see if it is fixed.

**Comment by mini-thor** [comment]
Hi guys,

I ran into the same issue and solved it by defining a `files` object inside the controller and setting the `ng-model` like this: `ng-model="files.uploads"`. Then you will have to modify the `$watch` expression also to look for changes in `files.uploads`.

Hope this helps

**Comment by danialfarid** [comment]
@ryanki1 for file binary data you can use FileReader `readAsDataURL` or `readAsBinaryString`.
You need to include the shim file.

**Comment by ryanki1** [comment]
Hi Daniel
doesn't work though - for readAsDataURL [object File] expected - [object] given - results in error "error - readASDataURL not supported"

Best regards,
Kieran

BTW - Demo works - well the "attach files" option at least. 





Date: Wed, 11 Feb 2015 11:56:33 -0800

**Comment by MesfinReda** [comment]
Hi Daniel,

I was trying to get the file upload to work for several hours in IE9 with no luck. Your demo doesn't work too. Do you have any release coming out to fix this?
The following links work:
http://1-6-0.angular-file-upload.appspot.com/
http://1-5-0.angular-file-upload.appspot.com/

the following links does NOT work:
http://2-0-0.angular-file-upload.appspot.com/
http://angular-file-upload.appspot.com/

**Comment by danialfarid** [comment]
What is not working?

**Comment by danielabar** [comment]
IE9 (emulation mode) on Windows 8 was also not working for me, was getting "FileAPI' undefined. Then realized I hadn't read in detail the Old Browsers support section of the readme. In summary, this is what worked for me:

```
bower install fileapi --save
```

Where .bowerrc is

```
{
  "directory": "webclient/vendor"
}
```

Then index.html

```
<script src="vendor/angular/angular.min.js"></script>
<!-- IE9 File Upload Shim -->
<script>
      FileAPI = {
        jsUrl: 'vendor/fileapi/dist/FileAPI.min.js',
        flashUrl: 'vendor/fileapi/dist/FileAPI.flash.swf',
      }
</script>
<script src="vendor/ng-file-upload/angular-file-upload-shim.min.js"></script>
<script src="vendor/ng-file-upload/angular-file-upload.min.js"></script>
```

Then the success case works. One final hack needed, is if server rejects the file upload (for example, max file size exceeded, returns 400), then the `$upload.upload...).error(...` the code never goes into the error block. Instead it goes to the success block with `data` undefined. So I had to check in success block, something like:

```
if (!data) {
  // do error handling here
}

**Comment by aktgmail** [comment]
Hi
I am facing problem in file upload on IE 10 with document mode IE9 Standards.
Error is 
TypeError: Unable to get property 'protocol' of undefined or null reference 
ReferenceError: 'uri' is undefined 

After adding FileAPI-min.js and FileAPI.flash.swf I am able to click upload button and browse file. But after choosing file I am getting above error.

**Comment by danialfarid** [comment]
@aktgmail this is a closed issue please open a new one. Also from your error it seems like you don't specify the url in the Upload.upload({}) options.

**Comment by pravisharun** [comment]
Hi,
I try to upload file,But i got  bad request error

**Comment by pravisharun** [comment]
This my code..
<div ng-controller="MyCtrl">
  <file-uploader></file-uploader>
</div>


my controller



var myApp = angular.module('myApp',[]);

//myApp.directive('myDirective', function() {});
//myApp.factory('myService', function() {});

function MyCtrl($scope) {
    $scope.name = 'Superhero';
}

myApp.directive('fileUploader', function() {
	return {
		restrict: 'E',
		transclude: true,
		template: '<div><input type="file" multiple /><button ng-click="upload()">Upload</button></div>'
		+'<ul><li ng-repeat="file in files">{{file.name}} - {{file.type}}</li></ul>',
		controller: function($scope, $fileUpload) {
			$scope.notReady = true;
			$scope.upload = function() {
				$fileUpload.upload($scope.files);
			};
		},
		link: function($scope, $element) {
			var fileInput = $element.find('input[type="file"]');
			fileInput.bind('change', function(e) {
				$scope.notReady = e.target.files.length == 0;
				$scope.files = [];
				for(i in e.target.files) {
          
					if(typeof e.target.files[i] == 'object') $scope.files.push(e.target.files[i]);
				}
			});
		}
	}
});

myApp.service('$fileUpload', ['$http', function($http) {
	this.upload = function(files) {
		
		var formData = new FormData();
		for(i in files) {
			formData.append('file_'+i, files[i]);
		}
		console.log(formData);
		$http({method: 'POST', url: '/customer/7/artifacts', data: formData, headers: {'Content-Type': undefined}, transformRequest: angular.identity})
		.success(function(data, status, headers, config) {

		});
	}
}]);

**Comment by danialfarid** [comment]
This plugin service is called Upload not $fileUpload, are you sure you are on the right github @pravisharun

**Comment by sendreams** [comment]
ie9 also have same problem.


3-0-2.angular-file-upload.appspot.com
Error: 参数无效。
   {
      [functions]: ,
      description: "参数无效。",
      message: "参数无效。",
      name: "Error",
      number: -2147024809
   }

FlashAPI.state: awaiting
(flash -> js).log: storeKey=509010064704040205072730307293530729_2.0.7
(flash -> js).log: timeout=0
FlashAPI.state: ready
FlashAPI.event.mouseenter: [object Object]
   "FlashAPI.event.mouseenter:"
   {
      [functions]: ,
      flashId: "fileapi14580998997412",
      type: "mouseenter"
   }

(js -> flash).multiple: false
(flash -> js).log: parseCmd, command: multiple
(js -> flash).accept: art,bm,bmp,dwg,dxf,cbr,cbz,fif,fpx,gif,ico,iefs,jfif,jpe,jpeg,jpg,jps,jut,mcf,nap,nif,pbm,pcx,pgm,pict,pm,png,pnm,qif,qtif,ras,rast,rf,rp,svf,tga,tif,tiff,xbm,xpm,xwd,m4a,flac,aac,rm,mpa,wav,wma,ogg,mp3,mp2,m3u,mod,amf,dmf,dsm,far,gdm,imf,it,m15,med,okt,s3m,stm,sfx,ult,uni,xm,sid,ac3,dts,cue,aif,aiff,wpl,ape,mac,mpc,mpp,shn,wv,nsf,spc,gym,adplug,adx,dsp,adp,ymf,ast,afc,hps,xs,m4v,3gp,nsv,ts,ty,strm,rmvb,ifo,mov,qt,divx,xvid,bivx,vob,nrg,img,iso,pva,wmv,asf,asx,ogm,m2v,avi,bin,dat,dvr-ms,mpg,mpeg,mp4,mkv,avc,vp3,svq3,nuv,viv,dv,fli,flv,ART,BM,BMP,DWG,DXF,CBR,CBZ,FIF,FPX,GIF,ICO,IEFS,JFIF,JPE,JPEG,JPG,JPS,JUT,MCF,NAP,NIF,PBM,PCX,PGM,PICT,PM,PNG,PNM,QIF,QTIF,RAS,RAST,RF,RP,SVF,TGA,TIF,TIFF,XBM,XPM,XWD,M4A,FLAC,AAC,RM,MPA,WAV,WMA,OGG,MP3,MP2,M3U,MOD,AMF,DMF,DSM,FAR,GDM,IMF,IT,M15,MED,OKT,S3M,STM,SFX,ULT,UNI,XM,SID,AC3,DTS,CUE,AIF,AIFF,WPL,APE,MAC,MPC,MPP,SHN,WV,NSF,SPC,GYM,ADPLUG,ADX,DSP,ADP,YMF,AST,AFC,HPS,XS,M4V,3GP,NSV,TS,TY,STRM,RMVB,IFO,MOV,QT,DIVX,XVID,BIVX,VOB,NRG,IMG,ISO,PVA,WMV,ASF,
(flash -> js).log: parseCmd, command: accept
