### ISSUE TITLE
Not able to load files on S3

### ISSUE THREAD

**Issue by j4ml3t** [danialfarid/ng-file-upload#535]
Hello, I get this error when I try to upload from your website app 'https://angular-file-upload.appspot.com/':
"XMLHttpRequest cannot load https://notifications-s3.s3.amazonaws.com/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://angular-file-upload.appspot.com' is therefore not allowed access. The response had HTTP status code 403."
I tried nukulb solution on 'https://github.com/nukulb/s3-angular-file-upload' but I get the same result.
Credentials are ok, bucket and CORS. If I try to upload files with aws-sdk js without your library I get it.
I can show you the credentials if you want it.
I've lost lot of time trying to get it but I can't. I'm absolutely lost.
Thanks in advance

**Comment by danialfarid** [comment]
You need to enable CORS requests for your bucket.

**Comment by j4ml3t** [comment]
Hi, thanks for answering. This is my CORS configuration:
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>PUT</AllowedMethod>
        <AllowedMethod>GET</AllowedMethod>
        <MaxAgeSeconds>3000</MaxAgeSeconds>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>

**Comment by danialfarid** [comment]
Are you sending PUT or POST?
Enable post as well.
And I'm not sure if AllowedHeader * would actually work.

**Comment by j4ml3t** [comment]
It was my fault. Two things, I enabled POST method, and the other thing, I was working on chromium. It works ok from your website with chrome or firefox. But it isn't working with Nukulb app. I get a 403 Forbidden. Thank you anyway

**Comment by j4ml3t** [comment]
When I'm going to upload the file, If I change the acl data to 'private' and the acl policy condition to 'private' as well, it works, but I don't know why..

**Comment by cesarzeppini** [comment]
I'm actually having the same problem, but adding POST and setting ACL data and ACL policy to private didn't help. I still get the exact same error: **No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://angular-file-upload.appspot.com' is therefore not allowed access. The response had HTTP status code 403.**

I'm trying from your demo page, adding all info needed. 

I used this exact code to generate my keys:
```
{
  "expiration": "2020-01-01T00:00:00Z",
  "conditions": [
    {"bucket": "[MY-BUCKET]"},
    ["starts-with", "$key", ""],
    {"acl": "private"},
    ["starts-with", "$Content-Type", ""],
    ["starts-with", "$filename", ""],
    ["content-length-range", 0, 524288000]
  ]
}
```

Do you know what I can do?

**Comment by gronel** [comment]
i got error when i upload file in API XMLHttpRequest cannot load http://localhost:20015/api/mifs/files-upload. Response for preflight has invalid HTTP status code 405 I used MVC5 in server side

**Comment by danialfarid** [comment]
Post on stackoverflow this is a server side issue

**Comment by bishtpradeep** [comment]
**<quote>**
Are you sending PUT or POST?
Enable post as well.
And I'm not sure if AllowedHeader * would actually work.
**</quote>**

Hi @danialfarid 

I was getting the same error and when I enable POST as per your suggestion, the upload works successfully. However, I'm puzzled that my ios app is able to upload to the same bucket url even though POST is not enabled. Why does ng-file-upload requires POST to be enabled ? The upload url is a presigned url to s3 bucket.

Thank you for the awesome library.
