### ISSUE TITLE
'ng' prefix not a good naming convention.

### ISSUE THREAD

**Issue by kvetis** [danialfarid/ng-file-upload#538]
Prefixing custom directives 'ng' is a bad practice. You should use your own prefix if you don't any user code mixup. Something like 'da' or 'afu' would be better. :-)
See https://github.com/mgechev/angularjs-style-guide#directives

**Comment by rvanbaalen** [comment]
+1 for this use a prefix like `ngupload-` or something.

This will of course be a breaking change but it is definitely required.

**Comment by demisx** [comment]
+1 Very bad practice.

**Comment by reifi** [comment]
+1 bad practice, as confusing as using $variables

**Comment by rvanbaalen** [comment]
Since this will be a breaking change, perhaps set the milestone to `4.0.0` @danialfarid ?

**Comment by danialfarid** [comment]
Fixed in version 4.0.0
