### ISSUE TITLE
Safari issue - not treating ng-accept correctly

### ISSUE THREAD

**Issue by eabovsky** [danialfarid/ng-file-upload#551]
When using the drag and drop upload feature, safari seems to ignore whatever rules I put in the ng-accept field for the purpose of setting the accept/reject class on my drop-zone.

It still seems to respect it for the purpose of actually uploading a file - eg - it won't actually upload a file it's not supposed to accept, however, it won't highlight the field as "rejected" if an incompatible file type is being dragged over it.

**Comment by danialfarid** [comment]
That only works in Chrome.

**Comment by danialfarid** [comment]
Other browsers does not provide any information about type or filename of the items being dragged over.

**Comment by danialfarid** [comment]
So highlighting only works in chrome but the actual upload works everywhere

**Comment by eabovsky** [comment]
I see... I guess I'll just have to implement some "post-drop" validation & user feedback.
