### ISSUE TITLE
IE9 + Upload button inside bootstrap modal - Clicking button results in browser "Is not responding".

### ISSUE THREAD

**Issue by alphster** [danialfarid/ng-file-upload#552]
First off, thanks for the awesome library.  I've used it in 2 projects already.

I have one issue that i'm able to consistently reproduce.  I've had other testers also reproduce it with their IE9 browsers.

All you need to do, is set up a simple html page:
- include the angular-file-upload with shim support
- include bootstrap js and css

Use the bootstrap website to help you create a basic bare-bones modal.  Stick an upload button inside of it using angular-file-upload.  Create another button on the main page to make the modal pop up.
http://getbootstrap.com/javascript/#modals-examples

After clicking on the first button to pop up the modal, clicking on the button to get the file-selector dialog will basically freeze your IE9 browser.  After a few seconds, you'll see a message on the bottom that says "... is not responding."  No file select dialog will pop up.  

Everything will work fine if the button is placed outside of the modal (on the main page).  Something about bootstrap modal being hidden and then shown, while it contains the upload button, is causing this problem.

**Comment by danialfarid** [comment]
Can you create a jsfiddle off the jsfiddle sample in the readme file.

**Comment by alphster** [comment]
Here you go:
http://jsfiddle.net/nmdcwf3w/32/

Thanks for looking into this.  I put little notes all over the fiddle -- just be aware that you'll need to set up a real IE9 browser since it's only reproducible with the real thing.  Emulation mode on newer browsers will not reproduce the problem.

I'm able to get this fiddle working and am able to see the problem by opening it with IE9.

**Comment by alphster** [comment]
It obviously has something to do with either bootstrap modal/js implementation, or perhaps the way this button for file select is hidden and then resurfaced.  Not sure...

If you remove the "modal fade" class from the top of the modal (so that the modal is always showing), there's no problem.  That obviously circumvents a lot of what's going on under the hood, but i hope it helps.

**Comment by danialfarid** [comment]
hmm that's so weird. I think it might be related to FileAPI or Flash, everything works fine until you click on that flash object which is supposed to show the flash popup but it makes the browser unresponsive.

**Comment by alphster** [comment]
Yeah.  Check out the end of this thread.  Similar issues when using flash inside bootstrap modal.
https://github.com/mailru/FileAPI/issues/100

I might try that solution/hack in the end tomorrow and see what happens.

**Comment by alphster** [comment]
Wow, simply dropping this line into the controller fixes it.

$('[id^='+FileAPI.expando+']').on('focusin', false);

**Comment by alphster** [comment]
Ok, i was a little bit off with the above solution.

It needs to be delayed until FileAPI is ready to go.  I wrapped it with a $timeout.

I also made it conditional so that you don't get console errors in new browsers.

See solution here.
http://jsfiddle.net/nmdcwf3w/82/

**Comment by trotil** [comment]
wow, this helped a lot, saved my day, thank you!
