### ISSUE TITLE
iPhone click event is unstable

### ISSUE THREAD

**Issue by olalonde59** [danialfarid/ng-file-upload#555]
Using an iPhone 5S, on the file input, the user must "press" the file input container to trigger the click event. A simple fast click is not working.

The touchend event seems to better work on my iPhone.

It is possible to provide an event configuration to let the developer choose what event he want to bind (may depend on device detection)? Could be provided on the directive, ex:

```
<button ng-file-select ng-file-select-event="touchend" ng-file-change="onFileSelected($files)" ng-multiple="false" ng-capture="camera" ng-accept="'image/*'">
<span class="icon icon-camera"></span>
</button>
```

Cheers!

**Comment by danialfarid** [comment]
Fixed in version 3.3.4
