### ISSUE TITLE
file upload with Express

### ISSUE THREAD

**Issue by monad98** [danialfarid/ng-file-upload#559]
Hi.
I am using Express middleware 'multer' and want to make array of uploaded file names.

    exports.create = function(req, res) {
        var images = [];
        for (var i=0;i<req.files.file.length;i++) {
          images.push(req.files.file[i].name);
          console.log(req.files.file[i].name);
    }

but, resulting images array is [undefined, "image1.jpg", "image2.jpg", .......].
printed log is as expected.
image0.jpg
image1.jpg
image2.jpg

what's the problem?
Thanks in advance.

**Comment by neilhanekom** [comment]
I too need some help getting some form data plus files uploaded with multer middleware..

**Comment by danialfarid** [comment]
Can you post here the request headers and content that being sent to the server from your browser's debug tool.
