### ISSUE TITLE
How can I get the image size before uploading?

### ISSUE THREAD

**Issue by burzum** [danialfarid/ng-file-upload#568]
How can I get the image size before uploading? I need to get the size to validate that the image is at least X pixel width and height.

I know I can do it like this in a directive that I apply to the `<img>` element itself.

```js
		link: function(scope, element, attributes) {
			element.on('load', function () {
				scope.cmsImageSize.originalHeight = this.height;
				scope.cmsImageSize.originalHidth = this.width;
			});
		}
````

But how do I get it from within my files I'm watching? I've spent now some time inspecting the objects I have there but couldn't figure out from where I could get the image dimensions.

```js
$scope.$watch('data.files', function() {
				for (var i = 0; i < $scope.data.files.length; i++) {
					var file = $scope.data.files[i];
					$scope.upload = $upload.upload({
						url: '/api/v1/image_files/upload.json',
						method: 'POST',
						data: {
							'data[ImageFile][model]': 'CmsPageElementImage',
							'data[ImageFile][foreign_key]': $scope.element.CmsPageElement.id
						},
						file: file,
						fileFormDataName: 'data[ImageFile][file]'
					}).progress(function (evt) {
                                            /* ... */
					}).success(function (data, status, headers, config) {
                                            /* ... */
					});
				}
			});
```

**Comment by burzum** [comment]
OK, I've managed to get it to work with this code. Guess this is how it has to be done in JS, looks like an ugly work-around to me.

```
					var fr = new FileReader;
					fr.onload = function () { // file is loaded
						var img = new Image;
						img.onload = function () {
							alert(img.width); // image is loaded; sizes are available
						};
						img.src = fr.result; // is the data URL because called with readAsDataURL
					};
					fr.readAsDataURL(file); // I'm using a <input type="file"> for demonstrating
```

**Comment by drichfield** [comment]
Thanks burzum, this worked for me.

**Comment by danialfarid** [comment]
If you have ngf-max-width or similar validation, the width and height of the image will be calculated automatically and you can get it by `file.width` or `file.height`.
You can also use `Upload,imageDimensions(file).then(success, error)`

**Comment by drichfield** [comment]
Danial, even better.  I never saw the width and height properties on file, but that must be because I was not using validation.  I will just set it very high as I don't want to limit dimensions, in order to access those properties.  Thanks.

**Comment by grutta16** [comment]
Thanks guys. @drichfield you can use ngf-min-height="1" or ngf-min-width="1" instead, I think is better. @danialfarid there is a way to get the image resolution in ppp and the deep in bits? Thanks again.

**Comment by danialfarid** [comment]
@grutta16 create a separate issue for that request. Not at the moment.

**Comment by i2p0** [comment]
@danialfarid Hi Danial, I'm trying to use your tool with large size images but i don't se ngf-max-width with 300MB images... there something particular to setup? I'm more interested to get the image width and heigh than limit the size.

**Comment by danialfarid** [comment]
Use 'Upload.imageDimensions(file).then()`

**Comment by i2p0** [comment]
sorry it is what i have tried but I ended in error Value: "load Error" there something else I miss?

**Comment by danialfarid** [comment]
Are you able to show the image using `<img src='url to the image'>` on the page?

**Comment by i2p0** [comment]
I don't want to do it because it's too big... and i risk to hang the browser it's up to 60,000PX x 20,000PX and 250GB size
I'm looking at a way to get size without opening the image like from General informations in Operation system

**Comment by danialfarid** [comment]
I don't think that is possible, the file information you get from the browser when you select the file through popup is very limited, only type, size and name. You need to load the image in the browser to get the image dimensions.

**Comment by i2p0** [comment]
thank's for the reply i will look somewhere else in processing the image after upload... I don't want to hand the uploader

**Comment by Colmedo** [comment]
Thank you ! @burzum this work for me in Angular 4 too.
