### ISSUE TITLE
Checksum MD5 / SHA1 on client and server side

### ISSUE THREAD

**Issue by klaszlo** [danialfarid/ng-file-upload#575]
After uploading a file, i would like to check if it has been correctly uploaded.
So I would like to perform a checksum on server side, and also on client side. 
I think md5 is the fastest option.

Any idea for such implementation? It may be an enhancement request.

Update: 
A bit research. This javascript  MD5 library is good enough:
https://github.com/satazor/SparkMD5

A stackoverflow question about just this:
http://stackoverflow.com/questions/768268/how-to-calculate-md5-hash-of-a-file-using-javascript

**Comment by danialfarid** [comment]
You could create a pull request if you like to contribute.
