### ISSUE TITLE
Does angular-file-upload automatically resume upload after reconnect?

### ISSUE THREAD

**Issue by BaurzhanSakhariev** [danialfarid/ng-file-upload#578]
I'm using angular-file-upload and want to share my thanks to the author for developing such useful module. 

Now I want to make my upload more stable and add possibility to resume upload after disconnect. When I tried to simulate network error on the demo page by simply unplugging network cable I saw progress bar stopped and started from the current upload state after reconnecting cable. Does it mean that angular-file-upload automatically works without reloading whole file again? About demo - how client side knows what parts of file already loaded to server when it resumes upload? AFAIK, angular-file-upload uses multipart/formdata and doesn't  split file into chunks, that's why smart behavior of demo page surprised me.

Actually, my objective is to provide upload with possibility to resume, limit upload speed and size - does angular-file-upload fit my requirements or I should switch to other lib or even applet?

**Comment by danialfarid** [comment]
That's the browser/network interface that handle the temporary disconnect.

**Comment by danialfarid** [comment]
You can limit the file size by checking the file length before uploading but upload speed and resumable upload is not supported yet. Most of these need special coding on the server side.
