### ISSUE TITLE
file array resetting

### ISSUE THREAD

**Issue by MichaelValentine** [danialfarid/ng-file-upload#580]
html:

```html
<div id="images" class="row form-group" data-ng-repeat="image in ss.files.images track by $index">
    <input type="file" name="image" ng-file-select ng-model="image" accept="image/*"/>
</div>
<button class="btn btn-sm btn-block btn-primary" ng-click="addImage()">Add image</button>
```

js:
```javascript
var ss= {
            files:{
                images:[{}]
            }
        };

$scope.addImage = function(){
            $scope.ss.files.images.push({});
        };
```
When the user uploads an image, it hits the array just fine, but when the Add image button is clicked, rather than just appending an empty object to the array, the entire array becomes empty object (but maintains its length).

**Comment by MichaelValentine** [comment]
Update, it also isnt actually saving anything to the array anymore either. This is different behavior than 2.2.2 which I just updated from. Is there a new way to handle arrays of files?

**Comment by MichaelValentine** [comment]
File was being saved in a newly created scope under "image"

Html workaround:
ng-file-select ng-model="ss.files.images[$index]"

Then in js reference using ss.files.images[index][0].

Is there anyway to be able to reference nested repeatable objects using the key given in:
ng-repeat="key in dictionary"?

**Comment by markvp** [comment]
Do you mean like this:
````
<div ng-repeat="(key, value) in nested.dictionary">
````

See https://docs.angularjs.org/api/ng/directive/ngRepeat

**Comment by MichaelValentine** [comment]
Appologies, I did not wrap my html in a code block on the first comment, it is correctly rendering now to show my intention

**Comment by danialfarid** [comment]
Could you create a jsfiddle showing the problem and how you cannot use the key in ng-repeat? You can use the jsfiddle sample on the readme file as base.
