### ISSUE TITLE
Can not upload a video file

### ISSUE THREAD

**Issue by yela** [danialfarid/ng-file-upload#590]
Here is my input tag:
```html
<input type="file" ng-file-select="onFileSelect($files)"  ng-model="picFile" resetOnClick="true" ng-accept="'image/jpeg, image/jpg, image/png, video/mp4, video/3gp, video/mov'">
```
In controller in console I get an empty array when I upload a video file:
```javascript
$scope.onFileSelect = function($files) {
    console.log($files);
    ...
}

Could you please explain what I am doing wrong?

**Comment by danialfarid** [comment]
The files are begin rejected by ng-accept. You can add `ng-model-rejected` attribute to your element to see the rejected files.

Don't put spaces between ng-accept mime-types.
Also make sure the file you are chosing has one of those content-types.

**Comment by AntJanus** [comment]
The spaces tripped me up as well.

**Comment by yela** [comment]
Thanks! I removed spaces and everything now works fine.
