### ISSUE TITLE
Progress function reports 100% success almost immediately.

### ISSUE THREAD

**Issue by mdemougin** [danialfarid/ng-file-upload#591]
I have the following code in my directive:

this.$scope.upload = this.$upload.upload({
      url: url
      method: 'POST',
      headers: {'Content-Type': file.type},
      data: data,
      file: file,
      fileName: fileName
    }).progress((evt: any) => {
      console.log('percent: ' + parseInt((100.0 * evt.loaded / evt.total).toString(), 10));
    }).success((result: any, status: any, headers: any, config: any) => {
      // file is uploaded successfully
      console.log('Success');
    }).error((msg: any) => {
       console.log('Error ' + msg);
    });

If I upload a 100MB file, progress will be called a number of times with the last call reporting 100%, all within about a second.  Roughly 30 seconds to a minute later, success is called.  I'm running this against a Java/REST backend running on Tomcat and setting a breakpoint in the REST controller reveals that the 100% is reached before the file is even read from the input stream.  Do you have any ideas what could cause this?  I know it isn't browser, because your demo page works just fine in all the browsers I am testing this against.  I also tried getting the xhr from .xhr and adding an event listener there, but the exact same scenario occurred.  The same scenario also occurred when I attempted to use this.$scope.upload.progress = function(e) { ... }; instead of the chained code.

**Comment by danialfarid** [comment]
That's probably a server side problem. You can change the url of the jsfiddle sample in readme file to upload to your server (if your server supports cors request) to make sure it is not your js code.

**Comment by danialfarid** [comment]
You should not have 'headers: {'Content-Type': file.type},' for `$upload.upload()` see the readme file on how to use $upload.upload and $upload.http.
