### ISSUE TITLE
Prevent opening window

### ISSUE THREAD

**Issue by jirikolarik** [danialfarid/ng-file-upload#592]
Hi,

is possible to prevent opening the file select window? I need to ask user before if he really want to do that.

Thanks.

**Comment by wdhilliard-genebygene** [comment]
this is not an issue. you can achieve this by adding a button that triggers a popup and triggering the file selection only on confirmation.

**Comment by danialfarid** [comment]
You can add `ng-disabled` to the element.

**Comment by jirikolarik** [comment]
Thanks for reply, that was really stupid question, I see it now and I shouldn't ask on end of working day. :)
