### ISSUE TITLE
NodeJs Server does not see the request as "post" request on my upload specified Url.

### ISSUE THREAD

**Issue by neilhanekom** [danialfarid/ng-file-upload#595]
When I try to submit data on the specified URL in the upload config. The server responds with a bad request and sees the request as a GET request. I have also supplied method: 'POST' in the config. But still I get the same issue. 

I am using Multer Middleware with Express. 

Can anyone suggest what I might be doing wrong or what am I missing.??

**Comment by danialfarid** [comment]
Closed due to inactivity. Assuming you have solved it already.
