### ISSUE TITLE
Work with scope architecture shortage.

### ISSUE THREAD

**Issue by druxax** [danialfarid/ng-file-upload#596]
Hello, Danial!

You angular extension is awesome.
But, why you using $scope like thise:

$scope.$watch('files', function () {
    $scope.upload($scope.files);
});
$scope.upload = function (files) {
   if (files && files.length) {
       //Do thx
   }
}

If I want to load more than one different files and add more than one load buttons?

It's good solution don't use $scope when pass the files like this:

div ng-controller="myController"
   button ng-file-select ng-file-change='myController.upload($files)' >Load files/button
/div

But this upload($files) isn't invoke in myController.
Is it bug or architecture shortage?
Please fix it because people realy like you extension!

**Comment by danialfarid** [comment]
I don't get where the problem is, could you create a jsfiddle from the example on the readme file to show the problem? I will reopen this if you could create an example with reproducing the problem.
