### ISSUE TITLE
success event handler not triggering...ONLY IN IE9

### ISSUE THREAD

**Issue by polisettyk** [danialfarid/ng-file-upload#598]
Service call to ‘./api/test/legacypost’ happens successfully(returns plain/text content type) but the success event handler does not trigger. Iam using ASP.NET Web API for the service calls. I am missing something? Please let me know.

var upload = $upload.upload({
                        url: './api/test/legacypost',                        
                        data: vm.contact,
                        file: $files[0],
                    }).success(function(data, status, headers, config) {
                    // this callback will be called asynchronously
                    // when the response is available
                            console.write("test");
                    }).
                  error(function(data, status, headers, config) {
                    // called asynchronously if an error occurs
                      // or server returns response with an error status.
                    });

**Comment by danialfarid** [comment]
What browser and version of plugin?

**Comment by polisettyk** [comment]
IE 9 and I assume the latest plugin. Colleagues tarted using last week. I can confirm plugin version tomorrow

**Comment by polisettyk** [comment]
It works in chrome and Firebox browsers but not IE 9

**Comment by danialfarid** [comment]
Make sure your server returns some response body, see the readme old browser's known issues.

**Comment by polisettyk** [comment]
Thank you much for your response. I am using 3.0.7 plugin version. server is returning a response body with content type as 'text/plain'. is there any where i can put a break point and probably take it from there?

**Comment by polisettyk** [comment]
I even tried sending error status codes and could not catch errors as well.

**Comment by danialfarid** [comment]
https://github.com/danialfarid/angular-file-upload/blob/master/dist/angular-file-upload-shim.js#L103

**Comment by polisettyk** [comment]
I already tried based on threads linked to known issues. It never hits line 103 in both 3.0.7 and 3.1.1 version.

**Comment by danialfarid** [comment]
Then it would be a flash issue.
Do you receive the progress event?

**Comment by polisettyk** [comment]
No. I did not receive progress event as well.

**Comment by danialfarid** [comment]
Do you receive the whole file on the server?

**Comment by polisettyk** [comment]
I received the whole file from the server and was able to send success and error responses back to the browser. I was able to verify that using fiddler.

**Comment by danialfarid** [comment]
You can use a network monitoring tool and compare the content of your request and response with the demo page and see what's the difference between the response you are sending back and the response of the demo page that makes it work.

**Comment by danialfarid** [comment]
Please reopen if the issue still exists.
