### ISSUE TITLE
Upload does not work with Isolated scope in a directive

### ISSUE THREAD

**Issue by gottfrois** [danialfarid/ng-file-upload#600]
Hey guys,

First of all, thanks for the great work you are putting into this lib, it's just amazing!

I'd like to extract the upload logic into a re-usable directive therefor with an isolated scope. Unfortunately as soon as I isolate the scope of the directive, upload does not work anymore.

I'm sure i'm missing something really trivial here so i'll just dump a plunker here. Any help or guidance would be much appreciated !

http://plnkr.co/edit/px1wmmVITJgLLFN2lMMQ?p=preview

In `app.js` simply remove `scope: {}`  to see it working again in web console.

Thanks,

**Comment by markvp** [comment]
This seems to be an angular-wide issue related to your use of isolated scope with the controllerAs syntax in a directive. See: https://github.com/angular/angular.js/issues/7635

**Comment by gottfrois** [comment]
Thanks for pointing me in that direction but unfortunately, removing the `controllerAs` feature is still not uploading the file when isolating the scope. Any ideas?

Updated code: http://plnkr.co/edit/px1wmmVITJgLLFN2lMMQ?p=preview

**Comment by davidsielert** [comment]
Ever figure this out?

**Comment by gottfrois** [comment]
More a work around, I forwared the `files` into the scope:

```
scope: {
    files: '='
}
```

Then watching the files:

```
$scope.$watch 'files', (files)->
  ...
```
