### ISSUE TITLE
Progress always showing 100%

### ISSUE THREAD

**Issue by npearson72** [danialfarid/ng-file-upload#602]
When I compute the progress event like so:
````
var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
console.log('progress: ' + progressPercentage + '% ' + evt.config.file.name);
````

I always get a 100% immediately.

I know the images are not done loading though. I also have `angular-loading-bar` installed and it too is still working while the progress callback resolves to 100% right away.

Any ideas?

**Comment by danialfarid** [comment]
Can you create a jsfiddle?

**Comment by npearson72** [comment]
@danialfarid Sure, sorry for the delay:

http://jsfiddle.net/dv9s98vr/1/

I added this visual progress arc so it's easier to see what's up:

https://github.com/mathewbyrne/angular-progress-arc

**Comment by danialfarid** [comment]
It works fine for me in chrome, if you chose a relatively bigger file it shows the progress.
What browser are you testing on and what is the size of the file you are uploading?

**Comment by npearson72** [comment]
You're right. It does work with larger files (and in general). I think what's going on for me is that I'm sending the file to my server and from there it gets uploaded to Cloudinary. I'm assuming the progress only measure the transmission of the request, not the entire request/response loop?

**Comment by danialfarid** [comment]
True
