### ISSUE TITLE
Trouble with IE9 upload and NTLM authentication

### ISSUE THREAD

**Issue by Stefan318i** [danialfarid/ng-file-upload#605]
Hello,

I have the directive running fine in Chrome also using NTLM authentication. However when I use IE9 it falls back to flash and sends one request which gets an 401 back from the server. The sent request looks fine but it doesn't resume with the usual second and third request for sending credentials but just stops. Do you have an idea what I could do about that?

I am using version 3.1.1 of the file upload and version 1.3.0 of angularjs. Any help would be appreciated and btw great directive.

Thanks,
Stefan

**Comment by danialfarid** [comment]
You cannot send custom headers in IE9, read the readme file old browser limitations and related issues for workarounds for custom headers.

**Comment by Stefan318i** [comment]
OK - thanks for the info. As far as I have seen in the other posts there is now real acceptable workaround for this. Have you ever though about using iFrames instead of Flash for supporting old browsers? This seems to be working at least with IE9 but of course I don't know what limitations that might have. Do you think it would be complicated to exchange the Flash for another option in your shim.js?

**Comment by danialfarid** [comment]
With iframe approach the file is just being sent on user click and you won't have access to the file size,name,type before uploading so you cannot validate the file beforehand.
Silverlight approach also has it's own limitations/bugs and Flash seems to be more reliable.
So Flash is the best option if you want to get the file information before uploading (assigning it to a model object).

**Comment by Stefan318i** [comment]
Thanks for taking the time to elaborate. In my case a simple upload without knowing things about the file would be sufficient but I understand that in your common case scenario Flash is the best approach. So I will close the issue and maybe give it a try to use your directive but replace the flash part with the iFrame part.

**Comment by danialfarid** [comment]
You cannot send custom headers with iframe approach either, so it doesn't give anything extra it just won't provide progress and file info before upload.
