### ISSUE TITLE
Rename github repo to match published bower module

### ISSUE THREAD

**Issue by vic** [danialfarid/ng-file-upload#606]
I guess we could avoid many confusion if this repo would be named `ng-file-upload` just as the bower component it provides. This could prevent people thinking that that the `angular-file-upload` module is actually from this repo.

**Comment by rvanbaalen** [comment]
Or people could just read the whole thing and see `danialfarid` in the project url :wink:

**Comment by danialfarid** [comment]
https://github.com/danialfarid/ng-file-upload/issues/606

**Comment by danialfarid** [comment]
Done!

**Comment by rvanbaalen** [comment]
Whoa @danialfarid renaming the repo has quite some impact! For instance people using rawgit.com as a CDN pointing to your repo's files -- all links are dead now!

Just for the sake of 'convenience' without properly announcing the change would be a little too much in my opinion.

**Comment by danialfarid** [comment]
@rvanbaalen all the old links should still work, the angular-file-upload path will be redirected to ng-file-upload.

**Comment by rvanbaalen** [comment]
Well that's apparently not the case for `rawgit.com`..

**Comment by danialfarid** [comment]
Can you give me an example? the links I tried with rawgit are working.

**Comment by rvanbaalen** [comment]
Strange perhaps it was temporary right after you changed the name. 

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by rvanbaalen** [comment]
My bad this issue can be closed.

Instead of changing the URL from

```
//cdn.rawgit.com/danialfarid/angular-file-upload/3.1.2/dist/angular-file-upload-shim.js
```

to 

```
//cdn.rawgit.com/danialfarid/ng-file-upload/3.1.2/dist/angular-file-upload-shim.js
```

I changed it to 

```
//cdn.rawgit.com/danialfarid/angular-file-upload/3.1.2/dist/ng-file-upload-shim.js
```

So, to confirm, both of these URL's are working now:

```
//cdn.rawgit.com/danialfarid/ng-file-upload/3.1.2/dist/angular-file-upload-shim.js
//cdn.rawgit.com/danialfarid/angular-file-upload/3.1.2/dist/angular-file-upload-shim.js
```

Although I would recommend going for the former to prevent future confusion.

**Comment by danialfarid** [comment]
The files are renamed to ng-file-upload.js as well,

**Comment by danialfarid** [comment]
Since version 4.0.0
