### ISSUE TITLE
Prevent the angular-file-upload-shim from intercepting regular xhr requests

### ISSUE THREAD

**Issue by rvanbaalen** [danialfarid/ng-file-upload#608]
Right now the shim patches the global XHR object which has a negative effect on the rest of my application: all xhr requests (made by Angular and others) are going through the shim; not only the upload requests. 

This is highly unwanted. For instance, some if my regular non-upload-related API calls are even (silently) failing when the shim is active.

**Comment by danialfarid** [comment]
That shouldn't happen. The shim will just call the original method if the xhr call is not upload related, so it would just "pass through".
If you have a special case that it is not working as expected post the related code here.
