### ISSUE TITLE
POSTing as application/json instead of multipart

### ISSUE THREAD

**Issue by baxford** [danialfarid/ng-file-upload#610]
Hi, first off thanks for a great plugin!
I'm trying to POST to an API that accepts plan JSON (with the file itself encoded as Base64), similar to this directive:
https://github.com/adonespitogo/angular-base64-upload, but I'd like to keep the features of your plugin, such as drag and drop, multiple files etc.
I've managed to get things working by creating my own transformRequest function which returns the JSON object including the base64 encoded file, eg
          transformRequest: function(data, headerGetter) {
            var r = {image: base64String, fileName: fileName };
            return JSON.stringify(r);
          }

However in angular-file-upload.js upload function (line 114), it also pushes a transformRequest function which returns a FormData object. This seems to force the POST to be a multipart POST.

Is there a simple way to prevent this final transformRequest function from being added, so that it only uses my custom transformRequest function, or would it require modifications, or a flag in the config object?
I can submit a pull request if this would help.
thanks!

**Comment by danialfarid** [comment]
Use `$upload.http()`. You can find sample in the readme file.

**Comment by baxford** [comment]
ah, I missed that on reading the doco, but it works great, thanks!
