### ISSUE TITLE
accept/ng-accept attribute for file-drop with file-select

### ISSUE THREAD

**Issue by pasine** [danialfarid/ng-file-upload#614]
I have noticed a couple of wired behaviour using file-drop + file-select.
I was trying to use file-drop with file-select and I spotted these issues:

- accept attribute must be a string, without quotes (this is correct in the demo, but not in the Readme)

```
accept=" image/* " <- Works
accept=" 'image/*' " <- Doesn't work
```

- if reject files model is initially undefined, it is not created on drop, but only on select

- if both accept and ng-accept are defined, ng-accept is ignored on drop.
According to the [release note](https://github.com/danialfarid/ng-file-upload/releases/tag/3.1.0) I would expect the opposite.

You can see the behaviour in [this fiddle](http://jsfiddle.net/notme/6dz9nhw1/).

**Comment by danialfarid** [comment]
Should work in version 3.2.1
