### ISSUE TITLE
S3 Upload - Unsupported Authorization Type

### ISSUE THREAD

**Issue by Synergi** [danialfarid/ng-file-upload#615]
Don't think this is an issue but rather a request for a little assistance if anybody out there has any suggestions. I have been on this for a while now and I'm not getting anywhere. No matter what I try, I continue to get back the same error message from Amazon.

     <Error>
        <Code>InvalidArgument</Code>
        <Message>Unsupported Authorization Type</Message>
        <ArgumentName>Authorization</ArgumentName>
        <ArgumentValue>Basic U1Q6</ArgumentValue>
        <RequestId>80B90936C37C0CEE</RequestId>
        <HostId>NphuQmN38ri6LvRAlpec8dSC2YwqOKD15ozInX7UmRPhFPZsGmFIghziNfzB/Y7o</HostId>
    </Error>

I am using ng-file-upload (https://github.com/danialfarid/ng-file-upload) to upload to S3. I have followed the documentation and have used the demo installation to successfully upload a file to my bucket so I know my AWS Key and Secret Key are correct.

My controller is as follows:

    AWSs3 = {
        key:  'AWS-KEY-HERE',
        filename: file[0].name,
        fileSize: file[0].size,
        fileType: file[0].type,
        bucket: 'manual-attachments',
        acl: 'public-read',
        timestamp: timestamp
    }

    $http({
        method: "post",
        url: "../api/manuals/s3",
        data: AWSs3
    }).success(function(data, status, headers, config){                                     
        file.upload = $upload.upload({
        url : 'https://bucket.s3.amazonaws.com/',
        method : 'POST',
        fields : {
                key: file[0].name,
                acl: AWSs3.acl,
                AWSAccessKeyId: AWSs3.key,
                policy: data.policy,
                signature: data.signature,
                "Content-Type"  : file.type === null || file.type === '' ? 'application/octet-stream' : file.type,
                filename: file[0].name
                },
                file : file,
            });

            file.upload.then(function(response) {
                $timeout(function() {
                    file.result = response.data;
                });
            }, function(response) {
                if (response.status > 0)
                    $scope.errorMsg = response.status + ': ' + response.data;
            });

            file.upload.progress(function(evt) {
                file.progress = Math.min(100, parseInt(100.0 * evt.loaded / evt.total));
                });

    }).error(function(data, status, headers, config){
        $log.info('{Error: '+data+'}');
        return false;
    });

Now the PHP for generating the policy and signature is as follows:

    class S3 {
        public static $AWS_ACCESS_KEY           = "AWS-KEY";
        public static $AWS_SECRET_ACCESS_KEY    = "AWS-SECRET-KEY";

        public static function get_policy_and_signature( array $data )
        {
            $policy = self::get_policy_doc( $data );
            $signature = self::get_signature( $policy );

        if ( strpos($signature, '+') !== FALSE )
        {
           $data['timestamp'] = intval(@$data['timestamp']) + 1;
           return self::get_policy_and_signature( $data );
        }

        return '{"policy": "'.$policy.'", "signature":"'.$signature.'"}';
    }

    public static function get_policy_doc(array $data)
     {
        $now = strtotime(date("Y-m-d\TG:i:s"));
        $expire = date('Y-m-d\TG:i:s\Z', strtotime('+ 10 minutes', $now));

        return base64_encode(
          '{'.
               '"expiration": "'.$expire.'",'.
               '"conditions": '.
               '['.
                   '{"bucket": "'.$data['bucket'].'"},'.
                   '["starts-with", "$key", ""],'.
                   '{"acl": "public-read"},'.
                   '{"success_action_status": "201"},'.
                   '["starts-with", "$Content-Type", ""],'.
                   '["starts-with", "$filename", ""],'.
                   '["content-length-range",0,5242880]'.
               ']'.
           '}'
       );
    }

    public static function get_signature( $policy_doc ) {
       return base64_encode(hash_hmac(
           'sha1', $policy_doc, self::$AWS_SECRET_ACCESS_KEY, true
       ));
    }
    }

The http headers show "Authorization:Basic U1Q6" which is obviously the issue. Any assistance with this would be greatly appreciated.

**Comment by Synergi** [comment]
I'm an idiot! It's official! The header was the result of my own login/authorisation script that I completely forgot about.

Sorry for any confusion.

**Comment by sensahin** [comment]
> I'm an idiot! It's official! The header was the result of my own login/authorisation script that I completely forgot about.
> 
> Sorry for any confusion.

So how did you solve it? I am also having same issue.

**Comment by Synergi** [comment]
> > I'm an idiot! It's official! The header was the result of my own login/authorisation script that I completely forgot about.
> > Sorry for any confusion.
> 
> So how did you solve it? I am also having same issue.

I examined the headers more closely and realised that my app was configured to globally add an “Authorisation” header for all outgoing requests so it was this additional header that was causing the problem. Once that was identified it was a simple matter of creating an exception for that global header.

Hope that helps you to track it down.

**Comment by sensahin** [comment]
> > > I'm an idiot! It's official! The header was the result of my own login/authorisation script that I completely forgot about.
> 
> > > Sorry for any confusion.
> 
> > 
> 
> > So how did you solve it? I am also having same issue.
> 
> 
> 
> I examined the headers more closely and realised that my app was configured to globally add an “Authorisation” header for all outgoing requests so it was this additional header that was causing the problem. Once that was identified it was a simple matter of creating an exception for that global header.
> 
> 
> 
> Hope that helps you to track it down.

Thank you! I just removed the authorization from header and it worked! Thanks a lot sharing this info. I was trying to fix this issue for days!

**Comment by pr1ntr** [comment]
10 years later, this issue is still paying dividends
