### ISSUE TITLE
Jade/Other Compiled templating language can cause issue with ng-file-change

### ISSUE THREAD

**Issue by SimeonC** [danialfarid/ng-file-upload#616]
This is mostly an FYI for anyone else who has problems with this. I defined my file upload like so:
```jade
.list-group-item(
	ng-file-drop
	ng-file-select
	ng-model="upload.files"
	ng-file-change="startUpload($files, upload)"
) {{upload.name}}
```
Unfortunately this causes issues as this compiles to:
```html
<div class="list-group-item"
	ng-file-drop="ng-file-drop"
	ng-file-select="ng-file-drop"
	ng-model="upload.files"
	ng-file-change="startUpload($files, upload)"
>{{upload.name}}</div>
```
This causes issues as ng-file-drop and ng-file-select attribute values try to override the ng-file-change if both are defined which makes it seem like the change event doesn't fire (I may have missed this documented somewhere).

The workaround for this is to make the attributes blank like so:
```jade
.list-group-item(
	ng-file-drop=""
	ng-file-select=""
	ng-model="upload.files"
	ng-file-change="startUpload($files, upload)"
) {{upload.name}}
```

I can get this to work that way but I thought it best to mention this as I couldn't find any docs anywhere about this quirk.

**Comment by danialfarid** [comment]
Fixed in version 3.3.0
