### ISSUE TITLE
Async validation in ng-accept

### ISSUE THREAD

**Issue by hinok** [danialfarid/ng-file-upload#617]
Hey,
I'm using using ng-accept for checking size of selected files and their type.

I've wanted implement mechanism to checking dimensions of selected image file but in that specific case getting image size is asynchronous thus I couldn't return boolean in validate function passed to ng-accept.

It could be great if function passed to ng-accept could return plain boolean (sync way) or a promise (async way).

Below is link to jsfiddle which shows the problem.
http://jsfiddle.net/29a7a0vt/4/

**Comment by danialfarid** [comment]
Could you submit a PR?

**Comment by hinok** [comment]
I'll try at the weekend use some code that I wrote for my own directive (just wrapper for ng-file-upload) and if everything will go smoothly I will add PR :racehorse:

**Comment by danialfarid** [comment]
`ngfValidateAsync` is added to the latest versions.
