### ISSUE TITLE
Remove console.log debugging output

### ISSUE THREAD

**Issue by lancecaraccioli** [danialfarid/ng-file-upload#618]
https://github.com/danialfarid/ng-file-upload/blob/master/demo/war/js/angular-file-upload.js#L223
https://github.com/danialfarid/ng-file-upload/blob/master/demo/war/js/angular-file-upload.js#L496

**Comment by danialfarid** [comment]
Do you wanna submit a PR?

**Comment by lancecaraccioli** [comment]
sure, can do

**Comment by lancecaraccioli** [comment]
do you prefer only the src template change, or the results of running grunt to be submitted in the PR?
