### ISSUE TITLE
multiple files alternatingly works or not in IE9

### ISSUE THREAD

**Issue by thynctank** [danialfarid/ng-file-upload#626]
Not sure if this is an issue for this project or FileAPI.

Using ng-file-drop with ng-multiple set to true:

Sometimes, IE9 only allows me to select a single file via the "Choose File to Upload" modal. This appears to be the native file input dialog.

Other times, it allows me to select a single file via "Select file(s) to upload..." modal, which I take to be the Flash-based dialog.

I haven't as yet determined what actually causes this varying behavior, but there are no changes happening besides this.

Any idea what's happening here? Thanks! Attached are the screen grabs of the alternate dialogs.

![choose_file](https://cloud.githubusercontent.com/assets/5626/6674644/8528ae46-cbf1-11e4-920d-453432c6e390.png)
![select_files](https://cloud.githubusercontent.com/assets/5626/6674643/852727e2-cbf1-11e4-9497-433baa08df1a.png)

**Comment by danialfarid** [comment]
So in both cases you cannot select multiple files?

**Comment by thynctank** [comment]
When the "Choose File..." dialog pops, the user can only select one file. When the "Select file(s)..." does, user can select one or more.

**Comment by danialfarid** [comment]
Should be fixed in version 3.3.0
