### ISSUE TITLE
Uploading a file more than once causes an error

### ISSUE THREAD

**Issue by astromac** [danialfarid/ng-file-upload#627]
I'm finding an error that occurs when you try to upload a file for a second time after successfully uploading a file. Specifically the error returned is:
```
TypeError: Failed to construct 'Blob': The 1st argument provided is either null, or an invalid Array object.
    at TypeError (native)
    at config.transformRequest (http://localhost:8080/bower_components/ng-file-upload/angular-file-upload.js:141:30)
    (error continues)...
```
Any reason why this would occur?

**Comment by astromac** [comment]
Just realized I'm using the 2.x version. Let me upgrade to the 3.x version and see if things fix themselves before you waste time with this issue.

**Comment by thynctank** [comment]
As the error says, any time a non-array (well it says "invalid Array") object is passed in this may happen. Check an example in below screen grab.

Are you passing in a single file somehow instead of an array?

Where exactly is the error happening, can you list a particular call you're making?

![blob](https://cloud.githubusercontent.com/assets/5626/6690037/44efb984-cc94-11e4-9274-26bc1c57ee10.png)

**Comment by astromac** [comment]
I upgraded to 3.x from 2.x and the issue corrected itself which leads me to believe I wasn't resetting the model properly when you clicked the button to upload a new file.

Consider the issue closed.

**Comment by suhyunjeon** [comment]
@astromac  Hello. 
I still got a same problem with version 3.3.4. T.T

```
 {
  "name": "angular-file-upload",
  "main": "angular-file-upload.js",
  "version": "3.3.4",
  "homepage": "https://github.com/danialfarid/angular-file-upload",
  "authors": [
    "danialf <danial.farid@gmail.com>"
  ],
  "description": "Lightweight Angular JS directive to upload files. Support drag&drop, progress and abort",
  "ignore": [],
  "license": "MIT",
  "_release": "3.3.4",
  "_resolution": {
    "type": "version",
    "tag": "3.3.4",
    "commit": "b909036b1b0b61e83cba3ba16eaa951fac99c499"
  },
  "_source": "git://github.com/danialfarid/angular-file-upload-bower.git",
  "_target": "~3.3.4",
  "_originalSource": "ng-file-upload",
  "_direct": true
}
```

**Comment by danialfarid** [comment]
You are probably sending an empty array or an empty object instead of the file.

**Comment by thynctank** [comment]
I’ve updated my usage in our project to new version/naming conventions but
personally haven’t checked yet in IE. Will try to remember to do so in the
next few days!

On Monday, May 4, 2015, Danial Farid <notifications@github.com> wrote:

> You are probably sending an empty array or an empty object instead of the
> file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danialfarid/ng-file-upload/issues/627#issuecomment-98927401>
> .
>


-- 
Sent from my Mobile

**Comment by suhyunjeon** [comment]
@danialfarid  I've got object instead of the file. Not empty.
