### ISSUE TITLE
UI issues when styling with Bootstrap's btn-group-justified

### ISSUE THREAD

**Issue by seshadrik** [danialfarid/ng-file-upload#629]
I am having issues when styling (select file container) with Bootstrap's btn-group-justified. The issue is noticeable when you click cancel in the choose file dialog. Can you please take a look at http://jsfiddle.net/oftxsmbp/1/ and let me know what am I doing wrong?

**Comment by danialfarid** [comment]
What the issue is?

**Comment by seshadrik** [comment]
The button gets totally resized to almost zero width.

**Comment by danialfarid** [comment]
What browser?

**Comment by seshadrik** [comment]
I was trying it in chrome
________________________________

**Comment by danialfarid** [comment]
Fixed in version 3.3.0
