### ISSUE TITLE
Android CM Browser not working.

### ISSUE THREAD

**Issue by dragonfire1119** [danialfarid/ng-file-upload#630]
It's not working on my site http://buysellfindit.com & it's not working on the demo site either.

When you click the upload button nothing happens.

``Android version: 4.4.2``
``CM Browser: 5.1.74``
``angularjs: 1.3.8``
``ng-file-upload: 3.1.2``

Nevermind android browsers don't support file upload.

**Comment by danialfarid** [comment]
Possibily a CM browser bug.
Can you verify if a normal html form file upload works?

**Comment by dragonfire1119** [comment]
@danialfarid Thanks for the reply back I found out that the only browsers that work on android for file upload is Google Chrome, Dolphin Browser, UC Browser, Firefox, Opera & Puffin Web Browser. It's actually a android issue.

https://code.google.com/p/android/issues/detail?id=2519
