### ISSUE TITLE
hide-on-drop-not-available default state is true?

### ISSUE THREAD

**Issue by mygzi** [danialfarid/ng-file-upload#631]
Per the README, this attribute should default to false:

> hide-on-drop-not-available="true|false" // default false, hides element if file drag&drop is not supported

With IE9, the droppable div was hidden until I explicitly set the attribute to false:

```
<div class="row" ng-controller="AController" ng-file-drop ng-file-change="onFileDrop($files, $event)" hide-on-drop-not-available="false">

```

**Comment by danialfarid** [comment]
Which version?

**Comment by mygzi** [comment]
installed from bower but can no longer tell which version I have - will update to latest and see if the issue is resolved.
