### ISSUE TITLE
IE9 doesnot try resending file on 401

### ISSUE THREAD

**Issue by asadaries** [danialfarid/ng-file-upload#632]
Hi

I have a situation where i need to upload a file to server which is protected by Window authentication, everything works fine untill sometimes i get a 401 while uploading a file, and problem with IE is that it does not negotiate with server to send an authenticated request to upload file, as in chrome it retries sending file with proper authorization header and finally uploads the file. Is there any fix for this in IE9+?

**Comment by danialfarid** [comment]
Custom headers won't work in IE8-9. See the readme file old browser limitations.

**Comment by asadaries** [comment]
so is there any fix to this ?

**Comment by danialfarid** [comment]
There are workarounds. Search for similar issues here and readme file links to those.

**Comment by asadaries** [comment]
Hi, Thanks for the quick response, i have gone through the issues listed and readme file, but i couldn't get to some solution, The problem is sometime file is sent properly with a Http 200 ok response, but sometime it just return 401, then never send even if clicked again and again.
P.S i am only uploading one file at a time, and website is protected with windows authentication.

**Comment by danialfarid** [comment]
You need to send them as request parameters instead of headers or as `fields` then on the server handle them and treat them as headers you are expecting.

**Comment by danialfarid** [comment]
So you could just bypass the authentication and do the authentication manually from the request parameters being sent.

**Comment by raybarkatullah** [comment]
Hi - I'm having the same issue.  Not sure how to pass the parameters to process since IIS is throwing the 401 before the request gets to the server code.

**Comment by afhuiskes** [comment]
I've got the same issue in IE9 (with flash upload). it looks like (in my situation) the 401 occurs when i wait longer then 30 seconds to send the form. The json that's in the request is empty (Content-Length: 0) when i've waited. When i send the form directly the json is filled and a 200 returned.

**Comment by daggmano** [comment]
I seem to be getting this issue on IE11 as well, but can't pin it down enough to debug.

**Comment by danialfarid** [comment]
Please open a separate issue if you still have problems, this one is closed.

**Comment by martinoss** [comment]
Same issue here with IE 11. As an ugly workaround, doing a dummy rest-call just before upload does the trick. Still looking for a better solution.

**Comment by jesuslpm** [comment]
Same issue here with IE 11. With Windows Authentication enabled, sometimes browser sends invalid requests, it sets the content-length, but it sends an empty body. Server responds with 408 error code. Additionally, the error is not captured in angular, catch callback is not called. I'm using the same workaround as martinoss.

**Comment by KoenLuyten** [comment]
Had the same problem with IE11.

Fix for me was configuration on IIS; the providers for windows authentication should have "NTLM" as first provider.
