### ISSUE TITLE
IE9 selected file's name not displaying

### ISSUE THREAD

**Issue by hrajotia** [danialfarid/ng-file-upload#633]
Hi,
Thanks for this great library.
I Just noticed that while using this on IE9 the name of selected file won't appear near the flash 'Browse...' button.

![flash_browse_button](https://cloud.githubusercontent.com/assets/6231183/6730152/a3cf8192-ce5f-11e4-8692-d1cb64333424.PNG)

I am using below html with `angular - v1.3.14` and `angular-file-upload - v3.2.4`
```
<input type="file" name="file" ng-file-select="" ng-model="textFile"
      ng-file-change="onFileChange($files, $event)" ng-multiple="false"
      accept="*.txt,.txt">
```

**Comment by danialfarid** [comment]
Yes it wont'
Use the model object `textFile[0].name` to show the name of the selected file.

**Comment by hrajotia** [comment]
Yeah I could do that as an alternative, but there is a blank textbox and the name or path of selected file suppose to be there, also from UI/UX perspective it may look odd if I put the name separately and the empty textbox still consuming space on screen.

what do you think?

**Comment by danialfarid** [comment]
Style the button like the demo page, or if you really want it to be on the button itself style the name over it.

**Comment by hrajotia** [comment]
So anyways it won't possible to show the name/path within the textbox. I'll make change at my end accordingly.

Thanks for suggestions and quick response.
