### ISSUE TITLE
File-select from controller

### ISSUE THREAD

**Issue by toksfifo** [danialfarid/ng-file-upload#634]
Hi,

Is there any way of prompting for file selection from a controller?

I tried `$('.class-of-ng-file-upload').trigger('click')` (using jQuery), but that doesn't seem to work on the element, even though it works fine on other elements on the page.

Thanks,

**Comment by danialfarid** [comment]
Can you create a jsfiddle.

**Comment by toksfifo** [comment]
Let me know if this gets the point across: http://jsfiddle.net/nmdcwf3w/342/

**Comment by danialfarid** [comment]
For security reasons you cannot click on file input programmatically.
