### ISSUE TITLE
I have two questions ,first one , the ng-multiple="true" directive does not work ,second one ,how could i get the name of selected file 

### ISSUE THREAD

**Issue by xiaoliuliu2050** [danialfarid/ng-file-upload#638]
I use it to  the ionic android project,

first ,I include the three js files used to upload my file  
  angular.min.js
 angular-file-upload-shim.min.js
 angular-file-upload.min.js

second ,i rewrite the app.js 
angular.module('starter', ['ngRoute','angularFileUpload','starter.services','ionic','angular-gestures'])
as you can see, i put the angularFileUpload module in it.

then  i write the controller 

 .controller('upLoadController',['$scope', '$upload', function ($scope, $upload)   {
     $scope.upload = function (files) {
            window.alert("upload2");
            if (files && files.length) {
                for (var i = 0; i < files.length; i++) {
                    var file = files[i];
                    // upload file code ...........
                }
            }
        };
}) 

finally it is the page 

body  ng-controller="upLoadController">
                ng-file-select ng-model="files"   ng-file-change="upload($files)" ng-multiple="true">xx</ng-file-select>
 /body>

the code above ,i delete the first <  symbol, you add the symbol < and then it is the right code .
i do this because the right can not show correctly in the preview module.
 
as a result ,now i could upload the file to my server correctly ,
but  i  can not select two pictures at the same time . it means that the ng-multiple="true" directive does not work ,

and another question is that ,i want to show the image on the page right now when i select it.
how could i do ?

best wishes !

**Comment by danialfarid** [comment]
The demo page shows the picture.
See the demo code and it also allows multiple file upload so you could have a look how it is set up.
