### ISSUE TITLE
ng-file-upload issue in IE

### ISSUE THREAD

**Issue by Achyuth-India** [danialfarid/ng-file-upload#639]
Hi,
I use Angularjs ng-file-upload to upload data to a Node Server based back-end.

I use the following code to upload my file.

$upload.upload({

        url: my-upload/URL',
        method: 'POST',
        headers: {
          'Content-Type': 'text/csv'
        },

        data: data,
        fields: data,
        file: file
      })
      .success(function(response) {
        de.resolve(response);
      }).error(function(err) {
        de.reject(err);
      });

On the node server, I am trying to get the request parameters as following,

__req.param(param)__

Its works fine for me in Chrome browser. But in IE11 I didn't receive any data/params on request body send from front end function, but the request header seems to be fine.

Please suggest me some solution. Thanks in advance.

**Comment by danialfarid** [comment]
remove 
```
    headers: {
      'Content-Type': 'text/csv'
    },
```
