### ISSUE TITLE
ng-accept or accept break ng-file-change 

### ISSUE THREAD

**Issue by stevenbarragan** [danialfarid/ng-file-upload#641]
I have this code
```javascript
<button class="csv-upload-button" ng-file-select ng-accept="'.csv'" ng-file-change="importBatches($files)">
  <i class="fa fa-lg fa-cloud-upload"></i> Import Tracking Numbers
</button>
```

It doesn't fire ``ng-file-change`` event, but I notice if I get rid of the ``ng-accept`` tag it works, it doesn't work even with only the ``accept`` tag.

am I missing something?

I think it could be related to https://github.com/danialfarid/ng-file-upload/issues/609

**Comment by danialfarid** [comment]
Your selected files are probably rejected by ng-accept.
add 'ng-file-change="importBatches($files, $rejectedFiles)"' and see if the file is in the rejected files.
