### ISSUE TITLE
i want to know how to transform the dom file object to the file object which can be submitted to server

### ISSUE THREAD

**Issue by xiaoliuliu2050** [danialfarid/ng-file-upload#642]
maybe ,you do not understand me,
that is ok ,
i will say it in detail ,
for example

<
input type="file" id="file1" />
var fileobj=document.getElementById("file1");
here is the dom file object.

but when pass the file to server ,we use the file parameter which is not the dom object.
but another object which contails file type ,file size ,and file name.

var files=[];

$upload.upload({
url: 'http://www.baidu.com/',
fields: {
'name': $scope.thegood.name
},
file: files
})

now i want to know how to transfrom the dom file object to the needed file object.

**Comment by danialfarid** [comment]
You can pass the other properties of the file using fields the same way you are sending the name.
```
$upload.upload({
url: 'http://www.baidu.com/',
fields: {
'name': $scope.thegood.name,
'type':$scope.thegood.type,
'size':$scope.thegood.size,
},
file: files
})
```

and then on the server handle that.
