### ISSUE TITLE
How do I send an array along with data.

### ISSUE THREAD

**Issue by neilhanekom** [danialfarid/ng-file-upload#644]
I have an array of created in my controller. How do I send that along with files and filed to the server.

**Comment by recurrence** [comment]
Add to formDataAppender

**Comment by danialfarid** [comment]
`$upload.upload({..., fields: {myArray: [1,2,3], ...});`

**Comment by raphaelyancey** [comment]
Hi Danial. It doesn't work with an array of objects, it's sent as a string.
`families: '[{"name":"Test","parent":"TesTest"}]' }` as logged by my Node.js uploading script.

**Comment by danialfarid** [comment]
try $upload.upload({..., data: {myArray: [1,2,3], ...}) and on the server grab `data.myArray` object,

**Comment by raphaelyancey** [comment]
Thank you Danial. I managed to send each item of the array in a`array[]` FormData field like this:

([`angular-file-upload.js` line 156](https://github.com/danialfarid/ng-file-upload/blob/master/dist/angular-file-upload.js#L150))
```
else if(angular.isArray(val)) {
     for(i = 0; i < val.length; i++)
        formData.append(key+'[]', JSON.stringify(val[i]));
}
```

And then, in the backend script, I do a `JSON.parse()` for each item of this array to get the objects.

**Comment by danialfarid** [comment]
Using `data` might make it easier since it would send it as `application/json` content-type.

**Comment by johnlim5847** [comment]
@danialfarid  hi, i have tried your suggestion by using `data` and grab it on the server side however the it still parse as a string like field. may i know is there any possible solution for this problem ? 

```Javascript
  var data  = $scope.dealsData;
  Upload.upload({
                  url: '/api/postDeals',
                  fields:data,
                  data:{favour:$scope.choices},
                  file: file
              }
```

in my nodejs console 

```javascript
{ deals_name: 'ad',
  deals_price: '12.12',
  deals_amount: '12',
  deals_description: 'asd',
  deals_term_condition: 'asd',
  favour_type: 'survey',
  data: '{"favour":[{"type":"mcq","$$hashKey":"object:67","mcq_question":"asd","mcq_choice1":"asd","mcq_choice2":"asd"},{"type":"open_ended","$$hashKey":"object:68","open_ended_question":"asd"}]}' }
```
if i do it the usual way i don't have the $$hashkey or object:6x thingy in my json 

```Javascript
$scope.dealsData.favour =  angular.toJson($scope.choices);
var data  = $scope.dealsData;
  Upload.upload({
                  url: '/api/postDeals',
                  fields:data,
                  data:{favour:$scope.choices},
                  file: file
              }
```
in my nodejs console 
```Javascript
{ deals_name: 'asd',
  deals_price: '12.12',
  deals_amount: '12',
  deals_description: 'asd',
  deals_term_condition: 'asd',
  favour_type: 'survey',
  favour: '[{"type":"mcq","mcq_question":"asd","mcq_choice1":"asd","mcq_choice2":"asd"},{"type":"open_ended","open_ended_question":"asd"}]' }
```

**Comment by danialfarid** [comment]
Use: 
```
map of extra form data fields to send along with file. each field will be sent as a form field.
  The values are converted to json string or jsob blob or nested form depending on 'sendFieldsAs' option. */
  fields: {key: $scope.myValue, ...},
  /*
  default is 'json', sends each field as json string plain text content type, 'json-blob' sends object fields 
  as a blob object with content type 'application/json', 'form' sends fields as nested form fields. see #784 */
  sendFieldsAs: json|json-blob|form,
```

**Comment by joshbedo** [comment]
@danialfarid Is their any way to send data not stringified? Still a little confused.

**Comment by danialfarid** [comment]
how does your data look like?

**Comment by joshbedo** [comment]
So i'm passing a plain old javascript object like
`{ type: 'displayImage' }`

but the server receives this... which i can't comprehend why you would ever want to send a stringified object instead of the object. This  is annoying when multiple clients use your API and you have to do something on mobile because a web plugin does it.

`'{ "type": "displayImage" }'`

**Comment by danialfarid** [comment]
Post your code here, it is not clear how you are using the upload service,
