### ISSUE TITLE
Issues with controllerAs syntax

### ISSUE THREAD

**Issue by joshikeerti** [danialfarid/ng-file-upload#645]
I am using Angular ver 1.3.15 and using controllerAs syntax for my controllers, however if I use the controllerAs syntax for the upload controller, it breaks. 
When I switched back to not using controllerAs it works ok. 
Is this not compatible with the latest version of angular or does not support controllerAs?

**Comment by danialfarid** [comment]
Can you create a jsfiddle showing the error? What is breaking? any error message?
