### ISSUE TITLE
Issues with deleting/re-uploading an image

### ISSUE THREAD

**Issue by jhoniemartinez** [danialfarid/ng-file-upload#646]
I have been experiencing issues with re-uploading images after I have deleted them. Here are the steps I've taken:

1. Upload an image with the hypothetical name image1.jpeg

2. Delete image1.jpeg in my application (the application does not know or care about this name)

3. Attempt to re-upload image1.jpeg without refreshing my browser 

4. The upload window appears, I am able to select image1.jpeg and click continue, the window disappears and nothing happens
- I have tried placing log messages throughout the $upload directive to see if anything is being fired, but it is as if the directive is not being called at all 

Side note: I tried renaming multiple images image1.jpeg and they all experienced the same problem. Which has lead me to determine this is a file name related issue.

Thank you in advance!

**Comment by danialfarid** [comment]
What version of the plugin are you using? Can you reproduce it on the demo page?

**Comment by jhoniemartinez** [comment]
Hi Danial,

We are using v 1.6.12 - I have posted a video to the demo page. Please let
me know if you did not receive it.

Thanks,
Jhonie

On Sat, Apr 11, 2015 at 8:08 PM, Danial Farid <notifications@github.com>
wrote:

> What version of the plugin are you using? Can you reproduce it on the demo
> page?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danialfarid/ng-file-upload/issues/646#issuecomment-91976004>
> .
>



-- 
*JHONIE MARTINEZ | Web Engineer*
 (559) 213 - 2596
 jhonie@enplug.com

[image: Enplug, Inc.] <http://www.enplug.com/>

Public Computing Platform ™
<https://twitter.com/enplug> <https://www.facebook.com/Enplug>
<http://instagram.com/enplug/>
<https://www.linkedin.com/company/enplug-inc.> <https://github.com/Enplug>
<https://www.quora.com/Enplug>
------------------------------
NOTICE: This email may contain information that is confidential or
privileged and may constitute inside information or trade secrets. The
contents of this email are intended only for the recipient(s) listed above.
If you are not the intended recipient, you are directed not to read,
disclose, distribute or otherwise use this transmission. If you have
received this email in error, please notify the sender immediately and
delete the transmission. Delivery of this message is not intended to waive
any applicable privileges. Have a nice day.

**Comment by danialfarid** [comment]
Use the latest version
