### ISSUE TITLE
progress callback only returns 100%, progress is not updated in .NET

### ISSUE THREAD

**Issue by imperat0r** [danialfarid/ng-file-upload#648]
It seems progress is only reported when file is uploaded, If  console.log progress I get 100% only, never 5%,10%...Backend is ASP.NET web api. angular version 1.3.19

**Comment by danialfarid** [comment]
You might need to configure your server to report progress event.

**Comment by danialfarid** [comment]
If the same code you have is working when uploading to http://angular-file-upload-cors-srv.appspot.com/upload then it is a server issue.

**Comment by robotnoises** [comment]
@imperat0r Have you included the shim? We were experiencing the same issue and found that including the shim fixed it.
