### ISSUE TITLE
Protractor test support

### ISSUE THREAD

**Issue by anilapu** [danialfarid/ng-file-upload#653]
I have to select file without open dialog or with open dialog support for protractor test cases.
Usually, selenium send keys (file path) to model is not working

![code](https://cloud.githubusercontent.com/assets/9476474/6936685/72a4959a-d872-11e4-810a-0182a1e10366.png)

<pre> it('upload file', function(){   
      var fileToUpload = 'C:/Users/Cronj-4/Desktop/demo.csv';
      var absolutePath = path.resolve(fileToUpload);
      $('input[type="file"]').sendKeys(absolutePath);
      browser.sleep(500);
 });
</pre>

![testcase](https://cloud.githubusercontent.com/assets/9476474/6958049/8c4f339a-d923-11e4-9888-9bd6ffb2ad97.png)

This code is trying to upload but file is saving in rejfiles model even though it is valid file.
Could any one help me out?

**Comment by danialfarid** [comment]
What kind of file are you uploading? Would it work if you change the accept to image/* and upload an image?

**Comment by anilapu** [comment]
It worked when i have changed ng-accept = "*.csv"
