### ISSUE TITLE
Upgrading to version ^3.2. Doesn't work with S3

### ISSUE THREAD

**Issue by TomerAvni** [danialfarid/ng-file-upload#654]
When upgrading to 3.2.4 I've experienced BAD REQUEST from S3:
<Error><Code>InvalidArgument</Code><Message>Bucket POST must contain a field named 'key'.  If it is specified, please check the order of the fields.

Downgrading to 2.2.2 Solved it.

**Comment by danialfarid** [comment]
You should use 'fields' instead of 'data' in your config `$upload.upload({fields:...})`

**Comment by danialfarid** [comment]
I assume changing data to fields solved the problem for version 3.2.4. If not please reopen.
