### ISSUE TITLE
Needs a Fileprovider to play with headers

### ISSUE THREAD

**Issue by mohghaderi** [danialfarid/ng-file-upload#655]
When uploading on Amazon S3, we need to remove headers to make it work. I used to have this code for JQuery fileupload, but couldn't find anything here:

app.config([
        '$httpProvider', 'fileUploadProvider',
        function ($httpProvider, fileUploadProvider) {
            delete $httpProvider.defaults.headers.common['X-Requested-With'];
	}
])

**Comment by danialfarid** [comment]
The code uses angular $http underneath so however you could remove headers in angular $http() you can do the same for $upload.upload().
