### ISSUE TITLE
Not working if type="button"

### ISSUE THREAD

**Issue by Bartosh-s** [danialfarid/ng-file-upload#657]
`<button  ng-file-select ng-model="files">working</button>`
`<button type="button"  ng-file-select ng-model="files">NOT working</button>`

**Comment by Frank3K** [comment]
See #628. Fixed in v3.2.5.

**Comment by recurrence** [comment]
@danialfarid Can you set the version label for 3.2.5?   Otherwise, one can fork and add their own but then they have to track their fork :)

**Comment by danialfarid** [comment]
@Bartosh-s What version are you using?
It works fine for both on the demo page.

**Comment by Frank3K** [comment]
@danialfarid We're using the latest version in bower, i.e. 3.2.4. [That version](https://github.com/danialfarid/ng-file-upload/blob/9479a5db448bba77ff29f38747edd0fe7d3df5cc/dist/angular-file-upload.js#L244-L247) contains a for-loop in `createFileInput` that is not filtering for `type` attributes.

PR #628 fixes the issue, but that version is not tagged yet and thus not available on bower.

**Comment by danialfarid** [comment]
Fixed in version 3.3.0
