### ISSUE TITLE
ng-accept does not work with comma separated wildcard and multiple files

### ISSUE THREAD

**Issue by swege** [danialfarid/ng-file-upload#658]
According to the docs, ng-accept accepts a comma separated list of file extensions:

    ng-accept="'.pdf,.jpg'|validate($file)" // function or comma separated wildcard to filter files allowed

It does work, but using this syntax does not allow multiple file uploads anymore. Steps to reproduce:

 * Go to https://angular-file-upload.appspot.com/
 * In the "Play with attributes" section, enable `ng-multiple`
 * As `ng-accept` value, enter `.jpg,.png`
 * Drag and drop multiple files into the box. It will only upload one of them, the other ones are not even displayed as “rejected”. The filter rule itself is working (only `png` and `jpg` allowed).

Tested with `Chromium Version 41.0.2272.76 Ubuntu 14.04 (64-bit)` and `Firefox 37.0`

**Comment by danialfarid** [comment]
you meed to set ng-multiple to true.

**Comment by swege** [comment]
I did checked that box, see step 2 in my list. Just changing the ng-accept value back to "image/*" makes it work again.

**Comment by danialfarid** [comment]
Fixed in version 3.3.0

**Comment by gottfrois** [comment]
It's working for drag and drop but not when selecting files from the input button. Looking at the web console there is a parse error showing up: http://jsfiddle.net/mut7cevm/1/

**Comment by danialfarid** [comment]
`ng-accept="'.txt'"`

**Comment by gottfrois** [comment]
oh man sorry about that
