### ISSUE TITLE
IE9 javascript error

### ISSUE THREAD

**Issue by maleblond** [danialfarid/ng-file-upload#660]
In IE9, I get the following error when choosing a file from the file explorer: 

Unable to get value of the property 'length': object is null or undefined
angular-file-upload.js?body=1, line 210 character 29

However, everything work fine in IE10 and chrome. I haven't tested other browsers.

Also, drag and drop doesn't work and FileAPI.flash.swf + FileAPI.min.js are never loaded by the browser, even if they are in the same directory as angular-file-upload.js file.

Any idea how to solve this?

**Comment by danialfarid** [comment]
You are probably in compatibility mode or have another library that defines FormData object for IE9.

**Comment by ukupat** [comment]
I had the same issue when using `angular-file-upload.js`. Switching to `angular-file-upload-all.js` solved the issue for me.

**Comment by maleblond** [comment]
The problem was on my side. Path to FileAPI.min.js / FileAPI.flash.swf was wrong.
