### ISSUE TITLE
 select file ， click cancel button. Once again pop select file 

### ISSUE THREAD

**Issue by cnlinjie** [danialfarid/ng-file-upload#663]
sorry!
my english is poor.
select file ， click cancel button. Once again pop select file .
code copy Sample!

**Comment by jmendozais** [comment]
I have the same problem. I created a input-file element with ng-file-select. The first use works well, I mean, I select the file to upload, and it is submitted successfully. On the second use, the ng-file-select function is called before I have selected a file.

**Comment by danialfarid** [comment]
@jmendozais second time you click, it would empty the previous value so it will be called with empty files and this is expected behaviour.

@cnlinjie can you create a jsfiddle showing this error? You can use the jsfiddle sample on the readme file.

**Comment by cnlinjie** [comment]
@danialfarid Thanks. I went to the test。

**Comment by slavinskas** [comment]
I have the same issue with Angular 1.3.15 and ng-file-upload 3.3.1. When I click on ng-file-select element and choose file or cancel, another upload window immediately pops up.

    <div accept="'image/*'"
            ng-file-select
            ng-file-change="vm.onFileSelect($files, $event)"
            ng-multiple="false" allow-dir="false"></div>

**Comment by danialfarid** [comment]
which browser? can you create a jsfiddle?

**Comment by cnlinjie** [comment]
@slavinskas  Y。 I use Angular 1.3.15  。
@danialfarid  Chrome 39.0.2171.95 (64-bit)  For Fedora 20

**Comment by cnlinjie** [comment]
@danialfarid  jsfiddle  only have Angular 1.2 ,
  I try upload 1.3.15 ！

**Comment by danialfarid** [comment]
It is probably not from angular version, the demo page works with 1.3.15.

**Comment by ilbarzo** [comment]
I have the same issue, Chrome 42.0.2311.90 m on Win 7 64, angular 1.3.14, ng-file-upload 3.3.1.
here my code:
```html
<div class="upload-button-zone" ng-file-select ng-model="attachFile" ng-multiple="false" ng-file-change="fileSelected($files, $event)">
<a class="js-file-upload-button button button-upload">
<span class="button-icon fa fa-plus"></span> Seleziona file
</a>dal tuo computer.
</div>
```
```javascript
$scope.fileSelected = function(files, event) {
        console.log(files)
        if (files != null && files.length == 1) {
            console.log(files[0])
            $scope.uploadFile(files[0]);
        }
    };
```
when click first time open file window, then if I select file or click cancel reopen window, on second window if I select file it works.
best regards

**Comment by ilbarzo** [comment]
it seem that $scope.fileSelected is fired two times, because on first click I have two console entry ([] []).
I have created a [jsfiddle](http://jsfiddle.net/9wweb50x/) with only this part of code and it works, so it is something in my page/scope, but I dont understand what!!

**Comment by cnlinjie** [comment]
@danialfarid  Hi. I use $ocLazyLoad , can have issue. 
else  , at index.html  cite js file , no problem.
sorry , english very poor!

**Comment by ilbarzo** [comment]
also for me the problem was $ocLazyLoad, without it (including ng-file-upload as usual) all works fine.
@danialfarid can you check if there is some problem using [$ocLazyLoad](https://github.com/ocombe/ocLazyLoad)?
best regards

**Comment by danialfarid** [comment]
If the issue still exists please specify the plugin version and browser version
