### ISSUE TITLE
Assign single value to `ng-model` when `multiple="false"`

### ISSUE THREAD

**Issue by marshall007** [danialfarid/ng-file-upload#665]
In cases where `ng-multiple` is explicitly set to false, it would be nice if the value assigned to `ng-model` were just the single file object rather than an array so that we don't have to pull out the first element ourselves.

I'll submit a PR if you're ok with introducing this behavior.

**Comment by danialfarid** [comment]
What if you want to have dynamic ng-multiple. Then you have to handle the selected files result differently. It's kind of a bit of inconvenient either way.

**Comment by danialfarid** [comment]
This is the default since newer version 6+
