### ISSUE TITLE
how to hook file open dialog cancel or close event

### ISSUE THREAD

**Issue by CleanCoder** [danialfarid/ng-file-upload#666]
Is there any callback once user cancel or close the file open dialog? If so, how? I need such notification, so I can reject a promise after user click the 'cancel' button in the file open dialog. Thanks in advance.

**Comment by danialfarid** [comment]
There is no easy/crossbrowser way to detect that. The plugin fires a change event when the user click on the button and set the file value to empty to handle this case, so when the user cancels the popup the file is already set to empty.
