### ISSUE TITLE
file url to server

### ISSUE THREAD

**Issue by CrackerakiUA** [danialfarid/ng-file-upload#669]
When i have my file inside input file it's working, but now i have something like this:
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAYAAACtWK6eAAAgAElEQVR4XkS92bOl13net/Y8nbHnCY0GQBCQRGuyKZdKlCNFFAeJlhiaEodSLpgq5yY3+Y9ykVz5xr7xjVyux ... and 100 more lines of hash.
How can i upload it to server? I am using crop tool which save cropped image inside this kind of url (showing in tag img)

**Comment by danialfarid** [comment]
Convert it to Blob: http://stackoverflow.com/questions/12168909/blob-from-dataurl
and set it as file for $upload.upload()

**Comment by CrackerakiUA** [comment]
Thanks allot
