### ISSUE TITLE
Bower downloads version 3.0.0 when setting bower.json to 3.3.1

### ISSUE THREAD

**Issue by kasperbaago** [danialfarid/ng-file-upload#670]
When running ``bower install ng-file-upload``, it downloads version 3.0.0 of the js files, even when the ``.bower`` file says version 3.3.1

Has the new version 3.3.1 version of the code not been submitted to bower or how can this happen?
Anyone else having this problem?

When you search on the package on http://bower.io/search/?q=ng-file-upload, it returns nothing... :(

**Comment by danialfarid** [comment]
That was just a typo in the version number in the release, the files are be version 3.3.1.
Anyway it is fixed in 3.3.2
