### ISSUE TITLE
PUT method does not support 'data' param config for $upload.upload() method

### ISSUE THREAD

**Issue by james-hoegerl** [danialfarid/ng-file-upload#672]
Is this standard html request or did I do something wrong. 

Using Laravel this lets me see the 'data' sent with the reuqest

 $scope.uploadImageFile = function(){
        $scope.loading = true;
        $scope.FileLoading = true;
        $upload.upload({
            data: {Value: "File"},
            url: '/setting/logo',
            method: 'POST',
            file: $scope.newImageFile,
            fileFormDataName: "setting"
        });
    }

And this doesnt

 $scope.uploadImageFile = function(){
        $scope.loading = true;
        $scope.FileLoading = true;
        $upload.upload({
            data: {Value: "File"},
            url: '/setting/logo',
            method: 'PUT',
            file: $scope.newImageFile,
            fileFormDataName: "setting"
        });
    }

**Comment by danialfarid** [comment]
http://stackoverflow.com/questions/25387166/laravel-doesnt-read-http-request-payload-for-put-request
