### ISSUE TITLE
ng-file-select directive broken on IE8 since 3.3.*

### ISSUE THREAD

**Issue by rdubigny** [danialfarid/ng-file-upload#673]
On hover on this element with v3.3.*

    <div ng-file-select ng-file-change="onFileSelect($files)"></div>

Application crashes with a "mismatch" error on IE8.

It's ok with version 3.2.4 though.

**Comment by danialfarid** [comment]
try with latest version.

**Comment by rdubigny** [comment]
Still not working sry. It crashes at "e.detachEvent("on"+t,n)" with t="change" and n=undefined

**Comment by danialfarid** [comment]
Are you sure you are not in compatibility mode and have flash installed?

**Comment by rdubigny** [comment]
Sry, I just notice that from the begging I wrote 2.2 & 2.3 instead of 3.2 & 3.3 . I just updated the title of the issue.

**Comment by acourtiol** [comment]
:+1: I'm getting the same issue using ng-file-upload v3.3.x and IE 8-11

**Comment by rdubigny** [comment]
I just double checked the issue: 
- flash is installed & not in compatibility mode
- update to FileAPI 2.0.10 (=> your FileAPI version doesn't seem to exist on the [original repo](https://github.com/mailru/FileAPI/blob/master/dist/FileAPI.min.js)
- angular-file-upload.shim to 3.3.3 
- ng-file-upload to 3.3.3
Seems to work now. 

@acourtiol maybe this issue can be closed ?

Note that I encounter issue using [aight](https://github.com/shawnbot/aight), the upload is not triggered.

**Comment by rdubigny** [comment]
Eventually, it seems to work with your 2.0.7 version of FileAPI.

**Comment by danialfarid** [comment]
You should use the version of the FileAPI that comes with this plugin since there are some issues that are only fixed in those files.

**Comment by danialfarid** [comment]
If the problem still exists with the latest version reopen this.
