### ISSUE TITLE
Having issues uploading files using IE9

### ISSUE THREAD

**Issue by asabla** [danialfarid/ng-file-upload#674]
I'm not sure if this is a bug or just me doing it wrong, so please correct me if I'm wrong.

We're using this plugin as a primary source for uploading files and it's been working really well until now, IE9 is having some issues when selecting a file/s to upload. At a first glance on what could be wrong, we're experiencing two different file pickers (see attached files bellow) depending if it's first load of the page or not. If it's the first then the first picker will be displayed, and every other time it will be the second one.

![plugin-stuff](https://cloud.githubusercontent.com/assets/1063362/7180058/23a5bb22-e43e-11e4-8e7c-89b8c7bb8e73.png)

![plugin-stuff2](https://cloud.githubusercontent.com/assets/1063362/7180057/23a5beba-e43e-11e4-8d50-ed2ce5dbe7ad.png)

The problem will only occur with the second file picker, were no file name will be displayed or even picked up by the model. In angular-file-upload-shim.js in the function: "changeFnWrapper" i can see the file being picked up by the event (with all the information), so flash is not the problem.

This is what it looks like in our view:
`<input type="file" ng-file-select="fileDetails.onFileSelected($files)" />`

In the controller:
`
$scope.selectedFile = null;
    $scope.onFileSelected = function ($files) {
      $scope.selectedFile = $files[0];
      //console.log($files)
    };
`

So what am I doing wrong?

**Comment by danialfarid** [comment]
Try using the latest version of the plugin. There was some issues with the mouseenter event which is fixed in the latest version.

**Comment by asabla** [comment]
Thank you for the suggestion. I will give a try this or the next week and will resubmit my result
