### ISSUE TITLE
Upload on file change doesn't work as expected

### ISSUE THREAD

**Issue by alphatwit** [danialfarid/ng-file-upload#675]
Choosing a file with the "watching model:" option adds the filename to the list at the bottom, however the "on file change:" option doesn't seem to do the same.

http://jsfiddle.net/nmdcwf3w/

(Using Chrome v41.0.2272.101 )

**Comment by danialfarid** [comment]
because on file change doesn't set the model value, it just uploads the selected files without setting the model value. and what you see the the bottom is the model value.
