### ISSUE TITLE
File API Shim does not work within a UI Bootstrap Modal

### ISSUE THREAD

**Issue by Oceanswave** [danialfarid/ng-file-upload#676]
Finally repro'd this in a jsfiddle:

https://jsfiddle.net/nmdcwf3w/511/

**Comment by Oceanswave** [comment]
Doesn't seem to work with the jQuery hack.

https://jsfiddle.net/nmdcwf3w/513/

**Comment by danialfarid** [comment]
Fixed in version 3.3.3

**Comment by Oceanswave** [comment]
Well that fix was over 9000!! :o) Thanks!
