### ISSUE TITLE
image preview

### ISSUE THREAD

**Issue by gogliko** [danialfarid/ng-file-upload#678]
how add image preview ?

**Comment by Banananan** [comment]
E.g. by use of custom directive:
angular.module('app')
    .directive('thumbnail', ['$window', function ($window) {
        return {
            restrict: 'A',
            template: '<canvas/>',
            link: function (scope, element, attributes) {
                function onLoadFile(event) {
                    var img = new Image();
                    img.onload = onLoadImage;
                    img.src = event.target.result;
                }
                function onLoadImage() {
                    var width = params.width || this.width / this.height * params.height;
                    var height = params.height || this.height / this.width * params.width;
                    canvas.attr({width: width, height: height});
                    canvas[0].getContext('2d').drawImage(this, 0, 0, width, height);
                }
                var params = scope.$eval(attributes.thumbnail);
                var canvas = element.find('canvas');
                var reader = new FileReader();
                reader.onload = onLoadFile;
                reader.readAsDataURL(params.file);
            }
        };
    }]);

and then in your HTML file:
<div>
    <ul>
        <li ng-repeat="image in images">
            <img width="100px" height="100px" ng-src="{{ image.address }}" alt="{{ image.description }}"/>
        </li>
    </ul>
</div>

**Comment by nfantone** [comment]
@Banananan You are declaring a `thumbnail` directive but not using it anywhere in your template.

**Comment by danialfarid** [comment]
@Banananan  that's a good idea, I would add it to the next version to have a directive like `thumbnail="dataUrls"` which would assign the selected files dataURLs to the model.

**Comment by Banananan** [comment]
@nfantone, yeah, you're right. Here's example:
'''
<div ng-repeat="image in images">
    <div thumbnail="{ file: image }"></div>
</div>
'''

**Comment by mvarrieur** [comment]
````
var width = params.width || this.width / this.height * params.height;
var height = params.height || this.height / this.width * params.width;
````

On these two lines I had to use `this.width` and `this.height` directly as `params.width` and `params.height` didn't exist and threw an error.

Any idea how this could be adapted to be used when it falls back to the Flash uploader (if it's even possible?) When this falls back to the flash uploader it fails on this line:
````
reader.readAsDataUrl(params.file);
````
because params.file is not a blob.

**Comment by danialfarid** [comment]
`params.file[0]`?

**Comment by mvarrieur** [comment]
That doesn't work either...here's how  `params.file` looks when forcing the flash fallback:

![screenshot 2015-04-21 08 34 25](https://cloud.githubusercontent.com/assets/1863155/7252253/42851a6c-e801-11e4-9f93-ef09b1cc2b57.png)


It's not a big deal I modified it to only show a preview now when it is using the native HTML5 viewer. But just something to keep in mind if you do end up using some kind of directive like this in the project.

**Comment by omarqx** [comment]
Try this directive

    'use strict';
    angular.module('app').directive('thumbnail', function () {
    return {
        restrict: 'E',
        replace:true,
        template: '<img src="" height="63" width="73" style="margin-right: 15px;" class="img-rounded"/>',
        link: function (scope, element, attributes) {
            var preview = element[0];
            var files = scope.$eval(attributes.file);
            var file = files.file[0];
            var reader  = new FileReader();

            reader.onloadend = function () {
                preview.src = reader.result;
            };

            if (file) {
                reader.readAsDataURL(file);
            } else {
                preview.src = "";
            }
        }
    };
    });

**Comment by gogliko** [comment]
@Banananan  http://prntscr.com/6xxp70 no't working .

**Comment by danialfarid** [comment]
Added feature in version 4.0.x. You can use `<img ngf-thumbnail="files[0]" class="thumb">`.

**Comment by trd** [comment]
Is this feature still available? ngf-thumbnail. I can't see any documentation about it.

**Comment by danialfarid** [comment]
@trd use `<img ngf-src` or `<div ngf-background` instead

**Comment by trd** [comment]
The problem is that the browser crashes if there are many big images. A thumbnail would be very useful.

**Comment by danialfarid** [comment]
Added ngf-thumbnail to version 7.3.0

**Comment by trd** [comment]
Thank you very much!

**Comment by Overflow012** [comment]
Hello!
I have the below code:
```
            <div ng-repeat="file in files">
                <div class="col-sm-6 col-md-3">
                        <img ngf-thumbnail="file" class="thumb">
                        <div class="progress" ng-show="file.progress >= 0">
                            <div class="progress-bar" style="width:{{file.progress}}%"  
                                 ng-bind="file.progress + '%'"></div>
                        </div>
                </div>
            </div>
```

The thumbnail size is equal than the original image. What am I doing wrong?

**Comment by danialfarid** [comment]
set a css size for your img element.

**Comment by Overflow012** [comment]
So I don't understand what is the purpose of ngf-thumbnail. I think that should show small image preview.

**Comment by danialfarid** [comment]
It depends on how small you want to show it.

**Comment by emranch31** [comment]
ngthumb is not previewing image file over 15mb 
how to fix it ???

**Comment by danialfarid** [comment]
@emranch31 try ngf-src instead

**Comment by simonepri** [comment]
@danialfarid It will be usefull to bind the file reader **onload** event when ngf-src and -ngf-thumbnail are used.
For exemple we can add something like ngf-src-onload and ngf-thumbnail-onload. This will allow for exmple to add spinner icon while the file is loading and then remove it when one of that callback is called.
What you think about that?

**Comment by r4nc1d** [comment]
@danialfarid is there a way to return the full image path after it was selected?

**Comment by danialfarid** [comment]
@r4nc1d full path is not provided by the browser because of security reasons.
@simonepri the feature is gonna be available in angular2 and will be ported back to angular 1 at some point. For now you can use `ngf-before-model-change` on the file select/drop to know when the files are selected and the thumbnail processing begins.

**Comment by suhail1805** [comment]
Unable to show Image preview of JPEG file using **ngf-src**
