### ISSUE TITLE
Missing "ignore" entry in bower.json

### ISSUE THREAD

**Issue by AaronBuxbaum** [danialfarid/ng-file-upload#681]
When including `ng-file-upload` from bower, the following warning is thrown:

`bower ng-file-upload#~3.2.4       invalid-meta angular-file-upload is missing "ignore" entry in bower.json`

While this obviously doesn't break anything, it'd be easy to include an empty `ignore` entry to avoid the warning being thrown. Should only take a minute to fix it!

**Comment by danialfarid** [comment]
Fixed in version 3.3.4
