### ISSUE TITLE
Upload queue

### ISSUE THREAD

**Issue by luis-elumen** [danialfarid/ng-file-upload#683]
Is there a way to use an upload queue??

**Comment by danialfarid** [comment]
Yes you can upload selected files in any order or any time you want.

**Comment by LennyLip** [comment]
@danialfarid  can you give some example how to determine, that all files has been loaded?

     for (var i = 0; i < files.length; i++) {
                var file = files[i];
                Upload.upload({
                     url: 'upload/url',
                    fields: {'username': $scope.username},
                    file: file
                }).success(function (data, status, headers, config) {
                    console.log('file ' + config.file.name + 'uploaded. Response: ' + data);
     }

we must use promises or we must not use for() ?
thanks.

**Comment by danialfarid** [comment]
```
var counter = 0;
Upload.upload({})
.finally(function(...) {
    counter++;
    if (counter === files.length) {
         all file uploads are completed.
    }
})
```

**Comment by LennyLip** [comment]
@danialfarid many thanks! I was thinking something like this..
