### ISSUE TITLE
"415 unsupported media type" when uploading file

### ISSUE THREAD

**Issue by dimitrilahaye** [danialfarid/ng-file-upload#688]
Hello there ! I've a 415 error code when I upload a file.
"415 unsupported media type".
Here's my code on my Controller.
Do you have any idea ?

```javascript
		$scope.$watch('files', function(files) {
			$scope.formUpload = false;
			if (files != null) {
				for (var i = 0; i < files.length; i++) {
					$scope.errorMsg = null;
					(function(file) {
						uploadFileReprise(file);
					})(files[i]);
				}
			}
		});
		
		$scope.uploadPic = function(files) {
			$scope.formUpload = true;
			if (files != null) {
				uploadFileReprise(files[0]);
			}
		};
function uploadFileReprise(file) {
			$scope.errorMsg = null;
			uploadUsing$http(file);
		};

		function uploadUsing$http(file) {
			file.upload = $upload.http({
				url:/*my_url*/
				method: 'POST',
				headers: {
					'Content-Type': '*/*'
				},
				data: file
			});
```
```html
<fieldset><legend>Upload on form submit</legend>
	    
	    Profile Picture: <input type="file" ng-file-select="" ng-model="picFile" name="file" accept="*/*" required="">
	  	<br>
		<button ng-click="uploadPic(picFile)">Submit</button>
	    <img ng-show="picFile[0].dataUrl != null" ng-src="{{picFile[0].dataUrl}}" class="thumb">
		<span class="progress" ng-show="picFile[0].progress &gt;= 0">		
			<div style="width:{{picFile[0].progress}}%" ng-bind="picFile[0].progress + '%'" class="ng-binding"></div>
		</span>	
		<span ng-show="picFile[0].result">Upload Successful</span>
  	</fieldset>
```

**Comment by danialfarid** [comment]
That seems like a server error, make sure your server accepts the file you are sending.

**Comment by dimitrilahaye** [comment]
How can I do this ? I'm on a tomcat Server, springMVC, how it can be arrives in your opinion ?

**Comment by danialfarid** [comment]
Find some sample file upload code for spring mvc. Your controller annotations should be like that, allowing multipart/form-data.

**Comment by danialfarid** [comment]
Here is a sample: https://github.com/danialfarid/ng-file-upload/wiki/spring-mvc-example

**Comment by dimitrilahaye** [comment]
Thanks ! It works like a charm :)

**Comment by gronel** [comment]
hi @danialfarid  can you help me i got error when i upload my file thru web api i got 415 (Unsupported Media Type)

this is my controller code 
`  Upload.upload({
                                                     url: 'http://localhost:20015/api/mifs/files-upload',
                                                     fields: { 'issueresponseId': responseId, 'created_by': userFullname },
                                                     file: file,
                                                     headers: { 'Accept': 'application/json', 'Content-Type': 'application/json; ; charset=UTF-8' },
                                                     dataType: 'json',
                                                 }).progress(function (evt) {
                                                     var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
                                                     self.max = 100;
                                                     self.isStartUpload = true;
                                                     //  console.log('progress: ' + progressPercentage + '% ' + evt.config.file.name);
                                                     console.log('percent: ' + parseInt(100.0 * evt.loaded / evt.total));
                                                 }).success(function (data, status, headers, config) {

                                                     // console.log('file ' + config.file.name + ' uploaded. Response: ' + data);
                                                     self.dynamic = parseInt(100.0 * i / self.files.length);

                                                 });`

**Comment by danialfarid** [comment]
Remove content-type

**Comment by qwerty24491** [comment]
hi, from 3 days I am having same problem 415 with angular js and spring . I tried many solution to resolve it but I am getting 400 . plz help

post request :
   //Post data and selected files.  
    $scope.save = function () {  
    window.alert("json ::"+$scope.username +"      "+$scope.age);
     
    $scope.jsonData = {  
 		       username:$scope.username,  
               age: $scope.age 
     };  
   
    var formData = new FormData();  

    var file = $scope.files;
    var json = $scope.jsonData;

   // window.alert("js ="+$scope.jsonData);
    formData.append("model",JSON.stringify(json));  
    formData.append("files",file);  
    
    $http({
        method: 'POST',
        url: 'fileDataController/uploadFile.htm',
        headers: {
            'Content-Type': undefined
        },
        data: {
           model:json,
           uploadfile:file
        },
        transformRequest: function (data, headersGetter) {
            var formData = new FormData();
            angular.forEach(data, function (value, key) {
                formData.append(key, value);
            });

            var headers = headersGetter();
            delete headers['Content-Type'];

            return formData;
        }
    }).
        success(function (data, status, headers, config) {  
            alert("success!"+status +data);  
        }).  
        error(function (data, status, headers, config) {  
            alert("failed!"+status +data);  
        });  
    };  

controller:
@RequestMapping(value = "uploadFile.htm", method = RequestMethod.POST)
	@ResponseBody
	public Object saveUserDataAndFile(@ RequestParam("uploadfile") MultipartFile file, @RequestParam("model") User user) {
//code
}
