### ISSUE TITLE
ng-file-select not working via mouse click in chrome on tablet with touch

### ISSUE THREAD

**Issue by erikkolo** [danialfarid/ng-file-upload#689]
Please change:
var clickTouchEvent = 'ontouchend' in document ? 'touchend' : 'click'

to:
var clickTouchEvent = 'touchend' in document ? 'touchend' : 'click'

(remove the 'on' prefix).

Otherwise it isn't working on a tablet or laptop with a touch display using a mouse in chrome.

**Comment by danialfarid** [comment]
Fixed in version 4.0.0
