### ISSUE TITLE
problems with drag-over-class and ng-accept

### ISSUE THREAD

**Issue by antonioreyna** [danialfarid/ng-file-upload#690]
hello, I have a drop zone wiht ng-accept="'.jpg,.png" and drag-over-class="{accept:'dragover', reject:'dragover-error', delay:100}"   but the class added is always the reject one, even if the file is png or jpg what is wrong?

**Comment by danialfarid** [comment]
Fixed in version 4.0.2

**Comment by danialfarid** [comment]
drag-over-class only works on file type, it cannot verify file extension since chrome does nor report it. It also only works in chrome.
