### ISSUE TITLE
Using ngImgCrop with ng-file-upload

### ISSUE THREAD

**Issue by GarySwift** [danialfarid/ng-file-upload#696]
I'm having some issues when trying to use __[ngImgCrop](https://github.com/alexk111/ngImgCrop)__ in conjunction with __[ng-file-upload](https://github.com/danialfarid/ng-file-upload)__. Basically, I can get both working, but not together.

Does anyone have any experience using these two directives together and how did you do it?

***
If it helps, here is a partial overview of how these are both implemented.

There is an event listener for the the input field (#fileInput) that calls handleFileSelect.
```html	
	<input type="file" id="fileInput" />
```
```javascript	
	angular.element(document.querySelector('#fileInput')).on('change',handleFileSelect);
```	
And ng-file-upload is implemented using the following way.
```html
	<input  type="file" 
			ngf-select 
			ng-model="picFile" 
			name="file" accept="image/*" 
			ngf-change="generateThumb(picFile[0], $files)" 
			required
	>		
```
I guess I'm looking for a way for __ngf-select__ to call __handleFileSelect__ and for there not to be conflict.

**Comment by danialfarid** [comment]
You can have `ngf-change=handleFileSelect($files)`

**Comment by GarySwift** [comment]
Thank you for the reply. I couldn't get it working as I wanted so I have tried a different approach.

**Comment by danialfarid** [comment]
See the sample on the readme page for how to integrate with ngImgCrop: http://jsfiddle.net/xxo3sk41/1/
