### ISSUE TITLE
How to get the file content data on server side when using $upload.http

### ISSUE THREAD

**Issue by yingdanh** [danialfarid/ng-file-upload#699]
I can get the content if the file format is .txt or .csv by using:
Object.keys(req.body);

I saw req.body is like: 
body: { 'This is a test file created by @yingdanh': '' }

But this way doesn't work for PDF format. Could someone please help?

Btw, another problem when I use $upload.http is that I can only use: 
'Content-Type': 'application/x-www-form-urlencoded'

If I use Content-Type as 'application/pdf', I can't see the file data on the server side anymore.

Thank you,
Yingdan

**Comment by danialfarid** [comment]
Can you post your code here?

**Comment by yingdanh** [comment]
I use yeoman to generate angular full stack code. 

Front-end filetrap.controller.js:

$upload.http({
            url: '/api/filetrap/' + file.name,
            headers: {
              'Content-Type': 'application/x-www-form-urlencoded',
              'X-Remote-Path': uploadPath
            },
            data: file
          }).progress(function (evt) {
            /*var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
            console.log('progress: ' + progressPercentage + '% ' + evt.config.data.name);

            $timeout(function () {
              $scope.progressValue = progressPercentage;
            }, 200);*/
          }).success(function (data, status, headers, config) {
            //console.log('file ' + config.data.name + ' uploaded. Response: ' + data);
            $scope.onNodeToggle($scope.selectedNode);
          });

Front end calls the backend code:
var uploadFile = function (req, res) {
  var filename = req.params.filename;
  var sftpPath = req.headers['x-remote-path'];
  var fileContent = Object.keys(req.body);
  console.log(fileContent);

......
}

I only need upload one file at one time. My .txt file has one line: This is a test file created by @yingdanh.
I can see request body: { 'This is a test file created by @yihuang': '' }, then var fileContent = Object.keys(req.body) gives me that line. 

.csv works fine, but pdf doesn't work - I saved the .txt file to .pdf. 

Thanks a lot!
Yingdan

**Comment by danialfarid** [comment]
Why don't you use `Upload.upload`? What's the reason for using `Upload.http`?

**Comment by danialfarid** [comment]
If you are using `$upload.http({})` set the content-type header to `file.type` instead of `application/x-www-form-urlencoded`
