### ISSUE TITLE
Multipart Upload to S3

### ISSUE THREAD

**Issue by simonKon** [danialfarid/ng-file-upload#700]
Is it possible to use the AWS S3 multipart upload with this library?
Means, is there a way to hook in at some point (earliest would be after file is dropped in broser )
and change or add some own uploading code?

**Comment by danialfarid** [comment]
Demo page has S3 upload sample.

**Comment by sk-swimp-de** [comment]
Hi danialfarid, thx for the fast reply. 
I have already used the S3 upload sample on your demo page and in general its working pretty fine.
As far as i got it, its using POST which means the upload is performed as one big object. 

My case requires the upload of files up to 1 GB. 
The AWS documentation has a limited object size of 5 GB using POST which is enough for my case, but they also recommend using multipart-methods for objects bigger than 100 MB.
http://docs.aws.amazon.com/AmazonS3/latest/dev/uploadobjusingmpu.html
Multipart will be more stable, faster and recoverable.

I like your library and want to use it, but wont deal my big files with POST.
So again the question it think is not closed yet is whether I can upload files with your library using multipart out of the box? 
If not, is there a way to decouple Drag and Drop from the upload  part and hook a multipart upload
without forking or messing up the library with my own code?
Do you plan to add this functionality?

Kind regards

**Comment by danialfarid** [comment]
Selecting the file and uploading it are done separately so you can still use the plugin directive to select the file and then upload it however you like. You could still use `Upload.upload()` to upload parts of the file but you gotta break down the file into parts first and send them with the part number.
related: #251
If you are willing to contribute and submit a PR let me know.

**Comment by simonKon** [comment]
Thx again for the fast reply,  I've hoped you designed the library that way.
>If you are willing to contribute and submit a PR let me know.

Perhaps I will come back to you ...
