### ISSUE TITLE
Show alert for ngf-min-size ngf-max-size

### ISSUE THREAD

**Issue by faustlife** [danialfarid/ng-file-upload#703]
When I load image (ngf-change="generateThumb(img,$files)"), using directives "ngf-min-size" or "ngf-max-size", with unvalid size, I don't understand when I can show alert like "You load bad size image". 
Function generateThumb(img) in js executed before as img was select, and after as img was select . In both cases and parameter img is null.
Help me please!

**Comment by danialfarid** [comment]
it should be `ngf-change="generateThumb($files, $rejectedFiles)`
