### ISSUE TITLE
File/Mime type in IE8 is always going as application/octet-stream

### ISSUE THREAD

**Issue by anandsumeet** [danialfarid/ng-file-upload#704]
using latest version 4.0 with angular ver 1.2.28 for <IE9
On file select the file.type is correct in IE8 but server (php) receives it as octet-stream.  What possibly is wrong or is this the expected behavior?

**Comment by danialfarid** [comment]
What file type? Can you monitor the http request being sent and see what content-type is reported for that file in the request being sent to the server?

**Comment by anandsumeet** [comment]
Tried various file types: pdf, doc, ppt, pptx, png, jpeg, gif
testing in IE11 emulation mode for IE8; using the upload method and not http method.

http request & response below for file type pdf, its same for all other types
REQUEST
{  "method": "POST",  "transformRequest": [    null  ],  "transformResponse": [
    null  ],
  "url": "http://192.168.10.30/iHub/int/api.php?app=upload&method=contentfile&datatype=text&furl=/home/content/recent&cTime=2015-04-30T10:14:21+05:30",
  "file": {    "id": "1430369061922811",    "flashId": "fileapi14303687443852",
    "type": "pdf",    "size": 711050,
    "name": "FINANCIAL MARKET INTEGRATION.pdf",    "foname": "ATTACHMENTS",
    "prgrs": 0,    "cbk": {      "UUID": "cc00654170c1d25e1d45dbeb0c005044",
      "VERSION": "2-6e2e654644cfebc4e96b711cac98e9c8",      "VERSIONNO": 1,
      "name": "FINANCIAL MARKET INTEGRATION.pdf",
      "description": "FINANCIAL MARKET INTEGRATION.pdf",
      "fileName": "FINANCIAL MARKET INTEGRATION.pdf",
      "type": "application/octet-stream",
      "file": "download/content/cc00654170c1d25e1d45dbeb0c005044/FINANCIAL MARKET INTEGRATION.pdf"
    }  },  "fields": {    "Content-Type": "pdf"  },
  "fileFormDataName": "files",  "headers": {
    "Accept": "application/json, text/plain, */*"  },  "cached": false}

I have interceptor configured for response processing and $httpProvider  setting header as below
$httpProvider.defaults.headers.post['Content-Type'] = 'application/x-www-form-urlencoded;charset=utf-8';
could this be causing the problem?

Tried the demo at angular-file-upload.appspot.com also, but there its throwing FILEAPI error in console for IE8, so cant test default functionality.


Another strange thing I noted, on a page I have 2 ngf-select under a custom controller(2 diff instances), at one place Flash object is showing but in the second place  the flash object is not loading (right click doesn't show flash menu) , this ngf-slect+controller is in a bootstrap modal while the first one is on the page, but both elements have same parent controller.   In the modal case where flash object is not showing my call to server never goes (progress and success events not triggering)

The backend I am using is a restful API in php and all instances of fileupload uses the same API and same controller.  The octet problem is coming everywhere but flash issue is only occurring in the modal case.

**Comment by danialfarid** [comment]
You don't need to set the content-type that might be the problem, also why your file object has two name,type,etc?

**Comment by anandsumeet** [comment]
the duplicate data is inside another property "cbk" that gets added when response comes, using it to display post upload, removed it now. 
Sending the plain response  in case of Chrome and IE8(emulation)
I tried by commenting the $httpProvider.defaults.headers.post['Content-Type'] code but no change

I noticed that the content-type inside config.headers is going as undefined (in console it shows like that, not when logging the object as string), but file.type is fine.  Its same in chrome but works fine there.  Also chrome sends file.type as "application/pdf" whereas IE8 is sending it as "pdf", which should not be a problem.

We extract the mime from the file binary on our server, it seems flash is doing something here due to which we are getting it as octet-stream.  Can it be due to version of flash plugin? which one is supported by V4.0?  I can update and try again.

RESPONSE + REQUEST CONFIG DATA
--------------------------------------------------------------------------------
The config object is what angular sends
The DEBUG object, has the header and other data as received on the server
R object has the response data (file type received etc)

IE8:
===============================
{ 
	"config" : { "cached" : false,
      "file" : { "flashId" : "fileapi14304625230942",
          "foname" : "ATTACHMENTS",
          "id" : "1430462586612847",
          "name" : "rbi_ownership_report.pdf",
          "prgrs" : 100,
          "size" : 517775,
          "type" : "pdf"
        },
      "fileFormDataName" : "files",
      "headers" : { "Accept" : "application/json, text/plain, */*" },
      "method" : "POST",
      "transformRequest" : [ null ],
      "transformResponse" : [ null ],
      "url" : "http://192.168.10.30/iHub/int/api.php?app=upload&method=contentfile&datatype=text&furl=/home/content/recent&cTime=2015-05-01T12:13:06+05:30"
    },
  "data" : { 
		"DEBUG" : { "COOKIE" : { "__sales__" : "9af16472-186f-4daf-81e0-bf3edf116b07" },
			  "HEADERS" : [ "Set-Cookie: __sales__=9af16472-186f-4daf-81e0-bf3edf116b07; Domain=192.168.10.30; Max-Age=604800; Path=/iHub/; HttpOnly",
				  "Content-Type: text/plain",
				  "Pragma: no-cache",
				  "Cache-Control: no-store, no-cache, must-revalidate",
				  "Content-Disposition: inline",
				  "Vary: Accept",
				  "X-Content-Type-Options: nosniff"
				],
			  "REQUEST" : { "Filename" : "rbi_ownership_report.pdf",
				  "Upload" : "Submit Query",
				  "app" : "upload",
				  "cTime" : "2015-05-01T12:13:06 05:30",
				  "datatype" : "text",
				  "furl" : "/home/content/recent",
				  "method" : "contentfile"
				},
			  "SERVER" : { "CONTENT_LENGTH" : "518218",
				  "CONTENT_TYPE" : "multipart/form-data; boundary=----------cH2Ij5gL6ei4Ij5GI3KM7GI3ei4GI3",
				  "CONTEXT_DOCUMENT_ROOT" : "/var/www/html",
				  "CONTEXT_PREFIX" : "",
				  "DOCUMENT_ROOT" : "/var/www/html",
				  "GATEWAY_INTERFACE" : "CGI/1.1",
				  "HTTP_ACCEPT" : "text/*",
				  "HTTP_CACHE_CONTROL" : "no-cache",
				  "HTTP_CONNECTION" : "Keep-Alive",
				  "HTTP_COOKIE" : "__sales__=9af16472-186f-4daf-81e0-bf3edf116b07",
				  "HTTP_HOST" : "192.168.10.30",
				  "HTTP_USER_AGENT" : "Shockwave Flash",
				  "PATH" : "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
				  "PHP_SELF" : "/iHub/int/api.php",
				  "QUERY_STRING" : "app=upload&method=contentfile&datatype=text&furl=/home/content/recent&cTime=2015-05-01T12:13:06+05:30",
				  "REMOTE_ADDR" : "192.168.10.21",
				  "REMOTE_PORT" : "58237",
				  "REQUEST_METHOD" : "POST",
				  "REQUEST_SCHEME" : "http",
				  "REQUEST_TIME" : 1430462587,
				  "REQUEST_TIME_FLOAT" : 1430462587.3929999,
				  "REQUEST_URI" : "/iHub/int/api.php?app=upload&method=contentfile&datatype=text&furl=/home/content/recent&cTime=2015-05-01T12:13:06+05:30",
				  "SCRIPT_FILENAME" : "/var/www/html/iHub/int/api.php",
				  "SCRIPT_NAME" : "/iHub/int/api.php",
				  "SERVER_ADDR" : "192.168.10.30",
				  "SERVER_ADMIN" : "webmaster@localhost",
				  "SERVER_NAME" : "192.168.10.30",
				  "SERVER_PORT" : "80",
				  "SERVER_PROTOCOL" : "HTTP/1.1",
				  "SERVER_SIGNATURE" : "",
				  "SERVER_SOFTWARE" : "Apache/2.4.7 (Ubuntu)"
				}
		},
      "R" : { "app" : "upload",
          "code" : "UPLOAD_FILE_COMPLETED",
          "dataSet" : { "data" : [ { "UUID" : "4739887acfdeaa9485a81a06610293ef",
                    "VERSION" : "2-3ae3f7438b77d8b3ec01e6aab591899d",
                    "VERSIONNO" : 1,
                    "description" : "rbi_ownership_report.pdf",
                    "file" : "download/content/4739887acfdeaa9485a81a06610293ef/rbi_ownership_report.pdf",
                    "fileName" : "rbi_ownership_report.pdf",
                    "name" : "rbi_ownership_report.pdf",
                    "type" : "application/octet-stream"
                  } ],
              "from" : 0,
              "total" : 1
            },
          "exec" : true,
          "id" : "API-5543207ba396d",
          "method" : "contentfile",
          "msg" : "Cheers! We received the file(s).",
          "session" : "9af16472-186f-4daf-81e0-bf3edf116b07"
        }
    },
  "status" : 200,
  "statusText" : ""
}

CHROME:
=============================

{ 
	"config" : { "cached" : false,
      "file" : { "foname" : "ATTACHMENTS",
          "lastModified" : 1399457255000,
          "lastModifiedDate" : "2014-05-07T10:07:35.000Z",
          "name" : "FINANCIAL MARKET INTEGRATION.pdf",
          "prgrs" : 100,
          "size" : 711050,
          "type" : "application/pdf",
          "webkitRelativePath" : ""
        },
      "fileFormDataName" : "files",
      "headers" : { "Accept" : "application/json, text/plain, */*" },
      "method" : "POST",
      "transformRequest" : [ null ],
      "transformResponse" : [ null ],
      "url" : "http://192.168.10.30/iHub/int/api.php?app=upload&method=contentfile&datatype=text&furl=/home/content/recent&cTime=2015-05-01T11:34:36+05:30"
    },
  "data" : { 
		"DEBUG" : { "COOKIE" : { "__sales__" : "a937a4af-8345-44e5-82fc-7a655cf1366a",
              "_ga" : "GA1.1.768873267.1427295352"
            },
			  "HEADERS" : [ "Set-Cookie: __sales__=a937a4af-8345-44e5-82fc-7a655cf1366a; Domain=192.168.10.30; Max-Age=604800; Path=/iHub/; HttpOnly",
				  "Content-Type: text/plain",
				  "Pragma: no-cache",
				  "Cache-Control: no-store, no-cache, must-revalidate",
				  "Content-Disposition: inline",
				  "Vary: Accept",
				  "X-Content-Type-Options: nosniff"
				],
			  "REQUEST" : { "app" : "upload",
				  "cTime" : "2015-05-01T11:34:36 05:30",
				  "datatype" : "text",
				  "furl" : "/home/content/recent",
				  "method" : "contentfile"
				},
			  "SERVER" : { "CONTENT_LENGTH" : "711262",
				  "CONTENT_TYPE" : "multipart/form-data; boundary=----WebKitFormBoundarykM8KXymmMnhQ82sW",
				  "CONTEXT_DOCUMENT_ROOT" : "/var/www/html",
				  "CONTEXT_PREFIX" : "",
				  "DOCUMENT_ROOT" : "/var/www/html",
				  "GATEWAY_INTERFACE" : "CGI/1.1",
				  "HTTP_ACCEPT" : "application/json, text/plain, */*",
				  "HTTP_ACCEPT_ENCODING" : "gzip, deflate",
				  "HTTP_ACCEPT_LANGUAGE" : "en-US,en;q=0.8",
				  "HTTP_CACHE_CONTROL" : "no-cache",
				  "HTTP_CONNECTION" : "keep-alive",
				  "HTTP_COOKIE" : "__sales__=a937a4af-8345-44e5-82fc-7a655cf1366a; _ga=GA1.1.768873267.1427295352",
				  "HTTP_HOST" : "192.168.10.30",
				  "HTTP_ORIGIN" : "http://192.168.10.30",
				  "HTTP_PRAGMA" : "no-cache",
				  "HTTP_REFERER" : "http://192.168.10.30/iHub/",
				  "HTTP_USER_AGENT" : "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36",
				  "PATH" : "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
				  "PHP_SELF" : "/iHub/int/api.php",
				  "QUERY_STRING" : "app=upload&method=contentfile&datatype=text&furl=/home/content/recent&cTime=2015-05-01T11:34:36+05:30",
				  "REMOTE_ADDR" : "192.168.10.21",
				  "REMOTE_PORT" : "57833",
				  "REQUEST_METHOD" : "POST",
				  "REQUEST_SCHEME" : "http",
				  "REQUEST_TIME" : 1430460275,
				  "REQUEST_TIME_FLOAT" : 1430460275.273,
				  "REQUEST_URI" : "/iHub/int/api.php?app=upload&method=contentfile&datatype=text&furl=/home/content/recent&cTime=2015-05-01T11:34:36+05:30",
				  "SCRIPT_FILENAME" : "/var/www/html/iHub/int/api.php",
				  "SCRIPT_NAME" : "/iHub/int/api.php",
				  "SERVER_ADDR" : "192.168.10.30",
				  "SERVER_ADMIN" : "webmaster@localhost",
				  "SERVER_NAME" : "192.168.10.30",
				  "SERVER_PORT" : "80",
				  "SERVER_PROTOCOL" : "HTTP/1.1",
				  "SERVER_SIGNATURE" : "",
				  "SERVER_SOFTWARE" : "Apache/2.4.7 (Ubuntu)"
				}
        },
      "R" : { "app" : "upload",
          "code" : "UPLOAD_FILE_COMPLETED",
          "dataSet" : { "data" : [ { "UUID" : "4739887acfdeaa9485a81a0661023cd3",
                    "VERSION" : "2-9e50b5f3391a76954af22bb0d3cd8706",
                    "VERSIONNO" : 1,
                    "description" : "FINANCIAL MARKET INTEGRATION.pdf",
                    "file" : "download/content/4739887acfdeaa9485a81a0661023cd3/FINANCIAL MARKET INTEGRATION.pdf",
                    "fileName" : "FINANCIAL MARKET INTEGRATION.pdf",
                    "name" : "FINANCIAL MARKET INTEGRATION.pdf",
                    "type" : "application/pdf"
                  } ],
              "from" : 0,
              "total" : 1
            },
          "exec" : true,
          "id" : "API-55431773981f7",
          "method" : "contentfile",
          "msg" : "Cheers! We received the file(s).",
          "session" : "a937a4af-8345-44e5-82fc-7a655cf1366a"
        }
    },
  "status" : 200,
  "statusText" : "OK"
}

**Comment by anandsumeet** [comment]
Please provide some pointers to locate the cause. I'll try to troubleshoot accordingly.

**Comment by danialfarid** [comment]
Does it send the same content-type if you upload it with the demo page?

**Comment by anandsumeet** [comment]
As mentioned, the demo page is not working at all in IE8.  It throws FILEAPI error in console

**Comment by danialfarid** [comment]
What error?

**Comment by anandsumeet** [comment]
PFA the image..tried with angular 1.2.20 as well as 1.2.28(last version that supports IE8)
The error comes on page load and comes again on uploading a file

![ngf-ie8-console-err](https://cloud.githubusercontent.com/assets/5029560/7674780/9c7e9ca4-fd4c-11e4-926c-358190b97b3c.png)

**Comment by danialfarid** [comment]
Are you sure you are not in compatibility mode? What operating system are you using.
I have Win XP IE8 and everything works fine.

**Comment by danialfarid** [comment]
That error usually occurs when a plugin or browser trying to override XMLHttpRequest or FormData for the browser which could happen in compatibility mode or if you have a special plugin installed.

**Comment by anandsumeet** [comment]
I am in emulation mode as shown in screen shot above...will try and get hold of XP machine and test.
Anyway, we managed to fix the issue by using a better way to extract mime at server end. So i'll close this issue now.
