### ISSUE TITLE
IE9 file upload error to S3 amazon. 

### ISSUE THREAD

**Issue by rolands-timoshenko** [danialfarid/ng-file-upload#705]
When upload file to S3.amazon from IE9, throws error mess - undefined.

![snapshot_2015_4_29_13_38_36](https://cloud.githubusercontent.com/assets/3304305/7389275/129a2958-ee75-11e4-9f9b-6318a73ce7de.png)

![snapshot_2015_4_29_13_39_27](https://cloud.githubusercontent.com/assets/3304305/7389289/30df78be-ee75-11e4-89cb-82b339d895b3.png)

When change http to https for s3 amazon 
![snapshot_2015_4_29_13_54_13](https://cloud.githubusercontent.com/assets/3304305/7389519/51f3c0b2-ee77-11e4-8445-b9d43528a548.png)

Error throws after GET request to crossdomain.xml
![snapshot_2015_4_29_13_28_13](https://cloud.githubusercontent.com/assets/3304305/7389132/bf886d02-ee73-11e4-9c5e-f861bf73a1e7.png)

Loaded shim ->
![snapshot_2015_4_29_13_29_56](https://cloud.githubusercontent.com/assets/3304305/7389143/df882304-ee73-11e4-88d5-1e94f5432073.png)

Upload object ->
![snapshot_2015_4_29_13_31_28](https://cloud.githubusercontent.com/assets/3304305/7389174/18c0335a-ee74-11e4-95fa-ee9c95991146.png)

Upload html button ->
![snapshot_2015_4_29_13_32_27](https://cloud.githubusercontent.com/assets/3304305/7389185/387ac32c-ee74-11e4-9856-2eeb269c7fd5.png)

crossdomain.xml
![snapshot_2015_4_29_13_34_42](https://cloud.githubusercontent.com/assets/3304305/7389211/8c165bf4-ee74-11e4-92c2-2ee1c903ddcf.png)

**Comment by rolands-timoshenko** [comment]
Any idea why this could be happening and what to do to solve it?

**Comment by danialfarid** [comment]
make sure your crossdomain.xml file is publicly accessible.
