### ISSUE TITLE
Leverage dropfile for fallback

### ISSUE THREAD

**Issue by planttheidea** [danialfarid/ng-file-upload#708]
While the current version uses the Flash FileAPI polyfill to provide the multifile form upload capabilities, the drag-and-drop capabilities are not polyfilled. There are existing libraries out that that could be leveraged in the same way that FileAPI is, and <a href="https://github.com/MrSwitch/dropfile">dropfile</a> is one such library. It uses Silverlight to provide drag and drop back to IE6.

Any possibility that this could be incorporated into this directive? :D

**Comment by danialfarid** [comment]
How do you convert the file data into Blob or file object to be uploaded?

**Comment by danialfarid** [comment]
Actually IE8-9 doesn't support form data, so uploading part also needs to be handled by silverlight.
We would need another plugin to be able to handle silverlight upload.

**Comment by planttheidea** [comment]
Correct, dropfile (the project I reference) is a shim for FileAPI which uses Silverlight to make drag and drop accessible for IE9-. The goal was merely to aid in solving the "drag and drop fallback" issue, as the current Flash solution does not support that, so I guess a better way to introduce this was "is there a way to incorporate drag and drop with the Flash fallback". I know drag and drop is supported back to IE5 (albeit in a super hacky way compared to the HTML5 spec). The incorporation of dropfile was an idea to potentially bridge that gap.

**Comment by danialfarid** [comment]
I am not that keen on spending time to implement fancy features for older browsers which will have less and less users over time. For the purpose of uploading files you could just have an upload button for those browsers which I assume would be good enough for most use cases. 
But if you are willing to contribute and submit a PR that would be nice addition.

**Comment by planttheidea** [comment]
No worries, understandable considering how niche it is.
