### ISSUE TITLE
Browser files open twice

### ISSUE THREAD

**Issue by MateenKadwaikar** [danialfarid/ng-file-upload#709]
Hello,

I have implemented this code in my project, but when I click browse it open the dialog box and after selecting the image or after pressing cancel the dialog box open again. It open twice in short.

This is how I am implementing the code in my html.

Can you please tell what wrong I am doing. 

 <div ng-file-drop ng-file-select ng-model="vm.files" class="drop-box" class="drop-box pull-right"
            ng-file-drag-over-class="dragover" ng-file-multiple="false" ng-file-allow-dir="true"
          accept="image/*">Drop pdfs or images here or click to upload</div>

**Comment by danialfarid** [comment]
What version of the plugin are you using? Try using the latest version.

**Comment by MateenKadwaikar** [comment]
The latest one which is in Github repository.

**Comment by danialfarid** [comment]
Then you gotta change the directive name, the prefixes are now ngf-*.
Create a jsfiddle to reproduce the problem if you can.

**Comment by MateenKadwaikar** [comment]
Ok I'll try n update u

-Best Regards
Mateen Kadwaikar

**Comment by MateenKadwaikar** [comment]
Its working fine now. Thank you,.

**Comment by avalon2110** [comment]
i have same problem with new version.
