### ISSUE TITLE
problems when adding ng-if

### ISSUE THREAD

**Issue by antonioreyna** [danialfarid/ng-file-upload#711]
If I add an ng-if to my dropzone, the model stops getting the file.

**Comment by danialfarid** [comment]
Can you create a jsfiddle

**Comment by antonioreyna** [comment]
I tried, but i wasnt able to, this is my drop zone:

    <div ng-if="!logo" ng-file-drop ng-file-select ng-model="clientLogoEdit" class="drop-box" drag-over-class="{accept:'dragover', reject:'dragover-error', delay:100}" ng-multiple="false" allow-dir="false" ng-accept="'image/*'" ng-file-change="fileDropped($files, $event, $rejectedFiles)">drop your file</div>
        <div ng-no-file-drop>Su navegador no soporta esta opción</div>

**Comment by antonioreyna** [comment]
another thing i noticed on your example, i see you inject ngFileUpload and i am injecting angularFileUpload, is that the same?

**Comment by danialfarid** [comment]
no since version 4.x you gotta use ngFileUpload

**Comment by danialfarid** [comment]
also the name of the directive has changed to ngf prefix. That's probably why it's not working

**Comment by antonioreyna** [comment]
i updated the library and changed the zone to this

    <div ng-if="!clientFields.logo" ngf-drop ngf-select ng-model="clientLogoEdit" class="drop-box" ngf-drag-over-class="{accept:'dragover', reject:'dragover-error', delay:100}" ngf-multiple="false" ngf-allow-dir="false" ngf-accept="'image/*'" ngf-change="fileDropped($files, $event, $rejectedFiles)">

and I get the same, if i ```console.log(clientLogoEdit)``` it is null and if instead of ng-if i use ng-show it works the clientLogoEdit shows the object when i console.log

**Comment by rguldener** [comment]
@antonioreyna `ng-if` has the side effect of creating a new child scope and putting your element there. Try using `ng-model="$parent.clientLogoEdit"`

**Comment by antonioreyna** [comment]
and that did the trick!!, thank you @rguldener and thank you @danialfarid
