### ISSUE TITLE
max file size by file type

### ISSUE THREAD

**Issue by parliament718** [danialfarid/ng-file-upload#714]
I have an input that ```accepts``` images as well as other files types. 

I'd like to put a limit on the image file size so that images load faster for other users viewing them.

However, it would be unreasonably to limit video size to the same size as for images.

Can this be made more flexiable with a function callback for ```ngf-max-size```?

```
   ngf-max-size="validateMaxSize($file)"
```

or options:

```
   ngf-max-size="{ 'video/*': 5000000, 'image/*': 1000000 }"
```

**Comment by danialfarid** [comment]
Added feature to 4.1.2
