### ISSUE TITLE
ngf-accept values should be case insensitive 

### ISSUE THREAD

**Issue by parliament718** [danialfarid/ng-file-upload#715]
In my testing 

```
   ngf-accept="'.jpg,.jpeg,.png'"
```

blocks   someimage.PNG because PNG is capital. I'm aware I can use 'image/*' for my case, but this should be case insensitive as it will not work in every case.

**Comment by danialfarid** [comment]
fixed in version 4.1.2

**Comment by gracehopper17** [comment]
How to show error message on browser id ngf-accept does not match the validation?

**Comment by danialfarid** [comment]
@gracehopper17 add `ng-model-rejected="rejFiles"` directive and watch rejFiles in your controller and show the allert if it is not empty.

**Comment by papizza** [comment]
the watch on rejFiles doesn't work? even for files, the watch only trigers when the page is loaded, it won't get triggered when i click the upload button

**Comment by danialfarid** [comment]
@papizza can you create a jsfiddle
