### ISSUE TITLE
Document ngf-accept validation function semantics

### ISSUE THREAD

**Issue by rguldener** [danialfarid/ng-file-upload#716]
Please add documentation to clarify the behavior of the validation function `validate($file)` that can be passed into `ngf-accept`. Currently the only way to know what to return to indicate a valid or invalid file is to read the source. To make matters worse, 9d3227f96ba6e5e7cac4d35f55ea69a22307f010 has significantly altered its semantics without any mention in the release notes.

Three suggestions:

1. Add documentation to `README.md` to explain the semantics of the validation function: Return null to indicate a valid file, return a non-null, non-string value to indicate an invalid file. Return a string if you want that string to be interpreted as a RegEx and check if the filename matches against that.

2. Add a note to the 4.0.0 release notes that clarifies the change in validation semantics. Previously returning `true` from the validation function indicated an accepted file and returning `false` indicated an invalid file.

3. Rethink the current semantics, I think the 3.x semantics were much more in line with normal validation function semantics. The current one is pretty confusing, especially the string-as-regex special case.

**Comment by danialfarid** [comment]
This could have been a bug.
Anyway in version 4.1.1 it should work as stated in the docs:
`function or comma separated wildcard to filter files allowed`
