### ISSUE TITLE
Chrome on Windows 8 not working

### ISSUE THREAD

**Issue by sebloix** [danialfarid/ng-file-upload#719]
I am using the directive perfectly on Mac (Chrome, Firefox, Safari, Opera) and on Windows8 (IE 10, Firefox), and on Linux (Chrome). But somehow on Windows8 Chrome it doesn't trigger the file picker.

As it works everywhere but there, I am thinking that it must be something on my pc instead of a ng-file-upload/Chrome issue but I just wanted to check if anyone experienced something similar.

Thanks for this great directive!

**Comment by danialfarid** [comment]
It might be a chrome plugin interfering.
Try it in private mode or a new install.

**Comment by sebloix** [comment]
Hi, thanks for the feedback.
I just found out what it is... It is related to the line:
'var clickTouchEvent = 'ontouchend' in document ? 'touchend' : 'click''
The pc I am testing on is a touch screen Dell (http://www.dell.com/us/p/inspiron-15-7537/pd). It seems that Chrome is the only browser with the 'ontouchend' event registered in document and so the directive is expecting that event (and indeed it works if I touch the screen).
I don't know why Dell had to enter the touch screen space on laptop but it just ads a bit more nightmare for the developers..... :)

I am going to try to bind both click and ontouchend and see what happens.
Thanks

**Comment by danialfarid** [comment]
If you use the latest version it would listen to both events so it should work.

**Comment by sebloix** [comment]
Indeed.. I updated to latest version and it works perfectly. thanks!
