### ISSUE TITLE
ng-model-rejected not set when also using an ng-if on the file input

### ISSUE THREAD

**Issue by bryanbak** [danialfarid/ng-file-upload#720]
I have a file input that I'm only showing in certain cases using ng-if. When I try selecting a file that should be rejected based on ngf-accept, it is rejected, but the ng-model-rejected value is never set. If I remove the ng-if from the file input then everything works as expected.

Here's a plunker that shows what's going on: http://plnkr.co/edit/jvMHCHl4ml3PEx1MGpGu?p=preview
Basically all it should do is print the file name below the input if it is rejected. It only works if you remove the ng-if from the file input though.

This is with version 4.1.3 and angular version 1.3.8

**Comment by danialfarid** [comment]
Try the approach here: https://github.com/danialfarid/ng-file-upload/issues/711

**Comment by bryanbak** [comment]
I ended up going a level higher and putting my ng-if on a div that contained the file input. That did the trick for me.
If this isn't going to change it might be nice to note it on the docs somewhere that you shouldn't use ng-if with the ngf-* directives.
