### ISSUE TITLE
Cannot set Content-Type

### ISSUE THREAD

**Issue by mpandey-myglobalit** [danialfarid/ng-file-upload#722]
I want to send a file by using PUT method in x-www-form-urlencoded form. 

So, i add this line to header: 
headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
data: {key:'val'}

But, when i checked you lib, i found that you are manually overriding the CONTENT_TYPE
Line 119        config.headers = config.headers || {};
Line 120        config.headers['Content-Type'] = undefined;

Is there any way to fix it.

**Comment by danialfarid** [comment]
multipart/form-data   is used for sending files, x-www-form-urlencoded is not intended for sending files with binary and non ASCII characters in them.
