### ISSUE TITLE
Input element with display:none does not trigger in some browsers

### ISSUE THREAD

**Issue by alphatwit** [danialfarid/ng-file-upload#724]
I'm seeing this issue in Safari on Windows right now. The file select window doesn't come up when I select the element with the directive. When the input element is created, it is using display:none, which prevents some browsers from triggering it. Alternatives:

opacity:0;width:0px;height:0px;
or
visibility: hidden;position: absolute;

**Comment by danialfarid** [comment]
Fixed in version 4.2.0
