### ISSUE TITLE
ng-file-select not opening window to select file

### ISSUE THREAD

**Issue by mohamednagy** [danialfarid/ng-file-upload#727]
<button ng-file-select=""  ng-click="uploadBtn()" ng-model="picFile" name="photo" accept="image/*" class="btn btn-info m-h-md">Change</button>
Cann't open window to select files in safari web browser

**Comment by danialfarid** [comment]
what version what browser version?

**Comment by mohamednagy** [comment]
v 5.1.7 on windows

**Comment by danialfarid** [comment]
latest version is 4.2.0

**Comment by williamweckl** [comment]
I'm with the same issue.
Using the latest version. Happens when I use ngf-drop and ngf-select together with ngf-change.

**Comment by danialfarid** [comment]
Post your code here, The demo page and jsfiddle sample both have an example of using both directives and they are working.

**Comment by williamweckl** [comment]
https://jsfiddle.net/3t50b3fw/121/

Happens if I use `reader.readAsDataURL(file);` inside the function.

**Comment by williamweckl** [comment]
Solved! Was an error inside my function that I was calling with ngf-change. Thank you.
