### ISSUE TITLE
Image Preview doesn't work with android 4.2.1 and below

### ISSUE THREAD

**Issue by AlpeshT** [danialfarid/ng-file-upload#728]
I am using this functionality with ionic framework to preview the profile image before upload. But image preview doesn't work which mobile devices has android v4.2.1 and below. Is there any solution for it !? 

<b>My html file</b>

    <div class="signup-img" ng-file-select="generateThumb(files)" ng-model="files" id="files">&nbsp;
    <img src="{{image.imgUrl}}" width="110" height="107" class="title-image profile-image">
    </div>   

<b>In my controller</b>

    $scope.generateThumb = function (files) {
                var file = files[0];
                if (file != null) {
                    if ($scope.fileReaderSupported && file.type.indexOf('image') > -1) {
                        $timeout(function () {
                            var fileReader = new FileReader();
                            fileReader.readAsDataURL(file);
                            fileReader.onload = function (e) {
                                $scope.$apply(function ($scope) {
                                    file.dataUrl = e.target.result;
                                    $scope.image.imgUrl = file.dataUrl;
                                });
                            }
                        });
                    }
                }
            }

**Comment by danialfarid** [comment]
Does `ngf-src` directive works?
Try a smaller file maybe it has to do with the file size.
You can also try a simple <img> with a constant data url src to narrow down the issue.

**Comment by AlpeshT** [comment]
It works on other devices which has android version 4.2.2 and above.  I tried to upload smaller file also.
