### ISSUE TITLE
Load a local json file into app $scope?

### ISSUE THREAD

**Issue by mikegoodstadt** [danialfarid/ng-file-upload#729]
Hi!
I currently use FileReader to load user local JSON files into the app $scope.
However I would prefer to use a actively-maintained popular module with good functionality eg. ng-file-upload's drag-drop :)
It is possible to achieve the same local-to-local with ng-file-upload?
ie. not upload to a server but just pass the data to $scope or localStorage
Maybe I am just missing the obvious but I am having a fuzzy-brain day and so would appreciate some guidance...
Many thanks, Mike

**Comment by danialfarid** [comment]
If you use the directive it would add the File object to the scope with ng-model. Then if you want to show the preview or convert it to the data url on the front-end you can use `ngf-src` directive but if you want to store it in localStorage you should use FileReader.

Using FileReader is pretty straight forward so I don't need a plugin is needed for that.

**Comment by mikegoodstadt** [comment]
Thanks Danial!
I will try this and get back if I have any problems.
Saludos, Mike
