### ISSUE TITLE
IE9 File Upload not working

### ISSUE THREAD

**Issue by stephan-fischer** [danialfarid/ng-file-upload#730]
Hello,

i using following Code:

        <script src="assets/js/plugins/ng-file-upload/ng-file-upload-shim.min.js"></script>
        <script src="assets/js/plugins/ng-file-upload/ng-file-upload.min.js"></script>
        
                
                Upload.upload({
                    url: '/profile/image/upload.json',
                    fields: {'authToken': api.getAuthToken()},
                    file: file,
                    method: 'POST',
                     fileFormDataName: 'file'
                }).progress(function (evt) {
                    var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
                    console.log('progress: ' + progressPercentage + '% ' + evt.config.file.name);
                }).success(function (data, status, headers, config) {
                    api.handleResponse(data);
                    
                    console.log('file ' + config.file.name + 'uploaded. Response: ' , data);
                });

And get following error, only in IE9:

Error: Ungültiges Argument.
   {
      [functions]: ,
      description: "Invalid Argument.",
      message: "Invalid Argument.",
      name: "Error",
      number: -2147024809
   }

**Comment by danialfarid** [comment]
Is the flash loaded? Do you see flash context menu when you right click on the button?

**Comment by stephan-fischer** [comment]
yes its coming and flash is loaded

**Comment by stephan-fischer** [comment]
And i can see the upload dialog, choose a picture, and after that, the error message comes

**Comment by danialfarid** [comment]
Does it happen on the demo page?

**Comment by stephan-fischer** [comment]
the demopage works correctly

**Comment by stephan-fischer** [comment]
Ok i know why, but not how to fix it:
The problem is the url parameter. In the demo-Page this works:
url: 'https://angular-file-upload-cors-srv.appspot.com/upload' + $scope.getReqParams(),

and it also works
 url: 'http://www.auto.de/',

but it not works with relative, or absolute paths like:
 url: '/profile/image/upload.json',

any solution for that? Thank you!

**Comment by danialfarid** [comment]
What do you mean by relative or absolute path? You mean the file path?

**Comment by stephan-fischer** [comment]
yes the file path of course for the uploading script

absolute i mean to the root:
/absolute/path/upload.json (not php)

or 
relative/path/upload.json

**Comment by danialfarid** [comment]
That has to be a url, for security reasons you cannot reference a file.
