### ISSUE TITLE
Upload url getting changed in chrome

### ISSUE THREAD

**Issue by rcr929** [danialfarid/ng-file-upload#731]
I'm trying to upload a file to my dev server with the code
```
Upload.upload({
    url: '***.**.*.***:1000/exampleURL',
    file: file[0]
})
```
and I get a console error that it can't connect to the URL because `%3` is getting appended to the beginning of the upload URL.  Any ideas on what is causing this or what can be done to fix it?

**Comment by danialfarid** [comment]
It is processed by angular so your url needs to be in a correct format, why do you have * there?

**Comment by rcr929** [comment]
I don't actually have *'s in my code.  It's the ip address and port of the server but I put the *'s instead of the actual address for the post.  The url is in the format `IPaddress:port/route`.  I'll look into why angular might be appending the `%3` to the front of the URL

**Comment by huxiaoqiang** [comment]
Hi, I have the same problem . the error is   
XMLHttpRequest cannot load %3127.0.0.1:8000/file/upload. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

can you tell me how to set the upload path? I'll always appreciate that.

**Comment by danialfarid** [comment]
You should have 'http://127.0.0.1:8000...`

**Comment by rcr929** [comment]
Didn't think the http:// should make a difference, but that fixed it for me. Thanks.

**Comment by larvanitis** [comment]
Out of curiosity I just checked what's really happening and actually the '1' in **1**27 gets replaced with its url encoded representation which is `%31`.
