### ISSUE TITLE
Upload.progress() fires 100% immediately

### ISSUE THREAD

**Issue by Tyguy7** [danialfarid/ng-file-upload#732]
The progress event fires 100% complete as soon as the upload starts, and doesn't fire again.  The upload continues, maybe 20-30s for a large image, and everything works as expected after, but the progress indicator is useless.

**Comment by Tyguy7** [comment]
Ok, it appears that the progress indicator relies on server response.  I thought that this plugin behaved like jQuery file upload and was able to report progress from the front end.

**Comment by Tyguy7** [comment]
I've been trying this with HTML5 shim as well, no matter what I do, it immediately fires 100% upload complete.  For a 100mb upload, it fires 100% immediately, then waits 2 minutes to complete...

**Comment by danialfarid** [comment]
what browser/version?
