### ISSUE TITLE
how to create file for upload method from scope arraybuffer

### ISSUE THREAD

**Issue by gswartz777** [danialfarid/ng-file-upload#735]
I am using this in an angular app to allow a user to select a local file to upload which in itself is simple enough.  However, we also have to offer the ability for the user to select a file from their google drive or dropbox.  I have this working where when the user selects a remote file from google or dropbox, it downloads the file and sets a scope arraybuffer to the contents of the downloaded file and also sets a scope filename property to the name of the file.  I am doing this on the fileSelected method of the ng-file-upload directive...

    $scope.fileSelected = function (files) {
        if (files && files.length) {
            $scope.filename = files[0].name;
            var reader = new FileReader();
            reader.onload = function(e) {
                $scope.fileArrayBuffer = reader.result;
            }
            reader.readAsArrayBuffer(files[0]);
            $scope.$digest();
        }
    };

So, in all cases, when someone is done with the form and wants to submit it, I have a $scope.fileArrayBuffer property with the file contents and a $scope.filename property with the filename.  So, how can I do a final conversion to a file format for the Upload.upload method?  Thanks.

**Comment by danialfarid** [comment]
Why do you convert it from file to array buffer in the first place?

**Comment by gswartz777** [comment]
Because google drive and dropbox just return the file as a string.  So I figured I needed to create some type of structure like a byte array containing the data from the file.  Just to keep everything consistent and make it easier to test, I figured I'd do the same with whatever file is selected locally so when it hits the uploading section it all works the same.  I'm kind of new to the whole file api and so I'm not saying this is the best way to do it... it's just where I'm currently at.  But if you can suggest an alternative to create a file from what google drive or dropbox would create that is the same as what is selected from the file system that's great... I just thought I read that you can't create an instance of a file - only read one.

**Comment by danialfarid** [comment]
"Because google drive and dropbox just return the file as a string." What data is in that string?

**Comment by gswartz777** [comment]
well it's the xmlhttprequest responsetext which my understanding is just a string.  but it could represent an html doc, txt file, rtf, pdf, etc.  So I am a bit unsure this is the proper way to do it - I mean, is it safe to assume I can create a Uint8Array from the responseText?  Here's a bit of that code for reference.

var buf = new ArrayBuffer(remote.responseText.length), i = 0;
var bufView = new Uint8Array(buf);
for (i, strLen = remote.responseText.length; i < strLen; i += 1) {
      bufView[i] = remote.responseText.charCodeAt(i);
}
$scope.fileArrayBuffer = buf;

**Comment by danialfarid** [comment]
There might be better way to handle it but if you are looking for a way to convert ArrayBuffer to File you can do:
`file = new Blob([buffer], {type: fileType});`

**Comment by gswartz777** [comment]
Ok, thank you.  And will 'file' then be useable by your upload method?  And I'm assuming fileType needs to be something like 'text/html'?

**Comment by danialfarid** [comment]
yes

**Comment by gswartz777** [comment]
Here is my updated code. 

This is part of the code that downloads from google drive.

$scope.$watchCollection('googleFiles', function (newGoogleFiles) {
    $scope.invalidResume = false;
    if (newGoogleFiles.length > 0) {

        var mimeType = newGoogleFiles[newGoogleFiles.length - 1].mimeType.toLowerCase();
        if (!$scope.isValidMimeType(mimeType)){
            $scope.invalidResume = true;
            return false;
        }
        var token = gapi.auth.getToken().access_token;
        var request = gapi.client.request({
            path: '/drive/v2/files/' + newGoogleFiles[newGoogleFiles.length - 1].id,
            method: 'GET',
            params: {
                alt: 'json',
                key: 'XXXXXXXXXXXXX',
                access_token: token
            }
        }).execute(function(file) {
            if (file.error) return;
            var url = file.downloadUrl;
            if (mimeType === 'application/vnd.google-apps.document'){ //this is a native google doc, not an uploaded file, so grab the pdf version of the file
                url = file.exportLinks['application/pdf'];
            }

            if (url !== undefined) {
                var remote = new XMLHttpRequest();
                remote.open('GET', url);
                remote.setRequestHeader('Authorization', 'Bearer ' + token);
                remote.onload = function() {
                    $scope.filename = newGoogleFiles[newGoogleFiles.length - 1].name;
                    $scope.fileBlob = new Blob([remote.response], {type: mimeType});
                    $scope.$digest();
                };
                remote.send();
            }
        });
    }
});

And this is the updated fileSelected method when a local file is selected.

$scope.fileSelected = function (files) {
    if (files && files.length) {
        $scope.filename = files[0].name;
        var mimeType = $scope.determineMimeType(files[0].name);
        if (mimeType === ''){
            $scope.invalidResume = true;
            return false;
        }
        $scope.fileBlob = files[0];
        $scope.$digest();
    }
};

And finally, the updated upload code...

Upload.upload({
    url: hookApi.url + '/apply',
    fields: {
        'first_name' : $scope.firstName,
        'last_name' : $scope.lastName,
        'phone_number' : $scope.phoneNumber
    },
    file: $scope.fileBlob
}).success(function (data, status, headers, config) {
    deferred.resolve(data);
});

When I submit the form (calling the upload method) after selecting a local file, it all works fine.  However, if I submit the form with a google drive object or dropbox object, it doesn't seem to post the blob file.

Interestingly I did a console.log of $scope.fileBlob within the local file system select and when I do that, it comes back with the full file object with the name, etc.  But if I do that with either google or dropbox, it comes back as a Blob object with no filename or anything - which I'm not sure if that's expected or not.  So, do you have any idea why the uploader wouldn't be uploading it when it's a blob?  Thanks so much for all of your help!

**Comment by danialfarid** [comment]
Can you see what is being sent in case of google drive in your network tab.
You can also set the `fileName` and `fileFormDataName` in the options.

**Comment by gswartz777** [comment]
Yes. Aside from the content-type it looks nearly identical to the local file.  Here's the google drive attachment 

![chrome-tools](https://cloud.githubusercontent.com/assets/4447393/7597962/28fa18d4-f8c5-11e4-88c5-1f2465519ce7.gif)

and here's the local file
![local](https://cloud.githubusercontent.com/assets/4447393/7597967/39bcde86-f8c5-11e4-88ce-7e1bdf78b7ae.gif)

**Comment by danialfarid** [comment]
Well looking at the request headers and payload it does send the file correctly. So what is not working? Do you receive the file on the server?

**Comment by danialfarid** [comment]
In both cases you have a 500 internal error so maybe it is an error on the server.

**Comment by gswartz777** [comment]
Yes, there seems to be a problem requesting a pdf version of a google doc and that's what is causing my problem.  The html version is fine.  Anyway, not related to the ng file upload, so thank you again very much for your help!
