### ISSUE TITLE
Main image with multiple thumb images

### ISSUE THREAD

**Issue by Satif** [danialfarid/ng-file-upload#736]
![home page - google chrome 2015-05-13 13 14 34](https://cloud.githubusercontent.com/assets/6329929/7608426/32b05c00-f972-11e4-9d9d-9a555461c9fd.png)

I have a main image (on top), that load, after i select file from input field. Than file store to mysql db and output images (ng-repeat) to bottom list. 
On bottom image click i must replace main image with file from db. How can i do this?

**Comment by danialfarid** [comment]
return the id of the image stored in mysql and when the user clicks on it replace the id of the main image in your database.
