### ISSUE TITLE
NOT loading ngfileupload

### ISSUE THREAD

**Issue by archanamaddineni** [danialfarid/ng-file-upload#738]
[$injector:modulerr] http://errors.angularjs.org/1.3.10/$injector/modulerr?p0=viewConfigApp&p1=%5B%24injector%3Amodulerr%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.3.10%2F%24injector%2Fmodulerr%3Fp0%3DviewConfigTableControllers%26p1%3D%255B%2524injector%253Amodulerr%255D%2520http%253A%252F%252Ferrors.angularjs.org%252F1.3.10%252F%2524injector%252Fmodulerr%253Fp0%253DviewConfigDetails%2526p1%253D%25255B%252524injector%25253Amodulerr%25255D%252520http%25253A%25252F%25252Ferrors.angularjs.org%25252F1.3.10%25252F%252524injector%25252Fmodulerr%25253Fp0%25253DangularFileUpload%252526p1%25253D%2525255B%25252524injector%2525253Anomod%2525255D%25252520http%2525253A%2525252F%2525252Ferrors.angularjs.org%2525252F1.3.10%2525252F%25252524injector%2525252Fnomod%2525253Fp0%2525253DangularFileUpload 
angular.min.js, line 35 character 519

I am getting the above issue when i try to load my app in IE9 and its blocking entire app from loading. I am using angular 1.3.10 and fileupload 4.2.0
I have included file api and .swf files also.
it works fine in other browsers

**Comment by danialfarid** [comment]
Make sure you inject ngFileUpload not angularFileUpload.

**Comment by archanamaddineni** [comment]
Thank you for quick reply. Figured it out later on
