### ISSUE TITLE
412 (Precondition Failed)

### ISSUE THREAD

**Issue by tUrG0n** [danialfarid/ng-file-upload#739]
Hey guys,

I am uploading a file to s3 using the plugin, however, I received a `412 (Precondition Failed)` error once the upload is done.
Any idea what might be causing this?

Thank you!

**Comment by danialfarid** [comment]
It is a server side issue

**Comment by seshunivarthi** [comment]
@danialfarid I know it is a closed issue. But, do you know what might be the issue on server side?
