### ISSUE TITLE
only allowing dragged files to active drag-over class

### ISSUE THREAD

**Issue by rohanbhangui** [danialfarid/ng-file-upload#741]
I found this weird issue where if i click and select some text on my page and then drag it, the dragoverclass gets activated. I have the drop feature set to my window right now. Any way to work around this?

**Comment by danialfarid** [comment]
You can use ngf-drag-over-class to specify a separate accept and reject class. If the dragged item is not a file it would be rejected. See the readme and the demo page for example. You can just have empty reject class or set it to a class to show the dragged item is not valid.

**Comment by rohanbhangui** [comment]
So if it is a file would the  ngf-drag-over-class get cancelled (aka be turned off?)

**Comment by danialfarid** [comment]
it would use the accept class

**Comment by rohanbhangui** [comment]
okay, cause what I need is to accept all files but not accept selected text that is dragged into the window (my drag and drop is on the body)

**Comment by danialfarid** [comment]
yea just look at the demo page html

**Comment by rohanbhangui** [comment]
Yeah I think I got it, im pretty sure you are able to pass a function as an accept arguement

**Comment by danialfarid** [comment]
you can just have ` ngf-drag-over-class="{accept:'fileDragOver, reject:'textDragOver}`

**Comment by rohanbhangui** [comment]
@danialfarid  my filter seems to not work for drag and drop is this correct:

<code>
ngf-accept="file_extension|audio/*|video/*|image/*|media_type"
</code>

I am trying to get a filter for all files (not including dragged in content)

I know in the demo you disable the dragenter and leave events because you are dragging only to a certain area. However dragenter and dragleave cannot be disabled when dragging to the body (which is my case)

**Comment by danialfarid** [comment]
If you accept all files you don't need to set ngf-accept

**Comment by rohanbhangui** [comment]
But that doesn't prevent me from dragging text into the upload drop area

**Comment by danialfarid** [comment]
If you add ngf-drag-over-class the way I described before, it would.
```
	<div ngf-drop ng-model="files"  ngf-drag-over-class="{accept:'dragover'}">
```

**Comment by rohanbhangui** [comment]
@danialfarid I did it that way and the text bug still exists:  http://733ecfab.ngrok.com

**Comment by danialfarid** [comment]
How do you reproduce it on that page?

**Comment by rohanbhangui** [comment]
well if you click and drag the text, on the page and try to drag it on the page the "drag over class" gets activated (think it might have to do with the error in the console, not sure

**Comment by rohanbhangui** [comment]
i think right now because the filter is producing an error it wont let files be dragged over

**Comment by danialfarid** [comment]
Once you have a reproducible example I'll have the look, but the code I posted above works you can just try it in the demo page.

**Comment by rohanbhangui** [comment]
yeah so one thing i noticed is that for the ngf-accept (specifically for drag and drop) you have it set to an input via the ng-model, however when i go to do so (without the model but inserting the accepted file types manually) it doesnt work. The link is working now because I have <code>...ngf-accept="media_type"...</code> however if i make a selection on the page and I try to select and drag the drag over class activates

**Comment by danialfarid** [comment]
I provided you with the working example, so you should be able to figure out what is going wrong in your case,

**Comment by rohanbhangui** [comment]
sure thanks
