### ISSUE TITLE
Upload to amazon S3 pre-signed url

### ISSUE THREAD

**Issue by Mistrall** [danialfarid/ng-file-upload#743]
I need to upload file to Amazon S3 via pre-signed url.
I've checked via curl and was able to upload files successfully.

Unfortunately upload via Upload.upload method fails each time with 403 Forbidden.
**Do you have an example uploading to pre-signed S3 URL?**

Details:
Here is how I get pre-signed url
```javascript
// Load the AWS SDK for Node.js
var AWS = require('aws-sdk');
/**
 * Export the following environment variables:
 *
 * export AWS_ACCESS_KEY_ID='AKID'
 * export AWS_SECRET_ACCESS_KEY='SECRET'
 */

// Set your region for future requests.
AWS.config.region = 'us-west-2';

var s3 = new AWS.S3();
var params = {Bucket: 'your-bucket-name', Key: 'file2', Expires: 3600};
var url = s3.getSignedUrl('putObject', params);
console.log(url);
```
Resulted pre-signed url looks like this: 
https://your-bucket-name.s3-us-west-2.amazonaws.com/file2?AWSAccessKeyId=AKID&Expires=1431709638&Signature=TWgv9o7esxqhDlBxJuhYNZhCmlM%3D

Bucket config looks like this
```xml
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>POST</AllowedMethod>
        <AllowedMethod>PUT</AllowedMethod>
        <AllowedMethod>DELETE</AllowedMethod>
        <MaxAgeSeconds>3000</MaxAgeSeconds>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
```

**Comment by danialfarid** [comment]
Can you compare the headers of your curl that is working with the request that is being sent with this plugin (use chrome netwerk tab to see the request) or post them here.

**Comment by Mistrall** [comment]
Sorry for misinformation, issue was on Amazon side, when generating pre-signed url it should include file content-type. Once I added it issue was resolved.

**Comment by Guiiks** [comment]
Hello @Mistrall :)

I'm trying to do it the same way. My signedUrl is ok but if I execute the following code :

**Comment by Mistrall** [comment]
Hey @Guiiks 
Here is how I upload to S3 (I'm using typescript)
```javascript
    export class FileUploadService {
        /* @ngInject */
        constructor(private Upload : ng.fileUpload.IUploadService,
                    private $http : ng.IHttpService) {
        }

        public upload<T>(file : File, url : string) : ng.fileUpload.IHttpProgressPromise<T> {
            return this.Upload.http({
                method           : 'PUT',
                url              : url,
                headers          : {
                    'Content-Type' : file.type
                },
                data             : file
            });
        }
```
Issue was not with ng-upload but with Content-Type parameter of URL (see below)
Url for upload is generated by AWS SDK should look like this
https://<your bucket>.s3.amazonaws.com/<path>/<filename>?Content-Type=image%2Fjpeg&AWSAccessKeyId=<aws AccessKeyID>&Expires=1436809879&Signature=7nmKbAIyNDMVYQixOL0yMEPS3Ck%3D

**Comment by Guiiks** [comment]
Hello @Mistrall,

Thanks for the code ;) I'll try it in the next few days!
Indeed, the content-type wasn't in my signed url, now it should be resolved!

Thanks again,
Best,

**Comment by kvetis** [comment]
hi, sorry for the late comment, but it should be mentioned in this topic: The problem with amazon signed URL is that it expects raw data, so if you use `Upload.upload` method data is sent using multipart/form data. Even if you set the content-type right, the whole data is sent there. Use raw data upload - `Upload.http` so the data does not get corrupted.

**Comment by gunar** [comment]
Holy macaroni that saved my day, @kvetis. Thank you!

**Comment by tonycurwen** [comment]
@kvetis very useful.

I also came unstuck with 403 errors from S3 and eventually found that I had the wrong minimum bucket policy configured. II was missing the PutObjectAcl permission. So for other folks that find this thread you need the following as a minimum:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:PutObjectAcl"
            ],
            "Resource": [
                "arn:aws:s3:::YOUR_BUCKET_ID_HERE/*"
            ]
        }
    ]
}
```

**Comment by nmarcetic** [comment]
@kvetis Thank you for Upload.http suggestion.

**Comment by rushglen** [comment]
Thanks Mistrall, your comment about adding Content-Type to the url worked for me too!

**Comment by ShrJoshi28** [comment]
I have error for headers: {
        "Content-Type": file.type != '' ? file.type : 'application/octet-stream'
    },

how to slove this error 
and also get the error like this {"message": "Internal server error"}

**Comment by ShrJoshi28** [comment]
@Mistrall  I have error this: Access to XMLHttpRequest at 'https://4kd2hi3ere.execute-api.us-east-1.amazonaws.com/default/myfirstvuecode' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
please help

**Comment by ShrJoshi28** [comment]
@Mistrall  I changes CORSConfiguration having following errors
At front end-
Access to XMLHttpRequest at 'https://4kd2hi3ere.execute-api.us-east-1.amazonaws.com/default/myfirstvuecode' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
lambda.js?ba28:16 Error: Network Error
at createError (eval at (app.js:798), :15:15)
at XMLHttpRequest.handleError (eval at (app.js:780), :87:14)

And in CloudWatch -
05:21:52
START RequestId: 26c51933-b1e7-43a9-be6d-5b34e70989ad Version: $LATEST
START RequestId: 26c51933-b1e7-43a9-be6d-5b34e70989ad Version: $LATEST

05:21:52
END RequestId: 26c51933-b1e7-43a9-be6d-5b34e70989ad
END RequestId: 26c51933-b1e7-43a9-be6d-5b34e70989ad

05:21:52
REPORT RequestId: 26c51933-b1e7-43a9-be6d-5b34e70989ad	Duration: 225.02 ms	Billed Duration: 300 ms Memory Size: 128 MB	Max Memory Used: 33 MB
REPORT RequestId: 26c51933-b1e7-43a9-be6d-5b34e70989ad	Duration: 225.02 ms	Billed Duration: 300 ms Memory Size: 128 MB	Max Memory Used: 33 MB

Please help.

**Comment by guillermomezzano** [comment]
I have the same problem I'm using javascript like this
`await Axios.put(data.uploadUrl, file, {
              headers: {
                'Content-Type': file.type,
              },
            });`
            

and i have these permissions in serverless
 
` Action:
            - 's3:PutObject'
            - 's3:PutObjectAcl'`
            
and finally these permissions in the s3 bucket
 
` [
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "PUT"
        ],
        "AllowedOrigins": [
            "http://localhost:3000"
        ],
        "ExposeHeaders": [
            "ETag"
        ]
    }
]`

**Comment by kvetis** [comment]
@guillermomezzano please use stackoverflow to ask for general programming support. Your question is unrelated to ng-file-upload.
