### ISSUE TITLE
Browser files open twice with ionic framework

### ISSUE THREAD

**Issue by root-io** [danialfarid/ng-file-upload#744]
Try this plnkr with Chrome or Firefox for Android

http://embed.plnkr.co/xrQXOuFncBBA7c1R5t0W/preview

**Comment by Jaware** [comment]
yes i met the problem too囧

**Comment by Jaware** [comment]
it is ok on pc while both android and ios open file dialog twice,the first dialog can not work,only the second dialog can upload file

**Comment by Jaware** [comment]
<div class="button" ngf-select ngf-change="upload($files)">Upload on file change</div>

$scope.upload = function (files) {
        if (files && files.length) {.........}
}

**Comment by danialfarid** [comment]
@root-io 
Can you add `return false;` after this line:
https://github.com/danialfarid/ng-file-upload/blob/master/dist/ng-file-upload.js#L299
and see if it changes anything?

**Comment by Jaware** [comment]
i tried,still twice

**Comment by danialfarid** [comment]
If you change `button` to` input type="file"` would it work?

**Comment by root-io** [comment]
@danialfarid Yes, works fine with an input file, but not with button and image for example

**Comment by danialfarid** [comment]
So if the button works on android browser without ionic then ionic probably does something special for the android browser, you can ask the question on their github we might find a clue from there.

**Comment by root-io** [comment]
Ok @danialfarid, thanks for your time, I'll ask them ;)

**Comment by Jaware** [comment]
have you found any solution @root-io

**Comment by root-io** [comment]
Yes, dirty hack:

```
.directive('upload', function() {
  return {
    restrict: 'E',
    link: function(scope, element) {
      element.find('button').bind('click', function() {
        element.find('input')[0].click();
      });
    }
  };
})
```
```
<upload>
  <input ng-hide="true" type="file" ngf-select ngf-change="upload($files)" />
  <button type="button">Upload</button>
</upload>
```

**Comment by Jaware** [comment]
thanks, good thought,nice way ^-^

**Comment by hassanbazzi** [comment]
You can use a label because label clicks propagate to their corresponding inputs anyways ;)
