### ISSUE TITLE
How to send JSON object to web service?

### ISSUE THREAD

**Issue by codewzrd** [danialfarid/ng-file-upload#746]
A JAVA web service I am calling requires that I send it a JSON object. The service requires it to be a POST and it accepts "application/json".

The object looks like this:
```javascript
{
    id: null,
    ticketID: 12345,
    filename: 'filename from selected file',
    desc: 'file name without extension',
    attachment: byte array of file content
}
```
I am trying to use the upload.http() method i see that the  the attachment is empty in the request parameter view of the browser's Network tab.
```javascript
{"id":111619,"ticketID":"NewCorpActions.xlsx","desc":"NewCorpAction","attachment":{}}
```
```javascript
    this.attachFileToTicket = function(ticket, files) {
        // Really only 1 file
        for (var i = 0; i < files.length; i++) {
            var file = files[i];

            return uploadSvc.http({
                url: '/ticket/attachFile',
                headers : {
                    'Content-Type': undefined
                },
                data: { 'id': ticket.id, att_filename: file.name, att_desc: file.name.substr(0, file.name.lastIndexOf('.') - 1), attachment: file }
            });
        }
    }
```
Any help would be greatly appreciated. Thanks.

**Comment by danialfarid** [comment]
You cannot have additional data with `Upload.http`. It just sends the file binary content in the body of the request so the only way is to specify the params in the url.

**Comment by farlee2121** [comment]
A few years late, but ASP.NET MVC can map data just fine if you submit as a form. `Upload.upload` submits as a form and takes extra parameters.

I have a working example that looks about like
```js
Upload.upload({
  url: '/something',
  data: { ticketId: 5, files: files}
});
```

```cs
[HttpPost]
public JsonResult Something(int ticketId, IEnumerable<HttpPostedFileBase> files){
...
}
```
