### ISSUE TITLE
Using ngf-select on type=file is not automation friendly

### ISSUE THREAD

**Issue by veekey** [danialfarid/ng-file-upload#748]
In my case we don't want our user to see the 'file' widget, but only browse button. 

Intially i used ngf-select on the button but then the problem with this is we cannot use selenium to upload file during automation, as clicking on button opens native file selection window and the selenium driver cannot perform a grab on the native file selection window. The workaround for this is to use 

**Driver.FindElement(By.CssSelector("input[type='files']")).SendKeys("FilePath")**

Now to use above approach i created a file widget with display:none. And on click of browse button we are invoking the click on hidden file element.

Now ng-upload is replacing the file element with its own element and not propagting **id,style,class** attributes to the new element.

Is there any reason that these attributes are not propagated?

**Comment by danialfarid** [comment]
That issue was fixed, use the latest version.

**Comment by nehaabrol87** [comment]
Our automation QA is facing the same issue.
What version  was it fixed in.
We are at 12.2.13
