### ISSUE TITLE
ngf-change/ng-model not registering changes in ie9 (or in flash)

### ISSUE THREAD

**Issue by kadowki** [danialfarid/ng-file-upload#749]
$files and $event are undefined in IE9 (or in flash), ngf-change also does not fire. ng-model inside $watch is not registering either.

HTML
``button(accept='image/*', ngf-select, ngf-change='initPhoto($files, $event, $index)' ) Click to Select Upload``

In debug mode on Chrome, the same behavior is also present. For IE9, flash is installed and can right-click to verfiy. It will pop up and allow me to choose a photo, but it does nothing once chosen. No console.log or anything inside initPhoto().

Any advice?

**Comment by danialfarid** [comment]
Follow the demo page as an example, you can click on edit html and create a custom button there to see if it works.
Otherwise you can create a jsfiddle so I could see how your code is.

**Comment by kadowki** [comment]
@danialfarid I was using blueimp canvas-to-blob  to flip image previews based on EXIF data and it was messing with it. The polyfills that were being used were working properly, but it wasn't throwing any errors at all. I discovered this while I was making a jsFiddle for you, haha. Sorry for the false alarm and thank you for being responsive. Your directive has saved my ass quite a few times.
