### ISSUE TITLE
IE8 response 406 error

### ISSUE THREAD

**Issue by gsugiart** [danialfarid/ng-file-upload#750]
Hi Danial, when I tried to do file upload in IE8, it was able to successfully upload the file but for some weird reason the response that I got from my server is 406 error even when there is no exception in my Java app server:
 IOErrorEvent type="ioError" bubbles=false cancelable=false eventPhase=2 text="Error #:[IOErrorEvent type="ioError" bubbles=false cancelable=false eventPhase=2 text="Error #2038.

Have you ever seen such error? Below is the error that I put in Javascript alert:

![image](https://cloud.githubusercontent.com/assets/136661/7753976/bdfc1318-ff9d-11e4-9b66-6433a9476e24.png)

**Comment by danialfarid** [comment]
What the response from your server looks like? Do you return any body in your response from the server?

**Comment by gsugiart** [comment]
I returned a JSON like the following:
{"success":true,"messages":[],"vault":null,"artifact":null}

**Comment by gsugiart** [comment]
Nevermind, this is a server side error. For some weird reason my Java Spring MVC framework is responding differently when Flash do file upload vs. just using HTML5 FormData. I used to return plain Java object and Spring MVC will automatically convert to JSON. When Flash is doing upload, for some weird reason the JSON converter failed. As a work around, I manually convert the Java object to JSON instead of relying on Spring MVC. thanks anyway.
