### ISSUE TITLE
File with accented characters in name not working

### ISSUE THREAD

**Issue by amairi** [danialfarid/ng-file-upload#754]
Hello,
i want to upload file with with accented characters in name, but not working.
for example :  éèà.pdf

thank you for your support
BR

**Comment by danialfarid** [comment]
What is not working?

**Comment by amairi** [comment]
the file name is changed, his turns as "nb Ã©Ã Ã§u.pdf"
I think it's a problem of encoding

**Comment by danialfarid** [comment]
Upload the file using the demo page and click on the details of uploaded file, if it shows the correct name then the problem is probably in your server or js code.
