### ISSUE TITLE
ngf-drag-over-class always applies 'reject' class

### ISSUE THREAD

**Issue by aderowbotham** [danialfarid/ng-file-upload#757]
When passing an object to **ngf-drag-over-class** as follows:
`ngf-drag-over-class="{ accept:'dragover', reject:'dragover-err', delay:100}" `
and with
`ngf-accept="'.jpg,.png'"`

The `reject' class is applied on dragover in *all cases*, regardless of whether the dragged files are accepted.

If **ngf-drag-over-class** is set to the string 'dragover' instead of using the object syntax then this does work and the dragover class is added.

AngularJS v1.3.15
Chrome 43.0.2357.65
OS X 10.10.3

JS Fiddle: https://jsfiddle.net/m9kyubty/

**Comment by danialfarid** [comment]
It works only on file type, it was in the docs I made it more clear.

**Comment by aderowbotham** [comment]
Apologies - I don't understand.

I *want* it to work on file type. e.g. I drag and drop an mp3: turn red, I drag and drop an image: turn green.

Right now I can't get it to show the 'accept' class at all. It always adds the 'reject' class on dragover.

**Comment by danialfarid** [comment]
Thanks,
Updated the example and readme to be more clear.
