### ISSUE TITLE
ngf-change gets called as soon as button is clicked

### ISSUE THREAD

**Issue by lookfirst** [danialfarid/ng-file-upload#762]
The documentation suggests that `ngf-change` would be called after the files are selected in the chooser dialog. Right now, it gets called as soon as the button is clicked.

**Comment by deckikwok** [comment]
You are right though I wont say it's an error. I believe if your model did not specify null initially then a 'change' would have been detected.  For now, you can do an if (file && file.length)

**Comment by danialfarid** [comment]
Updated the wordings in the doc.

**Comment by lookfirst** [comment]
Please re-open. This can't possibly be the intended behavior. Not only does it fire before the file chooser opens, but also after.

**Comment by danialfarid** [comment]
Yea I explained it in the docs, it will be called when the files selected or cleared by clicking on the button.

**Comment by lookfirst** [comment]
@danialfarid What I'm seeing is that `ngf-change` is being called TWICE. Once when you click the button and the file chooser dialog opens and once when the dialog closes after selecting a file.

I added this to your fiddle...

```
    $scope.upload = function (files) {
        alert('called from upload. files is: ' + files);
```

Whatever is calling it shouldn't call it the first time. There is no reason to call $scope.upload if files is null. This would allow me to remove the null check and simplify things greatly.

**Comment by danialfarid** [comment]
I explained on my first comment why it needs to be set to null when you click on it. So it is expected behaviour.

**Comment by lookfirst** [comment]
It doesn't need to fire.

**Comment by danialfarid** [comment]
https://github.com/danialfarid/ng-file-upload/issues/764
