### ISSUE TITLE
How to send input texts to PHP with Upload

### ISSUE THREAD

**Issue by lcg51** [danialfarid/ng-file-upload#763]
Hi Im using ng-file-upload,for a project im developing. The issue is: How can I sent more data besides the file. In my form Im sending the data of the file and two text inputs to the server. Using the Upload method the file is sended without problem but the two inputs are not detected by the server.I don't know If Im sending wrong from the client or the server. Here's a part of my code.

That's how i send the file and the dat with upload:
 Upload.upload({
                    url: 'http://localhost/degusto/uploadRecipe.php',
                    file: file,
                    method: 'POST',
                    data: {
                    nombre: recipe.nombre,          
                    descrip: recipe.descrip},
                    headers: { 'Content-Type': 'application/x-www-form-urlencoded' }
...

Here's the server part(PHP):

$data = json_decode(file_get_contents('php://input'), true);

// Check if the two inputs are not null

if(isset($data['nombre']) && isset($data['descrip'])){

	$n = $data['nombre'];
	$d = $data['descrip'];
	$date = date('Y-m-d');

	$fichero = guardarImagen($_FILES['file'], 'img/',$_FILES['file']['name']);
					if($fichero=='')
					{
						$R = array( "error"=>"No se pudo guardar el fichero");
					}

...
}

**Comment by aderowbotham** [comment]
Include a `fields` property in the object passed to `Upload.upload()'.

Here is a working example from the project I am working on:

    Upload.upload({
      url: '/api/files/upload',
      fields: {
        'fileContext': 'product',
        'editMode': $scope.editMode,
        'productSeed': $scope.product.seed
      },
      file: files,
      fileFormDataName: 'files[]'
    }).progress(function (evt) {
      // ...
    }).success(function (data, status, headers, config) {
      //...
    });

**Comment by danialfarid** [comment]
From version 5.0.0 instead of setting `fileFormDataName` you can set `sendFieldsAs: "form"`
