### ISSUE TITLE
file upload not working

### ISSUE THREAD

**Issue by AntJanus** [danialfarid/ng-file-upload#765]
For some reason, with migrating to 4.x, my uploads completely stopped working, even after I migrated all of my code. Here's what my upload area looks like:

````html
<div ng-if="!folderUpload">
  <div 
    class="upload-area" 
    ngf-drop 
    ng-model="files" 
    ngf-drag-over-class="'is-active'"
    ngf-multiple="true"
    ngf-allow-dir="false">
  </div>
</div>
<div ng-if="folderUpload">
  <div 
    class="upload-area" 
    ngf-drop 
    ng-model="files" 
    ngf-drag-over-class="'is-active'"
    ngf-multiple="true"
    ngf-allow-dir="true">
  </div>
</div>
````

The controller has this code:

````js
$scope.$watch('files', function(files) {
  vm.upload = UploadManager.upload; //UploadManager is a wrapper for the Upload service
  vm.upload(files, progress, success);

  //other logic
});
````

When I try to drag over a file, the `is-active` class *does* get applied; however, the `files` model does not get accessed so the `$watch` doesn't get triggered. I decided to debug by showing the files `{{ files }}`, but nothing ever shows up. 

I tried `ngf-select` and various options but can't get it working.

Some other info:

1. the code is within a custom `uploadModal` directive.
2. using `ngf-change` seemed to sporadically work but ended up not working at all in the end.

Any ideas?

*note:* in the 3.x versions, everything worked flawlessly

**Comment by danialfarid** [comment]
https://github.com/danialfarid/ng-file-upload/issues/711

**Comment by AntJanus** [comment]
@danialfarid well, that is just appalling from Angular's side. Thanks for letting me know!
