### ISSUE TITLE
Click event not fired [almost always] on Android > 4.4.4

### ISSUE THREAD

**Issue by tsanko** [danialfarid/ng-file-upload#768]
line 299 (ng-file-upload.js) : if (navigator.userAgent.toLowerCase().match(/android/)) {
....
File select dialog does not appear. (or appear once in a blue moon / cannot find any pattern)
After removing the Android specific code - everything behaves as expected.
Tested with: S4 (4.4.4) Native Browser, S5(5.0) Chrome and Native Browser, MotoX (5.0) Chrome,
Chrome @ MAC w/ device mode for Nexus 5
...
Test page does not suffer this issue (simple layout and no other components? :) )

**Comment by danialfarid** [comment]
"Test page does not suffer this issue (simple layout and no other components?"
What test page?

**Comment by tsanko** [comment]
Project’s test/demo page. (https://angular-file-upload.appspot.com/ <https://angular-file-upload.appspot.com/>)
… just tried JSFiddle sample page (http://jsfiddle.net/3t50b3fw/ <http://jsfiddle.net/3t50b3fw/>) and don’t see any problems.

The code I mentioned does not seem to be needed for the later Android (cannot check versions earlier than 4.4.4). Maybe the check should be more granular than the very broad check for ‘android’?

**Comment by Johnnyrook777** [comment]
I was also experiencing the same issue in our app. Removing the android specific resolution resolved it on my Android 5 device using chrome.

**Comment by tsanko** [comment]
@Johnnyrook777: This is the original issue #647. Unfortunately I have no device with Android 4.2 to test browser's User-Agent string.

**Comment by danialfarid** [comment]
Gonna be fixed in the next version

**Comment by zk33** [comment]
こここきなこく

2015年6月4日木曜日、Danial Farid<notifications@github.com>さんは書きました:

> Gonna be fixed in the next version
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danialfarid/ng-file-upload/issues/768#issuecomment-108720258>
> .
>


-- 
山崎 貴明
ymzktkak@gmail.com
080-6530-9057

**Comment by danialfarid** [comment]
Fixed in version 5.0.0

**Comment by Johnnyrook777** [comment]
Thanks danialfarid :)
