### ISSUE TITLE
how to cancel a file in progress

### ISSUE THREAD

**Issue by a-birla** [danialfarid/ng-file-upload#769]

**Comment by danialfarid** [comment]
You can call `abort()` on the promise returned by Upload.upload().

**Comment by a-birla** [comment]
Where is it implemented in the repo?

**Comment by danialfarid** [comment]
See the readme file and the demo page example, on the demo page you can abort an upload if the file is long and you have enough time to click on it before the download finishes.

**Comment by louisamoros** [comment]
When I log the promise returned by `Upload.upload()` I don't see any `abort()` method. I tried to upload a big file to be able to cancel it according to the README file and your previous message, it didn't work. Maybe I missed something.
Here is my code:

    var upload = null;
    $scope.upload = function () {
        upload = Upload
            .upload({...})
            .progress({...})
            .success({...})
            .error({...})
            .then({...});
    };
    $scope.abortUpload = function () {
        console.log(upload); //no abort method
        upload.abort(); //doesn't work
    };

What am I doing wrong?

**Comment by danialfarid** [comment]
The promise returned by then() doesn't have the abort(). Assign it to upload before calling then on it.
