### ISSUE TITLE
ngf-select not working   in a template called by ng-view

### ISSUE THREAD

**Issue by XLacedaemonX** [danialfarid/ng-file-upload#770]
http://stackoverflow.com/questions/30496000/angular-ngf-select-fileupload-not-working-with-ngview

anyone has same problem ?

**Comment by danialfarid** [comment]
Can you create a jsfiddle showing this problem?

**Comment by XLacedaemonX** [comment]
yes I can.

but I don't know , on jsfiddle , how can I make  2 html page and  one
include the other ??

I need  2 html part to show it

2015-05-28 13:59 GMT+09:00 Danial Farid <notifications@github.com>:

**Comment by XLacedaemonX** [comment]
I found the way :) 

    watching model:
    <div class="button" ngf-select ng-model="files" ngf-multiple="multiple">Select File</div>
    on file change:
    <div class="button" ngf-select ngf-change="upload($files)" ngf-multiple="multiple">Select File</div>

ngf-change style is working well!!!!

$watch model is not working 

thx man!!

**Comment by p4priyanka** [comment]
Hi ,

I am calling one function on ngf-select which is like this--- ngf-select="uploadFiles($files, $invalidFiles)".
in $file , there is file details of upladed file.in that file, there is two extension.this issue is coming with only window.PLEASE give me solution and reason.

**Comment by p4priyanka** [comment]
Hi,
i am uploading file by  ngf-select="uploadFiles($files, $invalidFiles)". in $file, there is two times extension.
Please give me solution and what is the reason behind this?
