### ISSUE TITLE
Rejecting large files

### ISSUE THREAD

**Issue by benfoster** [danialfarid/ng-file-upload#771]
We need to implement file size validation that is specific to the file types. Currently we wrap the calls to ng-file-upload is our own service so it would be a good place to add this validation.

How would you recommend we do this? I spiked out the following which uses `$q` to return a rejected promise. This does mean we can no longer use the `.success`, `.progress` functions on the upload object so we'll have to fallback to the standard deferred API `.then(success, error, progress)`:

```
function mediaService($http, $q, $upload, config) {

    var MAX_GIF_SIZE = 4194304; // 4MB

    var service = {
      uploadFile: uploadFile,
    };

    return service;

    function uploadFile(siteId, file) {
      if (file.type == 'image/gif' && file.size > MAX_GIF_SIZE) {
        return $q.reject('The file ' + file.name + ' is too large. GIFs cannot be greater than 4MB in size.');
      }

      return $upload.upload({
        url: config.apiUri + 'sites/' + siteId + '/media',
        file: file
      });
    }
}
```

Would you approach this differently?

It would be nice if we could provide a filter/validation function to do this.

**Comment by danialfarid** [comment]
use `ngf-max-size` and `ngf-min-size`. See the readme page for sample.

**Comment by danialfarid** [comment]
or in your case you can use `ngf-accept="validate($files)"` and implement the validate method in your scopre.
