### ISSUE TITLE
Allow drag and drop for text

### ISSUE THREAD

**Issue by miskin200** [danialfarid/ng-file-upload#774]
Hi,

I would like to add an option for the users to drag and drop both text and images (or other files) to the same element.
But I encountered a problem when setting the directive on the element that contain text input elements inside it. Adding files is working like it should, but when I try to drag and drop text to those input elements it's not accepted - nothing happens.
Am I overlooking something here or it can not be set to accept plain text?

Thanks for the great plug in!

**Comment by danialfarid** [comment]
This is a plugin for file upload so dropping a text wouldn't make much sense for this plugin.
You could set the `ngf-stop-propagation` to false and then add another drop listener to the element to handle text drops.

**Comment by miskin200** [comment]
Hi,
Thank for you reply

Ngf-stop-propagation didn't work for me, so I came up with a different solution.
I've created a new directive and assigned it to the text input element.

That directive looks like this:

define([], function () {
    	 
    var dropTextDirective = function () 
    {  
		
        var dragdroptext = {};

        dragdroptext.restrict = 'A';
        
        dragdroptext.link = function(scope, element)
        {
			// convert current element to javascript DOM element
			var raw_element = angular.element(element)[0];
			
			var handleTextDrop = function(e)
			{
				// if text is being dragged allow it to be dropped on the element
				// and stop propagation - stop event to be handled by dropFilesDirective
				if ($.inArray('text/plain', e.dataTransfer.types) > -1)
				{
					e.stopPropagation();
				}
			};

			raw_element.addEventListener("dragover", handleTextDrop, false);
			raw_element.addEventListener("drop", handleTextDrop, false);

        };
		
		return dragdroptext;
	};
	
    return [dropTextDirective];
});

Thank for the great plug-in!
