### ISSUE TITLE
Usage of sendObjectsAsJsonBlob option leads to sending of invalid value to the server

### ISSUE THREAD

**Issue by montgomery1944** [danialfarid/ng-file-upload#777]
When using sendObjectsAsJsonBlob option ng-file-upload uses "formData.append(key, new Blob([val], {type: 'application/json'}));" code to add object to the form data. The problem is, that browser before sending the data converts object to string, which in case of normal object leads to sending of "[object Object]" string to the server.

Right now to fix this issue I have to pass "new String(angular.toJson(object))" to the upload method to omit the "angular.isString(val)" condition, which is adding string without the "application/json" type. Then the serialization is calling toString() method on the String object, which is returning the proper JSON representation of the object.

I think that the library should call "formData.append(key, new Blob([JSON.stringify(val)], {type: 'application/json'}));" to fix this issue.

**Comment by danialfarid** [comment]
Fixed in version 5.0.0,

**Comment by danialfarid** [comment]
Added option sendFieldsAs: 'json-blob'

**Comment by Ashlandky** [comment]
I’m looking for someone to review my wife’s files I have them on phone but I have no clue what I’m looking at . 606-315-6602
