### ISSUE TITLE
Authorization Headers / Caching

### ISSUE THREAD

**Issue by edweena** [danialfarid/ng-file-upload#778]
Hey guys, I know something similar was closed some time ago, but I'm having a hell of a time getting the transformRequest to delete the Authorization header IF I've logged into my app with JWT. 

Basically, it looks like the request is sending a cached version of Authorization headers, which transformRequest has zero effect on. 

If I clear my cache, the code works as expected. Any ideas for how to handle this? I'm not actually seeing where this header is being cached.

Here's my upload service code:

```
upload: function(file, awsParams, folder){
        var deferred = $q.defer();
        var self = this;
        var folderName = self.imgFolder;

        console.log(awsParams);

        if (folder === 'files'){
          folderName = self.fileFolder;
        }

        Upload.upload({
          url: self.url,
          method: 'POST',

          transformRequest: function(data, headersGetter){


            // ------------------------------------------------
            // Change headers
            //
            var headers = headersGetter();
            // delete headers.authorization;
            delete headers['Authorization'];

            
            return data;

          },

          fields: {
            key: folderName + file.name,
            AWSAccessKeyId: awsParams.AWSAccessKeyId,
            acl: 'public-read',
            policy: awsParams.s3Policy,
            signature: awsParams.s3Signature,
            'Content-Type': file.type,
            'success_action_status': 201
          },

          file: file
        

        }).progress(function(evt){
          var progressPercentage = parseInt(100.0 * evt.loaded / evt.total, 10);

          $rootScope.$broadcast('progressPercent', progressPercentage);


        }).success(function(response){

          console.log(response);

          // ------------------------------------------------
          // Convert XML to JSON
          //
          var jsonResponse = xml2json.parser(response);
          deferred.resolve(jsonResponse);
          
        }).error(function(err){
          // ------------------------------------------------
          // Convert XML to JSON
          //

          console.log(err);

          var jsonResponse = xml2json.parser(err);
          console.log(jsonResponse);
          deferred.reject(jsonResponse);
          
        });

        return deferred.promise;
      },
```

Any ideas would be super appreciated.

**Comment by danialfarid** [comment]
Why do you add "Athorization" header at first place? The way you are removing it sounds fine though. 

Can you post the content of the requests you are sending from netwrok tab.

**Comment by edweena** [comment]
I'm not adding the Authorization header explicitly at all. I'm running into the same problem as [Issue 382](https://github.com/danialfarid/ng-file-upload/issues/382).

Request headers attached.

![response](https://cloud.githubusercontent.com/assets/4332285/7946777/ff57e032-0978-11e5-9e3e-8512c9c38ff7.png)
![payload](https://cloud.githubusercontent.com/assets/4332285/7946778/02d43f26-0979-11e5-8705-edeb8e0c6e4a.png)

**Comment by edweena** [comment]
Ok, i slightly lied here I just realized... I am adding the auth header in an $http interceptor at runtime. I'm guessing that the transformRequest doesn't work since the header is being appended after the fact, based on whether or not a cookie exists. Closing this, as I don't think it's a problem with ng-file-upload. Thanks
