### ISSUE TITLE
 ngf-multiple="true"  not working on android devices 

### ISSUE THREAD

**Issue by naqvisyed** [danialfarid/ng-file-upload#780]
Hi 

ngf-multiple="true"  not working on android devices even the demo is also not working for multiple selection https://angular-file-upload.appspot.com/

**Comment by ishworthapaliya** [comment]
+1

**Comment by emadd** [comment]
+1

**Comment by danialfarid** [comment]
http://caniuse.com/#feat=input-file-multiple
