### ISSUE TITLE
 Failed to instantiate module ngFileUpload

### ISSUE THREAD

**Issue by amicos** [danialfarid/ng-file-upload#781]
I instaled ngFileUpload with npm 
but i had this issue , who can help me?

Uncaught Error: [$injector:modulerr] Failed to instantiate module webappApp due to:
Error: [$injector:modulerr] Failed to instantiate module ngFileUpload due to:
Error: [$injector:nomod] Module 'ngFileUpload' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.15/$injector/nomod?p0=ngFileUpload
   ............

I add ngFileUpload as dependence in my  JS file :

var app = angular
  .module('webappApp', ['ngCookies',
    'ngResource',
    'ngRoute','ngFileUpload'

I have the "ng-file-upload" in node_modules....

**Comment by danialfarid** [comment]
It could be a syntax error in your js code, try with just including the module with empty controller body.

**Comment by amicos** [comment]
I get the error just after adding the module in js file. I think perhaps the "ngFileUpload" is not installed as it must be!

**Comment by danialfarid** [comment]
Is the ng-file-upload.js loaded in your browser from network tab?

**Comment by amicos** [comment]
I use http server by Grunt in localhost way.

**Comment by amicos** [comment]
I tried to add another module I got the same error! how to force the loading of modules in my browser?

**Comment by amicos** [comment]
I load ng-file-upload-all.js befor angular.js. That was my mistake.
Thanks for your help. You can close this issue

**Comment by etischler** [comment]
How did you change the order that i loaded in @amicos
