### ISSUE TITLE
__setXHR_  for what 

### ISSUE THREAD

**Issue by wushijing2011** [danialfarid/ng-file-upload#787]
This is my  upload image header ：

__setXHR_:function (a){a&&(d.__XHR=a,d.xhrFn&&d.xhrFn(a),a.upload.addEventListener("progress",function(a){a.config=d,e.notify?e.notify(a):f.progress_fn&&c(function(){f.progress_fn(a)})},!1),a.upload.addEventListener("load",function(a){a.lengthComputable&&(a.config=d,e.notify?e.notify(a):f.progress_fn&&c(function(){f.progress_fn(a)}))},!1))}

![image](https://cloud.githubusercontent.com/assets/1777299/7976212/b9d41bb0-0aaa-11e5-8d4c-b6ca7f779920.png)

This header is for what? 

Thanks!

**Comment by danialfarid** [comment]
Do you use other libraries that wrap or modify the XMLHttpRequest?

**Comment by wushijing2011** [comment]
Thanks for your answer!

I found the reason!
I use this package (https://github.com/HubSpot/pace)
It rewrite the function "window.XMLHttpRequest" 
But I  still to know this header's function.
There may be some compatibility problems.

**Comment by danialfarid** [comment]
That header function is to allow monitoring progress event on the underlying angular xhr object.

**Comment by wushijing2011** [comment]
Thanks a lot !
