### ISSUE TITLE
Use external scope in ulpoad function.

### ISSUE THREAD

**Issue by charlou28** [danialfarid/ng-file-upload#788]
Hi,

I have a problem to use external value of upload function.

For example, I need an other information in my url.
But I change this value before to upload my file. It's to select the folder's category.

If I print value in upload. This value has not changed.

code:
var app = angular.module('fileUpload', ['ngFileUpload']);

app.controller('MyCtrl', ['$scope', 'Upload', function ($scope, Upload) {

--> $scope.otherInfo = "toto";

-->$scope.changeValue = function()
   {
     $scope.otherInfo = "titi";
   }

    $scope.$watch('files', function () {
        $scope.upload($scope.files);
    });

    $scope.upload = function (files) {
        if (files && files.length) {
            for (var i = 0; i < files.length; i++) {
                var file = files[i];
                Upload.upload({
--->                    url: 'upload/url/ + $scope.otherInfo', //otherInfo stay "toto"

                    fields: {'username': $scope.username},
                    file: file
                }).progress(function (evt) {
                    var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
                    console.log('progress: ' + progressPercentage + '% ' + evt.config.file.name);
                }).success(function (data, status, headers, config) {
                    console.log('file ' + config.file.name + 'uploaded. Response: ' + data);
                });
            }
        }
    };
}]);

Thx for your help.

Charles.

**Comment by danialfarid** [comment]
Could you create a jsfiddle showing the error from the sample on the readme? It's hard to find the problem with partial code.
