### ISSUE TITLE
Set drop/select readonly on some scope condition

### ISSUE THREAD

**Issue by Mistrall** [danialfarid/ng-file-upload#789]
Hey Danial!

Is it possible to set ngf-drop, ngf-select disabled on some scope conditions?
Like this 
```html
<div ng-init="enableSelect=false">
       <div ngf-drop ngf-select="enableSelect" ng-model="model" ></div>
</div>
```
I need this drop areas to be readonly on some point

**Comment by danialfarid** [comment]
Added feature in version 5.0.0, as you suggested here.

**Comment by Mistrall** [comment]
Great!
Thanks for following up on this.

**Comment by danialfarid** [comment]
This feature now move to `ngf-select-disabled` and `ngf-drop-disabled` directives.
