### ISSUE TITLE
Authentication with JWT causes invalid JSON?

### ISSUE THREAD

**Issue by gwilakers** [danialfarid/ng-file-upload#790]
I have an Angular / Node app and was using ng-file-upload with success up until I added authentication using jwt. Now, I am continuing to get invalid json errors during uploads no matter what I try. Is there a known issue with this or a work around that people normally use? Thanks.

**Comment by danialfarid** [comment]
Please post your code here or create a jsfiddle with more information about versions and error messages.

**Comment by gwilakers** [comment]
```
angular.module('app').controller("UploadController", [ '$scope', 'Upload', function($scope, Upload) {
    $scope.log = '';
    $scope.$watch('files', function () {
        $scope.uploadFile($scope.files);
    });
    $scope.uploadFile = function(files) {
        if (files && files.length) {
            for (var i = 0; i < files.length; i++) {
                var file = files[i];
                Upload.upload({
                  url: '/admin/upload',
                  file: file,
                  headers: {
                    'Content-Type': 'application/json'
                  }
                }).progress(function (evt) {
                    var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
                    $scope.log = 'progress: ' + progressPercentage + '% ' + evt.config.file.name + '\n' + $scope.log;
                }).success(function (data, status, headers, config) {
                  console.log(data);
                    $scope.log = 'File ' + config.file.name + ' uploaded.';
                }).error(function(data, status, headers, config) {
                  console.log(config);
                  console.log("Error: " + data);
                });
            }
        }
    };
}]);
```

Looking in the Developer Console on Chrome, I am seeing this error:

![image](https://cloud.githubusercontent.com/assets/2496236/7991497/858274c6-0ac6-11e5-84e5-fe70d0a3062c.png)

**Comment by gwilakers** [comment]
Also on a side note, I am using authentication with this route, so there is should be a jwt and username passed, however, now there is this __setHXR_ inside the header along with the content-type undefined. That's it. What is the hxr thing?

**Comment by danialfarid** [comment]
Try including ng-file-upload after your other js files.

**Comment by danialfarid** [comment]
That is needed to enable progress event in angular

**Comment by gwilakers** [comment]
Including it after all of the other files produced the same results. The __XHR in the header is the only difference between my requests that are passing and the one that is failing.

**Comment by danialfarid** [comment]
Could you narrow down the issue and create a jsfiddle? This is probably a conflict with another library that is modifying the XMLHttpRequest

**Comment by gwilakers** [comment]
I'm not sure how I would put this into a fiddle, but I know that the only other file modifying the XMLHttpRequest is this piece of code that modifies the header of every request:

```
angular.module('app').factory('TokenFactory', function($q, $sessionStorage) {
    return {
        request: function(config) {
            config.headers = config.headers || {};
            if ($sessionStorage.token) {
                config.headers['X-Access-Token'] = $sessionStorage.token;
                config.headers['X-Key'] = $sessionStorage.user;
                config.headers['Content-Type'] = "multipart/form-data";
            }
            return config || $q.when(config);
        },
        response: function(response) {
            return response || $q.when(response);
        }
    };
});
```

**Comment by gwilakers** [comment]
The Content-Type was application/json prior to this comment, but I have been changing it to see what different errors it gives.

**Comment by gwilakers** [comment]
Alright I figured out the issue. I removed this line from the snippet above:
```
config.headers['Content-Type'] = "application/json";
```

That allowed the headers to be set appropriately. Sorry for the confusion!
