### ISSUE TITLE
Undesired scrolling bars when the body uses a flex layout

### ISSUE THREAD

**Issue by yellowiscool** [danialfarid/ng-file-upload#796]
Hei,

My application uses angular-material, and the HTML body has an horizontal flex layout. When the input is added to the body, it results in a undesired scrollbar.

I can fix the problem by setting ```top:0;left:0;``` to the input element.

**Comment by danialfarid** [comment]
Could you create a jsfiddle?

**Comment by yellowiscool** [comment]
Here you go: http://jsfiddle.net/2acn71m3/3/

**Comment by danialfarid** [comment]
Fixed in 5.0.3

**Comment by yellowiscool** [comment]
Thank you.
