### ISSUE TITLE
403 (Forbidden) - upload url

### ISSUE THREAD

**Issue by nielvrom** [danialfarid/ng-file-upload#797]
I'm trying to upload an image/pdf/text or word document  to a folder in my wordpress website but it isn't working.

This is my HTML:

```<input type="file" ngf-select="" ng-model="application.cv" name="appcv" accept="application/msword, text/plain, application/pdf, image/*" required>```

In my controllers.js I have the following:
```
function StepController($scope, $http, $routeParams, Upload)
	{
	    // inits
	    $scope.application = {};

	    $scope.$watch('application.cv', function () {
	        $scope.upload($scope.application.cv);
	    });

	    $scope.upload = function (files) {
	        if (files && files.length) {
	            for (var i = 0; i < files.length; i++) {
	                var file = files[i];
	                Upload.upload({
	                    url: 'http://domain.localhost/wp-content/uploads',
	                    file: file
	                }).progress(function (evt) {
	                    var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
	                    console.log('progress: ' + progressPercentage + '% ' + evt.config.file.name);
	                }).success(function (data, status, headers, config) {
	                    console.log('file ' + config.file.name + 'uploaded. Response: ' + data);
	                });
	            }
	        }
	    };
	}

```

The folder has read & write permissions but I'm always receiving the following error when tries to upload:

> GET http://vkgroup.localhost/wp-content/uploads/ 403 (Forbidden)

**Comment by danialfarid** [comment]
This is a server error so find out why your server returns that error to the request.

**Comment by nielvrom** [comment]
Is it normal that he tries to make a GET request to the url? I don't think so?

**Comment by danialfarid** [comment]
It should be POST. So the error may not be from the upload.
