### ISSUE TITLE
npm install v5.x.x - no `dist` directory

### ISSUE THREAD

**Issue by rpallas** [danialfarid/ng-file-upload#798]
Hi,

While attempting to update to the latest version (5.0.1) by running `npm install ng-file-upload` i noticed that there is no longer a `dist` directory in `/node_modules/ng-file-upload/`.

If i try `npm install ng-file-upload@v4.2.4` (or any earlier version) the `dist` files are provided.

Is this intentional?

Thanks

**Comment by danialfarid** [comment]
fixed in version 5.0.2

**Comment by rpallas** [comment]
Nice, thanks for the fast fix!
