### ISSUE TITLE
ngf-src

### ISSUE THREAD

**Issue by chepapoa** [danialfarid/ng-file-upload#799]
I'm developing an application that i have to upload images, save using .ashx handler. That's ok, but when i edit an item that have images already saved, i cannot show this images on my <img></img> coming from the server. Which way i have to passo to ngf-src to render my image?

**Comment by danialfarid** [comment]
You can just use <img src="image url to your server"> you don't need to use this plugin for this purpose.

**Comment by chepapoa** [comment]
I'm using an carousel to show all images from an user, and i want to show the server images and, if the user do, the new images to upload.

**Comment by danialfarid** [comment]
You can also use `ngf-default-src` and set it to the url of the server.

**Comment by LennyLip** [comment]
ngf-default-src does not work for me as https://github.com/danialfarid/ng-file-upload#file-preview.
change 
ngf-default-src="file" 
to
ngf-default-src="{{file}}"

and its work now.
may be it's helped somebody.
