### ISSUE TITLE
"Unable to get value of the property 'length': object is null or undefined" with IE9

### ISSUE THREAD

**Issue by jiivonen** [danialfarid/ng-file-upload#800]
Tried on my own system and then on the Demo page. I keep on getting this same error with IE 9:
"Unable to get value of the property 'length': object is null or undefined" ng-file-upload.js, line 260 character 27 when selecting the file to be uploaded.

I checked the compatibility mode as per #660 , but it's not on. (If it's on, we don't get to select the file)

I can't notice louading of the FileAPI-files. At what point that should happen?

**Comment by danialfarid** [comment]
If you right click on the button it should show the flash context menu, if it doesn't it means that the flash and FileAPI is not loaded. They will be loaded when ng-file-upload-shim.js is loaded.

**Comment by M21B8** [comment]
I'm getting exactly the same error as @jiivonen I can see the shim being loaded, but I don't get the flash context menu on right click.

**Comment by danialfarid** [comment]
FileAPI.Flash.swf and FileAPI.min.js should be loaded

**Comment by sdornan** [comment]
I am also having this issue, even on the demo page:

![](https://s3.amazonaws.com/uploads.hipchat.com/154108/1895014/VPE9iT01raoPJJV/Untitled.png)

**Comment by danialfarid** [comment]
What files are loaded in the network tab? Make sure you are not in the compatibility mode. What IE version?

**Comment by sdornan** [comment]
![](https://s3.amazonaws.com/uploads.hipchat.com/154108/1895014/Xv0UPHVH42QWpig/Untitled.png)

I am not in compatibility mode. I am using IE9.

**Comment by danialfarid** [comment]
Fixed in version 5,0.4

**Comment by jiivonen** [comment]
5.0.4 fixes the issue. Verified. Thank you.

**Comment by GirishAd** [comment]
Issues is fixed on Demo page but in our project we are still facing the same issue. We upgraded to 5.0.4. I have included ng-file-upload.js and shim file which loads as well. Any thoughts?

**Comment by danialfarid** [comment]
The jsfiddle demo didn't include shim file, try this one: http://jsfiddle.net/18yao91v/

**Comment by GirishAd** [comment]
The new jsfiddle works on IE9. For our project, the error 'Unable to get value of..' goes off if I include shim file but it did not fire ngf-change event. We are using Xdomain.js for cross-domain calls. Here is sample code for input element:

<input id="fileTBI" value="Choose file" accept=".jpg,.jpeg" type="button" data-icon="false" ngf-multiple="multiple" 
ngf-change="vm.uploadFile($files)" ngf-select="">

**Comment by danialfarid** [comment]
Add your element to the demo page and see if it works there.
