### ISSUE TITLE
Not working with jQuery 1.7.2

### ISSUE THREAD

**Issue by kotazi** [danialfarid/ng-file-upload#803]
Is it possible to use ng-file-upload with jQuery 1.7.2?

When I use it, the `Uncaught Error: type property can't be changed` error happens.

```
// We can't allow the type property to be changed (since it causes problems in IE)
  if ( rtype.test( elem.nodeName ) && elem.parentNode ) {
    jQuery.error( "type property can't be changed" );
  } 
```

**Comment by danialfarid** [comment]
It seems to be working for me, could you create a jsfiddle?
