### ISSUE TITLE
Upload file in the same site

### ISSUE THREAD

**Issue by juanluis04** [danialfarid/ng-file-upload#805]
Hi,

I have an application developed with AngularJS, and I was trying to upload a file to a folder of my Angular website, but I can't understand if I need the url in the 

Upload.upload({
                        url: 'img/uploads',
                        //fields: { 'username': $scope.username },
                        file: file
                    })

The 'img/uploads' is an existing folder in my website but when I try to run this I get the 405 response, could you share with me an example where the upload using a "url" for a local folder?

**Comment by danialfarid** [comment]
The url has to be a server endpoint which accepts upload multipart/from-data requests.

**Comment by juanluis04** [comment]
Yeah, thank you, I suppose that :)...

Well I don't know if you could help me, as I understand the uploaded files are stored in the remote API, and I have a question... For instance, imagine you have a profile or account section, then you have the classic Profile Picture, and the user can change this picture, when he select his picture to change, this is sent to the API and stored, and.... What is the easiest way to reference this uploaded file from the AngularJS website?... if you have you API in a server and your AngularJS in a different server :/

**Comment by danialfarid** [comment]
If the files are already on the server just sent the id or the selected file with a $post
