### ISSUE TITLE
Handling exceeding file size

### ISSUE THREAD

**Issue by gorankami** [danialfarid/ng-file-upload#807]
Is there a way to intercept when a file that I upload exceeds the value set in ngf-max-size? Selecting a larger file just closes the file selection dialog and i can catch the watcher on the model but the model is null so I cannot see what has changed. I cannot use oninvalid event since it is not rendered as input and i cannot use ng-model-rejected because it is for rejected file types. Any solution?

**Comment by danialfarid** [comment]
`ng-model-rejected ` will return rejected file sizes as well

**Comment by gorankami** [comment]
Right, I had a typo in the code: ngf-model-rejected , analogue to other properties. It works fine now, thanks and sorry to raise an issue on my own error
