### ISSUE TITLE
Using file upload with bootstrap filestyle

### ISSUE THREAD

**Issue by nileshpore** [danialfarid/ng-file-upload#811]
Hello,
I am using ng-file-upload with bootstrap filestyle element (https://github.com/markusslima/bootstrap-filestyle/). I am facing couple of issues with this.

1. Unable see selected filename for first time file selection, when I select file second time i can see the filename.

2. ngf-change event is not firing, this event fires only once; when second time I select another file ngf-change event is not getting triggered.

Following is the code snippet I have used.

<input accept=".jpg,.jpeg" ngf-select ngf-change="vm.onTopBannerImageSelect($files)" id="fileTopBannerImage" type="file" class="filestyle" data-icon="false" ng-disabled="vm.bannerImage.entityManagesTopBanner == false" />

And to apply filestyle i have used following code

$(":file").filestyle({ icon: false });

Can someone let me know how can i fix these issue.

Thanks,
Nilesh

**Comment by danialfarid** [comment]
Can you create a jsfiddle?
