### ISSUE TITLE
ngf-select not opening window to select file Safari on Windows

### ISSUE THREAD

**Issue by dinu88** [danialfarid/ng-file-upload#813]
ngf-select is not opening window to select file in Safari latest on Windows 7.
tested on browserstack, on demo page:
https://angular-file-upload.appspot.com/

**Comment by dinu88** [comment]
Invoking click in setTimeout fixes the issue but then i'm getting another issue, similar with one i had in older version of file-upload
To fix click : ng-file-upload.js lines ~345
setTimeout(function() {
    fileElem[0].click();
},0);

then, after selecting image, I'm getting another error:

'undefined' is not a function (evaluating 'FileAPI.readAsDataURL(file, listener)') ng-file-upload-shim.js:422

**Comment by danialfarid** [comment]
It shouldn't use the FileAPI for safari.
Can you copy your code or create a jsfiddle?
The demo page seems to work with the setTimeout fix on Windwos Safari.

**Comment by danialfarid** [comment]
Fixed in 5.0.5

**Comment by kediamanav** [comment]
I found the same issue. Later I realized that it was due to the Chrome plugin Batarang. If you disable that plugin and run. It works just fine. Maybe that was the issue with the Chrome users.
