### ISSUE TITLE
Base64 Encoding

### ISSUE THREAD

**Issue by krusk** [danialfarid/ng-file-upload#816]
Hi all,

I am attempting to use this directive to upload files into SharePoint, but it appears to be failing as the file needs to be Base64 encoded. How would I use this directive to encode via base64? My current code is as follows: (Note that the controller is bound at the page level)

HTML:
    
    <div>
                watching model:
                <div class="button" ngf-select ng-model="files">Upload using model $watch</div>
                <div class="button" ngf-select ngf-change="upload($files)">Upload on file change</div>
                Image thumbnail: <img ngf-src="files[0]" ngf-default-src="'/thumb.jpg'" ngf-accept="'image/*'">
            </div>
 
Controller:

     appControllersUploadImage.controller('appUploadImageCtrl', ['$scope', '$location', 'Upload', function ($scope, $location, Upload) {
        
            $scope.$watch('files', function () {
            $scope.upload($scope.files);
        });

        $scope.upload = function (files) {
            if (files && files.length) {
                for (var i = 0; i < files.length; i++) {
                    var file = files[i];
                    Upload.upload({
                        url: "/sites/ens/_api/web/lists/getByTitle('Images')/RootFolder/Files/add(url='test.jpg',overwrite='true')",
                        fields: {'Title': "test"},
                        file: file,
                        headers: {
                            'Accept': 'application/json;odata=verbose', 'content-type': 'image/jpeg', 'X-RequestDigest': $("#__REQUESTDIGEST").val()
                        }
                    }).progress(function (evt) {
                        var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
                        console.log('progress: ' + progressPercentage + '% ' + evt.config.file.name);
                    }).success(function (data, status, headers, config) {
                        console.log('file ' + config.file.name + 'uploaded. Response: ' + data);
                    });
                }
            }
        };
    }]);

**Comment by kadowki** [comment]
I'm doing this using FileAPI that is included with ng-file-upload. You'll have to wrap your code inside the callback function below. There are a few ways to do this, but the function below uses the FileAPI polyfill and is used as followed:

      FileAPI.readAsDataURL(file, function (dataUrlObject) {                  
        var dataUrl = dataUrlObject.result;
      });

**Comment by danialfarid** [comment]
You don't need FileAPI for the html5 browsers. You could use standard FileReader
```
var fileReader = new FileReader();
fileReader.readAsDataURL(file);
fileReader.onload = function (e) {
    dataUrl = e.target.result;
};
```
If the browser does not support html5 FileAPI will be used automatically so this code would work cross-browser.

**Comment by krusk** [comment]
How would I incorporate this with my upload function?

**Comment by danialfarid** [comment]
Extract the base64 part of the dataurl and send it with a regular $http.post()

**Comment by krusk** [comment]
Thanks Danial. Could you show a little code to help me visualize it.

**Comment by arusakov** [comment]
@krusk if still relevant...
dataUrl looks like "data:image/png;base64,DATA..." so:
var base64part = dataUrl.substr(dataUrl.indexOf('base64,') + 'base64,'.length);

**Comment by krusk** [comment]
Thank you. Where do I pass this variable into my code above?

**Comment by arusakov** [comment]
@krusk 
use @danialfarid code and add something like this:
```javascript
var fileReader = new FileReader();
fileReader.readAsDataURL(file);
fileReader.onload = function (e) {
  var dataUrl = e.target.result;
  var base64Data = dataUrl.substr(dataUrl.indexOf('base64,') + 'base64,'.length);
  $http.post('/url/to/upload/', { img: base64Data }).success(function () {
    // all right
  });
};
```

**Comment by krusk** [comment]
Awesome! That's what I was looking for

**Comment by amicos** [comment]
How we can decode the base64Data and generate the file to display in my page

**Comment by amicos** [comment]
I used that:

                              var binary = atob(dataUrl.split(',')[1]);
							    var array = [];
							    for(var i = 0; i < binary.length; i++) {
							        array.push(binary.charCodeAt(i));
							    }
							   var leblob= new Blob([new Uint8Array(array)], {type: 'image/jpeg'});
							   leblob.lastModifiedDate = new Date();
							   leblob.name = "my-image.jpg";
