### ISSUE TITLE
'undefined' is not a function FileAPI, safari latest on W7

### ISSUE THREAD

**Issue by dinu88** [danialfarid/ng-file-upload#818]
Hi,

I have this issue on safari 5.1.7 and W7. 
Issue is reproducible on demo page as well.
tested on browserstack.com

'undefined' is not a function (evaluating 'FileAPI.readAsDataURL(file, listener)')
https://angular-file-upload.appspot.com/js/ng-file-upload-shim.js:422

Any suggestions?

**Comment by dinu88** [comment]
I don't know about demo page but on my project issue is caused by FileReader:
var reader = new FileReader();
reader.readAsDataURL($file[0]);

**Comment by danialfarid** [comment]
Make sure you either use automatic inclusion of FileAPI files or include the FileAPI files that ship with this plugin. It works only with the specific FileAPI files that are shipped with this plugin.
