### ISSUE TITLE
Callback function return always empty object

### ISSUE THREAD

**Issue by IsmaBit** [danialfarid/ng-file-upload#819]
Hi danial, i've some problem:
When i select i file, the callback function returns always an empty object.
HTML
`<div class="button button-block button-stable" ngf-select ngf-change="upload($files)"> Carica</div>`
Javascript
`$scope.upload = function(files) {
        console.log("result: " + JSON.stringify(files));
    };`

The code open correctly the window folder explorer, but after select a file return:
`result: [{ }]`
I use the angularjs incorporated with ionic framework

Could someone help me?

**Comment by danialfarid** [comment]
There is one object in your array result in the output. the browser might just not show the content.
try `console.log(files[0].name)`

**Comment by IsmaBit** [comment]
Ehi @danialfarid, thanks for replay! I try to make the change you suggested, but the result it's tha same:
`fd: {}`

I try many different solution, using only javascript and html. But the result is the same.. always an empty object.

**Comment by danialfarid** [comment]
Create a jsfiddle please
