### ISSUE TITLE
max file size

### ISSUE THREAD

**Issue by a-birla** [danialfarid/ng-file-upload#821]
how does     ngf-max-size='3000000' // maximum acceptable file size in bytes work? it allows me to still select files larger than the bytes  and hangs...doesnt display any error coming from backend too

**Comment by danialfarid** [comment]
it puts them in the ng-model-rejected

**Comment by danialfarid** [comment]
You can also access the reason for error by `ng-model-rejected = "rejFiles"` `rejFiles[0].$error`
