### ISSUE TITLE
Send binary via JSON to DB

### ISSUE THREAD

**Issue by nikkwong** [danialfarid/ng-file-upload#822]
I've been totally unable to get this work. I'm getting a ```BAD REQUEST``` from using 

        Upload.http({
            url: url, // accepts JSON
            data: file
        })

So I'm trying to send properties over individually, i.e. 

        Upload.http({
            url: url, // accepts JSON
            data: {'size': file.size, 'date': file.lastModifiedDate}
        })

Works fine. 
But I can't get the actual file binary over to the DB, since—as the author said—it doesn't "show up" in the browser. I'm lost as how to send my image binaries to my DB. Any advice is appreciated!

**Comment by danialfarid** [comment]
When you use Upload.http it would sent the file content binary in the request so there is no space for any other data to be sent other than in the url request parameters.
You gotta find out why your server returns bad request.

**Comment by nikkwong** [comment]
Ok, I'll keep looking into it, thanks.

**Comment by nikkwong** [comment]
Woot woot! One week and countless hours later, was able to finally get it by converting it to a blob before it is sent, like so: 

    function create_blob(file) {
         var reader = new FileReader();
         reader.onload = function() { 
            return reader.result;
            };
         reader.readAsDataURL(file);
    };

Thoughts on this method?

**Comment by danialfarid** [comment]
I have no idea what format and what type of requests your server will accept for the file upload but most online services accept either the regular Upload.upload() or Upload.http() so there shouldn't be a need to convert the file to data url.
If you convert the file to base64 data url then you need to decode it on the server back to binary from base64.

**Comment by nikkwong** [comment]
I'm using mongolab to store all objects. I wouldn't think they would require anything out of the norm, but this is the only way I could get the requests to send the file data properly. Hopefully this helps someone.

**Comment by amicos** [comment]
I have the same problem, I want to convert the File to base64. How I can do?

**Comment by amicos** [comment]
please help ?

**Comment by philsam** [comment]
encode
$window.btoa(string);
decode
$window.atob(string); 
create a your own test fiddle. it helps :)

this fiddle might help
http://jsfiddle.net/eliseosoto/JHQnk/

**Comment by danialfarid** [comment]
You can use 
```
Upload.dataUrl(file, callback); 
```
to convert the file to dataurl and then extract the base64 data from it.
