### ISSUE TITLE
How to add Files in my Json Object?

### ISSUE THREAD

**Issue by amicos** [danialfarid/ng-file-upload#826]
I construct Json Object with all data I want to send to server by Rest Service. Then I want to add my Uploaded Files. How can I do It?  
Thanks a lot

**Comment by danialfarid** [comment]
Better to upload the file first alone, send an id back for the uploaded file and then post your json with the file id.

**Comment by amicos** [comment]
I have two questions : How can I save the file in the local way and upload it in the page each time the page is loaded?
What information allows me to recover the image as Json Object and thus show my image?

**Comment by amicos** [comment]
thanks Daniel, I understand the better way is to upload files first. But I want just send string to the server. Then I think base64 can be a key. Please how to have the base64 of the file in the way of ng-file-upload.
I'm stuck on it :-(

**Comment by danialfarid** [comment]
https://github.com/danialfarid/ng-file-upload/issues/816

**Comment by danialfarid** [comment]
You can also use:
```
Upload.dataUrl(file, function(dataUrl) {
...
});
```

**Comment by amicos** [comment]
thanks
