### ISSUE TITLE
Is e2e testing possible?

### ISSUE THREAD

**Issue by redhead** [danialfarid/ng-file-upload#827]
We need to have some e2e tests and part of that is to do a file upload. Using this library, is it possible to trick browser to upload a file? To be exact, we do not use the directives on an input (type=file) tag but on a div (so we can style it and everything). 

The library, however, creates a file input on click and shows the default OS dialog. This makes the e2e test hard send the file path into the library's file input.

**Comment by redhead** [comment]
Never mind, I think I got it.

**Comment by BelfordZ** [comment]
@redhead Care to share the solution?

**Comment by redhead** [comment]
It is still a bit of a workaround though: I do not know if it was already fixed, but in the version we are using (4.2.4), the `input[type=file]` used to upload the files is created by library and appended to body when directive is added to the DOM, not after clicking on it. So in our tests we take that input in body, make it visible (through `executeScript`), then we call `sendKeys` on it with path to a file we want to upload and the directive does the rest. Then we hide the  input again.

The downside is that in this version the input doesn't get removed from body after directive's scope is destroyed, so I made a ngfSelect "override" directive which removes the element correctly after itself:

	$scope.$on('$destroy', function () {
		if ($element.__ngf_ref_elem__) {
			$element.__ngf_ref_elem__.remove();
		}
	});

**Comment by BelfordZ** [comment]
@redhead Thanks for the help!
