### ISSUE TITLE
Error: 'name' getter called on an object that does not implement interface File

### ISSUE THREAD

**Issue by zlepper** [danialfarid/ng-file-upload#829]
Error: http://paste.ubuntu.com/11744293/
Angular version: 1.4.1
ng-file-upload version: 5.0.9
My upload code: http://paste.ubuntu.com/11744301/

The error happens every time I upload a file with ng-file-upload. 
The uploads works, it just spews out this error every time. 

I'm using node.js and dicer https://github.com/mscdex/dicer to receive the files on the server.
The code is: http://paste.ubuntu.com/11744312/

**Comment by danialfarid** [comment]
Can you create a jsfiddle showing the error? It seems like it is not from the server so you should be able to reproduce it just with the client code.

**Comment by zlepper** [comment]
I would happily like to, but when I attempted to reproduce the error angular simply refused to work at all. 
This is from your fiddle, the only thing I did was update angular to version 1.3.16
http://jsfiddle.net/18yao91v/2/

**Comment by danialfarid** [comment]
angular should be loaded beforehand.

**Comment by zlepper** [comment]
For some odd reason I cannot reproduce the issue with jsfiddle, however it is consistent in my application. 
However it will happen in this project: https://github.com/zlepper/mccontroller
If you start it with nodejs and navigate to the setup tab, there should be a well where you can drag a zipfile over. This will give you the errors in the console. 

I have however done a bit more investigation, and it seems to be an error in angularjs' equal function, it doesn't check if a key exists before it attempts to access it, which seems to cause the error.
If that is relevant to this I do not know, but I just thought you might want to know.

**Comment by danialfarid** [comment]
Try to make it reproducible, add all the js libraries you have there to the jsfiddle, or give me a link to the live running sample you are having trouble with

**Comment by zlepper** [comment]
I just sent to the login information in an email.
The upload field can be found on the setup page.

**Comment by danialfarid** [comment]
the setup page doesn't have any upload field

**Comment by zlepper** [comment]
![capture](https://cloud.githubusercontent.com/assets/1499810/8520053/6bb5b344-23d7-11e5-8d07-dc10b82a069c.PNG) It should have right in the red field

**Comment by danialfarid** [comment]
This works for me on Chrome:
```
(anonymous function) @ angular.js:12314$get @ angular.js:9101$get.Scope.$digest @ angular.js:15685(anonymous function) @ angular.js:15869completeOutstandingRequest @ angular.js:5387(anonymous function) @ angular.js:5659
setup.js:43 Object {url: "https://angular-file-upload-cors-srv.appspot.com/upload", fields: Object, file: File, headers: Object, transformRequest: Array[1]…}
setup.js:44 file IMG_2470.JPG uploaded. Response: [object Object]
```

**Comment by zlepper** [comment]
Yes, the file uploads successfully, as I stated in the op, but it's all the other errors that messes with me: 
http://paste.ubuntu.com/11832682/

**Comment by danialfarid** [comment]
You probably have some code in the progress function that throws that error, try removing everything from the progress function to narrow down the error.

**Comment by danialfarid** [comment]
or post your related js code here

**Comment by zlepper** [comment]
```javascript
    $scope.upload = function (files) {
        if (files && files.length) {
            for (var i = 0; i < files.length; i++) {
                var file = files[i];
                Upload.upload({
                    //url: "/uploadMod",
                    url: 'https://angular-file-upload-cors-srv.appspot.com/upload',
                    fields: {
                        'username': "Zlepper"
                    },
                    file: file
                }).progress(function (evt) {
                    console.log(evt);
                    var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
                    console.log('progress: ' + progressPercentage + '% ' + evt.config.file.name);
                }).success(function (data, status, headers, config) {
                    console.log(config);
                    console.log('file ' + config.file.name + ' uploaded. Response: ' + data);
                })
            }
        }
    };
```

**Comment by danialfarid** [comment]
It is probably from socket.io

**Comment by zlepper** [comment]
Disabled socket.io:
```
Array[0]
Failed to load resource: the server responded with a status of 404 (Not Found)
Array[1]
TypeError: Illegal invocation
    at equals (angular.js:1030)
    at equals (angular.js:1015)
    at Scope.$digest (angular.js:15661)
    at Scope.$apply (angular.js:15935)
    at angular.js:17691
    at completeOutstandingRequest (angular.js:5387)
    at angular.js:5659
TypeError: Illegal invocation
    at equals (angular.js:1030)
    at equals (angular.js:1015)
    at Scope.$digest (angular.js:15661)
    at Scope.$apply (angular.js:15935)
    at $$debounceViewValueCommit (angular.js:25068)
    at $setViewValue (angular.js:25040)
    at ng-file-upload.js:433
    at angular.js:17682
    at completeOutstandingRequest (angular.js:5387)
    at angular.js:5659
TypeError: Illegal invocation
    at equals (angular.js:1030)
    at equals (angular.js:1015)
    at Scope.$digest (angular.js:15661)
    at Scope.$apply (angular.js:15935)
    at angular.js:17691
    at completeOutstandingRequest (angular.js:5387)
    at angular.js:5659
XMLHttpRequestProgressEvent
progress: 100% Capture.PNG
XMLHttpRequestProgressEvent
progress: 100% Capture.PNG
TypeError: Illegal invocation
    at equals (angular.js:1030)
    at equals (angular.js:1015)
    at Scope.$digest (angular.js:15661)
    at angular.js:15869
    at completeOutstandingRequest (angular.js:5387)
    at angular.js:5659
Object
file Capture.PNG uploaded. Response: [object Object]
TypeError: Illegal invocation
    at equals (angular.js:1030)
    at equals (angular.js:1015)
    at Scope.$digest (angular.js:15661)
    at Scope.$apply (angular.js:15935)
    at done (angular.js:10356)
    at completeRequest (angular.js:10528)
    at XMLHttpRequest.requestLoaded (angular.js:10469)

```

**Comment by danialfarid** [comment]
Try removing the included libraries from the head one by one to see which one is responsible

**Comment by danialfarid** [comment]
might be bootstrap

**Comment by masious** [comment]
Same issue here. I'm trying to use it inside a bootstrap modal. I don't know where the problem is.

**Comment by danialfarid** [comment]
@masious could you create a jsfiddle showing the error?

**Comment by masious** [comment]
[Here it is](http://jsfiddle.net/6mrs29o8/13/)
When you select a file, error occurs.

**Comment by danialfarid** [comment]
If I change the ng-model to `myFile` it won't show that error again: http://jsfiddle.net/6058a15w/
Does it give you a clue?

**Comment by masious** [comment]
Not actually. But I need `ng-model` to be `model[options.key]`

**Comment by danialfarid** [comment]
That's not a valid value for ng-model. options.key must be resolved beforehand.
Try it on a normal input type=text with ng-model first.

**Comment by victor-duarte** [comment]
Hi all,
Was there a solution using`model[options.key]`?
Regards,

**Comment by victor-duarte** [comment]
So, after a while and following recommendations around the web, the error seems to be related to the `File object` created once a file is selected. It has an attribute `lastModifiedDate` that stores a `Date object` as a string with no quotes. I am guessing that when its evaluated by formly `model[options.key]` the type is not valid/illegal.

In my case i could not used `model[options.key]` in the `ng-model`. I used a random var in the `ng-model` and `$watch` it to hold the `File object`. Then in the `$watch` i stored an updated copy of the `File object` in the `model[options.key]` that would be used by formly avoiding the error message. On the upload I used the file stored in the initial var.
Its confusing, but i hope it helps someone else.

Regards,
Victor

**Comment by yahyaKacem** [comment]
@victor-duarte how you did that, I tried using expressionProperty, watchers but didn't work it only run one time at the beginning, then I used a controller and watched the random var in ng-model and when it changed I updated the original model, but it gives the same error here's a [plunker](http://plnkr.co/edit/tpl:0I9Bk8uVrT3X0RVcS9kX?p=preview) could you please change my plunker to show how you implemented your solution, thanks in advanced.

**Comment by victor-duarte** [comment]
@yahyaKacem i was not able to check you plnkr. I do not remember how i did it exactly but I created [plnkr](http://plnkr.co/edit/d2ooYR?p=info) with something similar to what was implemented. Hope it is useful. If you find something that can be improved for others let me know.

Regards,
Victor

**Comment by stephengardner** [comment]
I just fixed the ```illegal invocation``` problem for my case.

I had ```ng-if```'s that evaluated an expression based on the model object that ```ngf-select``` bound to.  

This is *no bueno*.  I switched the expression of the ```ng-if``` to something like ```nf-ig="picFile.name"``` instead of ```ng-if="picFile"```

```picFile.name``` evaluates to a string which is I suppose more ng-if friendly than the enormous ```picFile``` model object.

**Comment by darkmavis1980** [comment]
Same problem here, if I use any `ng-if`on the bound object of the `ngf-select` I get the same issues.

**Comment by darkmavis1980** [comment]
Ok, I found a ugly but working solution: I've created another scope variable, false by default, which I use to check if the file has been loaded, and I pass a function to the `ngf-select` to toggle the scope variable to true, so on my `ng-if` I just need to listen to that scope variable.
Not beautiful, but it works
