### ISSUE TITLE
S3 'public' should be 'public-read' for acl?

### ISSUE THREAD

**Issue by sunshineo** [danialfarid/ng-file-upload#831]
I was following the README
I had several issues but when I eventually got it work, I have 'public-read' instead of 'public' for acl.
Did s3 change something? In that case, we should update the README.

**Comment by henns20** [comment]
@sunshine 
- I can't get the public-read acl to work 
- what other changes did you make besides the public-read in the policy document 
- any specific changes - to buck policy/permissions that I am missing
- I have changed - it to 'public-read' and I get a 403 error in the - I am not understanding the issue. There is not debugging info in the error message. Going in circles with a lot of trial an error- 
- any help would be great.

**Comment by sunshineo** [comment]
@henns20 
Please have a look at http://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html
There is no acl called "public" at all so "public-read" for sure.
403 sounds like you did not give public write permission to your bracket. Google that would be my suggestion

**Comment by danialfarid** [comment]
I don't see any mention of `public` in the README file. @sunshineo

**Comment by sunshineo** [comment]
@danialfarid , you don't see " acl: 'private', // sets the access to the uploaded file in the bucket: private or public" on the README file??
![public](https://cloud.githubusercontent.com/assets/1072766/10125956/66ccbfda-653b-11e5-9f7b-6b5ac455f511.jpg)

**Comment by danialfarid** [comment]
alright fixed it.
