### ISSUE TITLE
The plus sign disappears when dragged file is brought  to dropzone

### ISSUE THREAD

**Issue by sidt101** [danialfarid/ng-file-upload#834]
<div accept="image/*,*doc,*docx,*txt,*pdf,*xls,*xlsb,*ppt,*pptx,*mp4,*xlsx,*csv" class="well d-and-d-well ng-pristine ng-untouched ng-valid ng-isolate-scope" ng-file-drop-available="dropSupported=true" ng-file-drop="" ng-model="modalOptions.model.files" ng-multiple="false" ng-show="dropSupported">
      <div class="center full-padding">
        Drag and drop your file here or <span style="cursor: pointer; overflow: hidden;" ng-file-select="" ng-model="modalOptions.model.files" ng-multiple="false" accept="image/*,.doc,.docx,.txt,application/pdf,.xls,.xlsb,.ppt,.pptx,video/mp4,.xlsx,.csv" class="ng-pristine ng-untouched ng-valid ng-isolate-scope"><a>browse</a><input type="file" accept="image/*,.doc,.docx,.txt,application/pdf,.xls,.xlsb,.ppt,.pptx,video/mp4,.xlsx,.csv" tabindex="-1" ng-file-generated-elem="true" style="width: 1px; height: 1px; opacity: 0; position: absolute; padding: 0px; margin: 0px; overflow: hidden;"></span>
      </div>
    </div>

**Comment by danialfarid** [comment]
provide more information, steps to reproduce
