### ISSUE TITLE
conflicts with angular-socket-io

### ISSUE THREAD

**Issue by btmdave** [danialfarid/ng-file-upload#838]
Has anyone ran into any issues with including this along with https://github.com/btford/angular-socket-io.  We had an old version (1.1.10) of ng-file-upload.  As soon as we upgraded to 5.0.9, it seems to be conflicting with socket.io and not allow websockets to connect, the only change we made is the upgrade for ng-file-upload.

**Comment by danialfarid** [comment]
Any specific error? What exactly is not working? Can you upload a file?

**Comment by danialfarid** [comment]
Could you create a jsfiddle or plnkr to reproduce the error?

**Comment by btmdave** [comment]
Well, to be honest, I'm not sure this is the issue.  It's the weirdest thing.  The only change was ng-file-upload, but if I clear out all of the logic associated, it still occurs.  I had thought it may be something to do with modifying the setRequestHeader, which wasn't in 1.1.10, but I can't say for sure that's the case.  I'll close out this issue and if I'm able to specifically isolate a problem, I'll re-open.
