### ISSUE TITLE
hidden element is taking up space

### ISSUE THREAD

**Issue by Jakobovski** [danialfarid/ng-file-upload#839]
This directive creates a hidden element:

`<input type="file" ngf-select="" ng-model="filesToUpload" tabindex="-1" style="visibility: hidden; position: absolute; width: 0px; height: 0px; z-index: -100000;">`

The problem is it is taking up 1x1px and is adding a scroll bar to my page. Can you add a class to this element so it can be customized? Also why not just add `display:none` to the element?

**Comment by danialfarid** [comment]
What version of the plugin are you using?
display:none would make the element not being clickable in some browsers.

**Comment by Jakobovski** [comment]
"ng-file-upload": "4.2.1"

**Comment by danialfarid** [comment]
upgrade to the latest
