### ISSUE TITLE
Android Chrome crashing when trying to upload a file

### ISSUE THREAD

**Issue by celrenheit** [danialfarid/ng-file-upload#84]
Hello,
I found a bug when using it with mobile android chrome browser.

When I click the button get the file selection utility of android but the problem comes when I select a specific file for upload. Chrome crashes.

Is there already a workaround this issue ? 

Thanks.

P.S.: I'm using Android 4.4 KitKat on Nexus 5 with Chrome 31.
I tried to debug android chrome from computer but it crashes too quickly to check.

**Comment by alzalabany** [comment]
crashing on andoid honor 6 too, seems like `input type="file"` is to blame
