### ISSUE TITLE
Getting response 400 but still not triggering error handler function on IE 9 

### ISSUE THREAD

**Issue by swapnilgaykhe** [danialfarid/ng-file-upload#841]
Hi, 
My upload is working fine for chrome and firefox but on IE9, when I upload a file and server responds with 400, neither success nor my error callback handler is getting called.
I am also sending the response data back from server. And I can see the data in developer tool.

**Comment by danialfarid** [comment]
That is already mentioned in the readme file, see the old browsers known issues section.
