### ISSUE TITLE
$upload function not working on ipad with iOS 8.3

### ISSUE THREAD

**Issue by JoshPMP** [danialfarid/ng-file-upload#842]
Here's the function I'm trying to use after a file has been selected.  I can see that an image has been selected, but this function isn't getting triggered.  It works on my iMac and Android devices.  Any ideas?
```
$scope.uploadSub = function (files) {   
    if (files && files.length) {
        for (var i = 0; i < files.length; i++) {
            var file = files[i];
           $upload.upload({
                url: globalUrl + '/images',
                file: file,
                method: 'POST',
                headers: {'Authorization': token}, 
                data: file
            }).progress(function (evt) {
                var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
                console.log('progress: ' + progressPercentage + '% ' +
                            evt.config.file.name);
//                       $scope.stillLoading = true;
                 //create a new array to store loader gif
               $scope.lineItems[$scope.parent].subLineItems[$scope.subIndex].loadingPics = [];
       $scope.lineItems[$scope.parent].subLineItems[$scope.subIndex].loadingPics.push({src: 'http://lb.delfi.lv/images/loading-icon.gif'});
           }).success(function (data, status, headers, config) {
//                console.log('file ' + config.file.name + 'uploaded. Response: ' + JSON.stringify(data));
               //remove loader gif
               $scope.lineItems[$scope.parent].subLineItems[$scope.subIndex].loadingPics.pop();
               //push image placeholder src into its array
               $scope.lineItems[$scope.parent].subLineItems[$scope.subIndex].pictures.push({src: data.widget.file, uuid: data.widget.uuid});
             }).error(function(resp){
                $scope.loading = false;
                if(status == 403){
                    $scope.showRedirect = true;
                    $scope.messages = resp.messages;
                    $scope.showAlert = true;
                } else {
                    $scope.messages = resp.messages;
                    $scope.showAlert = true;
                };
           });
        }
      }else {
         
      }
    };
```

**Comment by danialfarid** [comment]
Try using the latest version of the plugin

**Comment by JoshPMP** [comment]
I updated the plugin, but still no luck.  It seems to be getting stuck on .progress().  I'm guessing it could be an issue with image size, network connectivity, or maybe the plugin just doesn't work well on mobile devices.  Any other ideas to try?  Thanks.

**Comment by danialfarid** [comment]
So what the issue is? ngf-change not being triggered or .success not being called?

**Comment by JoshPMP** [comment]
Hello Danial,

Thanks for getting back to me.  The issue is now resolved.  I think it was
an issue with our server that was timing out when uploading images.  Which
would mean the .success was not being called, but not because of anything
in the plug-in.  I do love this plug-in though. Great job.

-Josh

**Comment by JoshPMP** [comment]
Hello again,

Actually the issue is not resolved.  The image is not being sent when the
uploadMain function is being called.  But only on iOS devices???  It works
perfectly on samsung devices and desktops.  Do you have any advice or see
any issues with this code?

HTML:

 <input ng-disabled="permissions.inspections_update == false" type="file"
name="addPhoto_{{$index}}" id="1_{{$index}}"
ng-file-select="image_{{$index}}" ng-click="lineItemWatch(expenseIndex,
lineItemFiles)" ng-model="lineItemFiles">

 <button class="btn btn-primary upload-btn" ng-show="mainFiles"
ng-click="lineItemWatch($index, lineItemFiles);
inspectionAutoSave()">{{labels.buttons.upload}}</button>

CONTROLLER:

   $scope.$watch('lineItemFiles', function () {
        //run this function
        $scope.uploadMain($scope.lineItemFiles);
    });

 //here's that function mentioned above
    $scope.uploadMain = function (files) {
    if (files && files.length) {
        for (var i = 0; i < files.length; i++) {
            var file = files[i];
           $upload.upload({
                url: globalUrl + '/images',
                file: file,
                method: 'POST',
                headers: {'Authorization': token},
                data: file
            }).progress(function (evt) {
               var progressPercentage = parseInt(100.0 * evt.loaded /
evt.total);
               console.log('progress: ' + progressPercentage + '% ' +
                           evt.config.file.name);
                      $scope.stillLoading = true;
               $scope.loading = true;
               $scope.lineItems[$scope.mainIndex].loadingPics = [];
               $scope.lineItems[$scope.mainIndex].loadingPics.push({src: '
https://effc5ca340939d5dc1b9-4fe0d84684076c46981fe544dd06afe9.ssl.cf5.rackcdn.com/images/loading-icon.gif'}
);


            }).success(function (data, status, headers, config) {

                console.log('file ' + config.file.name + 'uploaded.
Response: ' + JSON.stringify(data));
               $scope.lineItems[$scope.mainIndex].loadingPics.pop();
               $scope.lineItems[$scope.mainIndex].pictures.push({src:
data.widget.file, uuid: data.widget.uuid});

                          $scope.loading = false;
            }).error(function(resp){
                $scope.loading = false;
                if(status == 403){
                    $scope.showRedirect = true;
                    $scope.messages = resp.messages;
                    $scope.showAlert = true;
                } else {
                    $scope.messages = resp.messages;
                    $scope.showAlert = true;
                };
           });
        }
      }
    };

**Comment by JoshPMP** [comment]
I found the issue.  the .progress() doesn't work on iOS devices.  I removed
that section and anything related to it, leaving me with just success and
error.  Now it works.
