### ISSUE TITLE
Files ~>50mb uploading on server twice.

### ISSUE THREAD

**Issue by v29neil** [danialfarid/ng-file-upload#844]
@version 5.0.9
browser - firefox 38.0.5/ chrome 43.0.2357.130 m
When i upload file greater than 50mb. It is uploading twice on server. 
Progress percent reach 99 once then after some time it goes back to 0 then re-upload the file in single upload. This works completely fine when file size is small (tested on 30Mb).
Is there anything i am missing?
Code:
HTML-
``<button class="button" ngf-select="" ngf-change="upload($files)">Upload</button>``
Js :
```.controller('controller',['$scope','$modal', function($scope,$modal) {

        $scope.upload = function($files) {
            if( (typeof $files[0] !== 'undefined')  ) {
                $modal.open({
                    templateUrl: 'views/fupload.html',
                    controller: 'ModalCtrl',
                    resolve: {
                        file: function () {
                            return $files;
                        }
                    }
                });
            }
        };
    }])
    .controller('ModalCtrl',function ($scope, $modalInstance,Upload,$window,file) {
         //var repeat='0';
            console.log(file[0]);
            //console.log(file[0].name.length);
            $scope.fileName = file[0].name;
            $scope.fileSize = file[0].size+' bytes';
            $scope.progressVisible = true;
        //if(repeat == 0){
            var upload =
                    Upload.upload({
                        url: 'http://localhost:8080/file-transfer/123/upload',
                        method: 'POST',
                        file: file
                    })
                    .progress(function (evt) {
                        console.log('progress: ' + parseInt(100.0 * evt.loaded / evt.total));
                        if (evt.lengthComputable) {
                            //repeat = '1';
                        $scope.progress = Math.round(evt.loaded * 100 / evt.total)
                        } else {
                            $scope.progress = 'unable to compute'
                        }
                    })
                    .success(function (data, status, headers, config) {
                        console.log(data);
                        $scope.status = true;
                        $scope.message = 'Upload success';
                        $scope.close = false;
                    })
                    .error(function (err) {
                        $scope.status = true;
                        $scope.fail = 'Upload failed';
                    });
            //};
            $scope.abort = function() {
                upload.abort();
                $modalInstance.dismiss('cancel');
            };
            $scope.cancel = function () {
                $modalInstance.dismiss('cancel');
            };
    });```

On server side, I save the file locally then upload it to dropbox server.
```
var client = new Dropbox.Client({
    "key": "XXXXXXXXXXX",
    "secret": "XXXXXXXXXXXX",
    "token": "XXXXXXXXXXXXXXXXXXx",
    "uid": "XXXX"
});
    app.all('/test', function (req, res) {
        console.log(req.files); 
        var f = req.files.file;
        var dbx_file_stat;
        var short_url;
        var new_file_name = 'generate file name';
        fs.readFile(f.path, function (error, data) {
            if (error) {
                console.log('read error');
                return console.log(error);
            }
            client.writeFile(new_file_name, data, function (error, stat) {
                if (error) {
                    console.log('write error');
                    return console.log(error);
                }
                //stopReportingProgress();
                client.makeUrl(new_file_name, {downloadHack:true},function (error,url) {
                        if (error) {
                        return console.log(error);
                    }                                       
                    res.send("it works");                             
                });
            });
        });
    })```

**Comment by danialfarid** [comment]
Probably your server rejects it and it is retried by a proxy or something?
What http code response is being returned from your server in case of 50mb+?
