### ISSUE TITLE
How to send array of object 

### ISSUE THREAD

**Issue by johnlim5847** [danialfarid/ng-file-upload#845]
Hi,  i have tried these two methods below but i still can't get it done, it always send array of object as a `string` instead of array of object. may i know is there any possible solution for this problem?

**Method#1**
```Javascript
  var data  = $scope.dealsData;
  Upload.upload({
                  url: '/api/postDeals',
                  fields:data,
                  data:{favour:$scope.choices},
                  file: file
              }
```

in my nodejs console 

```javascript
{ deals_name: 'ad',
  deals_price: '12.12',
  deals_amount: '12',
  deals_description: 'asd',
  deals_term_condition: 'asd',
  favour_type: 'survey',
  data: '{"favour":[{"type":"mcq","$$hashKey":"object:67","mcq_question":"asd","mcq_choice1":"asd","mcq_choice2":"asd"},{"type":"open_ended","$$hashKey":"object:68","open_ended_question":"asd"}]}' }
```
if i do it the usual way i don't have the $$hashkey or object:6x thingy in my json 
**Method#2**
```Javascript
$scope.dealsData.favour =  angular.toJson($scope.choices);
var data  = $scope.dealsData;
  Upload.upload({
                  url: '/api/postDeals',
                  fields:data,
                  file: file
              }
```
in my nodejs console 
```Javascript
{ deals_name: 'asd',
  deals_price: '12.12',
  deals_amount: '12',
  deals_description: 'asd',
  deals_term_condition: 'asd',
  favour_type: 'survey',
  favour: '[{"type":"mcq","mcq_question":"asd","mcq_choice1":"asd","mcq_choice2":"asd"},{"type":"open_ended","open_ended_question":"asd"}]' }
```

**Comment by danialfarid** [comment]
User `fields: myData` and `sendFieldsAs: form`.

**Comment by rjurado01** [comment]
I try this and array is sended as object:

    array_name: {0: value1, 1: value2}

How can I send as array?

**Comment by johnlim5847** [comment]
@rjurado01  i ended up doing this to solve this problem 

**in controller**

```
  var data = {
    business_tags:angular.toJson($scope.tags)
  }
```

**in backend node.js**

```
  // assign jsonstring to myJSONString
  var myJSONString = data.business_tags;
  // convert it to array of object
  var myObject = JSON.parse(myJSONString);
  // assign to myOBject
  data["business_tags"] = myObject;
```

however i think you can do it solely in controller. 


hope this help

**Comment by kuldeepaggarwal** [comment]
@danialfarid This issue is still present. We have missed the condition `angular.isArray()` [here](https://github.com/danialfarid/ng-file-upload/blob/master/dist/ng-file-upload.js#L248).

**Comment by danialfarid** [comment]
@kuldeepaggarwal What is the issue?

**Comment by kuldeepaggarwal** [comment]
Cases:

Case 1:
when fields are object, 

```js
var val = { "name": 'kuldeep Aggarwal' }
Upload.upload({
  fields: val
})
```
then the code is send correct params: `{fields: {"name": "Kuldeep Aggarwal"}}`

Case 2: 
when fields are array: 

```js
var val = [{"name": "kuldeep Aggarwal"}]
i.e.
Upload.upload({
  fields: val
})
```
then the code send incorrect params => `{fields: {"0": { "name": "Kuldeep Aggarwal" }}}`

instead it should send params => `{fields: [{"name": "Kuldeep Aggarwal"}] }`


So, if you think my assumption is write then I would like to contribute and create a PR for this issue.

**Comment by danialfarid** [comment]
`fields` is deprecated. Use `data` instead.

**Comment by kuldeepaggarwal** [comment]
Okay,, so data handles all the aforementioned scenarios?

**Comment by psnfrench** [comment]
Just had the same issue. As per the docs using arrayKey: '[]' solved the issue for me e.g.
`Upload.upload({
  data: val,
  arrayKey: '[]'
})`

**Comment by SHAPPY0** [comment]
Hi,
I am also having the same issue and also try to use `arrayKey:'[]'` but its didn't resolved.
I am trying to upload multiple files with some body data, and the body data contains some array of objects.
But in the backed I am getting a single object in array with comma separated values.

```
Upload.upload({
          url:configuration.PACKAGE_URL, 
	  arrayKey: '',
	 data: { data : $scope.packages, file : files} 
	   })
```

and `$scope.packages` is
```
  {
                       "packs": [{
			"i_name": "Tax",
			"i_code": "2"
		}, {
			"i_name": "Fli",
			"i_code": "3"
		}],
		"type": "Katt",
         	"category": "Low"
}
```
But in request body in backend I am getting request 
```
"packs" : [ 
        { 
            "i_name" : "Tax,Fli",
            "i_code" : "2,3",
           "$hashKey":"object:51"

        }
    ],
     "type": "Katt",
      "category": "Low"
```
