### ISSUE TITLE
How do you pass in the relative path to the file object?

### ISSUE THREAD

**Issue by AdityaAgg** [danialfarid/ng-file-upload#846]
#285 Wondering if there's a simplified way to pass in the relative path to a file object. I know that I can create a field file._relativePath, but it seems like this variable does not work by itself and I would have to receive it from chrome like this, http://stackoverflow.com/questions/3590058/does-html5-allow-drag-drop-upload-of-folders-or-a-folder-tree? This is less an issue with the project than a question of my experience but I'm wondering how would you be able to combine the two together to get the path for each file in relativePath? An example, link, or documentation beyond 285 to make this easier would really be appreciated.

**Comment by danialfarid** [comment]
You can get the relative path by `file.path` from ngf-drop dropped files.

**Comment by AdityaAgg** [comment]
Thank you. Your suggestion worked.
