### ISSUE TITLE
update comment that says xhr hack is for angular <1.2 since 1.3 is out & it isn't fixed yet

### ISSUE THREAD

**Issue by benatkin** [danialfarid/ng-file-upload#847]
From https://github.com/danialfarid/ng-file-upload/blob/master/dist/ng-file-upload.js#L12

``` javascript
// fix for angular < 1.2.0
```

How about pointing to https://github.com/angular/angular.js/issues/1934 instead of showing the angular version?

**Comment by danialfarid** [comment]
The check for `instanceof Function` is for angular < 1.2.0. The xhr hack is for all angular versions.
But for the whole hack the comment could be added, you could submit a PR if you like
