### ISSUE TITLE
Upload.upload data parameter send object as [object Object]

### ISSUE THREAD

**Issue by roma86** [danialfarid/ng-file-upload#848]
Thank you for this library. 
I follow instructions and examples, but have issue with additional data send along with file.

- *ng-file-upload version is 5.0.9*
- *backend is rails*

uploader settings:

```
Upload.upload({
          url: 'logo_images'
          method: 'POST'
          data: {name: 'Picture name if need'}
          file: file
          fileFormDataName: 'logo_image[image]'
          formDataAppender: (fd, key, val) ->
            if angular.isArray(val)
              angular.forEach(val, (v) -> fd.append("logo_image[#{key}]", v))
            else
              fd.append("logo_image[#{key}]", val)
        })

```

On the server side file received correctly, but 'data' object is strange:

```
Parameters: {"logo_image"=>{"data"=>"[object Object]", "image"=>
``` 

I tried use  ```data: JSON.stringify({name: 'Picture name if need'})```
Result is not usable too

```
Parameters: {"logo_image"=>{"data"=>"{\"name\":\"Picture name if need\"}"
```
Rails can not resolve data field as json parameters.

As i see in all examples, palin object used to sending data. 
I have messed some settings?

**Comment by danialfarid** [comment]
Remove `formDataAppender` instead of `data` use `fields` and add `sendFieldsAs: form`.

**Comment by roma86** [comment]
It's work. Thank you for quick answer and great lib.

**Comment by akshayseth** [comment]
file.upload = Upload.upload({
            url: '/api/uploaders/uploads',
            method: 'POST',
            fields: {
                username: $scope.advert
            },
            file: file,
            fileFormDataName: 'photo',
            sendFieldsAs: form
        });
I am not receivingg data with the image.Please help.
