### ISSUE TITLE
Size of file in "data" property different between Upload.http() and AngularJS $http()

### ISSUE THREAD

**Issue by yarhouse** [danialfarid/ng-file-upload#851]
I'm testing my upload service, and I'm getting an error from my backend service when using `Upload.http()`, but the same exact properties work 100% when using the standard `$http()` service.
EDIT: Ng-File-Upload 5.0.0, AngularJS 1.3.15

My file is a 0:06 video/mp4, and it looks like this (browser console output):

     data: File
       lastModified: 1435331273000
       lastModifiedDate: Fri Jun 26 2015 11:07:53 GMT-0400 (EDT)
       name: "test_2.mp4"
       size: 383631
       type: "video/mp4"

Before starting the file upload, I send a JSON of this information separately to the server for comparing to the upload later.
When using ng-file-upload in the suggested manner from the docs **Upload service** to send binary data:

    Upload.http({
      method : 'POST',
      url : HOST_URL + '/documentation/components/video/' + $scope.components.id + '/upload',
      data : file,
      headers: {'Content-Type': file.type}
    })
    .progress(function (evt) {
      console.log(evt.total);
      console.log(evt.totalSize);
      var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
      console.log('progress: ' + progressPercentage + '% ' + evt.config.data.name);
    })

my backend service throws an error when comparing the POSTed file size against the size value stored in that JSON snapshot I mentioned earlier

    Data read has a different length than the expected: dataLength=8; expectedLength=383631;

I can confirm this bad dataLength with the `evt` argument from the `.progress` promise, in which the `evt.total` and `evt.totalSize` both return as `8`, the incorrect dataLength.

However, when I use the core `$http()` in Angular, my mp4 file POSTs without any issue

    $http({
      method : 'POST',
      url : HOST_URL + '/documentation/components/video/' + $scope.widget.id + '/upload',
      data : file,
      headers: {'Content-Type': file.type}
    })

Its the same exact configuration (sans `.progress` promise), and since the docs state "_**Upload.http():** This is equivalent to angular $http() but allow you to listen to the progress event for HTML5 browsers_", this leads me to believe the error is coming from somewhere in ng-file-upload. I've checked the final `config` that is sent in the `$http` call (https://github.com/danialfarid/ng-file-upload/blob/master/dist/ng-file-upload.js#L65), and it outputs exactly what I expect to be correct:

    __XHR: XMLHttpRequest
    data: File
      lastModified: 1435331273000
      lastModifiedDate: Fri Jun 26 2015 11:07:53 GMT-0400 (EDT)
      name: "test_2.mp4"
      size: 383631type: "video/mp4"

    headers: Object
      Content-Type: "video/mp4"
      
    method: "POST"
    url: "http://localhost:8219/documentation/components/video/5592de1a300407a434e85ad2/upload"

To further confirm that this isn't an issue with the backend service and likely with ng-file-upload, I uploaded the video via cURL `-H 'Content-Type: video/mp4' -X POST --data-binary @test_2.mp4` and it works with no issue.

Is this a bug in the module, or am I possibly missing some other critical piece to get `Upload.http()` to work correctly and provide me with the `.progress` promise?

**Comment by danialfarid** [comment]
What version of the plugin?

**Comment by yarhouse** [comment]
I'm so sorry, I failed to put that and the Angular version
Ng-File-Upload 5.0.0
AngularJS 1.3.15

**Comment by danialfarid** [comment]
There was a bug in the earlier version, upgrade to the latest version.

**Comment by yarhouse** [comment]
That was the ticket, works perfectly now. Just to note, I didn't notice there was a v5.0.9. I installed from the **Migration notes** links in your docs which only linked to v5.0.0

Thanks again! Fantastic.
