### ISSUE TITLE
I had preview image before upload action,  when to upload the image, file.progress return 100% every time

### ISSUE THREAD

**Issue by qiuling2014** [danialfarid/ng-file-upload#852]
I had preview image before upload action,  when to upload the image, file.progress return 100% every time, I can't get the uploading progress info.

**Comment by qiuling2014** [comment]
@tristan , @aderowbotham  @samuraisam  @vvo

**Comment by qiuling2014** [comment]
@danialfarid

**Comment by danialfarid** [comment]
Can you create a jsfiddle? It might be something in your code, or the upload might be very fast so you would not see other percentages. Or your server may not be configured to report the progress event.
