### ISSUE TITLE
Allow plain URLs

### ISSUE THREAD

**Issue by alexandernst** [danialfarid/ng-file-upload#853]
The library's `ngf-src` (and `ngf-bg-src` from #849 when implemented) can't load remote URL's, which is very useful when loading an already uploaded photo.

Check the following example:

```html
<img ng-src="photo[0]">

<div ngf-drop ngf-select ng-model="photo" .... ></div>
```

This will show a preview of the image once an image is selected, but what if I already have an image on the server side?

My proposal:

```html
<img ng-src="photo[0]" ng-init-src="http://foo.bar/image.jpg">

<div ngf-drop ngf-select ng-model="photo" .... ></div>
```

That way the `<img>` tag will be initialized with the `image.jpg` image and replaced only when another file is selected.

Tell me what do you think about this?
Also, as this is something I need for a project I'm currently working for, I'm willing to make a PR (following any guides/advises you can give me).

**Comment by alexandernst** [comment]
Actually, after re-reading the docs, I think this is almost implemented. The `defaul-src` is what I should be using. Anyways, this could be improved by replacing what is does with the following:

* get the data URI (download the image)
* set the data URI to the model

**Comment by danialfarid** [comment]
Why would it be an  improvement to download the image?

**Comment by alexandernst** [comment]
Note that the image is downloaded either way. IMHO this is an improvement
because the image gets inserted in the model, which allows us to handle
better some situations, without causing any performance regressions.

Real world example:

Let's say I have an 'edit-profile' page that allows users to edit their
personal info and upload an avatar. Let's also say that I'm using another
AngularJS module to crop the selected image.

The way how it works now, the best I can do is show the user the current
profile picture, but if he/she wants to crop it, a new picture must be
selected in order to fill in the model and only then pass the model's data
to that other AngularJS module.

Another example: having the image in a data model (instead of making the
browser download it as a src for an img tag) allows us to pass the data to
any other component or even duplicate it without having to download it
again.

Last one, though this is a little bit of a personal opinion, I feel this is
'the AngularJS way' of doing it.

**Comment by danialfarid** [comment]
Both of these can be handled by a url as src from the server and browser does handle caching the same image and not re-downloading it.

**Comment by alexandernst** [comment]
@danialfarid Indeed, browsers do cache images, but note that cache works only with plain (direct) URLs, such as `foo.bar/img/user.png`. Browser cache is useless with raw streams (`foo.bar/user_image.php?id=123`) or timestamped URLs (`foo.bar/img/user.png?t=234524363`).

In those cases (which are very common, btw) browser cache will fail and pictures will be downloaded again, thus wasting time and bandwidth.

**Comment by danialfarid** [comment]
Well you could download the image with an xhr get and create data url from it and then set the data url as the default src.

**Comment by alexandernst** [comment]
I could, but I can't see why doing it on my own if the library can do it for me. Isn't that the point of the preview element? Being useful without making you write code yourself.

**Comment by danialfarid** [comment]
"Another example: having the image in a data model (instead of making the
browser download it as a src for an img tag) allows us to pass the data to
any other component or even duplicate it without having to download it
again."

This way when you download the image inside direvtive it wont be accessible to other directives unless you download it outside directive.

**Comment by danialfarid** [comment]
If you could show me a sample html/js that shows how your approach would work and is simpler than what it is there would make it clearer

**Comment by alexandernst** [comment]
After reconsidering this better, I think I'll follow your suggestion and do it the other way (using base64 strings and pushing manually to the model).

Do you still want me to push the `ngfBgSrc` directive (the code from #849)?
