### ISSUE TITLE
cloudfront POST request

### ISSUE THREAD

**Issue by monad98** [danialfarid/ng-file-upload#857]
I posted a same question at SO but got no answer.
http://stackoverflow.com/questions/31196299/aws-cloudfront-post-request-with-signed-cookies

I want to upload file to S3 through the cloudfront with signed cookies (https://cdn.example.com) from https://example.com. 
my POST request fail at preflight request. GET request with normal angular $http works fine.

But POST request with ng-file-upload fail at preflight request.
![image](https://cloud.githubusercontent.com/assets/6015975/8510711/7df51d38-22ab-11e5-87a7-7f64c4020e0b.png)
BTW, if I click "replay XHR" in the Chrome developer tool, it upload file to S3 !!
![image](https://cloud.githubusercontent.com/assets/6015975/8510734/b2eb1654-22ac-11e5-9f92-24245c609cba.png)
![image](https://cloud.githubusercontent.com/assets/6015975/8510728/61467708-22ac-11e5-8adc-ad2b8e88b236.png)
I tried with cURL, POSTMAN to test POST request and upload was successful.
I suspect that "withCredentials: true" doesn't work so cookie is not sent with request. But not sure.

I have no problem with upload to directly to S3 (https://example.s3.amazonaws.com). Of course, this upload doesn't need withCredentials:true option.

Help me. Thank you.

EDIT: 
1. if I don't set withCredentials option, preflight request fails and replay XHR upload file to S3 with cookies.
2. if I set withCredentials:false, preflight request fails and replay XHR fails again with same status code(403)

**Comment by danialfarid** [comment]
Follow it on SO since it is less likely to be an issue with the plugin but rather S3 configuration specific.

**Comment by Tomino2112** [comment]
@monad98 I posted answer to your SO question
