### ISSUE TITLE
open a file selector, but don't select a picture, uploaded picture will disappear

### ISSUE THREAD

**Issue by huguangju** [danialfarid/ng-file-upload#858]
When I open a file selector, but then do not select a picture, the picture which i uploaded before will disappear 

Because cancel select will make files model to be ```null```
```js
$scope.$watch('files', function (files) {
  console.log(files === null);
});
```
then the repeat of files can't work.
```js
<div ng-show="files.length > 0" class="response">
  <div class="sel-file" ng-repeat="f in files">
     <img ng-model="imgPrev" ng-show="f.type.indexOf('image') > -1" 
ngf-src="f" class="thumb img-thumbnail img-preview-150" ngf-accept="'image/*'">
   </div>
</div>
```

**Comment by danialfarid** [comment]
have a look at `ngf-keep`, `ngf-reset-on-click` and  `ngf-reset-model-on-click` options.

**Comment by huguangju** [comment]
if i use ```ngf-keep="true"``` and ```ngf-reset-on-click="false"```, how many times uploads will show how many images, but i want to have only one image;
if i use ```ngf-keep="false"``` and ```ngf-reset-on-click="true"```, image will be disappear like said above, and reupload image when i reopen file selector

**Comment by danialfarid** [comment]
`ngf-reset-on-click="false"` would be enough
