### ISSUE TITLE
Callback for file rejection

### ISSUE THREAD

**Issue by zhming0** [danialfarid/ng-file-upload#859]
Maybe it will be nice to have a attribute like `ngf-file-reject='fileReject(file, evt)'` to enable user to deal with the file rejection.

Now I am using `$watch` and `ngf-model-rejected` to handle the rejection, but I have to find the exact reason for rejection every time.

I know in current implementation `ngfChange` will be invoked when file is rejected, but it seems that neither rejection info nor error logs was passed to the `ngfChange`.

**Comment by jonwhittlestone** [comment]
+1

**Comment by wanglijie** [comment]
+1

**Comment by wanglijie** [comment]
Reading through the source code, there's an inner attribute $rejectedFiles which can be used to track rejected files. 
```
ngf-change="myController.upload($files, $rejectedFiles)"
```

**Comment by hxlniada** [comment]
+1

**Comment by danialfarid** [comment]
Since version 5.1.0 you can see the rejection reason with `file.$error`.
