### ISSUE TITLE
preview on modal view

### ISSUE THREAD

**Issue by SoftpymesAdrian** [danialfarid/ng-file-upload#860]
Hi!
I need display the preview generated in a modal window, i'm using the same controller in both views, but when i display the modal window the controller restart. can you help me?

**Comment by danialfarid** [comment]
Create a jsfiddle showing the error, or post more info

**Comment by SoftpymesAdrian** [comment]
already works...
I used a service to send the value of Files [0] to another controller, and so was able to display the preview of the image in a modal window.
Thanks for your quick response.
