### ISSUE TITLE
setting validation keys for each of the validators using controllers' $setValidity()

### ISSUE THREAD

**Issue by zeel** [danialfarid/ng-file-upload#861]
HI,

suppose I have following input file.
<input type="file" ngf-select valid-file required style="width:220px" ng-model="resumeSelectedFile" ngf-accept="'.pdf,.doc,.docx,.csv,.txt,.rtf'" ngf-multiple="false" ng-model-rejected="rejFiles" name="resume_file" id="id_file" ngf-max-size='500000'/>

there is no way that I can check which of the validators failed. Suppose I want to display error message whenever user have selected file with more then maximum filesize or other message when user selected file with extension not listed in accepted extension list.

Is there any way for it? I searched hard but it was in vain. I think there should be validators like controller.$error.maxFilesize so that whenever some validator fails user is informed. Rightnow this thing is sort of silent.

**Comment by danialfarid** [comment]
It is already implemented in the latest version, forgot to close this.
You can get the error on the rejected files with file.$error. Read the docs and release notes for more info.
