### ISSUE TITLE
How should I access file in struts action class.

### ISSUE THREAD

**Issue by shiljha** [danialfarid/ng-file-upload#862]
I am using following code to upload files.

    $scope.upload = function (files) {
    	
        if (files && files.length) {
            for (var i = 0; i < files.length; i++) {
                var file = files[i];
                Upload.upload({
                    url: 'https://angular-file-upload-cors-srv.appspot.com/upload',
                    fields: {
                        'username': $scope.username
                    },
                    file: file
                }).progress(function (evt) {
                    var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
                    $scope.log = 'progress: ' + progressPercentage + '% ' +
                                evt.config.file.name + '\n' + $scope.log;
                }).success(function (data, status, headers, config) {
                    $timeout(function() {
                        $scope.log = 'file: ' + config.file.name + ', Response: ' + JSON.stringify(data) + '\n' + $scope.log;
                    });
                });

Please guide me to use file:file  on java side

**Comment by danialfarid** [comment]
The backend code should be similar to any struts file upload sample you can find on the web,

**Comment by shiljha** [comment]
Thanx..I got it..In IE9 after getting response from server,inside success callback Im getting response as null.Getting following error.

Unable to get property 'statusText' of undefined or null reference

**Comment by danialfarid** [comment]
What version of the plugin?
