### ISSUE TITLE
Required Validation on File Upload

### ISSUE THREAD

**Issue by chaitanyavvs** [danialfarid/ng-file-upload#867]
Hi,
   I am new to Angularjs and I have a condition on the validation of the file to be uploaded before the user clicks on Save button. The file upload is a required file.

Can you help me out on how to do a validation on the file upload on submit .Any pointers are more than helpful. I have tried to google but found no satisfactory results

**Comment by danialfarid** [comment]
The demo page has the sample of having the file input required. For validation you can use ngf-min-size ngf-max-size ngf-accept, or ngf-accept with a custom function.
