### ISSUE TITLE
SignatureDoesNotMatch

### ISSUE THREAD

**Issue by rodrigogalindez** [danialfarid/ng-file-upload#868]
Hi Danial, 

First, great job. Thanks for your hard work. However, I'm getting this error when trying to upload a file on S3:

`POST http://mybucket.s3.amazonaws.com/ 403 (Forbidden)`

The Response tab in Chrome Dev tool shows this:

`The request signature we calculated does not match the signature you provided. Check your key and signing method.`

The Headers tab in Chrome Dev tool shows this:

**General**

Remote Address:54.231.11.104:80
Request URL:http://mybucket.s3.amazonaws.com/
Request Method:POST
Status Code:403 Forbidden

**Response Headers**

HTTP/1.1 403 Forbidden
Access-Control-Allow-Origin: http://localhost:9000
Access-Control-Allow-Methods: POST, GET, HEAD
Access-Control-Max-Age: 3000
Access-Control-Allow-Credentials: true
Vary: Origin, Access-Control-Request-Headers, Access-Control-Request-Method
x-amz-request-id: DFB731E92DB5820B
x-amz-id-2: tZrw6xer350J+WnNki/qmHVBQai15k1rgVMbwkuSDcR/xxP6AflQjj4JL4XZWvMl
Content-Type: application/xml
Transfer-Encoding: chunked
Date: Wed, 08 Jul 2015 17:38:11 GMT
Connection: close
Server: AmazonS3

**Request Headers**

POST / HTTP/1.1
Host: mybucket.s3.amazonaws.com
Connection: keep-alive
Content-Length: 4006
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json, text/plain, */*
Origin: http://localhost:9000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/537.36
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryOVBxRm16QJhOxPsR
Referer: http://localhost:9000/
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8,ca;q=0.6,es;q=0.4,fr;q=0.2

**Request Payload**

------WebKitFormBoundaryOVBxRm16QJhOxPsR
Content-Disposition: form-data; name="key"

accelerator.md
------WebKitFormBoundaryOVBxRm16QJhOxPsR
Content-Disposition: form-data; name="AWSAccessKeyId"

[MYACCESSKEYGOESHERE]
------WebKitFormBoundaryOVBxRm16QJhOxPsR
Content-Disposition: form-data; name="acl"

private
------WebKitFormBoundaryOVBxRm16QJhOxPsR
Content-Disposition: form-data; name="policy"

[MYPOLICYGOESHERE]
------WebKitFormBoundaryOVBxRm16QJhOxPsR
Content-Disposition: form-data; name="signature"

[MYSIGNATUREGOESHERE]
------WebKitFormBoundaryOVBxRm16QJhOxPsR
Content-Disposition: form-data; name="Content-Type"

application/octet-stream
------WebKitFormBoundaryOVBxRm16QJhOxPsR
Content-Disposition: form-data; name="filename"

accelerator.md
------WebKitFormBoundaryOVBxRm16QJhOxPsR
Content-Disposition: form-data; name="file"; filename="accelerator.md"
Content-Type: application/octet-stream

------WebKitFormBoundaryOVBxRm16QJhOxPsR--

Here's the function I'm using to upload the files:

```javascript
Upload.upload({
	url: 'http://mybucket.s3.amazonaws.com',
	method: 'POST',
	fields: {
		key: file.name, // the key to store the file on S3, could be file name or customized
		AWSAccessKeyId: 'myaccesskeyid',
		acl: 'private', // sets the access to the uploaded file in the bucket: private or public
		policy: $scope.policy, // base64-encoded json policy (see article below)
		signature: $scope.signature, // base64-encoded signature based on policy string (see article below)
		"Content-Type": file.type != '' ? file.type : 'application/octet-stream', // content type of the file (NotEmpty)
		filename: file.name // this is needed for Flash polyfill IE8-9
	},
	file: file
}).progress(function (evt) {
	var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
	console.log('progress: ' + progressPercentage + '% ' + evt.config.file.name);
}).success(function (data, status, headers, config) {
	console.log('file ' + config.file.name + 'uploaded. Response: ' + data);
}).error(function (data, status, headers, config) {
	console.log('error status: ' + status);
});
```

I used the generator you have in your demo page, with my Access Key ID, Secret Access Key, and have $scope.policy and $scope.signature set with the values. Chrome dev tools shows me the same values so in theory the signature is the same. I'm not sure what I'm missing here.

Any help with this?

Thank you!

**Comment by rodrigogalindez** [comment]
Found the error. Somehow I used wrong keys to generate the signature. Thanks again for your work!

**Comment by cjthomp** [comment]
We are seeing the same error, but we are definitely using the correct keys

**Comment by mcblum** [comment]
Us too -- @cjthomp did you ever get this figured out?
