### ISSUE TITLE
Provider for defaults

### ISSUE THREAD

**Issue by HHogg** [danialfarid/ng-file-upload#869]
Hi @danialfarid (not an issue) what do you think about a provider for configuring directive defaults? I was just thinking about starting this, but thought I would check first to see that it would be a welcomed change.

```js
.config(UploadProvider, function() {
  UploadProvider.setDefaults({
    accept: 'image/*,application/pdf,text/plain,application/rtf,application/msword',
    multiple: true,
    allowDir: false,
    maxSize: 10000
  });
});
```

This would just be quite handy for not having to repeat the attributes throughout an application.

**Comment by jordanmkoncz** [comment]
Was just looking for this feature. I'm working on an application that will have 15+ ng-file-upload inputs and they will all have exactly the same attributes other than the `ng-model`, so a provider for configuring defaults would save a lot of duplicate code.

**Comment by danialfarid** [comment]
Good idea it is welcomed.

**Comment by HHogg** [comment]
Awesome, I'm nearly done with it so will have it up in a PR soon.
