### ISSUE TITLE
ngf-select buttons fire when touched, not clicked

### ISSUE THREAD

**Issue by JClar101** [danialfarid/ng-file-upload#870]
Hi, I'm using ngf-select buttons in a mobile app using the Ionic framework, and when running the device on iOS or an iOS emulator, if the user touches one of the buttons and tries to drag it, the button activates as if it has been clicked. I believe a click to be the user touching the button, and then letting go. It activates upon contact for even a millisecond, it seems like. Is there a way to make the ngf-select button only fire when it has been CLICKED, not touched? This is not an issue with ng-click.

Here's the relevant code.
    

    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
    </head>
    <ion-nav-view></ion-nav-view>
          <ion-content class = "bgimg">
			  <ion-refresher pulling-text="Pull to refresh" on-refresh="refreshOrders()">
			  </ion-refresher>
          <ion-list>

    <div class="list card">
	<div class="item item-divider">
	{{currentRestaurantName}}
	</div>
	<div>
		<a ng-repeat="item in orders" href="#" class="item item-icon-left"
		ngf-select="processOrderInvoice($files, item.id)"> <i
		class="icon ion-camera"></i> {{item.vendor.name}} <br /> Created on:
		{{item.orderDate|date:'MM/dd/yyyy'}} <br /> by: {{item.createdBy}}
		</a>
	</div>
	<div class="item" ng-hide="orders.length > 0">
	No orders that require an invoice. 
	</div>
	<div class ="item item-divider">
		Refreshed at {{refreshDate|date:'medium'}}
	</div>

    </div>

    </ion-list>
    </ion-content>

**Comment by thbsolutions** [comment]
up

**Comment by danialfarid** [comment]
Fixed in version 6.0.3
