### ISSUE TITLE
z-index -100000 issue on iOS Safari

### ISSUE THREAD

**Issue by Bertjuhh** [danialfarid/ng-file-upload#871]
The page we use your file upload on had some weird issues on iOS Safari.
All other browsers (Safari, Chrome, IE, FF & Opera) devices (Android & WP) work just fine.
But only on iOS Safari the whole page was rendered and suddenly everything went behind the background. I found in the code ng-file-upload-all.js row 733 there was this css line: 'z-index', '-100000'). By removing this, it workes fine.

Iam wondering what the side effects will be when removing this line, since I cannot find anything stranges to happen.

Btw: I use the latest version (5.0.9)

**Comment by danialfarid** [comment]
That shouldn't have any side effect since it is an invisible zero length element. But I don't see how z-index on an invisible element could cause any issue.

**Comment by danialfarid** [comment]
Fixed in version 6.0.3
