### ISSUE TITLE
Unable to read response headers

### ISSUE THREAD

**Issue by rodrigogalindez** [danialfarid/ng-file-upload#873]
Hi Danial. Is there a way to get access to the response headers on success of the upload? I'm using: 

```javascript
file.upload.success(function (data, status, headers, config) {
	console.log(status);
	console.log(headers);
	console.log(headers['Location']);
});
```

Console returns:

`204`
`function anonymous(name)`
`undefined`

Network tab shows Response Headers correctly as in this screenshot:  http://cl.ly/image/2f1A1O2X0s3N

Any help? Thanks!

**Comment by danialfarid** [comment]
use `then()` function

**Comment by rodrigogalindez** [comment]
Thanks. Still doesn't work. Here's my code:

```javascript
file.upload.then(function (response, headers) {
	if (response.status > 0) {
		console.log(response.status);
		console.log(headers);
		console.log(headers['Location']);
	}
});
```

Console returns:

`204`
`undefined`
`angular.js:11607 TypeError: Cannot read property 'Location' of undefined`

**Comment by rodrigogalindez** [comment]
Any help with this, Danial?

**Comment by danialfarid** [comment]
```
file.upload.success(function (data, status, headers, config) {
    console.log(status);
    console.log(headers);
    console.log(headers('Location'));
});
```

**Comment by admiralobvious** [comment]
Still does not work for me.

          file.upload = Upload.http({
            url: 'http://127.0.0.1:5000/v1.0/files',
            method: 'POST',
            headers: {
              'Content-Type': file.type
            },
            data: file
          });

          file.upload.success(function (data, status, headers, config) {
            console.log(status);
            console.log(headers());
            console.log(headers('Location'));
          });

Response:

    201
    Object {}
    null

**Comment by rodrigogalindez** [comment]
Still not working:

`204`
`function anonymous(name)`
`null`

**Comment by danialfarid** [comment]
what browser? Can you create a jsfiddle?

**Comment by rodrigogalindez** [comment]
Chrome Version 43.0.2357.132 (64-bit)

Fiddle is: https://jsfiddle.net/2drmu3a0/

It will not work as AWS keys are hardcoded in the JS and I removed them. Any clues on this?

**Comment by danialfarid** [comment]
The plugin is using the underlying angular $http for response and response headers, so this issue would not be related to this plugin, there is no special handling of response headers happening in this plugin.
You can try it with regular $http or post it on stackoverflow might be aws related.

**Comment by marianocarpentier** [comment]
I managed to get the headers from an S3 upload by exposing the headers in the CORS config in my bucket:

<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedHeader>*</AllowedHeader>
    <ExposeHeader>Location</ExposeHeader>
    <ExposeHeader>ETag</ExposeHeader>
    <ExposeHeader>Date</ExposeHeader>
  </CORSRule>
</CORSConfiguration>

By doing so, this works:

file.upload.then(function (data) {
console.log(data.headers());
console.log(data.headers('Location'));
}

**Comment by pratik60** [comment]
Lifesafver!

**Comment by JoshuaNovak919** [comment]
@marianocarpentier Thanks!! Saved me so much time!
