### ISSUE TITLE
Can't get PUT request working.

### ISSUE THREAD

**Issue by AnimaMundi** [danialfarid/ng-file-upload#876]
#### My Code:
````javascript

var rootUrl = 'localhost/example/api/';
var resource = 'users';
var ext = '.json';

this.putUpload = function(entity, file, progress, success, error) {
    if (file) {
        if (entity.hasOwnProperty('id')) {

            url = rootUrl + resource + '/' + entity.id + ext;

            Upload.upload({
                 url: url,
                method: 'PUT',
                file: file
            }).progress(progress).success(success).error(error); 
        }
    }
};

this.postUpload = function(file, progress, success, error) {
    if (file) {
           
        url = rootUrl + resource + '/' + ext;
            
        Upload.upload({
            url: url,
            method: 'POST',
            file: file
        }).progress(progress).success(success).error(error); 
    }
};

````
This code is present inside a ````Service````,
````postUpload()```` works, ````putUpload()```` doesn't.

CakePHP runs the backend API, in the case of ````postUpload()```` I grab the file from the PHP variable ````$_FILES````, however when I run ````putUpload()```` this variable is empty.

**Comment by danialfarid** [comment]
Your server probably does not handle put requests for file upload properly

**Comment by AnimaMundi** [comment]
Yes you're right,
PHP will not populate the $_FILES variable when receiving a PUT request.
Instead, binary data needs to fed in through the "php:\\input" stream.
Not ideal, but that's PHP's problem not an issue with your module so I apologise for opening this issue!
To compensate, I will make a pull request to edit the documentation to include details on how to handle PUT requests on a PHP server if you wish?
Thanks!

**Comment by danialfarid** [comment]
You could add that to the php wiki page or a new wiki page to be linked in the php section

**Comment by AnimaMundi** [comment]
Unfortunately I don't think I'm going to be able to get this working,
I've managed to get .txt files working, but everything else seems to lose critical data in whatever encoding and decoding is happening under the hood with PHP.
If I revisit and find a solution later on I'll let you know, but it does not look like it will be simple.
