### ISSUE TITLE
PHPSlim Framework + Why GET request 

### ISSUE THREAD

**Issue by romainFan3466** [danialfarid/ng-file-upload#877]
Hi, 
I picked up the solution from @logusgraphics  at [textAngular issue](https://github.com/fraywing/textAngular/issues/213#issuecomment-111205155) to implement ng-file-upload into textAngular.
The problem is I have an issue on request made : 

    GET http://localhost/myblog/app/API/upload/img/ 404 (Not Found)

In my controller I have : 

    $scope.upload = function(){
        Upload.upload({
            url: API/upload/img',
            file: $scope.files[0],
            method: 'POST'
        }).progress(function (evt) {
            $scope.progress = parseInt(100.0 * evt.loaded / evt.total);
        }).success(function (data) {
            $scope.progress = 0;
            $scope.image = data.dir+data.filename;
        });
    };

On the server side I use PHP Slim framework to make an API. I did it according to the wiki provided  : 

    $app->post('/upload/img', function(){
	    $filename = $_FILES['file']['name'];
	    $destination = '/upload/img/' . $filename;
	    move_uploaded_file( $_FILES['file']['tmp_name'] , $destination );
	    echoResponse(200, null);
    });

My folder `upload/img` has the write/read permissions for all. 

Why do I get a GET request to this `upload/img/`  ? I agree if the request would be with the file name but why to this address ? I can't upload my image anymore with the POST method.
Could you tell me if something is wrong in my conf ? 
Thanks in advance.

**Comment by danialfarid** [comment]
This plugin doesn't send GET it's from another part of your code.

**Comment by logusgraphics** [comment]
Dear @romainFan3466 you must be aiming wrongfully at the API's address "upload/img" that's why you're getting a 404. You must understand that this image upload implementation needs deep understanding of how AngularJS works and also Danial Farid's Upload Service. Your back end side (PHP Slim) needs to return a response with the directory and the filename in which the image was uploaded.
