### ISSUE TITLE
Problem with additional attributes

### ISSUE THREAD

**Issue by LennyLip** [danialfarid/ng-file-upload#879]
I have a upload button       

        <button 
             ngf-change="upload($files)" ngf-multiple="true"
             type="file" ngf-select ngf-accept="'image/*'" ngf-capture="'camera'"
             ngf-min-size='10' ngf-max-size='30000000'>
             tratata
        </button>

it's work fine and "files" array is populate correctly.

But if i add ng-if attr populating "files" is broken:

       <button ng-if="!files"
             ngf-change="upload($files)" ngf-multiple="true"
             type="file" ngf-select ngf-accept="'image/*'" ngf-capture="'camera'"
             ngf-min-size='10' ngf-max-size='30000000'>
             tratata
        </button>

or ng-if="files==undefined"

Select file popup window is work, but when i've click OK - "files" still undefined.

Also, f.e., it is does not work, when i've add angular-strap tooltip attributes:

       <button data-placement="right" data-animation="am-flip-x" bs-tooltip="tooltip'"
             ng-model="files"
             ngf-change="upload($files)" ngf-multiple="true"
             type="file" ngf-select ngf-accept="'image/*'" ngf-capture="'camera'"
             ngf-min-size='10' ngf-max-size='30000000'>
             tratata
        </button>

**Comment by LennyLip** [comment]
Also, it does not work if i remove
ngf-change
and $watch for "files"

watch event does not fired.

**Comment by danialfarid** [comment]
https://github.com/danialfarid/ng-file-upload/issues/711

**Comment by LennyLip** [comment]
ng-if="!$parent.files" does not work

ng-if="1" also does not work.

will try to debug problem

**Comment by LennyLip** [comment]
yep, its work like a:

1. ng-if="1"  ng-model="$parent.files"

2. ng-if="1"  bs-tooltip="tooltip'" ng-model="$parent.$parent.files"

completely unintuitive :)
