### ISSUE TITLE
Any reason why not parsing accept?

### ISSUE THREAD

**Issue by gumatias** [danialfarid/ng-file-upload#881]
Looking at my input and the [source code][1] looks like we don't parse it, is there a particular reason why? looks like what was passed is being disregarded, therefore allowing all files to be accepted.

`<input type="file" accept="{{accept}}" name="document-attachment" ng-show="(!limit || documents.length < limit) &amp;&amp; !isDisabled" ngf-change="attachDocument($files)" ngf-select="false" tabindex="-1" style="visibility: visible; position: absolute; overflow: hidden; width: 1px; height: 1px; z-index: 100; border: none; margin: 0px; padding: 0px;">`

[1]: https://github.com/danialfarid/ng-file-upload/blob/master/dist/ng-file-upload.js#L278

**Comment by danialfarid** [comment]
accept is only for popup window and is browser specific. Use ngf-accept for that. Read the related doc in the readme file.

**Comment by gumatias** [comment]
@danialfarid what's the behavior of ngf-accept? does it work across all browsers?

**Comment by danialfarid** [comment]
```accept="image/*" // see standard HTML file input accept attribute
ngf-accept="'image/*'" or "validate($file)" // function or comma separated wildcard to filter files allowed
```
yes
