### ISSUE TITLE
Model not changing on selecting file

### ISSUE THREAD

**Issue by varunachar** [danialfarid/ng-file-upload#882]
HTML Code:

```html
<script type="text/ng-template" id="closeImageTemplate.html">
                <button type="button" class="btn btn-default" ng-click="removeImage(pic)">
               Remove
              </button>
</script>
<div ngf-select="" ngf-drop="" ng-model="uploads" ngf-multiple="true" ngf-accept="'image/*'" ngf-capture="'camera'" ngf-drag-over-class="{accept:'dragover', reject:'dragover-err', delay:100}" ngf-keep="true" ngf-keep-distinct="true" ngf-reset-on-click="false" ngf-reset-model-on-click="false" ngf-allow-dir="false" class="hlyt-drop-box" ngf-drop-available="dropAvailable">Select File
 <span ng-show="dropAvailable">or Drop</span></div>
 <br>
 <div class="hlyt-preview-section">
     <span class="hlyt-preview-img" ng-repeat="pic in uploads">
          <img ngf-src="pic" ngf-accept="'image/*'" popover-template="closeImageTemplate" popover-trigger="click" popover-placement="top">
     </span>
</div>
```

```javascript
// Image Upload
$scope.$watch('uploads', function(uploads) {
$scope.formUpload = false;
  if (uploads != null) {
    for (var i = 0; i < uploads.length; i++) {
        $scope.errorMsg = null;
              (function(file) {
                uploadFile(file);
               })(uploads[i]);
      }
  }
});

$scope.removeImage = function(pic) {
    console.log($scope.uploads);  // always empty
}
```

The code only enters the $watch function when the page first loads. It doesn't when I select a file. I've tried using $watchCollection, $watch with equality, but nothing seems to work.

Morever, in the removeImage function, the $scope.uploads value is always empty.

Using latest version available in bower, 5.0.9. Please Advice.

**Comment by bonkenmoose** [comment]
Same issue in latest chrome

**Comment by varunachar** [comment]
Dunno if its chrome related. The Demos seem to work fine in the latest chrome. I even debugged them to see what the difference was.

**Comment by erkanarslan** [comment]
Same here. When a file selected ng-model does not update.

For now, I use

    ngf-change="fileUpdated($files, $event)"

 and in the callback function I can access the files with:

    $scope.files = $event.target.files`

This is my upload code, it works fine:

    var file = $scope.files[0];
    
    Upload.upload({
        url    : 'api/user/update/profile-picture',
        file   : file
    })

**Comment by terjekrogstad** [comment]
Same issue here in different browsers on a Mac with both dev-version and built version of app. Solved it with @erkanarslan solution. Thx!

**Comment by varunachar** [comment]
Are you guys using BrowserSync while working? I was using it and ngf-change also didn't work for me. So I tried using the non BrowerSync url and found ngf-change started working for me over there. The original problem still exists though. But in case you are using browersync, try checking the code in the non browersync url.

**Comment by danialfarid** [comment]
If this is still an issue could you guys create a jsfiddle showing the error?
You can use the example on the readme page and add your library/codes there.
Also it might be scope related, see if using `ng-model="$parent.uploads"` does any difference.

**Comment by wojno** [comment]
using `$parent` on the model worked for me.

**Comment by erkanarslan** [comment]
Yep, using $parent works.

My code is in an ng-switch block. It's my fault for not considering the scope.

**Comment by bonkenmoose** [comment]
Parent works here too, thanks

**Comment by varunachar** [comment]
Nope. Didn't work for me.

**Comment by erkanarslan** [comment]
You may need to use multiple `$parent`s depending on your scope structure.

**Comment by varunachar** [comment]
There are no nested scopes. Below ngf code, I have a preview block that works off the same $scope.uploads model. Using ngf-change, I'm able to set the $scope.uploads model, and the files are displayed in the preview block. So the scope is correct.

**Comment by danialfarid** [comment]
@varunachar create a jsfiddle if the problem still exists and open an issue or reopen.

**Comment by varunachar** [comment]
Hi.. Don't have time to create a jsfiddle right now, I'll try creating it when I get the time.. but in my case I figured out that the model was getting added to some other scope even though there is no scope nesting.. I'm yet to figure out which scope. It's definitely not the parent scope. So effectively, the model is getting added to some other scope and the function defined in ngf-change is getting called against a different scope (I don't know if it's always like that since I'm pretty new to angular)

**Comment by phuyem** [comment]
I have been using the library for months, around May up to now, through various update, I have to agree with @varunachar  this behavior, I don't know why it does not happen on danialfarid fiddle : 

ng-model is not updated on the first time, only 2nd time onward. ngf-change works normally though.

**Comment by danialfarid** [comment]
Can you reproduce it in the demo page or create a jsfiddle?

**Comment by victmo** [comment]
Hi!
First of all, thanks for this awesome directive, you've made my life so much easier.
Here's a simple fiddle illustrating the problem: https://jsfiddle.net/victmo/gmuge0dj/
The model changes to an empty object right after you select or drop a file.

**Comment by danialfarid** [comment]
It is not empty, the binary is not viewable by toString() or JSON.stringify().

**Comment by victmo** [comment]
Ok got it, that totally makes sense. I assumed the file name was being returned, but it makes more sense to return the actual file.
Thanks for the quick response.

**Comment by korell** [comment]
Hi everyone, I encountered the same issue and I confirm that binding the ng-model to the $parent scope it works for me !
Thanks Danial for that great directive !
