### ISSUE TITLE
Unable to use the library

### ISSUE THREAD

**Issue by lousan92** [danialfarid/ng-file-upload#885]
I'm trying to use this library using an application with Node.js, Express and AngularJS. I've installed it with NPM, but now I can't use it. 

The library is, of course, in node_modules. In my index template Jade page I have all my includes, but it seems that script(src="node_modules/ng-file-upload/dist/ng-file-upload.js") doesn't work, as I create a button in another page with ng-file-select and it doesn't display the exploring window. What could I do? Thanks in advance.

**Comment by danialfarid** [comment]
It is 'ngf-select`
