### ISSUE TITLE
Instead of saving images

### ISSUE THREAD

**Issue by yunyeng** [danialfarid/ng-file-upload#887]
I kind of have problem, I am using the plugin to upload 3-4 images to one div and create ad campaign for my users. And when the form submits another html2canvas plugin turns this div into canvas as to png. But images do not show up, because your plugin I guess upload them to the same domain, I used other plugins but they just use data:image, I guess not upload them to the server side, so images show up without any problem, can we do this with your plugin as well? Thank you

**Comment by danialfarid** [comment]
User 'ngf-src' directive.

**Comment by yunyeng** [comment]
I do use it, the problem is I can not see the images when I try to turn them into canvas. The plugin stores them locally in different place than the native way. They need to be hashed in base64 and stored in locally until I send them to the server.

**Comment by danialfarid** [comment]
Ok I will add the option to the next version.
For now you can remove the condition at line: https://github.com/danialfarid/ng-file-upload/blob/master/dist/ng-file-upload.js#L703 to always convert it to base64.

**Comment by yunyeng** [comment]
Thanks, I must have missed that condition! Also how can we add specific remove buttons to remove those images?

**Comment by danialfarid** [comment]
remove them from the model

**Comment by danialfarid** [comment]
Since version 5.1.0 you can add `ngfNoObjectUrl=true` to make it always convert it to base64 url.

**Comment by StephaneC** [comment]
I set 
<input type="file" ngf-select ngf-no-object-url="true" ng-model="newPoll.answers[$index].image" name="file" accept="image/*" ngf-max-size="2MB" required>
but received object still looks like that : 
File
dataUrl: "blob:http%3A//localhost%3A8080/336c0852-fe53-4800-b886-71350e4eb4f6"
lastModified: 1427464119000
lastModifiedDate: Fri Mar 27 2015 14:48:39 GMT+0100 (CET)
name: "logo.png"
size: 16752
type: "image/png"
webkitRelativePath: ""

So no, base64. Any clue?

**Comment by danialfarid** [comment]
There have been a fix at version 7.0.10 for an issue that would cause ngfNoObjectUrl not to take effect if there are prior validations.
