### ISSUE TITLE
How to prevent window select files open

### ISSUE THREAD

**Issue by chepapoa** [danialfarid/ng-file-upload#890]
I'm using ng-file-upload and i need to limit the number of upload images. So i want to prevent the select file window open. I tried this, but this wont work.
```
 <button class="btn btn-block btn-default btn-flat"  ngf-select="{{canSelect}}" ngf-change="upload($files)" accept="'image/*'" ngf-multiple="true">Select Images</button>
```
How can i do that?

Thanks

**Comment by danialfarid** [comment]
This is working for me:
http://jsfiddle.net/d53qyb88/

**Comment by chepapoa** [comment]
hi danialfarid.
that's the ideia, but i want to upload 2~5 files an then prevent to upload more, like this:
 if ($scope.images.length < $scope.usuario.Imagens) {
            $scope.upload($scope.files);
        }
        else {
            $scope.canSelect = false;
            alert('The maximum number o files has exceeded.');
        }

**Comment by danialfarid** [comment]
Use `ngf-keep` option
