### ISSUE TITLE
ng-file-upload calling twice the service and the  ngf-accept="'.csv'" attribute is not working

### ISSUE THREAD

**Issue by HaythemJ** [danialfarid/ng-file-upload#891]
I am facing some problems when using this module and I hope that you will be able to help me:

Here is my code: I want to upload only csv files

                <button type="button" class="btn btn-info" ngf-select ngf-change="upload($file)" ngf-accept="'.csv'" ngf-multiple="false">Importer fichier</button>

                $scope.upload = function (file) {
                    Upload.upload({
                        url: 'http://localhost:20120/api/Context/UploadFile',
                        file: file
                    }).progress(function (evt) {
                        var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
                        console.log('progress: ' + progressPercentage + '% ');
                    }).success(function (data, status, headers, config) {
                        console.log('success upload file ');
                    }).error(function (data, status, headers, config) {
                        console.log('error status: ' + status);
                    })
                           
        };

Here I am facing 2 problems:

1/ The client is calling the service twice. the first one is when I click the button and the second one when I select the file

2/ The filter on the csv files is not applied as mentioned in the ngf-accept="'.csv'" attribute.

Thank you in advance for your support.

**Comment by danialfarid** [comment]
Use `accept` read the docs.
The syntax is `ngf-change="upload($files)"` with an s at the end, and you should check if it is not empty before uploading.

**Comment by HaythemJ** [comment]
Hi,

Thank you for the reply. Issue#1 is fixed using the right instructions. But for issue#2 what I want is that I filter documents in the popup window. Using ngf-accept="validate($file)" did not solve my problem. I don't want to reject the upload using 

$scope.validate = function ($file) {
           return false;
        };

**Comment by HaythemJ** [comment]
Hi,

Thank you for the reply. Issue#1 is fixed using the right instructions. But for issue#2 what I want is that I filter documents in the popup window. Using ngf-accept="validate($file)" did not solve my problem. I don't want to reject the upload using

    $scope.validate = function ($file) {
       ////Some validation here
       return false;
    };

I want to disaply only csv files in the popup.

**Comment by danialfarid** [comment]
Use `accept` instead of `ngf-accept` they are different and first one is for the popup, it is mentioned in the docs.

**Comment by HaythemJ** [comment]
Many thanks for your support @danialfarid 

I will close the issue.

**Comment by Sampath-Lokuge** [comment]
@HaythemJ Can you tell me how did you fix the issue 1 ? Thanks.

**Comment by HaythemJ** [comment]
Hi @Sampath-Lokuge ,

Here is my code:
 ```
$scope.upload = function (files) {
            if (files && files.length) {
                for (var i = 0; i < files.length; i++) {
                    var file = files[i];
                    Upload.upload({
                        url: 'http://localhost:20120/api/Context/UploadFile',
                        fields: { ATT1: att1, ATT2, att2 },
                        file: file,
                        headers: { Authorization: 'Bearer ' + localStorageService.get('authorizationData').token }
                    }).progress(function (evt) {
                        var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
                        console.log('progress: ' + progressPercentage + '% ');
                    }).success(function (data, status, headers, config) {
                        reloadData();
                        console.log('success upload file ');
                    }).error(function (data, status, headers, config) {
                        toaster.error({ title: "Téléchargement", body: "Une errur est survenue !" });
                        console.log('error status: ' + status);
                    });
                }
            }

        };
```

Best Regards
HJ

**Comment by Sampath-Lokuge** [comment]
@HaythemJ Thanks for the feedback.I have used the same code snippet.But it gives same issue which you have mentioned on the issue 1.You too can test this if you put an `alert('error')` on the `else` part of this  ` if (files && files.length) {`.I think this is the BUG on this api. You cannot use `Sweetalert` kind of popup messages on the else part which I have mentioned above.But you can use in-line messages without any issue as shown below.Your thoughts ? Thanks. 

     <ul>
                        <li ng-repeat="f in vm.errFiles">
                            {{f.name}}
                        </li>
                    </ul>

**Comment by danialfarid** [comment]
@Sampath-Lokuge That's expected behaviour previous files will be reset and set to null upon clicking on the button. There are other issues and mentions in the docs about this.

**Comment by danialfarid** [comment]
https://github.com/danialfarid/ng-file-upload/issues/1401#issuecomment-192820003

**Comment by ushakrn10** [comment]
@danialfarid issuw with IE11 browser upload_document method is calling twice, it is working fine for other browsers.
<input type="file" class="form-control" ngf-select="false" ngf-change="upload_document($file)">
