### ISSUE TITLE
Multer 1.0.1

### ISSUE THREAD

**Issue by CrackerakiUA** [danialfarid/ng-file-upload#892]
Have you checked new update of multer? It ask for "form enctype='multipart/form-data'" so file can be uploaded, how can we add that? At the moment when i am trying to upload file, i see undefined fields.

**Comment by danialfarid** [comment]
It should work as expected. What request is being sent to the server?

**Comment by CrackerakiUA** [comment]
req.file is empty, should be file details. I have build small code to send find without plugin and it's working. Multer need's form enctype='multipart/form-data

**Comment by root-io** [comment]
Same problem, I can't upload any files with the new version of multer.

**Comment by ashraffayad** [comment]
Same problem. multer doesn't work with ng-file-upload

**Comment by danialfarid** [comment]
@root-io Can you go to the network tab and post here the content of the POST request being sent for file upload in the working version versus not working version?
@CrackerakiUA You could also do the same send here the content/headers of request from the network tab when using plugin versus not using the plugin.
Thanks,

**Comment by CrackerakiUA** [comment]
By me the topic is closed, i have stopped to use ng-file-upload, my own script worked out. I guess root-io can post his content/header and when his problem is closed topic can be closed.

**Comment by root-io** [comment]
I tried to reproduce with multer 1.0.3 and ng-file-upload 7.0.10 and it seems to be fixed.
