### ISSUE TITLE
Send file into body

### ISSUE THREAD

**Issue by orselliandrea** [danialfarid/ng-file-upload#893]
Hi, since a few time when i send a file to node.js server, not show in req.files as object but in req.body as string.
I had update bower with dependences 1 week ago.
Can you help me?
Thanks
A

**Comment by danialfarid** [comment]
Post your code here or create a jsfiddle.

**Comment by orselliandrea** [comment]
I discovered that this problem is caused by the angular version.
After 1.3.0 version the upload not allow access caused by there isn't "'Access-Control-Allow-Origin' header is present on the requested resource".
I use in node server the package “connect-multiparty” to catch the media.

What code can I post?

This in my controller:

	$scope.upload = function (files) {
        if (files && files.length) {
	        for(var i=0;i<files.length;i++){
		        var lim = i==0 ? "" : "-"+i;
		        var name = odisseoServ.userLogin.utenti_id + "." + Date.now() + lim;
		        Upload.upload({
		            url: 'http://gestione.sicurixscelta.it:8080/up',
		            fields: { "nameFile" : name },
		            file: files[i]
		        }).success(function(data){
			        console.log(data)
		        }).error(function(data){
			        console.log(data)
		        });

		    }
	    }
    };


This in my service:

app.post('/up', multipartyMiddleware, function(req, res) {
	
	res.header("Access-Control-Allow-Origin", "*");

	fs.readFile(req.files.file.path, function (err, data) {
		var extSplit = req.files.file.originalFilename.split(".");
		var ext = extSplit[extSplit.length-1];
		var nome = req.body.nameFile + "." + ext;
		var newPath = '../www/uploads/'+nome;
		var newPathThumb = '../www/uploads/thumbs/'+nome;
		var newPathLarges = '../www/uploads/larges/'+nome;
		var fields = {
			"media_url" : nome,
			"media_type" : req.files.file.type
		}
		fs.writeFile(newPath, data, function (err) {
			
			im.identify(newPath,function(err,features){
					
					im.resize({
						srcPath: newPath,
						dstPath: newPathThumb,
						width:   400
						}, function(err, stdout, stderr){}
					);
					im.resize({
						srcPath: newPath,
						dstPath: newPathLarges,
						width:   1000
						}, function(err, stdout, stderr){}
					);
					var type = "media";
					var table = tables[type]["tabella"];
					var date = new Date();
					var str = "(";
					var val = "(";
					for(key in fields){
						if(tables[type]["fields"].indexOf(key) != -1) {
							str += key + ",";
							val += "'" + fields[key] + "',";
						} 
					}
				
					str += type + "_data_creazione)";
					val += fn.formatDate() + ")";
					
					connection.query("INSERT INTO "+table+" " + str + " VALUES " + val ,function(err,data){
				
						if(err) {
							res.end(fn.respond(err,false));
						} else {
							req.files = {};
							res.end(fn.respond({id:data.insertId},true));
						}
						
					});
			});
			
		});
	});

});

If I set 

config.headers = { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8' };

in file ng-file-uploads.js work but the file sended in code format and in object body.

Thanks

**Comment by danialfarid** [comment]
Assuming it is fixed by now.
