### ISSUE TITLE
pass full object contening file to upload

### ISSUE THREAD

**Issue by cyrilepinat** [danialfarid/ng-file-upload#895]
Hi, 

I need to call an API service that needs the following parameter :
<pre>
document	: {
   name : string, 
   documentFile : file, 
   ... etc...
}
</pre>

Is there a way to do that ?

Thanks in advance

**Comment by danialfarid** [comment]
what would be the value for the file? you can send the encoded base64 value of the file but the actual file binary is being sent as a multipart form data and is in the root.
