### ISSUE TITLE
Detect / catch abort in Upload.upload().error... 

### ISSUE THREAD

**Issue by aderowbotham** [danialfarid/ng-file-upload#897]
Calling `abort()` results in an upload error being returned, which is fine:

    var upload = Upload.upload({
      url: "someurl",
      file: myFile,
      ...
      })
      .progress()
      .sucess()
      .error(function(data, status, headers, config) {
        $log.debug("An error occurred, status = " + status);
        // ^ This is triggered on abort
      });
    
      // abort
      upload.abort();

...but how to identify in that error callback whether the error was caused by aborting?

To the error function it looks the same as a connection failure. `data` is null and `status` is 0

**Comment by danialfarid** [comment]
For http errors you would have a non zero status code. Also you can set `upload.aborted = true` and in the error you can check `if (upload.aborted) {...}`

**Comment by aderowbotham** [comment]
Actually you also get a zero status code if the browser cannot connect to the server at all (e.g. CORS reasons, or no network connection).

But your suggestion of actively setting an `aborted` property removes any ambiguity. Thank you!
