### ISSUE TITLE
How to open native OS file upload dialog programmatically?

### ISSUE THREAD

**Issue by p4004** [danialfarid/ng-file-upload#902]
Hello,

I need to open file upload dialog when clicked on a button in tinymce toolbar. So using this library I add a button to upload files, hide it from user and when user clicks tinymce button, I programmatically click the file upload button.

However that does not work because of this line: 

if (evt && evt.clientY > 0) {

When clicking programmatically, evt.clientY = 0;

Also, if I comment this line, there is an issue with browsers that use flash to upload files. I know that programmatically clicking flash button is not possible.

So, are there any chances that programmatic opening of file upload dialog would be possible in all browsers?

**Comment by danialfarid** [comment]
Fixed in version 6.0.3
