### ISSUE TITLE
Possibility to obtain drag-and-drop support status or hide message or hide ng-no-file-drop

### ISSUE THREAD

**Issue by shershen08** [danialfarid/ng-file-upload#903]
If there's some internal property or method of the plugin to know if the current browser supports drag-and-drop uploading of the files?
There's a attribute ```ng-no-file-drop``` for notification message when d'n'd is not supported, but tag with this attribute is still displayed event when browser supports d'n'd - so there's two

**Comment by danialfarid** [comment]
That was a typo in readme it is `ngf-no-file-drop`. You can also use `ngf-drop-available`
