### ISSUE TITLE
fields with boolean doesn't behave as expected

### ISSUE THREAD

**Issue by benneq** [danialfarid/ng-file-upload#904]
I'm using Chrome 44.

```
Upload.upload({
    ...,
    fields: {
        'description': $scope.description,
        'public': $scope.public
    },
    file: $scope.file,
    sendFieldsAs: 'json-blob'
})
```

This results in:
```
------WebKitFormBoundaryEbPaAvKBm7IlxkjB
Content-Disposition: form-data; name="description"

foo
------WebKitFormBoundaryEbPaAvKBm7IlxkjB
Content-Disposition: form-data; name="public"; filename="blob"
Content-Type: application/json


------WebKitFormBoundaryEbPaAvKBm7IlxkjB
Content-Disposition: form-data; name="file"; filename="test.jpg"
Content-Type: image/jpeg


------WebKitFormBoundaryEbPaAvKBm7IlxkjB--
```

As you can see: `description` got sent fine, but `public` got a filename and no visible content.

In my opinion this should be this:
```
------WebKitFormBoundaryEbPaAvKBm7IlxkjB
Content-Disposition: form-data; name="public"
Content-Type: application/json

true
```

**Comment by danialfarid** [comment]
Yes regular post and form data post are different. You could set those fields as `data` option and then on the server side get the `data` field and convert it from json string to object. There is no way to set the content-type of individual form data element unless they are blob.
You can also give `sendFieldsAs:json-blob` a try might work.

**Comment by benneq** [comment]
I already use `sendFieldsAs:json-blob`.
