### ISSUE TITLE
hidden input[type=file] + required not possible?

### ISSUE THREAD

**Issue by dbounds** [danialfarid/ng-file-upload#905]
Can you provide an a example where the user has a hidden input that's required and a a single link/button to display the file selector and upload?

In an earlier version of your library that was how I implemented this but cannot get it to work with your latest version/api.

Here's an example of what I used to do:

```
div(class='file-input-container type')
  a(href='#', ng-click='showFileSelector()', ng-if='candidate.resume.file_name') Attached: {{candidate.resume.file_name}}
  a(class='placeholder', href='#', ng-click='showFileSelector()', ng-if='!candidate.resume.file_name') Upload Resume
 input(id='main-attachment', name='cResume', class="attachment", style="display:none;", type="file", ng-file-select="onFileSelect($files)") 
```

**Comment by danialfarid** [comment]
The name of the directives have changes, read the README file.

**Comment by dbounds** [comment]
@danialfarid I've updated with the new directives and can get the above working, I just can't get it working with the input field being required.

The example on your demo page has a visible input.

**Comment by dbounds** [comment]
@danialfarid 

What I have now is:

```
div(class='file-input-container type')
  a(href='', ng-click='e.preventDefault(); showFileSelector()', ng-if='candidate.resume.file_name') Attached: {{candidate.resume.file_name}}
  a(class='placeholder', href='', ng-click='e.preventDefault(); showFileSelector()', ng-if='!candidate.resume.file_name') Upload Resume
  input(id='main-attachment', name='cResume', class="attachment", style="display:none;", type="file", ngf-change="onFileSelect($files)", required=portal.position.application_form.resume==='required')
div(class='error-container', ng-show="form.cResume.$error.required")
  span(class='error') A resume is required
```

**Comment by dbounds** [comment]
In that case, ngf-change is never triggered when the file is selected. The same is the case if I use ngf-select="" on the <a> instead of my showFileSelector() function.

**Comment by dbounds** [comment]
Live example here: https://acme.breezy.hr/p/575b90b85ffc-marketing-coordinator/apply2

**Comment by danialfarid** [comment]
Could you ask the question on SO. It doesn't seem to be an issue with the plugin but just a question.
