### ISSUE TITLE
ngfSelect mobile safari/touch fix

### ISSUE THREAD

**Issue by priley86** [danialfarid/ng-file-upload#909]
For some reason the "select file or drop" box in the demo does not open an upload photo dialogue on mobile safari.

Changing the clickAndAssign function in the ngfSelect directive from:
```javascript
      function clickAndAssign(evt) {
        if (evt && evt.clientY > 0) {
          fileElem[0].click();
        }
```
to this:
```javascript
      function clickAndAssign(evt) {
        if (evt) {
          fileElem[0].click();
        }
```
appears to resolve the issue. The event.clientY appears to be undefined on mobile safari.

Hope this helps...

**Comment by danialfarid** [comment]
Fixed in version 6.0.3
