### ISSUE TITLE
Drag & drop doesn't work on Microsoft Edge

### ISSUE THREAD

**Issue by richardthombs** [danialfarid/ng-file-upload#910]
Dragging files into the drop zone on the demo page comes up with a "no entry" cursor and doesn't accept the file. Clicking to select a file and uploading that way works though.

Microsoft Edge, Windows 10.

**Comment by UnraveledMnd** [comment]
Also, ngf-drop-available still evaluates to `true` on Microsoft Edge.

**Comment by danialfarid** [comment]
Seems like known microsoft Edge issue:
https://social.technet.microsoft.com/Forums/ie/en-US/ec3c0be0-0834-4873-8e94-700e9df9c822/edge-browser-drag-and-drop-files-not-working?forum=ieitprocurrentver

**Comment by danialfarid** [comment]
I can set the availability of drop to false for Microsoft Edge but they might fix it soon.

**Comment by richardthombs** [comment]
You seem to be releasing pretty frequently at the moment, so I would say return false until it's fixed. After all, MS might take ages to fix it... replies still don't go to the "Reply-To" address in the Mail app!

**Comment by danialfarid** [comment]
Fixed at version 7.0.9

**Comment by danialfarid** [comment]
hmm or maybe not, could you come up with a way to detect windows edge user agent?
this `/Edge\/12./i.test(navigator.userAgent)` doesn't seem to work for my VM windows 10

**Comment by richardthombs** [comment]
RegEx and dropAvailable work fine on my Edge.

UA is `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240`
