### ISSUE TITLE
500 (Unexpected character ('-' (code 45)) in numeric value: expected digit (0-9) to follow minus sign, for valid numeric value  at [Source: java.io.StringReader@45a1bf65; line: 1, column: 3])

### ISSUE THREAD

**Issue by azherf** [danialfarid/ng-file-upload#911]
I am trying to upload an excel file with ng-file-upload. When I use the uploadBySubmit method, I get the following error.

com.google.appengine.repackaged.org.codehaus.jackson.JsonParseException: Unexpected character ('-' (code 45)) in numeric value: expected digit (0-9) to follow minus sign, for valid numeric value
 at [Source: java.io.StringReader@45a1bf65; line: 1, column: 3]

I will be grateful if someone could let me know what I am doing wrong.

This is my controller:
--------------------------
angular_app.controller('settingsImportOrExportController', ['$scope', 'settingsImportOrExport', 'Utils', 'Upload', function($scope, settingsImportOrExport, Utils, Upload){
        
    $scope.uploadUsingUpload = function (file) {
        file.upload = Upload.upload({
            url: '/_ah/api/havasay/v1/resource/categories',
            method: 'POST',
            headers: {
                'x-hs-salt': _salt,
				'skey': (Utils && Utils.getOrganizationDetails() && Utils.getOrganizationDetails().skey),
				'Content-Type': undefined
            },
            fields: {organizationId: Utils.getOrganizationDetails()._id},
            file: file,
            fileFormDataName: 'myFile'
        });

        file.upload.then(function (response) {
            $timeout(function () {
                file.result = response.data;
            });
        }, function (response) {
            if (response.status > 0)
                $scope.errorMsg = response.status + ': ' + response.data;
        });

        file.upload.progress(function (evt) {
            // Math.min is to fix IE which reports 200% sometimes
            file.progress = Math.min(100, parseInt(100.0 * evt.loaded / evt.total));
        });

        file.upload.xhr(function (xhr) {
            // xhr.upload.addEventListener('abort', function(){console.log('abort complete')}, false);
        });
    };
    }]);

This is my html file:
------------------------

form name="myForm" ng-controller="settingsImportOrExportController"
  <fieldset>
    <legend>Upload on form submit</legend>
    Profile Picture: <input type="file" ngf-select ng-model="picFile" name="file" required>
    <br/>

    <button ng-disabled="!myForm.$valid" ng-click="uploadUsingUpload(picFile)">Submit</button>
    
  </fieldset>
  <br/>
/form

**Comment by danialfarid** [comment]
How does your request look like?

**Comment by danialfarid** [comment]
Also you won't need `'Content-Type': undefined`

**Comment by gamebox** [comment]
Don't really understand why this issue is closed.  No resolution seemed to be reached.  I was actually experiencing the same bug with almost identical code.  For me, all that had to change was putting the widget inside of a named form.  Might not address the issue above, but that may help someone else witht this issue

**Comment by krishnaiitd** [comment]
I am facing the same issue with below error:

`Unexpected character ('-' (code 45)) in numeric value: expected digit (0-9) to follow minus sign, for valid numeric value
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@561361d1; line: 1, column: 3]`

With logging at terminal 

`2017-12-26 12:07:43.570 TRACE [bootstrap,ffa7041d6b4fb4fd,ffa7041d6b4fb4fd,false] 9189 --- [izzly-worker(7)] c.i.n.s.a.f.RequestResponseLoggingFilter : 0:0:0:0:0:0:0:1  POST  /template/  HTTP/1.1  400  1
`

**Comment by torbenr** [comment]
Hi - I had a very similar problem trying to send a request via PostMan to the Nuxeo API. To cut a long story short I was mistakenly setting "content-type" as "application/json" when it should have been "multipart/form-data"

**Comment by will152520** [comment]
I had a similar problem when I trying to send a request of post method  via PostMan.I setted “content-type” as "application/json" and use the “raw”  with "json".The problem solved.

**Comment by vjmorcillo** [comment]
Same here. The problem solved swapping to raw instead form-data body.

**Comment by emartineztbcap** [comment]
I had the same issue in PHP and solve it by json encoding the body.
