### ISSUE TITLE
Can we get the physical path of the uploaded file?

### ISSUE THREAD

**Issue by abinashbohidar** [danialfarid/ng-file-upload#912]
I need the physical path of the uploaded file as I don't want to send File Object Array form one page to another. Can you please help me?

**Comment by danialfarid** [comment]
If the file is selected through browsers popup or dropped it is not possible for security reasons.

**Comment by bullitbd** [comment]
Could you explain the security reasons?  We need the file name to pass on to a parser.  Thanks.

**Comment by danialfarid** [comment]
You can get the file name by `file.name` but not the physical path on the device.

**Comment by bullitbd** [comment]
aha - sorry should have sorted that. Thanks.
