### ISSUE TITLE
Doesn't (reliably) open native picture select menu on iOS 8.3 on iPad

### ISSUE THREAD

**Issue by richardthombs** [danialfarid/ng-file-upload#913]
Hi there,

Tapping on the "Profile picture" button or the "Select file or drop" div both fail to bring up iOS' "take picture / photo library" menu.

It will occasionally work, most reliably when you've pinch zoomed out to get iOS to display the tab list, gone back to the demo page AND the first thing you try to do is click on one of the two ngf-select controls.

**Comment by danialfarid** [comment]
Fixed in version 6.0.3

**Comment by richardthombs** [comment]
Thank you for such a speedy fix and paste support too! :)
