### ISSUE TITLE
Show "Drop Zone" when user is dragging files into the browser

### ISSUE THREAD

**Issue by hancock808** [danialfarid/ng-file-upload#915]
Is it possible to only show the "drop zone" only when the user is dragging files into the browser?

**Comment by danialfarid** [comment]
Yea set the css as you like for dragged or not dragged classes.

**Comment by hancock808** [comment]
This is what I'm looking to achieve: http://jsfiddle.net/myukxhux/
Works mostly, but maybe you can recommend a better way.

I want to show the dropbox when the user drags a file into the HTML BODY and show some other CSS when dragging over the dropbox itself.

**Comment by danialfarid** [comment]
That sounds right. I would do the same approach,
