### ISSUE TITLE
Drag and Drop element overlapping previous DIV.

### ISSUE THREAD

**Issue by sweisman** [danialfarid/ng-file-upload#916]
I have a dialog popup that renders like this:

![image](https://cloud.githubusercontent.com/assets/317943/9082387/5675b018-3b6c-11e5-979c-99933e59582e.png)

The two images and the DND element are both in two separate DIVs. Does anyone have a suggestion to stop this?

**Comment by roydondsouza** [comment]
That seems to be a CSS issues; create a JS fiddle and we can help you out

**Comment by sweisman** [comment]
Sorry for not replying sooner. I figured this out.

**Comment by roydondsouza** [comment]
Cool.
