### ISSUE TITLE
Upload video server side

### ISSUE THREAD

**Issue by amicos** [danialfarid/ng-file-upload#917]
I use Upload.upload({url : urlUploadVideo,fields : {	'envId' : 13},	file : file}) to upload the video file.
In server side, I perform Web service Rest to upload the video, but doesn't work. Have you an idea, please, how to do it?
I use :   
    @Path("/upload")
    @Consumes({ MediaType.MULTIPART_FORM_DATA })
    public Response uploadContent(@FormParam("file") File uploadedFile) 

Thanks

**Comment by danialfarid** [comment]
https://github.com/danialfarid/ng-file-upload/wiki/spring-mvc-example

**Comment by amicos** [comment]
It's web service Rest. I don't use Spring.

**Comment by danialfarid** [comment]
Post it on stackoverflow lease with ng-file-upload tag.
