### ISSUE TITLE
Ng-model not populated by files on change

### ISSUE THREAD

**Issue by dackmin** [danialfarid/ng-file-upload#918]
On v6.0.3, when using ngf-select, selecting a file doesn't update model.

When using ngf-change to manually add it to model within a method, method is called twice with $files as an empty array in one of the calls.

Reverted back to v5.0.9 and it works as a charm, maybe that can be a hint.

**Comment by danialfarid** [comment]
Can you create a jsfiddle showing the problem? The demo page and jsfiddle sample both use the ng-model and it is working.
For change being called twice that's intended. When you click on the upload first it clears the previous values so there is a change to empty array and once you select the file the array would have the selected file, so you can check for empty array in your code.

**Comment by danialfarid** [comment]
It should be fixed in the latest.
