### ISSUE TITLE
Flash FileAPI HTTP error code 400 is treated as success

### ISSUE THREAD

**Issue by gessnerfl** [danialfarid/ng-file-upload#92]
Hi,

I need the flash-based FileApi solution for IE8 support. Thereby I face the following issue:
I try to bind event handler for all three events (success, error, progress). In the HTML5 version without FileApi everything works fine. But with the FileAPI the success handler is called in case of an error but in case of an successful upload no handler is called.

This issue happens when using success( ), error( ), and progress( ) and also when just using then( ) to bind the event handler functions.

I am using the latest version 1.2.3. 

Thanks and Best Regards
Florian

**Comment by danialfarid** [comment]
Doesn't seem to be that serious issue since there are workarounds and not an easy solution since it is a flash FileAPI related issue. Marking it as won't fix for now.
