### ISSUE TITLE
Cannot paste plain text in a textarea inside of a droparea.

### ISSUE THREAD

**Issue by jeremy-dimasuay** [danialfarid/ng-file-upload#920]
First off, thank you for your work!

I found this issue when trying to implement a fullpage droparea.  I've re-created a similar situation here:
http://jsfiddle.net/L6wkb54g/

I narrowed the issue down to the `paste` event listener.  As a temporary workaround, I added a conditional that skips `evt.preventDefault()` if it finds a custom attribute `ngfAllowPasteText`.  However, I believe you added it for a reason.

```
    elem[0].addEventListener('paste', function (evt) {
      if (elem.attr('disabled') || disabled) return;
      if (!$parse(getAttr(attr, 'ngfAllowPasteText'))()) { evt.preventDefault(); } // Changed this line
      if (stopPropagation(scope)) evt.stopPropagation();
      extractFiles(evt, function (files, rejFiles) {
        updateModel($parse, $timeout, scope, ngModel, attr,
          getAttr(attr, 'ngfChange') || getAttr(attr, 'ngfDrop'), files, rejFiles, evt);
      }, false, getAttr(attr, 'multiple') || $parse(getAttr(attr, 'ngfMultiple'))(scope));
    }, false);
```

Let me know if I can provide any more detail to help.  Thanks again!

**Comment by danialfarid** [comment]
Yea I will separate the paste image directive from drop in the next version. For now use the previous version 6.0.2

**Comment by jeremy-dimasuay** [comment]
Got it.  Thanks for the heads up.  :+1:

**Comment by danialfarid** [comment]
Ok it is a bit of work to separate it into another directive, so for now I just removed the preventDefaults and stopPropagation lines.
Should be working at version 6.0.4
