### ISSUE TITLE
Rejected file reasons

### ISSUE THREAD

**Issue by roydondsouza** [danialfarid/ng-file-upload#921]
If we add min and max size and accept types, can we know what was the reason the files were rejected in the rejectedFiles model? Or do we manually have to check it against our rules?

**Comment by danialfarid** [comment]
Yes `file.$error` contains the reject reason, see the readme file.

**Comment by roydondsouza** [comment]
Thank you Danial

Regards,

Roydon D' Souza
Ph.: +91-9739791096

Disclaimer Notice: This message contains confidential information and is
intended only for the individual named. If you are not the named addressee
you should not disseminate, distribute or copy this e-mail. Please notify
the sender immediately by e-mail if you have received this e-mail by
mistake and delete this e-mail from your system. E-mail transmission cannot
be guaranteed to be secure or error-free as information could be
intercepted, corrupted, lost, destroyed, arrive late or incomplete, or
contain viruses. The sender therefore does not accept liability for any
errors or omissions in the contents of this message, which arise as a
result of e-mail transmission. If verification is required please request a
hard-copy version.

WARNING: Computer viruses can be transmitted via email. The recipient
should check this email and any attachments for the presence of viruses.
The company accepts no liability for any damage caused by any virus
transmitted by this email. E-mail transmission cannot be guaranteed to be
secure or error-free as information could be intercepted, corrupted, lost,
destroyed, arrive late or incomplete, or contain viruses. The sender
therefore does not accept liability for any errors or omissions in the
contents of this message, which arise as a result of e-mail transmission.

All Emails of Roydon D'Souza are managed by the MailBox.
http://www.roydondsouza.com
