### ISSUE TITLE
File Upload called multiple times

### ISSUE THREAD

**Issue by dmanatunga** [danialfarid/ng-file-upload#922]
When trying to use the drag and drop upload mechanism in Chrome (including the demo site), the callback function for the upload file is called multiple times for the same file, even if only a single file has been selected for upload.

**Comment by danialfarid** [comment]
Can you create a jsfiddle?

**Comment by danialfarid** [comment]
ngf-change will be called once when you click on the button with empty values meaning the already selected files are being wiped out. Then it would be called with the newly selected files.

**Comment by dmanatunga** [comment]
https://jsfiddle.net/cqycqe46/

So this one doesn't work at all and I am not sure why. The main example I had was that I would insert a console.log() into the demo page's Upload function, and it would show the same file name being logged four times. However, if I visit the jsfiddle on the readme, it doesn't seem to have that issue. No idea why this is happening.

**Comment by dmanatunga** [comment]
Sorry, wrong link. http://jsfiddle.net/dmanatunga/cqycqe46/8/.

**Comment by dmanatunga** [comment]
After some experimentation, it seems the issue is with the ngf-multiple. If ngf-multiple is not set, I either get conditions where the drag and drop does not work, or file received multiple times (tried it on DEMO page, with console.log). If ngf-multiple is set, than callback function only called once.

**Comment by danialfarid** [comment]
I would still need a jsfiddle or plunker to show the error you are talking about. it all seems to work fine for me. The demo page uploads the dropped file only once.

**Comment by danialfarid** [comment]
It was a bug in the demo page not the actual plugin code that would make the watch to be called multiple times and upload multiple times, it is fixed now.
