### ISSUE TITLE
Flash fallback positioning incorrect when file input is located within modal

### ISSUE THREAD

**Issue by Quirksmode** [danialfarid/ng-file-upload#924]
Sadly I must support IE9 for this project I am working on, I have managed to get the flash fallback working, but have noticed that the positioning is off due to the file input being contained within a modal. The flash fallback gets prepended to the <body> element, is there a way to adjust this so it prepends to the modal?

I could do this manually, but wanted to first check there is not a clever built in way of fixing it.

**Comment by danialfarid** [comment]
Not sure what you mean by prepend to the modal.
Could you create a jsfiddle.
