### ISSUE TITLE
iOS - Taking a picture to upload is always coming out landscape

### ISSUE THREAD

**Issue by Quirksmode** [danialfarid/ng-file-upload#927]
When using any iOS device, when I use the ngf-capture="'camera'" attribute and take a picture, it doesn't matter what orientation the device is, the picture always comes out landscape, this results in sideways pictures when the orientation is portrait. 

My code is:

    <input type="file" id="formBodyContent_image" accept=".jpg, .png" ngf-select ngf-change="BlockImageCtrl.upload($files)" ngf-multiple="false" ngf-capture="'camera'">

**Comment by danialfarid** [comment]
Add exif support

**Comment by danialfarid** [comment]
https://github.com/danialfarid/ng-file-upload/issues/745

**Comment by jdegger** [comment]
@danialfarid Any clue when this is going to be fixed? We might write our own hotfix for the time being.

**Comment by danialfarid** [comment]
I'll make it higher priority. Hopefully I will get into it by the next week or so, if you like to contribute and submit a PR that would be great. https://github.com/blueimp/JavaScript-Load-Image/blob/master/js/load-image-orientation.js

**Comment by jdegger** [comment]
Unfortunately I don't have time to make a PR but I am very thankful you're willing to make it a higher priority :)!

Cheers

**Comment by danialfarid** [comment]
I believe version 9.1.0 should fix this issue. Could you guys investigate if it is fixed?

**Comment by jdegger** [comment]
Confirmed! Thanks a lot @danialfarid!
