### ISSUE TITLE
Drag&Drop in a list triggers for every item in the list

### ISSUE THREAD

**Issue by burakkilic** [danialfarid/ng-file-upload#929]
Hi;

I have a list of items like in the photo:

![screen shot 2015-08-11 at 22 12 31](https://cloud.githubusercontent.com/assets/123382/9207403/1ca36970-4076-11e5-9a87-bdb2e1df702e.png)

I want to be able to drag and drop the images to the list items. The code is:

    <div class="col-md-3">
            <div data-nodrag  class="col-md-3" id="direct_upload{{node.name.en}}" ngf-drop="onFileSelect(node, $files)" ng-file-drag-over-class="dragOverClass($event)" ng-model="node.image" ng-multiple="false" accept="image/*">
                        <img class="drag-icon" style="width:100%;" src="img/icons/cloud_upload.png">
                        
                        <div class="file" ng-repeat="file in itemImage">
                            <div class="progress progress-striped active">
                                <div class="progress-bar progress-bar-success" style="width: {{file.progress}}%" ng-init="progress=0" role="progressbar"></div>
                            </div>
                        </div>
                    </div>
                    <div ng-show="shop.background" class="preview">
                        <div class="row">
                            <cl-image public-id="{{shop.background}}" class="thumbnail inline" format="jpg">
                                <cl-transformation height="200" width="150" crop="fit" />
                            </cl-image>
                            <button type="file" class="btn btn-danger" ng-file-select ng-multiple="false" accept="image/*" ng-model="itemImage">Change</button>
                        </div>
                    </div>
        </div>

But ngf-drop="onFileSelect(node, $files)" is triggered for every list item. Where am I wrong?

**Comment by danialfarid** [comment]
What do you mean it is triggered for every list item? what is a list item?

**Comment by burakkilic** [comment]
Every row in the screenshot is a list item. If I want to drag and drop an image to "Ara Sıcaklar", 

ngf-drop="onFileSelect(node, $files)" is called for every row.

**Comment by danialfarid** [comment]
Can you create a jsfiddle? The code you have posted here doesn't seem to match the screenshot you have.
