### ISSUE TITLE
Upload is not sending OPTIONS request

### ISSUE THREAD

**Issue by rokerkony** [danialfarid/ng-file-upload#931]
Hi guys,
I see in demo that OPTIONS request for progress are sent. I have same configuration and it's not sending on my side :(

it is sending only POST so I'm not able receive data to show progress...

any idea why it's not working?

I'm using
- Angular 1.4.3
- ng-file-upload 6.0.4

my code:
```js
var uploadPromise = Upload.upload({
    method: 'POST',
    url: apiBaseUrl + 'upload',
    fields: {
        'importMode': vm.form.importMode.id
    },
    file: files[0]
});

uploadPromise.progress(function(evt) {
    vm.fileUploadProgress = parseInt(100.0 * evt.loaded / evt.total);
    $log.debug('progress:', vm.fileUploadProgress);
});
```

```html
<div ngf-select
     accept="text/csv"
     ngf-accept="'text/csv'"
     ngf-multiple="false"
     ngf-change="importCtrl.upload($files)">
    Select file
</div>
```

**Comment by danialfarid** [comment]
OPTIONS is just for CORS requests being sent automatically by the browser, so if your server url is on the same domain as your client then you won't need an OPTIONS request. The progress is being send with the post request.
