### ISSUE TITLE
Upload adding header and footer?

### ISSUE THREAD

**Issue by ThomasMldr** [danialfarid/ng-file-upload#933]
When uploading files through your otherwise very useful library, I found all files where corrupt upon arrival.
It seems the library adds a header and footer on every upload to the binary stream, and I’m not sure why…
I had to strip off the bytes in question in order to maintain the files intact. 
This guy “Capt. Rochefort” wrote a very helpful blogpost on how to fix the problem: http://xombe.com/2014/06/05/angularjs-file-upload-corrupting-files/

So now my question is/are: 
Does this “feature” have a use that I’m missing (which is entirely possible)? Or is it something you may have overlooked?

Anyways, thanks for your useful library, and I’m looking forward to be enlightened!

Greets, 
Thomas Mulder

**Comment by danialfarid** [comment]
The plugin doesn't add anything to the file binary. Could you create a jsfiddle or post your code here?

**Comment by ThomasMldr** [comment]
Actually I think taking a look at the blogpost below would clarify things much more than my code, it's pretty much dedicated to your plugin and these mysterious headers.
http://xombe.com/2014/06/05/angularjs-file-upload-corrupting-files/

**Comment by danialfarid** [comment]
That blog doesn't have any js code. It might be a modification you do before sending the file with the plugin or other plugins that modify xhr requests.

**Comment by danialfarid** [comment]
You know this plugin is being used by so many people and the file is being sent correctly to the server for all of them.

**Comment by ThomasMldr** [comment]
I know, but I found the blogpost quite easily after experiencing the same problems...  And even though I'm fresh from school and have lots to learn, the author appears to know what he's doing, why else would he have a technical blog like that? 
But it's entirely possible that I did something wrong, even though most of the code originates from the examples and jsfiddles found here..

this is the upload button: 
`<div class="btn" ngf-select ng-model="file.new">@IntranetResources.Generic_Upload</div>`

and this the javascript in my controller
```javascript
$scope.uploadFile = function (file) {
            Upload.upload({
                url: "/Umbraco/api/Documents/UploadFile?contentId=" + $routeParams.id + "&fileName=" + file.name,
                file: file
            }).progress(function (evt) {
                var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
                console.log('progress: ' + progressPercentage + '% ' + evt.config.file.name);
            }).success(function (data, status, headers, config) {...}
```

and this is the C# code on the API controller that receives the upload
```c#
[HttpPost]
        public HttpResponseMessage UploadFile(int contentId, string fileName)
        {
            try
            {
                var stream = FixFileContent((StreamContent) Request.Content).Result; 
                //this is where I go to Capt. Rochefort's code to strip off the headers.. So something went wrong before this stage...
...

```

Let me know if you miss anything!

**Comment by danialfarid** [comment]
It might be a proxy or middleware on your server side that adds stuff to the request.
