### ISSUE TITLE
Possible to validate image resolution?

### ISSUE THREAD

**Issue by windmark** [danialfarid/ng-file-upload#934]
The documentation covers being able to validate the file type and size, but in the case of handling images, is it possible to check or restrict what image resolution they have?

I'm currently working with an API on the backend that requires an image with a resolution over a specific width. I also feel that this is a commonly occurring task with images.

Regards,
Marcus Windmark

**Comment by danialfarid** [comment]
Not at the moment but I will add it to the future versions.
For now off the top of my head you can have a hidden image element `<img ngf-src="file">` and onload verify its width and height and show error messages if it is not of a valid resolution.

**Comment by danialfarid** [comment]
Feature is added to version 6.2.0
