### ISSUE TITLE
release 6.1.1 breaks if no `ng-model` attribute present

### ISSUE THREAD

**Issue by schmkr** [danialfarid/ng-file-upload#936]
We're using this library without `ng-model` attribute but with an `ngf-change` attribute defined to handle changes in selected files.

With the release of 6.1.1 , [this line](https://github.com/danialfarid/ng-file-upload/commit/32739690ae5295bd59ec30d0c46ca2bf9e466e94#diff-71257b2ea673e6a11bc86329d6034b33R984) is now causing an error: `Cannot read property '$modelValue' of null`.

Is `ng-model` an required attribute now? The README still shows that is should be able to use without:

    <div class="button" ngf-select ng-model="file">Upload using model $watch</div>
    <div class="button" ngf-select ng-model="files" ngf-multiple="true">Upload multiple using model $watch</div>
    <div class="button" ngf-select ngf-change="upload($file)">Upload on file change</div>
    <div class="button" ngf-select ngf-change="upload($files)" ngf-multiple="true">Upload multiple on file change</div>

**Comment by danialfarid** [comment]
Fixed at 6.1.2

**Comment by schmkr** [comment]
Yep, it's working again, thanks for the quick fix!
