### ISSUE TITLE
File popup window reopens

### ISSUE THREAD

**Issue by windmark** [danialfarid/ng-file-upload#940]
The file popup window is immediately reopening once since updating to the latest 6.2.1 version. The file data seems to be updating correctly for each try, but I have to select each file twice to actually get the popup window to close. This is also the case when pressing cancel.

Best regards,
Marcus Windmark

**Comment by danialfarid** [comment]
What browser?
Can you reproduce it on demo page? can you create a jsfiddle?

**Comment by windmark** [comment]
The problem occurs in both Chrome and Firefox and seems to be caused by ngf-background. I'm trying to set the background of the drop area to be the dropped file. In the migration notes to 6.2.X, you mention changed ngf-default-src and ngf-default-background, but nothing to ngf-background.

See the following jsfiddle: http://jsfiddle.net/mhtvs6ce/

**Comment by danialfarid** [comment]
the fiddle is working for me. It does set the background image.

**Comment by windmark** [comment]
It does indeed set the background image, but as you can notice, the file popup window reopens the first time a file is selected. I've been able to reproduce the problem using my earlier posted jsfiddle in Chrome, Firefox, Edge on both Windows and Ubuntu. This wasn't a problem before 6.2.1.

**Comment by danialfarid** [comment]
Fixed in version 7.0.4.
Thanks for reporting.

**Comment by windmark** [comment]
Perfect! This works like a charm together with the migration notes to 7.x.x.
Thank you for all quick answers!
