### ISSUE TITLE
ng-file-upload is not working?

### ISSUE THREAD

**Issue by gamevnlc** [danialfarid/ng-file-upload#942]
I got some error when set ng-file-upload for a tag.It isn't work.
![capture](https://cloud.githubusercontent.com/assets/2215185/9326168/187f5614-45c2-11e5-8e50-8d8d33d9bc7e.PNG)
When click at camera-button it will display toolbar dropdown menu below .
I set ng-file-upload for "upload image" but it isn't show anything.

if i write ng-file-upload outer it work. Could you tell me why ng-file-upload is not work

Sorry for my English.
Thank you

**Comment by danialfarid** [comment]
As a workaround don't use it as a tag name. Not quiet sure why it is not working but there is obvious workaround it so closing this and I might update the document to not use it as tag if other people report the same issue.
