### ISSUE TITLE
Drag and drop is possible from file select dialog

### ISSUE THREAD

**Issue by zeldigas** [danialfarid/ng-file-upload#943]
Hi 

It's currently possible to drag and drop files from system select file dialog. Is it a bug or a feature? If it's a feature is it possible to turn it off?

How to reproduce:

1. Open https://angular-file-upload.appspot.com/
2. click on the "Select File, Drop file or paste image" location
3. in the opened system file selection get file and drag and drop it on "drag and drop location"

Expected behaviour: drag-n-drop from system dialog is not handled, i.e. ignored
Actual behaviour: file start uploading + i can continue using system file selection dialog to select file. If so then it will replace one that was drag-n-dropped

**Comment by danialfarid** [comment]
There is not much we can do about that the browser popup and drop event all coming from the browser and are browser specific implementation. So there is no way to tell where the drop event comes from.
