### ISSUE TITLE
Angular Bindings not being updated on successful upload.

### ISSUE THREAD

**Issue by mspivak** [danialfarid/ng-file-upload#944]
I'm pretty sure this is not a bug on ng-file-upload, but I wanted to share this here in case anyone run into the same issue or knows what might be going on.

http://stackoverflow.com/questions/32075605/why-is-my-angularjs-binding-not-always-updating-properly

Thanks in advance!
PS: Should I post the actual question or the SO link is fine?

**Comment by danialfarid** [comment]
Closing this since it is already on SO.
