### ISSUE TITLE
Not possible to have both ngf-validate-fn and ngf-validate-async-fn?

### ISSUE THREAD

**Issue by schmkr** [danialfarid/ng-file-upload#945]
I wanted to use both `ngf-validate-async-fn` and `ngf-validate-fn` for validating files, but when `ngf-validate-async-fn` is present, the callback defined in `ngf-validate-fn` never gets called.

Is this by design? Is it not possible to use both attributes at the same time?

**Comment by danialfarid** [comment]
Fixed in 7.0.5, it was being called but the result would be overwritten by validate-async-fn
