### ISSUE TITLE
ngf-change callback gets called twice when validations are invalid

### ISSUE THREAD

**Issue by schmkr** [danialfarid/ng-file-upload#946]
I use ng-file-upload without `ng-model` attribute, but with `ngf-change`. I've also set a the `ngf-max-size` attribute and whenever the validation result in an error, the `ngf-change` callback gets called twice. When everything is valid, the callback gets called only once.

This happens since the 7.0 release.

Is it by design, that the `ngf-change` callback gets called twice?

**Comment by danialfarid** [comment]
Fixed in 7.0.5
