### ISSUE TITLE
Error: 'slice' called on an object that does not implement interface Blob.

### ISSUE THREAD

**Issue by anish274** [danialfarid/ng-file-upload#947]
I am previewing the image on page,
and after clicking on save button I am uploading image + sending http data of other form fields.

The image gets uploaded successfully but when sending http request to save all data, the error occurs.
**"Error: 'slice' called on an object that does not implement interface Blob."**
Tried a lot to solve this not got success.

Please help me on this.

**Upload code:**
```javascript
            Upload.upload({
                url: 'myproject/controller/image_upload',                
                file: file,
                method: 'POST',
                sendFieldsAs: 'form'
            }).progress(function (evt) {
                var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
                console.log('progress: ' + progressPercentage + '% ' + evt.config.file.name);
            }).success(function (data, status, headers, config) {
                console.log('file ' + config.file.name + 'uploaded. Response: ' + data);
            }).error(function (data, status, headers, config) {
                console.log('error status: ' + status);
            }) 
```
**Code to save form data**
```javascript
            $http({
                method: 'POST',
                url: "myproject/controller/get_data",
                data: $.param($scope.store),
                headers: {'Content-Type': 'application/x-www-form-urlencoded'}
            })
```

**Comment by danialfarid** [comment]
So is the error occurs on the Upload.upload function or $http() ? Can you create a jsfiddle?

**Comment by danialfarid** [comment]
It should be fixed in the latest versions.

**Comment by udaybajare** [comment]
Did you get a solution for tis problem? I am facing the same problem while sending Input type="file" value using Ajax. Your help is appriciated.

**Comment by KathyKate** [comment]
Because the used file and the obtained file are not the same type, convert it at the point of use, webupload encapsulates the file twice.
use as `file.source.source`

**Comment by DanroyMwangi** [comment]
How does one convert it?

**Comment by DanroyMwangi** [comment]
Found that you should just add "contentType: false, processData: false," to your ajax request.
Look at this https://stackoverflow.com/questions/19722920/submitting-a-file-with-jquery-ajax-gives-typeerror
