### ISSUE TITLE
File Upload issue in ie9

### ISSUE THREAD

**Issue by hoomersinpsom** [danialfarid/ng-file-upload#948]
When i try to upload something trow the message "Adode Flash Player need to be installed. To check ahead use "FileAPI.hasFlash" in console, flash is instaled and the swf is being loaded, if i go in the js and define FileAPI.hasFlash the file is uploaded fine without errors on ie9 if i define forceLoad: true, html5: false fir debug on chrome and firefox i get de same errors, i am using with FileAPI.hasFlash = true to work properly, thanks :)

**Comment by danialfarid** [comment]
What version of the plugin?

**Comment by hoomersinpsom** [comment]
6.2.0

**Comment by danialfarid** [comment]
Can you try with the latest version

**Comment by hoomersinpsom** [comment]
with the version 7.0.6 i got the same error, the message still the same "Adode Flash Player need to be installed. To check ahead use "FileAPI.hasFlash" :(

**Comment by danialfarid** [comment]
It should be fixed in version 8.0.1

**Comment by adyngom** [comment]
@danialfarid hello :) It seems like it's not fixed in latest version - we are running 9.0.19 and I'm running into the same issue. I'm on a Window 7 IE9. Any thoughts?

**Comment by danialfarid** [comment]
Could you create a jsfiddle?
