### ISSUE TITLE
multiple upload preview - dataUrl duplicated

### ISSUE THREAD

**Issue by LukaszWiktor** [danialfarid/ng-file-upload#950]
I wanted to create a multiple image upload with a preview. The problem is that all files (although different) point to the same dataUrl:
![image](https://cloud.githubusercontent.com/assets/2964543/9370318/a3f99638-46cf-11e5-86d0-9ec69d624b17.png)
As you may guess the result is that preview shows the same image repeated n times.

Here is my html:
```html
<form ng-app="fileUpload" name="form">
    <button class="btn" ngf-select ngf-change="upload($files)"
            ng-model="files" ngf-multiple="true" ngf-max-size="'2M'">
        Add images
    </button>
</form>
<div ng-repeat="file in files">
    <img ngf-src="file" class="thumbnail">
</div>
```

**Comment by danialfarid** [comment]
Fixed in version 7.0.6
