### ISSUE TITLE
Lack of Testing

### ISSUE THREAD

**Issue by whitef0x0** [danialfarid/ng-file-upload#954]
Looking through the test.js it seems like there is a worrying lack of testing (i.e. no tests at all). 

I'm about to start writing some unit tests, but before I do, is there a similar effort underway already that I can join instead of writing spec tests from scratch?

**Comment by danialfarid** [comment]
You are right there in none, it would be appreciated if you could contribute to writing tests.
Submit PRs frequently before going too far for feedbacks, etc. thanks.

**Comment by danialfarid** [comment]
https://github.com/danialfarid/ng-file-upload/issues/701

**Comment by danialfarid** [comment]
@whitef0x0  any news?

**Comment by danialfarid** [comment]
I close this since it's been inactive for a while. If you have worked on it submit a PR.
