### ISSUE TITLE
file.type is undefined when setting ngf-src

### ISSUE THREAD

**Issue by eduacostam** [danialfarid/ng-file-upload#958]
On version 7.0.6 this worked, on version 7.0.9 it doesn't.

So I have this html:
```html
<div ngf-drop ng-model="vm.cover" ngf-multiple="false" class="radio-cover-picture">
	<img ng-show="vm.cover" ngf-src="vm.cover" class="img-responsive">
	<div ng-hide="vm.cover"></div>
	<p>Drop cover picture here (500x500)</p>
</div>
```

When the page is loaded from the server the controller sets `vm.cover` to the url of the already uploaded image. When a user drops a new image into that `div` it changes vm.cover to a `File`.

On version 7.0.6 on page load the img showed the correct image loaded from the given url in `vm.cover`, on latest version it throws an error saying `file.type` is undefined.
I was able to narrow it down to the new `$watch ` statement added to the `ngf-src` directive.

Regards

**Comment by danialfarid** [comment]
Fixed in version 7.0.10

**Comment by jarsj** [comment]
Having the same problem. 
```
		<md-button ngf-select ng-model="locality.profile_picture" ngf-multiple="false">
			<img ngf-src='locality.profile_picture' height='100'/>
		</md-button>
```
This is the Edit form, so initially locality.profile_picture is a valid URL string. On page load I get "file.type is not defined"

**Comment by danialfarid** [comment]
Try to assign the initial url to another model and have `ngf-src="locality.profile_picture || default_pic"`
