### ISSUE TITLE
new validation changes skip validators and allow adding invalid files

### ISSUE THREAD

**Issue by jbarrus** [danialfarid/ng-file-upload#959]
The new changes to validation have a logic error that allows adding files that are invalid.  If multiple files are added at once, some invalid files may pass depending on the order.

See the code block at https://github.com/danialfarid/ng-file-upload/blob/master/src/validate.js#L126
The valid = valid && ... prevents any further validators from running once one has come up invalid (with the exception of the error noted below).

Also, this part https://github.com/danialfarid/ng-file-upload/blob/master/src/validate.js#L118 has an ordering problem - if the last file is valid, then the result is valid even if other files were invalid.

**Comment by danialfarid** [comment]
Thanks for reporting, fix in version 7.0.10
