### ISSUE TITLE
ngf-drop in nested child scope doesn't set ng-model on parent

### ISSUE THREAD

**Issue by yarrumretep** [danialfarid/ng-file-upload#960]
This is easily demonstrated by editing this Plunker:

http://jsfiddle.net/danialfarid/s8kc7wg0/1/

to change this tag:
  ` <div ngf-drop ng-model="files" class="drop-box" 
        ngf-drag-over-class="dragover" ngf-multiple="true" ngf-allow-dir="true"
        accept="image/*,application/pdf">`

to this:
  ` <div ngf-drop ng-model="files" class="drop-box" 
        ngf-drag-over-class="dragover" ngf-multiple="true" ngf-allow-dir="true"
        accept="image/*,application/pdf" ng-if="true">`
       
Granted, this is a nonsense example, but the ng-if causes angular to create a child-scope for that div - which, in turn, causes the ngf-drop directive to write to the "files" variable in that local child-scope, rather than the original $scope that the code is expecting.

In other ng-model cases, isn't it the case that child-scopes are ignored and only the parent isolate-scope in the scope hierarchy is written to?

**Comment by danialfarid** [comment]
Well the directive uses the current scope for that element and it doesn't create a new scope on it's own. But I don't think it should write to the parent scope it may not be desirable. You can use `ng-model="$parent.files"` if you have ng-if or a directive that would create a new child scope.

**Comment by yarrumretep** [comment]
I guess the problem comes that you could have multiple layers of parental
scopes depending on the logic on the DOM above you.  Do other directives
require you to navigate manually to the desired scope?  Would a ng-model on
an <input> with an ng-if on it require $parent?

I was surprised when I added an ng-if on a parent DOM element to
conditionally show the drop zone that the files stopped showing up.  Indeed
they were being attached at a nested scope.

What do you think?  Will you consider a pull request if I submit?

Thank you for this very cool framework!

Best,

Pete

On Saturday, August 22, 2015, Danial Farid <notifications@github.com> wrote:

> Well the directive uses the current scope for that element and it doesn't
> create a new scope on it's own. But I don't think it should write to the
> parent scope it may not be desirable. You can use ng-model="$parent.files"
> if you have ng-if or a directive that would create a new child scope.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danialfarid/ng-file-upload/issues/960#issuecomment-133633747>
> .
>


-- 
-pete
peter m. murray
pete@pmurray.com

**Comment by danialfarid** [comment]
Yea ng-model on input behaves the same:
http://jsfiddle.net/danialfarid/xfdqqtoa/

**Comment by yarrumretep** [comment]
Well, ya - you *can* manually find the parent scope.  This fiddle shows two
<input> tags that are ng-model bound to the same variable - but are in
different scopes (border colors):

https://jsfiddle.net/h3nwnbjg/1/

It seems to me that ng-model should "find" the $scope that is current and
get/set values there, rather than the local DOM scope.  Does that make
sense?

Best,

pete

On Sat, Aug 22, 2015 at 1:28 PM, Danial Farid <notifications@github.com>
wrote:

> Yea ng-model on input behaves the same:
> http://jsfiddle.net/danialfarid/xfdqqtoa/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danialfarid/ng-file-upload/issues/960#issuecomment-133729896>
> .
>



-- 
-pete
peter m. murray
pete@pmurray.com

**Comment by yarrumretep** [comment]
So - this looks to be my misunderstanding.

In this fiddle if you type first into the "Outer" input field, the inner
and outer are referring to the same scope.

Once, however, you type something into the "Inner" input field, it becomes
disconnected from the outer scope.

https://jsfiddle.net/h3nwnbjg/2/

I presume this is by design in Angular - in fact it is documented in the
ng-if documentation (RTFM!).

Go ahead and close this issue as user-error.  I apologize for the
confusion.  Thank you!

Best,

pete

On Sat, Aug 22, 2015 at 6:56 PM, Peter Murray <pete@pmurray.com> wrote:

> Well, ya - you *can* manually find the parent scope.  This fiddle shows
> two <input> tags that are ng-model bound to the same variable - but are in
> different scopes (border colors):
>
> https://jsfiddle.net/h3nwnbjg/1/
>
> It seems to me that ng-model should "find" the $scope that is current and
> get/set values there, rather than the local DOM scope.  Does that make
> sense?
>
> Best,
>
> pete
>
> On Sat, Aug 22, 2015 at 1:28 PM, Danial Farid <notifications@github.com>
> wrote:
>
>> Yea ng-model on input behaves the same:
>> http://jsfiddle.net/danialfarid/xfdqqtoa/
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/danialfarid/ng-file-upload/issues/960#issuecomment-133729896>
>> .
>>
>
>
>
> --
> -pete
> peter m. murray
> pete@pmurray.com
>



-- 
-pete
peter m. murray
pete@pmurray.com

**Comment by yarrumretep** [comment]
Closing due to user error.
