### ISSUE TITLE
ngf-multiple not working for me

### ISSUE THREAD

**Issue by ivantorrellas** [danialfarid/ng-file-upload#961]
I have this code:

    <div class="button" ngf-select ng-model="file0" ngf-multiple="true" accept="image/*">
    <img ng-show="file0" ngf-src="file0"> 

Just like the Usage section describes it... but when I set the `ngf-multiple="true"` attribute my image preview does not show and I get this error:

    TypeError: Cannot read property 'indexOf' of undefined
    at Object.fn (ng-file-upload.js:589)

If I set the attribute to `ngf-multiple="false"` , the preview shows correctly. same as if I remove the attribute from the tag. but I need to be able to select multiple files.

I have update to 7.0.10 version.

Using Chrome Version 44.0.2403.155 (64-bit). OS-X v 10.10.5. Angular 1.4.2.

Thanks.

**Comment by danialfarid** [comment]
It is working for me: http://jsfiddle.net/danialfarid/1myn4b8j/
You need to have file0[0] for ngf-src if you have multiple files.

**Comment by ivantorrellas** [comment]
Oh. Thanks.
