### ISSUE TITLE
Setting pre-populated ng-model file array

### ISSUE THREAD

**Issue by abinashbohidar** [danialfarid/ng-file-upload#962]
Hi,
As per my requirement, My file[] will be pre populated from box. So that user can see the previously uploaded files and update/remove files. I need to find a way to pre-populate the file[]. Could you please provide the way how I can set the values to file[] manually.

**Comment by danialfarid** [comment]
You cannot set the value of the file input programmatically for the security reasons. You can have another scope variable `alreadyUploadedFiles` to keep the list of urls of the uploaded files.
