### ISSUE TITLE
Not able to access uploaded files in the controller

### ISSUE THREAD

**Issue by mukulgupta2507** [danialfarid/ng-file-upload#963]
Hi,

I have posted a detailed issue on SO. Can anyone please tell me if this is expected behavior or am I doing it wrong somewhere ?

http://stackoverflow.com/questions/32190072/not-able-to-access-uploaded-files-in-controller

Thanks,

**Comment by guillaumevincent** [comment]
Look at this js fiddle https://jsfiddle.net/danialfarid/2vq88rfs/12/ describe in the doc.

**Comment by danialfarid** [comment]
Fixed at version 7.0.12
