### ISSUE TITLE
Restrict to image files only

### ISSUE THREAD

**Issue by sprakashg** [danialfarid/ng-file-upload#966]
Hi Team,

The plugin is great. But lately am find hard to customize the upload process. I have to restrict the users to upload only valid image extensions before uploading it to s3.
I tried accept tag but if user wants to upload .html file, it uploads. 
How to do it within plugin itself
I tried the following example 
http://jsfiddle.net/3t50b3fw/

**Comment by danialfarid** [comment]
`accept` is only for select browser's popup filtering. Use `ngf-pattern` or ngf-validate` to validate the file type/pattern or size, etc.

**Comment by sprakashg** [comment]
Cool, I used this 
ngf-pattern="'.xls,.csv,.xlsx'"
The problem is it doesn't work for .xls and .xlsx, it accepts file with .csv extension?

**Comment by sprakashg** [comment]
Do I need to add mime type ?
Like this below?
ngf-pattern="'.xls,.csv,.xlsx, application/vnd.ms-excel, text/csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'"

**Comment by danialfarid** [comment]
You can specify either the mime type or the file extension, both should work. `ngf-pattern="'.xls,.csv,.xlsx'"` works for me.

**Comment by sprakashg** [comment]
This works fine, but if you select for example file ending with .mp3 and then it shows error message "'.xls,.csv,.xlsx'", but if you again select a file ending with ".csv", it doesn't work
