### ISSUE TITLE
Upload.http()'s `data` creates an extra object

### ISSUE THREAD

**Issue by fxck** [danialfarid/ng-file-upload#967]
Whatever I pass to the `data` property of http's config get wrapped in an object with key `0`.. so

```
{
  file: <base64>,
  name: 'foo',
  type: 'bar'
}
```

becomes

```
{
  0: {
     file: <base64>,
     name: 'foo',
     type: 'bar'
  }
}
```

any way around it?

**Comment by danialfarid** [comment]
It works fine for me, could you creaet a jsfiddle.

**Comment by fxck** [comment]
there @danialfarid http://jsbin.com/hofohavuzu/edit?html,js,output

look at request payload

![image](https://cloud.githubusercontent.com/assets/1303561/9497696/8cffa89a-4c16-11e5-8232-5c9b2eb3d246.png)

**Comment by danialfarid** [comment]
`data` has to be only the file for `Upload.http`

**Comment by fxck** [comment]
...ok. How do I add more data to that call then?

**Comment by fxck** [comment]
I also believe it's gonna create that `0` key object even if I only pass that base64 string there.

**Comment by danialfarid** [comment]
Use `Upload.upload` for `Upload.http` the content of the request is the file's binary so you cannot add any other data in the request body, you can have them as url parameters though.

**Comment by fxck** [comment]
Can I upload file as base64 string using `Upload.upload`?

**Comment by danialfarid** [comment]
ok that was a bug in `Upload.http`, fixed at version 7.0.13
Thanks for reporting.

**Comment by danialfarid** [comment]
btw to get the base64 data url of the file you can use `Upload.dataUrl(file, true).then(...)`

**Comment by fxck** [comment]
I tried, it wasn't really working. Firstly I have no idea what `disallowObjectUrl` does, and it also seems to have callback as the second parameter and it does not return a promise.

**Comment by fxck** [comment]
..and that callback returned blob

**Comment by danialfarid** [comment]
Use the latest version and the format I wrote in this post or is in the readme file.
`disallowObjectUrl` must be true to return base64 data url otherwise it would return blob object url.

**Comment by danialfarid** [comment]
It used to have callback instead of promise in older versions now it returns a promise.

**Comment by fxck** [comment]
I could have sworn I was using the latest version. I'll try tomorrow.

**Comment by fxck** [comment]
Alright, `Upload.dataUrl()` seems to be working now. I'm still not sure whether to use `http` or `upload` after this https://github.com/danialfarid/ng-file-upload/commit/596fd71340ce296b028873fce20444467f7f2bf9 

If I use `upload`, it's gonna be encoded as `multipart/form-data`, which shouldn't be required when I'm sending the file as base64 string, right?

---

So the end result I'd like to achieve is a file upload(base64), sent along with some other data as `POST` with working progress and other utility functions.

**Comment by danialfarid** [comment]
Use `Upload.http()`
