### ISSUE TITLE
"Flash not installed" error in IE9 even though it is

### ISSUE THREAD

**Issue by riyunoa** [danialfarid/ng-file-upload#969]
I've added angular-file-upload.shim.js, FileAPI.js and FileAPI.flash.swf, but I don't get the Flash button like I do on the example. 

I've also added the following: 

```
<script>
            //optional need to be loaded before angular-file-upload-shim(.min).js
            FileAPI = {
                debug: true,
                staticPath: '/vendor/ng-file-upload-shim/',
                jsPath: '/vendor/ng-file-upload-shim/'
            }
 </script>
```

Any ideas would be appreciated!

**Comment by danialfarid** [comment]
FileAPI.js and FileAPI.flash.swf would be loaded automatically so won't need to be included. look at your  developer tools network tab and see if those files are being tried to be downloaded.

**Comment by riyunoa** [comment]
Thanks for your quick reply, those files have indeed been successfully downloaded.

**Comment by danialfarid** [comment]
Oh sorry, that error means that flash is not installed on the browser. You can redirect the user to the flash download page.

**Comment by riyunoa** [comment]
Hi again, I found out why I had that problem. I saw one of the older posts had manually included FileAPI.js, so I did that. When that is done, it doesn't do FileAPI.hasFlash = hasFlash(); and so FileAPI.hasFlash is undefined. I removed it like you said and it was executing the part of the code which defines hasFlash.

But then I ran into another issue: 
SCRIPT5007: Unable to get value of the property 'insertBefore': object is null or undefined, FileAPI.min.js, line 5 character 13731

When I changed the following line: 
````
script.setAttribute('src', jsUrl || basePath + 'FileAPI.min.js');
````
to use the non-minified FileAPI.js it works!

**Comment by riyunoa** [comment]
I tested a few times and it looks like sometimes even with FileAPI.js it's giving the same "insertBefore" error as above. Other times it executes the request, but the promise doesn't seem to return. I don't understand why the result is so random, any ideas?

**Comment by danialfarid** [comment]
Could you verify if `document.body` is defined in your developer tool.
Also if you have debugging on it might show you which line has that insertBefore error, if you could find which file/line has the error that would help.

**Comment by riyunoa** [comment]
I've been having trouble reproducing it again. When it occurs again I'll check if document.body exists. Thanks.

**Comment by danialfarid** [comment]
Also make sure you are using the exact FileAPI files that ship with this plugin.
