### ISSUE TITLE
Delete\Remove File

### ISSUE THREAD

**Issue by goniak** [danialfarid/ng-file-upload#971]
Hi,

Is there a way to delete\remove file ?
example: i chose file, there is client side error (maxSize), that ng-messages display, but after i remove it
(i use bootstrap-fileinput, but i can use any other way that will work) the ng-messages is still displayed
and when 
the input file control ng-model="MemberSignUpAttemptModel.Photo" is not updated with, and still has the deleted file, and it sending in to the server 
(ng-click="signUp(MemberSignUpAttemptModel.Photo)").

i think that the problem is that model is not updating, is there a way to solve it?

Regards,
Gonen.

**Comment by danialfarid** [comment]
Could you create a jsfiddle?

**Comment by danialfarid** [comment]
Should be fixed at version 7.0.14

**Comment by ryanhinton** [comment]
I seem to still be having this issue.  I'm troubleshooting to figure out why.  I have an option for the user to delete a file that has yet to be uploaded to the server to save.  I use the `ngf-selected` attribute that called a function and if a user decides to add another file, the deleted file comes back with the newly selected file.
