### ISSUE TITLE
issue with ngf-pattern and accept

### ISSUE THREAD

**Issue by sprakashg** [danialfarid/ng-file-upload#974]
Hi Team,
I have used this code
                        <input type="file" ngf-select ng-model="picFile" name="file" ngf-pattern="'.xls,.csv,.xlsx'" accept=".csv" ngf-max-size="20MB" required class="btn btn-success">
                        <span ng-show="myForm.file.$error.pattern">Allowed formats are {{picFile.$errorParam}}</span>
when clicked on button it shows browser pop up, if I change from .csv to all files and select any other format and click back to .csv file, it doesn't get selected.
Any advise on this will be great help, even adding mime type also doesn't resolve this 

ngf-pattern="'.xls,.csv,.xlsx, application/vnd.ms-excel, text/csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'"

**Comment by danialfarid** [comment]
The browser popup restrictions are controlled by `accept` attribute, what value do you have for accept?

**Comment by sprakashg** [comment]
<input type="file" ngf-select ng-model="picFile" name="file" ngf-pattern="'.xls,.csv,.xlsx'" accept=".csv" ngf-max-size="20MB" required class="btn btn-success">
                        <span ng-show="myForm.file.$error.pattern">Allowed formats are {{picFile.$errorParam}}</span>

When the pop shows, by default it's showing as .csv, but if I change the option to All Files, select some file for example ending with ".mp3" and again select a file ending with ".csv", it's not working

**Comment by danialfarid** [comment]
You gotta change your accept to match the ngf-pattern. As for how the popup file select work it is browser dependent and there is not much we could do about it.
So `accept=".xls,.csv,.xlsx"` or setting the accept to mime types could work for you.

**Comment by sprakashg** [comment]
Its nice way actually, changed the code .
 <input type="file" ngf-select ng-model="picFile" name="file" ngf-pattern="'.xls,.csv,.xlsx'" accept=".xls,.csv,.xlsx" ngf-max-size="20MB" required class="btn btn-success">

 So in pop it shows as custom files. But when you switch to all files, make a invalid selection like .mp3 and again switch to matching pattern like ".csv", it doesn't let me select for upload. So this is browser dependent issue is it?

**Comment by sprakashg** [comment]
Its nice way actually, changed the code .
 <input type="file" ngf-select ng-model="picFile" name="file" ngf-pattern="'.xls,.csv,.xlsx'" accept=".xls,.csv,.xlsx" ngf-max-size="20MB" required class="btn btn-success">

 So in pop it shows as custom files. But when you switch to all files, make a invalid selection like .mp3 and again switch to matching pattern like ".csv", it doesn't let me select for upload. So this is browser dependent issue is it?

**Comment by danialfarid** [comment]
Yea try the mime types instead of extensions might work

**Comment by flavioruben** [comment]
accept="text/csv" works well

**Comment by Till86** [comment]
the recognized mime types can depend on what software is installed on the users machine (browser gets some of it's definitions there), have simular issues right now, pretty tricky so.

**Comment by sri-ni** [comment]
In my case the allowed extensions were .csv and .txt. The following worked for me.
```html
ngf-pattern="'.csv,.txt'"
accept="text/csv, text/plain"
```
