### ISSUE TITLE
file upload crossdomain ie 9

### ISSUE THREAD

**Issue by sylhero** [danialfarid/ng-file-upload#975]
I implemented everything for the old browser like IE9 and make the same call to the server all I get is the crossdomain.xml and there is no actual call to the backend. what's the possible reason for that? I put the crossdomain.xml on the root of my nginx server

**Comment by danialfarid** [comment]
Can you create a jsfiddle hard to tell without seeing your code. Is there any request being sent to the server or network tab?

**Comment by sylhero** [comment]
thanks for replying me!
first, I have all the files that you mentioned

![files](https://cloud.githubusercontent.com/assets/4540917/9530982/2331ce28-4cd1-11e5-8831-4d0ce8eb9f77.PNG)

then here is my html for upload:

<button class="btn btn-sm" data-ngf-select data-ngf-change="vm.upload($files)" data-ngf-multiple="false" >Upload <span data-ng-if="vm.isUploading" class="fa fa-spin fa-circle-o-notch"></span></button>

here is the upload in controller

 function upload(files) {
            vm.closeAlert();
            if (files && files.length > 0) {
                vm.isProcessing = true;
                var file = files[0];
                Upload.upload({
                    url: RosterService.uploadTemplateFilePath(),
                    file: file
                }).success(function(data) {
                    var parsedData = RosterService.parseDetails(data);
                    schedulerConfig(parsedData);
                    getRosterList(data.id, false);
                }).error(function(data) {
                    var reasons = data.cause;
                    if (reasons) {
                        vm.errorMessage = 'Could not upload the template because ' + reasons;
                    } else {
                        vm.errorMessage = 'Could not upload file please try it later';
                    }
                }).finally(function() {
                    vm.isProcessing = false;
                });
            }
        }

here is after I click the upload button

![click](https://cloud.githubusercontent.com/assets/4540917/9531036/8b88f910-4cd1-11e5-9eaf-8f7d2aaaf114.PNG)

then my call ends here. here is my crossdomain.xml

<cross-domain-policy>
<site-control permitted-cross-domain-policies="all"/>
<allow-access-from domain="*" secure="false"/>
<allow-access-from domain="testweb.se"/>
<allow-http-request-headers-from domain="*" headers="*" secure="false"/>
</cross-domain-policy>

any idea?

**Comment by danialfarid** [comment]
It might be `socket io` that interfering with it. Could you remove that dependency and see if it works.
Also you can try to put a breakpoint in the shim file where `send: ` or `oncomplete` is defined to see if the shim is actually being called.
