### ISSUE TITLE
imgur woes

### ISSUE THREAD

**Issue by dsifford** [danialfarid/ng-file-upload#976]
Hi there.

I've spent the last 5 hours attempting to upload an image to imgur and haven't been able to get it. 

Can you PLEASE help me out with this. This is driving me insane.

```javascript
  $scope.uploadImage = function(file) {
      console.log(file);
      var ppp;
      var fileReader = new FileReader();
      fileReader.readAsArrayBuffer(file);
      fileReader.onload = function(e) {
        console.log(e);
        Upload.upload({
            url: 'https://api.imgur.com/3/upload',
            headers: {'Authorization': 'Client-ID [my-client-id]'},
            file: e.target.result
        }).then(function(response) {
            //success;
            ppp = response;
        }, null, function(evt) {
            // $scope.progress[index] = parseInt(100.0 * evt.loaded / evt.total);
            console.log(evt);
        }).then(function() {
          console.log(ppp);
        });
```

**Comment by danialfarid** [comment]
what part is not working? Does it send a request to the server?

**Comment by dsifford** [comment]
I get 400 error codes every time.. I've tried every possible configuration possible and still no luck (including content type headers)

If you can post a full working snippet, I would be eternally grateful.

**Comment by danialfarid** [comment]
Try posting it on stackoverflow since it is related to imgur service and not entirely related to this plugin.
Any error message coming with 400?

**Comment by dsifford** [comment]
Nope, just generic 400 message.

**Comment by danialfarid** [comment]
Please post it on stackoverflow closing this since it doesn't seem to be an issue with the plugin.
