### ISSUE TITLE
S3 URL of uploaded File

### ISSUE THREAD

**Issue by sivailango** [danialfarid/ng-file-upload#977]
How to get the S3 URL of uploaded file from response in Angular JS?

<pre>
Upload.upload({
			        url: url, 
			        method: 'POST',
			        fields : {
				        key: file[i].name,
				        AWSAccessKeyId: 'xxxx',
				        acl: 'private', 
				        policy: $scope.policy,
				        signature: $scope.signature,
				        "Content-Type": file[i].type != '' ? file[i].type : 'application/octet-stream', 
				        filename: file[i].name,
			        },
			        file: file[i],
	      		}).progress(function (evt) {
		            var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
		            console.log('progress: ' + progressPercentage + '% ');
		        }).success(function (data, status, headers, config) {
		            console.log(data);
		            console.log(headers);
		        }).error(function (data, status, headers, config) {
		        });
</pre>

This is my code snippet.

**Comment by sprakashg** [comment]
You can follow the instructions in this link
http://www.cheynewallace.com/uploading-to-s3-with-angularjs/

**Comment by sivailango** [comment]
data returns the empty value, but the upload was success

**Comment by sprakashg** [comment]
yes declare it public 
 ACL: 'public-read'

**Comment by sivailango** [comment]
Still no value in data, can you post sample AWS policy?

**Comment by maghidini** [comment]
having the same problem, I got this response from S3 . This is the response from 
![image](https://cloud.githubusercontent.com/assets/7150038/9718031/75449396-554e-11e5-97ca-a99a1d704f8a.png)

But headers from the success method are empty (I want to use the Location header from s3)

**Comment by danialfarid** [comment]
Use `.then()` instead of `.success()` and see if that would help.
There is not much that this plugin does to the response.
You can put a breakpoint here and see the actual response coming back from angular $http() call:
https://github.com/danialfarid/ng-file-upload/blob/master/dist/ng-file-upload.js#L89
