### ISSUE TITLE
Send array is treated like single file

### ISSUE THREAD

**Issue by NetanelBasal** [danialfarid/ng-file-upload#979]
I have three file uploads buttons, when someone choose file i push the file to an array and after he clicks on submit i send the files to my rails server, but the problem is that in my server i see one file and not the array of files.

```html
           <input type="file" name="file" ngf-select="sc.pushFile($file)">
           <input type="file" name="file" ngf-select="sc.pushFile($file)">
           <input type="file" name="file" ngf-select="sc.pushFile($file)">
```

Controller:
```javascript

  pushFile( file ) {
     this.files.push(file);
  }

 submit() {
    this.myService.updateAction(this.files);
 }

```

```javascript
 updateAction(files) {
  this.Upload.upload({
          url   :  url,
          fields: { 'perform': 'submit' },
          method: 'PUT',
          file  : files
        }).progress(function( evt ) {
          var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
          console.log('progress: ' + progressPercentage + '% ' + evt.config.file.name);
        }).success(function( data, status, headers, config ) {
          console.log('file ' + config.file.name + 'uploaded. Response: ' + data);
        }).error(function( data, status, headers, config ) {
          console.log('error status: ' + status);
        })
}
```

**Comment by danialfarid** [comment]
How the request on the browsers network tab look like? Does it have all the files, if it does then it is a server issue.

**Comment by NetanelBasal** [comment]
Yes. But its seems like the files are not send as array. Its seems like the second file is overrding the first one for some reason.

**Comment by danialfarid** [comment]
You can set different names using `fileFormDataName` option.

**Comment by NetanelBasal** [comment]
But i am sending all the files in one request..how can i use what u suggest? Can you give small example please?

**Comment by danialfarid** [comment]
There is an explanation for it in the readme file and some sample in the issues and wiki if you search for it.

**Comment by danialfarid** [comment]
I would suggest to have `ngf-select ng-model="file1"`instead ngf-select with function and send the files like this:
`Upload.upload({..., file: {`files[0]`: file1, `files[1]': file2, ...}})
