### ISSUE TITLE
Selected file is missing in ng-model

### ISSUE THREAD

**Issue by andidev** [danialfarid/ng-file-upload#980]
The selected file should be bound to the ng-model according to the docs:
```
ng-model="myFiles" // binds the selected file or files to the scope model
                   // could be an array or single file depending on ngf-multiple and ngf-keep values.
```

however I only get the errors in the ng-model. 
E.g. 
```html
<button type="file" ngf-select ngf-min-size="6000" ngf-max-size="10000" ng-model="one.imageNgf">
    Add image
</button>
<pre>{{one.imageNgf}}</pre>
```

does output `{}` when a file is successfully selected and e.g. `{"$error":"maxSize","$errorParam":10000}` when a file larger then max size is selected. Should't it also output the info about the selected file?

using latest version 7.0.15

**Comment by danialfarid** [comment]
It's just console.out that doesn't show it. It does have the selected file info.

**Comment by andidev** [comment]
Okey a bit confusing, thanx!
