### ISSUE TITLE
ipad mini upload error with multiple drag&drop areas

### ISSUE THREAD

**Issue by mmswi** [danialfarid/ng-file-upload#981]
Hello,

I have multiple drag&drop areas as below:

Please note the div has a flip animation done in CSS, on hover.

<div class="row">
            <div class="col-xs-5">
                <div class="box-flip-container horizontal dimension320x50">
                    <div class="flipper height-25" ngf-drop ngf-select ngf-change="upload($files, '320x50')" ngf-multiple="false" ngf-allow-dir="false" accept="image/*" ngf-drag-over-class="dragover">
                        <div class="banner-box flip-front">
                            <div class="sponsor-banner-text relative-box height-25">320x50
                                <img ngf-src="banners.medium2" ngf-background="banners.medium2" alt="" class="flip-img height-25" ng-if="banners.medium2">
                            </div>

                        </div>
                        
                        <div class="flip-back horizontal banner-box sponsor-banner-text height-25" ng-class="{'app-box-shadow': expandText320}">
                            <span ng-class="{'hidden': expandText320}">back flip</span><span ng-class="{'hidden': !expandText320}">lorem ipsum lorem lorem ipsum lorem ipsum lorem ipsum</span>

                        </div>
                        
                        <div ngf-no-file-drop>File Drag/Drop is not supported for this browser</div>
                    </div>
                    
                    <a href="" class="default-btn more-info-plus" ng-click="expandText320 = !expandText320"><i class="fa" ng-class="{'fa-minus-square':expandText320, 'fa-plus-square': !expandText320}"></i></a>
                </div>
                
            </div>
            

            <div class="col-xs-2 no-pad-left-right">
                <div class="box-flip-container horizontal dimension120x60">
                    <div class="flipper height-25" ngf-drop ngf-select ngf-change="upload($files, '120x60')" ngf-drag-over-class="dragover" ngf-multiple="false" ngf-allow-dir="false" accept="image/*">
                        <div class="banner-box flip-front">
                            <div class="sponsor-banner-text relative-box height-25">120x60
                                <img ngf-src="banners.small1" ngf-background="banners.small1" alt="" class="flip-img height-25" ng-if="banners.small1">
                            </div>
                        </div>
                        
                        <div class="flip-back horizontal banner-box sponsor-banner-text height-25" ng-class="{'app-box-shadow': expandText12060}"><span ng-class="{'hidden': expandText12060}">back flip</span><span ng-class="{'hidden': !expandText12060}">lorem ipsum lorem ipsum lorem ipsum</span>
                        </div>
                        
                    </div>
                    
                    <div ngf-no-file-drop>File Drag/Drop is not supported for this browser</div>
                    <a href="" class="default-btn more-info-plus" ng-click="expandText12060 = !expandText12060"><i class="fa" ng-class="{'fa-minus-square':expandText12060, 'fa-plus-square': !expandText12060}"></i></a>
                </div>
                
            </div>
            

            <div class="col-xs-5">
                <div class="box-flip-container horizontal dimension320x50 float-right-medium">
                    <div class="flipper height-25" ngf-drop ngf-select ngf-change="upload($files, '300x50')" ngf-drag-over-class="dragover" ngf-multiple="false" ngf-allow-dir="false" accept="image/*">
                        <div class="banner-box flip-front">
                            <div class="relative-box sponsor-banner-text height-25">300x50
                                <img ngf-src="banners.medium1" ngf-background="banners.medium1" alt="" class="flip-img height-25" ng-if="banners.medium1">
                            </div>
                        </div>
                        
                        <div class="flip-back horizontal banner-box sponsor-banner-text height-25" ng-class="{'app-box-shadow': expandText300}"><span ng-class="{'hidden': expandText300}">back flip</span><span ng-class="{'hidden': !expandText300}">lorem ipsum lorem ipsum lorem ipsum</span>
                        </div>
                        
                    </div>
                    
                    <div ngf-no-file-drop>File Drag/Drop is not supported for this browser</div>
                    <a href="" class="default-btn more-info-plus" ng-click="expandText300 = !expandText300"><i class="fa" ng-class="{'fa-minus-square':expandText300, 'fa-plus-square': !expandText300}"></i></a>
                </div>
                
            </div>
            

        </div>
        

CSS:

/*********************
* flip animation
*********************/

.flipper {
    position: relative;
    padding-bottom: 20px;
    margin-top: 10px;
    width: 100%;
    text-align: center;
    cursor: pointer;
    &.dragover {
        outline: 2px dashed $active-link-color;
    }
}

.flip-front,
.flip-back {
    @include transition-property(transform);
    @include transition-duration(0.4s);
    @include transition-timing-function(ease-in);
    -webkit-backface-visibility: hidden;
    backface-visibility: hidden;
    word-wrap: break-word;
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    min-height: 100%;
    padding-left: 5px;
    padding-right: 5px;
}

.flip-back {
    z-index: 2;
    &.horizontal {
        @include transform(rotateY(-180deg));
    }
    &.vertical {
        @include transform(rotateX(-180deg));
    }
}

In iPad mini/Safari, if I upload on one of the areas, the file uploads. BUT if I click on another area and choose a photo, the previous area uploads again. I have to click again on the new area to be able to upload the file where I want. I have to double click on the new area in order to have the file upload on that area, or sometimes I have to click multiple times.

In iPad mini/Chrome: I need to upload 2 times the photo on the same area so you can see it. If you upload it once, it doesn't show. 

Could you please advise if this is a plugin error or is it something in my code?

Thank you and best regards,
Mihai

**Comment by danialfarid** [comment]
Can you create a jsfiddle?

**Comment by danialfarid** [comment]
What version of the plugin are you using? Upgrade to the latest.
