### ISSUE TITLE
Batarang Chrome Plugin - TypeError: Cannot read property 'exp' of undefined

### ISSUE THREAD

**Issue by badbod** [danialfarid/ng-file-upload#982]
I have used this previously and all worked well. Now I cannoit get it working.

using the latest version as of date of this post, as soon as I open the page with the <input type=file etc I get the error 'TypeError: Cannot read property 'exp' of undefined'

let me know if you need any more info

**Comment by danialfarid** [comment]
Create a jsfiddle or your code.

**Comment by SlippySken** [comment]
Mh, I got the same error with Chrome (Version 45.0.2454.85 m). In Firefox everything is fine. On other machines with the same Chrome Version everything is fine too. I have no idea what is different to my machine, but previously everything worked well :D.

**Comment by badbod** [comment]
Hi,
 I removed the chrome extension 'Batarang' and all was fine..  DOH!!

So if you have that, or the other one 'based on Batarang'   then I think removing it will solve the problem.

**Comment by SlippySken** [comment]
Ha!... that's right :D. Everything is fine now.
Thanks :)

**Comment by alatzl** [comment]
Has anyone determined why using batarang causes this issue with ng-file-upload?

**Comment by pbassut** [comment]
+1. Disabled batarang and it worked well.

**Comment by dflourusso** [comment]
+1. Disabled batarang and it worked well too.

**Comment by ivan-yin** [comment]
+1 Disabled batarang and it worked well. thanks

**Comment by migaber** [comment]
+1

**Comment by badbod** [comment]
@danialfarid

I appreciate your diligence. However, you have given no explanation. Is this a bug in Batarang ?  Or is it  an issue with your (excellent)  plugin?  I surmise your plugin does have an issue, as the latest version using your examples gives a 'undefined' error in  'resp.config.data.file.name' . No biggie, I rem them out and it works well, but......   :)


Regards
BaDboD

**Comment by badbod** [comment]
@danialfarid

Where is your 'donate' link? You deserve it. Your plugin is now a staple for all my projects requiring image uploads.

Regards
BaDboD

**Comment by danialfarid** [comment]
@badbod 
I wasn't able to reproduce the error by installing Batarang on Chrome and since this is a minor issue don't think it worth putting too much time on it since you can just disable the plugin.
If you can provide reproducible steps I will have a look.

For the error could you create a separate issue explaining which example you are talking about.

Thanks, donation links are at the top of the the main github page https://github.com/danialfarid/ng-file-upload

**Comment by badbod** [comment]
@danialfarid
tricky one, I didn't try using Batarang in Chrome on Linux. Swapping between the two, and I think I only saw the error in Win ?  Maybe others could confirm if this a Win only? I found Batarang somewhat useless anyway. Kinda forgot it was there until I removed it and a problem was fixed.

The other problem, could be how I handle scope. I will do as you suggest on that as I may well not be passing file. 

Regards
BaDboD

**Comment by badbod** [comment]
ahh,  ok

evt.config.data.file.name  
and
resp.config.data.file.name 

in both cases file.name is undefined, 

otherwise both work as expected.

**Comment by danialfarid** [comment]
What example are you referring to? Could you post the link

**Comment by danialfarid** [comment]
What example are you referring to? Could you post the link

**Comment by badbod** [comment]
so this is a different issue. Not important for me. I will see if I can make a new issue with examples (using your examples)  :-)   

How do I close this issue as resolved?

Regards
 BaDboD

**Comment by badbod** [comment]
the only things that don't work are the data.file.name.  The rest is fine. progress everything

**Comment by badbod** [comment]
but this is off topic,  I will open a new thread.

**Comment by danialfarid** [comment]
It should work the same way: see the jsfiddle sample on readme using the same syntax:  http://jsfiddle.net/danialfarid/s8kc7wg0/400/

**Comment by badbod** [comment]
the fiddle works. same browser, so not that.  Yet copy paste of your example always gives me a not defined error on the data.file.name.  Anyway, Ill make a new issue when I can work out why your plugin works perfectly except for this file.name thing.

Regards
BaDboD

**Comment by timmyrosen** [comment]
This also happens to me, when I have Batarang activated.

It only happens when I'm using the ngf-select attribute. The ngf-drop works fine.

Here is my button:
```
<md-button
        class="md-raised"
        ngf-max-files="10"
        ngf-multiple="true"
        ngf-select="rvm.uploader.choosenFiles($files)"
        ngf-pattern="'image/*'"
        ngf-capture="'camera'"
        ng-disabled="rvm.isUploading">Choose files</md-button>
```

Nothing special or fancy. I've tried removing all attributes except the ngf-select and it still doesn't work. Don't know if this helps or not, but as you said earlier, it's not really a big problem as I can just disable batarang. Thanks for an awesome plugin anyway!

**Comment by rocifier** [comment]
I just fixed this here, sorry no patch file: https://github.com/danialfarid/ng-file-upload/issues/1641

**Comment by NEbere** [comment]
Removed the Batarang extension and error was gone..
