### ISSUE TITLE
file upload not working in Ionics

### ISSUE THREAD

**Issue by chkm8** [danialfarid/ng-file-upload#984]
Hi, im using this library for my ionic application to upload multiple files but I cant make it work. In my PHP backend, I get empty response of $_FILES.

Ive created a question in Stackoverflow, hoping you could check it out.
http://stackoverflow.com/questions/32336171/ng-file-upload-not-uploading-in-ionics

thanks.

**Comment by dansanti** [comment]
i thinks, js never send file, i also use ionic , and on web version works fine, but on android not ,
https://github.com/danialfarid/ng-file-upload/issues/1001

**Comment by danialfarid** [comment]
Could you create a jsfiddle to show that it is working on web but not android? I could debug it that way.

**Comment by dansanti** [comment]
@chkm8 add on terminal : cordova plugin add cordova-plugin-file
maybe it's permissions problem, or this plugin complement native file api
