### ISSUE TITLE
Removing Image from model (array of images)

### ISSUE THREAD

**Issue by Squeezya** [danialfarid/ng-file-upload#985]
Hello,

If i want to upload multiple images and I DON'T want to re-choose all my images, i should be able to add and remove images as i please, in that fiddle all images will be removed when you are going to chose another image, but my problem is the following:
When i choose an image with error: for example, greater than 100KB, it shows me that that image has a bigger size that it should, but as i click the remove button of that Image, the error of the form does NOT disappear, i would like to know if there is a way of doing what I want.

Consider this fiddle:
http://jsfiddle.net/1m6fn6re/70/

Do the following to reproduce in the fiddle: click choose a file and select a file that is smaller than 100KB and a image that is bigger than 100KB, then remove the image with error in the list (button rem after the: {"$error":"maxSize","$errorParam":"100KB"} ), insert a username just to remove the error and see that the form has errors.

THE OPTIMAL case: put a username, and a valid image, see that the form has no errors.

**Comment by danialfarid** [comment]
The problem is that removing an element with splice does not trigger a model change on ngModelController since the object is still the same.
If you clone the array of files and put it back in the files it would work:
http://jsfiddle.net/1m6fn6re/72/

**Comment by Squeezya** [comment]
Omg thank you, i will try it on my code first thing tomorrow, thank you very much :)

**Comment by danialfarid** [comment]
btw you can use `ngf-keep` if you want the files to be added to the model as they are selected instead of wiping them out on each select.

**Comment by Squeezya** [comment]
oh ok, thanks :+1:  will do

**Comment by Squeezya** [comment]
ngf-keep does not work properly for me because user can add images, but then he will be able to edit them, and I can't put the images back on the model after refresh (or can I?)
