### ISSUE TITLE
Drag and drop not working on IE9

### ISSUE THREAD

**Issue by flyawaychen** [danialfarid/ng-file-upload#987]
Drag and drop does not working on IE9 

I'm using modern IE IE9 virtual machine. Even the demo page drag and drop is not working on it.

The progress is also not working on IE9 but works on everything else.

However, the flash loads and the upload works.

Can anybody verify it?

Below is the code I used.

                   <a class="upload-buttons form-group"                           
                             data-ngf-select=""                                    
                             data-ngf-drop=""                                      
                             data-ng-model="files"                                 
                             data-ng-model-rejected="rejFiles"                     
                             data-ngf-multiple="true"                              
                             data-ngf-accept="'image/*,audio/*,video/*,application/msword,application/pdf,application/postscript,application/rtf,application/vnd.ms-excel,application/zip,application/x-rar-compressed,text/plain'"
                             accept="image/*,audio/*,video/*,application/msword,application/pdf,application/postscript,application/rtf,application/vnd.ms-excel,application/zip,application/x-rar-    compressed,text/plain"
                             data-ngf-max-size='MAX_FILE_SIZE'                     
                             data-ng-disabled="disabled"                           
                             data-ngf-capture="'camera'"                           
                             data-ngf-drag-over-class="{accept:'dragover', reject:'dragover-err', delay:100}" 
                             data-ngf-allow-dir="allowDir"                         
                             data-ngf-drop-available="dropAvailable"               
                             data-ngf-change="handleFileChange()">                 
                        <img src="/images/upload_img.png">
                        Drag and drop files here or                                
                        <span class="browse"> browse</span> to upload              
                    </a>

**Comment by danialfarid** [comment]
Drag and drop file is not supported in IE9.

**Comment by flyawaychen** [comment]
Ahh I just realize this... it's nativley not supported.
