### ISSUE TITLE
Fire an event when duplicate file is found

### ISSUE THREAD

**Issue by cezarykluczynski** [danialfarid/ng-file-upload#989]
Now, whenever a duplicate file is found, it's just filtered out silently, and not added to model.

Could an event be fired for every file that is not unique, so user can be informed that he picked a duplicate? Will pull request be accepted for this?

**Comment by danialfarid** [comment]
Why don't you want the user to select the same file?

**Comment by danialfarid** [comment]
Are you using ngf-keep?

**Comment by cezarykluczynski** [comment]
I'm using ngf-keep and ngf-keep-distinct, both set to true.

My scenario is not to allow users to upload one file multiple times, but rather to know whether this happen, and show some feedback. Currently, when a user selects a file that's already been selected, nothing happens. I would like to be able to show some message to user, explaining what he did wrong, and why his file was not added, despite being selected from disk.

I believe it somewhere around here https://github.com/danialfarid/ng-file-upload/blob/a3ae72853057e1c4c03e7cfa075f2a320fa5c93a/src/model.js#L63 where checkup happens, and duplicate files are filtered out. I would propose something like

```
 ngf-duplicate-found="someCallback(original, duplicate)"
```

to handle this scenario, so an optional callback can be defined for giving feedback to user.

**Comment by danialfarid** [comment]
I see.
I would make ngf-keep and ngf-keep-distinct to accept a function like 
`ngf-keep="newFiles($files)"` `ngf-keep-distinct="duplicateFiles($files)"`.
PR is welcome but keep the changes to the minimum required.

**Comment by danialfarid** [comment]
Added feature to 7.3.0.
You can access new files and uplicate files with `ngf-select or ngf-drop or ngf-change="selected($files, $newFiles, $duplicateFiles)"`
