### ISSUE TITLE
Drag and drop files with selenium causes classes to be removed from drop target

### ISSUE THREAD

**Issue by mpetrovic** [danialfarid/ng-file-upload#990]
I'm dropping files onto an ngf-file-drop element through Selenium with the following script:
```javascript
        var inputs = $inputStr;
        e = document.createEvent("HTMLEvents");
        e.initEvent('drop', true, true);
        e.dataTransfer = {
          files : []
        };
        for (var i = 0; i < inputs.length; i++) {
          e.dataTransfer.files.push(jQuery('#'+inputs[i]).get(0).files[0]);
        }
        e.dataTransfer.files.item = function (i) {
          return this[i];
        }
        var result = document.evaluate("$target", document, null, XPathResult.ORDERED_NODE_ITERATOR_TYPE, null);
        var elem = result.iterateNext();
        elem.dispatchEvent(e);
```

$inputStr is a php variable which is a JSON array of ids for input elements, which I've previously added files to. 
$target is the XPath to the ngf-file-drop element I want to drop files onto. 

When I run the test, everything goes well, except any classes on the ngf-file-drop element are removed. A bit of sleuthing found that this is because in [drop.js Line 101](https://github.com/danialfarid/ng-file-upload/blob/master/src/drop.js#L101), actualDragOverClass is undefined. 

I'm not in a position to see if the latest version solves this problem, but eyeballing the code suggests it does not.

**Comment by danialfarid** [comment]
Fixed in version 7.3.0
