### ISSUE TITLE
ngf-select being triggered twice if same button is used

### ISSUE THREAD

**Issue by brunomperes** [danialfarid/ng-file-upload#992]
Hi, firstly thanks for this awesome directive :D

I am using the `ngf-select` to trigger my own upload (I'm doing a presigned url post to AWS S3, is it supported?) reusing the same button to upload various times, if the user wants so.

But the thing is, the first time I click and perform the upload the `ngf-select` is triggered fine with a `change` event, then the second time I click on the upload button the ngf-select is triggered with an event `click`.

Is it the expected behaviour? Should I do any sort of cleaning on my `$file` object?

**Comment by brunomperes** [comment]
I see that on the [fiddle at README](http://jsfiddle.net/danialfarid/0mz6ff9o/13/) there is a checking `if (site && !site.error)` which fixed my issue, though I am not sure if that is a bug or not.

**Comment by danialfarid** [comment]
That is expected, when you click on the upload it clears out the previous value so there is a change and ngf-select is called with empty value.
