### ISSUE TITLE
firing upload event before selecting a file 

### ISSUE THREAD

**Issue by ashiefk** [danialfarid/ng-file-upload#998]
<button class="btn btn-lg darkBack" ngf-select="upload($file)" ng-model="profile.image" name="profile_image" ngf-pattern="'image/*" accept="image/*" ngf-max-size="2MB" ngf-min-height="200" ngf-min-width="200">Upload Photo</button>

$scope.upload = function (file) {
	        Upload.upload({
	            url: '/upload',
	            fields: fields,
	            file: file
	        }).progress(function (evt) {
	            var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
	            console.log('progress: ' + progressPercentage + '% ' + evt.config.file.name);
	        }).success(function (data, status, headers, config) {
	            console.log('file ' + config.file.name + 'uploaded. Response: ' + data);
	        }).error(function (data, status, headers, config) {
	            console.log('error status: ' + status);
	        })
	    };

steps to reproduce:
1. click on upload button selects a file
2. select a file and upload(uploads successfully)
3. click on upload button again (don't refresh the page)
4. dont select a file check the call (it fires that ajax call before selecting the file)

Please check this issue....any help will be appreciated....let me know if i am doing anything wrong..
Thanks

**Comment by Droritos** [comment]
:+1: Having the same exact issue and was just about to post an issue

**Comment by ashiefk** [comment]
@Droritos i found a quick solution just check whether file exists it will call only when user selects 
 $scope.upload = function (file) {
       if(file) {
             //upload code

        }
}

it should update in document as well

**Comment by Droritos** [comment]
Yep, that did the trick. 
Thank you, @ashiefk !

**Comment by danialfarid** [comment]
That is intended. When you click on the button it will clear the old values first so the ngf-select and ngf-change functions will be called with empty value.

**Comment by ashiefk** [comment]
my point was it should call only when a file is selected not when the file manager is opened...

**Comment by danialfarid** [comment]
It is being called whenever the model value or input file value is changed. Since there is no cross browser way to know when the user cancels the popup file selector, the value of the file will be set to empt whenever you click on the upload button if there is a previous value. So `if (file)` should work for you and would let anyone who want to have special handling upon value of the file being cleared to receive the event.

**Comment by MrAtheist** [comment]
In addition to ngf-select being called beforehand, I also notice that the ```files``` for this particular call are carried over from the last select. So the files are duplicated in the model (even though I have set keep="distinct") before I select another files.

**Comment by danialfarid** [comment]
That is intended, when you click on select is like selecting no file which in case you have ngf-keep it will be the same set of files that were there before. You can check the $newFiles to make sure if there is any new files added.

**Comment by brianfeister** [comment]
I think this is similar to the issue I'm describing over on https://github.com/danialfarid/ng-file-upload/issues/460, for me, even with `ngf-keep` it still fires a change event when the dialog is opened, which seems wrong to me.

**Comment by danialfarid** [comment]
Should be fixed at 9.0.18. if ngf-keep is set and there is no new file it would not call the ngf-change or update model.
